//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 01:16:22 PM EST 
//


package com.honda.galc.client.teamleader.qi.stationconfig.clonestation.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.honda.galc.client.teamleader.qi.stationconfig.clonestation.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.honda.galc.client.teamleader.qi.stationconfig.clonestation.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QicsEntryStationConfigurationXmlDto }
     * 
     */
    public QicsEntryStationConfigurationXmlDto createQicsEntryStationConfigurationXmlDto() {
        return new QicsEntryStationConfigurationXmlDto();
    }

    /**
     * Create an instance of {@link QiStationConfigurationXmlDto }
     * 
     */
    public QiStationConfigurationXmlDto createQiStationConfigurationXmlDto() {
        return new QiStationConfigurationXmlDto();
    }

    /**
     * Create an instance of {@link QiStationEntryDepartmentXmlDto }
     * 
     */
    public QiStationEntryDepartmentXmlDto createQiStationEntryDepartmentXmlDto() {
        return new QiStationEntryDepartmentXmlDto();
    }

    /**
     * Create an instance of {@link QiStationEntryScreenXmlDto }
     * 
     */
    public QiStationEntryScreenXmlDto createQiStationEntryScreenXmlDto() {
        return new QiStationEntryScreenXmlDto();
    }

    /**
     * Create an instance of {@link QiStationPreviousDefectXmlDto }
     * 
     */
    public QiStationPreviousDefectXmlDto createQiStationPreviousDefectXmlDto() {
        return new QiStationPreviousDefectXmlDto();
    }

    /**
     * Create an instance of {@link QiStationResponsibilityXmlDto }
     * 
     */
    public QiStationResponsibilityXmlDto createQiStationResponsibilityXmlDto() {
        return new QiStationResponsibilityXmlDto();
    }

    /**
     * Create an instance of {@link QiStationWriteUpDepartmentXmlDto }
     * 
     */
    public QiStationWriteUpDepartmentXmlDto createQiStationWriteUpDepartmentXmlDto() {
        return new QiStationWriteUpDepartmentXmlDto();
    }

    /**
     * Create an instance of {@link QiStationUpcPartXmlDto }
     * 
     */
    public QiStationUpcPartXmlDto createQiStationUpcPartXmlDto() {
        return new QiStationUpcPartXmlDto();
    }

}
