//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 01:16:22 PM EST 
//


package com.honda.galc.client.teamleader.qi.stationconfig.clonestation.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processPointId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="division" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="site" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qiStationConfigurationXmlDto" type="{}QiStationConfigurationXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationEntryDepartmentXmlDto" type="{}QiStationEntryDepartmentXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationEntryScreenXmlDto" type="{}QiStationEntryScreenXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationPreviousDefectXmlDto" type="{}QiStationPreviousDefectXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationResponsibilityXmlDto" type="{}QiStationResponsibilityXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationWriteUpDepartmentXmlDto" type="{}QiStationWriteUpDepartmentXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="qiStationUpcPartXmlDto" type="{}QiStationUpcPartXmlDto" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processPointId",
    "division",
    "plant",
    "site",
    "qiStationConfigurationXmlDto",
    "qiStationEntryDepartmentXmlDto",
    "qiStationEntryScreenXmlDto",
    "qiStationPreviousDefectXmlDto",
    "qiStationResponsibilityXmlDto",
    "qiStationWriteUpDepartmentXmlDto",
    "qiStationUpcPartXmlDto"
})
@XmlRootElement(name = "QicsEntryStationConfigurationXmlDto")
public class QicsEntryStationConfigurationXmlDto {

    @XmlElement(required = true)
    protected String processPointId;
    @XmlElement(required = true)
    protected String division;
    @XmlElement(required = true)
    protected String plant;
    @XmlElement(required = true)
    protected String site;
    protected List<QiStationConfigurationXmlDto> qiStationConfigurationXmlDto;
    protected List<QiStationEntryDepartmentXmlDto> qiStationEntryDepartmentXmlDto;
    protected List<QiStationEntryScreenXmlDto> qiStationEntryScreenXmlDto;
    protected List<QiStationPreviousDefectXmlDto> qiStationPreviousDefectXmlDto;
    protected List<QiStationResponsibilityXmlDto> qiStationResponsibilityXmlDto;
    protected List<QiStationWriteUpDepartmentXmlDto> qiStationWriteUpDepartmentXmlDto;
    protected List<QiStationUpcPartXmlDto> qiStationUpcPartXmlDto;

    /**
     * Gets the value of the processPointId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessPointId() {
        return processPointId;
    }

    /**
     * Sets the value of the processPointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessPointId(String value) {
        this.processPointId = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlant() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlant(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSite(String value) {
        this.site = value;
    }

    /**
     * Gets the value of the qiStationConfigurationXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationConfigurationXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationConfigurationXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationConfigurationXmlDto }
     * 
     * 
     */
    public List<QiStationConfigurationXmlDto> getQiStationConfigurationXmlDto() {
        if (qiStationConfigurationXmlDto == null) {
            qiStationConfigurationXmlDto = new ArrayList<QiStationConfigurationXmlDto>();
        }
        return this.qiStationConfigurationXmlDto;
    }

    /**
     * Gets the value of the qiStationEntryDepartmentXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationEntryDepartmentXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationEntryDepartmentXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationEntryDepartmentXmlDto }
     * 
     * 
     */
    public List<QiStationEntryDepartmentXmlDto> getQiStationEntryDepartmentXmlDto() {
        if (qiStationEntryDepartmentXmlDto == null) {
            qiStationEntryDepartmentXmlDto = new ArrayList<QiStationEntryDepartmentXmlDto>();
        }
        return this.qiStationEntryDepartmentXmlDto;
    }

    /**
     * Gets the value of the qiStationEntryScreenXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationEntryScreenXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationEntryScreenXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationEntryScreenXmlDto }
     * 
     * 
     */
    public List<QiStationEntryScreenXmlDto> getQiStationEntryScreenXmlDto() {
        if (qiStationEntryScreenXmlDto == null) {
            qiStationEntryScreenXmlDto = new ArrayList<QiStationEntryScreenXmlDto>();
        }
        return this.qiStationEntryScreenXmlDto;
    }

    /**
     * Gets the value of the qiStationPreviousDefectXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationPreviousDefectXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationPreviousDefectXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationPreviousDefectXmlDto }
     * 
     * 
     */
    public List<QiStationPreviousDefectXmlDto> getQiStationPreviousDefectXmlDto() {
        if (qiStationPreviousDefectXmlDto == null) {
            qiStationPreviousDefectXmlDto = new ArrayList<QiStationPreviousDefectXmlDto>();
        }
        return this.qiStationPreviousDefectXmlDto;
    }

    /**
     * Gets the value of the qiStationResponsibilityXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationResponsibilityXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationResponsibilityXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationResponsibilityXmlDto }
     * 
     * 
     */
    public List<QiStationResponsibilityXmlDto> getQiStationResponsibilityXmlDto() {
        if (qiStationResponsibilityXmlDto == null) {
            qiStationResponsibilityXmlDto = new ArrayList<QiStationResponsibilityXmlDto>();
        }
        return this.qiStationResponsibilityXmlDto;
    }

    /**
     * Gets the value of the qiStationWriteUpDepartmentXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationWriteUpDepartmentXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationWriteUpDepartmentXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationWriteUpDepartmentXmlDto }
     * 
     * 
     */
    public List<QiStationWriteUpDepartmentXmlDto> getQiStationWriteUpDepartmentXmlDto() {
        if (qiStationWriteUpDepartmentXmlDto == null) {
            qiStationWriteUpDepartmentXmlDto = new ArrayList<QiStationWriteUpDepartmentXmlDto>();
        }
        return this.qiStationWriteUpDepartmentXmlDto;
    }

    /**
     * Gets the value of the qiStationUpcPartXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiStationUpcPartXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiStationUpcPartXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiStationUpcPartXmlDto }
     * 
     * 
     */
    public List<QiStationUpcPartXmlDto> getQiStationUpcPartXmlDto() {
        if (qiStationUpcPartXmlDto == null) {
            qiStationUpcPartXmlDto = new ArrayList<QiStationUpcPartXmlDto>();
        }
        return this.qiStationUpcPartXmlDto;
    }

	public void setQiStationConfigurationXmlDto(List<QiStationConfigurationXmlDto> qiStationConfigurationXmlDto) {
		this.qiStationConfigurationXmlDto = qiStationConfigurationXmlDto;
	}

	public void setQiStationEntryDepartmentXmlDto(List<QiStationEntryDepartmentXmlDto> qiStationEntryDepartmentXmlDto) {
		this.qiStationEntryDepartmentXmlDto = qiStationEntryDepartmentXmlDto;
	}

	public void setQiStationEntryScreenXmlDto(List<QiStationEntryScreenXmlDto> qiStationEntryScreenXmlDto) {
		this.qiStationEntryScreenXmlDto = qiStationEntryScreenXmlDto;
	}

	public void setQiStationPreviousDefectXmlDto(List<QiStationPreviousDefectXmlDto> qiStationPreviousDefectXmlDto) {
		this.qiStationPreviousDefectXmlDto = qiStationPreviousDefectXmlDto;
	}

	public void setQiStationResponsibilityXmlDto(List<QiStationResponsibilityXmlDto> qiStationResponsibilityXmlDto) {
		this.qiStationResponsibilityXmlDto = qiStationResponsibilityXmlDto;
	}

	public void setQiStationWriteUpDepartmentXmlDto(
			List<QiStationWriteUpDepartmentXmlDto> qiStationWriteUpDepartmentXmlDto) {
		this.qiStationWriteUpDepartmentXmlDto = qiStationWriteUpDepartmentXmlDto;
	}

	public void setQiStationUpcPartXmlDto(List<QiStationUpcPartXmlDto> qiStationUpcPartXmlDto) {
		this.qiStationUpcPartXmlDto = qiStationUpcPartXmlDto;
	}

}
