//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 01:16:22 PM EST 
//


package com.honda.galc.client.teamleader.qi.stationconfig.clonestation.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Station entry screen parameters
 * 
 * <p>Java class for QiStationEntryScreenXmlDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QiStationEntryScreenXmlDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="processPointId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="divisionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="entryScreen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orientationAngle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="allowScan" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QiStationEntryScreenXmlDto", propOrder = {

})
public class QiStationEntryScreenXmlDto {

    @XmlElement(required = true)
    protected String processPointId;
    @XmlElement(required = true)
    protected String divisionId;
    @XmlElement(required = true)
    protected String entryModel;
    protected int seq;
    @XmlElement(required = true)
    protected String entryScreen;
    protected int orientationAngle;
    protected int allowScan;

    /**
     * Gets the value of the processPointId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessPointId() {
        return processPointId;
    }

    /**
     * Sets the value of the processPointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessPointId(String value) {
        this.processPointId = value;
    }

    /**
     * Gets the value of the divisionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisionId() {
        return divisionId;
    }

    /**
     * Sets the value of the divisionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisionId(String value) {
        this.divisionId = value;
    }

    /**
     * Gets the value of the entryModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryModel() {
        return entryModel;
    }

    /**
     * Sets the value of the entryModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryModel(String value) {
        this.entryModel = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     */
    public int getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     */
    public void setSeq(int value) {
        this.seq = value;
    }

    /**
     * Gets the value of the entryScreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryScreen() {
        return entryScreen;
    }

    /**
     * Sets the value of the entryScreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryScreen(String value) {
        this.entryScreen = value;
    }

    /**
     * Gets the value of the orientationAngle property.
     * 
     */
    public int getOrientationAngle() {
        return orientationAngle;
    }

    /**
     * Sets the value of the orientationAngle property.
     * 
     */
    public void setOrientationAngle(int value) {
        this.orientationAngle = value;
    }

    /**
     * Gets the value of the allowScan property.
     * 
     */
    public int getAllowScan() {
        return allowScan;
    }

    /**
     * Sets the value of the allowScan property.
     * 
     */
    public void setAllowScan(int value) {
        this.allowScan = value;
    }

}
