DROP TRIGGER "GALADM"."PART_SPEC_TR2";
DROP TRIGGER "GALADM"."PART_SPEC_TR1";
DROP TABLE "GALADM"."PART_SPEC_TBX";

CREATE TABLE "GALADM"."PART_SPEC_TBX"  (
		  "PART_NAME" CHARACTER(32) NOT NULL , 
		  "PART_ID" CHARACTER(5) NOT NULL , 
		  "PART_DESCRIPTION" VARCHAR(128) , 
		  "PART_SERIAL_NUMBER_MASK"	CHARACTER(30),
		  "PART_MAX_ATTEMPTS" INTEGER,
		  "MEASUREMENT_COUNT"	INTEGER,
		  "ENTRY_TIMESTAMP"	TIMESTAMP,
		  "COMMENT" VARCHAR(256),
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP );



ALTER TABLE "GALADM"."PART_SPEC_TBX"
	ADD CONSTRAINT PART_SPEC_PK
	PRIMARY KEY ("PART_NAME","PART_ID");



CREATE TRIGGER "GALADM"."PART_SPEC_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."PART_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."PART_SPEC_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PART_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER "GALADM"."MEASURE_SPEC_TR2";
DROP TRIGGER "GALADM"."MEASURE_SPEC_TR1";
DROP TABLE "GALADM"."MEASUREMENT_SPEC_TBX";


CREATE TABLE "GALADM"."MEASUREMENT_SPEC_TBX"  (
		  "PART_NAME" CHARACTER(32) NOT NULL , 
		  "PART_ID" CHARACTER(5) NOT NULL ,
			"MEASUREMENT_SEQ_NUM" INTEGER NOT NULL,
			"MINIMUM_LIMIT" DOUBLE,
			"MAXIMUM_LIMIT" DOUBLE,
			"MAX_ATTEMPTS" INTEGER,
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP );



ALTER TABLE "GALADM"."MEASUREMENT_SPEC_TBX"
	ADD CONSTRAINT MEASUREMENT_SPC_PK
	PRIMARY KEY ("PART_NAME","PART_ID","MEASUREMENT_SEQ_NUM");



CREATE TRIGGER "GALADM"."MEASURE_SPEC_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."MEASUREMENT_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."MEASURE_SPEC_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."MEASUREMENT_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP




