INSERT INTO "GALADM"."NOTIFICATION" (NOTIFICATION_CLASS,DESCRIPTION,CLIENT_ONLY,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) VALUES ('ILogLevelNotification',null,0,null,null);
INSERT INTO "GALADM"."NOTIFICATION" (NOTIFICATION_CLASS,DESCRIPTION,CLIENT_ONLY,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) VALUES ('ILotControlRuleNotification',null,0,null,null);
INSERT INTO "GALADM"."NOTIFICATION" (NOTIFICATION_CLASS,DESCRIPTION,CLIENT_ONLY,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) VALUES ('IPropertyNotification',null,0,null,null);
