CREATE TABLE "GALADM"."GAL246TBX"
(
   PROCESS_POINT_ID char(16) DEFAULT ' ' NOT NULL,
   MODEL_YEAR_CODE char(1) DEFAULT ' ' NOT NULL,
   MODEL_CODE char(3) DEFAULT ' ' NOT NULL,
   MODEL_TYPE_CODE char(3) DEFAULT ' ' NOT NULL,
   MODEL_OPTION_CODE char(3) DEFAULT ' ' NOT NULL,
   INT_COLOR_CODE char(2) DEFAULT ' ' NOT NULL,
   EXT_COLOR_CODE char(10) DEFAULT ' ' NOT NULL,
   PART_NAME char(32) DEFAULT ' ' NOT NULL,
   SUB_ID char(2), 
   SEQUENCE_NUMBER int,
   EXPECTED_INSTALL_TIME int,
   VERIFICATION_FLAG int,
   SERIAL_NUMBER_SCAN_FLAG int,
   INSTRUCTION_CODE char(1),
   SERIAL_NUMBER_UNIQUE_FLAG int,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   DEVICE_ID char(16),
   STRATEGY varchar(256),
   PRIMARY KEY(PROCESS_POINT_ID,MODEL_YEAR_CODE,MODEL_CODE,MODEL_TYPE_CODE,MODEL_OPTION_CODE,INT_COLOR_CODE,EXT_COLOR_CODE,PART_NAME)
)

CREATE TRIGGER "GALADM"."GAL246TBX_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."GAL246TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP

CREATE TRIGGER "GALADM"."GAL246TBX_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."GAL246TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP
