DROP TRIGGER "GALADM"."PART_LOT_TR2";
DROP TRIGGER "GALADM"."PART_LOT_TR1";
DROP TABLE "GALADM"."PART_LOT_TBX";

CREATE TABLE "GALADM"."PART_LOT_TBX"  (
	PART_SERIAL_NUMBER CHARACTER(30) NOT NULL , 
	PART_NUMBER CHARACTER(30) NOT NULL , 
	PART_NAME CHARACTER(32) NOT NULL, 
	STATUS smallint default 0,
	STARTING_QUANTITY INTEGER default 0,
	CURRENT_QUANTITY INTEGER default 0,
	COMMENT VARCHAR(256),
	CREATE_TIMESTAMP TIMESTAMP, 
	UPDATE_TIMESTAMP TIMESTAMP,
	PRIMARY KEY (PART_SERIAL_NUMBER, PART_NAME, PART_NUMBER)
);   

COMMENT ON TABLE "GALADM"."PART_LOT_TBX" IS 'Part Lot';

CREATE TRIGGER "GALADM"."PART_LOT_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."PART_LOT_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PART_LOT_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PART_LOT_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;