DROP TRIGGER "GALADM"."PART_SPEC_TR2";
DROP TRIGGER "GALADM"."PART_SPEC_TR1";
DROP TABLE "GALADM"."PART_SPEC_TBX";

CREATE TABLE "GALADM"."PART_SPEC_TBX"  (
		  "PART_NAME" CHARACTER(32) NOT NULL , 
		  "PART_ID" CHARACTER(5) NOT NULL , 
		  "PART_DESCRIPTION" VARCHAR(128) , 
		  "PART_SERIAL_NUMBER_MASK"	CHARACTER(30),
			"PART_MAX_ATTEMPTS" INTEGER,
		  "MEASUREMENT_COUNT"	INTEGER,
		  "ENTRY_TIMESTAMP"	TIMESTAMP,
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

COMMENT ON TABLE "GALADM"."PART_SPEC_TBX" IS 'Installed Part Spec';

ALTER TABLE "GALADM"."PART_SPEC_TBX"
	ADD CONSTRAINT PART_SPEC_PK
	PRIMARY KEY ("PART_NAME","PART_ID");

CREATE TRIGGER "GALADM"."PART_SPEC_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."PART_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PART_SPEC_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PART_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GALADM.PART_SPEC_TBX TO GROUP GALCDV_A;
GRANT SELECT ON TABLE GALADM.PART_SPEC_TBX TO GROUP GALCDV_S;

DROP TRIGGER "GALADM"."MEASUREMENT_SPEC_TR2";
DROP TRIGGER "GALADM"."MEASUREMENT_SPEC_TR1";
DROP TABLE "GALADM"."MEASUREMENT_SPEC_TBX";


CREATE TABLE "GALADM"."MEASUREMENT_SPEC_TBX"  (
		  "PART_NAME" CHARACTER(32) NOT NULL , 
		  "PART_ID" CHARACTER(5) NOT NULL ,
			"MEASUREMENT_SEQ_NUM" INTEGER NOT NULL,
			"MINIMUM_LIMIT" DOUBLE,
			"MAXIMUM_LIMIT" DOUBLE,
			"MAX_ATTEMPTS" INTEGER,
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

COMMENT ON TABLE "GALADM"."MEASUREMENT_SPEC_TBX" IS 'Installed Part Measurement Spec';

ALTER TABLE "GALADM"."MEASUREMENT_SPEC_TBX"
	ADD CONSTRAINT MEASUREMENT_SPEC_PK
	PRIMARY KEY ("PART_NAME","PART_ID","MEASUREMENT_SEQ_NUM");

CREATE TRIGGER "GALADM"."MEASUREMENT_SPEC_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."MEASUREMENT_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."MEASUREMENT_SPEC_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."MEASUREMENT_SPEC_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE GALADM.MEASUREMENT_SPEC_TBX TO GROUP GALCDV_A;
GRANT SELECT ON TABLE GALADM.MEASUREMENT_SPEC_TBX TO GROUP GALCDV_S;

