DROP TABLE "GALADM"."PRODUCT_SPEC_CODE_TBX";

CREATE TABLE "GALADM"."PRODUCT_SPEC_CODE_TBX"
(
   PRODUCT_SPEC_CODE char(22) NOT NULL,
   PRODUCT_TYPE CHAR(10) NOT NULL,
   MODEL_YEAR_CODE CHAR(1),
   MODEL_CODE CHAR(3),
   MODEL_TYPE_CODE CHAR(3),
   MODEL_OPTION_CODE CHAR(3),
   EXT_COLOR_CODE CHAR(10),
   INT_COLOR_CODE CHAR(3),
   MODEL_YEAR_DESCRIPTION CHAR(4),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   PRIMARY KEY(PRODUCT_SPEC_CODE,PRODUCT_TYPE),
   FOREIGN KEY(PRODUCT_TYPE)
    REFERENCES GALADM.PRODUCT_TYPE_TBX(PRODUCT_TYPE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TRIGGER "GALADM"."PRODUCT_SPEC_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."PRODUCT_SPEC_CODE_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."PRODUCT_SPEC_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PRODUCT_SPEC_CODE_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

