DROP TRIGGER "GALADM"."HCMSEQUENCETR1"

ALTER TABLE "GALADM"."HCM_PRODUCT_SEQUENCE_TBX" DROP CONSTRAINT "SQL081030094631359"

DROP TABLE "GALADM"."HCM_PRODUCT_SEQUENCE_TBX"

CREATE TABLE "GALADM"."HCM_PRODUCT_SEQUENCE_TBX" (
		"PRODUCT_ID" CHAR(17) NOT NULL,
		"PROCESS_POINT_ID" CHAR(16) NOT NULL,
		"REFERENCE_TIMESTAMP" TIMESTAMP NOT NULL,
		"ASSOCIATE_NO" CHAR(11),
		"CREATE_TIMESTAMP" TIMESTAMP,
		"UPDATE_TIMESTAMP" TIMESTAMP
	)
	DATA CAPTURE NONE 

ALTER TABLE "GALADM"."HCM_PRODUCT_SEQUENCE_TBX" ADD CONSTRAINT "SQL081030094631359" PRIMARY KEY
	("PRODUCT_ID",
	 "PROCESS_POINT_ID")

CREATE TRIGGER "GALADM"."HCMSEQUENCETR1" 
	AFTER INSERT ON "GALADM"."HCM_PRODUCT_SEQUENCE_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
UPDATE "GALADM"."HCM_PRODUCT_SEQUENCE_TBX" SET CREATE_TIMESTAMP=CURRENT TIMESTAMP
WHERE PRODUCT_ID= A.PRODUCT_ID AND PROCESS_POINT_ID=A.PROCESS_POINT_ID AND REFERENCE_TIMESTAMP= A.REFERENCE_TIMESTAMP
