DROP TABLE "GALADM"."PRODUCT_TYPE_TBX";

CREATE TABLE "GALADM"."PRODUCT_TYPE_TBX"
(
   PRODUCT_TYPE char(10) NOT NULL,
   PRODUCT_TYPE_LABEL CHAR(30),
   PRODUCT_SPEC_CODE_FORMAT VARCHAR(256),
   PRODUCT_SPEC_CODE_LABEL CHAR(30) DEFAULT 'MTO',
   OWNER_PRODUCT_TYPE CHAR(10),
   PRODUCT_ID_LABEL CHAR(30),
   PRODUCT_ID_FORMAT CHAR(30),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   PRIMARY KEY(PRODUCT_TYPE)
);

CREATE TRIGGER "GALADM"."PRODUCT_TYPE_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."PRODUCT_TYPE_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."PRODUCT_TYPE_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PRODUCT_TYPE_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

