DROP TABLE "GALADM"."SUB_PRODUCT_TBX";

CREATE TABLE "GALADM"."SUB_PRODUCT_TBX"
(
   PRODUCT_ID char(17) DEFAULT ' ' NOT NULL,
   PRODUCTION_LOT char(20),
   KD_LOT_NUMBER char(18),
   PRODUCT_TYPE char(10),
   PRODUCT_SPEC_CODE char(22),
   SUB_ID char(2),
   PLAN_OFF_DATE date,
   TRACKING_STATUS char(16),
   PRODUCT_START_DATE date,
   ACTUAL_OFF_DATE date,
   AUTO_HOLD_STATUS smallint DEFAULT 0,
   STATUS smallint default 0,
   PRODUCTION_DATE date,
   LAST_PASSING_PROCESS_POINT_ID char(16),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   PRIMARY KEY(PRODUCT_ID)
);

CREATE TRIGGER "GALADM"."SUB_PRODUCT_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."SUB_PRODUCT_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."SUB_PRODUCT_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."SUB_PRODUCT_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
