DROP TABLE "GALADM"."SUB_PRODUCT_SHIPPING_TBX";

CREATE TABLE "GALADM"."SUB_PRODUCT_SHIPPING_TBX"
(
   KD_LOT_NUMBER char(18) NOT NULL,
   PRODUCTION_LOT char(20),
   PRODUCT_TYPE char(10),
   PRODUCT_SPEC_CODE char(22),
   LINE_NUMBER CHAR(2),
   PRODUCTION_DATE date,
   SEQ_NO integer default 0,
   STATUS smallint DEFAULT 0,
   SCH_QUANTITY smallint DEFAULT 0,
   ACT_QUANTITY smallint DEFAULT 0,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   PRIMARY KEY(KD_LOT_NUMBER)
);

CREATE TRIGGER "GALADM"."SUB_PROD_SHIP_TR1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."SUB_PRODUCT_SHIPPING_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."SUB_PROD_SHIP_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."SUB_PRODUCT_SHIPPING_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE "GALADM"."SUB_PRODUCT_SHIPPING_DETAIL_TBX"
(
   KD_LOT_NUMBER char(18) NOT NULL,
   SUB_ID char(2) NOT NULL,
   PRODUCT_SEQ_NO smallint DEFAULT 1 NOT NULL,	
   PRODUCT_ID char(17),
   PRODUCTION_LOT char(20),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   PRIMARY KEY(KD_LOT_NUMBER,SUB_ID,PRODUCT_SEQ_NO),
   FOREIGN KEY(KD_LOT_NUMBER)
    REFERENCES GALADM.SUB_PRODUCT_SHIPPING_TBX(KD_LOT_NUMBER)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TRIGGER "GALADM"."SUB_PROD_DETAIL_T1" 
	NO CASCADE BEFORE INSERT ON "GALADM"."SUB_PRODUCT_SHIPPING_DETAIL_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;



CREATE TRIGGER "GALADM"."SUB_PROD_DETAIL_T2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."SUB_PRODUCT_SHIPPING_DETAIL_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
