//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.honda.galc.service.qwx.ws;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StoreSphResult" type="{http://schemas.datacontract.org/2004/07/Sciemetric.QualityWorx.WebServiceGateway.Model}ServerResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "storeSphResult"
})
@XmlRootElement(name = "StoreSphResponse")
public class StoreSphResponse
    implements Serializable
{

    @XmlElementRef(name = "StoreSphResult", namespace = "http://tempuri.org/", type = JAXBElement.class)
    protected JAXBElement<ServerResponse> storeSphResult;

    /**
     * Gets the value of the storeSphResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ServerResponse }{@code >}
     *     
     */
    public JAXBElement<ServerResponse> getStoreSphResult() {
        return storeSphResult;
    }

    /**
     * Sets the value of the storeSphResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ServerResponse }{@code >}
     *     
     */
    public void setStoreSphResult(JAXBElement<ServerResponse> value) {
        this.storeSphResult = ((JAXBElement<ServerResponse> ) value);
    }

}
