package com.honda.galc.dao.jpa.conf;

import java.util.List;

import com.honda.galc.dao.jpa.BaseDaoImpl;
import com.honda.galc.entity.conf.MCMdrsManpowerAssignment;
import com.honda.galc.entity.conf.MCMdrsManpowerAssignmentId;
import com.honda.galc.dao.conf.MCMdrsManpowerAssignmentDao;

/**
 * @author vfc01778
 * @date December 09, 2014
 */
public class MCMdrsManpowerAssignmentDaoImpl extends BaseDaoImpl<MCMdrsManpowerAssignment, MCMdrsManpowerAssignmentId> implements MCMdrsManpowerAssignmentDao {

	private final String ASSIGNMENT_MAPPED_QUERY = "SELECT MDRS_MP.MANPOWER_ASSIGNMENT_ID, MDRS_MP.PLANT_LOC_CODE," +
			" MDRS_MP.DEPT_CODE,  MDRS_MP.LAST_UPDATED_DATE,  MDRS_MP.EXTRACT_DATE,  MDRS_MP.ASSOCIATE_ID," +			
			"  VIOS_MAST_PROC.PROCESS_POINT_ID,PF.PDDA_PLATFORM_ID, PE.LINE_NO, PE.PROCESS_LOCATION, " +			
			" PE.PLANT_CODE, MDRS_MP.PRODUCTION_DATE,PE.SHIFT, PE.PERIOD FROM (SELECT MA.MANPOWER_ASSIGNMENT_ID," +
			" MA.PLANT_LOC_CODE,  MA.DEPT_CODE, MA.LAST_UPDATED_DATE,   MA.EXTRACT_DATE,  MA.ASSOCIATE_ID," +
			" MA.TEAM_ID, MA.ROTATION_ID,MA.QUARTER,RO.PRODUCTION_DATE,RO.SHIFT_ID,TM.MODEL_YEAR_DATE," +
			" TM.PROD_SCH_QTY,  TM.VEHICLE_MODEL_CODE, TM.PROD_ASM_LINE_NO,  PAD.PROCESS_NO  FROM VIOS.MANPOWER_ASSIGNMENT MA" +
			"   LEFT JOIN VIOS.ROTATION RO ON MA.ROTATION_ID = RO.ROTATION_ID AND MA.EXTRACT_DATE = RO.EXTRACT_DATE" +
			" LEFT JOIN VIOS.PROCESS_ASSIGNMENT_DETAIL PAD  ON MA.MANPOWER_ASSIGNMENT_ID = PAD.MANPOWER_ASSIGNMENT_ID" +
			" AND MA.EXTRACT_DATE = PAD.EXTRACT_DATE  LEFT JOIN VIOS.PCLTM1 TM  ON MA.TEAM_ID = TM.TEAM_ID) AS MDRS_MP" +
			" LEFT JOIN GALADM.MC_PDDA_PLATFORM_TBX PF ON (    MDRS_MP.PLANT_LOC_CODE = PF.PLANT_LOC_CODE " +
			"   AND MDRS_MP.DEPT_CODE = PF.DEPT_CODE AND MDRS_MP.MODEL_YEAR_DATE = PF.MODEL_YEAR_DATE" +
			" AND MDRS_MP.PROD_SCH_QTY = PF.PROD_SCH_QTY AND MDRS_MP.PROD_ASM_LINE_NO = PF.PROD_ASM_LINE_NO"+
			" AND MDRS_MP.VEHICLE_MODEL_CODE = PF.VEHICLE_MODEL_CODE AND MDRS_MP.PROCESS_NO = PF.ASM_PROC_NO" +
			 " AND PF.APPROVED < CURRENT_TIMESTAMP AND (CURRENT_TIMESTAMP < PF.DEPRECATED OR PF.DEPRECATED IS NULL))" +
			" LEFT JOIN GALADM.MC_VIOS_MASTER_PLATFORM_TBX VIOS_MAST_PLAT ON PF.PLANT_LOC_CODE=VIOS_MAST_PLAT.PLANT_LOC_CODE AND PF.DEPT_CODE=VIOS_MAST_PLAT.DEPT_CODE AND PF.MODEL_YEAR_DATE=VIOS_MAST_PLAT.MODEL_YEAR_DATE AND PF.PROD_SCH_QTY=VIOS_MAST_PLAT.PROD_SCH_QTY AND PF.PROD_ASM_LINE_NO=VIOS_MAST_PLAT.PROD_ASM_LINE_NO AND PF.VEHICLE_MODEL_CODE=VIOS_MAST_PLAT.VEHICLE_MODEL_CODE " +
			" LEFT JOIN GALADM.MC_VIOS_MASTER_ASM_PROC_TBX VIOS_MAST_PROC ON VIOS_MAST_PLAT.VIOS_PLATFORM_ID=VIOS_MAST_PROC.VIOS_PLATFORM_ID AND PF.ASM_PROC_NO=VIOS_MAST_PROC.ASM_PROC_NO " +
			" LEFT JOIN GALADM.MC_MDRS_PERIOD_TBX PE  ON     MDRS_MP.PLANT_LOC_CODE = PE.PLANT_LOC_CODE" +
			 " AND MDRS_MP.DEPT_CODE = PE.DEPT_CODE AND MDRS_MP.SHIFT_ID = PE.SHIFT_ID AND MDRS_MP.QUARTER = PE.QUARTER" +
			" LEFT JOIN GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX MDRS_MA ON     MDRS_MP.MANPOWER_ASSIGNMENT_ID = "+
			 " MDRS_MA.MANPOWER_ASSIGNMENT_ID AND MDRS_MP.PLANT_LOC_CODE = MDRS_MA.PLANT_LOC_CODE " +
			" AND PE.DEPT_CODE = MDRS_MA.DEPT_CODE AND MDRS_MP.LAST_UPDATED_DATE = MDRS_MA.LAST_UPDATED_DATE " +
			 " AND MDRS_MP.EXTRACT_DATE = MDRS_MA.EXTRACT_DATE";
	
	
	public List<Object[]> getManPowerAssignmentsFromMDRS(){
		return findAllByNativeQuery(ASSIGNMENT_MAPPED_QUERY, null, Object[].class);
	}

}
