
------------------------------------------------
-- DDL Statements for Table "GALADM  "."ABNORMAL_REASON_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."ABNORMAL_REASON_TBX";


CREATE TABLE "GALADM  "."ABNORMAL_REASON_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "ABNORMAL_TYPE" CHAR(100 OCTETS) NOT NULL , 
		  "ABNORMAL_REASON" VARCHAR(255 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) NOT NULL , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."ABNORMAL_REASON_TBX" IS 'RMT AbnormalReason';






-- DDL Statements for Indexes on Table "GALADM  "."ABNORMAL_REASON_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."ABNORMAL_REASON_I1" ON "GALADM  "."ABNORMAL_REASON_TBX" 
		("PRODUCT_ID" ASC,
		 "ABNORMAL_TYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ABNORMAL_REASON_TR1";

CREATE TRIGGER GALADM.ABNORMAL_REASON_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ABNORMAL_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ABNORMAL_REASON_TR2";

CREATE TRIGGER GALADM.ABNORMAL_REASON_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ABNORMAL_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


