
------------------------------------------------
-- DDL Statements for Table "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX";


CREATE TABLE "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX"  (
		  "ID" INTEGER NOT NULL , 
		  "LINE_ID" VARCHAR(16 OCTETS) , 
		  "CYCLE_TIMER" VARCHAR(100 OCTETS) , 
		  "WARNING_VALUE" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "ERROR_VALUE" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATED_BY" VARCHAR(100 OCTETS) , 
		  "UPDATED_BY" VARCHAR(100 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX" IS 'Advanced Process Cycle Timer - It holds configuration data for Max Cycle Time and Min and Max time/units for Current Cycle, Over Cycles, Accum. Time and On Target';


-- DDL Statements for Primary Key on Table "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX"

ALTER TABLE "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX" 
	ADD CONSTRAINT "ADVANCE_PROCESS_CYCLE_TIMER_PK" PRIMARY KEY
		("ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TR1";

CREATE TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX
  REFERENCING
    NEW AS A
 FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TR2";

CREATE TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


