
------------------------------------------------
-- DDL Statements for Table "GALADM  "."AEP_STAT_OUT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."AEP_STAT_OUT_TBX";


CREATE TABLE "GALADM  "."AEP_STAT_OUT_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "EVENT_DATE" CHAR(6 OCTETS) , 
		  "EVENT_TIME" CHAR(6 OCTETS) , 
		  "ENGINE_ID" CHAR(12 OCTETS) NOT NULL , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "FRAME_MODEL" CHAR(4 OCTETS) , 
		  "FRAME_TYPE" CHAR(3 OCTETS) , 
		  "EXT_COLOR" CHAR(8 OCTETS) , 
		  "INT_COLOR" CHAR(1 OCTETS) , 
		  "FRAME_OPTION" CHAR(3 OCTETS) , 
		  "SENT_FLAG" CHAR(1 OCTETS) , 
		  "RECORD_TYPE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."AEP_STAT_OUT_TBX" IS 'AEP Outgoing Info OIF Table';


-- DDL Statements for Primary Key on Table "GALADM  "."AEP_STAT_OUT_TBX"

ALTER TABLE "GALADM  "."AEP_STAT_OUT_TBX" 
	ADD CONSTRAINT "AEP_STAT_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ENGINE_ID",
		 "PROCESS_POINT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."AEP_STAT_OUT_TR1";

CREATE TRIGGER GALADM.AEP_STAT_OUT_TR1 NO CASCADE BEFORE INSERT ON GALADM.AEP_STAT_OUT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."AEP_STAT_OUT_TR2";

CREATE TRIGGER GALADM.AEP_STAT_OUT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.AEP_STAT_OUT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


