
------------------------------------------------
-- DDL Statements for Table "GALADM  "."AUDIT_LOG_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."AUDIT_LOG_TBX";


CREATE TABLE "GALADM  "."AUDIT_LOG_TBX"  (
		  "TABLE_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "COLUMN_NAME" VARCHAR(128 OCTETS) NOT NULL , 
		  "PRIMARY_KEY_VALUE" VARCHAR(286 OCTETS) NOT NULL , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "PREVIOUS_VALUE" VARCHAR(256 OCTETS) , 
		  "CURRENT_VALUE" VARCHAR(256 OCTETS) , 
		  "UPDATE_REASON" VARCHAR(1024 OCTETS) , 
		  "MAINTENANCE_SCREEN" VARCHAR(64 OCTETS) , 
		  "SYSTEM" CHAR(18 OCTETS) , 
		  "CHANGE_TYPE" CHAR(18 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_USER" CHAR(11 OCTETS) , 
		  "PRIMARY_KEY" VARCHAR(128 OCTETS) NOT NULL WITH DEFAULT '' )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."AUDIT_LOG_TBX" IS 'NAQ Audit Log';


-- DDL Statements for Indexes on Table "GALADM  "."AUDIT_LOG_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."AUDIT_LOG_I1" ON "GALADM  "."AUDIT_LOG_TBX" 
		("TABLE_NAME" ASC,
		 "COLUMN_NAME" ASC,
		 "PRIMARY_KEY_VALUE" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."AUDIT_LOG_TBX"

ALTER TABLE "GALADM  "."AUDIT_LOG_TBX" 
	ADD CONSTRAINT "AUDIT_LOG_PK" PRIMARY KEY
		("TABLE_NAME",
		 "COLUMN_NAME",
		 "PRIMARY_KEY_VALUE",
		 "ACTUAL_TIMESTAMP");




-- DDL Statements for Check Constraints on Table "GALADM  "."AUDIT_LOG_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."AUDIT_LOG_TBX" 
	ADD CONSTRAINT "AUDIT_LOG_C1" CHECK 
		(TABLE_NAME = UPPER(TABLE_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."AUDIT_LOG_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."AUDIT_LOG_TBX" 
	ADD CONSTRAINT "AUDIT_LOG_C2" CHECK 
		(COLUMN_NAME = UPPER(COLUMN_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."AUDIT_LOG_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."AUDIT_LOG_TBX" 
	ADD CONSTRAINT "AUDIT_LOG_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."AUDIT_LOG_TR1";

CREATE TRIGGER GALADM.AUDIT_LOG_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.AUDIT_LOG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."AUDIT_LOG_TR2";

CREATE TRIGGER GALADM.AUDIT_LOG_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.AUDIT_LOG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


