
------------------------------------------------
-- DDL Statements for Table "GALADM  "."BLOCK_LOAD_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."BLOCK_LOAD_TBX";


CREATE TABLE "GALADM  "."BLOCK_LOAD_TBX"  (
		  "MC_NUMBER" CHAR(20 OCTETS) NOT NULL , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "LOT_SIZE" INTEGER , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "REFERENCE_NUMBER" INTEGER , 
		  "STATUS" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."BLOCK_LOAD_TBX" IS 'RMT BlockLoad';


-- DDL Statements for Primary Key on Table "GALADM  "."BLOCK_LOAD_TBX"

ALTER TABLE "GALADM  "."BLOCK_LOAD_TBX" 
	ADD CONSTRAINT "BLOCK_LOAD_PK" PRIMARY KEY
		("MC_NUMBER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."BLOCK_LOAD_TR1";

CREATE TRIGGER GALADM.BLOCK_LOAD_TR1 NO CASCADE BEFORE INSERT ON GALADM.BLOCK_LOAD_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."BLOCK_LOAD_TR2";

CREATE TRIGGER GALADM.BLOCK_LOAD_TR2 NO CASCADE BEFORE UPDATE ON GALADM.BLOCK_LOAD_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


