
------------------------------------------------
-- DDL Statements for Table "GALADM  "."BOM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."BOM_TBX";


CREATE TABLE "GALADM  "."BOM_TBX"  (
		  "PART_NO" CHAR(18 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PART_COLOR_CODE" CHAR(11 OCTETS) , 
		  "SUPPLIER_NO" CHAR(6 OCTETS) NOT NULL , 
		  "TARGET_MFG_DEST_NO" CHAR(6 OCTETS) , 
		  "PART_BLOCK_CODE" CHAR(1 OCTETS) , 
		  "PART_SECTION_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "PART_ITEM_NO" CHAR(7 OCTETS) NOT NULL , 
		  "TGT_SHIP_TO_CODE" CHAR(6 OCTETS) NOT NULL , 
		  "MTC_MODEL" CHAR(4 OCTETS) NOT NULL , 
		  "MTC_COLOR" CHAR(11 OCTETS) NOT NULL , 
		  "MTC_OPTION" CHAR(3 OCTETS) NOT NULL , 
		  "MTC_TYPE" CHAR(3 OCTETS) NOT NULL , 
		  "INT_COLOR_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "EFF_BEG_DATE" DATE NOT NULL , 
		  "EFF_END_DATE" DATE NOT NULL , 
		  "PART_PROD_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROCLOC_GP_NO" CHAR(2 OCTETS) NOT NULL , 
		  "PROCLOC_GP_SEQ_NO" CHAR(2 OCTETS) NOT NULL , 
		  "TGT_PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "TGT_MODEL_DEV_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "PART_COLOR_ID_CODE" CHAR(1 OCTETS) , 
		  "SUPPLIER_CAT_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PART_QTY" DECIMAL(6,0) NOT NULL , 
		  "DATA_UPD_DESC_TEXT" CHAR(20 OCTETS) NOT NULL , 
		  "TIMESTAMP_DATE" TIMESTAMP NOT NULL , 
		  "DC_FAM_CLASS_CODE" CHAR(5 OCTETS) NOT NULL , 
		  "DC_PART_NO" CHAR(18 OCTETS) NOT NULL , 
		  "DC_PART_NAME" CHAR(30 OCTETS) , 
		  "PDDA_FIF_TYPE" VARCHAR(3 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."BOM_TBX" IS 'RGALC table corresponding to  TIX.TISAF2';






-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."BOM_I1" ON "GALADM  "."BOM_TBX" 
		("PART_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."BOM_I2" ON "GALADM  "."BOM_TBX" 
		("PART_NO" ASC,
		 "MTC_MODEL" ASC,
		 "MTC_TYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."BOM_I3" ON "GALADM  "."BOM_TBX" 
		("MTC_TYPE" ASC,
		 "MTC_COLOR" ASC,
		 "MTC_MODEL" ASC,
		 "EFF_BEG_DATE" ASC,
		 "EFF_END_DATE" ASC,
		 "PDDA_FIF_TYPE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "PART_BLOCK_CODE" ASC,
		 "MTC_OPTION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM"."BOM_PK" ON "GALADM  "."BOM_TBX" 
                                ("PART_NO" ASC,
                                "PLANT_LOC_CODE" ASC,
                                "PART_COLOR_CODE" ASC,
                                "SUPPLIER_NO" ASC,
                                "TGT_SHIP_TO_CODE" ASC,
                                "MTC_MODEL" ASC,
                                "MTC_COLOR" ASC,
                                "MTC_OPTION" ASC,
                                "MTC_TYPE" ASC,
                                "INT_COLOR_CODE" ASC,
                                "EFF_BEG_DATE" ASC,
                                "PART_BLOCK_CODE" ASC,
                                "PART_SECTION_CODE" ASC,
                                "PART_ITEM_NO" ASC,
                                "DC_PART_NO" ASC 
                                )
                                COMPRESS NO 
                                INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."BOM_TR1";

CREATE TRIGGER GALADM.BOM_TR1 NO CASCADE BEFORE INSERT ON GALADM.BOM_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."BOM_TR2";

CREATE TRIGGER GALADM.BOM_TR2 NO CASCADE BEFORE UPDATE ON GALADM.BOM_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


