
------------------------------------------------
-- DDL Statements for Table "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX";


CREATE TABLE "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX"  (
		  "MODEL_GROUP" CHAR(32 OCTETS) NOT NULL , 
		  "PART_NO" CHAR(18 OCTETS) NOT NULL , 
		  "PART_COLOR_CODE" CHAR(11 OCTETS) NOT NULL , 
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL , 
		  "ATTRIBUTE_VALUE" VARCHAR(512 OCTETS) , 
		  "ATTRIBUTE_DESCRIPTION" CHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX" IS 'RMT BuildAttributeByBom';


-- DDL Statements for Primary Key on Table "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX"

ALTER TABLE "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX" 
	ADD CONSTRAINT "BUILD_ATTRIBUTE_BY_BOM_PK" PRIMARY KEY
		("MODEL_GROUP",
		 "PART_NO",
		 "PART_COLOR_CODE",
		 "ATTRIBUTE");



-- DDL Statements for Indexes on Table "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_I1" ON "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TBX" 
		("ATTRIBUTE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TR1";

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_ATTRIBUTE_BY_BOM_TR2";

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


