
------------------------------------------------
-- DDL Statements for Table "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX";


CREATE TABLE "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX"  (
		  "FORM_ID" CHAR(32 OCTETS) NOT NULL , 
		  "MODEL_GROUP" CHAR(32 OCTETS) NOT NULL , 
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL , 
		  "ROW" INTEGER , 
		  "COL" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX" IS 'Build Sheet Grid Maintenance By Model Grp';


-- DDL Statements for Primary Key on Table "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX"

ALTER TABLE "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX" 
	ADD CONSTRAINT "BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_PK" PRIMARY KEY
		("FORM_ID",
		 "MODEL_GROUP",
		 "ATTRIBUTE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX_TR1";

CREATE TRIGGER GALADM.BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX_TR2";

CREATE TRIGGER GALADM.BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_SHEET_PART_ATTR_BY_MODEL_GRP_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


