
------------------------------------------------
-- DDL Statements for Table "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX";


CREATE TABLE "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX"  (
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL , 
		  "ATTRIBUTE_LABEL" VARCHAR(32 OCTETS) NOT NULL , 
		  "ATTRIBUTE_GRP" CHAR(32 OCTETS) NOT NULL , 
		  "AUTO_UPDATE" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX" IS 'RMT BuildAttributeDefinition';


-- DDL Statements for Primary Key on Table "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX"

ALTER TABLE "GALADM  "."BUILD_ATTRIBUTE_DEF_TBX" 
	ADD CONSTRAINT "BUILD_ATTRIBUTE_DEF_PK" PRIMARY KEY
		("ATTRIBUTE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_ATTRIBUTE_DEF_TR1";

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_DEF_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_ATTRIBUTE_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BUILD_ATTRIBUTE_DEF_TR2";

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_DEF_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_ATTRIBUTE_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


