
------------------------------------------------
-- DDL Statements for Table "GALADM  "."CARRIER_ATTRIBUTES_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."CARRIER_ATTRIBUTES_TBX";


CREATE TABLE "GALADM  "."CARRIER_ATTRIBUTES_TBX"  (
		  "TRACKING_AREA" CHAR(10 OCTETS) NOT NULL , 
		  "CARRIER_NUMBER" CHAR(40 OCTETS) NOT NULL , 
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL , 
		  "ATTRIBUTE_VALUE" VARCHAR(512 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."CARRIER_ATTRIBUTES_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."CARRIER_ATTRIBUTES_TBX" IS 'RMT CarrierAttributes';


-- DDL Statements for Primary Key on Table "GALADM  "."CARRIER_ATTRIBUTES_TBX"

ALTER TABLE "GALADM  "."CARRIER_ATTRIBUTES_TBX" 
	ADD CONSTRAINT "CARRIER_ATTRIBUTES_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "CARRIER_NUMBER",
		 "ATTRIBUTE");



-- DDL Statements for Indexes on Table "GALADM  "."CARRIER_ATTRIBUTES_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CARRIER_ATTRIBUTES_I1" ON "GALADM  "."CARRIER_ATTRIBUTES_TBX" 
		("TRACKING_AREA" ASC,
		 "CARRIER_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CARRIER_ATTRIBUTES_TR1";

CREATE TRIGGER GALADM.CARRIER_ATTRIBUTES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CARRIER_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CARRIER_ATTRIBUTES_TR2";

CREATE TRIGGER GALADM.CARRIER_ATTRIBUTES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CARRIER_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


