
------------------------------------------------
-- DDL Statements for Table "GALADM  "."CASE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."CASE_TBX";


CREATE TABLE "GALADM  "."CASE_TBX"  (
		  "PRODUCT_ID" VARCHAR(255 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" VARCHAR(10 OCTETS) , 
		  "DC_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "MC_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "ENGINE_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "DUNNAGE" VARCHAR(20 OCTETS) , 
		  "HOLD_STATUS" SMALLINT NOT NULL , 
		  "DEFECT_STATUS" SMALLINT , 
		  "MODEL" VARCHAR(22 OCTETS) , 
		  "TRACKING_STATUS" VARCHAR(16 OCTETS) , 
		  "LAST_PASSING_PROCESS_POINT_ID" VARCHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."CASE_TBX" IS 'RMT Case';


-- DDL Statements for Primary Key on Table "GALADM  "."CASE_TBX"

ALTER TABLE "GALADM  "."CASE_TBX" 
	ADD CONSTRAINT "CASE_PK" PRIMARY KEY
		("PRODUCT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."CASE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CASE_I1" ON "GALADM  "."CASE_TBX" 
		("DUNNAGE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CASE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CASE_I2" ON "GALADM  "."CASE_TBX" 
		("LAST_PASSING_PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CASE_TR1";

CREATE TRIGGER GALADM.CASE_TR1 NO CASCADE BEFORE INSERT ON GALADM.CASE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CASE_TR2";

CREATE TRIGGER GALADM.CASE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.CASE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


