
------------------------------------------------
-- DDL Statements for Table "GALADM  "."COMPONENT_STATUS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."COMPONENT_STATUS_TBX";


CREATE TABLE "GALADM  "."COMPONENT_STATUS_TBX"  (
		  "COMPONENT_ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "STATUS_KEY" VARCHAR(64 OCTETS) NOT NULL , 
		  "STATUS_VALUE" VARCHAR(1024 OCTETS) NOT NULL , 
		  "DESCRIPTION" VARCHAR(64 OCTETS) , 
		  "CHANGE_USER_ID" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."COMPONENT_STATUS_TBX" IS 'RMT Compenent Status';


-- DDL Statements for Indexes on Table "GALADM  "."COMPONENT_STATUS_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."COMPONENT_STATUS_I1" ON "GALADM  "."COMPONENT_STATUS_TBX" 
		("COMPONENT_ID" ASC,
		 "STATUS_KEY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."COMPONENT_STATUS_TBX"

ALTER TABLE "GALADM  "."COMPONENT_STATUS_TBX" 
	ADD CONSTRAINT "COMPONENT_STATUS_PK" PRIMARY KEY
		("COMPONENT_ID",
		 "STATUS_KEY");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."COMPONENT_STATUS_TR1";

CREATE TRIGGER GALADM.COMPONENT_STATUS_TR1 NO CASCADE BEFORE INSERT ON GALADM.COMPONENT_STATUS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."COMPONENT_STATUS_TR2";

CREATE TRIGGER GALADM.COMPONENT_STATUS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.COMPONENT_STATUS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


