
------------------------------------------------
-- DDL Statements for Table "GALADM  "."CONROD_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."CONROD_TBX";


CREATE TABLE "GALADM  "."CONROD_TBX"  (
		  "CONROD_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "MC_SERIAL_NUMBER" VARCHAR(19 OCTETS) , 
		  "DC_SERIAL_NUMBER" VARCHAR(19 OCTETS) , 
		  "ENGINE_SERIAL_NUMBER" VARCHAR(17 OCTETS) , 
		  "MODEL" VARCHAR(12 OCTETS) , 
		  "TRACKING_STATUS" VARCHAR(16 OCTETS) , 
		  "DUNNAGE" VARCHAR(20 OCTETS) , 
		  "DEFECT_STATUS" SMALLINT , 
		  "HOLD_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."CONROD_TBX" IS 'RMT Conrod';


-- DDL Statements for Primary Key on Table "GALADM  "."CONROD_TBX"

ALTER TABLE "GALADM  "."CONROD_TBX" 
	ADD CONSTRAINT "CONROD_PK" PRIMARY KEY
		("CONROD_ID");



-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CONROD_I1" ON "GALADM  "."CONROD_TBX" 
		("ENGINE_SERIAL_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CONROD_I2" ON "GALADM  "."CONROD_TBX" 
		("DC_SERIAL_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CONROD_I3" ON "GALADM  "."CONROD_TBX" 
		("DUNNAGE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CONROD_I4" ON "GALADM  "."CONROD_TBX" 
		("LAST_PASSING_PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CONROD_TR1";

CREATE TRIGGER GALADM.CONROD_TR1 NO CASCADE BEFORE INSERT ON GALADM.CONROD_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CONROD_TR2";

CREATE TRIGGER GALADM.CONROD_TR2 NO CASCADE BEFORE UPDATE ON GALADM.CONROD_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


