
------------------------------------------------
-- DDL Statements for Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX";


CREATE TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX"  (
		  "CRANKSHAFT_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_COUNT" INTEGER NOT NULL WITH DEFAULT 1 , 
		  "DEVICE_ID" VARCHAR(32 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX" IS 'RMT CrankshaftHistory';


-- DDL Statements for Primary Key on Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"

ALTER TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX" 
	ADD CONSTRAINT "CRANKSHAFT_HISTORY_PK" PRIMARY KEY
		("CRANKSHAFT_ID",
		 "PROCESS_POINT_ID",
		 "ACTUAL_TIMESTAMP");



-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."CRANKSHAFT_HISTORY_I1" ON "GALADM  "."CRANKSHAFT_HISTORY_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CRANKSHAFT_HISTORY_TR1";

CREATE TRIGGER GALADM.CRANKSHAFT_HISTORY_TR1 NO CASCADE BEFORE INSERT ON
GALADM.CRANKSHAFT_HISTORY_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."CRANKSHAFT_HISTORY_TR2";

CREATE TRIGGER GALADM.CRANKSHAFT_HISTORY_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.CRANKSHAFT_HISTORY_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


