
------------------------------------------------
-- DDL Statements for Table "GALADM  "."DC_ZONE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."DC_ZONE_TBX";


CREATE TABLE "GALADM  "."DC_ZONE_TBX"  (
		  "ZONE_ID" CHAR(16 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "REPAIRABLE" SMALLINT NOT NULL WITH DEFAULT 0,
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."DC_ZONE_TBX" PCTFREE 0;

ALTER TABLE "GALADM  "."DC_ZONE_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."DC_ZONE_TBX" IS 'RMT Process points by zones representing areas of responsibility';


-- DDL Statements for Primary Key on Table "GALADM  "."DC_ZONE_TBX"

ALTER TABLE "GALADM  "."DC_ZONE_TBX" 
	ADD CONSTRAINT "DC_ZONE_TBX_PK" PRIMARY KEY
		("ZONE_ID",
		 "PROCESS_POINT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."DC_ZONE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."DC_ZONE_TBX_I1" ON "GALADM  "."DC_ZONE_TBX" 
		("ZONE_ID" ASC,
		 "PROCESS_POINT_ID" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."DC_ZONE_TBX_TR1";

CREATE TRIGGER GALADM.DC_ZONE_TBX_TR1
	NO CASCADE BEFORE INSERT
	ON GALADM.DC_ZONE_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."DC_ZONE_TBX_TR2";

CREATE TRIGGER GALADM.DC_ZONE_TBX_TR2
	NO CASCADE BEFORE UPDATE
	ON GALADM.DC_ZONE_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


