
------------------------------------------------
-- DDL Statements for Table "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX";


CREATE TABLE "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX"  (
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL , 
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "SECONDARY_PART_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "ACTUAL_PROBLEM_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX" IS 'RMT DefectActualProblem used by QICS';


-- DDL Statements for Primary Key on Table "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX"

ALTER TABLE "GALADM  "."DEFECT_ACTUAL_PROBLEM_TBX" 
	ADD CONSTRAINT "DEFECT_ACTUAL_PROBLEM_PK" PRIMARY KEY
		("MODEL_CODE",
		 "DEFECT_TYPE_NAME",
		 "INSPECTION_PART_NAME",
		 "SECONDARY_PART_NAME",
		 "ACTUAL_PROBLEM_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."DEFECT_ACTUAL_PROBLEM_TR1";

CREATE TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR1 NO CASCADE BEFORE INSERT
ON GALADM.DEFECT_ACTUAL_PROBLEM_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."DEFECT_ACTUAL_PROBLEM_TR2";

CREATE TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.DEFECT_ACTUAL_PROBLEM_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


