------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."DESIGN_CHANGE_RULES"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES";

CREATE TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES"  (
		  "DC_CLASS" VARCHAR(10 OCTETS) NOT NULL ,		  
		  "REFLASH" INTEGER NOT NULL ,
		  "INTERCHANGABLE" INTEGER NOT NULL ,		  
		  "SCRAP_PARTS" INTEGER NOT NULL ,		  
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES" IS 'VIN-BOM Rules Applied to Design Changes';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."DESIGN_CHANGE_RULES"

ALTER TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES" 
	ADD CONSTRAINT "DESIGN_CHANGE_RULES_PK" PRIMARY KEY
		("DC_CLASS");

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."DESIGN_CHANGE_RULES_TR1";

CREATE TRIGGER LCVINBOM.DESIGN_CHANGE_RULES_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.DESIGN_CHANGE_RULES
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."DESIGN_CHANGE_RULES_TR2";

CREATE TRIGGER LCVINBOM.DESIGN_CHANGE_RULES_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.DESIGN_CHANGE_RULES
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

-------------------------------
-- Add Default Data
-------------------------------

INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('A', 1, 0, 2, '2021-04-22 13:29:59.873203', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('B', 1, 0, 2, '2021-04-22 13:29:59.910272', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('C', 2, 2, 2, '2021-04-22 13:29:59.962081', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('D', 0, 1, 0, '2021-04-22 13:30:00.000264', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('E', 0, 1, 0, '2021-04-22 13:30:00.056491', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('J', 0, 1, 0, '2021-04-22 13:30:00.092246', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('L', 2, 2, 2, '2021-04-22 13:29:59.962081', null);