
------------------------------------------------
-- DDL Statements for Table "GALADM  "."DUNNAGE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."DUNNAGE_TBX";


CREATE TABLE "GALADM  "."DUNNAGE_TBX"  (
		  "DUNNAGE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "EXPECTED_QTY" SMALLINT , 
		  "PRODUCT_SPEC_CODE" VARCHAR(30 OCTETS) , 
		  "DUNNAGE_STATUS" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."DUNNAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."DUNNAGE_PK" ON "GALADM  "."DUNNAGE_TBX" 
		("DUNNAGE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."DUNNAGE_TBX"

ALTER TABLE "GALADM  "."DUNNAGE_TBX" 
	ADD CONSTRAINT "DUNNAGE_PK" PRIMARY KEY
		("DUNNAGE_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_TR1";

CREATE TRIGGER GALADM.DUNNAGE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.DUNNAGE_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_TR2";

CREATE TRIGGER GALADM.DUNNAGE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.DUNNAGE_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


