
------------------------------------------------
-- DDL Statements for Table "GALADM  "."DUNNAGE_CONTENT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."DUNNAGE_CONTENT_TBX";


CREATE TABLE "GALADM  "."DUNNAGE_CONTENT_TBX"  (
		  "DUNNAGE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "PRODUCT_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "DUNNAGE_ROW" VARCHAR(8 OCTETS) , 
		  "DUNNAGE_COLUMN" VARCHAR(8 OCTETS) , 
		  "DUNNAGE_LAYER" VARCHAR(8 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."DUNNAGE_CONTENT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."DUNNAGE_CONTENT_PK" ON "GALADM  "."DUNNAGE_CONTENT_TBX" 
		("DUNNAGE_ID" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."DUNNAGE_CONTENT_TBX"

ALTER TABLE "GALADM  "."DUNNAGE_CONTENT_TBX" 
	ADD CONSTRAINT "DUNNAGE_CONTENT_PK" PRIMARY KEY
		("DUNNAGE_ID",
		 "PRODUCT_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_CONTENT_TR1";

CREATE TRIGGER GALADM.DUNNAGE_CONTENT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.DUNNAGE_CONTENT_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_CONTENT_TR2";

CREATE TRIGGER GALADM.DUNNAGE_CONTENT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.DUNNAGE_CONTENT_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


