
------------------------------------------------
-- DDL Statements for Table "GALADM  "."ENGINE_MANIFEST_HIST_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."ENGINE_MANIFEST_HIST_TBX";


CREATE TABLE "GALADM  "."ENGINE_MANIFEST_HIST_TBX"  (
		  "ENGINE_NO" CHAR(12 OCTETS) NOT NULL , 
		  "COMPANY" CHAR(3 OCTETS) NOT NULL , 
		  "PLANT" CHAR(3 OCTETS) NOT NULL , 
		  "DEPARTMENT" CHAR(2 OCTETS) NOT NULL , 
		  "LINE" CHAR(1 OCTETS) NOT NULL , 
		  "PROCESS" CHAR(3 OCTETS) NOT NULL , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "PRODUCTION_DATE" DATE NOT NULL , 
		  "VIN" CHAR(17 OCTETS) NOT NULL , 
		  "ENGINE_FIRED_IND" CHAR(1 OCTETS) NOT NULL , 
		  "ENGINE_SOURCE" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."ENGINE_MANIFEST_HIST_TBX" IS 'ENGINE MANIFEST HISTORY RECORD';


-- DDL Statements for Indexes on Table "GALADM  "."ENGINE_MANIFEST_HIST_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."ENGINE_MANIFEST_HIST_I1" ON "GALADM  "."ENGINE_MANIFEST_HIST_TBX" 
		("ENGINE_NO" ASC,
		 "COMPANY" ASC,
		 "PLANT" ASC,
		 "DEPARTMENT" ASC,
		 "LINE" ASC,
		 "PROCESS" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."ENGINE_MANIFEST_HIST_TBX"

ALTER TABLE "GALADM  "."ENGINE_MANIFEST_HIST_TBX" 
	ADD CONSTRAINT "ENGINE_MANIFEST_HIST_PK" PRIMARY KEY
		("ENGINE_NO",
		 "COMPANY",
		 "PLANT",
		 "DEPARTMENT",
		 "LINE",
		 "PROCESS",
		 "ACTUAL_TIMESTAMP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ENGINE_MANIFEST_HIST_TBX_TR1";

CREATE TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ENGINE_MANIFEST_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ENGINE_MANIFEST_HIST_TBX_TR2";

CREATE TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ENGINE_MANIFEST_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


