
------------------------------------------------
-- DDL Statements for Table "GALADM  "."ENGINE_MANIFEST_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."ENGINE_MANIFEST_TBX";


CREATE TABLE "GALADM  "."ENGINE_MANIFEST_TBX"  (
		  "ENGINE_NO" CHAR(12 OCTETS) NOT NULL , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "ENGINE_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "ENGINE_TYPE" CHAR(3 OCTETS) NOT NULL , 
		  "ENGINE_OPTION" CHAR(2 OCTETS) NOT NULL , 
		  "ENGINE_BASIC_PART" CHAR(17 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENGINE_PC_NO" CHAR(9 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENGINE_CASE_NO" CHAR(7 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENGINE_EC_NO" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MISSION_NO" CHAR(11 OCTETS) NOT NULL , 
		  "COMPANY" CHAR(3 OCTETS) NOT NULL , 
		  "PLANT" CHAR(3 OCTETS) NOT NULL , 
		  "VIN" CHAR(17 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENGINE_KD_LOT" CHAR(11 OCTETS) NOT NULL , 
		  "ENGINE_FIRED_IND" CHAR(1 OCTETS) NOT NULL , 
		  "ENGINE_SOURCE" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "UNSHIP_STATUS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."ENGINE_MANIFEST_TBX" IS 'ENGINE MANIFEST';


-- DDL Statements for Indexes on Table "GALADM  "."ENGINE_MANIFEST_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."ENGINE_MANIFEST_I1" ON "GALADM  "."ENGINE_MANIFEST_TBX" 
		("ENGINE_NO" ASC,
		 "PLANT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."ENGINE_MANIFEST_TBX"

ALTER TABLE "GALADM  "."ENGINE_MANIFEST_TBX" 
	ADD CONSTRAINT "ENGINE_MANIFEST_PK" PRIMARY KEY
		("ENGINE_NO",
		 "PLANT");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ENGINE_MANIFEST_TBX_TR1";

CREATE TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ENGINE_MANIFEST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."ENGINE_MANIFEST_TBX_TR2";

CREATE TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ENGINE_MANIFEST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


