
------------------------------------------------
-- DDL Statements for Table "GALADM  "."EQUIP_FAULT_CODE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."EQUIP_FAULT_CODE_TBX";


CREATE TABLE "GALADM  "."EQUIP_FAULT_CODE_TBX"  (
		  "UNIT_ID" SMALLINT NOT NULL , 
		  "FAULT_CODE" INTEGER NOT NULL , 
		  "FAULT_DESCRIPTION" VARCHAR(60 OCTETS) , 
		  "IS_CONTROLLABLE" SMALLINT WITH DEFAULT 1 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."EQUIP_FAULT_CODE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."EQUIP_FAULT_CODE_TBX_I1" ON "GALADM  "."EQUIP_FAULT_CODE_TBX" 
		("UNIT_ID" ASC,
		 "FAULT_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."EQUIP_FAULT_CODE_TBX"

ALTER TABLE "GALADM  "."EQUIP_FAULT_CODE_TBX" 
	ADD CONSTRAINT "EQUIP_FAULT_CODE_PK" PRIMARY KEY
		("UNIT_ID",
		 "FAULT_CODE");




-- DDL Statements for Foreign Keys on Table "GALADM  "."EQUIP_FAULT_CODE_TBX"

ALTER TABLE "GALADM  "."EQUIP_FAULT_CODE_TBX" 
	ADD CONSTRAINT "REF_EQUIP_UNIT_FAULT_FK1" FOREIGN KEY
		("UNIT_ID")
	REFERENCES "GALADM  "."EQUIP_UNIT_FAULT_TBX"
		("UNIT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_FAULT_CODE_TR1";

CREATE TRIGGER GALADM.EQUIP_FAULT_CODE_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_FAULT_CODE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_FAULT_CODE_TR2";

CREATE TRIGGER GALADM.EQUIP_FAULT_CODE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_FAULT_CODE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


