
------------------------------------------------
-- DDL Statements for Table "GALADM  "."EQUIP_UNIT_FAULT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."EQUIP_UNIT_FAULT_TBX";


CREATE TABLE "GALADM  "."EQUIP_UNIT_FAULT_TBX"  (
		  "UNIT_ID" SMALLINT NOT NULL , 
		  "UNIT_NAME" VARCHAR(50 OCTETS) , 
		  "CURRENT_FAULT_CODE" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "IS_MANUAL_IMPORT" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."EQUIP_UNIT_FAULT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."EQUIP_UNIT_FAULT_I1" ON "GALADM  "."EQUIP_UNIT_FAULT_TBX" 
		("UNIT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."EQUIP_UNIT_FAULT_TBX"

ALTER TABLE "GALADM  "."EQUIP_UNIT_FAULT_TBX" 
	ADD CONSTRAINT "EQUIP_UNIT_FAULT_PK" PRIMARY KEY
		("UNIT_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_UNIT_FAULT_TR1";

CREATE TRIGGER GALADM.EQUIP_UNIT_FAULT_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_UNIT_FAULT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_UNIT_FAULT_TR2";

CREATE TRIGGER GALADM.EQUIP_UNIT_FAULT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_UNIT_FAULT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


