
------------------------------------------------
-- DDL Statements for Table "GALADM  "."EQUIP_GROUP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."EQUIP_GROUP_TBX";


CREATE TABLE "GALADM  "."EQUIP_GROUP_TBX"  (
		  "GROUP_ID" SMALLINT NOT NULL , 
		  "GROUP_NAME" VARCHAR(50 OCTETS) NOT NULL , 
		  "GROUP_DESCRIPTION" VARCHAR(100 OCTETS) NOT NULL , 
		  "FAULT_COUNT" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."EQUIP_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."EQUIP_GROUP_I1" ON "GALADM  "."EQUIP_GROUP_TBX" 
		("GROUP_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."EQUIP_GROUP_TBX"

ALTER TABLE "GALADM  "."EQUIP_GROUP_TBX" 
	ADD CONSTRAINT "EQUIP_GROUP_PK" PRIMARY KEY
		("GROUP_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_GROUP_TR1";

CREATE TRIGGER GALADM.EQUIP_GROUP_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_GROUP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EQUIP_GROUP_TR2";

CREATE TRIGGER GALADM.EQUIP_GROUP_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_GROUP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


