
------------------------------------------------
-- DDL Statements for Table "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX";


CREATE TABLE "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PARSE_STRATEGY" VARCHAR(32 OCTETS) NOT NULL , 
		  "PARSE_INFORMATION" VARCHAR(64 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PART_GROUP" VARCHAR(32 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX" IS 'RMT table for required parts';


-- DDL Statements for Primary Key on Table "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX"

ALTER TABLE "GALADM  "."EXT_REQUIRED_PART_SPEC_TBX" 
	ADD CONSTRAINT "EXT_REQUIRED_PART_SPEC_PK" PRIMARY KEY
		("PART_NAME",
		 "PART_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EXT_REQUIRED_PART_SPEC_TR1";

CREATE TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.EXT_REQUIRED_PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."EXT_REQUIRED_PART_SPEC_TR2";

CREATE TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.EXT_REQUIRED_PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


