
------------------------------------------------
-- DDL Statements for Table "GALADM  "."FEATURE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."FEATURE_TBX";


CREATE TABLE "GALADM  "."FEATURE_TBX"  (
		  "FEATURE_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) NOT NULL , 
		  "REFERENCE_ID" VARCHAR(32 OCTETS) , 
		  "REFERENCE_TYPE" VARCHAR(32 OCTETS) , 
		  "ENABLE_HISTORY" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."FEATURE_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."FEATURE_TBX" IS 'RMT Feature for visualizing information';


-- DDL Statements for Primary Key on Table "GALADM  "."FEATURE_TBX"

ALTER TABLE "GALADM  "."FEATURE_TBX" 
	ADD CONSTRAINT "FEATURE_PK" PRIMARY KEY
		("FEATURE_ID",
		 "FEATURE_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_TR1";

CREATE TRIGGER GALADM.FEATURE_TR1 NO CASCADE BEFORE INSERT ON GALADM.FEATURE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_TR2";

CREATE TRIGGER GALADM.FEATURE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.FEATURE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


