
------------------------------------------------
-- DDL Statements for Table "GALADM  "."FEATURE_POINTS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."FEATURE_POINTS_TBX";


CREATE TABLE "GALADM  "."FEATURE_POINTS_TBX"  (
		  "FEATURE_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "FEATURE_SEQ" INTEGER NOT NULL , 
		  "X_COORDINATE" DOUBLE , 
		  "Y_COORDINATE" DOUBLE , 
		  "Z_COORDINATE" DOUBLE , 
		  "CHILD_FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "SPATIAL_REFERENCE_SYSTEM" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."FEATURE_POINTS_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."FEATURE_POINTS_TBX" IS 'RMT FeaturePoint coordinates for visualizing information';


-- DDL Statements for Primary Key on Table "GALADM  "."FEATURE_POINTS_TBX"

ALTER TABLE "GALADM  "."FEATURE_POINTS_TBX" 
	ADD CONSTRAINT "FEATURE_POINTS_PK" PRIMARY KEY
		("FEATURE_ID",
		 "FEATURE_SEQ");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_POINTS_TR1";

CREATE TRIGGER GALADM.FEATURE_POINTS_TR1 NO CASCADE BEFORE INSERT ON GALADM.FEATURE_POINTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_POINTS_TR2";

CREATE TRIGGER GALADM.FEATURE_POINTS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.FEATURE_POINTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


