
------------------------------------------------
-- DDL Statements for Table "GALADM  "."FEATURE_TYPE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."FEATURE_TYPE_TBX";


CREATE TABLE "GALADM  "."FEATURE_TYPE_TBX"  (
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) NOT NULL , 
		  "FEATURE_SHAPE" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."FEATURE_TYPE_TBX" IS 'RMT Feature Types for visualizing information';


-- DDL Statements for Primary Key on Table "GALADM  "."FEATURE_TYPE_TBX"

ALTER TABLE "GALADM  "."FEATURE_TYPE_TBX" 
	ADD CONSTRAINT "FEATURE_TYPE_PK" PRIMARY KEY
		("FEATURE_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_TYPE_TR1";

CREATE TRIGGER GALADM.FEATURE_TYPE_TR1 NO CASCADE BEFORE INSERT ON GALADM.FEATURE_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FEATURE_TYPE_TR2";

CREATE TRIGGER GALADM.FEATURE_TYPE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.FEATURE_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


