
------------------------------------------------
-- DDL Statements for Table "GALADM  "."FIF_CODE_GROUPS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."FIF_CODE_GROUPS_TBX";


CREATE TABLE "GALADM  "."FIF_CODE_GROUPS_TBX"  (
		  "PLANT_CD" VARCHAR(4 OCTETS) NOT NULL , 
		  "MODEL_YEAR" VARCHAR(1 OCTETS) NOT NULL , 
		  "MODEL_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "DEV_SEQ_CD" VARCHAR(1 OCTETS) NOT NULL , 
		  "BASE_TYPE" VARCHAR(3 OCTETS) NOT NULL , 
		  "FIF_TYPE" VARCHAR(3 OCTETS) NOT NULL , 
		  "GROUP_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "GROUP_DESC" VARCHAR(30 OCTETS) NOT NULL , 
		  "EFCT_BEG_DT" DATE NOT NULL , 
		  "EFCT_END_DT" DATE NOT NULL , 
		  "REQUIRED" VARCHAR(1 OCTETS) NOT NULL , 
		  "FIF_LENGTH" SMALLINT NOT NULL , 
		  "FIF_OFFSET" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."FIF_CODE_GROUPS_TBX" IS 'RGALC table corresponding to  GPCS GMM90D00';


-- DDL Statements for Primary Key on Table "GALADM  "."FIF_CODE_GROUPS_TBX"

ALTER TABLE "GALADM  "."FIF_CODE_GROUPS_TBX" 
	ADD CONSTRAINT "FIF_CODE_GROUPS_PK" PRIMARY KEY
		("PLANT_CD",
		 "MODEL_YEAR",
		 "MODEL_CD",
		 "DEV_SEQ_CD",
		 "BASE_TYPE",
		 "FIF_TYPE",
		 "GROUP_CD",
		 "EFCT_BEG_DT");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FIF_CODE_GROUPS_TR1";

CREATE TRIGGER GALADM.FIF_CODE_GROUPS_TR1 NO CASCADE BEFORE INSERT ON GALADM.FIF_CODE_GROUPS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FIF_CODE_GROUPS_TR2";

CREATE TRIGGER GALADM.FIF_CODE_GROUPS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.FIF_CODE_GROUPS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


