
------------------------------------------------
-- DDL Statements for Table "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX";


CREATE TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX"  (
		  "FRM_MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "FRM_MODEL_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "FRM_MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "FRM_MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "ENG_MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "ENG_MODEL_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "ENG_MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "ENG_MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "UPDT_USERID" CHAR(11 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT5" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX" PCTFREE 0;

ALTER TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX" IS 'Engine to frame models mapping.';


-- DDL Statements for Primary Key on Table "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX"

ALTER TABLE "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX" 
	ADD CONSTRAINT "FRAME_ENGINE_MODEL_MAP_TBX_PK" PRIMARY KEY
		("FRM_MODEL_YEAR_CODE",
		 "FRM_MODEL_CODE",
		 "FRM_MODEL_TYPE_CODE",
		 "FRM_MODEL_OPTION_CODE",
		 "ENG_MODEL_YEAR_CODE",
		 "ENG_MODEL_CODE",
		 "ENG_MODEL_TYPE_CODE",
		 "ENG_MODEL_OPTION_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX_TR1";

CREATE TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR1
	NO CASCADE BEFORE INSERT
	ON GALADM.FRAME_ENGINE_MODEL_MAP_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."FRAME_ENGINE_MODEL_MAP_TBX_TR2";

CREATE TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR2
	NO CASCADE BEFORE UPDATE
	ON GALADM.FRAME_ENGINE_MODEL_MAP_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


