
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL179TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL179TBX";


CREATE TABLE "GALADM  "."GAL179TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_DESC_SHORT" VARCHAR(10 OCTETS) , 
		  "INSPECTION_PART_DESC_LONG" VARCHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL179TBX" IS 'RMT InspectionPart for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL179TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL179I1" ON "GALADM  "."GAL179TBX" 
		("INSPECTION_PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL179TBX"

ALTER TABLE "GALADM  "."GAL179TBX" 
	ADD CONSTRAINT "GAL179_PK" PRIMARY KEY
		("INSPECTION_PART_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL179_TR1";

CREATE TRIGGER GALADM.GAL179_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL179TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL179_TR2";

CREATE TRIGGER GALADM.GAL179_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL179TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


