
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL120TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL120TBX";


CREATE TABLE "GALADM  "."GAL120TBX"  (
		  "PASSING_COUNTER" INTEGER , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL120TBX" IS 'RMT CounterByProductionLot for summarizing number of production lots built by process point, production date, shift, period';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL120TBX"

ALTER TABLE "GALADM  "."GAL120TBX" 
	ADD CONSTRAINT "GAL120_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD",
		 "PRODUCTION_LOT");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL120_TR1";

CREATE TRIGGER GALADM.GAL120_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL120TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL120_TR2";

CREATE TRIGGER GALADM.GAL120_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL120TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


