
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL106TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL106TBX";


CREATE TABLE "GALADM  "."GAL106TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "NUMBER_OF_MAINS" INTEGER , 
		  "NUMBER_OF_CONS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "CONROD_WEIGHT_INDEX" VARCHAR(5 OCTETS),
 		  "CONROD_RANK_INDEX" VARCHAR(5 OCTETS),
  		  "CRANK_CON_INDEX" VARCHAR(7 OCTETS),
  		  "CRANK_MAIN_INDEX" VARCHAR(7 OCTETS),
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL106TBX" IS 'RMT Bearing Matrix';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL106TBX"

ALTER TABLE "GALADM  "."GAL106TBX" 
	ADD CONSTRAINT "GAL106_PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE");



-- DDL Statements for Indexes on Table "GALADM  "."GAL106TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL106_I2" ON "GALADM  "."GAL106TBX" 
		("MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "NUMBER_OF_CONS" ASC,
		 "NUMBER_OF_MAINS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL106_TR1";

CREATE TRIGGER GALADM.GAL106_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL106TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL106_TR2";

CREATE TRIGGER GALADM.GAL106_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL106TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


