
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL133TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL133TBX";


CREATE TABLE "GALADM  "."GAL133TBX"  (
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MISSION_PLANT_CODE" CHAR(4 OCTETS) , 
		  "MISSION_MODEL_CODE" CHAR(3 OCTETS) , 
		  "MISSION_PROTOTYPE_CODE" CHAR(1 OCTETS) , 
		  "MISSION_MODEL_TYPE_CODE" CHAR(3 OCTETS) , 
		  "ENGINE_NO_PREFIX" CHAR(5 OCTETS) , 
		  "TRANSMISSION" CHAR(5 OCTETS) , 
		  "TRANSMISSION_DESCRIPTION" CHAR(20 OCTETS) , 
		  "GEAR_SHIFT" CHAR(1 OCTETS) , 
		  "GEAR_SHIFT_DESCRIPTION" CHAR(20 OCTETS) , 
		  "DISPLACEMENT" CHAR(5 OCTETS) , 
		  "DISPLACEMENT_COMMENT" CHAR(20 OCTETS) , 
		  "ENGINE_PROTOTYPE_CODE" CHAR(1 OCTETS) , 
		  "PLANT_CODE" CHAR(4 OCTETS) , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) , 
		  "MODEL_YEAR_DESCRIPTION" CHAR(4 OCTETS) , 
		  "MISSION_MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL133TBX" IS 'RMT EngineSpec';


-- DDL Statements for Indexes on Table "GALADM  "."GAL133TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL133I1" ON "GALADM  "."GAL133TBX" 
		("PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL133TBX"

ALTER TABLE "GALADM  "."GAL133TBX" 
	ADD CONSTRAINT "GAL133_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE");




-- DDL Statements for Indexes on Table "GALADM  "."GAL133TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL133I2" ON "GALADM  "."GAL133TBX" 
		("PRODUCT_SPEC_CODE" ASC,
		 "MISSION_MODEL_CODE" ASC,
		 "MISSION_MODEL_TYPE_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL133_TR1";

CREATE TRIGGER GALADM.GAL133_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL133TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL133_TR2";

CREATE TRIGGER GALADM.GAL133_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL133TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


