
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL127TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL127TBX";


CREATE TABLE "GALADM  "."GAL127TBX"  (
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SECONDARY_PART_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL127TBX" IS 'RMT DefectTypeDescription for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL127I1" ON "GALADM  "."GAL127TBX" 
		("DEFECT_TYPE_NAME" ASC,
		 "SECONDARY_PART_NAME" ASC,
		 "DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL127TBX"

ALTER TABLE "GALADM  "."GAL127TBX" 
	ADD CONSTRAINT "GAL127_PK" PRIMARY KEY
		("DEFECT_TYPE_NAME",
		 "SECONDARY_PART_NAME",
		 "DEFECT_GROUP_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I2" ON "GALADM  "."GAL127TBX" 
		("DEFECT_GROUP_NAME" ASC,
		 "DEFECT_TYPE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I3" ON "GALADM  "."GAL127TBX" 
		("DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I4" ON "GALADM  "."GAL127TBX" 
		("DEFECT_TYPE_NAME" ASC,
		 "DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I5" ON "GALADM  "."GAL127TBX" 
		("DEFECT_TYPE_NAME" ASC,
		 "SECONDARY_PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I6" ON "GALADM  "."GAL127TBX" 
		("DEFECT_TYPE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL127TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL127I7" ON "GALADM  "."GAL127TBX" 
		("SECONDARY_PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL127_TR1";

CREATE TRIGGER GALADM.GAL127_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL127TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL127_TR2";

CREATE TRIGGER GALADM.GAL127_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL127TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


