
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL158TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL158TBX";


CREATE TABLE "GALADM  "."GAL158TBX"  (
		  "PLANT_CODE_FRAME" CHAR(4 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_DESCRIPTION" CHAR(4 OCTETS) , 
		  "EXT_COLOR_DESCRIPTION" CHAR(10 OCTETS) , 
		  "INT_COLOR_DESCRIPTION" CHAR(40 OCTETS) , 
		  "FRAME_NO_PREFIX" CHAR(11 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SERIES_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SERIES_DESCRIPTION" CHAR(40 OCTETS) , 
		  "GRADE_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BODY_AND_TRANS_TYPE_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BODY_AND_TRANS_TYPE_DESC" CHAR(30 OCTETS) , 
		  "SALES_MODEL_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SALES_MODEL_TYPE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SALES_MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SALES_EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SALES_INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROTOTYPE_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "F_E" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_CODE_ENGINE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ENGINE_MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ENGINE_MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ENGINE_MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ENGINE_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "COMMON_SALES_MODEL_CODE" CHAR(11 OCTETS) , 
		  "COMMON_SALES_MODEL_TYPE_CODE" CHAR(4 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL158TBX" IS 'RMT HostMtoc for OIF Frame MTO Master Specification';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL158TBX"

ALTER TABLE "GALADM  "."GAL158TBX" 
	ADD CONSTRAINT "GAL158_PK" PRIMARY KEY
		("PLANT_CODE_FRAME",
		 "MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "EXT_COLOR_CODE",
		 "INT_COLOR_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL158_TR1";

CREATE TRIGGER GALADM.GAL158_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL158TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL158_TR2";

CREATE TRIGGER GALADM.GAL158_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL158TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


