
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL143TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL143TBX";


CREATE TABLE "GALADM  "."GAL143TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ENGINE_SERIAL_NO" CHAR(17 OCTETS) , 
		  "MISSION_SERIAL_NO" CHAR(20 OCTETS) , 
		  "STRAIGHT_SHIP_PERCENTAGE" DOUBLE , 
		  "KEY_NO" CHAR(7 OCTETS) , 
		  "SHORT_VIN" CHAR(11 OCTETS) , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "TRACKING_STATUS" CHAR(16 OCTETS) , 
		  "PRODUCT_START_DATE" DATE , 
		  "ACTUAL_OFF_DATE" DATE , 
		  "AUTO_HOLD_STATUS" SMALLINT , 
		  "PRODUCTION_DATE" DATE , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "ENGINE_STATUS" INTEGER , 
		  "AF_ON_SEQUENCE_NUMBER" INTEGER , 
		  "ACTUAL_MISSION_TYPE" CHAR(22 OCTETS) , 
		  "PURCHASE_CONTRACT_NUMBER" CHAR(7),
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL143TBX" IS 'RMT Frame';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL143TBX"

ALTER TABLE "GALADM  "."GAL143TBX" 
	ADD CONSTRAINT "GAL143_PK" PRIMARY KEY
		("PRODUCT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I9" ON "GALADM  "."GAL143TBX" 
		("KD_LOT_NUMBER" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I1" ON "GALADM  "."GAL143TBX" 
		("ENGINE_SERIAL_NO" ASC,
		 "AF_ON_SEQUENCE_NUMBER" ASC,
		 "PRODUCT_SPEC_CODE" ASC,
		 "MISSION_SERIAL_NO" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I2" ON "GALADM  "."GAL143TBX" 
		("PRODUCT_ID" ASC,
		 "ENGINE_SERIAL_NO" ASC,
		 "AF_ON_SEQUENCE_NUMBER" ASC,
		 "PRODUCT_SPEC_CODE" ASC,
		 "MISSION_SERIAL_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I3" ON "GALADM  "."GAL143TBX" 
		("LAST_PASSING_PROCESS_POINT_ID" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I4" ON "GALADM  "."GAL143TBX" 
		("PRODUCT_SPEC_CODE" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I5" ON "GALADM  "."GAL143TBX" 
		("PRODUCT_ID" ASC,
		 "ENGINE_SERIAL_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I6" ON "GALADM  "."GAL143TBX" 
		("ENGINE_SERIAL_NO" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I7" ON "GALADM  "."GAL143TBX" 
		("TRACKING_STATUS" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL143TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL143_I8" ON "GALADM  "."GAL143TBX" 
		("PRODUCTION_LOT" ASC,
		 "PRODUCT_SPEC_CODE" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL143_TR1";

CREATE TRIGGER GALADM.GAL143_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL143TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL143_TR2";

CREATE TRIGGER GALADM.GAL143_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL143TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

