
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL119TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL119TBX";


CREATE TABLE "GALADM  "."GAL119TBX"  (
		  "PASSING_COUNTER" INTEGER , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL119TBX" IS 'RMT CounterByProductSpec for summarizing number of product specs built by process point, production date, shift, period';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL119TBX"

ALTER TABLE "GALADM  "."GAL119TBX" 
	ADD CONSTRAINT "GAL119_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD",
		 "PRODUCT_SPEC_CODE");



-- DDL Statements for Indexes on Table "GALADM  "."GAL119TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL119_I1" ON "GALADM  "."GAL119TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PRODUCTION_DATE" ASC,
		 "PASSING_COUNTER" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL119_TR1";

CREATE TRIGGER GALADM.GAL119_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL119TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL119_TR2";

CREATE TRIGGER GALADM.GAL119_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL119TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


