
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL174TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL174TBX";


CREATE TABLE "GALADM  "."GAL174TBX"  (
		  "IMAGE_SECTION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "IMAGE_NAME" VARCHAR(20 OCTETS) , 
		  "PART_KIND_FLAG" SMALLINT , 
		  "DESCRIPTION_ID" INTEGER , 
		  "OVERLAY_NO" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL174TBX" PCTFREE 0;

ALTER TABLE "GALADM  "."GAL174TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL174TBX" IS 'RMT ImageSection for QICS';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL174TBX"

ALTER TABLE "GALADM  "."GAL174TBX" 
	ADD CONSTRAINT "GAL174_PK" PRIMARY KEY
		("IMAGE_SECTION_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL174TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL174_I1" ON "GALADM  "."GAL174TBX" 
		("OVERLAY_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL174_TR1";

CREATE TRIGGER GALADM.GAL174_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL174TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL174_TR2";

CREATE TRIGGER GALADM.GAL174_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL174TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


