
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL144TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL144TBX";


CREATE TABLE "GALADM  "."GAL144TBX"  (
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) , 
		  "EXT_COLOR_DESCRIPTION" CHAR(10 OCTETS) , 
		  "INT_COLOR_DESCRIPTION" CHAR(40 OCTETS) , 
		  "PLANT_CODE_GPCS" CHAR(4 OCTETS) , 
		  "ENGINE_PLANT_CODE" CHAR(4 OCTETS) , 
		  "ENGINE_MTO" CHAR(10 OCTETS) , 
		  "SALES_MODEL_CODE" CHAR(10 OCTETS) , 
		  "SALES_MODEL_TYPE_CODE" CHAR(2 OCTETS) , 
		  "SALES_EXT_COLOR_CODE" CHAR(10 OCTETS) , 
		  "SALES_INT_COLOR_CODE" CHAR(2 OCTETS) , 
		  "PROTOTYPE_CODE" CHAR(1 OCTETS) , 
		  "FRAME_NO_PREFIX" CHAR(11 OCTETS) , 
		  "SERIES_CODE" CHAR(1 OCTETS) , 
		  "SERIES_DESCRIPTION" CHAR(40 OCTETS) , 
		  "GRADE_CODE" CHAR(10 OCTETS) , 
		  "BODY_AND_TRANS_TYPE_CODE" CHAR(1 OCTETS) , 
		  "BODY_AND_TRANS_TYPE_DESC" CHAR(30 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) , 
		  "MODEL_YEAR_DESCRIPTION" CHAR(4 OCTETS) , 
		  "BOUNDARY_MARK_REQUIRED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "ALT_ENGINE_MTO" CHAR(10 OCTETS) , 
		  "MODEL_DESCRIPTION" CHAR(40 OCTETS) , 
		  "SHORT_MODEL_DESCRIPTION" CHAR(15 OCTETS) , 
		  "COMMON_SALES_MODEL_CODE" CHAR(11 OCTETS) , 
		  "COMMON_SALES_MODEL_TYPE_CODE" CHAR(4 OCTETS) )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL144TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL144TBX" IS 'RMT FrameSpec';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL144TBX"

ALTER TABLE "GALADM  "."GAL144TBX" 
	ADD CONSTRAINT "GAL144_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE");



-- DDL Statements for Indexes on Table "GALADM  "."GAL144TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL144_I1" ON "GALADM  "."GAL144TBX" 
		("PRODUCT_SPEC_CODE" ASC,
		 "SALES_MODEL_TYPE_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL144TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL144_I2" ON "GALADM  "."GAL144TBX" 
		("MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "EXT_COLOR_CODE" ASC,
		 "MODEL_YEAR_CODE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "MODEL_OPTION_CODE" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL144_TR1";

CREATE TRIGGER GALADM.GAL144_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL144TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL144_TR2";

CREATE TRIGGER GALADM.GAL144_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL144TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


