
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL192TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL192TBX";


CREATE TABLE "GALADM  "."GAL192TBX"  (
		  "IQS_CATEGORY_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "IQS_ITEM_NAME" CHAR(64 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "COEFFICIENT" CHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL192TBX" IS 'RMT IQS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL192TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL192I1" ON "GALADM  "."GAL192TBX" 
		("IQS_CATEGORY_NAME" ASC,
		 "IQS_ITEM_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL192TBX"

ALTER TABLE "GALADM  "."GAL192TBX" 
	ADD CONSTRAINT "GAL192_PK" PRIMARY KEY
		("IQS_CATEGORY_NAME",
		 "IQS_ITEM_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL192_TR1";

CREATE TRIGGER GALADM.GAL192_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL192TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL192_TR2";

CREATE TRIGGER GALADM.GAL192_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL192TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


