
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL195TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL195TBX";


CREATE TABLE "GALADM  "."GAL195TBX"  (
		  "LINE_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_ID" CHAR(16 OCTETS) , 
		  "DIVISION_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME1" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME2" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LINE_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LINE_TYPE" INTEGER , 
		  "LINE_DESCRIPTION" CHAR(128 OCTETS) , 
		  "ENTRY_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "LINE_SEQUENCE_NUMBER" INTEGER , 
		  "STD_INVENTORY" INTEGER , 
		  "MAXIMUM_INVENTORY" INTEGER , 
		  "MINIMUM_INVENTORY" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL195TBX" IS 'RMT Line';


-- DDL Statements for Indexes on Table "GALADM  "."GAL195TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL195I1" ON "GALADM  "."GAL195TBX" 
		("LINE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL195TBX"

ALTER TABLE "GALADM  "."GAL195TBX" 
	ADD CONSTRAINT "GAL195_PK" PRIMARY KEY
		("LINE_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL195TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL195_I2" ON "GALADM  "."GAL195TBX" 
		("DIVISION_ID" ASC,
		 "LINE_ID" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL195TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL195_I1" ON "GALADM  "."GAL195TBX" 
		("LINE_ID" ASC)
		INCLUDE ("DIVISION_ID" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL195_TR1";

CREATE TRIGGER GALADM.GAL195_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL195TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL195_TR2";

CREATE TRIGGER GALADM.GAL195_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL195TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


