
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL175TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL175TBX";


CREATE TABLE "GALADM  "."GAL175TBX"  (
		  "IMAGE_SECTION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POINT_SEQUENCE_NO" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POINT_X" INTEGER , 
		  "POINT_Y" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL175TBX" IS 'RMT ImageSectionPoint for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL175TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL175I1" ON "GALADM  "."GAL175TBX" 
		("IMAGE_SECTION_ID" ASC,
		 "POINT_SEQUENCE_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL175TBX"

ALTER TABLE "GALADM  "."GAL175TBX" 
	ADD CONSTRAINT "GAL175_PK" PRIMARY KEY
		("IMAGE_SECTION_ID",
		 "POINT_SEQUENCE_NO");




-- DDL Statements for Indexes on Table "GALADM  "."GAL175TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL175_I1" ON "GALADM  "."GAL175TBX" 
		("IMAGE_SECTION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL175_TR1";

CREATE TRIGGER GALADM.GAL175_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL175TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL175_TR2";

CREATE TRIGGER GALADM.GAL175_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL175TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


