
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL123TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL123TBX";


CREATE TABLE "GALADM  "."GAL123TBX"  (
		  "DEFECT_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_GROUP_DESCRIPTION_SHORT" VARCHAR(10 OCTETS) , 
		  "DEFECT_GROUP_DESCRIPTION_LONG" VARCHAR(30 OCTETS) , 
		  "IMAGE_NAME" VARCHAR(20 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL123TBX" IS 'RMT DefectGroup for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL123TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL123I1" ON "GALADM  "."GAL123TBX" 
		("DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL123TBX"

ALTER TABLE "GALADM  "."GAL123TBX" 
	ADD CONSTRAINT "GAL123_PK" PRIMARY KEY
		("DEFECT_GROUP_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."GAL123TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL123I2" ON "GALADM  "."GAL123TBX" 
		("DEFECT_GROUP_NAME" ASC,
		 "IMAGE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL123TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL123I3" ON "GALADM  "."GAL123TBX" 
		("DEFECT_GROUP_NAME" ASC,
		 "DEFECT_GROUP_DESCRIPTION_LONG" ASC,
		 "DEFECT_GROUP_DESCRIPTION_SHORT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL123TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL123I4" ON "GALADM  "."GAL123TBX" 
		("IMAGE_NAME" ASC,
		 "DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL123TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL123_I4" ON "GALADM  "."GAL123TBX" 
		("MODEL_CODE" ASC,
		 "DEFECT_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL123_TR1";

CREATE TRIGGER GALADM.GAL123_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL123TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL123_TR2";

CREATE TRIGGER GALADM.GAL123_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL123TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


