
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL147TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL147TBX";


CREATE TABLE "GALADM  "."GAL147TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "HOLD_TYPE" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "RELEASE_TIMESTAMP" TIMESTAMP , 
		  "RELEASE_FLAG" SMALLINT , 
		  "HOLD_ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "HOLD_ASSOCIATE_NAME" CHAR(30 OCTETS) , 
		  "HOLD_ASSOCIATE_PHONE" CHAR(20 OCTETS) , 
		  "HOLD_ASSOCIATE_PAGER" CHAR(15 OCTETS) , 
		  "HOLD_REASON" CHAR(80 OCTETS) , 
		  "RELEASE_ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "RELEASE_ASSOCIATE_NAME" CHAR(30 OCTETS) , 
		  "RELEASE_ASSOCIATE_PHONE" CHAR(20 OCTETS) , 
		  "RELEASE_ASSOCIATE_PAGER" CHAR(15 OCTETS) , 
		  "RELEASE_REASON" CHAR(80 OCTETS) , 
		  "LOT_HOLD_STATUS" INTEGER , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "QSR_ID" INTEGER , 
		  "HOLD_PROCESS_POINT" CHAR(16 OCTETS) , 
		  "EQUIPMENT_FLAG" INTEGER WITH DEFAULT 0 , 
		  "RELEASE_PERMISSION" INTEGER WITH DEFAULT 0 )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL147TBX" IS 'RMT HoldResult';


-- DDL Statements for Indexes on Table "GALADM  "."GAL147TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL147I1" ON "GALADM  "."GAL147TBX" 
		("PRODUCT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC,
		 "HOLD_TYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL147TBX"

ALTER TABLE "GALADM  "."GAL147TBX" 
	ADD CONSTRAINT "GAL147_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ACTUAL_TIMESTAMP",
		 "HOLD_TYPE");




-- DDL Statements for Indexes on Table "GALADM  "."GAL147TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL147_L2" ON "GALADM  "."GAL147TBX" 
		("QSR_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL147_TR1";

CREATE TRIGGER GALADM.GAL147_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL147TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL147_TR2";

CREATE TRIGGER GALADM.GAL147_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL147TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


