
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL173TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL173TBX";


CREATE TABLE "GALADM  "."GAL173TBX"  (
		  "IMAGE_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "IMAGE_DESCRIPTION_SHORT" VARCHAR(10 OCTETS) , 
		  "IMAGE_DESCRIPTION_LONG" VARCHAR(30 OCTETS) , 
		  "BITMAP_FILE_NAME" VARCHAR(255 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "IMAGE_DATA" BLOB(1048576) LOGGED COMPACT )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL173TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL173TBX" IS 'RMT Image for QICS';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL173TBX"

ALTER TABLE "GALADM  "."GAL173TBX" 
	ADD CONSTRAINT "GAL173_PK" PRIMARY KEY
		("BITMAP_FILE_NAME");



-- DDL Statements for Indexes on Table "GALADM  "."GAL173TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL173_I1" ON "GALADM  "."GAL173TBX" 
		("IMAGE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL173_TR1";

CREATE TRIGGER GALADM.GAL173_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL173TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL173_TR2";

CREATE TRIGGER GALADM.GAL173_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL173TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


