
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL131TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL131TBX";


CREATE TABLE "GALADM  "."GAL131TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "VIN" CHAR(17 OCTETS) , 
		  "MISSION_SERIAL_NO" CHAR(20 OCTETS) , 
		  "ENGINE_FIRING_FLAG" SMALLINT WITH DEFAULT 0 , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "TRACKING_STATUS" CHAR(16 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "PRODUCT_START_DATE" DATE , 
		  "ACTUAL_OFF_DATE" DATE , 
		  "AUTO_HOLD_STATUS" SMALLINT , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "MISSION_STATUS" INTEGER , 
		  "FIRING_TYPE" INTEGER , 
		  "REPAIR_FLAG" SMALLINT , 
		  "ACTUAL_MISSION_TYPE" CHAR(22 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DEFECT_STATUS" SMALLINT , 
		  "PLANT_CODE" CHAR(4 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL131TBX" IS 'RMT Engine';


-- DDL Statements for Indexes on Table "GALADM  "."GAL131TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL131I1" ON "GALADM  "."GAL131TBX" 
		("PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL131TBX"

ALTER TABLE "GALADM  "."GAL131TBX" 
	ADD CONSTRAINT "GAL131_PK" PRIMARY KEY
		("PRODUCT_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL131TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL131I2" ON "GALADM  "."GAL131TBX" 
		("PRODUCT_ID" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL131TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL131I3" ON "GALADM  "."GAL131TBX" 
		("PRODUCT_ID" ASC,
		 "VIN" ASC,
		 "MISSION_SERIAL_NO" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL131TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL131I4" ON "GALADM  "."GAL131TBX" 
		("PRODUCTION_DATE" ASC,
		 "PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL131TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL131_I4" ON "GALADM  "."GAL131TBX" 
		("VIN" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL131_TR1";

CREATE TRIGGER GALADM.GAL131_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL131TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL131_TR2";

CREATE TRIGGER GALADM.GAL131_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL131TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


