
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL163TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL163TBX";


CREATE TABLE "GALADM  "."GAL163TBX"  (
		  "DATE_STRING" CHAR(6 OCTETS) , 
		  "TIME" CHAR(6 OCTETS) , 
		  "SEND_LOCATION" CHAR(1 OCTETS) , 
		  "TRAN_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VIN" CHAR(17 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PARKING_LOCATION" CHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PARK_CONTROL_NO" CHAR(6 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL163TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL163TBX" IS 'IF Park Change';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL163TBX"

ALTER TABLE "GALADM  "."GAL163TBX" 
	ADD CONSTRAINT "GAL163PK" PRIMARY KEY
		("VIN");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL163_TR1";

CREATE TRIGGER GALADM.GAL163_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL163TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL163_TR2";

CREATE TRIGGER GALADM.GAL163_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL163TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


