
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL118TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL118TBX";


CREATE TABLE "GALADM  "."GAL118TBX"  (
		  "PASSING_COUNTER" INTEGER , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL118TBX" IS 'RMT CounterByModelGroup for summarizing number of models built by process point, production date, shift, period';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL118TBX"

ALTER TABLE "GALADM  "."GAL118TBX" 
	ADD CONSTRAINT "GAL118_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD",
		 "MODEL_CODE",
		 "MODEL_YEAR_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL118_TR1";

CREATE TRIGGER GALADM.GAL118_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL118TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL118_TR2";

CREATE TRIGGER GALADM.GAL118_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL118TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


