
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL198TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL198TBX";


CREATE TABLE "GALADM  "."GAL198TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MEASUREMENT_SEQUENCE_NUMBER" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MEASUREMENT_VALUE" DOUBLE , 
		  "MEASUREMENT_STATUS" INTEGER , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "MEASUREMENT_ANGLE" DOUBLE , 
		  "PART_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PART_ID" CHAR(5 OCTETS) , 
		  "PART_REV" INTEGER , 
		  "MEASUREMENT_NAME" CHAR(32 OCTETS) , 
		  "MEASUREMENT_STRING_VALUE" CHAR(30 OCTETS) , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) , 
		  "METHOD_ID" VARCHAR(32 OCTETS) , 
		  "METHOD_DESCRIPTION" VARCHAR(64 OCTETS),
		  "DEFECT_REF_ID" BIGINT WITH DEFAULT 0)   

		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL198TBX" IS 'RMT Measurement';


-- DDL Statements for Indexes on Table "GALADM  "."GAL198TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL198I1" ON "GALADM  "."GAL198TBX" 
		("PRODUCT_ID" ASC,
		 "PART_NAME" ASC,
		 "MEASUREMENT_SEQUENCE_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL198TBX"

ALTER TABLE "GALADM  "."GAL198TBX" 
	ADD CONSTRAINT "GAL198PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PART_NAME",
		 "MEASUREMENT_SEQUENCE_NUMBER");




-- DDL Statements for Indexes on Table "GALADM  "."GAL198TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL198I2" ON "GALADM  "."GAL198TBX" 
		("ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL198TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL198_I1" ON "GALADM  "."GAL198TBX" 
		("PART_NAME" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL198_TR1";

CREATE TRIGGER GALADM.GAL198_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL198TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL198_TR2";

CREATE TRIGGER GALADM.GAL198_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL198TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL198_I3 ON GALADM.GAL198TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;
runstats on table GALADM.GAL198TBX   with distribution and detailed indexes all;
