
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL141TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL141TBX";


CREATE TABLE "GALADM  "."GAL141TBX"  (
		  "ENGINE_SERIAL_NO" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "RESULT_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "FIRING_TEST_TYPE" CHAR(20 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "FIRING_NOTES" VARCHAR(255 OCTETS) , 
		  "FIRING_STATUS" SMALLINT , 
		  "FIRING_BENCH_NO" INTEGER , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL141TBX" IS 'RMT EngineFiringResult';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL141TBX"

ALTER TABLE "GALADM  "."GAL141TBX" 
	ADD CONSTRAINT "GAL141_PK" PRIMARY KEY
		("ENGINE_SERIAL_NO",
		 "RESULT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL141_TR1";

CREATE TRIGGER GALADM.GAL141_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL141TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL141_TR2";

CREATE TRIGGER GALADM.GAL141_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL141TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


