
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL117TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL117TBX";


CREATE TABLE "GALADM  "."GAL117TBX"  (
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SITE_DESCRIPTION" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL117TBX" IS 'RMT Site';


-- DDL Statements for Indexes on Table "GALADM  "."GAL117TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL117I1" ON "GALADM  "."GAL117TBX" 
		("SITE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL117TBX"

ALTER TABLE "GALADM  "."GAL117TBX" 
	ADD CONSTRAINT "GAL117_PK" PRIMARY KEY
		("SITE_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL117_TR1";

CREATE TRIGGER GALADM.GAL117_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL117TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL117_TR2";

CREATE TRIGGER GALADM.GAL117_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL117TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


