
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL136TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL136TBX";


CREATE TABLE "GALADM  "."GAL136TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "EXCEPTIONAL_OUT_COMMENT" VARCHAR(255 OCTETS) , 
		  "EXCEPTIONAL_OUT_REASON_STRING" CHAR(64 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "LOCATION" VARCHAR(20 OCTETS) )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL136TBX" IS 'RMT ExceptionalOut';


-- DDL Statements for Indexes on Table "GALADM  "."GAL136TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL136I1" ON "GALADM  "."GAL136TBX" 
		("PRODUCT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL136TBX"

ALTER TABLE "GALADM  "."GAL136TBX" 
	ADD CONSTRAINT "GAL136_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ACTUAL_TIMESTAMP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL136_TR1";

CREATE TRIGGER GALADM.GAL136_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL136TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL136_TR2";

CREATE TRIGGER GALADM.GAL136_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL136TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


