
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL181TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL181TBX";


CREATE TABLE "GALADM  "."GAL181TBX"  (
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOC_DESC_SHORT" VARCHAR(10 OCTETS) , 
		  "INSPECTION_PART_LOC_DESC_LONG" VARCHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL181TBX" IS 'RMT InspectionPartLocation for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL181TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL181I1" ON "GALADM  "."GAL181TBX" 
		("INSPECTION_PART_LOCATION_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL181TBX"

ALTER TABLE "GALADM  "."GAL181TBX" 
	ADD CONSTRAINT "GAL181_PK" PRIMARY KEY
		("INSPECTION_PART_LOCATION_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL181_TR1";

CREATE TRIGGER GALADM.GAL181_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL181TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL181_TR2";

CREATE TRIGGER GALADM.GAL181_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL181TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


