
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL108TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL108TBX";


CREATE TABLE "GALADM  "."GAL108TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "JOURNAL_BLOCK_MEASUREMENTS" CHAR(6 OCTETS) , 
		  "JOURNAL_CRANK_MEASUREMENTS" CHAR(6 OCTETS) , 
		  "CONROD_CRANK_MEASUREMENTS" CHAR(6 OCTETS) , 
		  "CONROD_CONS_MEASUREMENTS" CHAR(6 OCTETS) , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "JOURNAL_UPPER_BEARING01" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING01" CHAR(30 OCTETS) , 
		  "JOURNAL_UPPER_BEARING02" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING02" CHAR(30 OCTETS) , 
		  "JOURNAL_UPPER_BEARING03" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING03" CHAR(30 OCTETS) , 
		  "JOURNAL_UPPER_BEARING04" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING04" CHAR(30 OCTETS) , 
		  "JOURNAL_UPPER_BEARING05" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING05" CHAR(30 OCTETS) , 
		  "JOURNAL_UPPER_BEARING06" CHAR(30 OCTETS) , 
		  "JOURNAL_LOWER_BEARING06" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING01" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING01" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING02" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING02" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING03" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING03" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING04" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING04" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING05" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING05" CHAR(30 OCTETS) , 
		  "CONROD_UPPER_BEARING06" CHAR(30 OCTETS) , 
		  "CONROD_LOWER_BEARING06" CHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL108TBX" IS 'RMT BearingSelectResult for tracking bearing used in a specific engine';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL108TBX"

ALTER TABLE "GALADM  "."GAL108TBX" 
	ADD CONSTRAINT "GAL108_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ACTUAL_TIMESTAMP");



-- DDL Statements for Indexes on Table "GALADM  "."GAL108TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL108_I1" ON "GALADM  "."GAL108TBX" 
		("ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL108_TR1";

CREATE TRIGGER GALADM.GAL108_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL108TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL108_TR2";

CREATE TRIGGER GALADM.GAL108_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL108TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


