
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL128TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL128TBX";


CREATE TABLE "GALADM  "."GAL128TBX"  (
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_DESCRIPTION" CHAR(128 OCTETS) , 
		  "DIVISION_NAME1" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME2" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL128TBX" IS 'RMT Division';


-- DDL Statements for Indexes on Table "GALADM  "."GAL128TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL128I1" ON "GALADM  "."GAL128TBX" 
		("DIVISION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL128TBX"

ALTER TABLE "GALADM  "."GAL128TBX" 
	ADD CONSTRAINT "GAL128PK" PRIMARY KEY
		("DIVISION_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL128TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL128I2" ON "GALADM  "."GAL128TBX" 
		("DIVISION_ID" ASC,
		 "DIVISION_NAME" ASC,
		 "DIVISION_NAME1" ASC,
		 "DIVISION_NAME2" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL128TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL128I3" ON "GALADM  "."GAL128TBX" 
		("DIVISION_ID" ASC,
		 "SEQUENCE_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL128TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL128I4" ON "GALADM  "."GAL128TBX" 
		("SITE_NAME" ASC,
		 "PLANT_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL128_TR1";

CREATE TRIGGER GALADM.GAL128_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL128TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL128_TR2";

CREATE TRIGGER GALADM.GAL128_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL128TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


