
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL125TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL125TBX";


CREATE TABLE "GALADM  "."GAL125TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SECONDARY_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECTRESULTID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TWO_PART_PAIR_PART" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TWO_PART_PAIR_LOCATION" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "SHIFT" CHAR(2 OCTETS) , 
		  "DATE" DATE , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "DEFECT_STATUS" SMALLINT , 
		  "IMAGE_NAME" VARCHAR(20 OCTETS) , 
		  "RESPONSIBLE_DEPT" VARCHAR(32 OCTETS) , 
		  "RESPONSIBLE_ZONE" VARCHAR(32 OCTETS) , 
		  "REPAIR_METHOD_NAME_PLAN" CHAR(64 OCTETS) , 
		  "REPAIR_TIME_PLAN" INTEGER , 
		  "REPAIR_ASSOCIATE_NO_PLAN" CHAR(11 OCTETS) , 
		  "REPAIR_ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "WRITE_UP_DEPARTMENT" VARCHAR(32 OCTETS) , 
		  "TWO_PART_DEFECT_FLAG" SMALLINT , 
		  "IQS_CATEGORY_NAME" CHAR(32 OCTETS) , 
		  "IQS_ITEM_NAME" CHAR(64 OCTETS) , 
		  "REGRESSION_CODE" CHAR(32 OCTETS) , 
		  "POINT_X" INTEGER , 
		  "POINT_Y" INTEGER , 
		  "ENTRY_DEPT" VARCHAR(32 OCTETS) , 
		  "OUTSTANDING_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "REPAIR_TIMESTAMP" TIMESTAMP , 
		  "RESPONSIBLE_LINE" VARCHAR(32 OCTETS) , 
		  "GDP_DEFECT" SMALLINT , 
		  "PART_GROUP_NAME" CHAR(20 OCTETS) , 
		  "NAQ_DEFECTRESULTID" BIGINT )   
		 IN "GALTBSDAT5" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL125TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL125TBX" IS 'RMT DefectResult for QICS recording defects to product';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL125TBX"

ALTER TABLE "GALADM  "."GAL125TBX" 
	ADD CONSTRAINT "GAL125_PK" PRIMARY KEY
		("INSPECTION_PART_NAME",
		 "INSPECTION_PART_LOCATION_NAME",
		 "DEFECT_TYPE_NAME",
		 "SECONDARY_PART_NAME",
		 "DEFECTRESULTID",
		 "APPLICATION_ID",
		 "PRODUCT_ID",
		 "TWO_PART_PAIR_PART",
		 "TWO_PART_PAIR_LOCATION");



-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I1" ON "GALADM  "."GAL125TBX" 
		("PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I2" ON "GALADM  "."GAL125TBX" 
		("PRODUCT_ID" ASC,
		 "ENTRY_DEPT" ASC,
		 "DEFECT_STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I3" ON "GALADM  "."GAL125TBX" 
		("DATE" ASC,
		 "ENTRY_DEPT" ASC,
		 "DEFECT_STATUS" ASC,
		 "SHIFT" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I4" ON "GALADM  "."GAL125TBX" 
		("DEFECTRESULTID" ASC,
		 "PRODUCT_ID" ASC,
		 "OUTSTANDING_FLAG" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I5" ON "GALADM  "."GAL125TBX" 
		("APPLICATION_ID" ASC,
		 "PRODUCT_ID" ASC,
		 "SHIFT" ASC,
		 "DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I6" ON "GALADM  "."GAL125TBX" 
		("DATE" ASC,
		 "OUTSTANDING_FLAG" ASC,
		 "APPLICATION_ID" ASC,
		 "SHIFT" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL125TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL125_I7" ON "GALADM  "."GAL125TBX" 
		("NAQ_DEFECTRESULTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL125_TR1";

CREATE TRIGGER GALADM.GAL125_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL125TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL125_TR2";

CREATE TRIGGER GALADM.GAL125_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL125TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


