
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL176TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL176TBX";


CREATE TABLE "GALADM  "."GAL176TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LINE_ID" CHAR(16 OCTETS) , 
		  "NEXT_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT5" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL176TBX" IS 'RMT InProcessProduct for LINE CONTROL';


-- DDL Statements for Indexes on Table "GALADM  "."GAL176TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL176I1" ON "GALADM  "."GAL176TBX" 
		("PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL176TBX"

ALTER TABLE "GALADM  "."GAL176TBX" 
	ADD CONSTRAINT "GAL176_PK" PRIMARY KEY
		("PRODUCT_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL176TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL176I2" ON "GALADM  "."GAL176TBX" 
		("NEXT_PRODUCT_ID" ASC,
		 "LINE_ID" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL176TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL176I3" ON "GALADM  "."GAL176TBX" 
		("NEXT_PRODUCT_ID" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL176TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL176I4" ON "GALADM  "."GAL176TBX" 
		("LINE_ID" ASC,
		 "CREATE_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL176_TR1";

CREATE TRIGGER GALADM.GAL176_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL176TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL176_TR2";

CREATE TRIGGER GALADM.GAL176_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL176TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


