
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL178TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL178TBX";


CREATE TABLE "GALADM  "."GAL178TBX"  (
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL178TBX" IS 'RMT InspectionModel for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL178TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL178I1" ON "GALADM  "."GAL178TBX" 
		("MODEL_CODE" ASC,
		 "PART_GROUP_NAME" ASC,
		 "DEFECT_GROUP_NAME" ASC,
		 "APPLICATION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL178TBX"

ALTER TABLE "GALADM  "."GAL178TBX" 
	ADD CONSTRAINT "GAL178_PK" PRIMARY KEY
		("MODEL_CODE",
		 "PART_GROUP_NAME",
		 "DEFECT_GROUP_NAME",
		 "APPLICATION_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL178TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL178I2" ON "GALADM  "."GAL178TBX" 
		("APPLICATION_ID" ASC,
		 "MODEL_CODE" ASC,
		 "PART_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL178_TR1";

CREATE TRIGGER GALADM.GAL178_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL178TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL178_TR2";

CREATE TRIGGER GALADM.GAL178_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL178TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


