
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL135TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL135TBX";


CREATE TABLE "GALADM  "."GAL135TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCT_ID" CHAR(17 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "LAST_PROCESSED_PRODUCT" CHAR(17 OCTETS) )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL135TBX" IS 'RMT ExpectedProduct for LOT CONTROL';


-- DDL Statements for Indexes on Table "GALADM  "."GAL135TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL135I1" ON "GALADM  "."GAL135TBX" 
		("PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL135TBX"

ALTER TABLE "GALADM  "."GAL135TBX" 
	ADD CONSTRAINT "GAL135_PK" PRIMARY KEY
		("PROCESS_POINT_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL135_TR1";

CREATE TRIGGER GALADM.GAL135_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL135TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL135_TR2";

CREATE TRIGGER GALADM.GAL135_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL135TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


