
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL111TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL111TBX";


CREATE TABLE "GALADM  "."GAL111TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SEQUENCE_NUMBER" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "DESTINATION_TYPE" INTEGER , 
		  "DESTINATION_ID" CHAR(32 OCTETS) , 
		  "REQUEST_ID" CHAR(32 OCTETS) , 
		  "ARGUMENT" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "AUTO_ENABLED" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CHECK_POINT" VARCHAR(50 OCTETS) , 
		  "CONDITION" VARCHAR(250 OCTETS) , 
		  "CONDITION_TYPE" VARCHAR(50 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL111TBX" IS 'RMT BroadcastDestination for setting up printing on a process point';


-- DDL Statements for Indexes on Table "GALADM  "."GAL111TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL111I1" ON "GALADM  "."GAL111TBX" 
		("PROCESS_POINT_ID" ASC,
		 "SEQUENCE_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL111TBX"

ALTER TABLE "GALADM  "."GAL111TBX" 
	ADD CONSTRAINT "GAL111PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "SEQUENCE_NUMBER");




-- DDL Statements for Check Constraints on Table "GALADM  "."GAL111TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."GAL111TBX" 
	ADD CONSTRAINT "AUTO_CHECK" CHECK 
		(AUTO_ENABLED IN (0,1))
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL111_TR1";

CREATE TRIGGER GALADM.GAL111_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL111TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL111_TR2";

CREATE TRIGGER GALADM.GAL111_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL111TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


