
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL107TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL107TBX";


CREATE TABLE "GALADM  "."GAL107TBX"  (
		  "BEARING_SERIAL_NO" CHAR(30 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BEARING_COLOR" CHAR(10 OCTETS) , 
		  "BEARING_TYPE" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL107TBX" IS 'RMT Bearing Part';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL107TBX"

ALTER TABLE "GALADM  "."GAL107TBX" 
	ADD CONSTRAINT "GAL107_PK" PRIMARY KEY
		("BEARING_SERIAL_NO");



-- DDL Statements for Indexes on Table "GALADM  "."GAL107TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL107_I2" ON "GALADM  "."GAL107TBX" 
		("BEARING_SERIAL_NO" ASC,
		 "BEARING_COLOR" ASC,
		 "BEARING_TYPE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL107_TR1";

CREATE TRIGGER GALADM.GAL107_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL107TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL107_TR2";

CREATE TRIGGER GALADM.GAL107_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL107TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


