
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL130TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL130TBX";


CREATE TABLE "GALADM  "."GAL130TBX"  (
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "END_PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL130TBX" PCTFREE 0;

ALTER TABLE "GALADM  "."GAL130TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL130TBX" IS 'Download Lot Sequence';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL130TBX"

ALTER TABLE "GALADM  "."GAL130TBX" 
	ADD CONSTRAINT "GAL130_PK" PRIMARY KEY
		("PROCESS_LOCATION",
		 "PROCESS_POINT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL130TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL130TBX_I1" ON "GALADM  "."GAL130TBX" 
		("PROCESS_LOCATION" ASC,
		 "PROCESS_POINT_ID" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL130_TR1";

CREATE TRIGGER GALADM.GAL130_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL130TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL130_TR2";

CREATE TRIGGER GALADM.GAL130_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL130TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


