
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL126TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL126TBX";


CREATE TABLE "GALADM  "."GAL126TBX"  (
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_TYPE_DESCRIPTION_SHORT" VARCHAR(10 OCTETS) , 
		  "DEFECT_TYPE_DESCRIPTION_LONG" VARCHAR(30 OCTETS) , 
		  "TWO_PART_DEFECT_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL126TBX" IS 'RMT DefectType for QICS to define defect type name';


-- DDL Statements for Indexes on Table "GALADM  "."GAL126TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL126I1" ON "GALADM  "."GAL126TBX" 
		("DEFECT_TYPE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL126TBX"

ALTER TABLE "GALADM  "."GAL126TBX" 
	ADD CONSTRAINT "GAL126_PK" PRIMARY KEY
		("DEFECT_TYPE_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."GAL126TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL126I2" ON "GALADM  "."GAL126TBX" 
		("DEFECT_TYPE_NAME" ASC,
		 "TWO_PART_DEFECT_FLAG" ASC,
		 "DEFECT_TYPE_DESCRIPTION_LONG" ASC,
		 "DEFECT_TYPE_DESCRIPTION_SHORT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL126_TR1";

CREATE TRIGGER GALADM.GAL126_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL126TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL126_TR2";

CREATE TRIGGER GALADM.GAL126_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL126TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


