
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL180TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL180TBX";


CREATE TABLE "GALADM  "."GAL180TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PART_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DESCRIPTION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL180TBX" IS 'RMT InspectionPartDescription for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL180TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL180I1" ON "GALADM  "."GAL180TBX" 
		("INSPECTION_PART_NAME" ASC,
		 "INSPECTION_PART_LOCATION_NAME" ASC,
		 "PART_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL180TBX"

ALTER TABLE "GALADM  "."GAL180TBX" 
	ADD CONSTRAINT "GAL180_PK" PRIMARY KEY
		("INSPECTION_PART_NAME",
		 "INSPECTION_PART_LOCATION_NAME",
		 "PART_GROUP_NAME");



-- DDL Statements for Unique Constraints on Table "GALADM  "."GAL180TBX"


ALTER TABLE "GALADM  "."GAL180TBX" 
	ADD UNIQUE
		("DESCRIPTION_ID");







-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL180_TR1";

CREATE TRIGGER GALADM.GAL180_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL180TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL180_TR2";

CREATE TRIGGER GALADM.GAL180_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL180TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


