
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL198_HIST_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL198_HIST_TBX";


CREATE TABLE "GALADM  "."GAL198_HIST_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MEASUREMENT_SEQUENCE_NUMBER" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MEASUREMENT_ATTEMPT" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MEASUREMENT_VALUE" DOUBLE , 
		  "MEASUREMENT_STATUS" INTEGER , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "MEASUREMENT_ANGLE" DOUBLE , 
		  "PART_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PART_ID" CHAR(5 OCTETS) , 
		  "PART_REV" INTEGER , 
		  "MEASUREMENT_NAME" CHAR(32 OCTETS) , 
		  "MEASUREMENT_STRING_VALUE" CHAR(30 OCTETS) , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) , 
		  "METHOD_ID" VARCHAR(32 OCTETS) , 
		  "METHOD_DESCRIPTION" VARCHAR(64 OCTETS),
		  "DEFECT_REF_ID" BIGINT WITH DEFAULT 0)   

		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL198_HIST_TBX" IS 'RMT Measurement Attempt History for LOT CONTROL';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL198_HIST_TBX"

ALTER TABLE "GALADM  "."GAL198_HIST_TBX" 
	ADD CONSTRAINT "GAL198_HIST_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PART_NAME",
		 "MEASUREMENT_SEQUENCE_NUMBER",
		 "MEASUREMENT_ATTEMPT");



-- DDL Statements for Indexes on Table "GALADM  "."GAL198_HIST_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL198_HIST_I2" ON "GALADM  "."GAL198_HIST_TBX" 
		("PART_NAME" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL198_HIST_TR1";

CREATE TRIGGER GALADM.GAL198_HIST_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL198_HIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL198_HIST_TR2";

CREATE TRIGGER GALADM.GAL198_HIST_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL198_HIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL198_HIST_I3 ON GALADM.GAL198_HIST_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;
runstats on table GALADM.GAL198_HIST_TBX    with distribution and detailed indexes all;
