
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL183TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL183TBX";


CREATE TABLE "GALADM  "."GAL183TBX"  (
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EMISSION_DENOMINATOR" INTEGER , 
		  "EMISSION_MOLECULE" INTEGER , 
		  "DIMENSION_DENOMINATOR" INTEGER , 
		  "DIMENSION_MOLECULE" INTEGER , 
		  "EMISSION_DENOMINATOR_MASTER" INTEGER , 
		  "EMISSION_MOLECULE_MASTER" INTEGER , 
		  "DIMENSION_DENOMINATOR_MASTER" INTEGER , 
		  "DIMENSION_MOLECULE_MASTER" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL183TBX" IS 'RMT Inspection Sampling';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL183TBX"

ALTER TABLE "GALADM  "."GAL183TBX" 
	ADD CONSTRAINT "GAL183_PK" PRIMARY KEY
		("MODEL_CODE",
		 "MODEL_TYPE_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL183_TR1";

CREATE TRIGGER GALADM.GAL183_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL183TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL183_TR2";

CREATE TRIGGER GALADM.GAL183_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL183TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


