
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL105TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL105TBX";


CREATE TABLE "GALADM  "."GAL105TBX"  (
		  "ROW_INSERT_TSTMP" TIMESTAMP , 
		  "ROW_UPDATE_TSTMP" TIMESTAMP , 
		  "ROW_DISUSE_TSTMP" TIMESTAMP , 
		  "ROW_HISTRC_CNTER" INTEGER , 
		  "ROW_UPDATE_USER" CHAR(11 OCTETS) , 
		  "USER_ID" CHAR(11 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PASSWD" CHAR(8 OCTETS) , 
		  "PASSWD_1" CHAR(8 OCTETS) , 
		  "PASSWD_2" CHAR(8 OCTETS) , 
		  "PASSWD_3" CHAR(8 OCTETS) , 
		  "PASSWD_4" CHAR(8 OCTETS) , 
		  "PASSWD_5" CHAR(8 OCTETS) , 
		  "PASSWD_UPD_DT" CHAR(8 OCTETS) , 
		  "ERROR_FREQ_1" SMALLINT , 
		  "ERROR_FREQ_2" SMALLINT , 
		  "LOGIN_STATUS" CHAR(1 OCTETS) , 
		  "USER_NAME" CHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL105TBX" IS 'RMT AccessControlManager for user security';


-- DDL Statements for Indexes on Table "GALADM  "."GAL105TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL105I1" ON "GALADM  "."GAL105TBX" 
		("USER_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL105TBX"

ALTER TABLE "GALADM  "."GAL105TBX" 
	ADD CONSTRAINT "GAL105_PK" PRIMARY KEY
		("USER_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL105_TR1";

CREATE TRIGGER GALADM.GAL105_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL105TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL105_TR2";

CREATE TRIGGER GALADM.GAL105_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL105TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


