
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL191TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL191TBX";


CREATE TABLE "GALADM  "."GAL191TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "IPP_TAG_NO" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL191TBX" IS 'RMT IPPTag for QICS to track Initial Production Part Tag';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL191TBX"

ALTER TABLE "GALADM  "."GAL191TBX" 
	ADD CONSTRAINT "GAL191PK" PRIMARY KEY
		("PRODUCT_ID",
		 "IPP_TAG_NO",
		 "DIVISION_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GAL191TBX"

ALTER TABLE "GALADM  "."GAL191TBX" 
	ADD CONSTRAINT "REFGAL128TBX6" FOREIGN KEY
		("DIVISION_ID")
	REFERENCES "GALADM  "."GAL128TBX"
		("DIVISION_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GAL191TBX" 
	ADD CONSTRAINT "REFGAL143TBX12" FOREIGN KEY
		("PRODUCT_ID")
	REFERENCES "GALADM  "."GAL143TBX"
		("PRODUCT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL191_TR1";

CREATE TRIGGER GALADM.GAL191_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL191TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL191_TR2";

CREATE TRIGGER GALADM.GAL191_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL191TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


