
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL177TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL177TBX";


CREATE TABLE "GALADM  "."GAL177TBX"  (
		  "REPAIR_AREA_NAME" CHAR(20 OCTETS) , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PARKING_LOCATION" CHAR(6 OCTETS) , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "REJECTION" CHAR(100 OCTETS) WITH DEFAULT ' ' , 
		  "RESPONSIBLE_DEPT" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL177TBX" IS 'RMT InRepairArea for QICS';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL177TBX"

ALTER TABLE "GALADM  "."GAL177TBX" 
	ADD CONSTRAINT "GAL177_PK" PRIMARY KEY
		("PRODUCT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL177TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL177_I1" ON "GALADM  "."GAL177TBX" 
		("PRODUCT_ID" ASC,
		 "PARKING_LOCATION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL177_TR1";

CREATE TRIGGER GALADM.GAL177_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL177TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL177_TR2";

CREATE TRIGGER GALADM.GAL177_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL177TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


