
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL148TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL148TBX";


CREATE TABLE "GALADM  "."GAL148TBX"  (
		  "DATE_STRING" CHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TIME" CHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SEND_LOCATION" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TRAN_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "VIN" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SALES_MODEL_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SALES_MODEL_TYPE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SALES_MODEL_OPTION_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SALES_MODEL_COLOR_CODE" CHAR(11 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "ENGINE_NO" CHAR(7 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "KEY_NO" CHAR(7 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CIC_ISSU_DATA" CHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "ADC_PROCESS_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCTION_LINE_NO" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCTION_DATE_STRING" CHAR(6 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCTION_SEQUENCE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCTION_SUFFIX" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "KD_LINE_NO" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "KD_DATE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "KD_SEQ_NO" CHAR(3 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "KD_SUFFIX" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRICE_STRING" CHAR(9 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "VEHICLE_UNIT_ID" CHAR(10 OCTETS) , 
		  "VEHICLE_COMM_UNIT" CHAR(11 OCTETS) , 
		  "SENDED_FLG" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRINTED_FLAG" CHAR(1 OCTETS) WITH DEFAULT 'N' , 
		  "AF_OFF_DATE" CHAR(6 OCTETS) NOT NULL , 
		  "CCC_REG_NBR" CHAR(12 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL148TBX" IS 'RMT OIF 50A Processing';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL148TBX"

ALTER TABLE "GALADM  "."GAL148TBX" 
	ADD CONSTRAINT "GAL148_PK" PRIMARY KEY
		("VIN");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL148_TR1";

CREATE TRIGGER GALADM.GAL148_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL148TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL148_TR2";

CREATE TRIGGER GALADM.GAL148_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL148TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


