
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL185TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL185TBX";


CREATE TABLE "GALADM  "."GAL185TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_SERIAL_NUMBER" VARCHAR(255 OCTETS) , 
		  "PASS_TIME" INTEGER , 
		  "INSTALLED_PART_REASON" CHAR(128 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "FIRST_ALARM" INTEGER , 
		  "SECOND_ALARM" INTEGER , 
		  "PART_ID" CHAR(5 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "OP_REV" INTEGER , 
		  "PART_REV" INTEGER , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "OVERRIDE_ASSOCIATE_NO" CHAR(11 OCTETS),
		  "DEFECT_REF_ID" BIGINT WITH DEFAULT 0)   
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL185TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL185TBX" IS 'RMT InstalledPart for LOT CONTROL';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL185TBX"

ALTER TABLE "GALADM  "."GAL185TBX" 
	ADD CONSTRAINT "GAL185PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PART_NAME");



-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I4" ON "GALADM  "."GAL185TBX" 
		("PROCESS_POINT_ID" ASC,
		 "CREATE_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I5" ON "GALADM  "."GAL185TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I6" ON "GALADM  "."GAL185TBX" 
		("PART_NAME" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I3" ON "GALADM  "."GAL185TBX" 
		("PART_SERIAL_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I1" ON "GALADM  "."GAL185TBX" 
		("PART_NAME" ASC,
		 "PART_SERIAL_NUMBER" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL185TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL185_I2" ON "GALADM  "."GAL185TBX" 
		("PART_NAME" ASC,
		 "PRODUCT_ID" ASC,
		 "PART_SERIAL_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "GALADM "."GAL185_I7" ON "GALADM "."GAL185TBX"
		("PART_ID" ASC, 
		"PART_NAME" ASC, 
		"PRODUCT_ID" ASC)
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;




-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL185_TR1";

CREATE TRIGGER GALADM.GAL185_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL185TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL185_TR2";

CREATE TRIGGER GALADM.GAL185_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL185TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL185_I8 ON GALADM.GAL185TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;
runstats on table GALADM.GAL185TBX with distribution and detailed indexes all;

