
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL234TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL234TBX";


CREATE TABLE "GALADM  "."GAL234TBX"  (
		  "HOST_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "IP_ADDRESS" VARCHAR(255 OCTETS) , 
		  "PORT" INTEGER , 
		  "ROUTER_PORT" INTEGER , 
		  "TERMINAL_DESCRIPTION" CHAR(128 OCTETS) , 
		  "LOCATED_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "DIVISION_ID" CHAR(16 OCTETS) , 
		  "AF_TERMINAL_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP ,
		  "AUTO_UPDATE_IP_ADDRESS"	SMALLINT NOT NULL WITH DEFAULT 0
		  )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL234TBX" IS 'RMT Terminal';


-- DDL Statements for Indexes on Table "GALADM  "."GAL234TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL234I1" ON "GALADM  "."GAL234TBX" 
		("HOST_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL234TBX"

ALTER TABLE "GALADM  "."GAL234TBX" 
	ADD CONSTRAINT "GAL234_PK" PRIMARY KEY
		("HOST_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL234_TR1";

CREATE TRIGGER GALADM.GAL234_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL234TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL234_TR2";

CREATE TRIGGER GALADM.GAL234_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL234TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


