
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL268TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL268TBX";


CREATE TABLE "GALADM  "."GAL268TBX"  (
		  "PLANT_CODE_FRAME" CHAR(4 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EFFECTIVE_DATE" CHAR(8 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRICE_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CURRENCY" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRICE" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "QUOTATION_NO" CHAR(6 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL268TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL268TBX" IS 'IF Frame MTOC Price Master Specification';


-- DDL Statements for Indexes on Table "GALADM  "."GAL268TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL268_I1" ON "GALADM  "."GAL268TBX" 
		("PLANT_CODE_FRAME" ASC,
		 "MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "MODEL_OPTION_CODE" ASC,
		 "EXT_COLOR_CODE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "EFFECTIVE_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL268TBX"

ALTER TABLE "GALADM  "."GAL268TBX" 
	ADD CONSTRAINT "GAL268_PK" PRIMARY KEY
		("PLANT_CODE_FRAME",
		 "MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "EXT_COLOR_CODE",
		 "INT_COLOR_CODE",
		 "EFFECTIVE_DATE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL268TBX_TR1";

CREATE TRIGGER GALADM.GAL268TBX_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL268TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL268TBX_TR2";

CREATE TRIGGER GALADM.GAL268TBX_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL268TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


