
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL206TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL206TBX";


CREATE TABLE "GALADM  "."GAL206TBX"  (
		  "PART_ID" CHAR(5 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_DESCRIPTION" CHAR(128 OCTETS) , 
		  "PART_SERIAL_NUMBER_MASK" VARCHAR(255 OCTETS) , 
		  "ENTRY_TIMESTAMP" TIMESTAMP , 
		  "MAXIMUM_VALUE1" DOUBLE , 
		  "MINIMUM_VALUE1" DOUBLE , 
		  "MAXIMUM_VALUE2" DOUBLE , 
		  "MINIMUM_VALUE2" DOUBLE , 
		  "MAXIMUM_VALUE3" DOUBLE , 
		  "MINIMUM_VALUE3" DOUBLE , 
		  "MAXIMUM_VALUE4" DOUBLE , 
		  "MINIMUM_VALUE4" DOUBLE , 
		  "MAXIMUM_VALUE5" DOUBLE , 
		  "MINIMUM_VALUE5" DOUBLE , 
		  "MAXIMUM_VALUE6" DOUBLE , 
		  "MINIMUM_VALUE6" DOUBLE , 
		  "MAXIMUM_VALUE7" DOUBLE , 
		  "MINIMUM_VALUE7" DOUBLE , 
		  "MAXIMUM_VALUE8" DOUBLE , 
		  "MINIMUM_VALUE8" DOUBLE , 
		  "MAXIMUM_VALUE9" DOUBLE , 
		  "MINIMUM_VALUE9" DOUBLE , 
		  "MAXIMUM_VALUE10" DOUBLE , 
		  "MINIMUM_VALUE10" DOUBLE , 
		  "MEASUREMENT_COUNT" INTEGER , 
		  "ALLOW_DUPLICATES" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "COMMENT" VARCHAR(256 OCTETS) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL206TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL206TBX" IS 'RMT Part for LOT CONTROL - Replaced by PART_SPEC_TBX and MEASUREMENT_SPEC_TBX';


-- DDL Statements for Indexes on Table "GALADM  "."GAL206TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL206I1" ON "GALADM  "."GAL206TBX" 
		("PART_ID" ASC,
		 "PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL206TBX"

ALTER TABLE "GALADM  "."GAL206TBX" 
	ADD CONSTRAINT "GAL206PK" PRIMARY KEY
		("PART_ID",
		 "PART_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."GAL206TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL206_I1" ON "GALADM  "."GAL206TBX" 
		("PART_NAME" ASC,
		 "PART_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL206_TR1";

CREATE TRIGGER GALADM.GAL206_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL206TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL206_TR2";

CREATE TRIGGER GALADM.GAL206_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL206TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


