
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL226TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL226TBX";


CREATE TABLE "GALADM  "."GAL226TBX"  (
		  "LINE_NO" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_CODE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DAY_OF_WEEK" CHAR(3 OCTETS) , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "TYPE" CHAR(3 OCTETS) , 
		  "PLAN" CHAR(1 OCTETS) , 
		  "START_TIME" TIME , 
		  "END_TIME" TIME , 
		  "NEXT_DAY" SMALLINT , 
		  "CAPACITY" INTEGER WITH DEFAULT 0 , 
		  "CAPACITY_ON" INTEGER WITH DEFAULT 0 , 
		  "PLAN_CODE" CHAR(11 OCTETS) , 
		  "WEEK_NO" CHAR(6 OCTETS) , 
		  "ISWORK" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "START_TIMESTAMP" TIMESTAMP , 
		  "END_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL226TBX" IS 'RMT DailyDepartmentSchedule for LINE CONTROL to define production working periods per GPCS Plan Code';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL226TBX"

ALTER TABLE "GALADM  "."GAL226TBX" 
	ADD CONSTRAINT "GAL226_PK" PRIMARY KEY
		("LINE_NO",
		 "PROCESS_LOCATION",
		 "PLANT_CODE",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD");



-- DDL Statements for Indexes on Table "GALADM  "."GAL226TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL226_I1" ON "GALADM  "."GAL226TBX" 
		("PROCESS_LOCATION" ASC,
		 "PLANT_CODE" ASC,
		 "LINE_NO" ASC,
		 "END_TIMESTAMP" ASC,
		 "START_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL226TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL226_I2" ON "GALADM  "."GAL226TBX" 
		("PRODUCTION_DATE" ASC,
		 "LINE_NO" ASC,
		 "PROCESS_LOCATION" ASC,
		 "PLANT_CODE" ASC,
		 "SHIFT" ASC,
		 "DAY_OF_WEEK" ASC,
		 "WEEK_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL226_TR1";

CREATE TRIGGER GALADM.GAL226_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL226TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL226_TR2";

CREATE TRIGGER GALADM.GAL226_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL226TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

