
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL238TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL238TBX";


CREATE TABLE "GALADM  "."GAL238TBX"  (
		  "GPCS_PLANT_CODE" CHAR(4 OCTETS) , 
		  "GPCS_LINE_NO" CHAR(2 OCTETS) , 
		  "GPCS_PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL238TBX" IS 'RMT GpcsDivision';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL238TBX"

ALTER TABLE "GALADM  "."GAL238TBX" 
	ADD CONSTRAINT "GAL238_PK" PRIMARY KEY
		("DIVISION_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL238_TR1";

CREATE TRIGGER GALADM.GAL238_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL238TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL238_TR2";

CREATE TRIGGER GALADM.GAL238_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL238TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


