
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL244TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL244TBX";


CREATE TABLE "GALADM  "."GAL244TBX"  (
		  "TASK_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "TASKSPEC_DESCRIPTION" CHAR(128 OCTETS) , 
		  "STATEFULL_SESSION_BEAN_FLAG" SMALLINT , 
		  "JNDI_NAME" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL244TBX" IS 'RMT TaskSpec';


-- DDL Statements for Indexes on Table "GALADM  "."GAL244TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL244I1" ON "GALADM  "."GAL244TBX" 
		("TASK_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL244TBX"

ALTER TABLE "GALADM  "."GAL244TBX" 
	ADD CONSTRAINT "GAL244_PK" PRIMARY KEY
		("TASK_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL244_TR1";

CREATE TRIGGER GALADM.GAL244_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL244TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL244_TR2";

CREATE TRIGGER GALADM.GAL244_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL244TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


