
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL227TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL227TBX";


CREATE TABLE "GALADM  "."GAL227TBX"  (
		  "SECONDARY_PART_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SECONDARY_PART_DESC_SHORT" VARCHAR(10 OCTETS) , 
		  "SECONDARY_PART_DESC_LONG" VARCHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL227TBX" IS 'RMT SecondaryPart for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL227TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL227I1" ON "GALADM  "."GAL227TBX" 
		("SECONDARY_PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL227TBX"

ALTER TABLE "GALADM  "."GAL227TBX" 
	ADD CONSTRAINT "GAL227_PK" PRIMARY KEY
		("SECONDARY_PART_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL227_TR1";

CREATE TRIGGER GALADM.GAL227_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL227TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL227_TR2";

CREATE TRIGGER GALADM.GAL227_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL227TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


