
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL260TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL260TBX";


CREATE TABLE "GALADM  "."GAL260TBX"  (
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "FIRST_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "LAST_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "PRODUCT_ID_INSPECT" INTEGER , 
		  "PRODUCT_ID_DIRECT_PASSED" INTEGER , 
		  "PRODUCT_ID_WITH_DEFECTS" INTEGER , 
		  "REPAIRED_PRODUCT_ID" INTEGER , 
		  "OUTSTANDING_PRODUCT_ID" INTEGER , 
		  "SCRAP" INTEGER , 
		  "AVERAGE_DEFECT_PER_PRODUCT_ID" DOUBLE , 
		  "STRAIGHT_SHIP_PERCENTAGE" DOUBLE , 
		  "ROYAL_STRAIGHT_SHIP_PERCENTAGE" DOUBLE , 
		  "TOP_COAT_PASS_RATE" DOUBLE , 
		  "REPAIR_PASS_RATE" DOUBLE , 
		  "OUTSTANDING_RPU" DOUBLE , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_ID_RSSR" INTEGER WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PREHEAT" INTEGER , 
		  "TOTAL_REJECTION" INTEGER , 
		  "SCAN_COUNT" INTEGER )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL260TBX" IS 'RMT StationResult for QICS Station Result per process point, production date and shift';


-- DDL Statements for Indexes on Table "GALADM  "."GAL260TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL260I1" ON "GALADM  "."GAL260TBX" 
		("APPLICATION_ID" ASC,
		 "SHIFT" ASC,
		 "PRODUCTION_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL260TBX"

ALTER TABLE "GALADM  "."GAL260TBX" 
	ADD CONSTRAINT "GAL260_PK" PRIMARY KEY
		("APPLICATION_ID",
		 "SHIFT",
		 "PRODUCTION_DATE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL260_TR1";

CREATE TRIGGER GALADM.GAL260_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL260TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL260_TR2";

CREATE TRIGGER GALADM.GAL260_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL260TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


