
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL279TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL279TBX";


CREATE TABLE "GALADM  "."GAL279TBX"  (
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "DAY_OF_WEEK" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "WEEK_NO" CHAR(6 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL279TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL279TBX" IS 'Annual Calendar';


-- DDL Statements for Indexes on Table "GALADM  "."GAL279TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL279I1" ON "GALADM  "."GAL279TBX" 
		("PRODUCTION_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL279TBX"

ALTER TABLE "GALADM  "."GAL279TBX" 
	ADD CONSTRAINT "GAL279_PK" PRIMARY KEY
		("PRODUCTION_DATE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL279TR1";

CREATE TRIGGER GALADM.GAL279TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL279TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL279TR2";

CREATE TRIGGER GALADM.GAL279TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL279TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


