
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL241TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL241TBX";


CREATE TABLE "GALADM  "."GAL241TBX"  (
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "APPLICATION_NAME" CHAR(35 OCTETS) , 
		  "APPLICATION_TYPE" INTEGER , 
		  "TERMINAL_APPLICATION_FLAG" SMALLINT , 
		  "SCREEN_ID" CHAR(16 OCTETS) , 
		  "WINDOW_TITLE" CHAR(32 OCTETS) , 
		  "SCREEN_CLASS" CHAR(128 OCTETS) , 
		  "APPLICATION_DESCRIPTION" CHAR(128 OCTETS) , 
		  "PRELOAD" INTEGER WITH DEFAULT 0 , 
		  "SESSION_REQUIRED" SMALLINT WITH DEFAULT 0 , 
		  "PERSISTENT_SESSION" SMALLINT WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "APP_VIEW" VARCHAR(255 OCTETS) , 
		  "APP_PROCESSOR" VARCHAR(255 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL241TBX" IS 'RMT Application';


-- DDL Statements for Indexes on Table "GALADM  "."GAL241TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL241I1" ON "GALADM  "."GAL241TBX" 
		("APPLICATION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL241TBX"

ALTER TABLE "GALADM  "."GAL241TBX" 
	ADD CONSTRAINT "GAL241_PK" PRIMARY KEY
		("APPLICATION_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL241_TR1";

CREATE TRIGGER GALADM.GAL241_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL241TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL241_TR2";

CREATE TRIGGER GALADM.GAL241_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL241TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


