
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL208TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL208TBX";


CREATE TABLE "GALADM  "."GAL208TBX"  (
		  "PART_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PART_GROUP_DESCRIPTION_SHORT" VARCHAR(10 OCTETS) , 
		  "PART_GROUP_DESCRIPTION_LONG" VARCHAR(30 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL208TBX" IS 'RMT PartGroup for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL208TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL208I1" ON "GALADM  "."GAL208TBX" 
		("PART_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL208TBX"

ALTER TABLE "GALADM  "."GAL208TBX" 
	ADD CONSTRAINT "GAL208_PK" PRIMARY KEY
		("PART_GROUP_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."GAL208TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL208I2" ON "GALADM  "."GAL208TBX" 
		("MODEL_CODE" ASC,
		 "PART_GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL208_TR1";

CREATE TRIGGER GALADM.GAL208_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL208TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL208_TR2";

CREATE TRIGGER GALADM.GAL208_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL208TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


