
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL212TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL212TBX";


CREATE TABLE "GALADM  "."GAL212TBX"  (
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LOT_SIZE" INTEGER , 
		  "START_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "SEND_STATUS" INTEGER , 
		  "STAMPED_COUNT" INTEGER , 
		  "HOLD_STATUS" INTEGER , 
		  "SENT_TIMESTAMP" TIMESTAMP , 
		  "NEXT_PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "LOT_NUMBER" CHAR(12 OCTETS) , 
		  "PLANT_CODE" CHAR(4 OCTETS) , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "LINE_NO" CHAR(2 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "BUILD_SEQ_NOT_FIXED_FLAG" CHAR(1 OCTETS) , 
		  "BUILD_SEQUENCE_NUMBER" CHAR(12 OCTETS) , 
		  "PLAN_CODE" CHAR(11 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "SEQUENCE" DOUBLE , 
		  "REMAKE_FLAG" CHAR(1 OCTETS) , 
		  "STAMPING_FLAG" CHAR(1 OCTETS) , 
		  "CARRY_IN_OUT_FLAG" CHAR(1 OCTETS) , 
		  "CARRY_IN_OUT_UNITS" INTEGER , 
		  "MBPN" VARCHAR(18 OCTETS) , 
		  "HES_COLOR" VARCHAR(11 OCTETS) , 
		  "DEMAND_TYPE" CHAR(2 OCTETS) , 
		  "NOTES" VARCHAR(256 OCTETS) ,
		  "PLAN_OFF_DATE" DATE)   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL212TBX" IS 'RMT PreProductionLot for LINE CONTROL';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL212TBX"

ALTER TABLE "GALADM  "."GAL212TBX" 
	ADD CONSTRAINT "GAL212_PK" PRIMARY KEY
		("PRODUCTION_LOT");



-- DDL Statements for Indexes on Table "GALADM  "."GAL212TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL212_I1" ON "GALADM  "."GAL212TBX" 
		("NEXT_PRODUCTION_LOT" ASC,
		 "SEND_STATUS" ASC,
		 "LOT_SIZE" ASC,
		 "STAMPED_COUNT" ASC,
		 "PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL212TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL212_I2" ON "GALADM  "."GAL212TBX" 
		("KD_LOT_NUMBER" ASC,
		 "PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL212_TR1";

CREATE TRIGGER GALADM.GAL212_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL212TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL212_TR2";

CREATE TRIGGER GALADM.GAL212_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL212TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


