
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL283TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL283TBX";


CREATE TABLE "GALADM  "."GAL283TBX"  (
		  "SCREEN_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SECURITY_GRP" VARCHAR(255 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "OPERATION" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL283TBX" IS 'RMT AccessControlEntry for SECURITY to manage access to Terminal Applications (Screen ID)';


-- DDL Statements for Indexes on Table "GALADM  "."GAL283TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL283I1" ON "GALADM  "."GAL283TBX" 
		("SCREEN_ID" ASC,
		 "SECURITY_GRP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL283TBX"

ALTER TABLE "GALADM  "."GAL283TBX" 
	ADD CONSTRAINT "GAL283_PK" PRIMARY KEY
		("SCREEN_ID",
		 "SECURITY_GRP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL283_TR1";

CREATE TRIGGER GALADM.GAL283_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL283TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL283_TR2";

CREATE TRIGGER GALADM.GAL283_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL283TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


