
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL258TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL258TBX";


CREATE TABLE "GALADM  "."GAL258TBX"  (
		  "FORMID" CHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "OFFSET" INTEGER , 
		  "LENGTH" INTEGER , 
		  "ATTRIBUTE_TYPE" INTEGER , 
		  "ATTRIBUTE_VALUE" VARCHAR(8000 OCTETS) , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "REQUIRED" INTEGER )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL258TBX" IS 'RMT PrintAttributeFormat for LOT CONTROL by Form';


-- DDL Statements for Indexes on Table "GALADM  "."GAL258TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL258I1" ON "GALADM  "."GAL258TBX" 
		("FORMID" ASC,
		 "ATTRIBUTE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL258TBX"

ALTER TABLE "GALADM  "."GAL258TBX" 
	ADD CONSTRAINT "GAL258_PK" PRIMARY KEY
		("FORMID",
		 "ATTRIBUTE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL258_TR1";

CREATE TRIGGER GALADM.GAL258_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL258TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL258_TR2";

CREATE TRIGGER GALADM.GAL258_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL258TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


