
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL224TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL224TBX";


CREATE TABLE "GALADM  "."GAL224TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "REUSE_VIN_REASON" VARCHAR(80 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL224TBX" IS 'RMT ReuseProductResult';


-- DDL Statements for Indexes on Table "GALADM  "."GAL224TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL224I1" ON "GALADM  "."GAL224TBX" 
		("PRODUCT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL224TBX"

ALTER TABLE "GALADM  "."GAL224TBX" 
	ADD CONSTRAINT "GAL224_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ACTUAL_TIMESTAMP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL224_TR1";

CREATE TRIGGER GALADM.GAL224_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL224TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL224_TR2";

CREATE TRIGGER GALADM.GAL224_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL224TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


