
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL243TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL243TBX";


CREATE TABLE "GALADM  "."GAL243TBX"  (
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "JNDI_NAME" CHAR(128 OCTETS) , 
		  "TASK_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SEQUENCE_NO" INTEGER , 
		  "INPUT_EVENT_EXIST_FLAG" SMALLINT , 
		  "BEGIN_FLAG" SMALLINT , 
		  "COMMIT_FLAG" SMALLINT , 
		  "STATEFULL_SESSION_BEAN_FLAG" SMALLINT , 
		  "ARGUMENT" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL243TBX" IS 'RMT ApplicationTask';


-- DDL Statements for Indexes on Table "GALADM  "."GAL243TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL243I1" ON "GALADM  "."GAL243TBX" 
		("APPLICATION_ID" ASC,
		 "TASK_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL243TBX"

ALTER TABLE "GALADM  "."GAL243TBX" 
	ADD CONSTRAINT "GAL243_PK" PRIMARY KEY
		("APPLICATION_ID",
		 "TASK_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL243_TR1";

CREATE TRIGGER GALADM.GAL243_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL243TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL243_TR2";

CREATE TRIGGER GALADM.GAL243_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL243TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


