
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL294TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL294TBX";


CREATE TABLE "GALADM  "."GAL294TBX"  (
		  "FORM_ID" CHAR(32 OCTETS) NOT NULL , 
		  "DESTINATION_ID" CHAR(32 OCTETS) NOT NULL , 
		  "DEFAULT_FLAG" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL294TBX" IS 'RMT PrintForm for LOT CONTROL to manage forms to printers';











-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL294_TR1";

CREATE TRIGGER GALADM.GAL294_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL294TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL294_TR2";

CREATE TRIGGER GALADM.GAL294_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL294TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


