
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL211TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL211TBX";


CREATE TABLE "GALADM  "."GAL211TBX"  (
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_LONG_DESCRIPTION" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP  )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL211TBX" IS 'RMT Plant';


-- DDL Statements for Indexes on Table "GALADM  "."GAL211TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL211I1" ON "GALADM  "."GAL211TBX" 
		("SITE_NAME" ASC,
		 "PLANT_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL211TBX"

ALTER TABLE "GALADM  "."GAL211TBX" 
	ADD CONSTRAINT "GAL211_PK" PRIMARY KEY
		("SITE_NAME",
		 "PLANT_NAME");







-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL211_TR1";

CREATE TRIGGER GALADM.GAL211_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL211TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL211_TR2";

CREATE TRIGGER GALADM.GAL211_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL211TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


