
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL261TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL261TBX";


CREATE TABLE "GALADM  "."GAL261TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_CONFIRM_CHECK" INTEGER , 
		  "WINDOW_LABEL" CHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "SUB_PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "PART_VISIBLE" INTEGER , 
		  "REPAIR_CHECK" INTEGER ,
		  "EXTERNAL_REQUIRED" INTEGER,
  		  "LET_CHECK_REQUIRED" INTEGER)   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL261TBX" IS 'RMT PartName for LOT CONTROL to manage Installed Part';


-- DDL Statements for Indexes on Table "GALADM  "."GAL261TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL261I1" ON "GALADM  "."GAL261TBX" 
		("PART_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL261TBX"

ALTER TABLE "GALADM  "."GAL261TBX" 
	ADD CONSTRAINT "GAL261_PK" PRIMARY KEY
		("PART_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL261_TR1";

CREATE TRIGGER GALADM.GAL261_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL261TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL261_TR2";

CREATE TRIGGER GALADM.GAL261_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL261TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


