
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL242TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL242TBX";


CREATE TABLE "GALADM  "."GAL242TBX"  (
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HOST_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DEFAULT_APPLICATION_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "SEQ_NUM" INTEGER )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL242TBX" IS 'RMT ApplicationByTerminal';


-- DDL Statements for Indexes on Table "GALADM  "."GAL242TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL242I1" ON "GALADM  "."GAL242TBX" 
		("APPLICATION_ID" ASC,
		 "HOST_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL242TBX"

ALTER TABLE "GALADM  "."GAL242TBX" 
	ADD CONSTRAINT "GAL242_PK" PRIMARY KEY
		("APPLICATION_ID",
		 "HOST_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL242_TR1";

CREATE TRIGGER GALADM.GAL242_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL242TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL242_TR2";

CREATE TRIGGER GALADM.GAL242_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL242TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


