
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL246TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL246TBX";


CREATE TABLE "GALADM  "."GAL246TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "EXPECTED_INSTALL_TIME" INTEGER , 
		  "VERIFICATION_FLAG" INTEGER , 
		  "SERIAL_NUMBER_SCAN_FLAG" INTEGER , 
		  "INSTRUCTION_CODE" CHAR(3 OCTETS) , 
		  "DEVICE_ID" CHAR(16 OCTETS) , 
		  "SERIAL_NUMBER_UNIQUE_FLAG" INTEGER , 
		  "STRATEGY" VARCHAR(256 OCTETS) , 
		  "SUB_ID" CHAR(2 OCTETS) ,
		  "QI_DEFECT_FLAG" INTEGER DEFAULT 0,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "GROUP_ID" CHAR(30 OCTETS) , 
		  "PART_CONFIRM_FLAG" INTEGER , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL246TBX" IS 'RMT LotControlRule for LOT CONTROL to define Installed Part rules per Process Point and Product Spec Code';


-- DDL Statements for Indexes on Table "GALADM  "."GAL246TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL246_I1" ON "GALADM  "."GAL246TBX" 
		("PROCESS_POINT_ID" ASC,
		 "MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "MODEL_OPTION_CODE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "EXT_COLOR_CODE" ASC,
		 "PART_NAME" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL246TBX"

ALTER TABLE "GALADM  "."GAL246TBX" 
	ADD CONSTRAINT "GAL246_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "INT_COLOR_CODE",
		 "EXT_COLOR_CODE",
		 "PART_NAME",
		 "PRODUCT_SPEC_CODE");




-- DDL Statements for Indexes on Table "GALADM  "."GAL246TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL246_I2" ON "GALADM  "."GAL246TBX" 
		("PART_NAME" ASC,
		 "PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL246_TR1";

CREATE TRIGGER GALADM.GAL246_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL246TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL246_TR2";

CREATE TRIGGER GALADM.GAL246_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL246TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


