
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL287TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL287TBX";


CREATE TABLE "GALADM  "."GAL287TBX"  (
		  "CLIENT_ID" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "NODENUMBER" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "NODENAME" CHAR(32 OCTETS) , 
		  "PARENTNODENUMBER" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL287TBX" IS 'RMT ApplicationMenuEntry for managing Menu Items on Terminals';


-- DDL Statements for Indexes on Table "GALADM  "."GAL287TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL287I1" ON "GALADM  "."GAL287TBX" 
		("CLIENT_ID" ASC,
		 "NODENUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL287TBX"

ALTER TABLE "GALADM  "."GAL287TBX" 
	ADD CONSTRAINT "GAL287_PK" PRIMARY KEY
		("CLIENT_ID",
		 "NODENUMBER");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL287_TR1";

CREATE TRIGGER GALADM.GAL287_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL287TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL287_TR2";

CREATE TRIGGER GALADM.GAL287_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL287TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


