
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL263TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL263TBX";


CREATE TABLE "GALADM  "."GAL263TBX"  (
		  "VIN" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "STATUS" INTEGER , 
		  "INVOICED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "ON_TIME_SHIPPING" SMALLINT , 
		  "APPC70A_EMISSION_FLAG" CHAR(1 OCTETS) , 
		  "APPC70A_TIMESTAMP" TIMESTAMP , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DEALER_NO" CHAR(6 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL263TBX" IS 'RMT ShippingStatus for LINE CONTROL to manage FRAME (Vin) shipping status';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL263TBX"

ALTER TABLE "GALADM  "."GAL263TBX" 
	ADD CONSTRAINT "GAL263PK" PRIMARY KEY
		("VIN");



-- DDL Statements for Indexes on Table "GALADM  "."GAL263TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL263_I1" ON "GALADM  "."GAL263TBX" 
		("STATUS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL263_TR1";

CREATE TRIGGER GALADM.GAL263_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL263TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL263_TR2";

CREATE TRIGGER GALADM.GAL263_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL263TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


