
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL222TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL222TBX";


CREATE TABLE "GALADM  "."GAL222TBX"  (
		  "REPAIR_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DEFECTRESULTID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "REPAIR_ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "ACTUAL_PROBLEM_NAME" CHAR(64 OCTETS) , 
		  "REPAIR_METHOD_NAME" CHAR(64 OCTETS) , 
		  "REPAIR_TIME" INTEGER , 
		  "REPAIR_DEPT" VARCHAR(32 OCTETS) , 
		  "REPAIR_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "COMMENT" VARCHAR(256 OCTETS) , 
		  "NAQ_REPAIR_ID" BIGINT )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL222TBX" IS 'RMT DefectRepairResult for QICS to record repairs for each product defect';


-- DDL Statements for Indexes on Table "GALADM  "."GAL222TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL222I1" ON "GALADM  "."GAL222TBX" 
		("REPAIR_ID" ASC,
		 "PRODUCT_ID" ASC,
		 "DEFECTRESULTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL222TBX"

ALTER TABLE "GALADM  "."GAL222TBX" 
	ADD CONSTRAINT "GAL222_PK" PRIMARY KEY
		("REPAIR_ID",
		 "PRODUCT_ID",
		 "DEFECTRESULTID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL222TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL222I2" ON "GALADM  "."GAL222TBX" 
		("DEFECTRESULTID" ASC,
		 "PRODUCT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL222TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL222I3" ON "GALADM  "."GAL222TBX" 
		("REPAIR_PROCESS_POINT_ID" ASC,
		 "DEFECTRESULTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL222_TR1";

CREATE TRIGGER GALADM.GAL222_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL222TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL222_TR2";

CREATE TRIGGER GALADM.GAL222_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL222TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


