
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL216TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL216TBX";


CREATE TABLE "GALADM  "."GAL216TBX"  (
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "STAMPING_SEQUENCE_NO" INTEGER , 
		  "SEND_STATUS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL216TBX" IS 'RMT ProductStampingSequence';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL216TBX"

ALTER TABLE "GALADM  "."GAL216TBX" 
	ADD CONSTRAINT "GAL216_PK" PRIMARY KEY
		("PRODUCTION_LOT",
		 "PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL216_TR1";

CREATE TRIGGER GALADM.GAL216_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL216TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL216_TR2";

CREATE TRIGGER GALADM.GAL216_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL216TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


