
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL205TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL205TBX";


CREATE TABLE "GALADM  "."GAL205TBX"  (
		  "PARKING_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PARKING_ADDRESS_PRIORITY" INTEGER , 
		  "VIN" CHAR(17 OCTETS) , 
		  "PARKING_ADDRESS_SPACE" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PARKING_ADDRESS_ROW" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PARKING_ADDRESS_ROW_NAME" VARCHAR(20 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL205TBX" IS 'RMT ParkingAddress';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL205TBX"

ALTER TABLE "GALADM  "."GAL205TBX" 
	ADD CONSTRAINT "GAL205_PK" PRIMARY KEY
		("PARKING_NAME",
		 "PARKING_ADDRESS_SPACE",
		 "PARKING_ADDRESS_ROW");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL205_TR1";

CREATE TRIGGER GALADM.GAL205_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL205TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL205_TR2";

CREATE TRIGGER GALADM.GAL205_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL205TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


