
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL257TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL257TBX";


CREATE TABLE "GALADM  "."GAL257TBX"  (
		  "CLIENT_ID" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "TAG" CHAR(128 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "OFFSET" INTEGER , 
		  "LENGTH" INTEGER , 
		  "TAG_TYPE" INTEGER , 
		  "TAG_VALUE" VARCHAR(1024 OCTETS) , 
		  "TAG_NAME" VARCHAR(512 OCTETS) , 
		  "DATA_TYPE" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL257TBX" IS 'RMT DeviceFormat for LOT CONTROL to configure Device by Client ID';


-- DDL Statements for Indexes on Table "GALADM  "."GAL257TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL257I1" ON "GALADM  "."GAL257TBX" 
		("CLIENT_ID" ASC,
		 "TAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL257TBX"

ALTER TABLE "GALADM  "."GAL257TBX" 
	ADD CONSTRAINT "GAL257PK" PRIMARY KEY
		("CLIENT_ID",
		 "TAG");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL257_TR1";

CREATE TRIGGER GALADM.GAL257_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL257TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL257_TR2";

CREATE TRIGGER GALADM.GAL257_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL257TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


