
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL253TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL253TBX";


CREATE TABLE "GALADM  "."GAL253TBX"  (
		  "CLIENT_ID" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ALIAS_NAME" CHAR(64 OCTETS) , 
		  "DEVICE_TYPE" INTEGER , 
		  "DEVICE_DESCRIPTION" CHAR(128 OCTETS) , 
		  "EIF_IP_ADDRESS" VARCHAR(255 OCTETS) , 
		  "EIF_PORT" INTEGER , 
		  "IO_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "DIVISION_ID" CHAR(16 OCTETS) , 
		  "REPLY_CLIENT_ID" CHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL253TBX" IS 'RMT Device for LOT CONTROL';


-- DDL Statements for Indexes on Table "GALADM  "."GAL253TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL253I1" ON "GALADM  "."GAL253TBX" 
		("CLIENT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL253TBX"

ALTER TABLE "GALADM  "."GAL253TBX" 
	ADD CONSTRAINT "GAL253_PK" PRIMARY KEY
		("CLIENT_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL253_TR1";

CREATE TRIGGER GALADM.GAL253_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL253TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL253_TR2";

CREATE TRIGGER GALADM.GAL253_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL253TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


