
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL219TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL219TBX";


CREATE TABLE "GALADM  "."GAL219TBX"  (
		  "REGRESSION_CODE" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL219TBX" IS 'RMT Regression';


-- DDL Statements for Indexes on Table "GALADM  "."GAL219TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL219I1" ON "GALADM  "."GAL219TBX" 
		("REGRESSION_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL219TBX"

ALTER TABLE "GALADM  "."GAL219TBX" 
	ADD CONSTRAINT "GAL219_PK" PRIMARY KEY
		("REGRESSION_CODE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL219_TR1";

CREATE TRIGGER GALADM.GAL219_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL219TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL219_TR2";

CREATE TRIGGER GALADM.GAL219_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL219TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


