
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL236TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL236TBX";


CREATE TABLE "GALADM  "."GAL236TBX"  (
		  "LINE_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PREVIOUS_LINE_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL236TBX" IS 'RMT PreviousLine';


-- DDL Statements for Indexes on Table "GALADM  "."GAL236TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL236I1" ON "GALADM  "."GAL236TBX" 
		("LINE_ID" ASC,
		 "PREVIOUS_LINE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL236TBX"

ALTER TABLE "GALADM  "."GAL236TBX" 
	ADD CONSTRAINT "GAL236_PK" PRIMARY KEY
		("LINE_ID",
		 "PREVIOUS_LINE_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL236_TR1";

CREATE TRIGGER GALADM.GAL236_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL236TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL236_TR2";

CREATE TRIGGER GALADM.GAL236_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL236TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


