
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL217TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL217TBX";


CREATE TABLE "GALADM  "."GAL217TBX"  (
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLAN_CODE" CHAR(11 OCTETS) , 
		  "LINE_NO" CHAR(2 OCTETS) , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "WE_LINE_NO" CHAR(2 OCTETS) , 
		  "WE_PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "PA_LINE_NO" CHAR(2 OCTETS) , 
		  "PA_PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "START_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "LOT_SIZE" INTEGER , 
		  "DEMAND_TYPE" CHAR(2 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "PRODUCTION_DATE" DATE , 
		  "LOT_PASS_FLAG" SMALLINT , 
		  "LOT_NUMBER" CHAR(12 OCTETS) , 
		  "PLANT_CODE" CHAR(4 OCTETS) , 
		  "LOT_STATUS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROD_LOT_KD" CHAR(20 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL217TBX" IS 'RMT ProductionLot';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL217TBX"

ALTER TABLE "GALADM  "."GAL217TBX" 
	ADD CONSTRAINT "GAL217_PK" PRIMARY KEY
		("PRODUCTION_LOT");



-- DDL Statements for Indexes on Table "GALADM  "."GAL217TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL217_I1" ON "GALADM  "."GAL217TBX" 
		("PRODUCTION_LOT" ASC)
		INCLUDE ("PLANT_CODE" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL217TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL217_I2" ON "GALADM  "."GAL217TBX" 
		("PROD_LOT_KD" ASC,
		 "LOT_SIZE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL217TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL217_I3" ON "GALADM  "."GAL217TBX" 
		("PROD_LOT_KD" ASC,
		 "PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL217_TR1";

CREATE TRIGGER GALADM.GAL217_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL217TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL217_TR2";

CREATE TRIGGER GALADM.GAL217_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL217TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


