
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL266TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL266TBX";


CREATE TABLE "GALADM  "."GAL266TBX"  (
		  "TABLE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "COLUMN_NAME" CHAR(30 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PREFIX" CHAR(8 OCTETS) , 
		  "START_ID" INTEGER , 
		  "END_ID" INTEGER , 
		  "CURRENT_ID" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL266TBX" IS 'RMT IdCreate for managing unique ids used in database columns';


-- DDL Statements for Indexes on Table "GALADM  "."GAL266TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL266I1" ON "GALADM  "."GAL266TBX" 
		("TABLE_NAME" ASC,
		 "COLUMN_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL266TBX"

ALTER TABLE "GALADM  "."GAL266TBX" 
	ADD CONSTRAINT "GAL266_PK" PRIMARY KEY
		("TABLE_NAME",
		 "COLUMN_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL266_TR1";

CREATE TRIGGER GALADM.GAL266_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL266TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL266_TR2";

CREATE TRIGGER GALADM.GAL266_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL266TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


