
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL256TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL256TBX";


CREATE TABLE "GALADM  "."GAL256TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BEARING_SERIAL_NO" CHAR(30 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL256TBX" IS 'RMT Bearing List';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL256TBX"

ALTER TABLE "GALADM  "."GAL256TBX" 
	ADD CONSTRAINT "GAL256_PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "BEARING_SERIAL_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL256_TR1";

CREATE TRIGGER GALADM.GAL256_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL256TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL256_TR2";

CREATE TRIGGER GALADM.GAL256_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL256TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


