
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL214TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL214TBX";


CREATE TABLE "GALADM  "."GAL214TBX"  (
		  "PROCESS_POINT_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROCESS_POINT_DESCRIPTION" CHAR(128 OCTETS) , 
		  "PROCESS_POINT_TYPE" INTEGER , 
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME1" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_NAME2" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LINE_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "LINE_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BACK_FILL_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "TRACKING_POINT_FLAG" SMALLINT , 
		  "RECOVERY_POINT_FLAG" SMALLINT , 
		  "PASSING_COUNT_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CURRENT_PROD_LOT" CHAR(20 OCTETS) , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) , 
		  "CURRENT_KD_LOT" CHAR(18 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL214TBX" IS 'RMT ProcessPoint';


-- DDL Statements for Indexes on Table "GALADM  "."GAL214TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL214_I1" ON "GALADM  "."GAL214TBX" 
		("PROCESS_POINT_ID" ASC)
		INCLUDE ("PLANT_NAME" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL214TBX"

ALTER TABLE "GALADM  "."GAL214TBX" 
	ADD CONSTRAINT "GAL214_PK" PRIMARY KEY
		("PROCESS_POINT_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL214TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL214_I2" ON "GALADM  "."GAL214TBX" 
		("LINE_ID" ASC,
		 "PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL214TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL214_I3" ON "GALADM  "."GAL214TBX" 
		("LINE_ID" ASC,
		 "PROCESS_POINT_NAME" ASC,
		 "PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL214TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL214_I4" ON "GALADM  "."GAL214TBX" 
		("PROCESS_POINT_ID" ASC)
		INCLUDE ("DIVISION_ID" ,
		 "LINE_ID" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL214_TR1";

CREATE TRIGGER GALADM.GAL214_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL214TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL214_TR2";

CREATE TRIGGER GALADM.GAL214_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL214TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


