
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL228TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL228TBX";


CREATE TABLE "GALADM  "."GAL228TBX"  (
		  "SMARTEYE_LABEL_NUMBER" CHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "VIN" CHAR(17 OCTETS) , 
		  "USE_COUNT" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL228TBX" IS 'Smart Eye';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL228TBX"

ALTER TABLE "GALADM  "."GAL228TBX" 
	ADD CONSTRAINT "GAL228_PK" PRIMARY KEY
		("SMARTEYE_LABEL_NUMBER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL228_TR1";

CREATE TRIGGER GALADM.GAL228_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL228TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL228_TR2";

CREATE TRIGGER GALADM.GAL228_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL228TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


