
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL225TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL225TBX";


CREATE TABLE "GALADM  "."GAL225TBX"  (
		  "RULE_ID" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTIVE_STATE" INTEGER , 
		  "RULE_DESCRIPTION" CHAR(254 OCTETS) , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL225TBX" IS 'RMT Rule';


-- DDL Statements for Indexes on Table "GALADM  "."GAL225TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL225I1" ON "GALADM  "."GAL225TBX" 
		("RULE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL225TBX"

ALTER TABLE "GALADM  "."GAL225TBX" 
	ADD CONSTRAINT "GAL225_PK" PRIMARY KEY
		("RULE_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL225_TR1";

CREATE TRIGGER GALADM.GAL225_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL225TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL225_TR2";

CREATE TRIGGER GALADM.GAL225_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL225TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


