
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL259TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL259TBX";


CREATE TABLE "GALADM  "."GAL259TBX"  (
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ATTRIBUTE_VALUE" VARCHAR(512 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "ATTRIBUTE_DESCRIPTION" CHAR(32 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(20 OCTETS) , 
		  "SUB_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL259TBX" IS 'RMT BuildAttribute for LOT CONTROL by Product Spec Code';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL259TBX"

ALTER TABLE "GALADM  "."GAL259TBX" 
	ADD CONSTRAINT "GAL259_PK" PRIMARY KEY
		("ATTRIBUTE",
		 "PRODUCT_SPEC_CODE",
		 "SUB_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL259_TR1";

CREATE TRIGGER GALADM.GAL259_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL259TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL259_TR2";

CREATE TRIGGER GALADM.GAL259_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL259TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


