
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL237TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL237TBX";


CREATE TABLE "GALADM  "."GAL237TBX"  (
		  "GPCS_PLANT_CODE" CHAR(4 OCTETS) , 
		  "SITE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL237TBX" IS 'RMT GpcsPlant';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL237TBX"

ALTER TABLE "GALADM  "."GAL237TBX" 
	ADD CONSTRAINT "GAL237_PK" PRIMARY KEY
		("SITE_NAME",
		 "PLANT_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL237_TR1";

CREATE TRIGGER GALADM.GAL237_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL237TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL237_TR2";

CREATE TRIGGER GALADM.GAL237_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL237TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


