
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL245TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL245TBX";


CREATE TABLE "GALADM  "."GAL245TBX"  (
		  "PART_ID" CHAR(5 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT8" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL245TBX" IS 'RMT PartByProductSpecCode for LOT CONTROL to define Installed Part IDs per Product Spec Code';


-- DDL Statements for Indexes on Table "GALADM  "."GAL245TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL245_I1" ON "GALADM  "."GAL245TBX" 
		("PART_ID" ASC,
		 "PART_NAME" ASC,
		 "MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "MODEL_OPTION_CODE" ASC,
		 "EXT_COLOR_CODE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL245TBX"

ALTER TABLE "GALADM  "."GAL245TBX" 
	ADD CONSTRAINT "GAL245_PK" PRIMARY KEY
		("PART_ID",
		 "PART_NAME",
		 "MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "EXT_COLOR_CODE",
		 "INT_COLOR_CODE",
		 "PRODUCT_SPEC_CODE");




-- DDL Statements for Indexes on Table "GALADM  "."GAL245TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL245_I2" ON "GALADM  "."GAL245TBX" 
		("PART_NAME" ASC,
		 "PART_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL245_TR1";

CREATE TRIGGER GALADM.GAL245_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL245TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL245_TR2";

CREATE TRIGGER GALADM.GAL245_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL245TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


