
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL251TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL251TBX";


CREATE TABLE "GALADM  "."GAL251TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT '*' , 
		  "JOURNAL_POSITION" VARCHAR(3 OCTETS) NOT NULL WITH DEFAULT '*' , 
		  "BEARING_TYPE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "COLUMN_MEASUREMENT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ROW_MEASUREMENT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "UPPER_BEARING" CHAR(30 OCTETS) , 
		  "LOWER_BEARING" CHAR(30 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL251TBX" IS 'RMT Bearing Matrix Cell';


-- DDL Statements for Indexes on Table "GALADM  "."GAL251TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL251I1" ON "GALADM  "."GAL251TBX" 
		("MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "JOURNAL_POSITION" ASC,
		 "BEARING_TYPE" ASC,
		 "COLUMN_MEASUREMENT" ASC,
		 "ROW_MEASUREMENT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL251TBX"

ALTER TABLE "GALADM  "."GAL251TBX" 
	ADD CONSTRAINT "GAL251PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "JOURNAL_POSITION",
		 "BEARING_TYPE",
		 "COLUMN_MEASUREMENT",
		 "ROW_MEASUREMENT");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL251_TR1";

CREATE TRIGGER GALADM.GAL251_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL251TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL251_TR2";

CREATE TRIGGER GALADM.GAL251_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL251TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


