
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL240TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL240TBX";


CREATE TABLE "GALADM  "."GAL240TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PASSING_COUNTER" INTEGER , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT1" INDEX IN "GALTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL240TBX" IS 'RMT Counter';


-- DDL Statements for Indexes on Table "GALADM  "."GAL240TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL240I1" ON "GALADM  "."GAL240TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PRODUCTION_DATE" ASC,
		 "SHIFT" ASC,
		 "PERIOD" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL240TBX"

ALTER TABLE "GALADM  "."GAL240TBX" 
	ADD CONSTRAINT "GAL240_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL240_TR1";

CREATE TRIGGER GALADM.GAL240_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL240TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL240_TR2";

CREATE TRIGGER GALADM.GAL240_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL240TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


