
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL215TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL215TBX";


CREATE TABLE "GALADM  "."GAL215TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_COUNT" INTEGER WITH DEFAULT 1 , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "APPROVER_NO" CHAR(11 OCTETS) , 
		  "DEVICE_ID" VARCHAR(32 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT1" INDEX IN "GALTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL215TBX" IS 'RMT ProductResult for LINE CONTROL to record history of Product through Process Points';


-- DDL Statements for Indexes on Table "GALADM  "."GAL215TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL215_I1" ON "GALADM  "."GAL215TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC,
		 "PRODUCT_ID" ASC)
		INCLUDE ("PRODUCTION_LOT" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL215TBX"

ALTER TABLE "GALADM  "."GAL215TBX" 
	ADD CONSTRAINT "GAL215_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "ACTUAL_TIMESTAMP",
		 "PRODUCT_ID");




-- DDL Statements for Indexes on Table "GALADM  "."GAL215TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL215_I2" ON "GALADM  "."GAL215TBX" 
		("PRODUCT_ID" ASC,
		 "PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL215TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL215_I3" ON "GALADM  "."GAL215TBX" 
		("PRODUCTION_LOT" ASC,
		 "PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL215TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL215_I4" ON "GALADM  "."GAL215TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PRODUCT_SPEC_CODE" ASC,
		 "PRODUCT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COLLECT STATISTICS 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL215_TR1";

CREATE TRIGGER GALADM.GAL215_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL215TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL215_TR2";

CREATE TRIGGER GALADM.GAL215_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL215TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


