
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL235TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL235TBX";


CREATE TABLE "GALADM  "."GAL235TBX"  (
		  "ZONE_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ZONE_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ZONE_DESCRIPTION" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "LINE_ID" CHAR(16 OCTETS) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL235TBX" IS 'RMT Zone';


-- DDL Statements for Indexes on Table "GALADM  "."GAL235TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL235I1" ON "GALADM  "."GAL235TBX" 
		("ZONE_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL235TBX"

ALTER TABLE "GALADM  "."GAL235TBX" 
	ADD CONSTRAINT "GAL235_PK" PRIMARY KEY
		("ZONE_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL235_TR1";

CREATE TRIGGER GALADM.GAL235_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL235TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL235_TR2";

CREATE TRIGGER GALADM.GAL235_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL235TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


