
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL364TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL364TBX";


CREATE TABLE "GALADM  "."GAL364TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TWO_PART_PAIR_LOCATION" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TWO_PART_PAIR_PART" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PART_GROUP_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT 'TWO PART PAIR' , 
		  "DESCRIPTION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL364TBX" IS 'RMT InspectionTwoPartDescription for QICS';


-- DDL Statements for Indexes on Table "GALADM  "."GAL364TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL364I1" ON "GALADM  "."GAL364TBX" 
		("INSPECTION_PART_NAME" ASC,
		 "INSPECTION_PART_LOCATION_NAME" ASC,
		 "TWO_PART_PAIR_LOCATION" ASC,
		 "PART_GROUP_NAME" ASC,
		 "TWO_PART_PAIR_PART" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL364TBX"

ALTER TABLE "GALADM  "."GAL364TBX" 
	ADD CONSTRAINT "GAL364_PK" PRIMARY KEY
		("INSPECTION_PART_NAME",
		 "INSPECTION_PART_LOCATION_NAME",
		 "TWO_PART_PAIR_LOCATION",
		 "PART_GROUP_NAME",
		 "TWO_PART_PAIR_PART");



-- DDL Statements for Unique Constraints on Table "GALADM  "."GAL364TBX"


ALTER TABLE "GALADM  "."GAL364TBX" 
	ADD UNIQUE
		("DESCRIPTION_ID");







-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL364_TR1";

CREATE TRIGGER GALADM.GAL364_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL364TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL364_TR2";

CREATE TRIGGER GALADM.GAL364_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL364TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


