
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL322TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL322TBX";


CREATE TABLE "GALADM  "."GAL322TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SECONDARY_PART_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "TWO_PART_PAIR_PART" VARCHAR(32 OCTETS) NOT NULL , 
		  "TWO_PART_PAIR_LOCATION" VARCHAR(20 OCTETS) NOT NULL , 
		  "PART_GROUP_NAME" CHAR(20 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "IQS_CATEGORY_NAME" CHAR(32 OCTETS) , 
		  "IQS_ITEM_NAME" CHAR(64 OCTETS) , 
		  "REGRESSION_CODE" CHAR(32 OCTETS) , 
		  "LOCK_MODE" SMALLINT , 
		  "RESPONSIBLE_DEPT" VARCHAR(32 OCTETS) , 
		  "RESPONSIBLE_ZONE" VARCHAR(32 OCTETS) , 
		  "TWO_PART_DEFECT_FLAG" SMALLINT , 
		  "INVENTORY_REPAIR_TIME" INTEGER , 
		  "ONLINE_REPAIR_TIME" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "RESPONSIBLE_LINE" VARCHAR(32 OCTETS) , 
		  "ENGINE_FIRING_FLAG" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "REPAIR_AREA" CHAR(20 OCTETS) , 
		  "REPAIR_DEPARTMENT" CHAR(32 OCTETS) )   
		 IN "GALTBSDAT5" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL322TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL322TBX" IS 'RMT DefectDescription for QICS';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL322TBX"

ALTER TABLE "GALADM  "."GAL322TBX" 
	ADD CONSTRAINT "GAL322_PK" PRIMARY KEY
		("INSPECTION_PART_NAME",
		 "INSPECTION_PART_LOCATION_NAME",
		 "DEFECT_TYPE_NAME",
		 "TWO_PART_PAIR_PART",
		 "TWO_PART_PAIR_LOCATION",
		 "SECONDARY_PART_NAME",
		 "PART_GROUP_NAME");



-- DDL Statements for Indexes on Table "GALADM  "."GAL322TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL322_I1" ON "GALADM  "."GAL322TBX" 
		("INSPECTION_PART_NAME" ASC,
		 "TWO_PART_PAIR_PART" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL322TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL322_I2" ON "GALADM  "."GAL322TBX" 
		("INSPECTION_PART_NAME" ASC,
		 "DEFECT_TYPE_NAME" ASC,
		 "INSPECTION_PART_LOCATION_NAME" ASC,
		 "SECONDARY_PART_NAME" ASC,
		 "RESPONSIBLE_ZONE" ASC,
		 "RESPONSIBLE_DEPT" ASC,
		 "REGRESSION_CODE" ASC,
		 "IQS_ITEM_NAME" ASC,
		 "IQS_CATEGORY_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL322_TR1";

CREATE TRIGGER GALADM.GAL322_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL322TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL322_TR2";

CREATE TRIGGER GALADM.GAL322_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL322TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


