
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL324TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL324TBX";


CREATE TABLE "GALADM  "."GAL324TBX"  (
		  "SECURITY_GRP" VARCHAR(255 OCTETS) NOT NULL , 
		  "GROUP_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL324TBX" IS 'RMT SecurityGroup for SECURITY';


-- DDL Statements for Indexes on Table "GALADM  "."GAL324TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL324I1" ON "GALADM  "."GAL324TBX" 
		("SECURITY_GRP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL324TBX"

ALTER TABLE "GALADM  "."GAL324TBX" 
	ADD CONSTRAINT "GAL324PK" PRIMARY KEY
		("SECURITY_GRP");




-- DDL Statements for Indexes on Table "GALADM  "."GAL324TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL324I2" ON "GALADM  "."GAL324TBX" 
		("SECURITY_GRP" ASC,
		 "GROUP_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL324_TR1";

CREATE TRIGGER GALADM.GAL324_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL324TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL324_TR2";

CREATE TRIGGER GALADM.GAL324_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL324TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


