
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL489TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL489TBX";


CREATE TABLE "GALADM  "."GAL489TBX"  (
		  "COMPONENT_ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "PROPERTY_KEY" VARCHAR(64 OCTETS) NOT NULL , 
		  "PROPERTY_VALUE" VARCHAR(1024 OCTETS) NOT NULL , 
		  "DESCRIPTION" VARCHAR(64 OCTETS) , 
		  "CHANGE_USER_ID" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL489TBX" PCTFREE 0;

ALTER TABLE "GALADM  "."GAL489TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL489TBX" IS 'RMT ComponentProperty for managing application properties';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL489TBX"

ALTER TABLE "GALADM  "."GAL489TBX" 
	ADD CONSTRAINT "GAL489_PK" PRIMARY KEY
		("COMPONENT_ID",
		 "PROPERTY_KEY");



-- DDL Statements for Indexes on Table "GALADM  "."GAL489TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL489_I1" ON "GALADM  "."GAL489TBX" 
		("PROPERTY_KEY" ASC,
		 "COMPONENT_ID" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL489_TR1";

CREATE TRIGGER GALADM.GAL489_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL489_TR2";

CREATE TRIGGER GALADM.GAL489_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


