
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL600TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL600TBX";


CREATE TABLE "GALADM  "."GAL600TBX"  (
		  "USER_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "PASSWORD" VARCHAR(32 OCTETS) FOR BIT DATA , 
		  "USER_DESC" VARCHAR(64 OCTETS) , 
		  "DISPLAY_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL600TBX" IS 'RMT AdminUser for SECURITY';

COMMENT ON COLUMN "GALADM  "."GAL600TBX"."PASSWORD" IS 'Encrypted password';

COMMENT ON COLUMN "GALADM  "."GAL600TBX"."USER_DESC" IS 'User Description';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL600TBX"

ALTER TABLE "GALADM  "."GAL600TBX" 
	ADD CONSTRAINT "GAL600_PK" PRIMARY KEY
		("USER_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL600_TR1";

CREATE TRIGGER GALADM.GAL600_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL600TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL600_TR2";

CREATE TRIGGER GALADM.GAL600_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL600TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


