
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL601TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL601TBX";


CREATE TABLE "GALADM  "."GAL601TBX"  (
		  "GROUP_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "GROUP_DESC" VARCHAR(64 OCTETS) , 
		  "DISPLAY_NAME" VARCHAR(64 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL601TBX" IS 'RMT AdminGroup for SECURITY';

COMMENT ON COLUMN "GALADM  "."GAL601TBX"."GROUP_DESC" IS 'Group Description';

COMMENT ON COLUMN "GALADM  "."GAL601TBX"."GROUP_ID" IS 'Group ID';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL601TBX"

ALTER TABLE "GALADM  "."GAL601TBX" 
	ADD CONSTRAINT "GAL601_PK" PRIMARY KEY
		("GROUP_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL601_TR1";

CREATE TRIGGER GALADM.GAL601_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL601TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL601_TR2";

CREATE TRIGGER GALADM.GAL601_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL601TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


