
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL602TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL602TBX";


CREATE TABLE "GALADM  "."GAL602TBX"  (
		  "USER_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "GROUP_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL602TBX" IS 'RMT AdminUserGroup for SECURITY';

COMMENT ON COLUMN "GALADM  "."GAL602TBX"."USER_ID" IS 'User ID';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL602TBX"

ALTER TABLE "GALADM  "."GAL602TBX" 
	ADD CONSTRAINT "GAL602_PK" PRIMARY KEY
		("USER_ID",
		 "GROUP_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GAL602TBX"

ALTER TABLE "GALADM  "."GAL602TBX" 
	ADD CONSTRAINT "GAL602_REFGAL600" FOREIGN KEY
		("USER_ID")
	REFERENCES "GALADM  "."GAL600TBX"
		("USER_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GAL602TBX" 
	ADD CONSTRAINT "GAL602_REFGAL601" FOREIGN KEY
		("GROUP_ID")
	REFERENCES "GALADM  "."GAL601TBX"
		("GROUP_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL602_TR1";

CREATE TRIGGER GALADM.GAL602_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL602TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL602_TR2";

CREATE TRIGGER GALADM.GAL602_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL602TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


