
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL722TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL722TBX";


CREATE TABLE "GALADM  "."GAL722TBX"  (
		  "LET_MFG_AREA_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LET_MFG_NO" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LET_LINE_NO" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT  , 
		  "SOFTWARE_VERSION" VARCHAR(32 OCTETS) , 
		  "TOTAL_TEST_STATUS" CHAR(1 OCTETS) , 
		  "MEMORY_TEST_STATUS" CHAR(1 OCTETS) , 
		  "PROCESSOR_TEST_STATUS" CHAR(1 OCTETS) , 
		  "DISK_TEST_STATUS" CHAR(1 OCTETS) , 
		  "KEYBOAD_TEST_STATUS" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL722TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL722TBX" IS 'LET Diagnosis Result ( Version:1.07 )';


-- DDL Statements for Indexes on Table "GALADM  "."GAL722TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL722I1" ON "GALADM  "."GAL722TBX" 
		("LET_MFG_AREA_CODE" ASC,
		 "LET_MFG_NO" ASC,
		 "LET_LINE_NO" ASC,
		 "LET_TERMINAL_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL722TBX"

ALTER TABLE "GALADM  "."GAL722TBX" 
	ADD CONSTRAINT "GAL722_PK" PRIMARY KEY
		("LET_MFG_AREA_CODE",
		 "LET_MFG_NO",
		 "LET_LINE_NO",
		 "LET_TERMINAL_ID",
		 "ACTUAL_TIMESTAMP");




-- DDL Statements for Indexes on Table "GALADM  "."GAL722TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL722I2" ON "GALADM  "."GAL722TBX" 
		("ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL722TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL722I3" ON "GALADM  "."GAL722TBX" 
		("LET_LINE_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL722_TR1";

CREATE TRIGGER GALADM.GAL722_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL722TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL722_TR2";

CREATE TRIGGER GALADM.GAL722_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL722TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


