
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL704TBX_03"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL704TBX_03";


CREATE TABLE "GALADM  "."GAL704TBX_03"  (
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PARAM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PARAM_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PARAM_VALUE" VARCHAR(255 OCTETS) , 
		  "INSPECTION_PARAM_UNIT" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "LOW_LIMIT" VARCHAR(32 OCTETS) , 
		  "HIGH_LIMIT" VARCHAR(32 OCTETS) )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL704TBX_03" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL704TBX_03" IS 'RMT LetProgramValueThree for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL704TBX_03"

ALTER TABLE "GALADM  "."GAL704TBX_03" 
	ADD CONSTRAINT "GAL704TBX_03_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "PRODUCT_ID",
		 "TEST_SEQ",
		 "INSPECTION_PGM_ID",
		 "INSPECTION_PARAM_ID",
		 "INSPECTION_PARAM_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL704TBX_03_TR1";

CREATE TRIGGER GALADM.GAL704TBX_03_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL704TBX_03
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL704TBX_03_TR2";

CREATE TRIGGER GALADM.GAL704TBX_03_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL704TBX_03
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


