
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL713TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL713TBX";


CREATE TABLE "GALADM  "."GAL713TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HISTORY_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PARAM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PARAM_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INSPECTION_PARAM_VALUE" VARCHAR(32 OCTETS) , 
		  "INSPECTION_PARAM_UNIT" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL713TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL713TBX" IS 'RMT LetProgramResultValueHistory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL713TBX"

ALTER TABLE "GALADM  "."GAL713TBX" 
	ADD CONSTRAINT "GAL713_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "HISTORY_SEQ",
		 "TEST_SEQ",
		 "INSPECTION_PGM_ID",
		 "INSPECTION_PARAM_ID",
		 "INSPECTION_PARAM_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL713_TR1";

CREATE TRIGGER GALADM.GAL713_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL713TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL713_TR2";

CREATE TRIGGER GALADM.GAL713_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL713TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


