
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL717TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL717TBX";


CREATE TABLE "GALADM  "."GAL717TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EFFECTIVE_TIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "CRITERIA_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "INSPECTION_DEVICE_TYPE" CHAR(1 OCTETS) , 
		  "CRITERIA_PGM_ATTRIBUTE" CHAR(1 OCTETS) )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL717TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL717TBX" IS 'RMT LetPassCriteria for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL717TBX"

ALTER TABLE "GALADM  "."GAL717TBX" 
	ADD CONSTRAINT "GAL717_PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "EFFECTIVE_TIME",
		 "CRITERIA_PGM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL717_TR1";

CREATE TRIGGER GALADM.GAL717_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL717TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL717_TR2";

CREATE TRIGGER GALADM.GAL717_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL717TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


