
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL725TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL725TBX";


CREATE TABLE "GALADM  "."GAL725TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "PASS_STATUS" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL725TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL725TBX" IS 'RMT LetResult for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL725TBX"

ALTER TABLE "GALADM  "."GAL725TBX" 
	ADD CONSTRAINT "GAL725_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ACTUAL_TIMESTAMP");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL725_TR1";

CREATE TRIGGER GALADM.GAL725_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL725TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL725_TR2";

CREATE TRIGGER GALADM.GAL725_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL725TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


