
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL700TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL700TBX";


CREATE TABLE "GALADM  "."GAL700TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "SERIES_FRAME_NO" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GAL700TBX" IS 'RMT Product for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL700TBX"

ALTER TABLE "GALADM  "."GAL700TBX" 
	ADD CONSTRAINT "GAL700_PK" PRIMARY KEY
		("PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL700_TR1";

CREATE TRIGGER GALADM.GAL700_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL700TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL700_TR2";

CREATE TRIGGER GALADM.GAL700_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL700TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


