
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL712TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL712TBX";


CREATE TABLE "GALADM  "."GAL712TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HISTORY_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_STATUS" CHAR(1 OCTETS) , 
		  "PROCESS_STEP" CHAR(9 OCTETS) , 
		  "PROCESS_STATUS" CHAR(1 OCTETS) , 
		  "PROCESS_START_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_END_TIMESTAMP" TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) , 
		  "LET_RESULT_CAL" CHAR(19 OCTETS) , 
		  "LET_RESULT_DCREV" CHAR(16 OCTETS) , 
		  "SOFTWARE_VERSION" VARCHAR(32 OCTETS) , 
		  "LET_OPERATOR_ID" CHAR(16 OCTETS) , 
		  "IN_CYCLE_RETEST_NUM" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL712TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL712TBX" IS 'RMT LetProgramResultHistory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL712TBX"

ALTER TABLE "GALADM  "."GAL712TBX" 
	ADD CONSTRAINT "GAL712_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "HISTORY_SEQ",
		 "TEST_SEQ",
		 "INSPECTION_PGM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL712_TR1";

CREATE TRIGGER GALADM.GAL712_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL712TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL712_TR2";

CREATE TRIGGER GALADM.GAL712_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL712TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


