CREATE VIEW GALADM.GAL703TBXV      ( END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PGM_STATUS,      PROCESS_STEP, PROCESS_STATUS, PROCESS_START_TIMESTAMP, PROCESS_END_TIMESTAMP, LET_TERMINAL_ID,      LET_RESULT_CAL, LET_RESULT_DCREV, SOFTWARE_VERSION, LET_OPERATOR_ID, IN_CYCLE_RETEST_NUM, CREATE_TIMESTAMP, UPDATE_TIMESTAMP )  AS      
  select *         
  from GALADM.GAL703TBX_01     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_02         
  UNION ALL     
  select *         
  from GALADM.GAL703TBX_03         
  UNION ALL         
  select *     
  from GALADM.GAL703TBX_04     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_05     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_06      
  WITH NO ROW MOVEMENT;

COMMENT ON TABLE "GALADM"."GAL703TBXV" IS 'Union ALL of All Six 703TBX Tables';
