
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL703TBX_03"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL703TBX_03";


CREATE TABLE "GALADM  "."GAL703TBX_03"  (
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_STATUS" CHAR(1 OCTETS) , 
		  "PROCESS_STEP" CHAR(9 OCTETS) , 
		  "PROCESS_STATUS" CHAR(1 OCTETS) , 
		  "PROCESS_START_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_END_TIMESTAMP" TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) , 
		  "LET_RESULT_CAL" CHAR(19 OCTETS) , 
		  "LET_RESULT_DCREV" CHAR(16 OCTETS) , 
		  "SOFTWARE_VERSION" VARCHAR(32 OCTETS) , 
		  "LET_OPERATOR_ID" CHAR(16 OCTETS) , 
		  "IN_CYCLE_RETEST_NUM" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL703TBX_03" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL703TBX_03" IS 'RMT LetProgramResultThree for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL703TBX_03"

ALTER TABLE "GALADM  "."GAL703TBX_03" 
	ADD CONSTRAINT "GAL703TBX_03_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "PRODUCT_ID",
		 "TEST_SEQ",
		 "INSPECTION_PGM_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL703TBX_03"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL703_I2_03" ON "GALADM  "."GAL703TBX_03" 
		("PRODUCT_ID" ASC,
		 "TEST_SEQ" ASC,
		 "INSPECTION_PGM_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL703TBX_03_TR1";

CREATE TRIGGER GALADM.GAL703TBX_03_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL703TBX_03
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL703TBX_03_TR2";

CREATE TRIGGER GALADM.GAL703TBX_03_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL703TBX_03
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


