
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL711TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL711TBX";


CREATE TABLE "GALADM  "."GAL711TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HISTORY_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "ECU_NAME" VARCHAR(64 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "ECU_LOG" VARCHAR(10000 OCTETS) FOR BIT DATA , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT2" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL711TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL711TBX" IS 'RMT LetLogHistory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL711TBX"

ALTER TABLE "GALADM  "."GAL711TBX" 
	ADD CONSTRAINT "GAL711_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "HISTORY_SEQ",
		 "TEST_SEQ",
		 "ECU_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL711_TR1";

CREATE TRIGGER GALADM.GAL711_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL711TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL711_TR2";

CREATE TRIGGER GALADM.GAL711_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL711TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


