
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL719TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL719TBX";


CREATE TABLE "GALADM  "."GAL719TBX"  (
		  "USER_ID" CHAR(11 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL719TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL719TBX" IS 'LET User ( Version:1.01 )';


-- DDL Statements for Indexes on Table "GALADM  "."GAL719TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL719I1" ON "GALADM  "."GAL719TBX" 
		("USER_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL719TBX"

ALTER TABLE "GALADM  "."GAL719TBX" 
	ADD CONSTRAINT "GAL719_PK" PRIMARY KEY
		("USER_ID");



-- DDL Statements for Aliases based on Table "GALADM  "."GAL719TBX"

DROP ALIAS "LETDB   "."GAL719TBX";

CREATE ALIAS "LETDB   "."GAL719TBX" FOR TABLE "GALADM  "."GAL719TBX";







-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL719_TR1";

CREATE TRIGGER GALADM.GAL719_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL719TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL719_TR2";

CREATE TRIGGER GALADM.GAL719_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL719TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


