
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL721TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL721TBX";


CREATE TABLE "GALADM  "."GAL721TBX"  (
		  "APPLICATION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL721TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL721TBX" IS 'LET Application ( Version:1.03 )';


-- DDL Statements for Indexes on Table "GALADM  "."GAL721TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL721I1" ON "GALADM  "."GAL721TBX" 
		("APPLICATION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL721TBX"

ALTER TABLE "GALADM  "."GAL721TBX" 
	ADD CONSTRAINT "GAL721_PK" PRIMARY KEY
		("APPLICATION_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL721_TR1";

CREATE TRIGGER GALADM.GAL721_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL721TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL721_TR2";

CREATE TRIGGER GALADM.GAL721_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL721TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


