
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL710TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL710TBX";


CREATE TABLE "GALADM  "."GAL710TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HISTORY_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "BUILD_CODE" CHAR(20 OCTETS) , 
		  "TEST_ID" CHAR(20 OCTETS) , 
		  "INSPECTION_MTO" CHAR(20 OCTETS) , 
		  "SEQ_STEP_FILE" VARCHAR(50 OCTETS) , 
		  "CONT_STEP_FILE" VARCHAR(50 OCTETS) , 
		  "SEQ_RANGE" CHAR(20 OCTETS) , 
		  "TOTAL_RESULT_STATUS" CHAR(1 OCTETS) , 
		  "START_TIMESTAMP" TIMESTAMP , 
		  "END_TIMESTAMP" TIMESTAMP , 
		  "LET_MFG_AREA_CODE" CHAR(1 OCTETS) , 
		  "LET_MFG_NO" CHAR(1 OCTETS) , 
		  "LET_LINE_NO" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "BASE_RELEASE" CHAR(19 OCTETS) , 
		  "PRODUCTION" CHAR(1 OCTETS) , 
		  "ADDITIONAL_DATA" CHAR(11 OCTETS) )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL710TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL710TBX" IS 'RMT LetResultHistory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL710TBX"

ALTER TABLE "GALADM  "."GAL710TBX" 
	ADD CONSTRAINT "GAL710_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "HISTORY_SEQ",
		 "TEST_SEQ");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL710_TR1";

CREATE TRIGGER GALADM.GAL710_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL710TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL710_TR2";

CREATE TRIGGER GALADM.GAL710_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL710TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


