
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL714TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL714TBX";


CREATE TABLE "GALADM  "."GAL714TBX"  (
		  "INSPECTION_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PGM_NAME" VARCHAR(75 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL714TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL714TBX" IS 'RMT LetInspectionProgram for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL714TBX"

ALTER TABLE "GALADM  "."GAL714TBX" 
	ADD CONSTRAINT "GAL714_PK" PRIMARY KEY
		("INSPECTION_PGM_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL714TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL714_I1" ON "GALADM  "."GAL714TBX" 
		("INSPECTION_PGM_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL714_TR1";

CREATE TRIGGER GALADM.GAL714_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL714TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL714_TR2";

CREATE TRIGGER GALADM.GAL714_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL714TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


