
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL715TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL715TBX";


CREATE TABLE "GALADM  "."GAL715TBX"  (
		  "INSPECTION_PARAM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INSPECTION_PARAM_NAME" VARCHAR(300 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL715TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL715TBX" IS 'RMT LetInspectionParam for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL715TBX"

ALTER TABLE "GALADM  "."GAL715TBX" 
	ADD CONSTRAINT "GAL715_PK" PRIMARY KEY
		("INSPECTION_PARAM_ID");



-- DDL Statements for Indexes on Table "GALADM  "."GAL715TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL715_I1" ON "GALADM  "."GAL715TBX" 
		("INSPECTION_PARAM_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL715_TR1";

CREATE TRIGGER GALADM.GAL715_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL715TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL715_TR2";

CREATE TRIGGER GALADM.GAL715_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL715TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


