
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL718TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL718TBX";


CREATE TABLE "GALADM  "."GAL718TBX"  (
		  "CRITERIA_PGM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CRITERIA_PGM_NAME" VARCHAR(75 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "INSPECTION_DEVICE_TYPE" CHAR(1 OCTETS) , 
		  "CRITERIA_PGM_ATTRIBUTE" CHAR(1 OCTETS) )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL718TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL718TBX" IS 'RMT LetPassCriteriaProgram for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL718TBX"

ALTER TABLE "GALADM  "."GAL718TBX" 
	ADD CONSTRAINT "GAL718_PK" PRIMARY KEY
		("CRITERIA_PGM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL718_TR1";

CREATE TRIGGER GALADM.GAL718_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL718TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL718_TR2";

CREATE TRIGGER GALADM.GAL718_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL718TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


