
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL720TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL720TBX";


CREATE TABLE "GALADM  "."GAL720TBX"  (
		  "SECURITY_GRP" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SECURITY_GRP_NAME" CHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL720TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL720TBX" IS 'LET Security Group ( Version:1.01 )';


-- DDL Statements for Indexes on Table "GALADM  "."GAL720TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GAL720I1" ON "GALADM  "."GAL720TBX" 
		("SECURITY_GRP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."GAL720TBX"

ALTER TABLE "GALADM  "."GAL720TBX" 
	ADD CONSTRAINT "GAL720_PK" PRIMARY KEY
		("SECURITY_GRP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL720_TR1";

CREATE TRIGGER GALADM.GAL720_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL720TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL720_TR2";

CREATE TRIGGER GALADM.GAL720_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL720TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


