
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL723TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL723TBX";


CREATE TABLE "GALADM  "."GAL723TBX"  (
		  "TABLE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PHYSICAL_TABLE_OFFSET" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PHYSICAL_TABLE_NAME" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL723TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL723TBX" IS 'RMT PhysicalTablePartitionSetting for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL723TBX"

ALTER TABLE "GALADM  "."GAL723TBX" 
	ADD CONSTRAINT "GAL723_PK" PRIMARY KEY
		("TABLE_NAME",
		 "PHYSICAL_TABLE_OFFSET");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL723_TR1";

CREATE TRIGGER GALADM.GAL723_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL723TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL723_TR2";

CREATE TRIGGER GALADM.GAL723_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL723TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


