
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL728TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL728TBX";


CREATE TABLE "GALADM  "."GAL728TBX"  (
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIAG_TEST_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "FAULT_CODE_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "SHORT_DESC_ID" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL728TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL728TBX" IS 'RMT DiagFaultDetail for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL728TBX"

ALTER TABLE "GALADM  "."GAL728TBX" 
	ADD CONSTRAINT "GAL728_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "LET_TERMINAL_ID",
		 "DIAG_TEST_ID",
		 "FAULT_CODE_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL728_TR1";

CREATE TRIGGER GALADM.GAL728_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL728TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL728_TR2";

CREATE TRIGGER GALADM.GAL728_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL728TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


