
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL724TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL724TBX";


CREATE TABLE "GALADM  "."GAL724TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TABLE_NAME" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PHYSICAL_TABLE_NAME" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL724TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL724TBX" IS 'RMT PhysicalTableMap for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL724TBX"

ALTER TABLE "GALADM  "."GAL724TBX" 
	ADD CONSTRAINT "GAL724_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "TABLE_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL724_TR1";

CREATE TRIGGER GALADM.GAL724_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL724TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL724_TR2";

CREATE TRIGGER GALADM.GAL724_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL724TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


