
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL709TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL709TBX";


CREATE TABLE "GALADM  "."GAL709TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "HISTORY_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "USER_ID" CHAR(11 OCTETS) , 
		  "MODIFY_TIMESTAMP" TIMESTAMP , 
		  "MODIFY_TYPE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL709TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL709TBX" IS 'RMT LetModifyHistory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL709TBX"

ALTER TABLE "GALADM  "."GAL709TBX" 
	ADD CONSTRAINT "GAL709_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "HISTORY_SEQ");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL709_TR1";

CREATE TRIGGER GALADM.GAL709_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL709TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL709_TR2";

CREATE TRIGGER GALADM.GAL709_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL709TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


