
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL716TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL716TBX";


CREATE TABLE "GALADM  "."GAL716TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EFFECTIVE_TIME" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "EXPIRATION_TIME" TIMESTAMP , 
		  "CONDITION_WEIGHT" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL716TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL716TBX" IS 'RMT LetPassCriteriaMTO for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL716TBX"

ALTER TABLE "GALADM  "."GAL716TBX" 
	ADD CONSTRAINT "GAL716_PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "EFFECTIVE_TIME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL716_TR1";

CREATE TRIGGER GALADM.GAL716_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL716TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL716_TR2";

CREATE TRIGGER GALADM.GAL716_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL716TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


