
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL730TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL730TBX";


CREATE TABLE "GALADM  "."GAL730TBX"  (
		  "INSPECTION_DEVICE_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CRITERIA_PGM_ATTRIBUTE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PGM_CATEGORY_NAME" CHAR(15 OCTETS) , 
		  "BG_COLOR" CHAR(7 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL730TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL730TBX" IS 'RMT LetProgramCategory for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL730TBX"

ALTER TABLE "GALADM  "."GAL730TBX" 
	ADD CONSTRAINT "GAL730_PK" PRIMARY KEY
		("INSPECTION_DEVICE_TYPE",
		 "CRITERIA_PGM_ATTRIBUTE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL730_TR1";

CREATE TRIGGER GALADM.GAL730_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL730TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL730_TR2";

CREATE TRIGGER GALADM.GAL730_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL730TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


