
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL726TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL726TBX";


CREATE TABLE "GALADM  "."GAL726TBX"  (
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "TOTAL_RESULT_STATUS" CHAR(1 OCTETS) , 
		  "BASE_RELEASE" CHAR(19 OCTETS) , 
		  "SOFTWARE_VERSION" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL726TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL726TBX" IS 'RMT LetDiagResult for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL726TBX"

ALTER TABLE "GALADM  "."GAL726TBX" 
	ADD CONSTRAINT "GAL726_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "LET_TERMINAL_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL726_TR1";

CREATE TRIGGER GALADM.GAL726_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL726TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL726_TR2";

CREATE TRIGGER GALADM.GAL726_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL726TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


