
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL729TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL729TBX";


CREATE TABLE "GALADM  "."GAL729TBX"  (
		  "DIAG_PARAM_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "DIAG_PARAM_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIAG_PARAM_VALUE" VARCHAR(75 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIAG_TEST_ID" INTEGER NOT NULL WITH DEFAULT 0 )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL729TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL729TBX" IS 'RMT LetDiagName for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL729TBX"

ALTER TABLE "GALADM  "."GAL729TBX" 
	ADD CONSTRAINT "GAL729TBX_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "LET_TERMINAL_ID",
		 "DIAG_TEST_ID",
		 "DIAG_PARAM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL729_TR1";

CREATE TRIGGER GALADM.GAL729_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL729TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL729_TR2";

CREATE TRIGGER GALADM.GAL729_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL729TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


