
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL701TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL701TBX";


CREATE TABLE "GALADM  "."GAL701TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TEST_SEQ" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "BUILD_CODE" CHAR(20 OCTETS) , 
		  "TEST_ID" CHAR(20 OCTETS) , 
		  "INSPECTION_MTO" CHAR(20 OCTETS) , 
		  "SEQ_STEP_FILE" VARCHAR(50 OCTETS) , 
		  "CONT_STEP_FILE" VARCHAR(50 OCTETS) , 
		  "SEQ_RANGE" CHAR(20 OCTETS) , 
		  "TOTAL_RESULT_STATUS" CHAR(1 OCTETS) , 
		  "START_TIMESTAMP" TIMESTAMP , 
		  "END_TIMESTAMP" TIMESTAMP , 
		  "LET_MFG_AREA_CODE" CHAR(1 OCTETS) , 
		  "LET_MFG_NO" CHAR(1 OCTETS) , 
		  "LET_LINE_NO" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "BASE_RELEASE" CHAR(19 OCTETS) , 
		  "PRODUCTION" CHAR(1 OCTETS) , 
		  "ADDITIONAL_DATA" CHAR(11 OCTETS) )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL701TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL701TBX" IS 'RMT LetResult for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL701TBX"

ALTER TABLE "GALADM  "."GAL701TBX" 
	ADD CONSTRAINT "GAL701_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "TEST_SEQ");



-- DDL Statements for Indexes on Table "GALADM  "."GAL701TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL701_I1" ON "GALADM  "."GAL701TBX" 
		("END_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."GAL701TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."GAL701_I2" ON "GALADM  "."GAL701TBX" 
		("LET_LINE_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL701_TR1";

CREATE TRIGGER GALADM.GAL701_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL701TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL701_TR2";

CREATE TRIGGER GALADM.GAL701_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL701TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


