
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GAL727TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GAL727TBX";


CREATE TABLE "GALADM  "."GAL727TBX"  (
		  "END_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "LET_TERMINAL_ID" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DIAG_TEST_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "DIAG_TEST_STATUS" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "LETTBSDAT1" INDEX IN "LETTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."GAL727TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."GAL727TBX" IS 'RMT LetDiagDetail for LET';


-- DDL Statements for Primary Key on Table "GALADM  "."GAL727TBX"

ALTER TABLE "GALADM  "."GAL727TBX" 
	ADD CONSTRAINT "GAL727_PK" PRIMARY KEY
		("END_TIMESTAMP",
		 "LET_TERMINAL_ID",
		 "DIAG_TEST_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL727_TR1";

CREATE TRIGGER GALADM.GAL727_TR1 NO CASCADE BEFORE INSERT ON GALADM.GAL727TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GAL727_TR2";

CREATE TRIGGER GALADM.GAL727_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GAL727TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


