
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GALCDB_VER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GALCDB_VER_TBX";


CREATE TABLE "GALADM  "."GALCDB_VER_TBX"  (
		  "VERSION" VARCHAR(15 OCTETS) , 
		  "DESC" VARCHAR(80 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "GALADM  "."GALCDB_VER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."GALCDB_VER_I1" ON "GALADM  "."GALCDB_VER_TBX" 
		("VERSION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GALCDB_VER_TR1";

CREATE TRIGGER GALADM.GALCDB_VER_TR1
NO CASCADE BEFORE INSERT
ON "GALADM"."GALCDB_VER_TBX"
REFERENCING
NEW AS A
FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GALCDB_VER_TR2";

CREATE TRIGGER GALADM.GALCDB_VER_TR2
NO CASCADE BEFORE UPDATE
ON "GALADM"."GALCDB_VER_TBX"
REFERENCING
NEW AS A
FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


