------------------------------------------------
-- DDL Statements for Table "GALADM  "."GALC_TO_PDDA_MAPPING_TBX" AS PART OF RGALCDEV-8543
------------------------------------------------

DROP TABLE GALADM.GALC_TO_PDDA_MAPPING_TBX;
DROP TRIGGER GALADM.GALC_TO_PDDA_MAPPING_TR1;
DROP TRIGGER GALADM.GALC_TO_PDDA_MAPPING_TR2;

CREATE TABLE GALADM.GALC_TO_PDDA_MAPPING_TBX (
  ID INTEGER NOT NULL,
  PROCESS_POINT_ID VARCHAR(16),
  PROCESS_NUMBER CHAR(8),
  CREATED_BY VARCHAR(100),
  UPDATED_BY VARCHAR(100),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP
) IN GALTBSDAT9 INDEX IN GALTBSIDX3;

COMMENT ON TABLE GALADM.GALC_TO_PDDA_MAPPING_TBX IS 'Mapping of NAQ/PDDA process id and GALC process point id';

ALTER TABLE GALADM.GALC_TO_PDDA_MAPPING_TBX 
	ADD CONSTRAINT GALC_TO_PDDA_MAPPING_TIMER_PK PRIMARY KEY (ID);
	
CREATE TRIGGER GALADM.GALC_TO_PDDA_MAPPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GALC_TO_PDDA_MAPPING_TBX
  REFERENCING
    NEW AS A
 FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GALC_TO_PDDA_MAPPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GALC_TO_PDDA_MAPPING_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
