
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_CLIENT_LIST_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_CLIENT_LIST_TBX";


CREATE TABLE "GALADM  "."GTS_CLIENT_LIST_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "CLIENT_IP" VARCHAR(40 OCTETS) NOT NULL , 
		  "CLIENT_PORT" SMALLINT NOT NULL , 
		  "CLIENT_NAME" VARCHAR(40 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" IS 'GTS Client List';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_CLIENT_LIST_TBX"

ALTER TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" 
	ADD CONSTRAINT "GTS_CLIENT_LIST_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "CLIENT_IP",
		 "CLIENT_PORT");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_CLIENT_LIST_TBX"

ALTER TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" 
	ADD CONSTRAINT "AREA_CLIENT_LIST_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_CLIENT_LIST_TR1";

CREATE TRIGGER GALADM.GTS_CLIENT_LIST_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_CLIENT_LIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_CLIENT_LIST_TR2";

CREATE TRIGGER GALADM.GTS_CLIENT_LIST_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_CLIENT_LIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


