
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_SEGMENT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX";


CREATE TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "LANE_SEGMENT_ID" INTEGER NOT NULL , 
		  "LANE_SEGMENT_NAME" VARCHAR(40 OCTETS) , 
		  "INPUT_NODE_ID" INTEGER NOT NULL , 
		  "OUTPUT_NODE_ID" INTEGER NOT NULL , 
		  "LANE_SEGMENT_CAPACITY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POWERED" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "INPUT_CPX" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INPUT_CPY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "OUTPUT_CPX" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "OUTPUT_CPY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CARRIER_VISIBLE" INTEGER NOT NULL WITH DEFAULT 1 , 
		  "IS_SOURCE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "IS_DESTINATION" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" IS 'GTS Lane Segment';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_SEGMENT_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "GTS_LANE_SEGMENT_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_SEGMENT_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "AREA_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "NODE_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "OUTPUT_NODE_ID")
	REFERENCES "GALADM  "."GTS_NODE_TBX"
		("TRACKING_AREA",
		 "NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "NODE_LANE_SEGMENT_FK2" FOREIGN KEY
		("TRACKING_AREA",
		 "INPUT_NODE_ID")
	REFERENCES "GALADM  "."GTS_NODE_TBX"
		("TRACKING_AREA",
		 "NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_SEGMENT_TR1";

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_LANE_SEGMENT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_SEGMENT_TR2";

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_LANE_SEGMENT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


