
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_DECISION_POINT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_DECISION_POINT_TBX";


CREATE TABLE "GALADM  "."GTS_DECISION_POINT_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "DP_ID" SMALLINT NOT NULL , 
		  "DECISION_POINT_NAME" VARCHAR(10 OCTETS) , 
		  "DECISION_POINT_DESCRIPTION" VARCHAR(40 OCTETS) , 
		  "RULE_CLASS" VARCHAR(100 OCTETS) , 
		  "ENABLED" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "TIME_INTERVAL" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_DECISION_POINT_TBX" IS 'GTS Decision Point';

COMMENT ON COLUMN "GALADM  "."GTS_DECISION_POINT_TBX"."ENABLED" IS 'Flag to indicate if the control is currently in use';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_DECISION_POINT_TBX"

ALTER TABLE "GALADM  "."GTS_DECISION_POINT_TBX" 
	ADD CONSTRAINT "GTS_DECISION_POINT_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "DP_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_DECISION_POINT_TBX"

ALTER TABLE "GALADM  "."GTS_DECISION_POINT_TBX" 
	ADD CONSTRAINT "AREA_DECISION_POINT_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_DECISION_POINT_TR1";

CREATE TRIGGER GALADM.GTS_DECISION_POINT_TR1 NO CASCADE BEFORE INSERT ON
GALADM.GTS_DECISION_POINT_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_DECISION_POINT_TR2";

CREATE TRIGGER GALADM.GTS_DECISION_POINT_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.GTS_DECISION_POINT_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


