
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_LANE_TBX";


CREATE TABLE "GALADM  "."GTS_LANE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "LANE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "LANE_DESCRIPTION" VARCHAR(40 OCTETS) , 
		  "LANE_CAPACITY" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LANE_TYPE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "ENTRY_GATE_ID" SMALLINT , 
		  "EXIT_GATE_ID" SMALLINT , 
		  "CARRIER_PRESENT" SMALLINT , 
		  "IS_PHYSICALLY_FULL" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_TBX" IS 'GTS Lane';

COMMENT ON COLUMN "GALADM  "."GTS_LANE_TBX"."LANE_TYPE" IS 'Normal,Entry,Exit';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_TBX" 
	ADD CONSTRAINT "GTS_LANE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_TBX" 
	ADD CONSTRAINT "AREA_TO_LANE_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_TR1";

CREATE TRIGGER GALADM.GTS_LANE_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_LANE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_TR2";

CREATE TRIGGER GALADM.GTS_LANE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_LANE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


