
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_OUTLINE_IMAGE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX";


CREATE TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX"  (
		  "IMAGE_ID" SMALLINT NOT NULL , 
		  "OUTLINE_IMAGE_DESCRIPTION" VARCHAR(40 OCTETS) , 
		  "IMAGE" BLOB(12768) LOGGED NOT COMPACT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX" IS 'GTS Outline Image';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_OUTLINE_IMAGE_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX" 
	ADD CONSTRAINT "GTS_OUTLINE_IMAGE_PK" PRIMARY KEY
		("IMAGE_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_OUTLINE_IMAGE_TR1";

CREATE TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR1 NO CASCADE BEFORE INSERT ON
GALADM.GTS_OUTLINE_IMAGE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_OUTLINE_IMAGE_TR2";

CREATE TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.GTS_OUTLINE_IMAGE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


