
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_AREA_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_AREA_TBX";


CREATE TABLE "GALADM  "."GTS_AREA_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "AREA_DESCRIPTION" VARCHAR(40 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(40 OCTETS) , 
		  "TAG_TYPE" SMALLINT , 
		  "IS_ENABLED" SMALLINT , 
		  "TRACKING_MODE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_AREA_TBX" IS 'GTS Area';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."PRODUCT_TYPE" IS 'Engine or Vehicle or ...';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."TAG_TYPE" IS 'TAG_TYPE - SMART EYE | RF TAG ....     NONE - NO Tag (In this case no carrier product association)     SMART_EYE     RF_TAG';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."TRACKING_MODE" IS 'production mode, maintenance mode. when in maintenance mode, the configuration (layout, bitmap etc) can be changed. When in production mode, configuration is not allowed to be changed ';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_AREA_TBX"

ALTER TABLE "GALADM  "."GTS_AREA_TBX" 
	ADD CONSTRAINT "GTS_AREA_PK" PRIMARY KEY
		("TRACKING_AREA");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_AREA_TR1";

CREATE TRIGGER GALADM.GTS_AREA_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_AREA_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_AREA_TR2";

CREATE TRIGGER GALADM.GTS_AREA_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_AREA_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


