
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_PRODUCT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_PRODUCT_TBX";


CREATE TABLE "GALADM  "."GTS_PRODUCT_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "PRODUCT_ID" VARCHAR(40 OCTETS) NOT NULL , 
		  "SHORT_PROD_ID" VARCHAR(20 OCTETS) , 
		  "LOT_NUMBER" VARCHAR(20 OCTETS) , 
		  "KD_LOT_NUMBER" VARCHAR(18 OCTETS) , 
		  "MODEL_YEAR" CHAR(1 OCTETS) , 
		  "MODEL_CODE" VARCHAR(5 OCTETS) , 
		  "MODEL_TYPE" VARCHAR(5 OCTETS) , 
		  "MODEL_OPTION" VARCHAR(5 OCTETS) , 
		  "INT_COLOR_CODE" VARCHAR(5 OCTETS) , 
		  "EXT_COLOR_CODE" VARCHAR(10 OCTETS) , 
		  "HOLD_STATUS" SMALLINT WITH DEFAULT 0 , 
		  "DEFECT_STATUS" SMALLINT , 
		  "INSPECTION_STATUS" SMALLINT WITH DEFAULT 0 , 
		  "PRODUCT_SEQ" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT5" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_PRODUCT_TBX" IS 'RMT GtsProduct';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_PRODUCT_TBX"

ALTER TABLE "GALADM  "."GTS_PRODUCT_TBX" 
	ADD CONSTRAINT "GTS_PRODUCT_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."GTS_PRODUCT_TBX_TR1";

CREATE TRIGGER GALADM.GTS_PRODUCT_TBX_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."GTS_PRODUCT_TBX_TR2";

CREATE TRIGGER GALADM.GTS_PRODUCT_TBX_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


