
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_MOVE_CONDITION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX";


CREATE TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "SOURCE_LANE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "DESTINATION_LANE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "INDICATOR_ID" VARCHAR(30 OCTETS) NOT NULL , 
		  "REQUIRED_VALUE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" IS 'GTS Move Condition';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_MOVE_CONDITION_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "GTS_MOVE_CONDITION_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID",
		 "INDICATOR_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_MOVE_CONDITION_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "MV_CONDITION_INDICATOR_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "INDICATOR_ID")
	REFERENCES "GALADM  "."GTS_INDICATOR_TBX"
		("TRACKING_AREA",
		 "INDICATOR_NAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "MV_CONDITION_TO_MOVE_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID")
	REFERENCES "GALADM  "."GTS_MOVE_TBX"
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_MOVE_CONDITION_TR1";

CREATE TRIGGER GALADM.GTS_MOVE_CONDITION_TR1 NO CASCADE BEFORE INSERT ON
GALADM.GTS_MOVE_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_MOVE_CONDITION_TR2";

CREATE TRIGGER GALADM.GTS_MOVE_CONDITION_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.GTS_MOVE_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


