
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LABEL_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_LABEL_TBX";


CREATE TABLE "GALADM  "."GTS_LABEL_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "LABEL_ID" INTEGER NOT NULL , 
		  "LABEL_TEXT" VARCHAR(40 OCTETS) , 
		  "LABEL_FONT" VARCHAR(40 OCTETS) , 
		  "BORDER_TYPE" SMALLINT , 
		  "BORDER_COLOR" VARCHAR(8 OCTETS) , 
		  "TEXT_COLOR" VARCHAR(8 OCTETS) , 
		  "BACK_COLOR" VARCHAR(8 OCTETS) , 
		  "X" SMALLINT , 
		  "Y" SMALLINT , 
		  "X_EXTENT" SMALLINT , 
		  "Y_EXTENT" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_LABEL_TBX" IS 'GTS Label';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LABEL_TBX"

ALTER TABLE "GALADM  "."GTS_LABEL_TBX" 
	ADD CONSTRAINT "GTS_LABEL_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LABEL_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LABEL_TBX"

ALTER TABLE "GALADM  "."GTS_LABEL_TBX" 
	ADD CONSTRAINT "LABEL_TO_AREA_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LABEL_TR1";

CREATE TRIGGER GALADM.GTS_LABEL_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_LABEL_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LABEL_TR2";

CREATE TRIGGER GALADM.GTS_LABEL_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_LABEL_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


