
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX";


CREATE TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "LANE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "LANE_SEQ" SMALLINT NOT NULL , 
		  "LANE_SEGMENT_ID" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" IS 'GTS Lane Segment Map';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "GTS_LANE_SEGMENT_MAP_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID",
		 "LANE_SEQ");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "LANE_SEGMENT_LANE_SEGMENT_MAP_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID")
	REFERENCES "GALADM  "."GTS_LANE_SEGMENT_TBX"
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "LANE_TO_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_ID")
	REFERENCES "GALADM  "."GTS_LANE_TBX"
		("TRACKING_AREA",
		 "LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_SEGMENT_MAP_TR1";

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR1 NO CASCADE BEFORE INSERT
ON GALADM.GTS_LANE_SEGMENT_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_SEGMENT_MAP_TR2";

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.GTS_LANE_SEGMENT_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


