
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_SHAPE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_SHAPE_TBX";


CREATE TABLE "GALADM  "."GTS_SHAPE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "SHAPE_ID" SMALLINT NOT NULL , 
		  "SHAPE_TYPE" SMALLINT , 
		  "SHAPE_STYLE" SMALLINT , 
		  "LINE_WIDTH" DOUBLE , 
		  "LINE_STYLE" SMALLINT , 
		  "LINE_COLOR" VARCHAR(8 OCTETS) NOT NULL , 
		  "FILL_COLOR" VARCHAR(8 OCTETS) NOT NULL , 
		  "X" SMALLINT , 
		  "Y" SMALLINT , 
		  "X_EXTENT" SMALLINT , 
		  "Y_EXTENT" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_SHAPE_TBX" IS 'GTS Shape';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_SHAPE_TBX"

ALTER TABLE "GALADM  "."GTS_SHAPE_TBX" 
	ADD CONSTRAINT "GTS_SHAPE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "SHAPE_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_SHAPE_TBX"

ALTER TABLE "GALADM  "."GTS_SHAPE_TBX" 
	ADD CONSTRAINT "SHAPE_TO_AREA_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_SHAPE_TR1";

CREATE TRIGGER GALADM.GTS_SHAPE_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_SHAPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_SHAPE_TR2";

CREATE TRIGGER GALADM.GTS_SHAPE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_SHAPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


