
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_CARRIER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_CARRIER_TBX";


CREATE TABLE "GALADM  "."GTS_CARRIER_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "CARRIER_NUMBER" VARCHAR(40 OCTETS) NOT NULL , 
		  "PRODUCT_ID" VARCHAR(40 OCTETS) , 
		  "CARRIER_TYPE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_CARRIER_TBX" IS 'GTS Carrier';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_CARRIER_TBX" 
	ADD CONSTRAINT "GTS_CARRIER_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "CARRIER_NUMBER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_CARRIER_TR1";

CREATE TRIGGER GALADM.GTS_CARRIER_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_CARRIER_TR2";

CREATE TRIGGER GALADM.GTS_CARRIER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


