
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_CARRIER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_LANE_CARRIER_TBX";


CREATE TABLE "GALADM  "."GTS_LANE_CARRIER_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "LANE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "LANE_POSITION" TIMESTAMP NOT NULL , 
		  "LANE_CARRIER" VARCHAR(40 OCTETS) , 
		  "DISCREPANCY_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" IS 'GTS Lane Carrier';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" 
	ADD CONSTRAINT "GTS_LANE_CARRIER_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID",
		 "LANE_POSITION");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" 
	ADD CONSTRAINT "LANE_TO_CARRIER_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_CARRIER")
	REFERENCES "GALADM  "."GTS_CARRIER_TBX"
		("TRACKING_AREA",
		 "CARRIER_NUMBER")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_CARRIER_TR1";

CREATE TRIGGER GALADM.GTS_LANE_CARRIER_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_LANE_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_LANE_CARRIER_TR2";

CREATE TRIGGER GALADM.GTS_LANE_CARRIER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_LANE_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


