
------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_OUTLINE_MAP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX";


CREATE TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX"  (
		  "TRACKING_AREA" VARCHAR(10 OCTETS) NOT NULL , 
		  "OUTLINE_MAP_ID" SMALLINT NOT NULL , 
		  "MODEL_CODE" VARCHAR(5 OCTETS) NOT NULL , 
		  "IMAGE" BLOB(12768) LOGGED NOT COMPACT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" IS 'GTS Outline Map';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_OUTLINE_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" 
	ADD CONSTRAINT "GTS_OUTLINE_MAP_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "OUTLINE_MAP_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_OUTLINE_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" 
	ADD CONSTRAINT "AREA_OUTLINE_MAP_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_OUTLINE_MAP_TR1";

CREATE TRIGGER GALADM.GTS_OUTLINE_MAP_TR1 NO CASCADE BEFORE INSERT ON GALADM.GTS_OUTLINE_MAP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."GTS_OUTLINE_MAP_TR2";

CREATE TRIGGER GALADM.GTS_OUTLINE_MAP_TR2 NO CASCADE BEFORE UPDATE ON GALADM.GTS_OUTLINE_MAP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


