
------------------------------------------------
-- DDL Statements for Table "GALADM  "."HEAD_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."HEAD_TBX";


CREATE TABLE "GALADM  "."HEAD_TBX"  (
		  "HEAD_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "MC_SERIAL_NUMBER" VARCHAR(17 OCTETS) , 
		  "DC_SERIAL_NUMBER" VARCHAR(17 OCTETS) , 
		  "ENGINE_SERIAL_NUMBER" VARCHAR(17 OCTETS) , 
		  "MODEL" VARCHAR(12 OCTETS) , 
		  "TRACKING_STATUS" VARCHAR(16 OCTETS) , 
		  "DUNNAGE" VARCHAR(20 OCTETS) , 
		  "DEFECT_STATUS" SMALLINT , 
		  "HOLD_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "ENGINE_FIRING_FLAG" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."HEAD_TBX" IS 'RMT Head';


-- DDL Statements for Primary Key on Table "GALADM  "."HEAD_TBX"

ALTER TABLE "GALADM  "."HEAD_TBX" 
	ADD CONSTRAINT "HEAD_PK" PRIMARY KEY
		("HEAD_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HEAD_TR1";

CREATE TRIGGER GALADM.HEAD_TR1 NO CASCADE BEFORE INSERT ON GALADM.HEAD_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HEAD_TR2";

CREATE TRIGGER GALADM.HEAD_TR2 NO CASCADE BEFORE UPDATE ON GALADM.HEAD_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


