
------------------------------------------------
-- DDL Statements for Table "GALADM  "."HEAD_HISTORY_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."HEAD_HISTORY_TBX";


CREATE TABLE "GALADM  "."HEAD_HISTORY_TBX"  (
		  "HEAD_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_COUNT" INTEGER NOT NULL WITH DEFAULT 1 , 
		  "DEVICE_ID" VARCHAR(32 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."HEAD_HISTORY_TBX" IS 'RMT HeadHistory';


-- DDL Statements for Primary Key on Table "GALADM  "."HEAD_HISTORY_TBX"

ALTER TABLE "GALADM  "."HEAD_HISTORY_TBX" 
	ADD CONSTRAINT "HEAD_HIST_PK" PRIMARY KEY
		("HEAD_ID",
		 "PROCESS_POINT_ID",
		 "ACTUAL_TIMESTAMP");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HEAD_HISTORY_TR1";

CREATE TRIGGER GALADM.HEAD_HISTORY_TR1 NO CASCADE BEFORE INSERT ON GALADM.HEAD_HISTORY_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HEAD_HISTORY_TR2";

CREATE TRIGGER GALADM.HEAD_HISTORY_TR2 NO CASCADE BEFORE UPDATE ON GALADM.HEAD_HISTORY_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.HEAD_HISTORY_I1 ON GALADM.HEAD_HISTORY_TBX
(
   "ACTUAL_TIMESTAMP" ASC
)
ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS
;


