
------------------------------------------------
-- DDL Statements for Table "GALADM  "."HOLD_PARM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."HOLD_PARM_TBX";


CREATE TABLE "GALADM  "."HOLD_PARM_TBX"  (
		  "HOLD_ID" BIGINT NOT NULL , 
		  "DEPARTMENT" VARCHAR(16 OCTETS) NOT NULL , 
		  "MACHINE_NUMBER" VARCHAR(50 OCTETS) NOT NULL , 
		  "DIE_NUMBER" VARCHAR(80 OCTETS) , 
		  "START_DATE" DATE NOT NULL , 
		  "STOP_DATE" DATE NOT NULL , 
		  "HOLD_REASON" VARCHAR(80 OCTETS) NOT NULL , 
		  "HOLD_ASSOCIATE_ID" VARCHAR(11 OCTETS) NOT NULL , 
		  "HOLD_ASSOCIATE_NAME" VARCHAR(30 OCTETS) NOT NULL , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "RELEASE_FLAG" SMALLINT NOT NULL , 
		  "RELEASE_ASSOCIATE_ID" VARCHAR(11 OCTETS) , 
		  "RELEASE_ASSOCIATE_NAME" VARCHAR(30 OCTETS) , 
		  "RELEASE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "QSR_ID" INTEGER , 
		  "MODEL_CODE" VARCHAR(3 OCTETS) , 
		  "CORE_NUMBER" VARCHAR(80 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."HOLD_PARM_TBX" IS 'RMT HoldParm';


-- DDL Statements for Primary Key on Table "GALADM  "."HOLD_PARM_TBX"

ALTER TABLE "GALADM  "."HOLD_PARM_TBX" 
	ADD CONSTRAINT "HOLD_PARM_PK" PRIMARY KEY
		("HOLD_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HOLD_PARM_TR1";

CREATE TRIGGER GALADM.HOLD_PARM_TR1 NO CASCADE BEFORE INSERT ON GALADM.HOLD_PARM_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."HOLD_PARM_TR2";

CREATE TRIGGER GALADM.HOLD_PARM_TR2 NO CASCADE BEFORE UPDATE ON GALADM.HOLD_PARM_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


