
------------------------------------------------
-- DDL Statements for Table "GALADM  "."HOLD_REASON_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."HOLD_REASON_TBX";


CREATE TABLE "GALADM  "."HOLD_REASON_TBX"  (
		  "REASON_ID" INTEGER NOT NULL , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL , 
		  "HOLD_REASON" VARCHAR(80 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."HOLD_REASON_TBX" IS 'RMT HoldReason';


-- DDL Statements for Primary Key on Table "GALADM  "."HOLD_REASON_TBX"

ALTER TABLE "GALADM  "."HOLD_REASON_TBX" 
	ADD CONSTRAINT "HOLD_REASON_PK" PRIMARY KEY
		("REASON_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HOLD_REASON_TR1";

CREATE TRIGGER GALADM.HOLD_REASON_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HOLD_REASON_TR2";

CREATE TRIGGER GALADM.HOLD_REASON_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


