
------------------------------------------------
-- DDL Statements for Table "GALADM  "."HOLD_REASON_MAPPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."HOLD_REASON_MAPPING_TBX";


CREATE TABLE "GALADM  "."HOLD_REASON_MAPPING_TBX"  (
		  "REASON_MAPPING_ID" INTEGER NOT NULL , 
		  "REASON_ID" INTEGER NOT NULL , 
		  "QC_ACTION_ID" INTEGER NOT NULL , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL , 
		  "LINE_ID" CHAR(16 OCTETS) NOT NULL , 
		  "ASSOCIATE_ID" VARCHAR(11 OCTETS) NOT NULL , 
		  "ASSOCIATE_NAME" VARCHAR(30 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."HOLD_REASON_MAPPING_TBX" IS 'RMT HoldReasonMap';


-- DDL Statements for Primary Key on Table "GALADM  "."HOLD_REASON_MAPPING_TBX"

ALTER TABLE "GALADM  "."HOLD_REASON_MAPPING_TBX" 
	ADD CONSTRAINT "HOLD_REASON_MAPPING_PK" PRIMARY KEY
		("REASON_MAPPING_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HOLD_REASON_MAPPING_TR1";

CREATE TRIGGER GALADM.HOLD_REASON_MAPPING_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_REASON_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HOLD_REASON_MAPPING_TR2";

CREATE TRIGGER GALADM.HOLD_REASON_MAPPING_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_REASON_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


