
------------------------------------------------
-- DDL Statements for Table "GALADM  "."INVOICE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."INVOICE_TBX";


CREATE TABLE "GALADM  "."INVOICE_TBX"  (
		  "INVOICE_NO" DECIMAL(10,0) NOT NULL , 
		  "INVOICE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "BATCH_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "BATCH_SEQUENCE" INTEGER NOT NULL , 
		  "PROC_DATE" DATE , 
		  "NUM_SUMMARY_REC" INTEGER NOT NULL , 
		  "NUM_DTL_REC" INTEGER NOT NULL , 
		  "TRANCE_CODE" CHAR(3 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."INVOICE_TBX" IS 'OIF Invoice';


-- DDL Statements for Primary Key on Table "GALADM  "."INVOICE_TBX"

ALTER TABLE "GALADM  "."INVOICE_TBX" 
	ADD CONSTRAINT "INVOICE_PK" PRIMARY KEY
		("INVOICE_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_TR1";

CREATE TRIGGER GALADM.INVOICE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_TR2";

CREATE TRIGGER GALADM.INVOICE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.INVOICE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


