
------------------------------------------------
-- DDL Statements for Table "GALADM  "."INVOICE_SUMMARY_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."INVOICE_SUMMARY_TBX";


CREATE TABLE "GALADM  "."INVOICE_SUMMARY_TBX"  (
		  "INVOICE_NO" DECIMAL(10,0) NOT NULL , 
		  "SUM_PRICE" DECIMAL(14,2) NOT NULL , 
		  "SUM_TOTAL_QUANTITY" INTEGER NOT NULL , 
		  "QUOTATION_NO" CHAR(20 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "SUM_SHIPMENT_NO" CHAR(3 OCTETS) WITH DEFAULT ' ' , 
		  "SUM_INVOICE_DATE" DATE , 
		  "SHIP_DATE" DATE , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."INVOICE_SUMMARY_TBX" IS 'OIF Invoice(Summary Record)';


-- DDL Statements for Primary Key on Table "GALADM  "."INVOICE_SUMMARY_TBX"

ALTER TABLE "GALADM  "."INVOICE_SUMMARY_TBX" 
	ADD CONSTRAINT "INVOICE_SUMMARY_PK" PRIMARY KEY
		("INVOICE_NO",
		 "QUOTATION_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_SUMMARY_TR1";

CREATE TRIGGER GALADM.INVOICE_SUMMARY_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_SUMMARY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_SUMMARY_TR2";

CREATE TRIGGER GALADM.INVOICE_SUMMARY_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.INVOICE_SUMMARY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


