
------------------------------------------------
-- DDL Statements for Table "GALADM  "."INVOICE_DETAIL_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."INVOICE_DETAIL_TBX";


CREATE TABLE "GALADM  "."INVOICE_DETAIL_TBX"  (
		  "PRODUCT_ID" CHAR(64 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INSPECTION_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "SHIPPING_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "PRICE" DECIMAL(11,2) NOT NULL , 
		  "QUOTATION_NO" CHAR(20 OCTETS) WITH DEFAULT ' ' , 
		  "PRICE_TYPE" CHAR(1 OCTETS) WITH DEFAULT ' ' , 
		  "INVOICE_NO" DECIMAL(10,0) NOT NULL , 
		  "AHM_INVOICE_NO" CHAR(10 OCTETS) WITH DEFAULT ' ' , 
		  "CORRECTION_FLAG" CHAR(1 OCTETS) WITH DEFAULT 'I' , 
		  "RECEIPT_TIMESTAMP" CHAR(19 OCTETS) WITH DEFAULT '0' , 
		  "VALIDATION_DATE" CHAR(10 OCTETS) WITH DEFAULT '0' , 
		  "FINAL_DATE" CHAR(10 OCTETS) WITH DEFAULT '0' , 
		  "FINAL_RECEIPT_FLG" CHAR(1 OCTETS) WITH DEFAULT 'F' , 
		  "FACTORY_SHIPMENT_NO" CHAR(3 OCTETS) WITH DEFAULT ' ' , 
		  "ERROR_CODE" CHAR(4 OCTETS) WITH DEFAULT ' ' , 
		  "DTL_ROW_NO" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."INVOICE_DETAIL_TBX" IS 'OIF Invoice(Detail Record)';


-- DDL Statements for Primary Key on Table "GALADM  "."INVOICE_DETAIL_TBX"

ALTER TABLE "GALADM  "."INVOICE_DETAIL_TBX" 
	ADD CONSTRAINT "INVOICE_DETAIL_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "INVOICE_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_DETAIL_TR1";

CREATE TRIGGER GALADM.INVOICE_DETAIL_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."INVOICE_DETAIL_TR2";

CREATE TRIGGER GALADM.INVOICE_DETAIL_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.INVOICE_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


