------------------------------------------------
-- DDL Statements for Table "GALADM  "."KICKOUT_LOCATION_TBX"
------------------------------------------------

DROP TABLE "GALADM  "."KICKOUT_LOCATION_TBX";


CREATE TABLE "GALADM  "."KICKOUT_LOCATION_TBX"  (
                  "KICKOUT_ID" BIGINT NOT NULL ,
                  "DIVISION_ID" VARCHAR(16) NOT NULL ,
                  "LINE_ID" VARCHAR(16) NOT NULL  ,
                  "PROCESS_POINT_ID" VARCHAR(16) NOT NULL  ,
                  "UPDATE_TIMESTAMP" TIMESTAMP ,
                  "CREATE_TIMESTAMP" TIMESTAMP)
                 DATA CAPTURE CHANGES
                 IN "GALTBSREF12" INDEX IN "GALTBSIDX4";


-- DDL Statements for Primary Key on Table "GALADM  "."KICKOUT_LOCATION_TBX"

ALTER TABLE "GALADM  "."KICKOUT_LOCATION_TBX"
        ADD CONSTRAINT "KICKOUT_LOCATION_PK" PRIMARY KEY
                ("KICKOUT_ID");


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."KICKOUT_LOCATION_TR1";

CREATE TRIGGER GALADM.KICKOUT_LOCATION_TR1 NO CASCADE BEFORE INSERT ON GALADM.KICKOUT_LOCATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."KICKOUT_LOCATION_TR2";

CREATE TRIGGER GALADM.KICKOUT_LOCATION_TR2 NO CASCADE BEFORE UPDATE ON GALADM.KICKOUT_LOCATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
