
------------------------------------------------
-- DDL Statements for Table "GALADM  "."LAYER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."LAYER_TBX";


CREATE TABLE "GALADM  "."LAYER_TBX"  (
		  "LAYER_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "LAYER_TYPE" VARCHAR(32 OCTETS) NOT NULL , 
		  "LAYER_DAO" VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DEFAULT_ZOOM" INTEGER , 
		  "BOUNDARY_LEFT" DOUBLE , 
		  "BOUNDARY_LOWER" DOUBLE , 
		  "BOUNDARY_RIGHT" DOUBLE , 
		  "BOUNDARY_UPPER" DOUBLE )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."LAYER_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."LAYER_TBX" IS 'RMT Layer to describe how to display visual information';


-- DDL Statements for Primary Key on Table "GALADM  "."LAYER_TBX"

ALTER TABLE "GALADM  "."LAYER_TBX" 
	ADD CONSTRAINT "LAYER_PK" PRIMARY KEY
		("LAYER_ID",
		 "LAYER_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LAYER_TR1";

CREATE TRIGGER GALADM.LAYER_TR1 NO CASCADE BEFORE INSERT ON GALADM.LAYER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LAYER_TR2";

CREATE TRIGGER GALADM.LAYER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.LAYER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


