
------------------------------------------------
-- DDL Statements for Table "GALADM  "."LAYER_FEATURES_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."LAYER_FEATURES_TBX";


CREATE TABLE "GALADM  "."LAYER_FEATURES_TBX"  (
		  "LAYER_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "VISIBLE" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."LAYER_FEATURES_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."LAYER_FEATURES_TBX" IS 'RMT LayerFeatures used to relate Layers to Features';


-- DDL Statements for Primary Key on Table "GALADM  "."LAYER_FEATURES_TBX"

ALTER TABLE "GALADM  "."LAYER_FEATURES_TBX" 
	ADD CONSTRAINT "LAYER_FEATURES_PK" PRIMARY KEY
		("LAYER_ID",
		 "FEATURE_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LAYER_FEATURES_TR1";

CREATE TRIGGER GALADM.LAYER_FEATURES_TR1 NO CASCADE BEFORE INSERT ON GALADM.LAYER_FEATURES_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LAYER_FEATURES_TR2";

CREATE TRIGGER GALADM.LAYER_FEATURES_TR2 NO CASCADE BEFORE UPDATE ON GALADM.LAYER_FEATURES_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


