
------------------------------------------------
-- DDL Statements for Table "GALADM  "."LET_CONNECTED_PROGRAM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."LET_CONNECTED_PROGRAM_TBX";


CREATE TABLE "GALADM  "."LET_CONNECTED_PROGRAM_TBX"  (
		  "CRITERIA_PGM_ID" INTEGER NOT NULL , 
		  "TRIGGERING_PGM_ID" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."LET_CONNECTED_PROGRAM_TBX"

ALTER TABLE "GALADM  "."LET_CONNECTED_PROGRAM_TBX" 
	ADD CONSTRAINT "LET_CONNECTED_PROGRAM_PK" PRIMARY KEY
		("CRITERIA_PGM_ID",
		 "TRIGGERING_PGM_ID");



-- DDL Statements for Foreign Keys on Table "GALADM  "."LET_CONNECTED_PROGRAM_TBX"

ALTER TABLE "GALADM  "."LET_CONNECTED_PROGRAM_TBX" 
	ADD CONSTRAINT "LET_CONNECTED_PROGRAM_FK1" FOREIGN KEY
		("CRITERIA_PGM_ID")
	REFERENCES "GALADM  "."GAL718TBX"
		("CRITERIA_PGM_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."LET_CONNECTED_PROGRAM_TBX" 
	ADD CONSTRAINT "LET_CONNECTED_PROGRAM_FK2" FOREIGN KEY
		("TRIGGERING_PGM_ID")
	REFERENCES "GALADM  "."GAL714TBX"
		("INSPECTION_PGM_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_CONNECTED_PROGRAM_TR1";

CREATE TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.LET_CONNECTED_PROGRAM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_CONNECTED_PROGRAM_TR2";

CREATE TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.LET_CONNECTED_PROGRAM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


