
------------------------------------------------
-- DDL Statements for Table "GALADM  "."LET_SPOOL_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."LET_SPOOL_TBX";


CREATE TABLE "GALADM  "."LET_SPOOL_TBX"  (
		  "SPOOL_ID" INTEGER NOT NULL , 
		  "ENV_NAME" VARCHAR(16 OCTETS) NOT NULL , 
		  "LINE_NAME" VARCHAR(16 OCTETS) NOT NULL , 
		  "PORT_NUMBER" INTEGER NOT NULL , 
		  "XML_SAVE_LOCATION" VARCHAR(128 OCTETS) , 
		  "EXCEPTION_SAVE_LOCATION" VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."LET_SPOOL_TBX"

ALTER TABLE "GALADM  "."LET_SPOOL_TBX" 
	ADD CONSTRAINT "LET_SPOOL_PK" PRIMARY KEY
		("SPOOL_ID");



-- DDL Statements for Indexes on Table "GALADM  "."LET_SPOOL_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."LET_SPOOL_I1" ON "GALADM  "."LET_SPOOL_TBX" 
		("ENV_NAME" ASC,
		 "LINE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_SPOOL_TR1";

CREATE TRIGGER "GALADM"."LET_SPOOL_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."LET_SPOOL_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_SPOOL_TR2";

CREATE TRIGGER "GALADM"."LET_SPOOL_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."LET_SPOOL_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


