
------------------------------------------------
-- DDL Statements for Table "GALADM  "."LET_PART_CHECK_SPEC_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."LET_PART_CHECK_SPEC_TBX";


CREATE TABLE "GALADM  "."LET_PART_CHECK_SPEC_TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "INSPECTION_PROGRAM_ID" INTEGER NOT NULL , 
		  "INSPECTION_PARAM_ID" INTEGER NOT NULL , 
		  "SEQUENCE_NUMBER" INTEGER NOT NULL , 
		  "PARAM_TYPE" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."LET_PART_CHECK_SPEC_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."LET_PART_CHECK_SPEC_TBX" IS 'RMT table for rules checked by LET';


-- DDL Statements for Primary Key on Table "GALADM  "."LET_PART_CHECK_SPEC_TBX"

ALTER TABLE "GALADM  "."LET_PART_CHECK_SPEC_TBX" 
	ADD CONSTRAINT "LET_PART_CHECK_SPEC_PK" PRIMARY KEY
		("PART_NAME",
		 "PART_ID",
		 "INSPECTION_PROGRAM_ID",
		 "INSPECTION_PARAM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_PART_CHECK_SPEC_TR1";

CREATE TRIGGER GALADM.LET_PART_CHECK_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LET_PART_CHECK_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."LET_PART_CHECK_SPEC_TR2";

CREATE TRIGGER GALADM.LET_PART_CHECK_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LET_PART_CHECK_SPEC_TBX
   REFERENCING NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


