------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."LET_PARTIAL_CHECK"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."LET_PARTIAL_CHECK";


CREATE TABLE "LCVINBOM  "."LET_PARTIAL_CHECK"  (
		  "CATEGORY_CODE_ID" BIGINT NOT NULL , 
		  "LET_INSPECTION_NAME" VARCHAR(255 OCTETS) NOT NULL , 		   
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."LET_PARTIAL_CHECK" IS 'VIN-BOM LET Systems for Partial Check';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."LET_PARTIAL_CHECK"

ALTER TABLE "LCVINBOM  "."LET_PARTIAL_CHECK" 
	ADD CONSTRAINT "LET_PARTIAL_CHECK_PK" PRIMARY KEY
		("CATEGORY_CODE_ID","LET_INSPECTION_NAME");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_PARTIAL_CHECK_TR1";

CREATE TRIGGER LCVINBOM.LET_PARTIAL_CHECK_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.LET_PARTIAL_CHECK
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_PARTIAL_CHECK_TR2";

CREATE TRIGGER LCVINBOM.LET_PARTIAL_CHECK_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.LET_PARTIAL_CHECK
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;