------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."LOT_PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."LOT_PART";


CREATE TABLE "LCVINBOM  "."LOT_PART"  (
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "ACTIVE" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."LOT_PART" IS 'VIN-BOM Part Number Assignment for LET System and Production Lot';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."LOT_PART"

ALTER TABLE "LCVINBOM  "."LOT_PART" 
	ADD CONSTRAINT "LOT_PART_PK" PRIMARY KEY
		("PRODUCTION_LOT","LET_SYSTEM_NAME","DC_PART_NUMBER");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LOT_PART_TR1";

CREATE TRIGGER LCVINBOM.LOT_PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.LOT_PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LOT_PART_TR2";

CREATE TRIGGER LCVINBOM.LOT_PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.LOT_PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;