
------------------------------------------------
-- DDL Statements for Table "VIOS    "."MANPOWER_ASSIGNMENT"
------------------------------------------------
 
DROP TABLE "VIOS    "."MANPOWER_ASSIGNMENT";


CREATE TABLE "VIOS    "."MANPOWER_ASSIGNMENT"  (
		  "MANPOWER_ASSIGNMENT_ID" BIGINT NOT NULL , 
		  "QUARTER" SMALLINT NOT NULL , 
		  "PAIR_TYPE" SMALLINT NOT NULL , 
		  "ERGO_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "REASON_CODE" SMALLINT NOT NULL , 
		  "DAYS_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "LAST_UPDATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "ROTATION_ID" INTEGER NOT NULL , 
		  "TEAM_ID" INTEGER , 
		  "MANPOWER_TAG_ID" INTEGER NOT NULL , 
		  "PROCESS_GROUP_ID" INTEGER , 
		  "PC_AREA_ID" INTEGER , 
		  "ASSOCIATE_ID" CHAR(7 OCTETS) , 
		  "ADDITIONAL_ASSOCIATE_ID" CHAR(7 OCTETS) , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."MANPOWER_ASSIGNMENT"

ALTER TABLE "VIOS    "."MANPOWER_ASSIGNMENT" 
	ADD CONSTRAINT "MANPOWER_ASSIGNMENT_PK" PRIMARY KEY
		("MANPOWER_ASSIGNMENT_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."MANPOWER_ASSIGNMENT_TR1";

CREATE TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR1 NO CASCADE BEFORE INSERT ON
VIOS.MANPOWER_ASSIGNMENT REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."MANPOWER_ASSIGNMENT_TR2";

CREATE TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR2 NO CASCADE BEFORE UPDATE ON
VIOS.MANPOWER_ASSIGNMENT REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


