
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MASS_MESSAGE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MASS_MESSAGE_TBX";


CREATE TABLE "GALADM  "."MASS_MESSAGE_TBX"  (
		  "PLANT_NAME" CHAR(16 OCTETS) NOT NULL , 
		  "DEPARTMENT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "LINE_ID" CHAR(16 OCTETS) NOT NULL , 
		  "MASS_MESSAGE_TYPE" SMALLINT NOT NULL , 
		  "MASS_MESSAGE" VARCHAR(255 OCTETS) NOT NULL , 
		  "MASS_MESSAGE_SEVERITY" VARCHAR(25 OCTETS) NOT NULL , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."MASS_MESSAGE_TBX"

ALTER TABLE "GALADM  "."MASS_MESSAGE_TBX" 
	ADD CONSTRAINT "MASS_MESSAGE_PK" PRIMARY KEY
		("PLANT_NAME",
		 "DEPARTMENT_ID",
		 "LINE_ID",
		 "MASS_MESSAGE_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MASS_MESSAGE_TR1";

CREATE TRIGGER GALADM.MASS_MESSAGE_TR1 NO CASCADE BEFORE INSERT ON GALADM.MASS_MESSAGE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MASS_MESSAGE_TR2";

CREATE TRIGGER GALADM.MASS_MESSAGE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MASS_MESSAGE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


