
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MBPN_PRODUCT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MBPN_PRODUCT_TBX";


CREATE TABLE "GALADM  "."MBPN_PRODUCT_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "CURRENT_PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "CURRENT_ORDER_NO" CHAR(20 OCTETS) , 
		  "TRACKING_STATUS" CHAR(16 OCTETS) , 
		  "LAST_PASSING_PROCESS_POINT" CHAR(16 OCTETS) , 
		  "TRACKING_SEQ" DOUBLE , 
		  "HOLD_STATUS_ID" INTEGER , 
		  "PRODUCT_STATUS_ID" INTEGER , 
		  "CONTAINER_ID" CHAR(17 OCTETS) , 
		  "CONTAINER_POS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DEFECT_STATUS" SMALLINT , 
		  "EXTERNAL_BUILD" INTEGER NOT NULL WITH DEFAULT 0 )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MBPN_PRODUCT_TBX" IS 'RMT MbpnProduct for tracking product id of type Manufacturing Base Part Number';

COMMENT ON COLUMN "GALADM  "."MBPN_PRODUCT_TBX"."HOLD_STATUS_ID" IS 'Link to HOLD_STATUS_TBX';

COMMENT ON COLUMN "GALADM  "."MBPN_PRODUCT_TBX"."PRODUCT_STATUS_ID" IS 'Link to PRODUCT_STATUS_TBX';


-- DDL Statements for Primary Key on Table "GALADM  "."MBPN_PRODUCT_TBX"

ALTER TABLE "GALADM  "."MBPN_PRODUCT_TBX" 
	ADD CONSTRAINT "MBPN_PRODUCT_PK" PRIMARY KEY
		("PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MBPN_PRODUCT_TR1";

CREATE TRIGGER GALADM.MBPN_PRODUCT_TR1 NO CASCADE BEFORE INSERT ON GALADM.MBPN_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MBPN_PRODUCT_TR2";

CREATE TRIGGER GALADM.MBPN_PRODUCT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MBPN_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


