
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MBPN_PRODUCT_TYPE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MBPN_PRODUCT_TYPE_TBX";


CREATE TABLE "GALADM  "."MBPN_PRODUCT_TYPE_TBX"  (
		  "MAIN_NO" CHAR(5 OCTETS) NOT NULL , 
		  "OWNER_MAIN_NO" CHAR(5 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MBPN_PRODUCT_TYPE_TBX" IS 'MBPN Product Type';


-- DDL Statements for Primary Key on Table "GALADM  "."MBPN_PRODUCT_TYPE_TBX"

ALTER TABLE "GALADM  "."MBPN_PRODUCT_TYPE_TBX" 
	ADD CONSTRAINT "MBPN_PRODUCT_TYPE_PK" PRIMARY KEY
		("MAIN_NO",
		 "OWNER_MAIN_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."MBPN_PRODUCT_TYPE_TR1";

CREATE TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MBPN_PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."MBPN_PRODUCT_TYPE_TR2";

CREATE TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MBPN_PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


