
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MBPN_MADE_FROM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MBPN_MADE_FROM_TBX";


CREATE TABLE "GALADM  "."MBPN_MADE_FROM_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "MAIN_NO" CHAR(5 OCTETS) NOT NULL , 
		  "FROM_PRODUCT_ID" CHAR(17 OCTETS) , 
		  "FROM_MAIN_NO" CHAR(5 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MBPN_MADE_FROM_TBX" IS 'MBPN Made From';


-- DDL Statements for Primary Key on Table "GALADM  "."MBPN_MADE_FROM_TBX"

ALTER TABLE "GALADM  "."MBPN_MADE_FROM_TBX" 
	ADD CONSTRAINT "MBPN_MADE_FROM_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "MAIN_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."MBPN_MADE_FROM_TR1";

CREATE TRIGGER GALADM.MBPN_MADE_FROM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MBPN_MADE_FROM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."MBPN_MADE_FROM_TR2";

CREATE TRIGGER GALADM.MBPN_MADE_FROM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MBPN_MADE_FROM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


