
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MBPN_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MBPN_TBX";


CREATE TABLE "GALADM  "."MBPN_TBX"  (
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "MBPN" CHAR(18 OCTETS) NOT NULL , 
		  "HES_COLOR" CHAR(11 OCTETS) NOT NULL , 
		  "MAIN_NO" CHAR(5 OCTETS) NOT NULL , 
		  "CLASS_NO" CHAR(3 OCTETS) NOT NULL , 
		  "PROTOTYPE_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "TYPE_NO" CHAR(4 OCTETS) NOT NULL , 
		  "SUPPLEMENTARY_NO" CHAR(2 OCTETS) NOT NULL , 
		  "TARGET_NO" CHAR(2 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "MASK_ID" CHAR(2 OCTETS) , 
		  "DISABLED" INTEGER WITH DEFAULT 0 )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MBPN_TBX" IS 'RMT Mbpn for defining Manufacturing Base Part Number product spec codes';


-- DDL Statements for Primary Key on Table "GALADM  "."MBPN_TBX"

ALTER TABLE "GALADM  "."MBPN_TBX" 
	ADD CONSTRAINT "MBPN_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MBPN_TR1";

CREATE TRIGGER GALADM.MBPN_TR1 NO CASCADE BEFORE INSERT ON GALADM.MBPN_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MBPN_TR2";

CREATE TRIGGER GALADM.MBPN_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MBPN_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


