
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_MDRS_TRAINING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_MDRS_TRAINING_TBX";


CREATE TABLE "GALADM  "."MC_MDRS_TRAINING_TBX"  (
		  "USER_LOGON_ID_NO" CHAR(7 OCTETS) NOT NULL , 
		  "PROCESS_ID" INTEGER NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "MTC_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "ENTERED_TSTP" TIMESTAMP NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "KNOWLEDGESTATUS_NO" INTEGER NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "PDDA_PLATFORM_ID" INTEGER , 
		  "SPEC_CODE_TYPE" VARCHAR(32 OCTETS) , 
		  "SPEC_CODE_MASK" VARCHAR(30 OCTETS) , 
		  "TRAINED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_MDRS_TRAINING_TBX" IS 'RMT MC_MDRS_TRAINING is used by Manufacturing Control to cross reference MC_TRAINING_TBX to MDRS TBLKNOWLEDGESTATUS';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_MDRS_TRAINING_TBX"

ALTER TABLE "GALADM  "."MC_MDRS_TRAINING_TBX" 
	ADD CONSTRAINT "MC_MDRS_TRAINING_PK" PRIMARY KEY
		("USER_LOGON_ID_NO",
		 "PROCESS_ID",
		 "MODEL_YEAR_DATE",
		 "MTC_MODEL",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "ENTERED_TSTP",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_TRAINING_TR1";

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_MDRS_TRAINING_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_TRAINING_TR2";

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_MDRS_TRAINING_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


