
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX";


CREATE TABLE "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX"  (
		  "TRAINING_STATUS_ID" BIGINT NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(7 OCTETS) , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "SPEC_CODE_TYPE" VARCHAR(32 OCTETS) , 
		  "SPEC_CODE_MASK" VARCHAR(30 OCTETS) , 
		  "TRAINED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX" IS 'MC_MDRS_TRAINING_STATUS_TBX is used by Manufacturing Control';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX"

ALTER TABLE "GALADM  "."MC_MDRS_TRAINING_STATUS_TBX" 
	ADD CONSTRAINT "MC_MDRS_TRAINING_STATUS_PK" PRIMARY KEY
		("TRAINING_STATUS_ID",
		 "PDDA_PLATFORM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_TRAINING_STATUS_TR1";

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR1 NO CASCADE BEFORE INSERT
ON GALADM.MC_MDRS_TRAINING_STATUS_TBX REFERENCING NEW AS A FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_TRAINING_STATUS_TR2";

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.MC_MDRS_TRAINING_STATUS_TBX REFERENCING NEW AS A FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


