
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX";


CREATE TABLE "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX"  (
		  "MANPOWER_ASSIGNMENT_ID" BIGINT NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "ASSOCIATE_ID" CHAR(7 OCTETS) , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "PDDA_PLATFORM_ID" INTEGER , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "LINE_NO" CHAR(2 OCTETS) , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) , 
		  "PLANT_CODE" CHAR(4 OCTETS) , 
		  "PRODUCTION_DATE" TIMESTAMP , 
		  "SHIFT" CHAR(2 OCTETS) , 
		  "PERIOD" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX" IS 'RMT MC_MDRS_MANPOWER_ASSIGNMENT_TBX is used by Manufacturing Control';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX"

ALTER TABLE "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TBX" 
	ADD CONSTRAINT "MC_MDRS_MANPOWER_ASSIGNMENT_PK" PRIMARY KEY
		("MANPOWER_ASSIGNMENT_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TR1";

CREATE TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR1 NO CASCADE BEFORE
INSERT ON GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX REFERENCING NEW AS A FOR
EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_MANPOWER_ASSIGNMENT_TR2";

CREATE TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX REFERENCING NEW AS A FOR
EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


