
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_MDRS_PERIOD_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_MDRS_PERIOD_TBX";


CREATE TABLE "GALADM  "."MC_MDRS_PERIOD_TBX"  (
		  "LINE_NO" CHAR(2 OCTETS) NOT NULL , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL , 
		  "PLANT_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL , 
		  "PERIOD" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "SHIFT_ID" SMALLINT NOT NULL , 
		  "QUARTER" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_MDRS_PERIOD_TBX" IS 'RMT MC_MDRS_PERIOD_TBX is used by Manufacturing Control';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_MDRS_PERIOD_TBX"

ALTER TABLE "GALADM  "."MC_MDRS_PERIOD_TBX" 
	ADD CONSTRAINT "MC_MDRS_PERIOD_PK" PRIMARY KEY
		("LINE_NO",
		 "PROCESS_LOCATION",
		 "PLANT_CODE",
		 "SHIFT",
		 "PERIOD",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "SHIFT_ID",
		 "QUARTER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_PERIOD_TR1";

CREATE TRIGGER GALADM.MC_MDRS_PERIOD_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_MDRS_PERIOD_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_MDRS_PERIOD_TR2";

CREATE TRIGGER GALADM.MC_MDRS_PERIOD_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_MDRS_PERIOD_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


