
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_ORDER_STRUCTURE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_ORDER_STRUCTURE_TBX";


CREATE TABLE "GALADM  "."MC_ORDER_STRUCTURE_TBX"  (
		  "ORDER_NO" CHAR(20 OCTETS) NOT NULL , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "STRUCTURE_REV" BIGINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_ORDER_STRUCTURE_TBX" IS 'RMT MC_ORDER_STRUCTURE is used by Manufacturing Control to define the structure revision that should be used to manufacture this order / lot';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_ORDER_STRUCTURE_TBX"

ALTER TABLE "GALADM  "."MC_ORDER_STRUCTURE_TBX" 
	ADD CONSTRAINT "MC_ORDER_STRUCTURE_PK" PRIMARY KEY
		("ORDER_NO",
		 "DIVISION_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_ORDER_STRUCTURE_TR1";

CREATE TRIGGER GALADM.MC_ORDER_STRUCTURE_TR1 NO CASCADE BEFORE INSERT ON
GALADM.MC_ORDER_STRUCTURE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_ORDER_STRUCTURE_TR2";

CREATE TRIGGER GALADM.MC_ORDER_STRUCTURE_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.MC_ORDER_STRUCTURE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


