
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_REV_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_REV_TBX";


CREATE TABLE "GALADM  "."MC_OP_REV_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "REV_ID" BIGINT NOT NULL , 
		  "OP_DESC" VARCHAR(255 OCTETS) , 
		  "OP_TYPE" VARCHAR(32 OCTETS) , 
		  "OP_VIEW" VARCHAR(255 OCTETS) , 
		  "OP_PROCESSOR" VARCHAR(255 OCTETS) , 
		  "OP_CHECK" INTEGER , 
		  "APPROVED" TIMESTAMP , 
		  "DEPRECATED_REV_ID" BIGINT , 
		  "DEPRECATED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_REV_TBX" IS 'RMT MC_OP_REV is used by Manufacturing Control to define the revision of operations that can be performed at a process point';


-- DDL Statements for Indexes on Table "GALADM  "."MC_OP_REV_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MC_OP_REV_I1" ON "GALADM  "."MC_OP_REV_TBX" 
		("OPERATION_NAME" ASC,
		 "OP_REV" ASC)
		INCLUDE ("APPROVED" ,
		 "DEPRECATED" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_REV_TBX"

ALTER TABLE "GALADM  "."MC_OP_REV_TBX" 
	ADD CONSTRAINT "MC_OP_REV_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "OP_REV");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_REV_TR1";

CREATE TRIGGER GALADM.MC_OP_REV_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_REV_TR2";

CREATE TRIGGER GALADM.MC_OP_REV_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

--Add column COMMON_NAME
ALTER TABLE GALADM.MC_OP_REV_TBX ADD COMMON_NAME VARCHAR(255) DEFAULT '';


