
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_PART_MATRIX_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_PART_MATRIX_TBX";


CREATE TABLE "GALADM  "."MC_OP_PART_MATRIX_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PART_REV" INTEGER NOT NULL , 
		  "SPEC_CODE_TYPE" VARCHAR(32 OCTETS) NOT NULL , 
		  "SPEC_CODE_MASK" VARCHAR(30 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_PART_MATRIX_TBX" IS 'RMT MC_OP_PART_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MC_STRUCTUREs';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_PART_MATRIX_TBX"

ALTER TABLE "GALADM  "."MC_OP_PART_MATRIX_TBX" 
	ADD CONSTRAINT "MC_OP_PART_MATRIX_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PART_ID",
		 "PART_REV",
		 "SPEC_CODE_TYPE",
		 "SPEC_CODE_MASK");



-- DDL Statements for Indexes on Table "GALADM  "."MC_OP_PART_MATRIX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MC_OP_PART_MATRIX_I2" ON "GALADM  "."MC_OP_PART_MATRIX_TBX" 
		("SPEC_CODE_TYPE" ASC,
		 "SPEC_CODE_MASK" DESC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_MATRIX_TR1";

CREATE TRIGGER GALADM.MC_OP_PART_MATRIX_TR1 NO CASCADE BEFORE INSERT ON
GALADM.MC_OP_PART_MATRIX_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_MATRIX_TR2";

CREATE TRIGGER GALADM.MC_OP_PART_MATRIX_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.MC_OP_PART_MATRIX_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


