
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_PART_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_PART_TBX";


CREATE TABLE "GALADM  "."MC_OP_PART_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PART_REV" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_PART_TBX" IS 'RMT MC_OP_PART is used by Manufacturing Control to define the current part specs that can be used at an operation';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_PART_TBX"

ALTER TABLE "GALADM  "."MC_OP_PART_TBX" 
	ADD CONSTRAINT "MC_OP_PART_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PART_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_TR1";

CREATE TRIGGER GALADM.MC_OP_PART_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_PART_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_TR2";

CREATE TRIGGER GALADM.MC_OP_PART_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_PART_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


