
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_PART_REV_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_PART_REV_TBX";


CREATE TABLE "GALADM  "."MC_OP_PART_REV_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PART_REV" INTEGER NOT NULL , 
		  "REV_ID" BIGINT NOT NULL , 
		  "PART_DESC" VARCHAR(255 OCTETS) , 
		  "PART_TYPE" VARCHAR(32 OCTETS) , 
		  "PART_VIEW" VARCHAR(255 OCTETS) , 
		  "PART_PROCESSOR" VARCHAR(255 OCTETS) , 
		  "DEVICE_ID" CHAR(32 OCTETS) , 
		  "DEVICE_MSG" CHAR(32 OCTETS) , 
		  "PART_NO" CHAR(18 OCTETS) , 
		  "PART_SECTION_CODE" CHAR(3 OCTETS) , 
		  "PART_ITEM_NO" CHAR(8 OCTETS) , 
		  "PART_MASK" VARCHAR(255 OCTETS) , 
		  "PART_MARK" VARCHAR(32 OCTETS) , 
		  "PART_MAX_ATTEMPTS" INTEGER , 
		  "MEASUREMENT_COUNT" INTEGER , 
		  "PART_TIME" INTEGER , 
		  "PART_CHECK" INTEGER , 
		  "APPROVED" TIMESTAMP , 
		  "DEPRECATED_REV_ID" BIGINT , 
		  "DEPRECATED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_PART_REV_TBX" IS 'RMT MC_OP_PART_REV is used by Manufacturing Control to define the revision of parts that can be used at an operation';


-- DDL Statements for Indexes on Table "GALADM  "."MC_OP_PART_REV_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MC_OP_PART_REV_I1" ON "GALADM  "."MC_OP_PART_REV_TBX" 
		("OPERATION_NAME" ASC,
		 "PART_ID" ASC,
		 "PART_REV" ASC)
		INCLUDE ("APPROVED" ,
		 "DEPRECATED" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_PART_REV_TBX"

ALTER TABLE "GALADM  "."MC_OP_PART_REV_TBX" 
	ADD CONSTRAINT "MC_OP_PART_REV_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PART_ID",
		 "PART_REV");




-- DDL Statements for Foreign Keys on Table "GALADM  "."MC_OP_PART_REV_TBX"

ALTER TABLE "GALADM  "."MC_OP_PART_REV_TBX" 
	ADD CONSTRAINT "MC_OP_PART_REV_FK1" FOREIGN KEY
		("OPERATION_NAME")
	REFERENCES "GALADM  "."MC_OP_TBX"
		("OPERATION_NAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."MC_OP_PART_REV_TBX" 
	ADD CONSTRAINT "MC_OP_PART_REV_FK3" FOREIGN KEY
		("REV_ID")
	REFERENCES "GALADM  "."MC_REV_TBX"
		("REV_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."MC_OP_PART_REV_TBX" 
	ADD CONSTRAINT "MC_OP_PART_REV_FK4" FOREIGN KEY
		("DEPRECATED_REV_ID")
	REFERENCES "GALADM  "."MC_REV_TBX"
		("REV_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_REV_TR1";

CREATE TRIGGER GALADM.MC_OP_PART_REV_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_PART_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_PART_REV_TR2";

CREATE TRIGGER GALADM.MC_OP_PART_REV_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_PART_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


