
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_TBX";


CREATE TABLE "GALADM  "."MC_OP_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_TBX" IS 'RMT MC_OP is used by Manufacturing Control to define the current operations that can be performed at a process point';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_TBX"

ALTER TABLE "GALADM  "."MC_OP_TBX" 
	ADD CONSTRAINT "MC_OP_PK" PRIMARY KEY
		("OPERATION_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_TR1";

CREATE TRIGGER GALADM.MC_OP_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_TR2";

CREATE TRIGGER GALADM.MC_OP_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


