
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_CHECKER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_CHECKER_TBX";


CREATE TABLE "GALADM  "."MC_OP_CHECKER_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "CHECK_POINT" VARCHAR(32 OCTETS) NOT NULL , 
		  "CHECK_SEQ" INTEGER NOT NULL , 
		  "CHECK_NAME" VARCHAR(35 OCTETS) NOT NULL , 
		  "CHECKER" VARCHAR(255 OCTETS) NOT NULL , 
		  "REACTION_TYPE" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_CHECKER_TBX" IS 'RMT MC_OP_CHECKER_TBX is used by Manufacturing Control to define Checkers at the Operation/Unit level';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_CHECKER_TBX"

ALTER TABLE "GALADM  "."MC_OP_CHECKER_TBX" 
	ADD CONSTRAINT "MC_OP_CHECKER_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "OP_REV",
		 "CHECK_POINT",
		 "CHECK_SEQ");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_CHECKER_TR1";

CREATE TRIGGER GALADM.MC_OP_CHECKER_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_CHECKER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_CHECKER_TR2";

CREATE TRIGGER GALADM.MC_OP_CHECKER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_CHECKER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


