
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_REV_PLATFORM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_REV_PLATFORM_TBX";


CREATE TABLE "GALADM  "."MC_OP_REV_PLATFORM_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "OP_SEQ_NUM" INTEGER , 
		  "OP_TIME" INTEGER , 
		  "DEVICE_ID" CHAR(32 OCTETS) , 
		  "DEVICE_MSG" CHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_REV_PLATFORM_TBX" IS 'RMT MC_OP_REV_PLATFORM is used by Manufacturing Control to define the platforms that should perform this revision of operation';


-- DDL Statements for Indexes on Table "GALADM  "."MC_OP_REV_PLATFORM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MC_OP_REV_PLATFORM_I1" ON "GALADM  "."MC_OP_REV_PLATFORM_TBX" 
		("OPERATION_NAME" ASC,
		 "PDDA_PLATFORM_ID" ASC,
		 "OP_REV" ASC)
		INCLUDE ("OP_TIME" ,
		 "OP_SEQ_NUM" ,
		 "DEVICE_MSG" ,
		 "DEVICE_ID" ,
		 "UPDATE_TIMESTAMP" ,
		 "CREATE_TIMESTAMP" )
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_REV_PLATFORM_TBX"

ALTER TABLE "GALADM  "."MC_OP_REV_PLATFORM_TBX" 
	ADD CONSTRAINT "MC_OP_REV_PLATFORM_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PDDA_PLATFORM_ID",
		 "OP_REV");




-- DDL Statements for Indexes on Table "GALADM  "."MC_OP_REV_PLATFORM_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MC_OP_REV_PLATFORM_I2" ON "GALADM  "."MC_OP_REV_PLATFORM_TBX" 
		("OP_REV" ASC,
		 "OPERATION_NAME" ASC,
		 "PDDA_PLATFORM_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_REV_PLATFORM_TR1";

CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR1 NO CASCADE BEFORE INSERT ON
GALADM.MC_OP_REV_PLATFORM_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_REV_PLATFORM_TR2";

CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.MC_OP_REV_PLATFORM_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


