
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_OP_MEAS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_OP_MEAS_TBX";


CREATE TABLE "GALADM  "."MC_OP_MEAS_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PART_REV" INTEGER NOT NULL , 
		  "OP_MEAS_SEQ_NUM" INTEGER NOT NULL , 
		  "MEAS_TYPE" VARCHAR(32 OCTETS) , 
		  "MEAS_VIEW" VARCHAR(255 OCTETS) , 
		  "MEAS_PROCESSOR" VARCHAR(255 OCTETS) , 
		  "DEVICE_ID" CHAR(32 OCTETS) , 
		  "DEVICE_MSG" CHAR(32 OCTETS) , 
		  "MIN_LIMIT" DOUBLE , 
		  "MAX_LIMIT" DOUBLE , 
		  "MEAS_MAX_ATTEMPTS" INTEGER , 
		  "MEAS_TIME" INTEGER , 
		  "MEAS_CHECK" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_OP_MEAS_TBX" IS 'RMT MC_OP_MEAS is used by Manufacturing Control to define the part measurement specs for a specific revision of an operation part';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_OP_MEAS_TBX"

ALTER TABLE "GALADM  "."MC_OP_MEAS_TBX" 
	ADD CONSTRAINT "MC_OP_MEAS_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PART_ID",
		 "PART_REV",
		 "OP_MEAS_SEQ_NUM");



-- DDL Statements for Foreign Keys on Table "GALADM  "."MC_OP_MEAS_TBX"

ALTER TABLE "GALADM  "."MC_OP_MEAS_TBX" 
	ADD CONSTRAINT "MC_OP_MEAS_FK1" FOREIGN KEY
		("OPERATION_NAME")
	REFERENCES "GALADM  "."MC_OP_TBX"
		("OPERATION_NAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_MEAS_TR1";

CREATE TRIGGER GALADM.MC_OP_MEAS_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_OP_MEAS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_OP_MEAS_TR2";

CREATE TRIGGER GALADM.MC_OP_MEAS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_OP_MEAS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


