
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX";


CREATE TABLE "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "DEPT_CODE" CHAR(2 OCTETS) , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) , 
		  "PROD_SCH_QTY" DECIMAL(5,1) , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX" IS 'RMT MC_PRODUCT_PDDA_PLATFORM is used by Manufacturing Control to link PDDA Plant Loc Code, Dept Code, Model Year Date, Prod Sch Qty, Prod ASM Line No, Vehicle Model Code to GALC PRODUCT ID';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX"

ALTER TABLE "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TBX" 
	ADD CONSTRAINT "MC_PRODUCT_PDDA_PLATFORM_PK" PRIMARY KEY
		("PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TR1";

CREATE TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PRODUCT_PDDA_PLATFORM_TR2";

CREATE TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


