
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX";


CREATE TABLE "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "LINE_NO" CHAR(2 OCTETS) NOT NULL , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL , 
		  "PLANT_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "PRODUCTION_DATE" TIMESTAMP NOT NULL , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL , 
		  "PERIOD" INTEGER NOT NULL , 
		  "APPROVER_NO" CHAR(11 OCTETS) , 
		  "APPROVE_METHOD" VARCHAR(16 OCTETS) , 
		  "COMMENTS" VARCHAR(250 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX" IS 'MC_PROCESS_ASSIGNMENT_TBX is used by Manufacturing Control';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX"

ALTER TABLE "GALADM  "."MC_PROCESS_ASSIGNMENT_TBX" 
	ADD CONSTRAINT "MC_PROCESS_ASSIGNMENT_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PDDA_PLATFORM_ID",
		 "LINE_NO",
		 "PROCESS_LOCATION",
		 "PLANT_CODE",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "PERIOD");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PROCESS_ASSIGNMENT_TR1";

CREATE TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR1 NO CASCADE BEFORE INSERT
ON GALADM.MC_PROCESS_ASSIGNMENT_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PROCESS_ASSIGNMENT_TR2";

CREATE TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.MC_PROCESS_ASSIGNMENT_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


