
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_PDDA_CHG_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_PDDA_CHG_TBX";


CREATE TABLE "GALADM  "."MC_PDDA_CHG_TBX"  (
		  "REV_ID" BIGINT NOT NULL , 
		  "CHANGE_FORM_ID" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_PDDA_CHG_TBX" IS 'RMT MC_PDDA_CHG is used by Manufacturing Control to link the PDDA Change Forms to GALC Revision';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_PDDA_CHG_TBX"

ALTER TABLE "GALADM  "."MC_PDDA_CHG_TBX" 
	ADD CONSTRAINT "MC_PDDA_CHG_PK" PRIMARY KEY
		("REV_ID",
		 "CHANGE_FORM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_CHG_TR1";

CREATE TRIGGER GALADM.MC_PDDA_CHG_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_PDDA_CHG_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_CHG_TR2";

CREATE TRIGGER GALADM.MC_PDDA_CHG_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_PDDA_CHG_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


