
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_PDDA_UNIT_REV_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_PDDA_UNIT_REV_TBX";


CREATE TABLE "GALADM  "."MC_PDDA_UNIT_REV_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "UNIT_NO" VARCHAR(6 OCTETS) NOT NULL , 
		  "PDDA_REPORT" VARCHAR(6 OCTETS) NOT NULL , 
		  "APVD_PROC_MAINT_ID" INTEGER NOT NULL , 
		  "APVD_UNIT_MAINT_ID" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_PDDA_UNIT_REV_TBX" IS 'RMT MC_PDDA_UNIT_REV is used by Manufacturing Control to define the approved PDDA revision of units on the given PDDA report';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_PDDA_UNIT_REV_TBX"

ALTER TABLE "GALADM  "."MC_PDDA_UNIT_REV_TBX" 
	ADD CONSTRAINT "MC_PDDA_UNIT_REV_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "OP_REV",
		 "PDDA_PLATFORM_ID",
		 "UNIT_NO",
		 "PDDA_REPORT");



-- DDL Statements for Indexes on Table "GALADM  "."MC_PDDA_UNIT_REV_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MC_PDDA_UNIT_REV_I1" ON "GALADM  "."MC_PDDA_UNIT_REV_TBX" 
		("PDDA_REPORT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_UNIT_REV_TR1";

CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_PDDA_UNIT_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_UNIT_REV_TR2";

CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_PDDA_UNIT_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


