
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_PDDA_UNIT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_PDDA_UNIT_TBX";


CREATE TABLE "GALADM  "."MC_PDDA_UNIT_TBX"  (
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL , 
		  "REV_ID" BIGINT NOT NULL , 
		  "APPROVER_NO" CHAR(11 OCTETS) , 
		  "APPROVED" TIMESTAMP , 
		  "DEPRECATED_REV_ID" BIGINT , 
		  "DEPRECATER_NO" CHAR(11 OCTETS) , 
		  "DEPRECATED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_PDDA_UNIT_TBX" IS 'RMT MC_PDDA_UNIT is used by Manufacturing Control to define the active PDDA Platforms and Unit No associated to an Operation Name';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_PDDA_UNIT_TBX"

ALTER TABLE "GALADM  "."MC_PDDA_UNIT_TBX" 
	ADD CONSTRAINT "MC_PDDA_UNIT_PK" PRIMARY KEY
		("OPERATION_NAME",
		 "PDDA_PLATFORM_ID",
		 "UNIT_NO",
		 "REV_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_UNIT_TR1";

CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_PDDA_UNIT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_PDDA_UNIT_TR2";

CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_PDDA_UNIT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


