
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_REV_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_REV_TBX";


CREATE TABLE "GALADM  "."MC_REV_TBX"  (
		  "REV_ID" BIGINT NOT NULL , 
		  "REV_DESC" VARCHAR(255 OCTETS) , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "REV_TYPE" VARCHAR(32 OCTETS) , 
		  "REV_STATUS" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_REV_TBX" IS 'RMT MC_REV is used by Manufacturing Control to track the revisions of operations and parts';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_REV_TBX"

ALTER TABLE "GALADM  "."MC_REV_TBX" 
	ADD CONSTRAINT "MC_REV_PK" PRIMARY KEY
		("REV_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_REV_TR1";

CREATE TRIGGER GALADM.MC_REV_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_REV_TR2";

CREATE TRIGGER GALADM.MC_REV_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_REV_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


