
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_STRUCTURE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_STRUCTURE_TBX";


CREATE TABLE "GALADM  "."MC_STRUCTURE_TBX"  (
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "STRUCTURE_REV" BIGINT NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "OPERATION_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "OP_REV" INTEGER NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PART_REV" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PROCESS_SEQ_NUM" INTEGER NOT NULL WITH DEFAULT 0 )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_STRUCTURE_TBX" IS 'RMT MC_STRUCTURE is used by Manufacturing Control to define the revisions of operations and parts that are used to manufacture a Product Spec Code';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_STRUCTURE_TBX"

ALTER TABLE "GALADM  "."MC_STRUCTURE_TBX" 
	ADD CONSTRAINT "MC_STRUCTURE_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE",
		 "STRUCTURE_REV",
		 "DIVISION_ID",
		 "PROCESS_POINT_ID",
		 "OPERATION_NAME",
		 "OP_REV",
		 "PDDA_PLATFORM_ID",
		 "PART_ID",
		 "PART_REV");



-- DDL Statements for Indexes on Table "GALADM  "."MC_STRUCTURE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MC_STRUCTURE_I1" ON "GALADM  "."MC_STRUCTURE_TBX" 
		("OPERATION_NAME" ASC,
		 "OP_REV" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MC_STRUCTURE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MC_STRUCTURE_I2" ON "GALADM  "."MC_STRUCTURE_TBX" 
		("STRUCTURE_REV" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_STRUCTURE_TR1";

CREATE TRIGGER GALADM.MC_STRUCTURE_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_STRUCTURE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_STRUCTURE_TR2";

CREATE TRIGGER GALADM.MC_STRUCTURE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_STRUCTURE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

-- Add PROCESS_SEQ_NUM Column in MC_STRUCTURE_TBX
ALTER TABLE GALADM.MC_STRUCTURE_TBX ADD PROCESS_SEQ_NUM INTEGER NOT NULL DEFAULT 0;