
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MC_TRAINING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MC_TRAINING_TBX";


CREATE TABLE "GALADM  "."MC_TRAINING_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) NOT NULL , 
		  "PDDA_PLATFORM_ID" INTEGER NOT NULL , 
		  "SPEC_CODE_TYPE" VARCHAR(32 OCTETS) NOT NULL , 
		  "SPEC_CODE_MASK" VARCHAR(30 OCTETS) NOT NULL , 
		  "TRAINED" TIMESTAMP NOT NULL , 
		  "EXPIRED" TIMESTAMP , 
		  "APPROVER_NO" CHAR(11 OCTETS) , 
		  "TRAINING_METHOD" VARCHAR(16 OCTETS) , 
		  "COMMENTS" VARCHAR(250 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MC_TRAINING_TBX" IS 'RMT MC_TRAINING is used by Manufacturing Control to define the Associates that are trained for specific products at a given process';


-- DDL Statements for Primary Key on Table "GALADM  "."MC_TRAINING_TBX"

ALTER TABLE "GALADM  "."MC_TRAINING_TBX" 
	ADD CONSTRAINT "MC_TRAINING_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "ASSOCIATE_NO",
		 "PDDA_PLATFORM_ID",
		 "SPEC_CODE_TYPE",
		 "SPEC_CODE_MASK",
		 "TRAINED");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_TRAINING_TR1";

CREATE TRIGGER GALADM.MC_TRAINING_TR1 NO CASCADE BEFORE INSERT ON GALADM.MC_TRAINING_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MC_TRAINING_TR2";

CREATE TRIGGER GALADM.MC_TRAINING_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MC_TRAINING_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


