DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER			NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_VIOS_MASTER_OP_MEAS_CHECKER_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, OP_MEAS_SEQ_NUM, CHECK_POINT, CHECK_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX IS 'RMT MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX is used by Manufacturing Control to define master data of Checkers at the measurement level';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX ADD USER_ID CHAR(11) NOT NULL;
