DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_TYPE            VARCHAR(32)		NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER			NOT NULL,
   DEVICE_ID			CHARACTER(32),
   DEVICE_MSG			CHARACTER(32),
   MIN_LIMIT			DOUBLE,
   MAX_LIMIT			DOUBLE,
   MEAS_CHECK			INTEGER,
   MEAS_MAX_ATTEMPTS	INTEGER,
   MEAS_VIEW			VARCHAR(255),
   MEAS_PROCESSOR		VARCHAR(255),
   MEAS_TIME			INTEGER,
   MEAS_TYPE			VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX IS 'RMT MC_VIOS_MASTER_OP_MEAS_TBX is used by Manufacturing Control to define the master data of measurements that can be used in a part';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_MEAS_I1 ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  (VIOS_PLATFORM_ID ASC, UNIT_NO ASC, PART_TYPE ASC, OP_MEAS_SEQ_NUM ASC)
  INCLUDE (CREATE_TIMESTAMP, UPDATE_TIMESTAMP)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_MEAS_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO, PART_TYPE, OP_MEAS_SEQ_NUM);
     
 ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX ADD USER_ID CHAR(11) NOT NULL;
