DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   OP_VIEW         	 	VARCHAR(255)	NOT NULL,
   OP_PROCESSOR     	VARCHAR(255)	NOT NULL,
   COMMON_NAME	     	VARCHAR(255),
   OP_CHECK 			INTEGER,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_TBX IS 'RMT MC_VIOS_MASTER_OP_TBX is used by Manufacturing Control to create master configuration of Views and Processors';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO);
     
 ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX ADD USER_ID CHAR(11) NOT NULL;