DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_NO              CHARACTER(18)	NOT NULL,
   PART_TYPE            VARCHAR(32)		NOT NULL,
   PART_DESC            VARCHAR(255),
   PART_VIEW            VARCHAR(255),
   PART_PROCESSOR       VARCHAR(255),
   DEVICE_ID            CHARACTER(32),
   DEVICE_MSG           CHARACTER(32),
   PART_MASK          	VARCHAR(255),
   PART_MARK            VARCHAR(32),
   MEASUREMENT_COUNT  	INTEGER,
   PART_CHECK           INTEGER,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX IS 'RMT MC_VIOS_MASTER_OP_PART_TBX is used by Manufacturing Control to define the master data of parts that can be used at an operation';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_PART_I1 ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  (VIOS_PLATFORM_ID ASC, UNIT_NO ASC, PART_NO ASC, PART_TYPE ASC)
  INCLUDE (CREATE_TIMESTAMP, UPDATE_TIMESTAMP)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_PART_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_TYPE);
     
 ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX ADD USER_ID CHAR(11) NOT NULL;
