
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MEASUREMENT_SPEC_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MEASUREMENT_SPEC_TBX";


CREATE TABLE "GALADM  "."MEASUREMENT_SPEC_TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "MEASUREMENT_SEQ_NUM" INTEGER NOT NULL , 
		  "MINIMUM_LIMIT" DOUBLE , 
		  "MAXIMUM_LIMIT" DOUBLE , 
		  "MAX_ATTEMPTS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MEASUREMENT_SPEC_TBX" IS 'RMT MeasurementSpec for LOT CONTROL to define Installed Part Measurement Specs';


-- DDL Statements for Primary Key on Table "GALADM  "."MEASUREMENT_SPEC_TBX"

ALTER TABLE "GALADM  "."MEASUREMENT_SPEC_TBX" 
	ADD CONSTRAINT "MEASUREMENTSPECPK" PRIMARY KEY
		("PART_NAME",
		 "PART_ID",
		 "MEASUREMENT_SEQ_NUM");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MEASUREMENT_SPEC_TR1";

CREATE TRIGGER GALADM.MEASUREMENT_SPEC_TR1 NO CASCADE BEFORE INSERT ON GALADM.MEASUREMENT_SPEC_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MEASUREMENT_SPEC_TR2";

CREATE TRIGGER GALADM.MEASUREMENT_SPEC_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MEASUREMENT_SPEC_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


