
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MISSION_SPEC_CODE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MISSION_SPEC_CODE_TBX";


CREATE TABLE "GALADM  "."MISSION_SPEC_CODE_TBX"  (
		  "PRODUCT_SPEC_CODE" VARCHAR(22 OCTETS) NOT NULL , 
		  "PLANT_CODE" VARCHAR(4 OCTETS) , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "MODEL_CODE" VARCHAR(3 OCTETS) , 
		  "MODEL_TYPE_CODE" VARCHAR(3 OCTETS) , 
		  "MODEL_OPTION_CODE" VARCHAR(3 OCTETS) , 
		  "MISSION_NO_PREFIX" VARCHAR(5 OCTETS) , 
		  "MODEL_YEAR_DESCRIPTION" VARCHAR(4 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "STAMP_SERIAL_DESC" VARCHAR(30 OCTETS) , 
		  "BOUNDARY_MARK" VARCHAR(1 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."MISSION_SPEC_CODE_TBX" IS 'RMT Mission Spec';


-- DDL Statements for Primary Key on Table "GALADM  "."MISSION_SPEC_CODE_TBX"

ALTER TABLE "GALADM  "."MISSION_SPEC_CODE_TBX" 
	ADD CONSTRAINT "MISSION_SPEC_CODE_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MISSION_SPEC_CODE_TR1";

CREATE TRIGGER GALADM.MISSION_SPEC_CODE_TR1 NO CASCADE BEFORE INSERT ON
GALADM.MISSION_SPEC_CODE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MISSION_SPEC_CODE_TR2";

CREATE TRIGGER GALADM.MISSION_SPEC_CODE_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.MISSION_SPEC_CODE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


