
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MISSION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MISSION_TBX";


CREATE TABLE "GALADM  "."MISSION_TBX"  (
		  "PRODUCT_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "PRODUCTION_LOT" VARCHAR(20 OCTETS) , 
		  "PRODUCT_SPEC_CODE" VARCHAR(22 OCTETS) NOT NULL , 
		  "PLAN_OFF_DATE" DATE , 
		  "KD_LOT_NUMBER" VARCHAR(18 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "PRODUCT_START_DATE" DATE , 
		  "ACTUAL_OFF_DATE" DATE , 
		  "AUTO_HOLD_STATUS" SMALLINT , 
		  "TRACKING_STATUS" VARCHAR(16 OCTETS) , 
		  "LAST_PASSING_PROCESS_POINT_ID" VARCHAR(16 OCTETS) , 
		  "DEFECT_STATUS" SMALLINT , 
		  "REPAIR_FLAG" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."MISSION_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."MISSION_TBX" IS 'RMT Mission';


-- DDL Statements for Primary Key on Table "GALADM  "."MISSION_TBX"

ALTER TABLE "GALADM  "."MISSION_TBX" 
	ADD CONSTRAINT "MISSION_PK" PRIMARY KEY
		("PRODUCT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."MISSION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MISSION_I1" ON "GALADM  "."MISSION_TBX" 
		("PRODUCT_ID" ASC,
		 "PRODUCT_SPEC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MISSION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MISSION_I2" ON "GALADM  "."MISSION_TBX" 
		("PRODUCTION_DATE" ASC,
		 "PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MISSION_TR1";

CREATE TRIGGER GALADM.MISSION_TR1 NO CASCADE BEFORE INSERT ON GALADM.MISSION_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MISSION_TR2";

CREATE TRIGGER GALADM.MISSION_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MISSION_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


