
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MODEL_GROUP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MODEL_GROUP_TBX";


CREATE TABLE "GALADM  "."MODEL_GROUP_TBX"  (
		  "MODEL_GROUP" VARCHAR(32 OCTETS) NOT NULL , 
		  "SYSTEM" CHAR(18 OCTETS) NOT NULL , 
		  "MODEL_GROUP_DESCRIPTION" VARCHAR(32 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."MODEL_GROUP_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."MODEL_GROUP_TBX" IS 'MTC Model Group';


-- DDL Statements for Indexes on Table "GALADM  "."MODEL_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MODEL_GROUP_I1" ON "GALADM  "."MODEL_GROUP_TBX" 
		("MODEL_GROUP" ASC,
		 "SYSTEM" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."MODEL_GROUP_TBX"

ALTER TABLE "GALADM  "."MODEL_GROUP_TBX" 
	ADD CONSTRAINT "MODEL_GROUP_PK" PRIMARY KEY
		("MODEL_GROUP",
		 "SYSTEM");




-- DDL Statements for Check Constraints on Table "GALADM  "."MODEL_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."MODEL_GROUP_TBX" 
	ADD CONSTRAINT "MODEL_GROUP_C1" CHECK 
		(MODEL_GROUP = UPPER(MODEL_GROUP))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."MODEL_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."MODEL_GROUP_TBX" 
	ADD CONSTRAINT "MODEL_GROUP_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."MODEL_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."MODEL_GROUP_TBX" 
	ADD CONSTRAINT "MODEL_GROUP_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MODEL_GROUP_TR1";

CREATE TRIGGER GALADM.MODEL_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MODEL_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MODEL_GROUP_TR2";

CREATE TRIGGER GALADM.MODEL_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MODEL_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


