------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."MODEL_LOT"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."MODEL_LOT";

CREATE TABLE "LCVINBOM  "."MODEL_LOT"  (
		  "MODEL_PART_ID" BIGINT NOT NULL , 
		  "PLAN_CODE" CHAR(11) NOT NULL , 
		  "STARTING_PRODUCTION_LOT" CHAR(20) NOT NULL , 		  
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."MODEL_LOT" IS 'VIN-BOM Link Rule to Lot Assignment';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."MODEL_LOT"

ALTER TABLE "LCVINBOM  "."MODEL_LOT" 
	ADD CONSTRAINT "MODEL_LOT_PK" PRIMARY KEY
		("MODEL_PART_ID","PLAN_CODE");
		
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_LOT_TR1";

CREATE TRIGGER LCVINBOM.MODEL_LOT_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.MODEL_LOT
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_LOT_TR2";

CREATE TRIGGER LCVINBOM.MODEL_LOT_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.MODEL_LOT
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;