
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MS_PMX_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."MS_PMX_TBX";


CREATE TABLE "GALADM  "."MS_PMX_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "PLAN_CODE" CHAR(11 OCTETS) , 
		  "LINE_NO" CHAR(2 OCTETS) , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "PRODUCTION_DATE" DATE , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "LOT_SIZE" INTEGER , 
		  "ON_SEQ_NO" INTEGER , 
		  "PRODUCTION_LOT" CHAR(12 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "CURRENT_TIMESTAMP" CHAR(14 OCTETS) , 
		  "SENT_FLAG" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."MS_PMX_TBX" DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS;

COMMENT ON TABLE "GALADM  "."MS_PMX_TBX" IS 'OSL OIF Table';


-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MS_PMX_I1" ON "GALADM  "."MS_PMX_TBX" 
		("PRODUCT_ID" ASC,
		 "PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."MS_PMX_TBX"

ALTER TABLE "GALADM  "."MS_PMX_TBX" 
	ADD CONSTRAINT "MS_PMX_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PROCESS_POINT_ID");




-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MS_PMX_I2" ON "GALADM  "."MS_PMX_TBX" 
		("PRODUCT_ID" ASC,
		 "ON_SEQ_NO" ASC,
		 "PROCESS_POINT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MS_PMX_I3" ON "GALADM  "."MS_PMX_TBX" 
		("PRODUCTION_LOT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."MS_PMX_I4" ON "GALADM  "."MS_PMX_TBX" 
		("PRODUCT_ID" ASC,
		 "PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MS_PMX_I5" ON "GALADM  "."MS_PMX_TBX" 
		("ACTUAL_TIMESTAMP" ASC,
		 "PRODUCT_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."MS_PMX_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."MS_PMX_I6" ON "GALADM  "."MS_PMX_TBX" 
		("SENT_FLAG" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MS_PMX_TR1";

CREATE TRIGGER GALADM.MS_PMX_TR1 NO CASCADE BEFORE INSERT ON GALADM.MS_PMX_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."MS_PMX_TR2";

CREATE TRIGGER GALADM.MS_PMX_TR2 NO CASCADE BEFORE UPDATE ON GALADM.MS_PMX_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


