
------------------------------------------------
-- DDL Statements for Table "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX";


CREATE TABLE "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX"  (
		  "NOTIFICATION_CLASS" VARCHAR(256 OCTETS) NOT NULL , 
		  "CLIENT_IP" VARCHAR(255 OCTETS) NOT NULL , 
		  "CLIENT_PORT" INTEGER NOT NULL , 
		  "CLIENT_NAME" CHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "NOTIFICATION_HANDLER_CLASS" VARCHAR(255 OCTETS) , 
		  "PROVIDER" VARCHAR(256 OCTETS) NOT NULL WITH DEFAULT 'ANY' , 
		  "SUBSCRIPTION_TYPE" CHAR(7 OCTETS) NOT NULL WITH DEFAULT 'INCLUDE' )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX" IS 'RMT NotificationSubscriber for managing clients setup for asynchronous communication';


-- DDL Statements for Primary Key on Table "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX"

ALTER TABLE "GALADM  "."NOTIFICATION_SUBSCRIBER_TBX" 
	ADD CONSTRAINT "NOTIFICATION_SUBSCRIBER_PK" PRIMARY KEY
		("NOTIFICATION_CLASS",
		 "CLIENT_IP",
		 "CLIENT_PORT",
		 "PROVIDER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_SUBSCRIBER_TR1";

CREATE TRIGGER GALADM.NOTIFICATION_SUBSCRIBER_TR1 NO CASCADE BEFORE INSERT
ON GALADM.NOTIFICATION_SUBSCRIBER_TBX REFERENCING NEW AS A FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_SUBSCRIBER_TR2";

CREATE TRIGGER GALADM.NOTIFICATION_SUBSCRIBER_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.NOTIFICATION_SUBSCRIBER_TBX REFERENCING NEW AS A FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


