
------------------------------------------------
-- DDL Statements for Table "GALADM  "."NOTIFICATION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."NOTIFICATION_TBX";


CREATE TABLE "GALADM  "."NOTIFICATION_TBX"  (
		  "NOTIFICATION_CLASS" VARCHAR(256 OCTETS) NOT NULL , 
		  "DESCRIPTION" VARCHAR(256 OCTETS) , 
		  "CLIENT_ONLY" SMALLINT WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."NOTIFICATION_TBX" IS 'RMT Notification class definition for asynchronous communication';


-- DDL Statements for Primary Key on Table "GALADM  "."NOTIFICATION_TBX"

ALTER TABLE "GALADM  "."NOTIFICATION_TBX" 
	ADD CONSTRAINT "NOTIFICATIONPK" PRIMARY KEY
		("NOTIFICATION_CLASS");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_TR1";

CREATE TRIGGER GALADM.NOTIFICATION_TR1 NO CASCADE BEFORE INSERT ON GALADM.NOTIFICATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_TR2";

CREATE TRIGGER GALADM.NOTIFICATION_TR2 NO CASCADE BEFORE UPDATE ON GALADM.NOTIFICATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


