
------------------------------------------------
-- DDL Statements for Table "GALADM  "."NOTIFICATION_PROVIDER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."NOTIFICATION_PROVIDER_TBX";


CREATE TABLE "GALADM  "."NOTIFICATION_PROVIDER_TBX"  (
		  "NOTIFICATION_CLASS" VARCHAR(256 OCTETS) NOT NULL , 
		  "HOST_IP" VARCHAR(255 OCTETS) NOT NULL , 
		  "HOST_PORT" INTEGER NOT NULL , 
		  "HOST_NAME" CHAR(32 OCTETS) , 
		  "DESCRIPTION" VARCHAR(256 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."NOTIFICATION_PROVIDER_TBX" IS 'RMT NotificationProvider for managing hosts setup for asynchronous communication';


-- DDL Statements for Primary Key on Table "GALADM  "."NOTIFICATION_PROVIDER_TBX"

ALTER TABLE "GALADM  "."NOTIFICATION_PROVIDER_TBX" 
	ADD CONSTRAINT "NOTIFICATIONPROVPK" PRIMARY KEY
		("NOTIFICATION_CLASS",
		 "HOST_IP",
		 "HOST_PORT");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_PROVIDER_TR1";

CREATE TRIGGER GALADM.NOTIFICATION_PROVIDER_TR1 NO CASCADE BEFORE INSERT
ON GALADM.NOTIFICATION_PROVIDER_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."NOTIFICATION_PROVIDER_TR2";

CREATE TRIGGER GALADM.NOTIFICATION_PROVIDER_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.NOTIFICATION_PROVIDER_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


