
------------------------------------------------
-- DDL Statements for Table "GALADM  "."OIF_SCHED_TASK"
------------------------------------------------
 
DROP TABLE "GALADM  "."OIF_SCHED_TASK";


CREATE TABLE "GALADM  "."OIF_SCHED_TASK"  (
		  "TASKID" BIGINT NOT NULL , 
		  "VERSION" VARCHAR(5 OCTETS) NOT NULL , 
		  "ROW_VERSION" INTEGER NOT NULL , 
		  "TASKTYPE" INTEGER NOT NULL , 
		  "TASKSUSPENDED" SMALLINT NOT NULL , 
		  "CANCELLED" SMALLINT NOT NULL , 
		  "NEXTFIRETIME" BIGINT NOT NULL , 
		  "STARTBYINTERVAL" VARCHAR(254 OCTETS) , 
		  "STARTBYTIME" BIGINT , 
		  "VALIDFROMTIME" BIGINT , 
		  "VALIDTOTIME" BIGINT , 
		  "REPEATINTERVAL" VARCHAR(254 OCTETS) , 
		  "MAXREPEATS" INTEGER NOT NULL , 
		  "REPEATSLEFT" INTEGER NOT NULL , 
		  "TASKINFO" BLOB(102400) LOGGED NOT COMPACT , 
		  "NAME" VARCHAR(254 OCTETS) NOT NULL , 
		  "AUTOPURGE" INTEGER NOT NULL , 
		  "FAILUREACTION" INTEGER , 
		  "MAXATTEMPTS" INTEGER , 
		  "QOS" INTEGER , 
		  "PARTITIONID" INTEGER , 
		  "OWNERTOKEN" VARCHAR(200 OCTETS) NOT NULL , 
		  "CREATETIME" BIGINT NOT NULL )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."OIF_SCHED_TASK" IS 'RMT OIF WAS Scheduled Tasks';


-- DDL Statements for Indexes on Table "GALADM  "."OIF_SCHED_TASK"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."OIF_SCHED_TASKI1" ON "GALADM  "."OIF_SCHED_TASK" 
		("TASKID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."OIF_SCHED_TASK"

ALTER TABLE "GALADM  "."OIF_SCHED_TASK" 
	ADD CONSTRAINT "OIF_SCHED_TASK_PK" PRIMARY KEY
		("TASKID");




-- DDL Statements for Indexes on Table "GALADM  "."OIF_SCHED_TASK"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."OIF_SCHED_TASK_IDX2" ON "GALADM  "."OIF_SCHED_TASK" 
		("TASKID" ASC,
		 "OWNERTOKEN" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."OIF_SCHED_TASK"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."OIF_SCHED_TASK_IDX3" ON "GALADM  "."OIF_SCHED_TASK" 
		("NEXTFIRETIME" ASC,
		 "REPEATSLEFT" ASC,
		 "PARTITIONID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






