
------------------------------------------------
-- DDL Statements for Table "GALADM  "."ORDER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."ORDER_TBX";


CREATE TABLE "GALADM  "."ORDER_TBX"  (
		  "ORDER_NO" CHAR(20 OCTETS) NOT NULL , 
		  "PLAN_CODE" CHAR(11 OCTETS) NOT NULL , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) , 
		  "PRIORITY_DATE" DATE , 
		  "PRIORITY_SEQ" INTEGER , 
		  "PROD_ORDER_QTY" INTEGER , 
		  "LOCATION_LEVEL_ID" CHAR(16 OCTETS) , 
		  "ORDER_STATUS_ID" INTEGER , 
		  "HOLD_STATUS_ID" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."ORDER_TBX" IS 'RMT Orders for LINE to track status of Product Orders for a Plan Code';


-- DDL Statements for Primary Key on Table "GALADM  "."ORDER_TBX"

ALTER TABLE "GALADM  "."ORDER_TBX" 
	ADD CONSTRAINT "ORDER_PK" PRIMARY KEY
		("ORDER_NO",
		 "PLAN_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."ORDER_TR1";

CREATE TRIGGER GALADM.ORDER_TR1 NO CASCADE BEFORE INSERT ON GALADM.ORDER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."ORDER_TR2";

CREATE TRIGGER GALADM.ORDER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.ORDER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


