
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PALSQ1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PALSQ1";


CREATE TABLE "VIOS    "."PALSQ1"  (
		  "PCL_TO_QICS_SEQ" INTEGER NOT NULL , 
		  "COMPANY_CODE" CHAR(5 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "TEAM_DESC" CHAR(30 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL WITH DEFAULT 0.0 , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL WITH DEFAULT 0.0 , 
		  "VEHICLE_MODEL_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ASM_PROC_NO" CHAR(5 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "ASM_PROC_NAME" CHAR(35 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "UNIT_RANK" CHAR(20 OCTETS) WITH DEFAULT NULL , 
		  "PROD_UNIT_ID_NO" VARCHAR(20 OCTETS) WITH DEFAULT NULL , 
		  "STATUS" CHAR(8 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "BASE_PART_NO" CHAR(5 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "DATA_COL_BY_QICS" CHAR(1 OCTETS) WITH DEFAULT NULL , 
		  "INSERT_LOGON_NO" CHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "UPDATE_LOGON_NO" CHAR(50 OCTETS) WITH DEFAULT NULL , 
		  "UNIT_OP_DESC_TEXT" VARCHAR(254 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "VIOS    "."PALSQ1" PCTFREE 0;

COMMENT ON TABLE "VIOS    "."PALSQ1" IS 'PDDA Data for NAQ Responsibility';


-- DDL Statements for Primary Key on Table "VIOS    "."PALSQ1"

ALTER TABLE "VIOS    "."PALSQ1" 
	ADD CONSTRAINT "PALSQ1_PK" PRIMARY KEY
		("PCL_TO_QICS_SEQ");



-- DDL Statements for Indexes on Table "VIOS    "."PALSQ1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PALSQ1_I2" ON "VIOS    "."PALSQ1" 
		("PLANT_LOC_CODE" ASC,
		 "DEPT_CODE" ASC,
		 "MODEL_YEAR_DATE" ASC,
		 "VEHICLE_MODEL_CODE" ASC,
		 "PROD_ASM_LINE_NO" ASC,
		 "UNIT_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PALSQ1_TR1";

CREATE TRIGGER VIOS.PALSQ1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PALSQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PALSQ1_TR2";

CREATE TRIGGER VIOS.PALSQ1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PALSQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


