
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAMPS1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAMPS1";


CREATE TABLE "VIOS    "."PAMPS1"  (
		  "MAPPER_SOURCE_ID" INTEGER NOT NULL , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "SOURCE_NAME" VARCHAR(255 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAMPS1" IS 'RMT VIOS PID Mapping Source Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAMPS1"

ALTER TABLE "VIOS    "."PAMPS1" 
	ADD CONSTRAINT "PAMPS1_PK" PRIMARY KEY
		("MAPPER_SOURCE_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAMPS1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."XPAMPS12" ON "VIOS    "."PAMPS1" 
		("SOURCE_NAME" ASC,
		 "PLANT_LOC_CODE" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAMPS1_TR1";

CREATE TRIGGER VIOS.PAMPS1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPS1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAMPS1_TR2";

CREATE TRIGGER VIOS.PAMPS1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPS1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


