
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAMPL1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAMPL1";


CREATE TABLE "VIOS    "."PAMPL1"  (
		  "MAPPER_MATRIX_ID" INTEGER NOT NULL , 
		  "MAPPER_TYPE_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "SOURCE_VALUE_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "TARGET_VALUE_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAMPL1" IS 'RMT VIOS PID Mapping Matrix Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAMPL1"

ALTER TABLE "VIOS    "."PAMPL1" 
	ADD CONSTRAINT "PAMPL1_PK" PRIMARY KEY
		("MAPPER_MATRIX_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAMPL1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."PAMPL1_I2" ON "VIOS    "."PAMPL1" 
		("MAPPER_TYPE_ID" ASC,
		 "SOURCE_VALUE_ID" ASC,
		 "TARGET_VALUE_ID" ASC,
		 "PLANT_LOC_CODE" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAMPL1_TR1";

CREATE TRIGGER VIOS.PAMPL1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAMPL1_TR2";

CREATE TRIGGER VIOS.PAMPL1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


