
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAPID1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAPID1";


CREATE TABLE "VIOS    "."PAPID1"  (
		  "PART_IDENTIFICATION_ID" INTEGER NOT NULL , 
		  "PART_NO" CHAR(18 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "STRUCTURE_LENGTH" SMALLINT , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "PART_CODE" VARCHAR(255 OCTETS) , 
		  "PART_DESC" VARCHAR(255 OCTETS) , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DISPLAY_TYPE" CHAR(50 OCTETS) , 
		  "PART_CODE_LOCATOR" VARCHAR(255 OCTETS) , 
		  "STATION_ADDRESS" VARCHAR(255 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAPID1" IS 'RMT VIOS Part Identification Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAPID1"

ALTER TABLE "VIOS    "."PAPID1" 
	ADD CONSTRAINT "PAPID1_PK" PRIMARY KEY
		("PART_IDENTIFICATION_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAPID1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."PAPID1_I2" ON "VIOS    "."PAPID1" 
		("PART_NO" ASC,
		 "MODEL_YEAR_DATE" ASC,
		 "VEHICLE_MODEL_CODE" ASC,
		 "PLANT_LOC_CODE" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPID1_TR1";

CREATE TRIGGER VIOS.PAPID1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPID1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPID1_TR2";

CREATE TRIGGER VIOS.PAPID1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPID1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


