
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAPIK1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAPIK1";


CREATE TABLE "VIOS    "."PAPIK1"  (
		  "PID_PART_MASK_ID" INTEGER NOT NULL , 
		  "PART_IDENTIFICATION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MAPPER_TYPE_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "MASK_POSITION" SMALLINT , 
		  "MASK_LENGTH" SMALLINT , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAPIK1" IS 'RMT VIOS PID Mask Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAPIK1"

ALTER TABLE "VIOS    "."PAPIK1" 
	ADD CONSTRAINT "PAPIK1_PK" PRIMARY KEY
		("PID_PART_MASK_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAPIK1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."PAPIK1_I2" ON "VIOS    "."PAPIK1" 
		("PART_IDENTIFICATION_ID" ASC,
		 "MAPPER_TYPE_ID" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPIK1_TR1";

CREATE TRIGGER VIOS.PAPIK1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPIK1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPIK1_TR2";

CREATE TRIGGER VIOS.PAPIK1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPIK1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


