
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAPIA1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAPIA1";


CREATE TABLE "VIOS    "."PAPIA1"  (
		  "PID_PART_MASK_APP_ID" INTEGER NOT NULL , 
		  "PID_PART_MASK_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "MASK_CODE" VARCHAR(255 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAPIA1" IS 'RMT VIOS PID Part Masking for Application Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAPIA1"

ALTER TABLE "VIOS    "."PAPIA1" 
	ADD CONSTRAINT "PAPIA1_PK" PRIMARY KEY
		("PID_PART_MASK_APP_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAPIA1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."PAPIA1_I2" ON "VIOS    "."PAPIA1" 
		("PID_PART_MASK_ID" ASC,
		 "MASK_CODE" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPIA1_TR1";

CREATE TRIGGER VIOS.PAPIA1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPIA1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPIA1_TR2";

CREATE TRIGGER VIOS.PAPIA1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPIA1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


