
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PAPLL1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PAPLL1";


CREATE TABLE "VIOS    "."PAPLL1"  (
		  "PID_IMAGE_ID" INTEGER NOT NULL , 
		  "PART_IDENTIFICATION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "IMAGE_TYPE" SMALLINT , 
		  "IMAGE" BLOB(3145728) LOGGED NOT COMPACT , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) , 
		  "MAINT_DATE" TIMESTAMP , 
		  "IMAGE_NAME" VARCHAR(255 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PAPLL1" IS 'RMT VIOS PID Image Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PAPLL1"

ALTER TABLE "VIOS    "."PAPLL1" 
	ADD CONSTRAINT "PAPLL1_PK" PRIMARY KEY
		("PID_IMAGE_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PAPLL1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."PAPLL1_I2" ON "VIOS    "."PAPLL1" 
		("PART_IDENTIFICATION_ID" ASC,
		 "IMAGE_NAME" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPLL1_TR1";

CREATE TRIGGER VIOS.PAPLL1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPLL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PAPLL1_TR2";

CREATE TRIGGER VIOS.PAPLL1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPLL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


