------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."PART";


CREATE TABLE "LCVINBOM  "."PART"  (
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "BASE_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "EFFECTIVE_BEGIN_DATE" DATE NOT NULL , 
		  "EFFECTIVE_END_DATE" DATE NOT NULL , 
		  "DESCRIPTION"  VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."PART" IS 'VIN-BOM Contains the LET Systems and Part Numbers for LET BOM';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."PART"

ALTER TABLE "LCVINBOM  "."PART" 
	ADD CONSTRAINT "PART_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE","LET_SYSTEM_NAME","DC_PART_NUMBER");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."PART_TR1";

CREATE TRIGGER LCVINBOM.PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."PART_TR2";

CREATE TRIGGER LCVINBOM.PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;