CREATE TABLE "GALADM"."PART_LINK_TBX" (
		 "PARENT_PART_NAME" CHAR(32 OCTETS) NOT NULL ,
		 "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL ,
		 "CHILD_PART_NAME" CHAR(32 OCTETS) NOT NULL,
		 "CREATE_TIMESTAMP" TIMESTAMP , 
		 "UPDATE_TIMESTAMP" TIMESTAMP)
		DATA CAPTURE CHANGES
		IN "GALTBSREF11" INDEX IN "GALTBSIDX4"
		ORGANIZE BY ROW;
		
COMMENT ON TABLE "GALADM "."PART_LINK_TBX" IS 'Part Linkage for Enhanced Repair';

-- DDL Statements for Primary Key on Table "GALADM  "."PART_LINK_TBX"

ALTER TABLE "GALADM "."PART_LINK_TBX" 
	ADD CONSTRAINT "PART_LINK_PK" PRIMARY KEY
		("PARENT_PART_NAME",
		 "PRODUCT_SPEC_CODE",
		 "CHILD_PART_NAME");



