
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PART_SPEC_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PART_SPEC_TBX";


CREATE TABLE "GALADM  "."PART_SPEC_TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PART_ID" CHAR(5 OCTETS) NOT NULL , 
		  "PART_COLOR_CODE" CHAR(11 OCTETS), 
		  "PART_DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "PART_SERIAL_NUMBER_MASK" VARCHAR(255 OCTETS) , 
		  "PART_MAX_ATTEMPTS" INTEGER , 
		  "MEASUREMENT_COUNT" INTEGER , 
		  "ENTRY_TIMESTAMP" TIMESTAMP , 
		  "COMMENT" VARCHAR(256 OCTETS) WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PART_MARK" VARCHAR(255 OCTETS) , 
		  "PART_NUMBER" CHAR(30 OCTETS) , 
		  "DISPLAY_TYPE" CHAR(50 OCTETS) , 
		  "PARSE_STRATEGY" VARCHAR(32 OCTETS) , 
		  "PARSE_INFORMATION" VARCHAR(64 OCTETS) , 
		  "IMAGE_ID" INTEGER , 
		  "SCAN_COUNT" INTEGER )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PART_SPEC_TBX" IS 'RMT PartSpec for LOT CONTROL to define Installed Part Spec';


-- DDL Statements for Primary Key on Table "GALADM  "."PART_SPEC_TBX"

ALTER TABLE "GALADM  "."PART_SPEC_TBX" 
	ADD CONSTRAINT "PARTSPECPK" PRIMARY KEY
		("PART_NAME",
		 "PART_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_SPEC_TR1";

CREATE TRIGGER GALADM.PART_SPEC_TR1 NO CASCADE BEFORE INSERT ON GALADM.PART_SPEC_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_SPEC_TR2";

CREATE TRIGGER GALADM.PART_SPEC_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PART_SPEC_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


