
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PART_LOT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PART_LOT_TBX";


CREATE TABLE "GALADM  "."PART_LOT_TBX"  (
		  "PART_SERIAL_NUMBER" CHAR(30 OCTETS) NOT NULL , 
		  "PART_NUMBER" CHAR(30 OCTETS) NOT NULL , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "STATUS" SMALLINT WITH DEFAULT 0 , 
		  "STARTING_QUANTITY" INTEGER WITH DEFAULT 0 , 
		  "CURRENT_QUANTITY" INTEGER WITH DEFAULT 0 , 
		  "COMMENT" VARCHAR(256 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PART_LOT_TBX" IS 'RMT PartLot for tracking quantity of parts installed from a lot';


-- DDL Statements for Primary Key on Table "GALADM  "."PART_LOT_TBX"

ALTER TABLE "GALADM  "."PART_LOT_TBX" 
	ADD CONSTRAINT "PART_LOT_PK" PRIMARY KEY
		("PART_SERIAL_NUMBER",
		 "PART_NAME",
		 "PART_NUMBER");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_LOT_TR1";

CREATE TRIGGER GALADM.PART_LOT_TR1 NO CASCADE BEFORE INSERT ON GALADM.PART_LOT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_LOT_TR2";

CREATE TRIGGER GALADM.PART_LOT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PART_LOT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


