
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PART_SHIPMENT_PRODUCTS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PART_SHIPMENT_PRODUCTS_TBX";


CREATE TABLE "GALADM  "."PART_SHIPMENT_PRODUCTS_TBX"  (
		  "SHIPMENT_ID" INTEGER NOT NULL , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "UPDATE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "BUILD_STATUS" INTEGER )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."PART_SHIPMENT_PRODUCTS_TBX"

ALTER TABLE "GALADM  "."PART_SHIPMENT_PRODUCTS_TBX" 
	ADD CONSTRAINT "PART_SHIPMENT_PK" PRIMARY KEY
		("SHIPMENT_ID",
		 "PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_SHIPMENT_PRODUCTS_TR1";

CREATE TRIGGER GALADM.PART_SHIPMENT_PRODUCTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PART_SHIPMENT_PRODUCTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PART_SHIPMENT_PRODUCTS_TR2";

CREATE TRIGGER GALADM.PART_SHIPMENT_PRODUCTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PART_SHIPMENT_PRODUCTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


