
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PCLPR1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PCLPR1";


CREATE TABLE "VIOS    "."PCLPR1"  (
		  "APVD_PROC_MAINT_ID" INTEGER NOT NULL , 
		  "TEAM_ID" INTEGER NOT NULL , 
		  "MPTAG_ID" INTEGER NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "ASM_PROC_SEQ_NO" SMALLINT NOT NULL , 
		  "ASM_PROC_NO" CHAR(5 OCTETS) NOT NULL , 
		  "ASM_PROC_NAME" CHAR(35 OCTETS) NOT NULL , 
		  "ROTATION" CHAR(1 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."PCLPR1"

ALTER TABLE "VIOS    "."PCLPR1" 
	ADD CONSTRAINT "PCLPR1_PK" PRIMARY KEY
		("APVD_PROC_MAINT_ID",
		 "TEAM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLPR1_TR1";

CREATE TRIGGER VIOS.PCLPR1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLPR1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLPR1_TR2";

CREATE TRIGGER VIOS.PCLPR1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLPR1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


