
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PCLTM1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PCLTM1";


CREATE TABLE "VIOS    "."PCLTM1"  (
		  "TEAM_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "EFF_BEG_DATE" DATE NOT NULL , 
		  "EFF_END_DATE" DATE NOT NULL , 
		  "PROD_RATE_ID" INTEGER NOT NULL , 
		  "TEAM_SEQ_NO" SMALLINT NOT NULL , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."PCLTM1"

ALTER TABLE "VIOS    "."PCLTM1" 
	ADD CONSTRAINT "PCLTM1_PK" PRIMARY KEY
		("TEAM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLTM1_TR1";

CREATE TRIGGER VIOS.PCLTM1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLTM1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLTM1_TR2";

CREATE TRIGGER VIOS.PCLTM1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLTM1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


