
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PCLUN1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PCLUN1";


CREATE TABLE "VIOS    "."PCLUN1"  (
		  "UNIT_REC_ID" INTEGER NOT NULL , 
		  "APVD_UNIT_MAINT_ID" INTEGER NOT NULL , 
		  "APVD_PROC_MAINT_ID" INTEGER NOT NULL , 
		  "TEAM_ID" INTEGER NOT NULL , 
		  "UNIT_SEQ_NO" SMALLINT NOT NULL , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL , 
		  "UNIT_OP_DESC_TEXT" CHAR(254 OCTETS) NOT NULL , 
		  "JOINT_TYPE" CHAR(1 OCTETS) , 
		  "TORQUE_CHAR_VALUE" CHAR(3 OCTETS) NOT NULL , 
		  "MAX_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "MIN_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "STATUS" CHAR(8 OCTETS) NOT NULL , 
		  "ADDED_DATE" TIMESTAMP NOT NULL , 
		  "PROD_UNIT_ID_NO" VARCHAR(20 OCTETS) , 
		  "ACCEPTED_LOGON_ID" CHAR(8 OCTETS) , 
		  "ACCEPTED_DATE" TIMESTAMP , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "WORK_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "QLTY_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."PCLUN1"

ALTER TABLE "VIOS    "."PCLUN1" 
	ADD CONSTRAINT "PCLUN1_PK" PRIMARY KEY
		("UNIT_REC_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLUN1_TR1";

CREATE TRIGGER VIOS.PCLUN1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLUN1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PCLUN1_TR2";

CREATE TRIGGER VIOS.PCLUN1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLUN1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


