
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PLC_DATA_COLLECT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PLC_DATA_COLLECT_TBX";


CREATE TABLE "GALADM  "."PLC_DATA_COLLECT_TBX"  (
		  "ROBOT_ID" VARCHAR(50 OCTETS) NOT NULL , 
		  "DATASET_DATATIME" VARCHAR(50 OCTETS) , 
		  "IP_ADDRESS" VARCHAR(50 OCTETS) NOT NULL , 
		  "PROGRAM_EXECUTED" VARCHAR(50 OCTETS) , 
		  "SYSTEM_TIME" INTEGER , 
		  "CYCLE_TIME" REAL , 
		  "GROUP_NUMBER" SMALLINT , 
		  "GROUP_AXES" SMALLINT , 
		  "GROUP_TYPE" SMALLINT , 
		  "GROUP_ID" SMALLINT , 
		  "J1" INTEGER , 
		  "J2" INTEGER , 
		  "J3" INTEGER , 
		  "J4" INTEGER , 
		  "J5" INTEGER , 
		  "J6" INTEGER , 
		  "J7" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSDAT3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."PLC_DATA_COLLECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."PLC_DATA_COLLECT_PK" ON "GALADM  "."PLC_DATA_COLLECT_TBX" 
		("ROBOT_ID" ASC,
		 "IP_ADDRESS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."PLC_DATA_COLLECT_TBX"

ALTER TABLE "GALADM  "."PLC_DATA_COLLECT_TBX" 
	ADD CONSTRAINT "PLC_DATA_COLLECT_PK" PRIMARY KEY
		("ROBOT_ID",
		 "IP_ADDRESS");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PLC_DATA_COLLECT_TR1";

CREATE TRIGGER GALADM.PLC_DATA_COLLECT_TR1 NO CASCADE BEFORE INSERT ON GALADM.PLC_DATA_COLLECT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PLC_DATA_COLLECT_TR2";

CREATE TRIGGER GALADM.PLC_DATA_COLLECT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PLC_DATA_COLLECT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


