
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PLC_MEMORY_MAP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PLC_MEMORY_MAP_TBX";


CREATE TABLE "GALADM  "."PLC_MEMORY_MAP_TBX"  (
		  "METRIC" VARCHAR(160 OCTETS) NOT NULL , 
		  "DATA_TYPE" CHAR(30 OCTETS) , 
		  "MEMORY_BANK" CHAR(30 OCTETS) , 
		  "START_ADDRESS" CHAR(30 OCTETS) , 
		  "BIT" CHAR(30 OCTETS) , 
		  "BYTE_ORDER" CHAR(30 OCTETS) , 
		  "LENGTH" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PLC_MEMORY_MAP_TBX" IS 'RMT PlcMemoryMapItem for LOT CONTROL to manage PLC Memory Map';


-- DDL Statements for Primary Key on Table "GALADM  "."PLC_MEMORY_MAP_TBX"

ALTER TABLE "GALADM  "."PLC_MEMORY_MAP_TBX" 
	ADD CONSTRAINT "HMIN_MEM_PK" PRIMARY KEY
		("METRIC");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PLC_MEMORY_MAP_TR1";

CREATE TRIGGER GALADM.PLC_MEMORY_MAP_TR1 NO CASCADE BEFORE INSERT ON GALADM.PLC_MEMORY_MAP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PLC_MEMORY_MAP_TR2";

CREATE TRIGGER GALADM.PLC_MEMORY_MAP_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PLC_MEMORY_MAP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


