
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PROCESS_ASSIGNMENT_DETAIL"
------------------------------------------------
 
DROP TABLE "VIOS    "."PROCESS_ASSIGNMENT_DETAIL";


CREATE TABLE "VIOS    "."PROCESS_ASSIGNMENT_DETAIL"  (
		  "MANPOWER_ASSIGNMENT_ID" BIGINT NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "PROCESS_NO" CHAR(5 OCTETS) NOT NULL , 
		  "PROCESS_NAME" VARCHAR(35 OCTETS) NOT NULL , 
		  "VMC" CHAR(1 OCTETS) NOT NULL , 
		  "VMC_DESC" VARCHAR(35 OCTETS) NOT NULL , 
		  "MODEL_YEAR" CHAR(4 OCTETS) NOT NULL , 
		  "PRODUCTION_SCHEDULE_QTY" INTEGER NOT NULL , 
		  "EFF_BEGIN_DATE" TIMESTAMP NOT NULL , 
		  "EFF_END_DATE" TIMESTAMP NOT NULL , 
		  "DAYS_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "LAST_UPDATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "PROCESS_ID" BIGINT NOT NULL , 
		  "PDDA_PROCESS_ID" BIGINT , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."PROCESS_ASSIGNMENT_DETAIL"

ALTER TABLE "VIOS    "."PROCESS_ASSIGNMENT_DETAIL" 
	ADD CONSTRAINT "PROCESS_ASSIGNMENT_DETAIL_PK" PRIMARY KEY
		("MANPOWER_ASSIGNMENT_ID",
		 "PROCESS_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PROCESS_ASSIGNMENT_DETAIL_TR1";

CREATE TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR1 NO CASCADE BEFORE INSERT
ON VIOS.PROCESS_ASSIGNMENT_DETAIL REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."PROCESS_ASSIGNMENT_DETAIL_TR2";

CREATE TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR2 NO CASCADE BEFORE UPDATE
ON VIOS.PROCESS_ASSIGNMENT_DETAIL REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


