
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_SPEC_CODE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_SPEC_CODE_TBX";


CREATE TABLE "GALADM  "."PRODUCT_SPEC_CODE_TBX"  (
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) NOT NULL , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) , 
		  "MODEL_CODE" CHAR(3 OCTETS) , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) , 
		  "INT_COLOR_CODE" CHAR(3 OCTETS) , 
		  "MODEL_YEAR_DESCRIPTION" CHAR(4 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_SPEC_CODE_TBX" IS 'RMT ProductTypeData for defining the different product types';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_SPEC_CODE_TBX"

ALTER TABLE "GALADM  "."PRODUCT_SPEC_CODE_TBX" 
	ADD CONSTRAINT "PRODUCT_SPEC_CODE_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE",
		 "PRODUCT_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SPEC_CODE_TR1";

CREATE TRIGGER GALADM.PRODUCT_SPEC_CODE_TR1 NO CASCADE BEFORE INSERT ON
GALADM.PRODUCT_SPEC_CODE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SPEC_CODE_TR2";

CREATE TRIGGER GALADM.PRODUCT_SPEC_CODE_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.PRODUCT_SPEC_CODE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


