
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_ID_MASK_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_ID_MASK_TBX";


CREATE TABLE "GALADM  "."PRODUCT_ID_MASK_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) NOT NULL , 
		  "PRODUCT_ID_MASK" CHAR(17 OCTETS) NOT NULL , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_ID_MASK_TBX" IS 'Table to store the Map between productIdMask and productSpecCode for a Prcess point';


-- DDL Statements for Indexes on Table "GALADM  "."PRODUCT_ID_MASK_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."PRODUCT_ID_MASKI1" ON "GALADM  "."PRODUCT_ID_MASK_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PRODUCT_TYPE" ASC,
		 "PRODUCT_ID_MASK" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_ID_MASK_TBX"

ALTER TABLE "GALADM  "."PRODUCT_ID_MASK_TBX" 
	ADD CONSTRAINT "PRODUCT_ID_MASK_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCT_TYPE",
		 "PRODUCT_ID_MASK");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_ID_MASK_TR1";

CREATE TRIGGER GALADM.PRODUCT_ID_MASK_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_ID_MASK_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_ID_MASK_TR2";

CREATE TRIGGER GALADM.PRODUCT_ID_MASK_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_ID_MASK_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


