
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_TYPE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_TYPE_TBX";


CREATE TABLE "GALADM  "."PRODUCT_TYPE_TBX"  (
		  "PRODUCT_TYPE" CHAR(10 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE_LABEL" CHAR(30 OCTETS) , 
		  "PRODUCT_SPEC_CODE_FORMAT" VARCHAR(256 OCTETS) , 
		  "PRODUCT_SPEC_CODE_LABEL" CHAR(30 OCTETS) WITH DEFAULT 'MTO' , 
		  "OWNER_PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "PRODUCT_ID_LABEL" CHAR(30 OCTETS) , 
		  "PRODUCT_ID_FORMAT" VARCHAR(255 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) WITH DEFAULT 'AUTOMOBILE' 
		  )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_TYPE_TBX" IS 'RMT ProductTypeData for defining the different product types';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_TYPE_TBX"

ALTER TABLE "GALADM  "."PRODUCT_TYPE_TBX" 
	ADD CONSTRAINT "PRODUCT_TYPE_PK" PRIMARY KEY
		("PRODUCT_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_TYPE_TR1";

CREATE TRIGGER GALADM.PRODUCT_TYPE_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_TYPE_TR2";

CREATE TRIGGER GALADM.PRODUCT_TYPE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


