
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX";


CREATE TABLE "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX"  (
		  "TRACKING_STATUS" CHAR(16 OCTETS) NOT NULL , 
		  "TRACKING_SEQUENCE_NO" DOUBLE NOT NULL , 
		  "ORDER_NO" CHAR(20 OCTETS) , 
		  "PRODUCT_ID" CHAR(17 OCTETS) , 
		  "PLAN_TIMESTAMP" TIMESTAMP , 
		  "FORECAST_TIMESTAMP" TIMESTAMP , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "PLAN_STATUS_ID" INTEGER , 
		  "CONTAINER_ID" CHAR(17 OCTETS) , 
		  "CONTAINER_POS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX" IS 'RMT ProductPriorityPlan for LINE to manage sequence of product orders for a given tracking line';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX"

ALTER TABLE "GALADM  "."PRODUCT_PRIORITY_PLAN_TBX" 
	ADD CONSTRAINT "PRODUCT_PRIORITY_PLAN_PK" PRIMARY KEY
		("TRACKING_STATUS",
		 "TRACKING_SEQUENCE_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_PRIORITY_PLAN_TR1";

CREATE TRIGGER GALADM.PRODUCT_PRIORITY_PLAN_TR1 NO CASCADE BEFORE INSERT
ON GALADM.PRODUCT_PRIORITY_PLAN_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_PRIORITY_PLAN_TR2";

CREATE TRIGGER GALADM.PRODUCT_PRIORITY_PLAN_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.PRODUCT_PRIORITY_PLAN_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


