
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX";


CREATE TABLE "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX"  (
		  "MAIN_NO" CHAR(5 OCTETS) NOT NULL , 
		  "PRODUCT_ID_DEF" CHAR(24 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX" IS 'MBPN Type to Number Def';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX"

ALTER TABLE "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TBX" 
	ADD CONSTRAINT "PRODUCT_TYPE_TO_NUMBER_DEF_PK" PRIMARY KEY
		("MAIN_NO",
		 "PRODUCT_ID_DEF");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TR1";

CREATE TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."PRODUCT_TYPE_TO_NUMBER_DEF_TR2";

CREATE TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


