
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_SHIPPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_SHIPPING_TBX";


CREATE TABLE "GALADM  "."PRODUCT_SHIPPING_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) NOT NULL , 
		  "TRAILER_NUMBER" CHAR(10 OCTETS) , 
		  "DUNNAGE" VARCHAR(20 OCTETS) 
		  "SHIP_DATE" DATE , 
		  "TRAILER_STATUS" SMALLINT ,
		  "TRACKING_STATUS" CHAR(10 OCTETS) ,
		  "PROCESS_POINT_ID" CHAR(10 OCTETS) ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_SHIPPING_TBX"

ALTER TABLE "GALADM  "."PRODUCT_SHIPPING_TBX" 
	ADD CONSTRAINT "PRODUCT_SHIPPING_PK" PRIMARY KEY
		("PRODUCT_ID","TRAILER_NUMBER","PROCESS_POINT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SHIPPING_TR1";

CREATE TRIGGER GALADM.PRODUCT_SHIPPING_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_SHIPPING_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SHIPPING_TR2";

CREATE TRIGGER GALADM.PRODUCT_SHIPPING_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_SHIPPING_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


