
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_ATTRIBUTES_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_ATTRIBUTES_TBX";


CREATE TABLE "GALADM  "."PRODUCT_ATTRIBUTES_TBX"  (
		  "PRODUCT_ID" VARCHAR(255 OCTETS) NOT NULL , 
		  "ATTRIBUTE" CHAR(32 OCTETS) NOT NULL , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "ATTRIBUTE_VALUE" VARCHAR(512 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."PRODUCT_ATTRIBUTES_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."PRODUCT_ATTRIBUTES_TBX" IS 'RMT ProductAttributes';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_ATTRIBUTES_TBX"

ALTER TABLE "GALADM  "."PRODUCT_ATTRIBUTES_TBX" 
	ADD CONSTRAINT "PRODUCT_ATTRIBUTES_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "ATTRIBUTE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_ATTRIBUTES_TR1";

CREATE TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_ATTRIBUTES_TR2";

CREATE TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


