
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_SEQUENCE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_SEQUENCE_TBX";


CREATE TABLE "GALADM  "."PRODUCT_SEQUENCE_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "REFERENCE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "SEQUENCE_NUMBER" INTEGER , 
		  "SOURCE_SYSTEM_ID" VARCHAR(64 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_SEQUENCE_TBX" IS 'RMT ProductSequence';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_SEQUENCE_TBX"

ALTER TABLE "GALADM  "."PRODUCT_SEQUENCE_TBX" 
	ADD CONSTRAINT "PRODUCT_SEQUENCEPK" PRIMARY KEY
		("PRODUCT_ID",
		 "PROCESS_POINT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."PRODUCT_SEQUENCE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."PRODUCT_SEQUENCE_I1" ON "GALADM  "."PRODUCT_SEQUENCE_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "SEQUENCE_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SEQUENCE_TR1";

CREATE TRIGGER GALADM.PRODUCT_SEQUENCE_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_SEQUENCE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_SEQUENCE_TR2";

CREATE TRIGGER GALADM.PRODUCT_SEQUENCE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_SEQUENCE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


