
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_CARRIER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCT_CARRIER_TBX";


CREATE TABLE "GALADM  "."PRODUCT_CARRIER_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "CARRIER_ID" CHAR(10 OCTETS) NOT NULL , 
		  "ON_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "OFF_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PRODUCT_CARRIER_TBX" IS 'RMT Product to Carrier Association';


-- DDL Statements for Indexes on Table "GALADM  "."PRODUCT_CARRIER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."PRODUCT_CARRIER_I1" ON "GALADM  "."PRODUCT_CARRIER_TBX" 
		("PRODUCT_ID" ASC,
		 "CARRIER_ID" ASC,
		 "ON_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_CARRIER_TBX"

ALTER TABLE "GALADM  "."PRODUCT_CARRIER_TBX" 
	ADD CONSTRAINT "PRODUCT_CARRIER_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "CARRIER_ID",
		 "ON_TIMESTAMP");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_CARRIER_TR1";

CREATE TRIGGER GALADM.PRODUCT_CARRIER_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCT_CARRIER_TR2";

CREATE TRIGGER GALADM.PRODUCT_CARRIER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_CARRIER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


