DROP TRIGGER "GALADM"."PRODUCTCARRIERTR1"		
		
ALTER TABLE "GALADM"."PRODUCT_CARRIER_TBX" DROP CONSTRAINT "PRODUCT_CARRIER_PK"		
		
DROP TABLE "GALADM"."PRODUCT_CARRIER_TBX"		
		
CREATE TABLE "GALADM"."PRODUCT_CARRIER_TBX" (		
		PRODUCT_ID CHAR(17) NOT NULL,
		CARRIER_ID CHAR(10) NOT NULL,
		ON_TIMESTAMP TIMESTAMP NOT NULL,
		PROCESS_POINT_ID CHAR(16),
		OFF_TIMESTAMP TIMESTAMP,
		CREATE_TIMESTAMP TIMESTAMP,
		UPDATE_TIMESTAMP TIMESTAMP
	)	
	DATA CAPTURE NONE 	
		
ALTER TABLE "GALADM"."PRODUCT_CARRIER_TBX" ADD CONSTRAINT "PRODUCT_CARRIER_PK" PRIMARY KEY		
	("PRODUCT_ID",	
	 "CARRIER_ID",	
	 "ON_TIMESTAMP" )	
		
CREATE TRIGGER "GALADM"."PROD_CARRIER_TR1" 		
	AFTER INSERT ON "GALADM"."PRODUCT_CARRIER_TBX"	
	REFERENCING  NEW AS A	
	FOR EACH ROW MODE DB2SQL	
UPDATE "GALADM"."PRODUCT_CARRIER_TBX" SET CREATE_TIMESTAMP=CURRENT TIMESTAMP		
WHERE PRODUCT_ID= A.PRODUCT_ID AND CARRIER_ID=A.CARRIER_ID AND ON_TIMESTAMP= A.ON_TIMESTAMP		

CREATE TRIGGER "GALADM"."PROD_CARRIER_TR2" 
	NO CASCADE BEFORE UPDATE ON "GALADM"."PRODUCT_CARRIER_TBX"
	REFERENCING  NEW AS A
	FOR EACH ROW MODE DB2SQL
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;