
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PROXSCANNER_MAPPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PROXSCANNER_MAPPING_TBX";


CREATE TABLE "GALADM  "."PROXSCANNER_MAPPING_TBX"  (
		  "USER_ID" CHAR(11 OCTETS) , 
		  "CARD_NUMBER" BIGINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."PROXSCANNER_MAPPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."PROXSCANNER_MAPP_I1" ON "GALADM  "."PROXSCANNER_MAPPING_TBX" 
		("CARD_NUMBER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."PROXSCANNER_MAPPING_TBX"

ALTER TABLE "GALADM  "."PROXSCANNER_MAPPING_TBX" 
	ADD CONSTRAINT "PROXSCAN_PK" PRIMARY KEY
		("CARD_NUMBER");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PROXSCANNER_MAPPING_TR1";

CREATE TRIGGER GALADM.PROXSCANNER_MAPPING_TR1 NO CASCADE BEFORE INSERT ON
GALADM.PROXSCANNER_MAPPING_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PROXSCANNER_MAPPING_TR2";

CREATE TRIGGER GALADM.PROXSCANNER_MAPPING_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.PROXSCANNER_MAPPING_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;



