
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PUSH_TIMER_STATUS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PUSH_TIMER_STATUS_TBX";


CREATE TABLE "GALADM  "."PUSH_TIMER_STATUS_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "TERMINAL_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "PRODUCT_ID" VARCHAR(32 OCTETS) , 
		  "OPS_PLANNED" INTEGER , 
		  "OPS_COMPLETED" INTEGER , 
		  "STATUS_IN_SECS" BIGINT NOT NULL , 
		  "LAST_UPDATED" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "ASSOCIATE_NO" CHAR(11 OCTETS) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."PUSH_TIMER_STATUS_TBX" IS 'Maintains Push timer status from all VIOS clients';


-- DDL Statements for Primary Key on Table "GALADM  "."PUSH_TIMER_STATUS_TBX"

ALTER TABLE "GALADM  "."PUSH_TIMER_STATUS_TBX" 
	ADD CONSTRAINT "PUSH_TIMER_STATUS_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "TERMINAL_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PUSH_TIMER_STATUS_TR1";

CREATE TRIGGER GALADM.PUSH_TIMER_STATUS_TR1 NO CASCADE BEFORE INSERT ON
GALADM.PUSH_TIMER_STATUS_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PUSH_TIMER_STATUS_TR2";

CREATE TRIGGER GALADM.PUSH_TIMER_STATUS_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.PUSH_TIMER_STATUS_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


