
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVCFR1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVCFR1";


CREATE TABLE "VIOS    "."PVCFR1"  (
		  "CHANGE_FORM_ID" INTEGER NOT NULL , 
		  "CHANGE_FORM_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL , 
		  "CONTROL_NO" INTEGER NOT NULL , 
		  "REVISION_NO" CHAR(5 OCTETS) NOT NULL , 
		  "REPORT_DATE" TIMESTAMP NOT NULL , 
		  "CHANGE_DATE" TIMESTAMP NOT NULL , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) NOT NULL , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "APVD_USER" CHAR(8 OCTETS) , 
		  "APVD_DATE" TIMESTAMP , 
		  "PRINTED_LOGON_ID" CHAR(8 OCTETS) , 
		  "ASHIFT_TRAINING_DT" TIMESTAMP , 
		  "ASHIFT_REMARKS" CHAR(10 OCTETS) , 
		  "BSHIFT_TRAINING_DT" TIMESTAMP , 
		  "BSHIFT_REMARKS" CHAR(10 OCTETS) , 
		  "APV_PART_EFF_DATE" TIMESTAMP , 
		  "PPS_DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "USR_DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "PS_DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "CU_DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "SS_DOCUMENT_NO" CHAR(20 OCTETS) NOT NULL , 
		  "PPS_REVISION_NO" CHAR(10 OCTETS) NOT NULL , 
		  "USR_REVISION_NO" CHAR(10 OCTETS) NOT NULL , 
		  "PS_REVISION_NO" CHAR(10 OCTETS) NOT NULL , 
		  "CU_REVISION_NO" CHAR(10 OCTETS) NOT NULL , 
		  "SS_REVISION_NO" CHAR(10 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVCFR1" IS 'RMT VIOS ChangeForm Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVCFR1"

ALTER TABLE "VIOS    "."PVCFR1" 
	ADD CONSTRAINT "PVCFR1_PK" PRIMARY KEY
		("CHANGE_FORM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVCFR1_TR1";

CREATE TRIGGER VIOS.PVCFR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVCFR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVCFR1_TR2";

CREATE TRIGGER VIOS.PVCFR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVCFR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


