
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVCFU1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVCFU1";


CREATE TABLE "VIOS    "."PVCFU1"  (
		  "CHANGE_FORM_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "APVD_UNIT_MAINT_ID" INTEGER NOT NULL , 
		  "APVD_PROC_MAINT_ID" INTEGER NOT NULL , 
		  "ISSUED_DATE" TIMESTAMP , 
		  "ISSR_LOGON_ID" CHAR(8 OCTETS) , 
		  "ASM_PROC_NO" VARCHAR(5 OCTETS) NOT NULL , 
		  "CHANGE_DESC" VARCHAR(254 OCTETS) NOT NULL , 
		  "UNIT_NO" VARCHAR(6 OCTETS) , 
		  "PCF_IN" CHAR(1 OCTETS) NOT NULL , 
		  "USR_IN" CHAR(1 OCTETS) NOT NULL , 
		  "PPS_IN" CHAR(1 OCTETS) NOT NULL , 
		  "CU_IN" CHAR(1 OCTETS) NOT NULL , 
		  "PS_IN" CHAR(1 OCTETS) NOT NULL , 
		  "SS_IN" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVCFU1" IS 'RMT VIOS ChangeFormUnit Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVCFU1"

ALTER TABLE "VIOS    "."PVCFU1" 
	ADD CONSTRAINT "PVCFU1_PK" PRIMARY KEY
		("APVD_PROC_MAINT_ID",
		 "APVD_UNIT_MAINT_ID",
		 "CHANGE_FORM_ID");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVCFU1"

ALTER TABLE "VIOS    "."PVCFU1" 
	ADD CONSTRAINT "PVCFR1_PVCFU1_FK1" FOREIGN KEY
		("CHANGE_FORM_ID")
	REFERENCES "VIOS    "."PVCFR1"
		("CHANGE_FORM_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "VIOS    "."PVCFU1" 
	ADD CONSTRAINT "PVPMX1_PVCFU1_FK1" FOREIGN KEY
		("APVD_PROC_MAINT_ID")
	REFERENCES "VIOS    "."PVPMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "VIOS    "."PVCFU1" 
	ADD CONSTRAINT "PVUMX1_PVCFU1_FK1" FOREIGN KEY
		("APVD_UNIT_MAINT_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVCFU1_TR1";

CREATE TRIGGER VIOS.PVCFU1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVCFU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVCFU1_TR2";

CREATE TRIGGER VIOS.PVCFU1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVCFU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


