
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVDPT1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVDPT1";


CREATE TABLE "VIOS    "."PVDPT1"  (
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "SHOW_JOINT_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "SHOW_TORQUE" CHAR(1 OCTETS) NOT NULL , 
		  "SHOW_SAFETY_PT" CHAR(1 OCTETS) NOT NULL , 
		  "SHOW_IMPACT_PT" CHAR(1 OCTETS) NOT NULL , 
		  "USES_PQCT" CHAR(1 OCTETS) , 
		  "PRINT_MSDS_NO" CHAR(1 OCTETS) , 
		  "SHOW_QUALITY_ISSUE" CHAR(1 OCTETS) , 
		  "SHOW_QLTY_CTL_ITEM" CHAR(1 OCTETS) , 
		  "SHOW_TOOL" CHAR(1 OCTETS) , 
		  "PQCT_YEAR" CHAR(4 OCTETS) , 
		  "GPACV_WCH" CHAR(4 OCTETS) , 
		  "TORQUE_UOM" CHAR(2 OCTETS) , 
		  "UNIT_SHEET_TOOL" VARCHAR(254 OCTETS) , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) NOT NULL , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVDPT1" IS 'RMT VIOS DepartmentSettings Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVDPT1"

ALTER TABLE "VIOS    "."PVDPT1" 
	ADD CONSTRAINT "PVDPT1_PK" PRIMARY KEY
		("DEPT_CODE",
		 "PLANT_LOC_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVDPT1_TR1";

CREATE TRIGGER VIOS.PVDPT1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVDPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVDPT1_TR2";

CREATE TRIGGER VIOS.PVDPT1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVDPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


