
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVLPR1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVLPR1";


CREATE TABLE "VIOS    "."PVLPR1"  (
		  "PROCESS_ID" INTEGER NOT NULL , 
		  "TEAM_ID" INTEGER NOT NULL , 
		  "MPTAG_ID" INTEGER NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "ASM_PROC_SEQ_NO" SMALLINT NOT NULL , 
		  "ASM_PROC_NO" CHAR(5 OCTETS) NOT NULL , 
		  "ASM_PROC_NAME" CHAR(35 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVLPR1" IS 'RMT VIOS MdrsProcess Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVLPR1"

ALTER TABLE "VIOS    "."PVLPR1" 
	ADD CONSTRAINT "PVLPR1_PK" PRIMARY KEY
		("PROCESS_ID",
		 "TEAM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLPR1_TR1";

CREATE TRIGGER VIOS.PVLPR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLPR1_TR2";

CREATE TRIGGER VIOS.PVLPR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


