
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVLTM1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVLTM1";


CREATE TABLE "VIOS    "."PVLTM1"  (
		  "TEAM_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "EFF_BEG_DATE" DATE NOT NULL , 
		  "EFF_END_DATE" DATE NOT NULL , 
		  "PROD_RATE_ID" INTEGER NOT NULL , 
		  "TEAM_SEQ_NO" SMALLINT NOT NULL , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVLTM1" IS 'RMT VIOS MdrsTeam Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVLTM1"

ALTER TABLE "VIOS    "."PVLTM1" 
	ADD CONSTRAINT "PVLTM1_PK" PRIMARY KEY
		("TEAM_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "MODEL_YEAR_DATE",
		 "PROD_SCH_QTY",
		 "VEHICLE_MODEL_CODE",
		 "PROD_ASM_LINE_NO");



-- DDL Statements for Indexes on Table "VIOS    "."PVLTM1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVLTM1_I1" ON "VIOS    "."PVLTM1" 
		("PLANT_LOC_CODE" ASC,
		 "DEPT_CODE" ASC,
		 "MODEL_YEAR_DATE" ASC,
		 "PROD_SCH_QTY" ASC,
		 "VEHICLE_MODEL_CODE" ASC,
		 "TEAM_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLTM1_TR1";

CREATE TRIGGER VIOS.PVLTM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLTM1_TR2";

CREATE TRIGGER VIOS.PVLTM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


