
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVLUN1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVLUN1";


CREATE TABLE "VIOS    "."PVLUN1"  (
		  "UNIT_REC_ID" INTEGER NOT NULL , 
		  "UNIT_ID" INTEGER NOT NULL , 
		  "PROCESS_ID" INTEGER NOT NULL , 
		  "TEAM_ID" INTEGER NOT NULL , 
		  "UNIT_SEQ_NO" SMALLINT NOT NULL , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL , 
		  "UNIT_OP_DESC_TEXT" CHAR(254 OCTETS) NOT NULL , 
		  "JOINT_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "TORQUE_CHAR_VALUE" CHAR(3 OCTETS) NOT NULL , 
		  "MAX_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "MIN_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "STATUS" CHAR(8 OCTETS) NOT NULL , 
		  "ADDED_DATE" TIMESTAMP NOT NULL , 
		  "ACCEPTED_LOGON_ID" CHAR(8 OCTETS) NOT NULL , 
		  "ACCEPTED_DATE" TIMESTAMP NOT NULL , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "WORK_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "QLTY_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVLUN1" IS 'RMT VIOS MdrsUnit Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVLUN1"

ALTER TABLE "VIOS    "."PVLUN1" 
	ADD CONSTRAINT "PVLUN1_PK" PRIMARY KEY
		("UNIT_REC_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLUN1_TR1";

CREATE TRIGGER VIOS.PVLUN1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVLUN1_TR2";

CREATE TRIGGER VIOS.PVLUN1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


