
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVMRP1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVMRP1";


CREATE TABLE "VIOS    "."PVMRP1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "REACTION" VARCHAR(100 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVMRP1" IS 'RMT VIOS UnitReactionPlan Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVMRP1"

ALTER TABLE "VIOS    "."PVMRP1" 
	ADD CONSTRAINT "PVMRP1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "REACTION");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVMRP1"

ALTER TABLE "VIOS    "."PVMRP1" 
	ADD CONSTRAINT "PVUMX1_PVMRP1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVMRP1_TR1";

CREATE TRIGGER VIOS.PVMRP1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMRP1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVMRP1_TR2";

CREATE TRIGGER VIOS.PVMRP1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMRP1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


