
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVMSC1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVMSC1";


CREATE TABLE "VIOS    "."PVMSC1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "CONTROL_APPLIED" VARCHAR(254 OCTETS) NOT NULL , 
		  "PRINT" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVMSC1" IS 'RMT VIOS UnitSpecialControl';


-- DDL Statements for Primary Key on Table "VIOS    "."PVMSC1"

ALTER TABLE "VIOS    "."PVMSC1" 
	ADD CONSTRAINT "PVMSC1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "CONTROL_APPLIED");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVMSC1"

ALTER TABLE "VIOS    "."PVMSC1" 
	ADD CONSTRAINT "PVUMX1_PVMSC1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVMSC1_TR1";

CREATE TRIGGER VIOS.PVMSC1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMSC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVMSC1_TR2";

CREATE TRIGGER VIOS.PVMSC1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMSC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


