
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVPMU1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVPMU1";


CREATE TABLE "VIOS    "."PVPMU1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL , 
		  "UNIT_SEQ_NO" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVPMU1" IS 'RMT VIOS ProcessUnit Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVPMU1"

ALTER TABLE "VIOS    "."PVPMU1" 
	ADD CONSTRAINT "PVPMU1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "UNIT_NO",
		 "UNIT_SEQ_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVPMU1_TR1";

CREATE TRIGGER VIOS.PVPMU1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVPMU1_TR2";

CREATE TRIGGER VIOS.PVPMU1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


