
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVPMX1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVPMX1";


CREATE TABLE "VIOS    "."PVPMX1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "ASM_PROC_NO" CHAR(5 OCTETS) NOT NULL , 
		  "ASM_PROC_SEQ_NO" SMALLINT NOT NULL , 
		  "ASM_PROC_NAME" CHAR(35 OCTETS) NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL , 
		  "EFF_END_DATE" DATE NOT NULL , 
		  "EFF_BEG_DATE" DATE NOT NULL , 
		  "ADDITIONAL_COMMENT" CHAR(254 OCTETS) NOT NULL , 
		  "ADD_INFO_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "REASON_CODE_TYPE" CHAR(18 OCTETS) NOT NULL , 
		  "REASON_FOR_CHANGE" CHAR(254 OCTETS) NOT NULL , 
		  "TEAM_SEQ_NO" INTEGER NOT NULL , 
		  "TEAM_DESC" CHAR(30 OCTETS) NOT NULL , 
		  "PROCESS_LOCATION" CHAR(4 OCTETS) , 
		  "NUM_ASSOCIATES" SMALLINT NOT NULL , 
		  "ROTATION" CHAR(1 OCTETS) NOT NULL , 
		  "ACTION" CHAR(1 OCTETS) NOT NULL , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) NOT NULL , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVPMX1" IS 'RMT VIOS Process Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVPMX1"

ALTER TABLE "VIOS    "."PVPMX1" 
	ADD CONSTRAINT "PVPMX1_PK" PRIMARY KEY
		("MAINTENANCE_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PVPMX1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVPMX1_I1" ON "VIOS    "."PVPMX1" 
		("PLANT_LOC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "VIOS    "."PVPMX1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVPMX1_I2" ON "VIOS    "."PVPMX1" 
		("DEPT_CODE" ASC,
		 "PLANT_LOC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "VIOS    "."PVPMX1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVPMX1_I3" ON "VIOS    "."PVPMX1" 
		("ASM_PROC_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVPMX1_TR1";

CREATE TRIGGER VIOS.PVPMX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVPMX1_TR2";

CREATE TRIGGER VIOS.PVPMX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


