
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUML1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUML1";


CREATE TABLE "VIOS    "."PVUML1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "QUALITY_POINTS" VARCHAR(250 OCTETS) NOT NULL , 
		  "WORKING_POINTS" VARCHAR(250 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUML1" IS 'RMT VIOS UnitFmea Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUML1"

ALTER TABLE "VIOS    "."PVUML1" 
	ADD CONSTRAINT "PVUML1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "QUALITY_POINTS",
		 "WORKING_POINTS");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVUML1"

ALTER TABLE "VIOS    "."PVUML1" 
	ADD CONSTRAINT "PVUMX1_PVUML1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUML1_TR1";

CREATE TRIGGER VIOS.PVUML1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUML1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUML1_TR2";

CREATE TRIGGER VIOS.PVUML1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUML1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


