
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUMQ1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUMQ1";


CREATE TABLE "VIOS    "."PVUMQ1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "QUALITY_ISS_DESC" CHAR(20 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUMQ1" IS 'RMT VIOS UnitQualityIssue';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUMQ1"

ALTER TABLE "VIOS    "."PVUMQ1" 
	ADD CONSTRAINT "PVUMQ1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "QUALITY_ISS_DESC");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVUMQ1"

ALTER TABLE "VIOS    "."PVUMQ1" 
	ADD CONSTRAINT "PVUMX1_PVUMQ1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMQ1_TR1";

CREATE TRIGGER VIOS.PVUMQ1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMQ1_TR2";

CREATE TRIGGER VIOS.PVUMQ1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


