
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUMM1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUMM1";


CREATE TABLE "VIOS    "."PVUMM1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MOST_SEQ_NO" SMALLINT NOT NULL , 
		  "WORKING_POINT_DTL" CHAR(254 OCTETS) NOT NULL , 
		  "SHOW_ON_PRINT" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUMM1" IS 'RMT VIOS UnitMost Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUMM1"

ALTER TABLE "VIOS    "."PVUMM1" 
	ADD CONSTRAINT "PVUMM1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "MOST_SEQ_NO",
		 "WORKING_POINT_DTL");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVUMM1"

ALTER TABLE "VIOS    "."PVUMM1" 
	ADD CONSTRAINT "PVUMX1_PVUMM1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMM1_TR1";

CREATE TRIGGER VIOS.PVUMM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMM1_TR2";

CREATE TRIGGER VIOS.PVUMM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


