
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUMT1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUMT1";


CREATE TABLE "VIOS    "."PVUMT1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "MTC_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "MTC_TYPE" CHAR(3 OCTETS) NOT NULL , 
		  "MTC_OPTION" CHAR(3 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUMT1" IS 'RMT VIOS UnitModelType Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUMT1"

ALTER TABLE "VIOS    "."PVUMT1" 
	ADD CONSTRAINT "PVUMT1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "MODEL_YEAR_DATE",
		 "MTC_MODEL",
		 "MTC_TYPE",
		 "MTC_OPTION");



-- DDL Statements for Indexes on Table "VIOS    "."PVUMT1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVUMT1_I1" ON "VIOS    "."PVUMT1" 
		("MTC_MODEL" ASC,
		 "MTC_TYPE" ASC,
		 "MTC_OPTION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Foreign Keys on Table "VIOS    "."PVUMT1"

ALTER TABLE "VIOS    "."PVUMT1" 
	ADD CONSTRAINT "PVUMX1_PVUMT1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMT1_TR1";

CREATE TRIGGER VIOS.PVUMT1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMT1_TR2";

CREATE TRIGGER VIOS.PVUMT1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


