
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUMX1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUMX1";


CREATE TABLE "VIOS    "."PVUMX1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "UNIT_NO" CHAR(6 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" DECIMAL(5,1) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PROD_ASM_LINE_NO" CHAR(1 OCTETS) NOT NULL , 
		  "BASE_PART_NO" CHAR(5 OCTETS) NOT NULL , 
		  "UNIT_CREATE_DATE" TIMESTAMP NOT NULL , 
		  "MIN_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "MAX_TORQUE_VAL_QTY" DECIMAL(4,1) NOT NULL , 
		  "TORQUE_CHAR_VALUE" CHAR(3 OCTETS) NOT NULL , 
		  "JOINT_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "AUX_MTRL_DESC_TEXT" CHAR(50 OCTETS) , 
		  "TOOL" CHAR(50 OCTETS) NOT NULL , 
		  "UNIT_OP_DESC_TEXT" CHAR(254 OCTETS) NOT NULL , 
		  "UNIT_RANK" CHAR(20 OCTETS) , 
		  "AUX_MSDS_NO" CHAR(20 OCTETS) , 
		  "ACTION" CHAR(1 OCTETS) NOT NULL , 
		  "UNIT_SEQ_NO" INTEGER NOT NULL , 
		  "LINE_SPEED" DECIMAL(5,1) NOT NULL , 
		  "MAINT_LOGON_ID" CHAR(8 OCTETS) NOT NULL , 
		  "MAINT_DATE" TIMESTAMP NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "WORK_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "QLTY_PT_DESC_TEXT" VARCHAR(500 OCTETS) NOT NULL , 
		  "SAFETY_PT_DESC" VARCHAR(500 OCTETS) , 
		  "IMPACT_PT_DESC" VARCHAR(540 OCTETS) , 
		  "SAFETY_ERGO_PT" VARCHAR(500 OCTETS) , 
		  "SAFETY_ERGO_INST" VARCHAR(500 OCTETS) , 
		  "UNIT_TOT_TIME" DOUBLE NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUMX1" IS 'RMT VIOS Unit Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUMX1"

ALTER TABLE "VIOS    "."PVUMX1" 
	ADD CONSTRAINT "PVUMX1_PK" PRIMARY KEY
		("MAINTENANCE_ID");



-- DDL Statements for Indexes on Table "VIOS    "."PVUMX1"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."PVUMX1_I1" ON "VIOS    "."PVUMX1" 
		("PLANT_LOC_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMX1_TR1";

CREATE TRIGGER VIOS.PVUMX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMX1_TR2";

CREATE TRIGGER VIOS.PVUMX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


