
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUMI1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUMI1";


CREATE TABLE "VIOS    "."PVUMI1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "IMAGE_SEQ_NO" SMALLINT NOT NULL , 
		  "IMAGE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "IMAGE" BLOB(3145728) LOGGED NOT COMPACT NOT NULL , 
		  "UNIT_IMAGE" VARCHAR(508 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBS16K" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUMI1" IS 'RMT VIOS UnitImage Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUMI1"

ALTER TABLE "VIOS    "."PVUMI1" 
	ADD CONSTRAINT "PVUMI1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "IMAGE_SEQ_NO",
		 "IMAGE_TIMESTAMP");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMI1_TR1";

CREATE TRIGGER VIOS.PVUMI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUMI1_TR2";

CREATE TRIGGER VIOS.PVUMI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


