
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUPM1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUPM1";


CREATE TABLE "VIOS    "."PVUPM1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "PART_NO" CHAR(18 OCTETS) NOT NULL , 
		  "PART_SECTION_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "PART_ITEM_NO" CHAR(8 OCTETS) NOT NULL , 
		  "MTC_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "MTC_TYPE" CHAR(3 OCTETS) NOT NULL , 
		  "MTC_OPTION" CHAR(3 OCTETS) NOT NULL , 
		  "PART_QTY" SMALLINT NOT NULL , 
		  "PART_MARKING_NO" CHAR(4 OCTETS) NOT NULL , 
		  "TGT_EFF_BEG_DATE" TIMESTAMP NOT NULL , 
		  "PART_EFF_DATE" TIMESTAMP NOT NULL , 
		  "DELIVERY_LOCATION" CHAR(4 OCTETS) NOT NULL , 
		  "PART_NAME" CHAR(50 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUPM1" IS 'RMT VIOS UnitPart Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUPM1"

ALTER TABLE "VIOS    "."PVUPM1" 
	ADD CONSTRAINT "PVUPM1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "MTC_MODEL",
		 "MTC_TYPE",
		 "MTC_OPTION",
		 "PART_ITEM_NO",
		 "PART_NO",
		 "PART_SECTION_CODE",
		 "PART_QTY",
		 "PART_MARKING_NO",
		 "TGT_EFF_BEG_DATE",
		 "PART_EFF_DATE",
		 "DELIVERY_LOCATION",
		 "PART_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUPM1_TR1";

CREATE TRIGGER VIOS.PVUPM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUPM1_TR2";

CREATE TRIGGER VIOS.PVUPM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


