
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUPI1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUPI1";


CREATE TABLE "VIOS    "."PVUPI1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "IMAGE_SEQ_NO" SMALLINT NOT NULL , 
		  "IMAGE_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "PPE_ID" INTEGER NOT NULL , 
		  "PPE_REQUIRED" VARCHAR(200 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "IMAGE" BLOB(3145728) LOGGED NOT COMPACT NOT NULL , 
		  "POTENTIAL_HAZARD" VARCHAR(300 OCTETS) NOT NULL , 
		  "PPE_USAGE" VARCHAR(500 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBS16K" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUPI1" IS 'RMT VIOS UnitPpeImage Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUPI1"

ALTER TABLE "VIOS    "."PVUPI1" 
	ADD CONSTRAINT "PVUPI1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "IMAGE_SEQ_NO",
		 "PPE_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUPI1_TR1";

CREATE TRIGGER VIOS.PVUPI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUPI1_TR2";

CREATE TRIGGER VIOS.PVUPI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


