
------------------------------------------------
-- DDL Statements for Table "VIOS    "."PVUWX1"
------------------------------------------------
 
DROP TABLE "VIOS    "."PVUWX1";


CREATE TABLE "VIOS    "."PVUWX1"  (
		  "MAINTENANCE_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "CONCERN_POINT" VARCHAR(150 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."PVUWX1" IS 'RMT VIOS UnitConcernPoint Table';


-- DDL Statements for Primary Key on Table "VIOS    "."PVUWX1"

ALTER TABLE "VIOS    "."PVUWX1" 
	ADD CONSTRAINT "PVUWX1_PK" PRIMARY KEY
		("MAINTENANCE_ID",
		 "CONCERN_POINT");



-- DDL Statements for Foreign Keys on Table "VIOS    "."PVUWX1"

ALTER TABLE "VIOS    "."PVUWX1" 
	ADD CONSTRAINT "PVUMX1_PVUWX1_FK1" FOREIGN KEY
		("MAINTENANCE_ID")
	REFERENCES "VIOS    "."PVUMX1"
		("MAINTENANCE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	TRUSTED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUWX1_TR1";

CREATE TRIGGER VIOS.PVUWX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUWX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."PVUWX1_TR2";

CREATE TRIGGER VIOS.PVUWX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUWX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


