
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_BOM_PART_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_BOM_PART_TBX";


CREATE TABLE "GALADM  "."QI_BOM_PART_TBX"  (
		  "DC_PART_NO" CHAR(18 OCTETS) NOT NULL , 
		  "MODEL_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "MAIN_PART_NO" CHAR(5 OCTETS) NOT NULL , 
		  "DC_PART_NAME" VARCHAR(30 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) NOT NULL WITH DEFAULT 'AUTOMOBILE' )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_BOM_PART_TBX" IS 'NAQ BOM Part';


-- DDL Statements for Indexes on Table "GALADM  "."QI_BOM_PART_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_BOM_PART_I1" ON "GALADM  "."QI_BOM_PART_TBX" 
		("PRODUCT_KIND" ASC,
		 "DC_PART_NO" ASC,
		 "MODEL_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_BOM_PART_TBX"

ALTER TABLE "GALADM  "."QI_BOM_PART_TBX" 
	ADD CONSTRAINT "QI_BOM_PART_PK" PRIMARY KEY
		("PRODUCT_KIND",
		 "DC_PART_NO",
		 "MODEL_CODE");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_BOM_PART_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_BOM_PART_TBX" 
	ADD CONSTRAINT "QI_BOM_PART_C1" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_BOM_PART_TR1";

CREATE TRIGGER GALADM.QI_BOM_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_BOM_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_BOM_PART_TR2";

CREATE TRIGGER GALADM.QI_BOM_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_BOM_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


