
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_DEFECT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_DEFECT_TBX";


CREATE TABLE "GALADM  "."QI_DEFECT_TBX"  (
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) NOT NULL , 
		  "DEFECT_TYPE_DESCRIPTION_SHORT" VARCHAR(10 OCTETS) , 
		  "DEFECT_TYPE_DESCRIPTION_LONG" VARCHAR(30 OCTETS) , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) , 
		  "DEFECT_CATEGORY_NAME" VARCHAR(32 OCTETS) , 
		  "PRIMARY_POSITION" SMALLINT , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) , 
		  "APP_CREATE_TIMESTAMP" TIMESTAMP , 
		  "APP_UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_DEFECT_TBX" IS 'NAQ Defect';


-- DDL Statements for Indexes on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_DEFECT_I1" ON "GALADM  "."QI_DEFECT_TBX" 
		("DEFECT_TYPE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_DEFECT_TBX"

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_PK" PRIMARY KEY
		("DEFECT_TYPE_NAME");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C1" CHECK 
		(DEFECT_TYPE_NAME = UPPER(DEFECT_TYPE_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C2" CHECK 
		(DEFECT_TYPE_DESCRIPTION_SHORT = UPPER(DEFECT_TYPE_DESCRIPTION_SHORT))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C3" CHECK 
		(DEFECT_TYPE_DESCRIPTION_LONG = UPPER(DEFECT_TYPE_DESCRIPTION_LONG))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C4" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C5" CHECK 
		(DEFECT_CATEGORY_NAME = UPPER(DEFECT_CATEGORY_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C6" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C7" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_DEFECT_TR1";

CREATE TRIGGER GALADM.QI_DEFECT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_DEFECT_TR2";

CREATE TRIGGER GALADM.QI_DEFECT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


