------------------------------------------------
-- DDL Statements for Table "GALADM"."QI_DEFECT_IQS_SCORE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM"."QI_DEFECT_IQS_SCORE_TBX";


CREATE TABLE "GALADM"."QI_DEFECT_IQS_SCORE_TBX"  (
		  "DEFECTRESULTID" BIGINT NOT NULL, 
		  "IQS_SCORE" DECIMAL(5,2),
		  "IQS_AUDIT_ACTION" SMALLINT NOT NULL WITH DEFAULT 0,
		  "CREATE_TIMESTAMP" TIMESTAMP, 
		  "UPDATE_TIMESTAMP" TIMESTAMP 
		   )
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM"."QI_DEFECT_IQS_SCORE_TBX" IS 'Defect IQS Score';

-- DDL Statements for Indexes on Table "GALADM  "."QI_DEFECT_IQS_SCORE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM"."QI_DEFECT_IQS_SCORE_I1" ON "GALADM"."QI_DEFECT_IQS_SCORE_TBX" 
		("DEFECTRESULTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Primary Key on Table "QI_DEFECT_IQS_SCORE_TBX"

ALTER TABLE "GALADM"."QI_DEFECT_IQS_SCORE_TBX" 
	ADD CONSTRAINT "QI_DEFECT_IQS_SCORE_PK" PRIMARY KEY
		("DEFECTRESULTID");

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM"."QI_DEFECT_IQS_SCORE_TR1";

CREATE TRIGGER GALADM.QI_DEFECT_IQS_SCORE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_IQS_SCORE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM"."QI_DEFECT_IQS_SCORE_TR2";

CREATE TRIGGER GALADM.QI_DEFECT_IQS_SCORE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_IQS_SCORE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
