
------------------------------------------------
-- DDL Statements for Table "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX"
------------------------------------------------
 
DROP TABLE "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX";


CREATE TABLE "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX"  (
		  "QFS_DEFECT_NO" INTEGER NOT NULL , 
		  "SITE" CHAR(16 OCTETS) NOT NULL , 
		  "ASSOCIATE_ID" CHAR(7 OCTETS) NOT NULL , 
		  "STATUS" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

ALTER TABLE "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX" PCTFREE 0;

COMMENT ON TABLE "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX" IS 'NAQ Responsible Associate Data for MDRS';


-- DDL Statements for Indexes on Table "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_I1" ON "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX" 
		("QFS_DEFECT_NO" ASC,
		 "SITE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX"

ALTER TABLE "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TBX" 
	ADD CONSTRAINT "QI_DEFECT_RESP_ASSOCIATE_PK" PRIMARY KEY
		("QFS_DEFECT_NO",
		 "SITE");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TR1";

CREATE TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."QI_DEFECT_RESP_ASSOCIATE_TR2";

CREATE TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


