
------------------------------------------------
-- DDL Statements for Table "GALADM"."QI_DEFECT_DEVICE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM"."QI_DEFECT_DEVICE_TBX";


CREATE TABLE "GALADM"."QI_DEFECT_DEVICE_TBX"  (
		  "DEFECTRESULTID" BIGINT NOT NULL, 
		  "DEVICE_ID" VARCHAR(32 OCTETS) ,
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP 
		   )
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM"."QI_DEFECT_DEVICE_TBX" IS 'Defect Device Association ';


-- DDL Statements for Primary Key on Table "QI_DEFECT_DEVICE_TBX"

ALTER TABLE "GALADM"."QI_DEFECT_DEVICE_TBX" 
	ADD CONSTRAINT "QI_DEFECT_DEVICE_PK" PRIMARY KEY
		("DEFECTRESULTID");

		
-- DDL Statements for Indexes on Table "GALADM"."QI_DEFECT_DEVICE_TBX"

CREATE UNIQUE INDEX "GALADM"."QI_DEFECT_DEVICE_I1" ON "GALADM"."QI_DEFECT_DEVICE_TBX"
(
   "DEFECTRESULTID",
   "DEVICE_ID",
   "ACTUAL_TIMESTAMP"
)
;



-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_DEFECT_DEVICE_TR1";

CREATE TRIGGER GALADM.QI_DEFECT_DEVICE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_DEVICE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_DEFECT_DEVICE_TR2";

CREATE TRIGGER GALADM.QI_DEFECT_DEVICE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_DEVICE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
