
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX";


CREATE TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX"  (
		  "DEFECT_CATEGORY_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" IS 'NAQ Defect Category';


-- DDL Statements for Indexes on Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_DEFECT_CATEGORY_I1" ON "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
		("DEFECT_CATEGORY_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_PK" PRIMARY KEY
		("DEFECT_CATEGORY_NAME");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C1" CHECK 
		(DEFECT_CATEGORY_NAME = UPPER(DEFECT_CATEGORY_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_DEFECT_CATEGORY_TR1";

CREATE TRIGGER GALADM.QI_DEFECT_CATEGORY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_DEFECT_CATEGORY_TR2";

CREATE TRIGGER GALADM.QI_DEFECT_CATEGORY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


