
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX";


CREATE TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"  (
		  "ENTRY_SCREEN" VARCHAR(40 OCTETS) NOT NULL , 
		  "REGIONAL_DEFECT_COMBINATION_ID" INTEGER NOT NULL , 
		  "ENTRY_MODEL" VARCHAR(32 OCTETS) NOT NULL , 
		  "IS_USED" SMALLINT NOT NULL , 
		  "TEXT_ENTRY_MENU" VARCHAR(32 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" IS 'NAQ Entry Screen Defect Combination';


-- DDL Statements for Indexes on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_I1" ON "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
		("ENTRY_SCREEN" ASC,
		 "REGIONAL_DEFECT_COMBINATION_ID" ASC,
		 "ENTRY_MODEL" ASC,
		 "IS_USED" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_PK" PRIMARY KEY
		("ENTRY_SCREEN",
		 "REGIONAL_DEFECT_COMBINATION_ID",
		 "ENTRY_MODEL",
		 "IS_USED");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_C1" CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_C2" CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_ENTRY_SCREEN_DEFECT_COMBINATION_C5" CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1";

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2";

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


