
------------------------------------------------
-- DDL Statements for Table "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX"
------------------------------------------------
DROP TABLE "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX";


CREATE TABLE "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX"  (
		  "EXTERNAL_SYSTEM_ID" SMALLINT NOT NULL , 
		  "EXTERNAL_SYSTEM_DEFECT_KEY" BIGINT NOT NULL WITH DEFAULT 0, 
		  "DEFECTRESULTID" BIGINT NOT NULL , 
		  "IS_QICS_REPAIR_REQD" SMALLINT NOT NULL WITH DEFAULT 0, 
		  "IS_EXT_SYS_REPAIR_REQD" SMALLINT NOT NULL WITH DEFAULT 0, 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX" IS 'Qics mapping of external system key to defect id';


-- DDL Statements for Primary Key on Table "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX"

ALTER TABLE "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX" 
	ADD CONSTRAINT "QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX_PK" PRIMARY KEY
		("EXTERNAL_SYSTEM_ID",
		 "EXTERNAL_SYSTEM_DEFECT_KEY",
		 "DEFECTRESULTID");

-- DDL Statements for Indexes on Table "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_I4" ON "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX" 
		("EXTERNAL_SYSTEM_ID" ASC,
		 "EXTERNAL_SYSTEM_DEFECT_KEY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

		
CREATE UNIQUE INDEX "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_I6" ON "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX" 
		("DEFECTRESULTID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TR1";

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DEFECT_ID_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM"."QI_EXTERNAL_SYSTEM_DEFECT_ID_TR2";

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DEFECT_ID_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

-------------------------------
-- DDL Statements for SEQUENCE
-------------------------------
CREATE SEQUENCE DEFECT_REF_ID_SEQ AS BIGINT
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  NO CYCLE
  CACHE 20;


