
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX";


CREATE TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"  (
		  "ENTRY_MODEL" VARCHAR(32 OCTETS) NOT NULL , 
		  "MTC_MODEL" CHAR(4 OCTETS) NOT NULL , 
		  "IS_USED" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" IS 'NAQ Entry Model Grouping';


-- DDL Statements for Indexes on Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_ENTRY_MODEL_GROUPING_I1" ON "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" 
		("ENTRY_MODEL" ASC,
		 "MTC_MODEL" ASC,
		 "IS_USED" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
		
CREATE INDEX "GALADM  "."QI_ENTRY_MODEL_GROUPING_I2" ON "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"
 ("MTC_MODEL" ASC, "ENTRY_MODEL" ASC) ALLOW REVERSE SCANS;
 
-- DDL Statements for Primary Key on Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"

ALTER TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" 
	ADD CONSTRAINT "QI_ENTRY_MODEL_GROUPING_PK" PRIMARY KEY
		("ENTRY_MODEL",
		 "MTC_MODEL",
		 "IS_USED");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" 
	ADD CONSTRAINT "QI_ENTRY_MODEL_GROUPING_C1" CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" 
	ADD CONSTRAINT "QI_ENTRY_MODEL_GROUPING_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX" 
	ADD CONSTRAINT "QI_ENTRY_MODEL_GROUPING_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_ENTRY_MODEL_GROUPING_TR1";

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_ENTRY_MODEL_GROUPING_TR2";

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


