
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX";


CREATE TABLE "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"  (
		  "EXTERNAL_SYSTEM_NAME" CHAR(18 OCTETS) NOT NULL , 
		  "EXTERNAL_PART_CODE" VARCHAR(64 OCTETS) NOT NULL , 
		  "EXTERNAL_DEFECT_CODE" VARCHAR(64 OCTETS) NOT NULL , 
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "ENTRY_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "ENTRY_SITE" CHAR(16 OCTETS) , 
		  "ENTRY_DEPT" CHAR(16 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "ORIGINAL_DEFECT_STATUS" SMALLINT , 
		  "CURRENT_DEFECT_STATUS" SMALLINT , 
		  "WRITE_UP_DEPT" CHAR(16 OCTETS) , 
		  "IMAGE_NAME" VARCHAR(20 OCTETS) , 
		  "ASSOCIATE_ID" CHAR(11 OCTETS) , 
		  "POINT_X" INTEGER , 
		  "POINT_Y" INTEGER , 
		  "EXTERNAL_SYSTEM_DEFECT_KEY" BIGINT WITH DEFAULT 0,   
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX" IS 'NAQ table for failed data from External System';


-- DDL Statements for Indexes on Table "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_I1" ON "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX" 
		("EXTERNAL_SYSTEM_NAME" ASC,
		 "EXTERNAL_PART_CODE" ASC,
		 "EXTERNAL_DEFECT_CODE" ASC,
		 "PRODUCT_ID" ASC,
		 "PROCESS_POINT_ID" ASC,
		 "ENTRY_TIMESTAMP" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"

ALTER TABLE "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX" 
	ADD CONSTRAINT "QI_EXTERNAL_SYSTEM_DATA_PK" PRIMARY KEY
		("EXTERNAL_SYSTEM_NAME",
		 "EXTERNAL_PART_CODE",
		 "EXTERNAL_DEFECT_CODE",
		 "PRODUCT_ID",
		 "PROCESS_POINT_ID",
		 "ENTRY_TIMESTAMP");




-- DDL Statements for Indexes on Table "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_I2" ON "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX" 
		("EXTERNAL_SYSTEM_NAME" ASC,
		 "EXTERNAL_PART_CODE" ASC,
		 "EXTERNAL_DEFECT_CODE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TR1";

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TR2";

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


