
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IMAGE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_IMAGE_TBX";


CREATE TABLE "GALADM  "."QI_IMAGE_TBX"  (
		  "BITMAP_FILE_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "IMAGE_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "IMAGE_DESCRIPTION" VARCHAR(30 OCTETS) , 
		  "IMAGE_DATA" BLOB(1048576) LOGGED COMPACT , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_IMAGE_TBX" IS 'NAQ Iage';


-- DDL Statements for Indexes on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_IMAGE_I1" ON "GALADM  "."QI_IMAGE_TBX" 
		("BITMAP_FILE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_IMAGE_TBX"

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_PK" PRIMARY KEY
		("BITMAP_FILE_NAME");




-- DDL Statements for Indexes on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_IMAGE_I2" ON "GALADM  "."QI_IMAGE_TBX" 
		("IMAGE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C1" CHECK 
		(IMAGE_NAME = UPPER(IMAGE_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C2" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IMAGE_TR1";

CREATE TRIGGER GALADM.QI_IMAGE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IMAGE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IMAGE_TR2";

CREATE TRIGGER GALADM.QI_IMAGE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IMAGE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


