
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IQS_QUESTION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_IQS_QUESTION_TBX";


CREATE TABLE "GALADM  "."QI_IQS_QUESTION_TBX"  (
		  "IQS_QUESTION_NO" INTEGER NOT NULL , 
		  "IQS_QUESTION" VARCHAR(256 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_IQS_QUESTION_TBX" IS 'NAQ IQS Question';


-- DDL Statements for Indexes on Table "GALADM  "."QI_IQS_QUESTION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_IQS_QUESTION_I1" ON "GALADM  "."QI_IQS_QUESTION_TBX" 
		("IQS_QUESTION_NO" ASC,
		 "IQS_QUESTION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_IQS_QUESTION_TBX"

ALTER TABLE "GALADM  "."QI_IQS_QUESTION_TBX" 
	ADD CONSTRAINT "QI_IQS_QUESTION_PK" PRIMARY KEY
		("IQS_QUESTION_NO",
		 "IQS_QUESTION");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IQS_QUESTION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IQS_QUESTION_TBX" 
	ADD CONSTRAINT "QI_IQS_QUESTION_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IQS_QUESTION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IQS_QUESTION_TBX" 
	ADD CONSTRAINT "QI_IQS_QUESTION_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IQS_QUESTION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IQS_QUESTION_TBX" 
	ADD CONSTRAINT "QI_IQS_QUESTION_C3" CHECK 
		(IQS_QUESTION = UPPER(IQS_QUESTION))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IQS_QUESTION_TR1";

CREATE TRIGGER GALADM.QI_IQS_QUESTION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IQS_QUESTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IQS_QUESTION_TR2";

CREATE TRIGGER GALADM.QI_IQS_QUESTION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IQS_QUESTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


