
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX";


CREATE TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"  (
		  "IMAGE_SECTION_ID" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POINT_SEQUENCE_NO" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POINT_X" INTEGER , 
		  "POINT_Y" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" IS 'NAQ Iage Section Point';


-- DDL Statements for Primary Key on Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_PK" PRIMARY KEY
		("IMAGE_SECTION_ID",
		 "POINT_SEQUENCE_NO");



-- DDL Statements for Indexes on Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "GALADM  "."QI_IMAGE_SECTION_POINT_I1" ON "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
		("IMAGE_SECTION_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_POINT_TR1";

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_POINT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IMAGE_SECTION_POINT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_POINT_TR2";

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_POINT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IMAGE_SECTION_POINT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


