
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX";


CREATE TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX"  (
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "INSPECTION_PART_LOC_DESC_SHORT" VARCHAR(10 OCTETS) , 
		  "INSPECTION_PART_LOC_DESC_LONG" VARCHAR(30 OCTETS) , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) , 
		  "PRIMARY_POSITION" SMALLINT , 
		  "HIERARCHY" SMALLINT , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) , 
		  "APP_CREATE_TIMESTAMP" TIMESTAMP , 
		  "APP_UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" IS 'NAQ Inspection Location';


-- DDL Statements for Indexes on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_INSPECTION_LOCATION_I1" ON "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
		("INSPECTION_PART_LOCATION_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_PK" PRIMARY KEY
		("INSPECTION_PART_LOCATION_NAME");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C1" CHECK 
		(INSPECTION_PART_LOCATION_NAME = UPPER(INSPECTION_PART_LOCATION_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C2" CHECK 
		(INSPECTION_PART_LOC_DESC_SHORT = UPPER(INSPECTION_PART_LOC_DESC_SHORT))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C3" CHECK 
		(INSPECTION_PART_LOC_DESC_LONG = UPPER(INSPECTION_PART_LOC_DESC_LONG))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C4" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C5" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C6" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_INSPECTION_LOCATION_TR1";

CREATE TRIGGER GALADM.QI_INSPECTION_LOCATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_INSPECTION_LOCATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_INSPECTION_LOCATION_TR2";

CREATE TRIGGER GALADM.QI_INSPECTION_LOCATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_INSPECTION_LOCATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


