
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_LOCAL_THEME_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_LOCAL_THEME_TBX";


CREATE TABLE "GALADM  "."QI_LOCAL_THEME_TBX"  (
		  "LOCAL_THEME" CHAR(18 OCTETS) NOT NULL , 
		  "LOCAL_THEME_DESCRIPTION" VARCHAR(64 OCTETS) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_LOCAL_THEME_TBX" IS 'NAQ Local Theme';


-- DDL Statements for Indexes on Table "GALADM  "."QI_LOCAL_THEME_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_LOCAL_THEME_I1" ON "GALADM  "."QI_LOCAL_THEME_TBX" 
		("LOCAL_THEME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_LOCAL_THEME_TBX"

ALTER TABLE "GALADM  "."QI_LOCAL_THEME_TBX" 
	ADD CONSTRAINT "QI_LOCAL_THEME_PK" PRIMARY KEY
		("LOCAL_THEME");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_LOCAL_THEME_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_LOCAL_THEME_TBX" 
	ADD CONSTRAINT "QI_LOCAL_THEME_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_LOCAL_THEME_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_LOCAL_THEME_TBX" 
	ADD CONSTRAINT "QI_LOCAL_THEME_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_LOCAL_THEME_TR1";

CREATE TRIGGER GALADM.QI_LOCAL_THEME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_LOCAL_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_LOCAL_THEME_TR2";

CREATE TRIGGER GALADM.QI_LOCAL_THEME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_LOCAL_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


