
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX"  (
		  "ENTRY_SITE_NAME" CHAR(16 OCTETS) NOT NULL , 
		  "ENTRY_PLANT_NAME" CHAR(16 OCTETS) NOT NULL , 
		  "ENTRY_PROD_LINE_NO" SMALLINT NOT NULL , 
		  "ENTRY_DEPT" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_ENTRY_SITE" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_ENTRY_PLANT" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_ENTRY_PROD_LINE_NO" SMALLINT NOT NULL , 
		  "OLD_ENTRY_DEPT" CHAR(16 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX" IS 'NAQ Entry Department Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_ENTRY_DEPT_I1" ON "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX" 
		("ENTRY_SITE_NAME" ASC,
		 "ENTRY_PLANT_NAME" ASC,
		 "ENTRY_PROD_LINE_NO" ASC,
		 "ENTRY_DEPT" ASC,
		 "OLD_ENTRY_SITE" ASC,
		 "OLD_ENTRY_PLANT" ASC,
		 "OLD_ENTRY_PROD_LINE_NO" ASC,
		 "OLD_ENTRY_DEPT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX" 
	ADD CONSTRAINT "QI_MAPPING_ENTRY_DEPT_PK" PRIMARY KEY
		("ENTRY_SITE_NAME",
		 "ENTRY_PLANT_NAME",
		 "ENTRY_PROD_LINE_NO",
		 "ENTRY_DEPT",
		 "OLD_ENTRY_SITE",
		 "OLD_ENTRY_PLANT",
		 "OLD_ENTRY_PROD_LINE_NO",
		 "OLD_ENTRY_DEPT");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_ENTRY_DEPT_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_ENTRY_DEPT_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


