
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_COMBINATION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_COMBINATION_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_COMBINATION_TBX"  (
		  "REGIONAL_DEFECT_COMBINATION_ID" INTEGER NOT NULL , 
		  "OLD_COMBINATION" VARCHAR(169 OCTETS) NOT NULL , 
		  "INSPECTION_PART_NAME" VARCHAR(32 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) , 
		  "INSPECTION_PART_LOCATION2_NAME" VARCHAR(20 OCTETS) , 
		  "INSPECTION_PART2_NAME" VARCHAR(32 OCTETS) , 
		  "INSPECTION_PART2_LOCATION_NAME" VARCHAR(20 OCTETS) , 
		  "INSPECTION_PART2_LOCATION2_NAME" VARCHAR(20 OCTETS) , 
		  "INSPECTION_PART3_NAME" VARCHAR(32 OCTETS) , 
		  "DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) , 
		  "DEFECT_TYPE_NAME2" VARCHAR(45 OCTETS) , 
		  "OLD_COMBINATION_CODE" INTEGER , 
		  "OLD_INSPECTION_PART_NAME" VARCHAR(32 OCTETS) , 
		  "OLD_INSPECTION_PART_LOCATION_NAME" VARCHAR(20 OCTETS) , 
		  "OLD_INSPECTION_PART_LOCATION2_NAME" VARCHAR(20 OCTETS) , 
		  "OLD_INSPECTION_PART2_NAME" VARCHAR(32 OCTETS) , 
		  "OLD_INSPECTION_PART2_LOCATION_NAME" VARCHAR(20 OCTETS) , 
		  "OLD_INSPECTION_PART2_LOCATION2_NAME" VARCHAR(20 OCTETS) , 
		  "OLD_INSPECTION_PART3_NAME" VARCHAR(32 OCTETS) , 
		  "OLD_DEFECT_TYPE_NAME" VARCHAR(45 OCTETS) , 
		  "OLD_DEFECT_TYPE_NAME2" VARCHAR(45 OCTETS) , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_COMBINATION_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_COMBINATION_TBX" IS 'NAQ Part Defect Combination Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_COMBINATION_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_COMBINATION_I1" ON "GALADM  "."QI_MAPPING_COMBINATION_TBX" 
		("REGIONAL_DEFECT_COMBINATION_ID" ASC,
		 "OLD_COMBINATION" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_COMBINATION_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_MAPPING_COMBINATION_PK" PRIMARY KEY
		("REGIONAL_DEFECT_COMBINATION_ID",
		 "OLD_COMBINATION");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_MAPPING_COMBINATION_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_MAPPING_COMBINATION_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


