
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_IQS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_IQS_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_IQS_TBX"  (
		  "IQS_ID" INTEGER NOT NULL , 
		  "OLD_IQS_CATEGORY_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "OLD_IQS_ITEM_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "IQS_VERSION" CHAR(16 OCTETS) NOT NULL , 
		  "IQS_CATEGORY" VARCHAR(32 OCTETS) NOT NULL , 
		  "IQS_QUESTION_NO" INTEGER , 
		  "IQS_QUESTION" VARCHAR(256 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_IQS_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_IQS_TBX" IS 'NAQ IQS Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_IQS_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_IQS_I1" ON "GALADM  "."QI_MAPPING_IQS_TBX" 
		("IQS_ID" ASC,
		 "OLD_IQS_CATEGORY_NAME" ASC,
		 "OLD_IQS_ITEM_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_IQS_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_IQS_TBX" 
	ADD CONSTRAINT "QI_MAPPING_IQS_PK" PRIMARY KEY
		("IQS_ID",
		 "OLD_IQS_CATEGORY_NAME",
		 "OLD_IQS_ITEM_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_IQS_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_IQS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_IQS_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_IQS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


