
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX"  (
		  "RESPONSIBLE_SITE" CHAR(16 OCTETS) NOT NULL , 
		  "RESPONSIBLE_PLANT" CHAR(16 OCTETS) NOT NULL , 
		  "WRITE_UP_DEPARTMENT" VARCHAR(32 OCTETS) NOT NULL , 
		  "OLD_WRITE_UP_DEPARTMENT" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX" IS 'NAQ Write Up Department Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_I1" ON "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX" 
		("RESPONSIBLE_SITE" ASC,
		 "RESPONSIBLE_PLANT" ASC,
		 "WRITE_UP_DEPARTMENT" ASC,
		 "OLD_WRITE_UP_DEPARTMENT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX" 
	ADD CONSTRAINT "QI_MAPPING_WRITE_UP_DEPT_PK" PRIMARY KEY
		("RESPONSIBLE_SITE",
		 "RESPONSIBLE_PLANT",
		 "WRITE_UP_DEPARTMENT",
		 "OLD_WRITE_UP_DEPARTMENT");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


