
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX"  (
		  "IMAGE_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "OLD_IMAGE_NAME" VARCHAR(20 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX" IS 'NAQ IMAGE_NAME Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_IMAGE_NAME_I1" ON "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX" 
		("IMAGE_NAME" ASC,
		 "OLD_IMAGE_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX" 
	ADD CONSTRAINT "QI_MAPPING_IMAGE_NAME_PK" PRIMARY KEY
		("IMAGE_NAME",
		 "OLD_IMAGE_NAME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_IMAGE_NAME_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_IMAGE_NAME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_IMAGE_NAME_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_IMAGE_NAME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


