
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX"  (
		  "RESPONSIBLE_SITE" CHAR(16 OCTETS) NOT NULL , 
		  "RESPONSIBLE_PLANT" CHAR(16 OCTETS) NOT NULL , 
		  "RESPONSIBLE_DEPT" CHAR(16 OCTETS) NOT NULL , 
		  "RESPONSIBLE_LEVEL3" VARCHAR(32 OCTETS) NOT NULL , 
		  "RESPONSIBLE_LEVEL2" VARCHAR(32 OCTETS) NOT NULL , 
		  "RESPONSIBLE_LEVEL1" VARCHAR(32 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_SITE" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_PLANT" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_DEPT" CHAR(16 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_LEVEL3" VARCHAR(32 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_LEVEL2" VARCHAR(32 OCTETS) NOT NULL , 
		  "OLD_RESPONSIBLE_LEVEL1" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX" IS 'NAQ Responsible Level Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_RESPONSIBILITY_I1" ON "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX" 
		("RESPONSIBLE_SITE" ASC,
		 "RESPONSIBLE_PLANT" ASC,
		 "RESPONSIBLE_DEPT" ASC,
		 "RESPONSIBLE_LEVEL3" ASC,
		 "RESPONSIBLE_LEVEL2" ASC,
		 "RESPONSIBLE_LEVEL1" ASC,
		 "OLD_RESPONSIBLE_SITE" ASC,
		 "OLD_RESPONSIBLE_PLANT" ASC,
		 "OLD_RESPONSIBLE_DEPT" ASC,
		 "OLD_RESPONSIBLE_LEVEL3" ASC,
		 "OLD_RESPONSIBLE_LEVEL2" ASC,
		 "OLD_RESPONSIBLE_LEVEL1" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX" 
	ADD CONSTRAINT "QI_MAPPING_RESPONSIBILITY_PK" PRIMARY KEY
		("RESPONSIBLE_SITE",
		 "RESPONSIBLE_PLANT",
		 "RESPONSIBLE_DEPT",
		 "RESPONSIBLE_LEVEL3",
		 "RESPONSIBLE_LEVEL2",
		 "RESPONSIBLE_LEVEL1",
		 "OLD_RESPONSIBLE_SITE",
		 "OLD_RESPONSIBLE_PLANT",
		 "OLD_RESPONSIBLE_DEPT",
		 "OLD_RESPONSIBLE_LEVEL3",
		 "OLD_RESPONSIBLE_LEVEL2",
		 "OLD_RESPONSIBLE_LEVEL1");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_RESPONSIBILITY_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_RESPONSIBILITY_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


