
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_THEME_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_MAPPING_THEME_TBX";


CREATE TABLE "GALADM  "."QI_MAPPING_THEME_TBX"  (
		  "THEME" VARCHAR(64 OCTETS) NOT NULL , 
		  "OLD_THEME" VARCHAR(64 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_MAPPING_THEME_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_MAPPING_THEME_TBX" IS 'NAQ Theme Mapping between old and new QICS';


-- DDL Statements for Indexes on Table "GALADM  "."QI_MAPPING_THEME_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_MAPPING_THEME_I1" ON "GALADM  "."QI_MAPPING_THEME_TBX" 
		("THEME" ASC,
		 "OLD_THEME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_MAPPING_THEME_TBX"

ALTER TABLE "GALADM  "."QI_MAPPING_THEME_TBX" 
	ADD CONSTRAINT "QI_MAPPING_THEME_PK" PRIMARY KEY
		("THEME",
		 "OLD_THEME");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_THEME_TR1";

CREATE TRIGGER GALADM.QI_MAPPING_THEME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_MAPPING_THEME_TR2";

CREATE TRIGGER GALADM.QI_MAPPING_THEME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


