
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_PLANT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_PLANT_TBX";


CREATE TABLE "GALADM  "."QI_PLANT_TBX"  (
		  "SITE" CHAR(16 OCTETS) NOT NULL , 
		  "PLANT" CHAR(16 OCTETS) NOT NULL , 
		  "PLANT_DESCRIPTION" VARCHAR(32 OCTETS) , 
		  "HAM_PLANT_CODE" CHAR(1 OCTETS) , 
		  "PRODUCT_KIND" CHAR(18 OCTETS) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) , 
		  "ENTRY_SITE" CHAR(16 OCTETS) , 
		  "ENTRY_PLANT" CHAR(16 OCTETS) , 
		  "PROD_LINE_NO" SMALLINT , 
		  "PDDA_LINE" CHAR(1 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_PLANT_TBX" IS 'NAQ Plant';


-- DDL Statements for Indexes on Table "GALADM  "."QI_PLANT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_PLANT_I1" ON "GALADM  "."QI_PLANT_TBX" 
		("SITE" ASC,
		 "PLANT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_PLANT_TBX"

ALTER TABLE "GALADM  "."QI_PLANT_TBX" 
	ADD CONSTRAINT "QI_PLANT_PK" PRIMARY KEY
		("SITE",
		 "PLANT");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PLANT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PLANT_TBX" 
	ADD CONSTRAINT "QI_PLANT_C1" CHECK 
		(SITE = UPPER(SITE))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PLANT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PLANT_TBX" 
	ADD CONSTRAINT "QI_PLANT_C2" CHECK 
		(PLANT = UPPER(PLANT))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PLANT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PLANT_TBX" 
	ADD CONSTRAINT "QI_PLANT_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PLANT_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PLANT_TBX" 
	ADD CONSTRAINT "QI_PLANT_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_PLANT_TR1";

CREATE TRIGGER GALADM.QI_PLANT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_PLANT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_PLANT_TR2";

CREATE TRIGGER GALADM.QI_PLANT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_PLANT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


