----------------------------

-- DDL Statements for Views

----------------------------
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE VIEW GALADM.QI_PRODUCT_TYPE_TBV (PRODUCT_TYPE, PRODUCT_SPEC_CODE,
MODEL_YEAR_CODE , MODEL_CODE , MODEL_TYPE_CODE , MODEL_OPTION_CODE , MODEL_YEAR_DESCRIPTION
, EXT_COLOR_CODE, INT_COLOR_CODE, EXT_COLOR_DESCRIPTION , INT_COLOR_DESCRIPTION,
PLANT_CODE, ENGINE_PLANT_CODE, ENGINE_MTO, SALES_MODEL_CODE, SALES_MODEL_TYPE_CODE,
SALES_EXT_COLOR_CODE, SALES_INT_COLOR_CODE, PROTOTYPE_CODE, PRODUCT_TYPE_PREFIX,
SERIES_CODE, SERIES_DESCRIPTION, GRADE_CODE, BODY_AND_TRANS_TYPE_CODE,
BODY_AND_TRANS_TYPE_DESC, ALT_ENGINE_MTO, BOUNDARY_MARK_REQUIRED, DISPLACEMENT,
DISPLACEMENT_COMMENT,ENGINE_PROTOTYPE_CODE, MISSION_MODEL_YEAR_CODE, MISSION_MODEL_CODE,
MISSION_MODEL_TYPE_CODE, MISSION_PLANT_CODE, MISSION_PROTOTYPE_CODE, TRANSMISSION,
TRANSMISSION_DESCRIPTION, GEAR_SHIFT, GEAR_SHIFT_DESCRIPTION, STAMP_SERIAL_DESC,
MBPN, HES_COLOR   , MAIN_NO , CLASS_NO ,  TYPE_NO , SUPPLEMENTARY_NO ,
TARGET_NO , NAME) AS SELECT 'FRAME' as PRODUCT_TYPE, PRODUCT_SPEC_CODE
as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE, MODEL_CODE as
MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE as MODEL_OPTION_CODE,
MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION, EXT_COLOR_CODE as EXT_COLOR_CODE,
INT_COLOR_CODE as INT_COLOR_CODE, EXT_COLOR_DESCRIPTION as EXT_COLOR_DESCRIPTION,
INT_COLOR_DESCRIPTION as INT_COLOR_DESCRIPTION, PLANT_CODE_GPCS as PLANT_CODE,
ENGINE_PLANT_CODE as ENGINE_PLANT_CODE, ENGINE_MTO as ENGINE_MTO, SALES_MODEL_CODE
as SALES_MODEL_CODE , SALES_MODEL_TYPE_CODE as SALES_MODEL_TYPE_CODE, SALES_EXT_COLOR_CODE
as SALES_EXT_COLOR_CODE, SALES_INT_COLOR_CODE as SALES_INT_COLOR_CODE,
PROTOTYPE_CODE as PROTOTYPE_CODE, FRAME_NO_PREFIX as  Product_Type_PREFIX,
SERIES_CODE as SERIES_CODE, SERIES_DESCRIPTION as SERIES_DESCRIPTION, GRADE_CODE
as GRADE_CODE, BODY_AND_TRANS_TYPE_CODE as BODY_AND_TRANS_TYPE_CODE, BODY_AND_TRANS_TYPE_DESC
as BODY_AND_TRANS_TYPE_DESC, ALT_ENGINE_MTO as ALT_ENGINE_MTO , BOUNDARY_MARK_REQUIRED
as BOUNDARY_MARK_REQUIRED , '' as DISPLACEMENT, '' as DISPLACEMENT_COMMENT,
'' as ENGINE_PROTOTYPE_CODE, '' as MISSION_MODEL_YEAR_CODE, '' as MISSION_MODEL_CODE,
'' as MISSION_MODEL_TYPE_CODE, '' as MISSION_PLANT_CODE, '' as MISSION_PROTOTYPE_CODE,
'' as TRANSMISSION, '' as TRANSMISSION_DESCRIPTION, '' as GEAR_SHIFT, ''
as GEAR_SHIFT_DESCRIPTION, '' as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR,
'' as MAIN_NO, '' as CLASS_NO,  '' as TYPE_NO, '' as SUPPLEMENTARY_NO,
'' as TARGET_NO, '' as NAME FROM GALADM.GAL144TBX UNION ALL select 'ENGINE'
as PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE
as MODEL_YEAR_CODE, MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE,
MODEL_OPTION_CODE as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
'' as EXT_COLOR_CODE, '' as INT_COLOR_CODE, '' as EXT_COLOR_DESCRIPTION,
''  as INT_COLOR_DESCRIPTION, PLANT_CODE as PLANT_CODE, '' as ENGINE_PLANT_CODE,
'' as ENGINE_MTO, '' as SALES_MODEL_CODE , '' as SALES_MODEL_TYPE_CODE,
'' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE, '' as PROTOTYPE_CODE,
ENGINE_NO_PREFIX as Product_Type_PREFIX, '' as SERIES_CODE, '' as SERIES_DESCRIPTION,
'' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE, '' as BODY_AND_TRANS_TYPE_DESC,
'' as ALT_ENGINE_MTO , '' as BOUNDARY_MARK_REQUIRED , DISPLACEMENT as DISPLACEMENT,
DISPLACEMENT_COMMENT as DISPLACEMENT_COMMENT, ENGINE_PROTOTYPE_CODE as
ENGINE_PROTOTYPE_CODE, MISSION_MODEL_YEAR_CODE as MISSION_MODEL_YEAR_CODE,
MISSION_MODEL_CODE as MISSION_MODEL_CODE, MISSION_MODEL_TYPE_CODE as MISSION_MODEL_TYPE_CODE,
MISSION_PLANT_CODE as MISSION_PLANT_CODE, MISSION_PROTOTYPE_CODE as MISSION_PROTOTYPE_CODE,
TRANSMISSION as TRANSMISSION, TRANSMISSION_DESCRIPTION as TRANSMISSION_DESCRIPTION,
GEAR_SHIFT as GEAR_SHIFT, GEAR_SHIFT_DESCRIPTION as GEAR_SHIFT_DESCRIPTION,
'' as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME FROM GALADM.GAL133TBX UNION ALL select 'MISSION' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
'' as EXT_COLOR_CODE, '' as INT_COLOR_CODE, '' as EXT_COLOR_DESCRIPTION,
''  as INT_COLOR_DESCRIPTION, PLANT_CODE as PLANT_CODE, '' as ENGINE_PLANT_CODE,
'' as ENGINE_MTO, '' as SALES_MODEL_CODE , '' as SALES_MODEL_TYPE_CODE,
'' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE, '' as PROTOTYPE_CODE,
MISSION_NO_PREFIX as Product_Type_PREFIX, '' as SERIES_CODE, '' as SERIES_DESCRIPTION,
'' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE, '' as BODY_AND_TRANS_TYPE_DESC,
'' as ALT_ENGINE_MTO , BOUNDARY_MARK as BOUNDARY_MARK_REQUIRED , ''  as
DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
STAMP_SERIAL_DESC as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, ''
as MAIN_NO, '' as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as
TARGET_NO, '' as NAME from GALADM.MISSION_SPEC_CODE_TBX UNION ALL select
'MBPN' as PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, '' as MODEL_YEAR_CODE,
'' as MODEL_CODE, '' as MODEL_TYPE_CODE, '' as MODEL_OPTION_CODE, '' as
MODEL_YEAR_DESCRIPTION, '' as EXT_COLOR_CODE, '' as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, MBPN as MBPN, HES_COLOR as HES_COLOR, MAIN_NO
as MAIN_NO, CLASS_NO as CLASS_NO,  TYPE_NO as TYPE_NO, SUPPLEMENTARY_NO
as SUPPLEMENTARY_NO, TARGET_NO as TARGET_NO, '' as NAME from GALADM.MBPN_TBX
UNION ALL select 'HEAD' as PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE,
MODEL_YEAR_CODE as MODEL_YEAR_CODE, MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE
as MODEL_TYPE_CODE, MODEL_OPTION_CODE as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION
as MODEL_YEAR_DESCRIPTION, EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE
as INT_COLOR_CODE, '' as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION,
''  as PLANT_CODE, '' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE
, '' as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'BLOCK' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'CONROD' as
PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as
MODEL_YEAR_CODE, MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE,
MODEL_OPTION_CODE as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'CRANKSHAFT'
as PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE
as MODEL_YEAR_CODE, MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE,
MODEL_OPTION_CODE as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'MCASE' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'TCASE' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'PLASTICS' as
PRODUCT_TYPE, PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as
MODEL_YEAR_CODE, MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE,
MODEL_OPTION_CODE as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'WELD' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO, '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX UNION ALL select 'IPU' as PRODUCT_TYPE,
PRODUCT_SPEC_CODE as PRODUCT_SPEC_CODE, MODEL_YEAR_CODE as MODEL_YEAR_CODE,
MODEL_CODE as MODEL_CODE, MODEL_TYPE_CODE as MODEL_TYPE_CODE, MODEL_OPTION_CODE
as MODEL_OPTION_CODE, MODEL_YEAR_DESCRIPTION as MODEL_YEAR_DESCRIPTION,
EXT_COLOR_CODE as EXT_COLOR_CODE, INT_COLOR_CODE as INT_COLOR_CODE, ''
as EXT_COLOR_DESCRIPTION, ''  as INT_COLOR_DESCRIPTION, ''  as PLANT_CODE,
'' as ENGINE_PLANT_CODE, '' as ENGINE_MTO, '' as SALES_MODEL_CODE , ''
as SALES_MODEL_TYPE_CODE, '' as SALES_EXT_COLOR_CODE, '' as SALES_INT_COLOR_CODE,
'' as PROTOTYPE_CODE, ''  as Product_Type_PREFIX, '' as SERIES_CODE, ''
as SERIES_DESCRIPTION, '' as GRADE_CODE, '' as BODY_AND_TRANS_TYPE_CODE,
'' as BODY_AND_TRANS_TYPE_DESC, '' as ALT_ENGINE_MTO , ''  as BOUNDARY_MARK_REQUIRED
, ''  as DISPLACEMENT, ''  as DISPLACEMENT_COMMENT, ''  as ENGINE_PROTOTYPE_CODE,
''  as MISSION_MODEL_YEAR_CODE, ''  as MISSION_MODEL_CODE, ''  as MISSION_MODEL_TYPE_CODE,
''  as MISSION_PLANT_CODE, ''  as MISSION_PROTOTYPE_CODE, ''  as TRANSMISSION,
''  as TRANSMISSION_DESCRIPTION, ''  as GEAR_SHIFT, ''  as GEAR_SHIFT_DESCRIPTION,
''  as STAMP_SERIAL_DESC, '' as MBPN, '' as HES_COLOR, '' as MAIN_NO, ''
as CLASS_NO,  '' as TYPE_NO, '' as SUPPLEMENTARY_NO, '' as TARGET_NO, ''
as NAME from GALADM.PRODUCT_SPEC_CODE_TBX;
