
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX";


CREATE TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"  (
		  "PDDA_RESPONSIBILITY_ID" INTEGER NOT NULL , 
		  "PCL_TO_QICS_SEQ_KEY" INTEGER NOT NULL , 
		  "PREV_RESP_LEVEL1" VARCHAR(32 OCTETS) , 
		  "PREV_BASE_PART_NO" CHAR(5 OCTETS) , 
		  "PREV_RESP_LEVEL1_DESC" VARCHAR(32 OCTETS) , 
		  "PREV_PROCESS_NUMBER" CHAR(5 OCTETS) , 
		  "PREV_PROCESS_NAME" VARCHAR(35 OCTETS) , 
		  "PREV_UNIT_DESC" VARCHAR(254 OCTETS) , 
		  "PREV_PDDA_LINE" CHAR(1 OCTETS) , 
		  "ADMIN_CONFIRMED_FIX" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX" IS 'NAQ PDDA Responsible Load Trigger';


-- DDL Statements for Indexes on Table "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_I1" ON "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX" 
		("PDDA_RESPONSIBILITY_ID" ASC,
		 "PCL_TO_QICS_SEQ_KEY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"

ALTER TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX" 
	ADD CONSTRAINT "QI_PDDA_RESP_LOAD_TRIGGER_PK" PRIMARY KEY
		("PDDA_RESPONSIBILITY_ID",
		 "PCL_TO_QICS_SEQ_KEY");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX" 
	ADD CONSTRAINT "QI_PDDA_RESP_LOAD_TRIGGER_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TBX" 
	ADD CONSTRAINT "QI_PDDA_RESP_LOAD_TRIGGER_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TR1";

CREATE TRIGGER GALADM.QI_PDDA_RESP_LOAD_TRIGGER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_PDDA_RESP_LOAD_TRIGGER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_PDDA_RESP_LOAD_TRIGGER_TR2";

CREATE TRIGGER GALADM.QI_PDDA_RESP_LOAD_TRIGGER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_PDDA_RESP_LOAD_TRIGGER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


