CREATE TABLE "GALADM"."QI_RESPONSIBILITY_MAPPING_TBX"
(
   DEFAULT_RESPONSIBLE_LEVEL_ID int NOT NULL,
   PLANT_CODE char(4) NOT NULL,
   RESPONSIBLE_LEVEL_ID int NOT NULL,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   CREATE_USER char(11),
   UPDATE_USER char(11)
   )
DATA CAPTURE CHANGES
IN "GALTBSREF11" INDEX IN "GALTBSIDX4"
;
 
CREATE UNIQUE INDEX QI_RESPONSIBILITY_MAPPING_I1 ON "GALADM"."QI_RESPONSIBILITY_MAPPING_TBX"
(
  DEFAULT_RESPONSIBLE_LEVEL_ID,
  PLANT_CODE
)
;

 
ALTER TABLE "GALADM  "."QI_RESPONSIBILITY_MAPPING_TBX"
        ADD CONSTRAINT "QI_RESPONSIBILITY_MAPPING_PK" PRIMARY KEY
                (DEFAULT_RESPONSIBLE_LEVEL_ID, PLANT_CODE); 
 