
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPORTING_METRIC_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_REPORTING_METRIC_TBX";


CREATE TABLE "GALADM  "."QI_REPORTING_METRIC_TBX"  (
		  "METRIC_NAME" CHAR(10 OCTETS) NOT NULL , 
		  "LEVEL" CHAR(16 OCTETS) NOT NULL , 
		  "METRIC_DESCRIPTION" VARCHAR(64 OCTETS) , 
		  "METRIC_DATA_FORMAT" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" IS 'NAQ Reporting METRIC';


-- DDL Statements for Indexes on Table "GALADM  "."QI_REPORTING_METRIC_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_REPORTING_METRIC_I1" ON "GALADM  "."QI_REPORTING_METRIC_TBX" 
		("METRIC_NAME" ASC,
		 "LEVEL" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_REPORTING_METRIC_TBX"

ALTER TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" 
	ADD CONSTRAINT "QI_REPORTING_METRIC_PK" PRIMARY KEY
		("METRIC_NAME",
		 "LEVEL");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_REPORTING_METRIC_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" 
	ADD CONSTRAINT "QI_REPORTING_METRIC_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_REPORTING_METRIC_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" 
	ADD CONSTRAINT "QI_REPORTING_METRIC_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_REPORTING_METRIC_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_REPORTING_METRIC_TBX" 
	ADD CONSTRAINT "QI_REPORTING_METRIC_C3" CHECK 
		(METRIC_NAME = UPPER(METRIC_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_REPORTING_METRIC_TR1";

CREATE TRIGGER GALADM.QI_REPORTING_METRIC_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPORTING_METRIC_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_REPORTING_METRIC_TR2";

CREATE TRIGGER GALADM.QI_REPORTING_METRIC_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPORTING_METRIC_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


