
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_UPC_PART_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_STATION_UPC_PART_TBX";


CREATE TABLE "GALADM  "."QI_STATION_UPC_PART_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "MAIN_PART_NO" CHAR(7 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_STATION_UPC_PART_TBX" IS 'NAQ UPC Parts by Station';


-- DDL Statements for Indexes on Table "GALADM  "."QI_STATION_UPC_PART_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_STATION_UPC_PART_I1" ON "GALADM  "."QI_STATION_UPC_PART_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "MAIN_PART_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_STATION_UPC_PART_TBX"

ALTER TABLE "GALADM  "."QI_STATION_UPC_PART_TBX" 
	ADD CONSTRAINT "QI_STATION_UPC_PART_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "MAIN_PART_NO");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_UPC_PART_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_UPC_PART_TBX" 
	ADD CONSTRAINT "QI_STATION_UPC_PART_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_UPC_PART_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_UPC_PART_TBX" 
	ADD CONSTRAINT "QI_STATION_UPC_PART_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_UPC_PART_TR1";

CREATE TRIGGER GALADM.QI_STATION_UPC_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_UPC_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_UPC_PART_TR2";

CREATE TRIGGER GALADM.QI_STATION_UPC_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_UPC_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


