
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_CONFIG_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_STATION_CONFIG_TBX";


CREATE TABLE "GALADM  "."QI_STATION_CONFIG_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "PROPERTY_KEY" VARCHAR(64 OCTETS) NOT NULL , 
		  "PROPERTY_VALUE" VARCHAR(64 OCTETS) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_STATION_CONFIG_TBX" IS 'NAQ Station Configuration';


-- DDL Statements for Indexes on Table "GALADM  "."QI_STATION_CONFIG_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_STATION_CONFIG_I1" ON "GALADM  "."QI_STATION_CONFIG_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PROPERTY_KEY" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_STATION_CONFIG_TBX"

ALTER TABLE "GALADM  "."QI_STATION_CONFIG_TBX" 
	ADD CONSTRAINT "QI_STATION_CONFIG_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PROPERTY_KEY");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_CONFIG_TR1";

CREATE TRIGGER GALADM.QI_STATION_CONFIG_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_CONFIG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_CONFIG_TR2";

CREATE TRIGGER GALADM.QI_STATION_CONFIG_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_CONFIG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


