
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX";


CREATE TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "ENTRY_MODEL" VARCHAR(32 OCTETS) NOT NULL , 
		  "DIVISION_ID" CHAR(16 OCTETS) NOT NULL , 
		  "SEQ" SMALLINT NOT NULL , 
		  "ENTRY_SCREEN" VARCHAR(40 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) , 
		  "ORIENTATION_ANGLE" SMALLINT WITH DEFAULT 0 , 
		  "ALLOW_SCAN" SMALLINT )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" IS 'NAQ Entry Screen by Station';


-- DDL Statements for Indexes on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_STATION_ENTRY_SCREEN_I1" ON "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ENTRY_MODEL" ASC,
		 "DIVISION_ID" ASC,
		 "SEQ" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
		
CREATE INDEX "GALADM  "."QI_STATION_ENTRY_SCREEN_I2" on "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"
 ("ENTRY_SCREEN" ASC) ALLOW REVERSE SCANS;
 
-- DDL Statements for Primary Key on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

ALTER TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
	ADD CONSTRAINT "QI_STATION_ENTRY_SCREEN_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "ENTRY_MODEL",
		 "DIVISION_ID",
		 "SEQ");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
	ADD CONSTRAINT "QI_STATION_ENTRY_SCREEN_C1" CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
	ADD CONSTRAINT "QI_STATION_ENTRY_SCREEN_C2" CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
	ADD CONSTRAINT "QI_STATION_ENTRY_SCREEN_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX" 
	ADD CONSTRAINT "QI_STATION_ENTRY_SCREEN_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_ENTRY_SCREEN_TR1";

CREATE TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."QI_STATION_ENTRY_SCREEN_TR2";

CREATE TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


