
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_THEME_GROUPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QI_THEME_GROUPING_TBX";


CREATE TABLE "GALADM  "."QI_THEME_GROUPING_TBX"  (
		  "THEME_GROUP_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "THEME_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QI_THEME_GROUPING_TBX" IS 'NAQ Theme Grouping';


-- DDL Statements for Indexes on Table "GALADM  "."QI_THEME_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QI_THEME_GROUPING_I1" ON "GALADM  "."QI_THEME_GROUPING_TBX" 
		("THEME_GROUP_NAME" ASC,
		 "THEME_NAME" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QI_THEME_GROUPING_TBX"

ALTER TABLE "GALADM  "."QI_THEME_GROUPING_TBX" 
	ADD CONSTRAINT "QI_THEME_GROUPING_PK" PRIMARY KEY
		("THEME_GROUP_NAME",
		 "THEME_NAME");




-- DDL Statements for Check Constraints on Table "GALADM  "."QI_THEME_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_THEME_GROUPING_TBX" 
	ADD CONSTRAINT "QI_THEME_GROUPING_C1" CHECK 
		(THEME_GROUP_NAME = UPPER(THEME_GROUP_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_THEME_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_THEME_GROUPING_TBX" 
	ADD CONSTRAINT "QI_THEME_GROUPING_C2" CHECK 
		(THEME_NAME = UPPER(THEME_NAME))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_THEME_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_THEME_GROUPING_TBX" 
	ADD CONSTRAINT "QI_THEME_GROUPING_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."QI_THEME_GROUPING_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."QI_THEME_GROUPING_TBX" 
	ADD CONSTRAINT "QI_THEME_GROUPING_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_THEME_GROUPING_TR1";

CREATE TRIGGER GALADM.QI_THEME_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_THEME_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QI_THEME_GROUPING_TR2";

CREATE TRIGGER GALADM.QI_THEME_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_THEME_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


