------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_TEMPORARY_TRACKING_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR1;
DROP TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR2;
DROP TABLE GALADM.QI_TEMPORARY_TRACKING_TBX;

CREATE TABLE GALADM.QI_TEMPORARY_TRACKING_TBX
(
	TEMPORARY_TRACKING    CHAR(18) NOT NULL ,
	ACTIVE                SMALLINT,	
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_TEMPORARY_TRACKING_TBX IS 'NAQ Temporary Tracking';

CREATE UNIQUE INDEX GALADM.QI_TEMPORARY_TRACKING_I1
  ON GALADM.QI_TEMPORARY_TRACKING_TBX (TEMPORARY_TRACKING);

ALTER TABLE GALADM.QI_TEMPORARY_TRACKING_TBX 
	ADD CONSTRAINT QI_TEMPORARY_TRACKING_PK PRIMARY KEY (TEMPORARY_TRACKING);
		
ALTER TABLE GALADM.QI_TEMPORARY_TRACKING_TBX 
	ADD CONSTRAINT QI_TEMPORARY_TRACKING_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_TEMPORARY_TRACKING_TBX  
	ADD CONSTRAINT QI_TEMPORARY_TRACKING_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

CREATE TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_TEMPORARY_TRACKING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_TEMPORARY_TRACKING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;      