
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QSR_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QSR_TBX";


CREATE TABLE "GALADM  "."QSR_TBX"  (
		  "QSR_ID" INTEGER NOT NULL , 
		  "PROCESS_LOCATION" VARCHAR(16 OCTETS) , 
		  "DESCRIPTION" VARCHAR(250 OCTETS) , 
		  "QSR_STATUS" INTEGER , 
		  "COMMENT" VARCHAR(80 OCTETS) , 
		  "APPROVER_NAME" VARCHAR(30 OCTETS) , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_TYPE" VARCHAR(10 OCTETS) NOT NULL WITH DEFAULT '',
		  "RESPONSIBLE_DEPARTMENT" VARCHAR(16 OCTETS),
		  "HOLD_ACCESS_TYPE_ID" VARCHAR(20))   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "GALADM  "."QSR_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."QSR_L1" ON "GALADM  "."QSR_TBX" 
		("QSR_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."QSR_TBX"

ALTER TABLE "GALADM  "."QSR_TBX" 
	ADD CONSTRAINT "QSR_PK" PRIMARY KEY
		("QSR_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QSR_TR1";

CREATE TRIGGER GALADM.QSR_TR1 NO CASCADE BEFORE INSERT ON GALADM.QSR_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QSR_TR2";

CREATE TRIGGER GALADM.QSR_TR2 NO CASCADE BEFORE UPDATE ON GALADM.QSR_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


