
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QUORUM_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QUORUM_TBX";


CREATE TABLE "GALADM  "."QUORUM_TBX"  (
		  "QUORUM_DATE" DATE NOT NULL , 
		  "QUORUM_ID" INTEGER NOT NULL , 
		  "TRAILER_ID" INTEGER NOT NULL , 
		  "TRAILER_ROW" INTEGER NOT NULL , 
		  "PALLET_TYPE" VARCHAR(5 OCTETS) NOT NULL , 
		  "QUORUM_SIZE" INTEGER NOT NULL , 
		  "STATUS" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QUORUM_TBX" IS 'RMT ShippingQuorum';


-- DDL Statements for Primary Key on Table "GALADM  "."QUORUM_TBX"

ALTER TABLE "GALADM  "."QUORUM_TBX" 
	ADD CONSTRAINT "QUORUM_PK" PRIMARY KEY
		("QUORUM_DATE",
		 "QUORUM_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QUORUM_TR1";

CREATE TRIGGER GALADM.QUORUM_TR1 NO CASCADE BEFORE INSERT ON GALADM.QUORUM_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QUORUM_TR2";

CREATE TRIGGER GALADM.QUORUM_TR2 NO CASCADE BEFORE UPDATE ON GALADM.QUORUM_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


