
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QUORUM_DETAIL_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."QUORUM_DETAIL_TBX";


CREATE TABLE "GALADM  "."QUORUM_DETAIL_TBX"  (
		  "QUORUM_DATE" DATE NOT NULL , 
		  "QUORUM_ID" INTEGER NOT NULL , 
		  "QUORUM_SEQ" INTEGER NOT NULL , 
		  "KD_LOT" CHAR(18 OCTETS) , 
		  "YMTO" CHAR(9 OCTETS) , 
		  "ENGINE_NUMBER" CHAR(12 OCTETS) , 
		  "STATUS" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."QUORUM_DETAIL_TBX" IS 'RMT ShippingQuorumDetail';


-- DDL Statements for Primary Key on Table "GALADM  "."QUORUM_DETAIL_TBX"

ALTER TABLE "GALADM  "."QUORUM_DETAIL_TBX" 
	ADD CONSTRAINT "QUORUM_DETAILPK" PRIMARY KEY
		("QUORUM_DATE",
		 "QUORUM_ID",
		 "QUORUM_SEQ");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QUORUM_DETAIL_TR1";

CREATE TRIGGER GALADM.QUORUM_DETAIL_TR1 NO CASCADE BEFORE INSERT ON GALADM.QUORUM_DETAIL_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."QUORUM_DETAIL_TR2";

CREATE TRIGGER GALADM.QUORUM_DETAIL_TR2 NO CASCADE BEFORE UPDATE ON GALADM.QUORUM_DETAIL_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


