
------------------------------------------------
-- DDL Statements for Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX";


CREATE TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"  (
		  "CATEGORY_CODE" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "SITE" CHAR(16 OCTETS) NOT NULL , 
		  "PROCESS_POINT_GROUP_NAME" VARCHAR(256 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" IS 'REGIONAL PROCESS POINT GROUP';


-- DDL Statements for Primary Key on Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"

ALTER TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" 
	ADD CONSTRAINT "REGIONAL_PROCESS_POINT_GROUP_PK" PRIMARY KEY
		("CATEGORY_CODE",
		 "SITE",
		 "PROCESS_POINT_GROUP_NAME");



-- DDL Statements for Check Constraints on Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" 
	ADD CONSTRAINT "REGIONAL_PROCESS_POINT_GROUP_C1" CHECK 
		(SITE = UPPER(SITE))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" 
	ADD CONSTRAINT "REGIONAL_PROCESS_POINT_GROUP_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX" 
	ADD CONSTRAINT "REGIONAL_PROCESS_POINT_GROUP_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TR1";

CREATE TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TR2";

CREATE TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


