
------------------------------------------------
-- DDL Statements for Table "GALADM  "."REGIONAL_CODE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."REGIONAL_CODE_TBX";


CREATE TABLE "GALADM  "."REGIONAL_CODE_TBX"  (
		  "REGIONAL_CODE_NAME" VARCHAR(256 OCTETS) NOT NULL , 
		  "REGIONAL_VALUE" VARCHAR(256 OCTETS) NOT NULL , 
		  "REGIONAL_VALUE_NAME" VARCHAR(128 OCTETS) , 
		  "REGIONAL_VALUE_ABBR" VARCHAR(64 OCTETS) , 
		  "REGIONAL_VALUE_DESC" VARCHAR(256 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11 OCTETS) , 
		  "UPDATE_USER" CHAR(11 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."REGIONAL_CODE_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."REGIONAL_CODE_TBX" IS 'REGIONAL CODE';


-- DDL Statements for Indexes on Table "GALADM  "."REGIONAL_CODE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."REGIONAL_CODE_I1" ON "GALADM  "."REGIONAL_CODE_TBX" 
		("REGIONAL_CODE_NAME" ASC,
		 "REGIONAL_VALUE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."REGIONAL_CODE_TBX"

ALTER TABLE "GALADM  "."REGIONAL_CODE_TBX" 
	ADD CONSTRAINT "REGIONAL_CODE_PK" PRIMARY KEY
		("REGIONAL_CODE_NAME",
		 "REGIONAL_VALUE");




-- DDL Statements for Check Constraints on Table "GALADM  "."REGIONAL_CODE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."REGIONAL_CODE_TBX" 
	ADD CONSTRAINT "REGIONAL_CODE_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for Check Constraints on Table "GALADM  "."REGIONAL_CODE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

ALTER TABLE "GALADM  "."REGIONAL_CODE_TBX" 
	ADD CONSTRAINT "REGIONAL_CODE_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REGIONAL_CODE_TR1";

CREATE TRIGGER GALADM.REGIONAL_CODE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.REGIONAL_CODE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REGIONAL_CODE_TR2";

CREATE TRIGGER GALADM.REGIONAL_CODE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.REGIONAL_CODE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


