
------------------------------------------------
-- DDL Statements for Table "GALADM  "."REQUIRED_PARTS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."REQUIRED_PARTS_TBX";


CREATE TABLE "GALADM  "."REQUIRED_PARTS_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_OPTION_CODE" CHAR(3 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "INT_COLOR_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "EXT_COLOR_CODE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL WITH DEFAULT ' ' , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "SUB_ID" CHAR(2 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."REQUIRED_PARTS_TBX" IS 'RMT RequiredPart';


-- DDL Statements for Primary Key on Table "GALADM  "."REQUIRED_PARTS_TBX"

ALTER TABLE "GALADM  "."REQUIRED_PARTS_TBX" 
	ADD CONSTRAINT "REQUIRED_PARTS_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "MODEL_OPTION_CODE",
		 "INT_COLOR_CODE",
		 "EXT_COLOR_CODE",
		 "PART_NAME",
		 "PRODUCT_SPEC_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REQUIRED_PARTS_TR1";

CREATE TRIGGER GALADM.REQUIRED_PARTS_TR1 NO CASCADE BEFORE INSERT ON GALADM.REQUIRED_PARTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."REQUIRED_PARTS_TR2";

CREATE TRIGGER GALADM.REQUIRED_PARTS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.REQUIRED_PARTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


