
------------------------------------------------
-- DDL Statements for Table "VIOS    "."ROTATION"
------------------------------------------------
 
DROP TABLE "VIOS    "."ROTATION";


CREATE TABLE "VIOS    "."ROTATION"  (
		  "ROTATION_ID" INTEGER NOT NULL , 
		  "LINE_NUM" SMALLINT , 
		  "TEAM_ID" INTEGER , 
		  "PRODUCTION_DATE" TIMESTAMP NOT NULL , 
		  "LAST_UPDATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "CREATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "CREATED_DATE" TIMESTAMP NOT NULL , 
		  "TEAM_GROUP_ID" INTEGER , 
		  "PC_AREA_ID" INTEGER , 
		  "SHIFT_ID" SMALLINT NOT NULL , 
		  "IS_FINALIZED" CHAR(18 OCTETS) , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."ROTATION"

ALTER TABLE "VIOS    "."ROTATION" 
	ADD CONSTRAINT "ROTATION_PK" PRIMARY KEY
		("ROTATION_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."ROTATION_TR1";

CREATE TRIGGER VIOS.ROTATION_TR1 NO CASCADE BEFORE INSERT ON VIOS.ROTATION
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."ROTATION_TR2";

CREATE TRIGGER VIOS.ROTATION_TR2 NO CASCADE BEFORE UPDATE ON VIOS.ROTATION
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


