
------------------------------------------------
-- DDL Statements for Table "GALADM  "."RULE_EXCLUSION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."RULE_EXCLUSION_TBX";


CREATE TABLE "GALADM  "."RULE_EXCLUSION_TBX"  (
		  "PART_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."RULE_EXCLUSION_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."RULE_EXCLUSION_TBX" IS 'RMT table for excluded rules from required check';


-- DDL Statements for Primary Key on Table "GALADM  "."RULE_EXCLUSION_TBX"

ALTER TABLE "GALADM  "."RULE_EXCLUSION_TBX" 
	ADD CONSTRAINT "RULE_EXCLUSION_PK" PRIMARY KEY
		("PART_NAME",
		 "PRODUCT_SPEC_CODE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."RULE_EXCLUSION_TR1";

CREATE TRIGGER GALADM.RULE_EXCLUSION_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.RULE_EXCLUSION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."RULE_EXCLUSION_TR2";

CREATE TRIGGER GALADM.RULE_EXCLUSION_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.RULE_EXCLUSION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


