
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SALES_ORDER_FIF_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SALES_ORDER_FIF_TBX";


CREATE TABLE "GALADM  "."SALES_ORDER_FIF_TBX"  (
		  "LOC_PROD_MONTH" VARCHAR(6 OCTETS) NOT NULL , 
		  "ORDER_TYPE" VARCHAR(2 OCTETS) NOT NULL , 
		  "ORDER_SEQ_NO" SMALLINT NOT NULL , 
		  "UNIQUE_ID" VARCHAR(3 OCTETS) NOT NULL , 
		  "SALES_DIV" VARCHAR(1 OCTETS) , 
		  "PROD_DIV" VARCHAR(1 OCTETS) , 
		  "PROD_QTY" INTEGER NOT NULL , 
		  "MODEL_YEAR" VARCHAR(4 OCTETS) NOT NULL , 
		  "SALES_MODEL_CD" VARCHAR(11 OCTETS) NOT NULL , 
		  "SALES_VEH_DEST_CD" VARCHAR(4 OCTETS) NOT NULL , 
		  "SALES_OPTION_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "SALES_EXT_CLR_CD" VARCHAR(10 OCTETS) NOT NULL , 
		  "SALES_INT_CLR_CD" VARCHAR(2 OCTETS) NOT NULL , 
		  "FRM_PLANT_CD" VARCHAR(4 OCTETS) NOT NULL , 
		  "FRM_MODEL_YEAR_CD" VARCHAR(1 OCTETS) NOT NULL , 
		  "FRM_MODEL_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "FRM_DEV_SEQ_CD" VARCHAR(1 OCTETS) NOT NULL , 
		  "FRM_TYPE_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "FRM_OPTION_CD" VARCHAR(3 OCTETS) NOT NULL , 
		  "FRM_EXT_CLR_CD" VARCHAR(10 OCTETS) NOT NULL , 
		  "FRM_INT_CLR_CD" VARCHAR(2 OCTETS) NOT NULL , 
		  "BUILD_BY_DT" VARCHAR(8 OCTETS) NOT NULL , 
		  "SHIPPER_ID" VARCHAR(3 OCTETS) NOT NULL , 
		  "SALES_KD_LOT_NO" VARCHAR(9 OCTETS) , 
		  "EFCT_END_DT" DATE , 
		  "FIF_CODES" VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."SALES_ORDER_FIF_TBX" IS 'RGALC table corresponding to  GPCS GMM98D00';


-- DDL Statements for Primary Key on Table "GALADM  "."SALES_ORDER_FIF_TBX"

ALTER TABLE "GALADM  "."SALES_ORDER_FIF_TBX" 
	ADD CONSTRAINT "SALES_ORDER_FIF_PK" PRIMARY KEY
		("UNIQUE_ID",
		 "SALES_MODEL_CD",
		 "SALES_VEH_DEST_CD",
		 "SALES_OPTION_CD",
		 "SALES_EXT_CLR_CD",
		 "SALES_INT_CLR_CD",
		 "ORDER_TYPE",
		 "ORDER_SEQ_NO",
		 "FRM_PLANT_CD",
		 "FRM_MODEL_YEAR_CD",
		 "FRM_MODEL_CD",
		 "FRM_DEV_SEQ_CD",
		 "FRM_TYPE_CD",
		 "FRM_OPTION_CD",
		 "FRM_EXT_CLR_CD",
		 "FRM_INT_CLR_CD");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SALES_ORDER_FIF_TR1";

CREATE TRIGGER GALADM.SALES_ORDER_FIF_TR1 NO CASCADE BEFORE INSERT ON GALADM.SALES_ORDER_FIF_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SALES_ORDER_FIF_TR2";

CREATE TRIGGER GALADM.SALES_ORDER_FIF_TR2 NO CASCADE BEFORE UPDATE ON GALADM.SALES_ORDER_FIF_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


