
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SEQUENCE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SEQUENCE_TBX";


CREATE TABLE "GALADM  "."SEQUENCE_TBX"  (
		  "SEQUENCE_ID_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "START_SEQ" INTEGER NOT NULL , 
		  "END_SEQ" INTEGER NOT NULL , 
		  "CURRENT_SEQ" INTEGER NOT NULL , 
		  "INCREMENT_VALUE" INTEGER WITH DEFAULT 1 , 
		  "DESCRIPTION" VARCHAR(255 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

ALTER TABLE "GALADM  "."SEQUENCE_TBX" PCTFREE 0;

COMMENT ON TABLE "GALADM  "."SEQUENCE_TBX" IS 'RMT Sequence';


-- DDL Statements for Primary Key on Table "GALADM  "."SEQUENCE_TBX"

ALTER TABLE "GALADM  "."SEQUENCE_TBX" 
	ADD CONSTRAINT "SEQUENCE_PK" PRIMARY KEY
		("SEQUENCE_ID_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."SEQUENCE_TR1";

CREATE TRIGGER GALADM.SEQUENCE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."SEQUENCE_TR2";

CREATE TRIGGER GALADM.SEQUENCE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


