
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SKIPPED_PRODUCT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SKIPPED_PRODUCT_TBX";


CREATE TABLE "GALADM  "."SKIPPED_PRODUCT_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16 OCTETS) NOT NULL , 
		  "SUB_ID" CHAR(2 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "STATUS" SMALLINT WITH DEFAULT 0 , 
		  "SKIP_TIMESTAMP" TIMESTAMP , 
		  "DISABLE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."SKIPPED_PRODUCT_TBX" IS 'RMT SkippedProduct for tracking which products were skipped per plan';


-- DDL Statements for Primary Key on Table "GALADM  "."SKIPPED_PRODUCT_TBX"

ALTER TABLE "GALADM  "."SKIPPED_PRODUCT_TBX" 
	ADD CONSTRAINT "SKIPPED_PRODUCT_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PROCESS_POINT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SKIPPED_PRODUCT_TR1";

CREATE TRIGGER GALADM.SKIPPED_PRODUCT_TR1 NO CASCADE BEFORE INSERT ON GALADM.SKIPPED_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SKIPPED_PRODUCT_TR2";

CREATE TRIGGER GALADM.SKIPPED_PRODUCT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.SKIPPED_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


