
------------------------------------------------
-- DDL Statements for Table "GALADM  "."STANDARD_SCHEDULE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."STANDARD_SCHEDULE_TBX";


CREATE TABLE "GALADM  "."STANDARD_SCHEDULE_TBX"  (
		  "PLANT_CODE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "LINE_NO" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "DAY_OF_WEEK" CHAR(3 OCTETS) NOT NULL , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PERIOD" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "PERIOD_LABEL" CHAR(5 OCTETS) , 
		  "TYPE" CHAR(3 OCTETS) , 
		  "PLAN" CHAR(1 OCTETS) , 
		  "NEXT_DAY" SMALLINT WITH DEFAULT 0 , 
		  "CAPACITY" INTEGER WITH DEFAULT 0 , 
		  "CAPACITY_ON" INTEGER WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "START_TIME" TIME , 
		  "END_TIME" TIME )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."STANDARD_SCHEDULE_TBX" IS 'RMT StandardSchedule';


-- DDL Statements for Primary Key on Table "GALADM  "."STANDARD_SCHEDULE_TBX"

ALTER TABLE "GALADM  "."STANDARD_SCHEDULE_TBX" 
	ADD CONSTRAINT "STANDARD_SCHEDULE_PK" PRIMARY KEY
		("PLANT_CODE",
		 "LINE_NO",
		 "PROCESS_LOCATION",
		 "DAY_OF_WEEK",
		 "SHIFT",
		 "PERIOD");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STANDARD_SCHEDULE_TR1";

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR1 NO CASCADE BEFORE INSERT ON
GALADM.STANDARD_SCHEDULE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STANDARD_SCHEDULE_TR2";

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.STANDARD_SCHEDULE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


