
------------------------------------------------
-- DDL Statements for Table "GALADM  "."STATION_USER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."STATION_USER_TBX";


CREATE TABLE "GALADM  "."STATION_USER_TBX"  (
		  "HOST_NAME" CHAR(32 OCTETS) NOT NULL , 
		  "USER" CHAR(11 OCTETS) NOT NULL , 
		  "LOGIN_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."STATION_USER_TBX" IS 'Users logged on the station';


-- DDL Statements for Indexes on Table "GALADM  "."STATION_USER_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."STATION_USER_I1" ON "GALADM  "."STATION_USER_TBX" 
		("HOST_NAME" ASC,
		 "USER" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."STATION_USER_TBX"

ALTER TABLE "GALADM  "."STATION_USER_TBX" 
	ADD CONSTRAINT "STATION_USER_PK" PRIMARY KEY
		("HOST_NAME",
		 "USER");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STATION_USER_TR1";

CREATE TRIGGER GALADM.STATION_USER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.STATION_USER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STATION_USER_TR2";

CREATE TRIGGER GALADM.STATION_USER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.STATION_USER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


