
------------------------------------------------
-- DDL Statements for Table "GALADM  "."STRAGGLER_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."STRAGGLER_TBX";


CREATE TABLE "GALADM  "."STRAGGLER_TBX"  (
		  "PRODUCT_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "PP_DELAYED_AT" VARCHAR(16 OCTETS) NOT NULL ,
		  "STRAGGLER_TYPE"  CHARACTER(10) NOT NULL WITH DEFAULT ‘LOT’,
		  "IDENTIFIED_TIMESTAMP" TIMESTAMP , 
		  "LAST_PASSING_PROCESS_POINT" VARCHAR(16 OCTETS) , 
		  "UNITS_BEHIND" INTEGER , 
		  "ACTUAL_PROCESS_TIMESTAMP" TIMESTAMP , 
		  "ACTUAL_UNITS_BEHIND" INTEGER , 
		  "CODE" VARCHAR(64 OCTETS) , 
		  "COMMENTS" VARCHAR(256) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."STRAGGLER_TBX" IS 'Straggler';


-- DDL Statements for Primary Key on Table "GALADM  "."STRAGGLER_TBX"

ALTER TABLE "GALADM  "."STRAGGLER_TBX" 
	ADD CONSTRAINT "STRAGGLER_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "PP_DELAYED_AT",
		 "STRAGGLER_TYPE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STRAGGLER_TR1";

CREATE TRIGGER GALADM.STRAGGLER_TR1 NO CASCADE BEFORE INSERT ON GALADM.STRAGGLER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."STRAGGLER_TR2";

CREATE TRIGGER GALADM.STRAGGLER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.STRAGGLER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


