
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TBX";


CREATE TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TBX"  (
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "SUB_ID" CHAR(2 OCTETS) NOT NULL , 
		  "PRODUCT_SEQ_NO" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "PRODUCT_ID" CHAR(17 OCTETS) , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "STATUS" INTEGER WITH DEFAULT 0 , 
		  "CONTAINER_ID" CHAR(10 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TBX"

ALTER TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TBX" 
	ADD CONSTRAINT "SUB_PRODUCT_SHIPPING_DETAIL_PK" PRIMARY KEY
		("KD_LOT_NUMBER",
		 "PRODUCTION_LOT",
		 "SUB_ID",
		 "PRODUCT_SEQ_NO");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TR1";

CREATE TRIGGER GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TR1 NO CASCADE BEFORE
INSERT ON GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX REFERENCING NEW AS A FOR
EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_SHIPPING_DETAIL_TR2";

CREATE TRIGGER GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX REFERENCING NEW AS A FOR
EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


