
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SUB_PRODUCT_SHIPPING_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_TBX";


CREATE TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_TBX"  (
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "LINE_NUMBER" CHAR(2 OCTETS) , 
		  "PRODUCTION_DATE" DATE , 
		  "SEQ_NO" INTEGER WITH DEFAULT 0 , 
		  "STATUS" SMALLINT WITH DEFAULT 0 , 
		  "SCH_QUANTITY" SMALLINT WITH DEFAULT 0 , 
		  "ACT_QUANTITY" SMALLINT WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT1"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."SUB_PRODUCT_SHIPPING_TBX"

ALTER TABLE "GALADM  "."SUB_PRODUCT_SHIPPING_TBX" 
	ADD CONSTRAINT "SUB_PROD_SHIP_PK" PRIMARY KEY
		("KD_LOT_NUMBER",
		 "PRODUCTION_LOT");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_SHIPPING_TR1";

CREATE TRIGGER GALADM.SUB_PRODUCT_SHIPPING_TR1 NO CASCADE BEFORE INSERT
ON GALADM.SUB_PRODUCT_SHIPPING_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_SHIPPING_TR2";

CREATE TRIGGER GALADM.SUB_PRODUCT_SHIPPING_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.SUB_PRODUCT_SHIPPING_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


