
------------------------------------------------
-- DDL Statements for Table "GALADM  "."SUB_PRODUCT_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."SUB_PRODUCT_TBX";


CREATE TABLE "GALADM  "."SUB_PRODUCT_TBX"  (
		  "PRODUCT_ID" CHAR(17 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) , 
		  "KD_LOT_NUMBER" CHAR(18 OCTETS) , 
		  "PRODUCT_TYPE" CHAR(10 OCTETS) , 
		  "PRODUCT_SPEC_CODE" CHAR(22 OCTETS) , 
		  "SUB_ID" CHAR(2 OCTETS) , 
		  "PLAN_OFF_DATE" DATE , 
		  "TRACKING_STATUS" CHAR(16 OCTETS) , 
		  "PRODUCT_START_DATE" DATE , 
		  "ACTUAL_OFF_DATE" DATE , 
		  "AUTO_HOLD_STATUS" SMALLINT WITH DEFAULT 0 , 
		  "PRODUCTION_DATE" DATE , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "DEFECT_STATUS" SMALLINT , 
		  "DUNNAGE" VARCHAR(12 OCTETS) )   
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."SUB_PRODUCT_TBX" IS 'RMT SubProduct for subassembly products';


-- DDL Statements for Primary Key on Table "GALADM  "."SUB_PRODUCT_TBX"

ALTER TABLE "GALADM  "."SUB_PRODUCT_TBX" 
	ADD CONSTRAINT "SUB_PRODUCT_PK" PRIMARY KEY
		("PRODUCT_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_TR1";

CREATE TRIGGER GALADM.SUB_PRODUCT_TR1 NO CASCADE BEFORE INSERT ON GALADM.SUB_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SUB_PRODUCT_TR2";

CREATE TRIGGER GALADM.SUB_PRODUCT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.SUB_PRODUCT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


