
------------------------------------------------
-- DDL Statements for Table "VIOS    "."TBLKNOWLEDGESTATUS"
------------------------------------------------
 
DROP TABLE "VIOS    "."TBLKNOWLEDGESTATUS";


CREATE TABLE "VIOS    "."TBLKNOWLEDGESTATUS"  (
		  "USER_LOGON_ID_NO" CHAR(7 OCTETS) NOT NULL , 
		  "PROCESS_ID" INTEGER NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "MTC_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "PROCESS_NO" CHAR(5 OCTETS) NOT NULL , 
		  "PROCLINENO" CHAR(1 OCTETS) NOT NULL , 
		  "PROCTEAM" CHAR(4 OCTETS) NOT NULL , 
		  "PROCDESC" CHAR(35 OCTETS) NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "KNOWLEDGESTATUS_NO" INTEGER NOT NULL , 
		  "ENTEREDBY_UID" CHAR(7 OCTETS) NOT NULL , 
		  "ENTERED_TSTP" TIMESTAMP NOT NULL , 
		  "DAYSFLAG" VARCHAR(1 OCTETS) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "KNOWLEDGE_NOTE_TEXT" VARCHAR(250 OCTETS) , 
		  "PRODRATE" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."TBLKNOWLEDGESTATUS" IS 'RMT VIOS TBLKNOWLEDGESTATUS';


-- DDL Statements for Primary Key on Table "VIOS    "."TBLKNOWLEDGESTATUS"

ALTER TABLE "VIOS    "."TBLKNOWLEDGESTATUS" 
	ADD CONSTRAINT "TBLKNOWLEDGESTATUS_PK" PRIMARY KEY
		("USER_LOGON_ID_NO",
		 "PROCESS_ID",
		 "MODEL_YEAR_DATE",
		 "MTC_MODEL",
		 "EXTRACT_DATE");



-- DDL Statements for Indexes on Table "VIOS    "."TBLKNOWLEDGESTATUS"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."TBLKNOWLEDGESTATUS_I1" ON "VIOS    "."TBLKNOWLEDGESTATUS" 
		("USER_LOGON_ID_NO" ASC,
		 "PROCESS_ID" ASC,
		 "MODEL_YEAR_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "VIOS    "."TBLKNOWLEDGESTATUS"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."TBLKNOWLEDGESTATUS_I2" ON "VIOS    "."TBLKNOWLEDGESTATUS" 
		("PROCESS_ID" ASC,
		 "MODEL_YEAR_DATE" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLKNOWLEDGESTATUS_TR1";

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLKNOWLEDGESTATUS_TR2";

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


