
------------------------------------------------
-- DDL Statements for Table "VIOS    "."TBLROTATION_PROCESS"
------------------------------------------------
 
DROP TABLE "VIOS    "."TBLROTATION_PROCESS";


CREATE TABLE "VIOS    "."TBLROTATION_PROCESS"  (
		  "ROTATION_PROCESS_ID" INTEGER NOT NULL , 
		  "ROTATEREC_NO" INTEGER NOT NULL , 
		  "PROCESS_ID" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "ASM_PROC_NO" CHAR(5 OCTETS) NOT NULL , 
		  "ASM_PROC_NAME" CHAR(35 OCTETS) NOT NULL , 
		  "VEHICLE_MODEL_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "VMC_DESCRIPTION" CHAR(35 OCTETS) NOT NULL , 
		  "MODEL_YEAR_DATE" DECIMAL(5,1) NOT NULL , 
		  "PROD_SCH_QTY" INTEGER NOT NULL , 
		  "EFF_BEG_DATE" TIMESTAMP NOT NULL , 
		  "EFF_END_DATE" TIMESTAMP NOT NULL , 
		  "PROCESS_STATUS" SMALLINT NOT NULL , 
		  "DAYSFLAG" VARCHAR(1 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."TBLROTATION_PROCESS" IS 'RMT VIOS TBLROTATION_PROCESS';


-- DDL Statements for Primary Key on Table "VIOS    "."TBLROTATION_PROCESS"

ALTER TABLE "VIOS    "."TBLROTATION_PROCESS" 
	ADD CONSTRAINT "TBLROTATION_PROCESS_PK" PRIMARY KEY
		("ROTATEREC_NO",
		 "PROCESS_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLROTATION_PROCESS_TR1";

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLROTATION_PROCESS_TR2";

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


