
------------------------------------------------
-- DDL Statements for Table "VIOS    "."TBLROTATION"
------------------------------------------------
 
DROP TABLE "VIOS    "."TBLROTATION";


CREATE TABLE "VIOS    "."TBLROTATION"  (
		  "ROTATEREC_NO" INTEGER NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "PCAREA_ID" INTEGER NOT NULL , 
		  "TEAM_NO" CHAR(4 OCTETS) NOT NULL , 
		  "TEAM_GROUP_ID" INTEGER NOT NULL , 
		  "RECORDDATE" TIMESTAMP NOT NULL , 
		  "RECORDSHIFT" SMALLINT NOT NULL , 
		  "RECORDQTR" SMALLINT NOT NULL , 
		  "MPTAG_NO" INTEGER NOT NULL , 
		  "TAG_GROUP_ID" INTEGER NOT NULL , 
		  "USER_LOGON_ID_NO" CHAR(7 OCTETS) NOT NULL , 
		  "PAIRTYPE" SMALLINT NOT NULL , 
		  "ENTEREDBY_UID" CHAR(7 OCTETS) NOT NULL , 
		  "ENTERED_TSTP" TIMESTAMP NOT NULL , 
		  "DAYSFLAG" VARCHAR(1 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "ERGOTYPE" CHAR(1 OCTETS) , 
		  "COMMENT" VARCHAR(250 OCTETS) , 
		  "REASONCODE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "VIOSTBSDAT1" INDEX IN "VIOSTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "VIOS    "."TBLROTATION" IS 'RMT VIOS TBLROTATION';


-- DDL Statements for Primary Key on Table "VIOS    "."TBLROTATION"

ALTER TABLE "VIOS    "."TBLROTATION" 
	ADD CONSTRAINT "TBLROTATION_PK" PRIMARY KEY
		("ROTATEREC_NO");



-- DDL Statements for Indexes on Table "VIOS    "."TBLROTATION"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."TBLROTATION_I1" ON "VIOS    "."TBLROTATION" 
		("PCAREA_ID" ASC,
		 "TEAM_NO" ASC,
		 "RECORDDATE" ASC,
		 "USER_LOGON_ID_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "VIOS    "."TBLROTATION"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "VIOS    "."TBLROTATION_I2" ON "VIOS    "."TBLROTATION" 
		("MPTAG_NO" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;






-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLROTATION_TR1";

CREATE TRIGGER VIOS.TBLROTATION_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "VIOS    "."TBLROTATION_TR2";

CREATE TRIGGER VIOS.TBLROTATION_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


