
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TEAM_ROTATION_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TEAM_ROTATION_TBX";


CREATE TABLE "GALADM  "."TEAM_ROTATION_TBX"  (
		  "LINE_NO" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PROCESS_LOCATION" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PLANT_CODE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "PRODUCTION_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "SHIFT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT '' , 
		  "TEAM" VARCHAR(10 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT6" INDEX IN "GALTBSIDX2"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."TEAM_ROTATION_TBX" IS 'RMT used to track TEAM shift rotation';


-- DDL Statements for Primary Key on Table "GALADM  "."TEAM_ROTATION_TBX"

ALTER TABLE "GALADM  "."TEAM_ROTATION_TBX" 
	ADD CONSTRAINT "TEAM_ROTATION_PK" PRIMARY KEY
		("LINE_NO",
		 "PROCESS_LOCATION",
		 "PLANT_CODE",
		 "PRODUCTION_DATE",
		 "SHIFT",
		 "TEAM");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TEAM_ROTATION_TR1";

CREATE TRIGGER GALADM.TEAM_ROTATION_TR1 NO CASCADE BEFORE INSERT ON GALADM.TEAM_ROTATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TEAM_ROTATION_TR2";

CREATE TRIGGER GALADM.TEAM_ROTATION_TR2 NO CASCADE BEFORE UPDATE ON GALADM.TEAM_ROTATION_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


