
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TEMPLATES_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TEMPLATES_TBX";


CREATE TABLE "GALADM  "."TEMPLATES_TBX"  (
		  "TEMPLATE_NAME" VARCHAR(40 OCTETS) NOT NULL , 
		  "TEMPLATE_DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "TEMPLATE_TYPE" VARCHAR(32 OCTETS) , 
		  "TEMPLATE_DATA" BLOB(10485760) LOGGED COMPACT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "FORM_ID" VARCHAR(32 OCTETS) , 
		  "REVISION_ID" INTEGER )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBS32K1" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."TEMPLATES_TBX" IS 'RMT Template for LOT CONTROL to define Printing Templates';


-- DDL Statements for Primary Key on Table "GALADM  "."TEMPLATES_TBX"

ALTER TABLE "GALADM  "."TEMPLATES_TBX" 
	ADD CONSTRAINT "TEMPLATES_PK" PRIMARY KEY
		("TEMPLATE_NAME");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."TEMPLATES_TR1";

CREATE TRIGGER GALADM.TEMPLATES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TEMPLATES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."TEMPLATES_TR2";

CREATE TRIGGER GALADM.TEMPLATES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TEMPLATES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


