
------------------------------------------------
-- DDL Statements for Table "GALADM"."TERMINAL_TYPE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM"."TERMINAL_TYPE_TBX";


CREATE TABLE GALADM.TERMINAL_TYPE_TBX (
  TERMINAL_FLAG SMALLINT NOT NULL DEFAULT,
  NAME	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  ) 
  IN GALTBSREF11
  INDEX IN GALTBSIDX4
  ORGANIZE BY ROW;

ALTER TABLE GALADM.TERMINAL_TYPE_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.TERMINAL_TYPE_TBX IS 'RMT Terminal Type';

SET SCHEMA = QGALINST;

GRANT DELETE ON TABLE GALADM.TERMINAL_TYPE_TBX TO USER GALPURG;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.TERMINAL_TYPE_TBX TO USER DBQREP;

GRANT ALTER, DELETE, INDEX, INSERT, SELECT, REFERENCES, UPDATE ON TABLE GALADM.TERMINAL_TYPE_TBX TO USER GALINST1 WITH GRANT OPTION;

GRANT CONTROL ON TABLE GALADM.TERMINAL_TYPE_TBX TO USER GALINST1;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.TERMINAL_TYPE_TBX TO GROUP GALC_A;

GRANT SELECT ON TABLE GALADM.TERMINAL_TYPE_TBX TO GROUP GALC_R;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.TERMINAL_TYPE_TBX TO GROUP GALCQA_A;

GRANT SELECT ON TABLE GALADM.TERMINAL_TYPE_TBX TO GROUP GALCQA_S;

-- Step 2. Restoring constraints and indexes
ALTER TABLE GALADM.TERMINAL_TYPE_TBX
  ADD PRIMARY KEY
    (TERMINAL_FLAG)
    ENFORCED;

COMMIT;

-- Step 3. Runstats
RUNSTATS ON TABLE GALADM.TERMINAL_TYPE_TBX
	ALLOW WRITE ACCESS;

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM"."TERMINAL_TYPE_TR1";

CREATE TRIGGER GALADM.TERMINAL_TYPE_TR1 NO CASCADE BEFORE INSERT ON GALADM.TERMINAL_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM"."TERMINAL_TYPE_TR2";

CREATE TRIGGER GALADM.TERMINAL_TYPE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.TERMINAL_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;