
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TGA3021_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TGA3021_TBX";


CREATE TABLE "GALADM  "."TGA3021_TBX"  (
		  "PLAN_CODE" CHAR(11 OCTETS) NOT NULL , 
		  "LINE_NUMBER" CHAR(2 OCTETS) NOT NULL , 
		  "PLAN_PROC_LOC" CHAR(2 OCTETS) NOT NULL , 
		  "DAY_OF_WEEK" CHAR(3 OCTETS) NOT NULL , 
		  "VALID_DATE" DATE NOT NULL , 
		  "PERIOD" CHAR(3 OCTETS) NOT NULL , 
		  "SHIFT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "LABEL_NAME" CHAR(5 OCTETS) NOT NULL , 
		  "WORK_TYPE" CHAR(3 OCTETS) NOT NULL , 
		  "WORK_PLAN_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "WORK_START_TIME" TIME NOT NULL , 
		  "WORK_END_TIME" TIME NOT NULL , 
		  "NEXT_DAY" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "ROW_PROCESSED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."TGA3021_TBX"

ALTER TABLE "GALADM  "."TGA3021_TBX" 
	ADD CONSTRAINT "TGA3021_PK" PRIMARY KEY
		("PLAN_CODE",
		 "LINE_NUMBER",
		 "PLAN_PROC_LOC",
		 "DAY_OF_WEEK",
		 "VALID_DATE",
		 "PERIOD",
		 "CREATE_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3021_TR1";

CREATE TRIGGER GALADM.TGA3021_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3021_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3021_TR2";

CREATE TRIGGER GALADM.TGA3021_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3021_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


