
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TGA3051_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TGA3051_TBX";


CREATE TABLE "GALADM  "."TGA3051_TBX"  (
		  "AFAE_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "PLAN_CODE" CHAR(11 OCTETS) NOT NULL , 
		  "LINE_NUMBER" CHAR(2 OCTETS) NOT NULL , 
		  "PLAN_PROC_LOC" CHAR(2 OCTETS) NOT NULL , 
		  "WE_LINE_NUMBER" CHAR(2 OCTETS) NOT NULL , 
		  "WE_PLAN_PROC_LOC" CHAR(2 OCTETS) NOT NULL , 
		  "PA_LINE_NUMBER" CHAR(2 OCTETS) NOT NULL , 
		  "PA_PLAN_PROC_LOC" CHAR(2 OCTETS) NOT NULL , 
		  "AFAE_OFF_DATE" DATE NOT NULL , 
		  "PROD_SEQ_NUMBER" CHAR(12 OCTETS) NOT NULL , 
		  "DEMAND_TYPE" CHAR(2 OCTETS) NOT NULL , 
		  "KD_LOT_NO" CHAR(18 OCTETS) NOT NULL , 
		  "MODEL_YEAR_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "MODEL_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "MODEL_TYPE_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "MODEL_OPTION" CHAR(3 OCTETS) NOT NULL , 
		  "EXT_COLOUR_CODE" CHAR(10 OCTETS) NOT NULL , 
		  "INT_COLOUR_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "NO_OF_UNITS" INTEGER NOT NULL , 
		  "START_VIN_NUMBER" CHAR(17 OCTETS) NOT NULL , 
		  "REMAKE_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "Y_N_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "CARRY_I_O_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "NO_OF_UNITS_CICO" INTEGER NOT NULL , 
		  "PLAN_CREATED" CHAR(1 OCTETS) NOT NULL , 
		  "CREATE_DATE" DATE NOT NULL WITH DEFAULT CURRENT DATE , 
		  "ROW_PROCESSED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."TGA3051_TBX"

ALTER TABLE "GALADM  "."TGA3051_TBX" 
	ADD CONSTRAINT "TGA3051_PK" PRIMARY KEY
		("AFAE_FLAG",
		 "PLAN_CODE",
		 "LINE_NUMBER",
		 "PLAN_PROC_LOC",
		 "WE_LINE_NUMBER",
		 "WE_PLAN_PROC_LOC",
		 "PA_LINE_NUMBER",
		 "PA_PLAN_PROC_LOC",
		 "AFAE_OFF_DATE",
		 "PROD_SEQ_NUMBER",
		 "CREATE_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3051_TR1";

CREATE TRIGGER GALADM.TGA3051_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3051_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3051_TR2";

CREATE TRIGGER GALADM.TGA3051_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3051_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


