
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TGA3061_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TGA3061_TBX";


CREATE TABLE "GALADM  "."TGA3061_TBX"  (
		  "CALENDAR_DATE" CHAR(8 OCTETS) NOT NULL , 
		  "DAY_OF_WEEK" CHAR(3 OCTETS) NOT NULL , 
		  "WEEK_NUMBER" CHAR(6 OCTETS) , 
		  "UPDATE_TSTMP" TIMESTAMP NOT NULL , 
		  "UPDATE_UID" CHAR(8 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT9" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "GALADM  "."TGA3061_TBX"

ALTER TABLE "GALADM  "."TGA3061_TBX" 
	ADD CONSTRAINT "TGA3061_PK" PRIMARY KEY
		("CALENDAR_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3061_TR1";

CREATE TRIGGER GALADM.TGA3061_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3061_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TGA3061_TR2";

CREATE TRIGGER GALADM.TGA3061_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3061_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


