
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TRAILER_INFO_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TRAILER_INFO_TBX";


CREATE TABLE "GALADM  "."TRAILER_INFO_TBX"  (
		  "TRAILER_ID" INTEGER NOT NULL , 
		  "TRAILER_NUMBER" VARCHAR(10 OCTETS) , 
		  "SCH_QTY" INTEGER NOT NULL , 
		  "ACT_QTY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "STATUS" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."TRAILER_INFO_TBX" IS 'RMT ShippingTrailerInfo';


-- DDL Statements for Primary Key on Table "GALADM  "."TRAILER_INFO_TBX"

ALTER TABLE "GALADM  "."TRAILER_INFO_TBX" 
	ADD CONSTRAINT "TRAILER_INFO_PK" PRIMARY KEY
		("TRAILER_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TRAILER_INFO_TR1";

CREATE TRIGGER GALADM.TRAILER_INFO_TR1 NO CASCADE BEFORE INSERT ON GALADM.TRAILER_INFO_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TRAILER_INFO_TR2";

CREATE TRIGGER GALADM.TRAILER_INFO_TR2 NO CASCADE BEFORE UPDATE ON GALADM.TRAILER_INFO_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


