
------------------------------------------------
-- DDL Statements for Table "GALADM  "."TRAILER_STATUS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."TRAILER_STATUS_TBX";


CREATE TABLE "GALADM  "."TRAILER_STATUS_TBX"  (
		  "TRAILER_ID" INTEGER NOT NULL , 
		  "STATUS" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."TRAILER_STATUS_TBX" IS 'RMT ShippingTrailerStatus';


-- DDL Statements for Primary Key on Table "GALADM  "."TRAILER_STATUS_TBX"

ALTER TABLE "GALADM  "."TRAILER_STATUS_TBX" 
	ADD CONSTRAINT "TRAILER_STATUS_PK" PRIMARY KEY
		("TRAILER_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TRAILER_STATUS_TR1";

CREATE TRIGGER GALADM.TRAILER_STATUS_TR1 NO CASCADE BEFORE INSERT ON GALADM.TRAILER_STATUS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."TRAILER_STATUS_TR2";

CREATE TRIGGER GALADM.TRAILER_STATUS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.TRAILER_STATUS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


