DROP TRIGGER GALADM.TRAILER_TR1;
DROP TRIGGER GALADM.TRAILER_TR2;
DROP TABLE GALADM.TRAILER_TBX;

CREATE TABLE "GALADM"."TRAILER_TBX"
(
   TRAILER_NUMBER varchar(10) PRIMARY KEY NOT NULL,
   TRAILER_CAPACITY int,
   STATUS int,
   EMPTY_CARRIER_COUNT int DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp
);

CREATE TRIGGER GALADM.TRAILER_TR1 NO CASCADE BEFORE INSERT ON GALADM.TRAILER_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TRAILER_TR2 NO CASCADE BEFORE UPDATE ON GALADM.TRAILER_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
