
------------------------------------------------
-- DDL Statements for Table "VIOS    "."TRAINING_STATUS"
------------------------------------------------
 
DROP TABLE "VIOS    "."TRAINING_STATUS";


CREATE TABLE "VIOS    "."TRAINING_STATUS"  (
		  "TRAINING_STATUS_ID" BIGINT NOT NULL , 
		  "PROCESS_ID" BIGINT NOT NULL , 
		  "MODEL_YEAR" CHAR(4 OCTETS) NOT NULL , 
		  "MTC_MODEL" CHAR(3 OCTETS) NOT NULL , 
		  "STATUS_ID" SMALLINT NOT NULL , 
		  "NOTE" VARCHAR(250 OCTETS) , 
		  "PROD_RATE" INTEGER , 
		  "DAYS_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "LAST_UPDATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "USER_ID" CHAR(7 OCTETS) NOT NULL , 
		  "SCANNED_TRAINER_ID" VARCHAR(100 OCTETS) , 
		  "SCANNED_TRAINEE_ID" VARCHAR(100 OCTETS) , 
		  "ELECTRONIC_SIGN_TSTP" TIMESTAMP , 
		  "SCANNED_TRAINER_TSTP" TIMESTAMP , 
		  "SCANNED_TRAINEE_TSTP" TIMESTAMP , 
		  "IS_AVAILABLE" SMALLINT NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."TRAINING_STATUS"

ALTER TABLE "VIOS    "."TRAINING_STATUS" 
	ADD CONSTRAINT "TRAINING_STATUS_PK" PRIMARY KEY
		("TRAINING_STATUS_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."TRAINING_STATUS_TR1";

CREATE TRIGGER VIOS.TRAINING_STATUS_TR1 NO CASCADE BEFORE INSERT ON VIOS.TRAINING_STATUS
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."TRAINING_STATUS_TR2";

CREATE TRIGGER VIOS.TRAINING_STATUS_TR2 NO CASCADE BEFORE UPDATE ON VIOS.TRAINING_STATUS
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


