
------------------------------------------------
-- DDL Statements for Table "VIOS    "."TRAINING_PROCESS"
------------------------------------------------
 
DROP TABLE "VIOS    "."TRAINING_PROCESS";


CREATE TABLE "VIOS    "."TRAINING_PROCESS"  (
		  "PROCESS_ID" BIGINT NOT NULL , 
		  "PROCESS_NO" CHAR(5 OCTETS) NOT NULL , 
		  "LINE_NUM" SMALLINT , 
		  "TEAM_ID" INTEGER , 
		  "PROCESS_DESC" VARCHAR(35 OCTETS) NOT NULL , 
		  "BODY_LOC_NO" CHAR(4 OCTETS) NOT NULL , 
		  "LAST_UPDATED_BY" CHAR(7 OCTETS) NOT NULL , 
		  "LAST_UPDATED_DATE" TIMESTAMP NOT NULL , 
		  "PROCESSID" INTEGER , 
		  "PLANT_LOC_CODE" CHAR(1 OCTETS) NOT NULL , 
		  "DEPT_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "EXTRACT_DATE" TIMESTAMP NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "VIOSTBSDAT2" INDEX IN "VIOSTBSIDX2"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "VIOS    "."TRAINING_PROCESS"

ALTER TABLE "VIOS    "."TRAINING_PROCESS" 
	ADD CONSTRAINT "TRAINING_PROCESS_PK" PRIMARY KEY
		("PROCESS_ID",
		 "PLANT_LOC_CODE",
		 "DEPT_CODE",
		 "LAST_UPDATED_DATE",
		 "EXTRACT_DATE");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."TRAINING_PROCESS_TR1";

CREATE TRIGGER VIOS.TRAINING_PROCESS_TR1 NO CASCADE BEFORE INSERT ON VIOS.TRAINING_PROCESS
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP =
CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "VIOS    ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";

DROP TRIGGER "VIOS    "."TRAINING_PROCESS_TR2";

CREATE TRIGGER VIOS.TRAINING_PROCESS_TR2 NO CASCADE BEFORE UPDATE ON VIOS.TRAINING_PROCESS
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP =
CURRENT_TIMESTAMP;


