
------------------------------------------------
-- DDL Statements for Table "GALADM  "."VANNING_SCHEDULE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."VANNING_SCHEDULE_TBX";


CREATE TABLE "GALADM  "."VANNING_SCHEDULE_TBX"  (
		  "PRODUCTION_DATE" DATE NOT NULL , 
		  "VANNING_SEQ" INTEGER NOT NULL , 
		  "TRAILER_ID" INTEGER , 
		  "KD_LOT" CHAR(18 OCTETS) NOT NULL , 
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "YMTO" CHAR(9 OCTETS) NOT NULL , 
		  "SCH_QTY" INTEGER NOT NULL , 
		  "ACT_QTY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."VANNING_SCHEDULE_TBX" IS 'RMT ShippingVanningSchedule';


-- DDL Statements for Primary Key on Table "GALADM  "."VANNING_SCHEDULE_TBX"

ALTER TABLE "GALADM  "."VANNING_SCHEDULE_TBX" 
	ADD CONSTRAINT "VANNING_SCHEDULE_PK" PRIMARY KEY
		("PRODUCTION_DATE",
		 "VANNING_SEQ");


-- DDL Statements for Aliases based on Table "GALADM  "."VANNING_SCHEDULE_TBX"

DROP ALIAS "GALADM  "."VANNING_SCHEDULE_TBX";

CREATE ALIAS "GALADM  "."VANNING_SCHEDULE_TBX" FOR TABLE "GALADM  "."VANNING_SCHEDULE_TBX";

COMMENT ON ALIAS "GALADM  "."VANNING_SCHEDULE_TBX" IS 'RMT alias to VANNING_SCHEDULE_TBX';







-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."VANNING_SCHEDULE_TR1";

CREATE TRIGGER GALADM.VANNING_SCHEDULE_TR1 NO CASCADE BEFORE INSERT ON GALADM.VANNING_SCHEDULE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."VANNING_SCHEDULE_TR2";

CREATE TRIGGER GALADM.VANNING_SCHEDULE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.VANNING_SCHEDULE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


