
------------------------------------------------
-- DDL Statements for Table "GALADM  "."VIEW_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."VIEW_TBX";


CREATE TABLE "GALADM  "."VIEW_TBX"  (
		  "VIEW_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "LAYER_ID" VARCHAR(32 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."VIEW_TBX" IS 'RMT View describes collection of Layers';


-- DDL Statements for Primary Key on Table "GALADM  "."VIEW_TBX"

ALTER TABLE "GALADM  "."VIEW_TBX" 
	ADD CONSTRAINT "VIEW_PK" PRIMARY KEY
		("VIEW_ID",
		 "LAYER_ID");








-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."VIEW_TR1";

CREATE TRIGGER GALADM.VIEW_TR1 NO CASCADE BEFORE INSERT ON GALADM.VIEW_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."VIEW_TR2";

CREATE TRIGGER GALADM.VIEW_TR2 NO CASCADE BEFORE UPDATE ON GALADM.VIEW_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


