------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."VIN_PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."VIN_PART";


CREATE TABLE "LCVINBOM  "."VIN_PART"  (
		  "PRODUCT_ID" VARCHAR(255 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "SHIP_STATUS" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."VIN_PART" IS 'VIN-BOM Part Number Assignment for LET System and VIN';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."VIN_PART"

ALTER TABLE "LCVINBOM  "."VIN_PART" 
	ADD CONSTRAINT "VIN_PART_PK" PRIMARY KEY
		("PRODUCT_ID","LET_SYSTEM_NAME","DC_PART_NUMBER");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_TR1";

CREATE TRIGGER LCVINBOM.VIN_PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.VIN_PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_TR2";

CREATE TRIGGER LCVINBOM.VIN_PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.VIN_PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;