
------------------------------------------------
-- DDL Statements for Table "GALADM  "."WSBUILDS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."WSBUILDS_TBX";


CREATE TABLE "GALADM  "."WSBUILDS_TBX"  (
		  "BUILD_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "URL" VARCHAR(120 OCTETS) NOT NULL , 
		  "DEFAULT_BUILD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "BUILD_DATE" DATE , 
		  "DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."WSBUILDS_TBX" IS 'RMT WebStartBuild for Web Start to define build numbers';


-- DDL Statements for Indexes on Table "GALADM  "."WSBUILDS_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."WSBUILDSI1" ON "GALADM  "."WSBUILDS_TBX" 
		("BUILD_ID" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."WSBUILDS_TBX"

ALTER TABLE "GALADM  "."WSBUILDS_TBX" 
	ADD CONSTRAINT "WSBUILDSPK" PRIMARY KEY
		("BUILD_ID");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSBUILDS_TR1";

CREATE TRIGGER GALADM.WSBUILDS_TR1 NO CASCADE BEFORE INSERT ON GALADM.WSBUILDS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSBUILDS_TR2";

CREATE TRIGGER GALADM.WSBUILDS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.WSBUILDS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


