
------------------------------------------------
-- DDL Statements for Table "GALADM  "."WSCLIENTS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."WSCLIENTS_TBX";


CREATE TABLE "GALADM  "."WSCLIENTS_TBX"  (
		  "IP_ADDRESS" VARCHAR(255 OCTETS) NOT NULL , 
		  "HOST_NAME" VARCHAR(32 OCTETS) NOT NULL , 
		  "DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "BUILD_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "ASSET_NUMBER" VARCHAR(20 OCTETS) WITH DEFAULT '' , 
		  "COLUMN_LOCATION" VARCHAR(20 OCTETS) WITH DEFAULT '' , 
		  "HEARTBEAT_TIMESTAMP" TIMESTAMP , 
		  "SHUTDOWN_FLAG" INTEGER WITH DEFAULT -1 , 
		  "FEATURE_ID" VARCHAR(32 OCTETS) , 
		  "FEATURE_TYPE" VARCHAR(32 OCTETS) , 
		  "PHONE_EXTENSION" CHAR(10 OCTETS) )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."WSCLIENTS_TBX" IS 'RMT WebStartClient for Web Start to define Clients';


-- DDL Statements for Indexes on Table "GALADM  "."WSCLIENTS_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."WSCLIENTSI1" ON "GALADM  "."WSCLIENTS_TBX" 
		("IP_ADDRESS" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."WSCLIENTS_TBX"

ALTER TABLE "GALADM  "."WSCLIENTS_TBX" 
	ADD CONSTRAINT "WSCLIENTSPK" PRIMARY KEY
		("IP_ADDRESS");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSCLIENTS_TR1";

CREATE TRIGGER GALADM.WSCLIENTS_TR1 NO CASCADE BEFORE INSERT ON GALADM.WSCLIENTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSCLIENTS_TR2";

CREATE TRIGGER GALADM.WSCLIENTS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.WSCLIENTS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


