
------------------------------------------------
-- DDL Statements for Table "GALADM  "."WSDEFBUILDS_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."WSDEFBUILDS_TBX";


CREATE TABLE "GALADM  "."WSDEFBUILDS_TBX"  (
		  "ENVIRONMENT" VARCHAR(64 OCTETS) NOT NULL , 
		  "DEF_BUILD_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "ENV_DESCRIPTION" VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."WSDEFBUILDS_TBX" IS 'RMT WebStartDefaultBuild for Web start to define default builds per environment';


-- DDL Statements for Indexes on Table "GALADM  "."WSDEFBUILDS_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "GALADM  "."WSDEFBUILDSI1" ON "GALADM  "."WSDEFBUILDS_TBX" 
		("ENVIRONMENT" ASC)
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "GALADM  "."WSDEFBUILDS_TBX"

ALTER TABLE "GALADM  "."WSDEFBUILDS_TBX" 
	ADD CONSTRAINT "WSDEFBUILDSPK" PRIMARY KEY
		("ENVIRONMENT");









-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSDEFBUILDS_TR1";

CREATE TRIGGER GALADM.WSDEFBUILDS_TR1 NO CASCADE BEFORE INSERT ON GALADM.WSDEFBUILDS_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."WSDEFBUILDS_TR2";

CREATE TRIGGER GALADM.WSDEFBUILDS_TR2 NO CASCADE BEFORE UPDATE ON GALADM.WSDEFBUILDS_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


