insert into ORDER_MGR_TBX (ORDER_MGR_ID, LINE_NAME, MAX_DELIVERY_CAPACITY, DELIVERY_STOP, CONSUMPTION_STOP, VERSION) values (1, 'WELD LINE 1', 16, 70,  91,  0);
insert into ORDER_MGR_TBX (ORDER_MGR_ID, LINE_NAME, MAX_DELIVERY_CAPACITY, DELIVERY_STOP, CONSUMPTION_STOP, VERSION) values (2, 'WELD LINE 2', 30, 110, 119, 0);
insert into ORDER_MGR_TBX (ORDER_MGR_ID, LINE_NAME, MAX_DELIVERY_CAPACITY, DELIVERY_STOP, CONSUMPTION_STOP, VERSION) values (3, 'KD LINE',     20, 147, 101, 0);
