//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.16 at 02:44:26 PM EDT 
//


package com.honda.galc.client.teamleader.qi.mtcmodelimportexport.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="entrySiteName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="entryPlantName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="entryModel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="qiEntryModelImportExportTableSummaryXmlDto" type="{}QiEntryModelImportExportTableSummaryXmlDto" maxOccurs="unbounded"/&gt;
 *         &lt;element name="qiEnryScreens" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qiLocalDefectCombinationTbxXmlDto" type="{}QiLocalDefectCombinationTbxXmlDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qiEntryScreenDefectCombinationTbxXmlDto" type="{}QiEntryScreenDefectCombinationTbxXmlDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qiTextEntryMenuTbxXmlDto" type="{}QiTextEntryMenuTbxXmlDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qiEntryModelTbxXmlDto" type="{}QiEntryModelTbxXmlDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="qiEntryScreenTbxXmlDto" type="{}QiEntryScreenTbxXmlDto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entrySiteName",
    "entryPlantName",
    "entryModel",
    "qiEntryModelImportExportTableSummaryXmlDto",
    "qiEnryScreens",
    "qiLocalDefectCombinationTbxXmlDto",
    "qiEntryScreenDefectCombinationTbxXmlDto",
    "qiTextEntryMenuTbxXmlDto",
    "qiEntryModelTbxXmlDto",
    "qiEntryScreenTbxXmlDto"
})
@XmlRootElement(name = "QicsMtcModelConfigurationXmlDto")
public class QicsMtcModelConfigurationXmlDto {

    @XmlElement(required = true)
    protected String entrySiteName;
    @XmlElement(required = true)
    protected String entryPlantName;
    @XmlElement(required = true)
    protected String entryModel;
    @XmlElement(required = true)
    protected List<QiEntryModelImportExportTableSummaryXmlDto> qiEntryModelImportExportTableSummaryXmlDto;
    protected List<String> qiEnryScreens;
    protected List<QiLocalDefectCombinationTbxXmlDto> qiLocalDefectCombinationTbxXmlDto;
    protected List<QiEntryScreenDefectCombinationTbxXmlDto> qiEntryScreenDefectCombinationTbxXmlDto;
    protected List<QiTextEntryMenuTbxXmlDto> qiTextEntryMenuTbxXmlDto;
    protected List<QiEntryModelTbxXmlDto> qiEntryModelTbxXmlDto;
    protected List<QiEntryScreenTbxXmlDto> qiEntryScreenTbxXmlDto;

    /**
     * Gets the value of the entrySiteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrySiteName() {
        return entrySiteName;
    }

    /**
     * Sets the value of the entrySiteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrySiteName(String value) {
        this.entrySiteName = value;
    }

    /**
     * Gets the value of the entryPlantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryPlantName() {
        return entryPlantName;
    }

    /**
     * Sets the value of the entryPlantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryPlantName(String value) {
        this.entryPlantName = value;
    }

    /**
     * Gets the value of the entryModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryModel() {
        return entryModel;
    }

    /**
     * Sets the value of the entryModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryModel(String value) {
        this.entryModel = value;
    }

    /**
     * Gets the value of the qiEntryModelImportExportTableSummaryXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiEntryModelImportExportTableSummaryXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiEntryModelImportExportTableSummaryXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiEntryModelImportExportTableSummaryXmlDto }
     * 
     * 
     */
    public List<QiEntryModelImportExportTableSummaryXmlDto> getQiEntryModelImportExportTableSummaryXmlDto() {
        if (qiEntryModelImportExportTableSummaryXmlDto == null) {
            qiEntryModelImportExportTableSummaryXmlDto = new ArrayList<QiEntryModelImportExportTableSummaryXmlDto>();
        }
        return this.qiEntryModelImportExportTableSummaryXmlDto;
    }

    /**
     * Gets the value of the qiEnryScreens property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiEnryScreens property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiEnryScreens().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getQiEnryScreens() {
        if (qiEnryScreens == null) {
            qiEnryScreens = new ArrayList<String>();
        }
        return this.qiEnryScreens;
    }

    /**
     * Gets the value of the qiLocalDefectCombinationTbxXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiLocalDefectCombinationTbxXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiLocalDefectCombinationTbxXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiLocalDefectCombinationTbxXmlDto }
     * 
     * 
     */
    public List<QiLocalDefectCombinationTbxXmlDto> getQiLocalDefectCombinationTbxXmlDto() {
        if (qiLocalDefectCombinationTbxXmlDto == null) {
            qiLocalDefectCombinationTbxXmlDto = new ArrayList<QiLocalDefectCombinationTbxXmlDto>();
        }
        return this.qiLocalDefectCombinationTbxXmlDto;
    }

    /**
     * Gets the value of the qiEntryScreenDefectCombinationTbxXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiEntryScreenDefectCombinationTbxXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiEntryScreenDefectCombinationTbxXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiEntryScreenDefectCombinationTbxXmlDto }
     * 
     * 
     */
    public List<QiEntryScreenDefectCombinationTbxXmlDto> getQiEntryScreenDefectCombinationTbxXmlDto() {
        if (qiEntryScreenDefectCombinationTbxXmlDto == null) {
            qiEntryScreenDefectCombinationTbxXmlDto = new ArrayList<QiEntryScreenDefectCombinationTbxXmlDto>();
        }
        return this.qiEntryScreenDefectCombinationTbxXmlDto;
    }

    /**
     * Gets the value of the qiTextEntryMenuTbxXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiTextEntryMenuTbxXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiTextEntryMenuTbxXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiTextEntryMenuTbxXmlDto }
     * 
     * 
     */
    public List<QiTextEntryMenuTbxXmlDto> getQiTextEntryMenuTbxXmlDto() {
        if (qiTextEntryMenuTbxXmlDto == null) {
            qiTextEntryMenuTbxXmlDto = new ArrayList<QiTextEntryMenuTbxXmlDto>();
        }
        return this.qiTextEntryMenuTbxXmlDto;
    }

    /**
     * Gets the value of the qiEntryModelTbxXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiEntryModelTbxXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiEntryModelTbxXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiEntryModelTbxXmlDto }
     * 
     * 
     */
    public List<QiEntryModelTbxXmlDto> getQiEntryModelTbxXmlDto() {
        if (qiEntryModelTbxXmlDto == null) {
            qiEntryModelTbxXmlDto = new ArrayList<QiEntryModelTbxXmlDto>();
        }
        return this.qiEntryModelTbxXmlDto;
    }

    /**
     * Gets the value of the qiEntryScreenTbxXmlDto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qiEntryScreenTbxXmlDto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQiEntryScreenTbxXmlDto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QiEntryScreenTbxXmlDto }
     * 
     * 
     */
    public List<QiEntryScreenTbxXmlDto> getQiEntryScreenTbxXmlDto() {
        if (qiEntryScreenTbxXmlDto == null) {
            qiEntryScreenTbxXmlDto = new ArrayList<QiEntryScreenTbxXmlDto>();
        }
        return this.qiEntryScreenTbxXmlDto;
    }

	/**
	 * @param qiEntryModelImportExportTableSummaryXmlDto the qiEntryModelImportExportTableSummaryXmlDto to set
	 */
	public void setQiEntryModelImportExportTableSummaryXmlDto(
			List<QiEntryModelImportExportTableSummaryXmlDto> qiEntryModelImportExportTableSummaryXmlDto) {
		this.qiEntryModelImportExportTableSummaryXmlDto = qiEntryModelImportExportTableSummaryXmlDto;
	}

	/**
	 * @param qiEnryScreens the qiEnryScreens to set
	 */
	public void setQiEnryScreens(List<String> qiEnryScreens) {
		this.qiEnryScreens = qiEnryScreens;
	}

	/**
	 * @param qiLocalDefectCombinationTbxXmlDto the qiLocalDefectCombinationTbxXmlDto to set
	 */
	public void setQiLocalDefectCombinationTbxXmlDto(
			List<QiLocalDefectCombinationTbxXmlDto> qiLocalDefectCombinationTbxXmlDto) {
		this.qiLocalDefectCombinationTbxXmlDto = qiLocalDefectCombinationTbxXmlDto;
	}

	/**
	 * @param qiEntryScreenDefectCombinationTbxXmlDto the qiEntryScreenDefectCombinationTbxXmlDto to set
	 */
	public void setQiEntryScreenDefectCombinationTbxXmlDto(
			List<QiEntryScreenDefectCombinationTbxXmlDto> qiEntryScreenDefectCombinationTbxXmlDto) {
		this.qiEntryScreenDefectCombinationTbxXmlDto = qiEntryScreenDefectCombinationTbxXmlDto;
	}

	/**
	 * @param qiTextEntryMenuTbxXmlDto the qiTextEntryMenuTbxXmlDto to set
	 */
	public void setQiTextEntryMenuTbxXmlDto(List<QiTextEntryMenuTbxXmlDto> qiTextEntryMenuTbxXmlDto) {
		this.qiTextEntryMenuTbxXmlDto = qiTextEntryMenuTbxXmlDto;
	}

	/**
	 * @param qiEntryModelTbxXmlDto the qiEntryModelTbxXmlDto to set
	 */
	public void setQiEntryModelTbxXmlDto(List<QiEntryModelTbxXmlDto> qiEntryModelTbxXmlDto) {
		this.qiEntryModelTbxXmlDto = qiEntryModelTbxXmlDto;
	}

	/**
	 * @param qiEntryScreenTbxXmlDto the qiEntryScreenTbxXmlDto to set
	 */
	public void setQiEntryScreenTbxXmlDto(List<QiEntryScreenTbxXmlDto> qiEntryScreenTbxXmlDto) {
		this.qiEntryScreenTbxXmlDto = qiEntryScreenTbxXmlDto;
	}

}
