//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.13 at 03:11:19 PM EDT 
//


package com.honda.galc.client.teamleader.qi.mtcmodelimportexport.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * QI_ENTRY_SCREEN_TBX
 * 
 * <p>Java class for QiEntryScreenTbxXmlDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QiEntryScreenTbxXmlDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="entryScreen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isUsed" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="entryScreenDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isImage" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="active" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="screenIsUsed" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QiEntryScreenTbxXmlDto", propOrder = {

})
public class QiEntryScreenTbxXmlDto {

    @XmlElement(required = true)
    protected String entryScreen;
    @XmlElement(required = true)
    protected String entryModel;
    protected short isUsed;
    @XmlElement(required = true)
    protected String entryScreenDescription;
    protected short isImage;
    @XmlElement(required = true)
    protected String productType;
    @XmlElement(required = true)
    protected String imageName;
    protected short active;
    protected short screenIsUsed;

    /**
     * Gets the value of the entryScreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryScreen() {
        return entryScreen;
    }

    /**
     * Sets the value of the entryScreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryScreen(String value) {
        this.entryScreen = value;
    }

    /**
     * Gets the value of the entryModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryModel() {
        return entryModel;
    }

    /**
     * Sets the value of the entryModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryModel(String value) {
        this.entryModel = value;
    }

    /**
     * Gets the value of the isUsed property.
     * 
     */
    public short getIsUsed() {
        return isUsed;
    }

    /**
     * Sets the value of the isUsed property.
     * 
     */
    public void setIsUsed(short value) {
        this.isUsed = value;
    }

    /**
     * Gets the value of the entryScreenDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryScreenDescription() {
        return entryScreenDescription;
    }

    /**
     * Sets the value of the entryScreenDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryScreenDescription(String value) {
        this.entryScreenDescription = value;
    }

    /**
     * Gets the value of the isImage property.
     * 
     */
    public short getIsImage() {
        return isImage;
    }

    /**
     * Sets the value of the isImage property.
     * 
     */
    public void setIsImage(short value) {
        this.isImage = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageName(String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the active property.
     * 
     */
    public short getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(short value) {
        this.active = value;
    }

    /**
     * Gets the value of the screenIsUsed property.
     * 
     */
    public short getScreenIsUsed() {
        return screenIsUsed;
    }

    /**
     * Sets the value of the screenIsUsed property.
     * 
     */
    public void setScreenIsUsed(short value) {
        this.screenIsUsed = value;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "QiEntryScreenTbxXmlDto [entryScreen=" + entryScreen + ", entryModel=" + entryModel + ", isUsed="
				+ isUsed + ", entryScreenDescription=" + entryScreenDescription + ", isImage=" + isImage
				+ ", productType=" + productType + ", imageName=" + imageName + ", active=" + active + ", screenIsUsed="
				+ screenIsUsed + "]";
	}

}
