
delete from GALADM.GAL489TBX where component_id in ('EI_PA','GALC_MAINTENANCE', 'SRS_RS_FR_AIRBAG');

insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','HEADLESS','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','HEARTBEAT_ENABLED','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.classname1','com.honda.galc.client.device.plc.omron.FinsSocketPlcDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.classname2','com.honda.galc.client.device.plc.omron.FinsSocketPlcDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.connectiontimeout1','4000','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.connectiontimeout2','4000','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.deviceId1','PA_A','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.deviceId2','PA_B','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.pinginterval1','10000','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.pinginterval2','10000','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.responsetimeout1','10000','Socket response timeout','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('EI_PA','device.plc.responsetimeout2','10000','Socket response timeout','vnc60037');

insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.availPrinters','etcher1','availPrinters',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.baudrate','921600','Device baudrate','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.classname','com.honda.galc.client.device.lotcontrol.LaserEtcherSerialDevice','Device class name',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.connected','TRUE','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.databits','8','Device data bits',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.destinationPrinter','etcher1','Destination Printer',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.deviceId','etcher1','Device Id',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.enabled','true','Device status',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.eocmessage','print complete','Device eoc message',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.parity','0','Device parity',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.portname','COM22','Device port name','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.stopbits','1','Device stop bits',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.timeout','30000','Device time out',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.laseretcher.type','Serial','Device type',null);
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.availPrinters1','ipuprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.availPrinters2','imaprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.availPrinters3','pmccc1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.availPrinters4','ipbmpl','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.classname1','com.honda.galc.device.printer.PrinterSocketDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.classname2','com.honda.galc.device.printer.PrinterSocketDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.classname3','com.honda.galc.device.printer.PrinterSocketDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.classname4','com.honda.galc.device.printer.PrinterSocketDevice','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.destinationPrinter1','ipuprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.destinationPrinter2','imaprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.destinationPrinter3','pmccc1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.destinationPrinter4','ipbmpl','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.deviceId1','ipuprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.deviceId2','imaprinter','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.deviceId3','pmccc1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.deviceId4','ipbmpl','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.enabled1','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.enabled2','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.enabled3','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.enabled4','true','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.maxPrintsPerCycle1','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.maxPrintsPerCycle2','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.maxPrintsPerCycle3','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.maxPrintsPerCycle4','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.prePrintQty1','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.prePrintQty2','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.prePrintQty3','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.prePrintQty4','1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.type1','Printer','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.type2','Printer','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.type3','Printer','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','device.printer.type4','Printer','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('GALC_MAINTENANCE','USE CACHE','false','','vnc60037');

insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','sound.classname','com.honda.global.galc.client.common.audio.SoundProperties','directory path for sounds','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','sound.ng','/resource/sounds/LotBad_Buzz02.wav','Sound file for OK judgement','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','sound.ok','/resource/sounds/LASER.WAV','Sound file for OK judgement','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','HEARTBEAT_ENABLED','true','Enable Heartbeat','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','USE CACHE','FALSE','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.classname','com.honda.galc.client.device.lotcontrol.TorqueSocketDevice','Class name of the value object','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.deviceId','torque1','','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.enabled','true','Enabled/Disabled indicator','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.hostname','10.204.17.164','Host name/IP Address of the torque device','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.model','Atlas','Manufacturer/Model number','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.pinginterval','10000','KeepAlive ping message interval','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.port','4545','Port number','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.protocol','OpenProtocol 1.0','Communication protocol name/version','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','device.torque.type','TCPSocket','Communication type','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.backupip','galchminline1log','Backup IP for logging','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.backupport','5555','Backup port for logging','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.classname','com.honda.global.galc.system.logging.ClientLogger','directory path for local logs','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.ipaddress','galchminline1log','IP Address of the remote logger','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.localpath','d:/logs','directory path for local logs','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.port','5555','port number for the remote logger','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','logger.tracelevel','11','Level of logging','vnc60037');
insert into GALADM.GAL489TBX(COMPONENT_ID,PROPERTY_KEY,PROPERTY_VALUE,DESCRIPTION,CHANGE_USER_ID) values ('SRS_RS_FR_AIRBAG','sound.changed','/resource/sounds/Blip.wav','Sound file for CHANGED judgement','vnc60037');

