ALTER TABLE GALADM.PART_SPEC_TBX ADD COLUMN PART_MARK VARCHAR(255);
ALTER TABLE GALADM.PART_SPEC_TBX ADD COLUMN PART_NUMBER CHAR(30);
ALTER TABLE GALADM.PART_SPEC_TBX ADD COLUMN DISPLAY_TYPE CHAR(50); 
ALTER TABLE GALADM.PART_SPEC_TBX ADD COLUMN IMAGE BLOB;
