ALTER TABLE GALADM.CASE_TBX ALTER COLUMN PRODUCT_ID SET DATA TYPE VARCHAR(255);
ALTER TABLE GALADM.CASE_TBX ALTER COLUMN DC_SERIAL_NUMBER SET DATA TYPE VARCHAR(255);
ALTER TABLE GALADM.CASE_TBX ALTER COLUMN MC_SERIAL_NUMBER SET DATA TYPE VARCHAR(255);
ALTER TABLE GALADM.CASE_TBX ALTER COLUMN ENGINE_SERIAL_NUMBER SET DATA TYPE VARCHAR(255);
ALTER TABLE GALADM.CASE_TBX ALTER COLUMN MODEL SET DATA TYPE VARCHAR(22);
ALTER TABLE GALADM.CASE_TBX ALTER COLUMN DUNNAGE SET DATA TYPE VARCHAR(20);