ALTER TABLE GALADM.QI_DEFECT_TBX ADD APP_CREATE_TIMESTAMP TIMESTAMP;
ALTER TABLE GALADM.QI_DEFECT_TBX ADD APP_UPDATE_TIMESTAMP TIMESTAMP; 
ALTER TABLE GALADM.QI_INSPECTION_LOCATION_TBX ADD APP_CREATE_TIMESTAMP TIMESTAMP;
ALTER TABLE GALADM.QI_INSPECTION_LOCATION_TBX ADD APP_UPDATE_TIMESTAMP TIMESTAMP; 
ALTER TABLE GALADM.QI_INSPECTION_PART_TBX ADD APP_CREATE_TIMESTAMP TIMESTAMP;
ALTER TABLE GALADM.QI_INSPECTION_PART_TBX ADD APP_UPDATE_TIMESTAMP TIMESTAMP; 
