DROP TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR1;
DROP TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR2;
DROP TABLE "GALADM"."MBPN_PRODUCT_TYPE_TBX";

CREATE TABLE "GALADM"."MBPN_PRODUCT_TYPE_TBX"
(
   MAIN_NO char(5)  NOT NULL,
   OWNER_MAIN_NO char(5) NOT NULL,
   PRODUCT_TYPE char(10),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT MBPN_PRODUCT_TYPE_PK PRIMARY KEY
    (MAIN_NO,OWNER_MAIN_NO)
)
 IN GALTBSREF11 INDEX IN GALTBSIDX4;
 
COMMENT ON TABLE "GALADM"."MBPN_PRODUCT_TYPE_TBX"  IS 'MBPN Product Type';

CREATE TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MBPN_PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MBPN_PRODUCT_TYPE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MBPN_PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR1;
DROP TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR2;
DROP TABLE "GALADM"."PRODUCT_TYPE_TO_NUMBER_DEF_TBX";

CREATE TABLE "GALADM"."PRODUCT_TYPE_TO_NUMBER_DEF_TBX"
(
   MAIN_NO char(5)  NOT NULL,
   PRODUCT_ID_DEF char(24) NOT NULL,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT PRODUCT_TYPE_TO_NUMBER_DEF_PK PRIMARY KEY
    (MAIN_NO,PRODUCT_ID_DEF)

)
  IN GALTBSREF11 INDEX IN GALTBSIDX4;
  
COMMENT ON TABLE "GALADM"."PRODUCT_TYPE_TO_NUMBER_DEF_TBX"  IS 'MBPN Type to Number Def';


CREATE TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_TYPE_TO_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.PRODUCT_NUMBER_DEF_TR1;
DROP TRIGGER GALADM.PRODUCT_NUMBER_DEF_TR2;
DROP TABLE "GALADM"."PRODUCT_NUMBER_DEF_TBX";

CREATE TABLE "GALADM"."PRODUCT_NUMBER_DEF_TBX"
(
   PRODUCT_ID_DEF char(24) PRIMARY KEY NOT NULL,
   LENGTH SMALLINT DEFAULT 0,
   MASK char(64),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp
)
  IN GALTBSREF11 INDEX IN GALTBSIDX4;

COMMENT ON TABLE "GALADM"."PRODUCT_NUMBER_DEF_TBX"  IS 'MBPN Product Number Def';


CREATE TRIGGER GALADM.PRODUCT_NUMBER_DEF_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_NUMBER_DEF_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_NUMBER_DEF_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;



DROP TRIGGER GALADM.MBPN_MADE_FROM_TR1;
DROP TRIGGER GALADM.MBPN_MADE_FROM_TR2;
DROP TABLE "GALADM"."MBPN_MADE_FROM_TBX";

CREATE TABLE "GALADM"."MBPN_MADE_FROM_TBX"
(
   PRODUCT_ID char(17)  NOT NULL,
   MAIN_NO char(5)  NOT NULL,
   FROM_PRODUCT_ID char(17),
   FROM_MAIN_NO char(5),
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
    CONSTRAINT MBPN_MADE_FROM_PK PRIMARY KEY
    (PRODUCT_ID,MAIN_NO)

)
 IN GALTBSREF11 INDEX IN GALTBSIDX4;

COMMENT ON TABLE "GALADM"."MBPN_MADE_FROM_TBX"  IS 'MBPN Made From';

CREATE TRIGGER GALADM.MBPN_MADE_FROM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MBPN_MADE_FROM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MBPN_MADE_FROM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MBPN_MADE_FROM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;




