------------------------------------------------
-- DDL Statements for Table "GALADM  "."HOLD_REASON_TBX"
------------------------------------------------

DROP TRIGGER GALADM.HOLD_REASON_TR2;
DROP TRIGGER GALADM.HOLD_REASON_TR1;
DROP TABLE GALADM.HOLD_REASON_TBX;

CREATE TABLE "GALADM"."HOLD_REASON_TBX" (
   "REASON_ID" INTEGER NOT NULL,
   "DIVISION_ID" CHARACTER(16) NOT NULL,
   "HOLD_REASON" VARCHAR(80) NOT NULL,
   "CREATE_TIMESTAMP" TIMESTAMP , 
   "UPDATE_TIMESTAMP" TIMESTAMP,
   CONSTRAINT HOLD_REASON_PK PRIMARY KEY
     (REASON_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HOLD_REASON_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HOLD_REASON_TBX IS 'RMT HoldReason';

CREATE TRIGGER GALADM.HOLD_REASON_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOLD_REASON_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."HOLD_REASON_MAPPING_TBX"
------------------------------------------------
DROP TRIGGER GALADM.HOLD_REASON_MAPPING_TR2;
DROP TRIGGER GALADM.HOLD_REASON_MAPPING_TR1;
DROP TABLE GALADM.HOLD_REASON_MAPPING_TBX;

CREATE TABLE "GALADM"."HOLD_REASON_MAPPING_TBX" (
   "REASON_MAPPING_ID" INTEGER NOT NULL,
   "REASON_ID" INTEGER NOT NULL,
   "QC_ACTION_ID" INTEGER NOT NULL,
   "DIVISION_ID" CHARACTER(16) NOT NULL,
   "LINE_ID" CHARACTER(16) NOT NULL,
   "ASSOCIATE_ID" VARCHAR(11) NOT NULL,
   "ASSOCIATE_NAME" VARCHAR(30) NOT NULL,
   "CREATE_TIMESTAMP" TIMESTAMP , 
   "UPDATE_TIMESTAMP" TIMESTAMP, 
   CONSTRAINT HOLD_REASON_MAPPING_PK PRIMARY KEY
     (REASON_MAPPING_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HOLD_REASON_MAPPING_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HOLD_REASON_MAPPING_TBX IS 'RMT HoldReasonMap';

CREATE TRIGGER GALADM.HOLD_REASON_MAPPING_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_REASON_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOLD_REASON_MAPPING_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_REASON_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


