------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_PREVIOUS_DEFECT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_PREVIOUS_DEFECT_TR1;
DROP TRIGGER GALADM.QI_STATION_PREVIOUS_DEFECT_TR2;
DROP TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX;

CREATE TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX
(
	PROCESS_POINT_ID      CHAR(16) NOT NULL ,
	ENTRY_DIVISION_ID	  CHAR(16) NOT NULL ,
	CURRENT_DEFECT_STATUS	SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX IS 'NAQ Previous Defects shown on Station';

CREATE UNIQUE INDEX GALADM.QI_STATION_PREVIOUS_DEFECT_I1
  ON GALADM.QI_STATION_PREVIOUS_DEFECT_TBX (PROCESS_POINT_ID, ENTRY_DIVISION_ID);

ALTER TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX 
	ADD CONSTRAINT QI_STATION_PREVIOUS_DEFECT_PK PRIMARY KEY (PROCESS_POINT_ID, ENTRY_DIVISION_ID);
	
ALTER TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX 
	ADD CONSTRAINT QI_STATION_PREVIOUS_DEFECT_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX  
	ADD CONSTRAINT QI_STATION_PREVIOUS_DEFECT_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_PREVIOUS_DEFECT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_PREVIOUS_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_PREVIOUS_DEFECT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_PREVIOUS_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
        
        
            