ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX ALTER COLUMN MAIN_PART_NO SET DATA TYPE CHAR(5);
ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX;

ALTER TABLE GALADM.QI_BOM_PART_TBX ADD COLUMN PRODUCT_KIND CHAR(18) NOT NULL DEFAULT 'AUTOMOBILE';

ALTER TABLE GALADM.QI_BOM_PART_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_BOM_PART_TBX ALTER COLUMN MODEL_CODE SET DATA TYPE CHAR(4);
ALTER TABLE GALADM.QI_BOM_PART_TBX ALTER COLUMN MAIN_PART_NO SET DATA TYPE CHAR(5);
REORG TABLE GALADM.QI_BOM_PART_TBX;

ALTER TABLE GALADM.QI_BOM_PART_TBX ALTER COLUMN DC_PART_NAME SET DATA TYPE VARCHAR(30);
ALTER TABLE GALADM.QI_BOM_PART_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_BOM_PART_TBX;


ALTER TABLE GALADM.QI_BOM_PART_TBX DROP PRIMARY KEY;
DROP INDEX GALADM.QI_BOM_PART_I1;
CREATE UNIQUE INDEX GALADM.QI_BOM_PART_I1 ON GALADM.QI_BOM_PART_TBX (PRODUCT_KIND, DC_PART_NO, MODEL_CODE);
ALTER TABLE GALADM.QI_BOM_PART_TBX ADD CONSTRAINT QI_BOM_PART_PK PRIMARY KEY (PRODUCT_KIND, DC_PART_NO, MODEL_CODE);

ALTER TABLE GALADM.QI_BOM_PART_TBX ADD CONSTRAINT QI_BOM_PART_C1 CHECK (PRODUCT_KIND = UPPER(PRODUCT_KIND));			