ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX ADD COLUMN PRODUCTION_DATE DATE;
ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX ADD COLUMN SHIFT CHARACTER(2);
ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX ADD COLUMN TEAM VARCHAR(25);