-- Delete Procedure
DROP PROCEDURE GALADM.MC_STRUCTURE_MIGRATION;

-- ***END***

-- Drop PROCESS_POINT_ID, PROCESS_SEQ_NUM columns from MC_PDDA_PLATFORM_TBX
ALTER TABLE GALADM.MC_PDDA_PLATFORM_TBX DROP COLUMN PROCESS_POINT_ID DROP COLUMN PROCESS_SEQ_NUM;

--DROP Column REORG required
REORG TABLE GALADM.MC_PDDA_PLATFORM_TBX;