------------------------------------------------
-- DDL Statements to drop tables and triggers
------------------------------------------------

DROP TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR2; 
DROP TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR1; 
DROP TABLE GALADM.BUILD_SHEET_PART_MATRIX_TBX;

DROP TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR2; 
DROP TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR1; 
DROP TABLE GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX;