ALTER TABLE GALADM.GAL214TBX ADD COLUMN CURRENT_KD_LOT CHARACTER(18);

DROP INDEX GALADM.GAL143_I5;

CREATE INDEX GALADM.GAL143_I9
  ON GALADM.GAL143TBX
    (KD_LOT_NUMBER ASC, PRODUCT_ID ASC)
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE INDEX GALADM.GAL212_I2
  ON GALADM.GAL212TBX
    (KD_LOT_NUMBER ASC, PRODUCTION_LOT ASC)
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
DROP TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR2; 
DROP TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR1; 
DROP TABLE GALADM.BUILD_SHEET_PART_MATRIX_TBX;

CREATE TABLE GALADM.BUILD_SHEET_PART_MATRIX_TBX (
    FORM_ID CHARACTER(32) NOT NULL,
    MODEL_CODE CHARACTER(3) NOT NULL,
    MODEL_YEAR_CODE CHARACTER(1) NOT NULL,
    PART_NAME CHARACTER(32) NOT NULL,
    PART_LABEL CHARACTER(30),
    ROW INTEGER,
    COL INTEGER,
    CREATE_TIMESTAMP TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (FORM_ID, MODEL_CODE, MODEL_YEAR_CODE, PART_NAME)
) IN GALTBSREF11 INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.BUILD_SHEET_PART_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.BUILD_SHEET_PART_MATRIX_TBX IS 'Build Sheet Part Matrix';

CREATE TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_SHEET_PART_MATRIX_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.BUILD_SHEET_PART_MATRIX_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_SHEET_PART_MATRIX_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;