DROP TRIGGER GALADM.MC_ORDER_STRUCTURE_TR2; 
DROP TRIGGER GALADM.MC_ORDER_STRUCTURE_TR1; 
DROP TABLE GALADM.MC_ORDER_STRUCTURE_TBX; 

CREATE TABLE GALADM.MC_ORDER_STRUCTURE_TBX ( 
   ORDER_NO           CHARACTER(20) NOT NULL, 
   PRODUCT_SPEC_CODE        CHARACTER(30)        NOT NULL, 
   STRUCTURE_REV      BIGINT NOT NULL, 
   CREATE_TIMESTAMP          TIMESTAMP, 
   UPDATE_TIMESTAMP          TIMESTAMP, 
   CONSTRAINT MC_ORDER_STRUCTURE_PK PRIMARY KEY 
     (ORDER_NO) 
) 
  IN GALTBSREF12 
  INDEX IN GALTBSIDX4; 

ALTER TABLE GALADM.MC_ORDER_STRUCTURE_TBX 
  DATA CAPTURE CHANGES 
  PCTFREE 0 
  LOCKSIZE ROW 
  APPEND OFF 
  NOT VOLATILE; 

COMMENT ON TABLE GALADM.MC_ORDER_STRUCTURE_TBX IS 'RMT MC_ORDER_STRUCTURE is used by Manufacturing Control to define the structure revision that should be used to manufacture this order / lot'; 
    
CREATE TRIGGER GALADM.MC_ORDER_STRUCTURE_TR1 
  NO CASCADE BEFORE INSERT 
  ON GALADM.MC_ORDER_STRUCTURE_TBX 
  REFERENCING 
    NEW AS A 
  FOR EACH ROW 
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP; 

CREATE TRIGGER GALADM.MC_ORDER_STRUCTURE_TR2 
  NO CASCADE BEFORE UPDATE 
  ON GALADM.MC_ORDER_STRUCTURE_TBX 
  REFERENCING 
    NEW AS A 
  FOR EACH ROW 
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP; 