ALTER TABLE GALADM.GAL246TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.GAL246TBX ALTER COLUMN INSTRUCTION_CODE SET DATA TYPE CHAR(3);
ALTER TABLE GALADM.GAL246TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.GAL246TBX;