--Shipping Transaction 50A/B
-- Step 1. Delete the existing primary key (VIN,SENDED_FLG)
alter table GALADM.GAL148TBX data capture none;
alter table GALADM.GAL148TBX DROP CONSTRAINT GAL148_PK;

-- Step 2. Restoring the primary key.
alter table GALADM.GAL148TBX ADD CONSTRAINT GAL148_PK PRIMARY KEY(VIN);
alter table GALADM.GAL148TBX data capture changes;

REORG TABLE GALADM.GAL148TBX;

DROP TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR1;
DROP TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR2;
DROP TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR1;
DROP TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR2;
DROP TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR1;
DROP TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR2;
DROP TRIGGER GALADM.MC_MDRS_PERIOD_TR1;
DROP TRIGGER GALADM.MC_MDRS_PERIOD_TR2;
DROP TABLE GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX;
DROP TABLE GALADM.MC_MDRS_PERIOD_TBX;
DROP TABLE GALADM.MC_PROCESS_ASSIGNMENT_TBX;
DROP TABLE GALADM.MC_MDRS_TRAINING_STATUS_TBX;

CREATE TABLE GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX
(
   MANPOWER_ASSIGNMENT_ID   BIGINT NOT NULL,
   PLANT_LOC_CODE           CHARACTER (1) NOT NULL,
   DEPT_CODE                CHARACTER (2) NOT NULL,
   LAST_UPDATED_DATE        TIMESTAMP NOT NULL,
   EXTRACT_DATE             TIMESTAMP NOT NULL,
   ASSOCIATE_ID             CHARACTER (7),
   PROCESS_POINT_ID         CHARACTER (16),
   PDDA_PLATFORM_ID         INTEGER,
   ASSOCIATE_NO             CHARACTER (11),
   LINE_NO                  CHARACTER (2),
   PROCESS_LOCATION         CHARACTER (2),
   PLANT_CODE               CHARACTER (4),
   PRODUCTION_DATE          TIMESTAMP,
   SHIFT                    CHARACTER (2),
   PERIOD                   INTEGER,
   CREATE_TIMESTAMP         TIMESTAMP,
   UPDATE_TIMESTAMP         TIMESTAMP,
   CONSTRAINT MC_MDRS_MANPOWER_ASSIGNMENT_PK PRIMARY KEY
      (MANPOWER_ASSIGNMENT_ID,
       PLANT_LOC_CODE,
       DEPT_CODE,
       LAST_UPDATED_DATE,
       EXTRACT_DATE)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

CREATE TABLE GALADM.MC_MDRS_PERIOD_TBX
(
   LINE_NO            CHARACTER (2) NOT NULL,
   PROCESS_LOCATION   CHARACTER (2) NOT NULL,
   PLANT_CODE         CHARACTER (4) NOT NULL,
   SHIFT              CHARACTER (2) NOT NULL,
   PERIOD             INTEGER NOT NULL,
   PLANT_LOC_CODE     CHARACTER (1) NOT NULL,
   DEPT_CODE          CHARACTER (2) NOT NULL,
   SHIFT_ID           SMALLINT NOT NULL,
   QUARTER            SMALLINT NOT NULL,
   CREATE_TIMESTAMP   TIMESTAMP,
   UPDATE_TIMESTAMP   TIMESTAMP,
   CONSTRAINT MC_MDRS_PERIOD_PK PRIMARY KEY
      (LINE_NO,
       PROCESS_LOCATION,
       PLANT_CODE,
       SHIFT,
       PERIOD,
       PLANT_LOC_CODE,
       DEPT_CODE,
       SHIFT_ID,
       QUARTER)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

CREATE TABLE GALADM.MC_PROCESS_ASSIGNMENT_TBX
(
   PROCESS_POINT_ID   CHARACTER (16) NOT NULL,
   PDDA_PLATFORM_ID   INTEGER NOT NULL,
   LINE_NO            CHARACTER (2) NOT NULL,
   PROCESS_LOCATION   CHARACTER (2) NOT NULL,
   PLANT_CODE         CHARACTER (4) NOT NULL,
   PRODUCTION_DATE    TIMESTAMP NOT NULL,
   SHIFT              CHARACTER (2) NOT NULL,
   PERIOD             INTEGER NOT NULL,
   APPROVER_NO        CHARACTER (11),
   APPROVE_METHOD     VARCHAR (16),
   COMMENTS           VARCHAR (250),
   CREATE_TIMESTAMP   TIMESTAMP,
   UPDATE_TIMESTAMP   TIMESTAMP,
   CONSTRAINT MC_PROCESS_ASSIGNMENT_PK PRIMARY KEY
      (PROCESS_POINT_ID,
       PDDA_PLATFORM_ID,
       LINE_NO,
       PROCESS_LOCATION,
       PLANT_CODE,
       PRODUCTION_DATE,
       SHIFT,
       PERIOD)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

CREATE TABLE GALADM.MC_MDRS_TRAINING_STATUS_TBX
(
   TRAINING_STATUS_ID   BIGINT NOT NULL,
   PROCESS_POINT_ID     CHARACTER (16),
   ASSOCIATE_NO         CHARACTER (7),
   PDDA_PLATFORM_ID     INTEGER NOT NULL,
   SPEC_CODE_TYPE       VARCHAR (32),
   SPEC_CODE_MASK       VARCHAR (30),
   TRAINED              TIMESTAMP,
   CREATE_TIMESTAMP     TIMESTAMP,
   UPDATE_TIMESTAMP     TIMESTAMP,
   CONSTRAINT MC_MDRS_TRAINING_STATUS_PK PRIMARY KEY
      (TRAINING_STATUS_ID, PDDA_PLATFORM_ID)
)

  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
  ALTER TABLE GALADM.MC_MDRS_PERIOD_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
  ALTER TABLE GALADM.MC_PROCESS_ASSIGNMENT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
  ALTER TABLE GALADM.MC_MDRS_TRAINING_STATUS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX IS 'RMT MC_MDRS_MANPOWER_ASSIGNMENT_TBX is used by Manufacturing Control';
COMMENT ON TABLE GALADM.MC_MDRS_PERIOD_TBX IS 'RMT MC_MDRS_PERIOD_TBX is used by Manufacturing Control';
COMMENT ON TABLE GALADM.MC_PROCESS_ASSIGNMENT_TBX IS 'MC_PROCESS_ASSIGNMENT_TBX is used by Manufacturing Control';
COMMENT ON TABLE GALADM.MC_MDRS_TRAINING_STATUS_TBX IS 'MC_MDRS_TRAINING_STATUS_TBX is used by Manufacturing Control';

CREATE TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_MDRS_MANPOWER_ASSIGNMENT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_PERIOD_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_MDRS_PERIOD_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_PERIOD_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_MDRS_PERIOD_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PROCESS_ASSIGNMENT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PROCESS_ASSIGNMENT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PROCESS_ASSIGNMENT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_MDRS_TRAINING_STATUS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_STATUS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_MDRS_TRAINING_STATUS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;