ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX ADD CONSTRAINT QI_REPAIR_METHOD_C3 CHECK (REPAIR_METHOD = UPPER(REPAIR_METHOD));
ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX ADD CONSTRAINT QI_REPAIR_METHOD_C4 CHECK (REPAIR_METHOD_DESCRIPTION = UPPER(REPAIR_METHOD_DESCRIPTION));
REORG TABLE GALADM.QI_REPAIR_METHOD_TBX;
ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX DATA CAPTURE CHANGES;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_APPLIED_REPAIR_METHOD_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_APPLIED_REPAIR_METHOD_TR1;
DROP TRIGGER GALADM.QI_APPLIED_REPAIR_METHOD_TR2;
DROP TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX;

CREATE TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX
(
	REPAIR_ID             INTEGER NOT NULL ,
	REPAIR_METHOD_SEQ     SMALLINT NOT NULL ,
	REPAIR_METHOD	      VARCHAR(64),
	REPAIR_TIME           INTEGER,
	IS_COMPLETELY_FIXED   SMALLINT,
	COMMENT               VARCHAR(256),
	REPAIR_TIMESTAMP      TIMESTAMP,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX IS 'NAQ Applied Repair Method';

CREATE UNIQUE INDEX GALADM.QI_APPLIED_REPAIR_METHOD_I1
  ON GALADM.QI_APPLIED_REPAIR_METHOD_TBX (REPAIR_ID, REPAIR_METHOD_SEQ);

ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX 
	ADD CONSTRAINT QI_APPLIED_REPAIR_METHOD_PK PRIMARY KEY (REPAIR_ID, REPAIR_METHOD_SEQ);
	
ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX 
	ADD CONSTRAINT QI_APPLIED_REPAIR_METHOD_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX  
	ADD CONSTRAINT QI_APPLIED_REPAIR_METHOD_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX  
	ADD CONSTRAINT QI_APPLIED_REPAIR_METHOD_C3 CHECK 
		(REPAIR_METHOD = UPPER(REPAIR_METHOD));		

ALTER TABLE GALADM.QI_APPLIED_REPAIR_METHOD_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_APPLIED_REPAIR_METHOD_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_APPLIED_REPAIR_METHOD_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_APPLIED_REPAIR_METHOD_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_APPLIED_REPAIR_METHOD_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  


