ALTER TABLE GALADM.GAL198TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL198TBX
ADD COLUMN MEASUREMENT_NAME char(32)
ADD COLUMN MEASUREMENT_STRING_VALUE char(30)
;

ALTER TABLE GALADM.GAL198TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE GALADM.GAL198TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL198TBX;

ALTER TABLE GALADM.GAL198_HIST_TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL198_HIST_TBX
ADD COLUMN MEASUREMENT_NAME char(32)
ADD COLUMN MEASUREMENT_STRING_VALUE char(30)
;

ALTER TABLE GALADM.GAL198_HIST_TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE GALADM.GAL198_HIST_TBX;
REORG INDEXES  ALL FOR TABLE GALADM.GAL198_HIST_TBX;


