DROP TABLE "GALADM  "."HOLD_ACCESS_TYPE_TBX";

CREATE TABLE GALADM.HOLD_ACCESS_TYPE_TBX (
TYPE_ID VARCHAR(20) DEFAULT '' NOT NULL, 
SECURITY_GRP VARCHAR(255) DEFAULT '' NOT NULL, 
DESCRIPTION VARCHAR(255), 
CREATE_TIMESTAMP TIMESTAMP, 
UPDATE_TIMESTAMP TIMESTAMP
)

IN GALTBSREF12
  INDEX IN GALTBSIDX4;
  
COMMENT ON TABLE "GALADM  "."HOLD_ACCESS_TYPE_TBX" IS 'RMT Hold Access Type';


-- DDL Statements for Indexes on Table "GALADM  "."HOLD_ACCESS_TYPE_TBX"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';


-- DDL Statements for Primary Key on Table "GALADM  "."HOLD_ACCESS_TYPE_TBX"

ALTER TABLE GALADM.HOLD_ACCESS_TYPE_TBX
  ADD CONSTRAINT HOLD_ACCESS_TYPE_PK PRIMARY KEY
    (TYPE_ID, SECURITY_GRP);


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM"."HOLD_ACCESS_TYPE_TR1";

CREATE TRIGGER GALADM.HOLD_ACCESS_TYPE_TR1 NO CASCADE BEFORE INSERT ON GALADM.HOLD_ACCESS_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM"."HOLD_ACCESS_TYPE_TR2";

CREATE TRIGGER GALADM.HOLD_ACCESS_TYPE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.HOLD_ACCESS_TYPE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;