--Create Table GALADM.MC_VIOS_MASTER_OP_TBX

DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   OP_VIEW         	 	VARCHAR(255)	NOT NULL,
   OP_PROCESSOR     	VARCHAR(255)	NOT NULL,
   COMMON_NAME	     	VARCHAR(255),
   OP_CHECK             INTEGER,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_TBX IS 'RMT MC_VIOS_MASTER_OP_TBX is used by Manufacturing Control to create master configuration of Views and Processors';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO);
     
--Create Table GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_CHECKER_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_CHECKER_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX IS 'RMT MC_VIOS_MASTER_OP_CHECKER_TBX is used by Manufacturing Control to create master configuration of Operation Checkers';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_CHECKER_TBX_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO, CHECK_POINT, CHECK_SEQ);
     
 --Add COMMON_NAME Column in GALADM.MC_OP_REV_TBX
 
ALTER TABLE GALADM.MC_OP_REV_TBX ADD COMMON_NAME VARCHAR(255) DEFAULT '';

--Add GALADM.MC_VIOS_MASTER_OP_PART_TBX table

DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_NO              CHARACTER(18)	NOT NULL,
   PART_SECTION_CODE    CHARACTER(3)	NOT NULL,
   PART_ITEM_NO         CHARACTER(8)	NOT NULL,
   PART_TYPE            VARCHAR(32)		NOT NULL,
   PART_DESC            VARCHAR(255),
   PART_VIEW            VARCHAR(255),
   PART_PROCESSOR       VARCHAR(255),
   DEVICE_ID            CHARACTER(32),
   DEVICE_MSG           CHARACTER(32),
   PART_MASK          	VARCHAR(255),
   PART_MARK            VARCHAR(32),
   MEASUREMENT_COUNT  	INTEGER,
   PART_CHECK           INTEGER,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX IS 'RMT MC_VIOS_MASTER_OP_PART_TBX is used by Manufacturing Control to define the master data of parts that can be used at an operation';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_PART_I1 ON GALADM.MC_VIOS_MASTER_OP_PART_TBX
  (VIOS_PLATFORM_ID ASC, UNIT_NO ASC, PART_NO ASC, PART_SECTION_CODE ASC, PART_ITEM_NO ASC, PART_TYPE ASC)
  INCLUDE (CREATE_TIMESTAMP, UPDATE_TIMESTAMP)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_PART_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, PART_TYPE);
     
-- Add GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX table

DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_NO              CHARACTER(18)	NOT NULL,
   PART_SECTION_CODE    CHARACTER(3)	NOT NULL,
   PART_ITEM_NO         CHARACTER(8)	NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_VIOS_MASTER_OP_PART_CHECKER_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, CHECK_POINT, CHECK_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX IS 'RMT MC_VIOS_MASTER_OP_PART_CHECKER_TBX is used by Manufacturing Control to define master data of Checkers at the Part level';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

--Add GALADM.MC_VIOS_MASTER_OP_MEAS_TBX table

DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_NO              CHARACTER(18)	NOT NULL,
   PART_SECTION_CODE    CHARACTER(3)	NOT NULL,
   PART_ITEM_NO         CHARACTER(8)	NOT NULL,
   PART_TYPE            VARCHAR(32)		NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER			NOT NULL,
   DEVICE_ID			CHARACTER(32),
   DEVICE_MSG			CHARACTER(32),
   MIN_LIMIT			DOUBLE,
   MAX_LIMIT			DOUBLE,
   MEAS_CHECK			INTEGER,
   MEAS_MAX_ATTEMPTS	INTEGER,
   MEAS_VIEW			VARCHAR(255),
   MEAS_PROCESSOR		VARCHAR(255),
   MEAS_TIME			INTEGER,
   MEAS_TYPE			VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX IS 'RMT MC_VIOS_MASTER_OP_MEAS_TBX is used by Manufacturing Control to define the master data of measurements that can be used in a part';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_MEAS_I1 ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  (VIOS_PLATFORM_ID ASC, UNIT_NO ASC, PART_NO ASC, PART_SECTION_CODE ASC, PART_ITEM_NO ASC, PART_TYPE ASC, OP_MEAS_SEQ_NUM ASC)
  INCLUDE (CREATE_TIMESTAMP, UPDATE_TIMESTAMP)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_OP_MEAS_PK PRIMARY KEY 
     (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, PART_TYPE, OP_MEAS_SEQ_NUM);

--Add GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX table

DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   UNIT_NO 				VARCHAR(6) 		NOT NULL,
   PART_NO              CHARACTER(18)	NOT NULL,
   PART_SECTION_CODE    CHARACTER(3)	NOT NULL,
   PART_ITEM_NO         CHARACTER(8)	NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER			NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_VIOS_MASTER_OP_MEAS_CHECKER_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, OP_MEAS_SEQ_NUM, CHECK_POINT, CHECK_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX IS 'RMT MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX is used by Manufacturing Control to define master data of Checkers at the measurement level';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


