ALTER TABLE "GALADM"."NOTIFICATION_SUBSCRIBER_TBX" 
    ADD COLUMN PROVIDER VARCHAR(256) NOT NULL DEFAULT 'ANY';
ALTER TABLE "GALADM"."NOTIFICATION_SUBSCRIBER_TBX" 
    ADD COLUMN SUBSCRIPTION_TYPE CHARACTER(7) NOT NULL DEFAULT 'INCLUDE';

ALTER TABLE "GALADM"."NOTIFICATION_SUBSCRIBER_TBX" 
    DROP PRIMARY KEY;
ALTER TABLE "GALADM"."NOTIFICATION_SUBSCRIBER_TBX"
    ADD PRIMARY KEY
    ("NOTIFICATION_CLASS", "CLIENT_IP", "CLIENT_PORT", "PROVIDER"); 