ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN GROUP_TIMESTAMP TIMESTAMP;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN GROUP_TIMESTAMP TIMESTAMP;

ALTER TABLE GALADM.GAL260TBX ADD COLUMN TOTAL_REJECTION INTEGER;