ALTER TABLE GALADM.CONROD_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CONROD_TBX alter COLUMN CONROD_ID set data type varchar(17);
ALTER TABLE GALADM.CONROD_TBX alter COLUMN ENGINE_SERIAL_NUMBER set data type varchar(17);
ALTER TABLE GALADM.CONROD_TBX DATA CAPTURE CHANGES;
ALTER TABLE GALADM.CONROD_HISTORY_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CONROD_HISTORY_TBX alter COLUMN CONROD_ID set data type varchar(17);
ALTER TABLE GALADM.CONROD_HISTORY_TBX DATA CAPTURE CHANGES;
ALTER TABLE GALADM.CONROD_BUILD_RESULTS_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CONROD_BUILD_RESULTS_TBX alter COLUMN CONROD_ID set data type varchar(17);
ALTER TABLE GALADM.CONROD_BUILD_RESULTS_TBX DATA CAPTURE CHANGES;




ALTER TABLE GALADM.CRANKSHAFT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CRANKSHAFT_TBX alter COLUMN CRANKSHAFT_ID set data type varchar(17);
ALTER TABLE GALADM.CRANKSHAFT_TBX DATA CAPTURE CHANGES;
ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX alter COLUMN CRANKSHAFT_ID set data type varchar(17);
ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX DATA CAPTURE CHANGES;
ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_TBX alter COLUMN CRANKSHAFT_ID set data type varchar(17);
ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_TBX DATA CAPTURE CHANGES;
