ALTER TABLE GALADM.SUB_PRODUCT_TBX DATA CAPTURE NONE
ALTER TABLE GALADM.SUB_PRODUCT_TBX DROP COLUMN STATUS
ALTER TABLE GALADM.SUB_PRODUCT_TBX ADD COLUMN DEFECT_STATUS SMALLINT

ALTER TABLE GALADM.SUB_PRODUCT_TBX 
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

REORG TABLE GALADM.SUB_PRODUCT_TBX



