CREATE TABLE "GALADM"."SUB_PRODUCT_SHIPPING_TBX"
(
   KD_LOT_NUMBER char(18) NOT NULL,
   PRODUCTION_LOT char(20) NOT NULL,
   PRODUCT_TYPE char(10),
   PRODUCT_SPEC_CODE char(22),
   LINE_NUMBER char(2),
   PRODUCTION_DATE date,
   SEQ_NO int DEFAULT 0,
   STATUS smallint DEFAULT 0,
   SCH_QUANTITY smallint DEFAULT 0,
   ACT_QUANTITY smallint DEFAULT 0,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT SUB_PROD_SHIP_PK PRIMARY KEY (KD_LOT_NUMBER,PRODUCTION_LOT)
)
;
CREATE UNIQUE INDEX SUB_PROD_SHIP_IDX1 ON "GALADM"."SUB_PRODUCT_SHIPPING_TBX"
(
  KD_LOT_NUMBER,
  PRODUCTION_LOT
)
;

CREATE TRIGGER "GALADM"."SUB_PROD_SHIP_TR1" NO CASCADE BEFORE
INSERT ON "GALADM"."SUB_PRODUCT_SHIPPING_TBX" REFERENCING NEW AS A FOR EACH ROW MODE DB2SQL SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP
;

CREATE TRIGGER "GALADM"."SUB_PROD_SHIP_TR2" NO CASCADE BEFORE
UPDATE ON "GALADM"."SUB_PRODUCT_SHIPPING_TBX" REFERENCING NEW AS A FOR EACH ROW MODE DB2SQL SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP
;
