ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_REV_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MFG_CTRL_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_REV_FK2 FOREIGN KEY
    (PROCESS_POINT_ID)
  REFERENCES GALADM.GAL214TBX
    (PROCESS_POINT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_REV_FK3 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_REV_FK4 FOREIGN KEY
    (REV_ID)
  REFERENCES GALADM.MFG_CTRL_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_REV_FK5 FOREIGN KEY
    (DEPRECATED_REV_ID)
  REFERENCES GALADM.MFG_CTRL_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

--TODO after PDDA tables created    
--ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
--  ADD CONSTRAINT MFG_CTRL_OP_REV_FK6 FOREIGN KEY
--    (PDDA_UNIT_ID)
--  REFERENCES 
--    ()
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION
--    NOT ENFORCED
--    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_TBX
  ADD CONSTRAINT MFG_CTRL_OP_FK1 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MFG_CTRL_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_REV_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MFG_CTRL_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_REV_FK2 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_REV_FK3 FOREIGN KEY
    (REV_ID)
  REFERENCES GALADM.MFG_CTRL_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_REV_FK4 FOREIGN KEY
    (DEPRECATED_REV_ID)
  REFERENCES GALADM.MFG_CTRL_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
   
ALTER TABLE GALADM.MFG_CTRL_OP_PART_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_FK1 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MFG_CTRL_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_MEAS_TBX
  ADD CONSTRAINT MFG_CTRL_OP_MEAS_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MFG_CTRL_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_MEAS_TBX
  ADD CONSTRAINT MFG_CTRL_OP_MEAS_FK2 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MFG_CTRL_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_MEAS_TBX
  ADD CONSTRAINT MFG_CTRL_OP_MEAS_FK3 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_MATRIX_TBX
  ADD CONSTRAINT MFG_CTRL_OP_MATRIX_FK1 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MFG_CTRL_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_OP_PART_MATRIX_TBX
  ADD CONSTRAINT MFG_CTRL_OP_PART_MATRIX_FK1 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MFG_CTRL_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_FK1 FOREIGN KEY
    (ORDER_NO)
  REFERENCES GALADM.GAL217TBX
    (PRODUCTION_LOT)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

--NEED TO CHANGE PK OF ORDER_TBX TO JUST BE ORDER
--ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
--  ADD CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_FK2 FOREIGN KEY
--    (ORDER_NO)
--  REFERENCES GALADM.ORDER_TBX
--    (ORDER_NO)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION
--    NOT ENFORCED
--    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_FK3 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL144TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_FK4 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL133TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_FK5 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.MBPN_TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK1 FOREIGN KEY
    (PRODUCT_ID)
  REFERENCES GALADM.GAL143TBX
    (PRODUCT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK2 FOREIGN KEY
    (PRODUCT_ID)
  REFERENCES GALADM.MBPN_PRODUCT_TBX
    (PRODUCT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK3 FOREIGN KEY
    (PRODUCT_ID)
  REFERENCES GALADM.GAL131TBX
    (PRODUCT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK4 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL144TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK5 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL133TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_FK6 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.MBPN_TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK1 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL144TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK2 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.GAL133TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK3 FOREIGN KEY
    (PRODUCT_SPEC_CODE)
  REFERENCES GALADM.MBPN_TBX
    (PRODUCT_SPEC_CODE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK4 FOREIGN KEY
    (PROCESS_POINT_ID)
  REFERENCES GALADM.GAL214TBX
    (PROCESS_POINT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK5 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MFG_CTRL_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  ADD CONSTRAINT MFG_CTRL_STRUCTURE_FK6 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MFG_CTRL_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;    
    
ALTER TABLE GALADM.MFG_CTRL_PDDA_PROCESS_TBX
  ADD CONSTRAINT MFG_CTRL_PDDA_PROCESS_FK1 FOREIGN KEY
    (PROCESS_POINT_ID)
  REFERENCES GALADM.GAL214TBX
    (PROCESS_POINT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    