ALTER TABLE GALADM.GAL261TBX ADD COLUMN EXTERNAL_REQUIRED INTEGER;
ALTER TABLE GALADM.GAL261TBX ADD COLUMN LET_CHECK_REQUIRED INTEGER;

DROP TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR2;
DROP TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR1;
DROP TABLE GALADM.EXT_REQUIRED_PART_SPEC_TBX;

CREATE TABLE GALADM.EXT_REQUIRED_PART_SPEC_TBX (
  PART_NAME CHARACTER(32) NOT NULL,
  PART_ID CHARACTER(5) NOT NULL,
  PARSE_STRATEGY VARCHAR(32) NOT NULL,
  PARSE_INFORMATION VARCHAR(64) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP)
  IN GALTBSDAT10 INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.EXT_REQUIRED_PART_SPEC_TBX ADD CONSTRAINT EXT_REQUIRED_PART_SPEC_PK PRIMARY KEY (PART_NAME, PART_ID);

ALTER TABLE GALADM.EXT_REQUIRED_PART_SPEC_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.EXT_REQUIRED_PART_SPEC_TBX IS
   'RMT table for required parts';

CREATE TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.EXT_REQUIRED_PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.EXT_REQUIRED_PART_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.EXT_REQUIRED_PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.RULE_EXCLUSION_TR2;
DROP TRIGGER GALADM.RULE_EXCLUSION_TR1;
DROP TABLE GALADM.RULE_EXCLUSION_TBX;

CREATE TABLE GALADM.RULE_EXCLUSION_TBX (
  PART_NAME CHARACTER(32) NOT NULL,
  PRODUCT_SPEC_CODE CHARACTER(30) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP)
  IN GALTBSDAT10 INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.RULE_EXCLUSION_TBX ADD CONSTRAINT RULE_EXCLUSION_PK PRIMARY KEY (PART_NAME, PRODUCT_SPEC_CODE);

ALTER TABLE GALADM.RULE_EXCLUSION_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.RULE_EXCLUSION_TBX IS
   'RMT table for excluded rules from required check';

CREATE TRIGGER GALADM.RULE_EXCLUSION_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.RULE_EXCLUSION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.RULE_EXCLUSION_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.RULE_EXCLUSION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.LET_PART_CHECK_SPEC_TR2; DROP TRIGGER GALADM.LET_PART_CHECK_SPEC_TR1; DROP TABLE GALADM.LET_PART_CHECK_SPEC_TBX;

CREATE TABLE GALADM.LET_PART_CHECK_SPEC_TBX (
  PART_NAME CHARACTER(32) NOT NULL,
  PART_ID CHARACTER(5) NOT NULL,
  INSPECTION_PROGRAM_ID INTEGER NOT NULL,
  INSPECTION_PARAM_ID INTEGER NOT NULL,
  SEQUENCE_NUMBER INTEGER NOT NULL,
  PARAM_TYPE INTEGER NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP)
  IN GALTBSDAT10 INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.LET_PART_CHECK_SPEC_TBX ADD CONSTRAINT LET_PART_CHECK_SPEC_PK PRIMARY KEY (PART_NAME, PART_ID, INSPECTION_PROGRAM_ID, INSPECTION_PARAM_ID);

ALTER TABLE GALADM.LET_PART_CHECK_SPEC_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.LET_PART_CHECK_SPEC_TBX IS
   'RMT table for rules checked by LET';

CREATE TRIGGER GALADM.LET_PART_CHECK_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LET_PART_CHECK_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LET_PART_CHECK_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LET_PART_CHECK_SPEC_TBX
   REFERENCING NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
