update galadm.gal246tbx set STRATEGY='DEVICE_DATA_RESPONSE' where STRATEGY like 'AIRBAG_INSTALL%';

update galadm.gal489tbx set PROPERTY_VALUE = CHAR(REPLACE(PROPERTY_VALUE,'AIRBAG_INSTALL','DEVICE_DATA_RESPONSE')) where PROPERTY_KEY like 'STRATEGY_TYPES%';