ALTER TABLE GALADM.BLOCK_BUILD_RESULTS_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.BLOCK_BUILD_RESULTS_I2 ON GALADM.BLOCK_BUILD_RESULTS_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.BLOCK_BUILD_RESULTS_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.BLOCK_BUILD_RESULTS_HIST_I1 ON GALADM.BLOCK_BUILD_RESULTS_HIST_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.CONROD_BUILD_RESULTS_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.CONROD_BUILD_RESULTS_I1 ON GALADM.CONROD_BUILD_RESULTS_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.CONROD_BUILD_RESULTS_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.CONROD_BUILD_RESULTS_HIST_I1 ON GALADM.CONROD_BUILD_RESULTS_HIST_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.CRANKSHAFT_BUILD_RESULTS_I1 ON GALADM.CRANKSHAFT_BUILD_RESULTS_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_I1 ON GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.HEAD_BUILD_RESULTS_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.HEAD_BUILD_RESULTS_I2 ON GALADM.HEAD_BUILD_RESULTS_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.HEAD_BUILD_RESULTS_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT WITH DEFAULT 0;
CREATE INDEX GALADM.HEAD_BUILD_RESULTS_HIST_I1 ON GALADM.HEAD_BUILD_RESULTS_HIST_TBX ( DEFECT_REF_ID ) ALLOW REVERSE SCANS;

runstats on table GALADM.BLOCK_BUILD_RESULTS_TBX  with distribution and detailed indexes all;
runstats on table GALADM.BLOCK_BUILD_RESULTS_HIST_TBX with distribution and detailed indexes all;
runstats on table GALADM.CONROD_BUILD_RESULTS_TBX    with distribution and detailed indexes all;
runstats on table GALADM.CONROD_BUILD_RESULTS_HIST_TBX   with distribution and detailed indexes all;
runstats on table GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX with distribution and detailed indexes all;
runstats on table GALADM.CRANKSHAFT_BUILD_RESULTS_TBX  with distribution and detailed indexes all;
runstats on table GALADM.HEAD_BUILD_RESULTS_TBX    with distribution and detailed indexes all;
runstats on table GALADM.HEAD_BUILD_RESULTS_HIST_TBX   with distribution and detailed indexes all;
