UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = 'LAST_PID_TEXT_FIELD_HEIGHT' WHERE PROPERTY_KEY = 'LAST_PID_TEXT_FIELD_HIGHT';
UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = 'SKIPPED_PRODUCT_MONITOR_PANEL_HEIGHT' WHERE PROPERTY_KEY = 'SKIPPED_PRODUCT_MONITOR_PANEL_HIGHT';
UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = 'PRODUCT_ID_BUTTON_HEIGHT' WHERE PROPERTY_KEY = 'PRODUCT_ID_BUTTON_HIGHT';
