------------------------------------------------
-- DDL Statements for Table GALADM.AEP_STAT_OUT_TBX
------------------------------------------------
DROP TRIGGER GALADM.AEP_STAT_TR1;
DROP TRIGGER GALADM.AEP_STAT_TR2;
DROP TABLE GALADM.AEP_STAT_OUT_TBX;

-- Step 1. Sync
CREATE TABLE GALADM.AEP_STAT_OUT_TBX (
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL,
  EVENT_DATE	CHARACTER(6),
  EVENT_TIME	CHARACTER(6),
  ENGINE_ID	CHARACTER(12)	NOT NULL,
  PRODUCT_ID	CHARACTER(17)	NOT NULL,
  FRAME_MODEL	CHARACTER(4),
  FRAME_TYPE	CHARACTER(3),
  EXT_COLOR	CHARACTER(8),
  INT_COLOR	CHARACTER(1),
  FRAME_OPTION	CHARACTER(2),
  SENT_FLAG	CHARACTER(1),
  RECORD_TYPE	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  ) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.AEP_STAT_OUT_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.AEP_STAT_OUT_TBX IS 'AEP Outgoing Info OIF Table';

-- Step 2. Restoring constraints and indexes
ALTER TABLE GALADM.AEP_STAT_OUT_TBX
  ADD CONSTRAINT AEP_STAT_PK PRIMARY KEY
    (PRODUCT_ID, ENGINE_ID, PROCESS_POINT_ID);
    
CREATE OR REPLACE TRIGGER GALADM.AEP_STAT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.AEP_STAT_OUT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;
   
CREATE OR REPLACE TRIGGER GALADM.AEP_STAT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.AEP_STAT_OUT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table GALADM.GAL163TBX
------------------------------------------------
DROP TRIGGER GALADM.GAL163TR1;
DROP TRIGGER GALADM.GAL163TR2;
DROP TABLE GALADM.GAL163TBX;

-- Step 1. Sync
CREATE TABLE GALADM.GAL163TBX (
  DATE_STRING	CHARACTER(6),
  TIME	CHARACTER(6),
  SEND_LOCATION	CHARACTER(1),
  TRAN_TYPE	CHARACTER(2)	NOT NULL	DEFAULT ,
  VIN	CHARACTER(17)	NOT NULL	DEFAULT ,
  PARKING_LOCATION	CHARACTER(6)	NOT NULL	DEFAULT ,
  PARK_CONTROL_NO	CHARACTER(6),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  ) 
  IN GALTBSDAT9
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL163TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL163TBX IS 'IF Park Change';

-- Step 2. Restoring constraints and indexes
ALTER TABLE GALADM.GAL163TBX
  ADD CONSTRAINT GAL163PK PRIMARY KEY
    (VIN);
    

CREATE OR REPLACE TRIGGER GALADM.GAL163TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL163TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;


CREATE OR REPLACE TRIGGER GALADM.GAL163TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL163TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

