------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_TBX
(
	ENTRY_SCREEN          VARCHAR(20) NOT NULL ,
	ENTRY_SCREEN_DESCRIPTION  VARCHAR(30),
	IS_IMAGE              SMALLINT,
	PRODUCT_TYPE          CHAR(10),
	IMAGE_NAME            VARCHAR(20),
	ACTIVE                SMALLINT,
	ALL_DEPARTMENTS       SMALLINT,
	ALL_MODELS            SMALLINT, 
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_TBX IS 'NAQ Entry Screen';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_I1
  ON GALADM.QI_ENTRY_SCREEN_TBX (ENTRY_SCREEN);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_PK PRIMARY KEY (ENTRY_SCREEN);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
(
	ENTRY_SCREEN          VARCHAR(20) NOT NULL ,
	REGIONAL_DEFECT_COMBINATION_ID  INTEGER NOT NULL ,	
	TEXT_ENTRY_MENU       CHAR(18),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX IS 'NAQ Entry Screen Defect Combination';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_I1
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX (ENTRY_SCREEN, REGIONAL_DEFECT_COMBINATION_ID);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_PK PRIMARY KEY (ENTRY_SCREEN, REGIONAL_DEFECT_COMBINATION_ID);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C2 CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU));			
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX
(
	ENTRY_SCREEN          VARCHAR(20) NOT NULL ,
	DIVISION_ID           CHAR(16) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX IS 'NAQ Entry Screen by Department';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_DEPT_I1
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX (ENTRY_SCREEN, DIVISION_ID);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_PK PRIMARY KEY (ENTRY_SCREEN, DIVISION_ID);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
    

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_MODEL_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_MODEL_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_MODEL_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX
(
	ENTRY_SCREEN          VARCHAR(20) NOT NULL ,
	ENTRY_MODEL           CHAR(18) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX IS 'NAQ Entry Screen by Model';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_MODEL_I1
  ON GALADM.QI_ENTRY_SCREEN_MODEL_TBX (ENTRY_SCREEN, ENTRY_MODEL);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_MODEL_PK PRIMARY KEY (ENTRY_SCREEN, ENTRY_MODEL);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_MODEL_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_MODEL_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_MODEL_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_MODEL_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_MODEL_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_TEXT_ENTRY_MENU_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR1;
DROP TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR2;
DROP TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX;

CREATE TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX
(
	ENTRY_SCREEN          VARCHAR(20) NOT NULL ,
	TEXT_ENTRY_MENU       CHAR(18) NOT NULL ,
	TEXT_ENTRY_MENU_DESC  VARCHAR(64),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX IS 'NAQ Text Entry Menu by Entry Screen';

CREATE UNIQUE INDEX GALADM.QI_TEXT_ENTRY_MENU_I1
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX (ENTRY_SCREEN, TEXT_ENTRY_MENU);

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_PK PRIMARY KEY (ENTRY_SCREEN, TEXT_ENTRY_MENU);
	
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C2 CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU));			
		
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX  
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

        