------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_DEFECT_CATEGORY_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_DEFECT_CATEGORY_TR1";
DROP TRIGGER "GALADM  "."QI_DEFECT_CATEGORY_TR2";
DROP TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX";

CREATE TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX"  (
		  "DEFECT_CATEGORY_NAME" VARCHAR(32) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) ,
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_DEFECT_CATEGORY_TBX IS 'NAQ Defect Category';

CREATE UNIQUE INDEX GALADM.QI_DEFECT_CATEGORY_I1
  ON GALADM.QI_DEFECT_CATEGORY_TBX (DEFECT_CATEGORY_NAME);

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_PK" PRIMARY KEY
		("DEFECT_CATEGORY_NAME");
		
ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C1" CHECK 
		(DEFECT_CATEGORY_NAME = UPPER(DEFECT_CATEGORY_NAME));
		
ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_DEFECT_CATEGORY_TBX" 
	ADD CONSTRAINT "QI_DEFECT_CATEGORY_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_DEFECT_CATEGORY_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_DEFECT_CATEGORY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_DEFECT_CATEGORY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_DEFECT_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_DEFECT_TR1";
DROP TRIGGER "GALADM  "."QI_DEFECT_TR2";
DROP TABLE "GALADM  "."QI_DEFECT_TBX";

CREATE TABLE "GALADM  "."QI_DEFECT_TBX"  (
		  "DEFECT_TYPE_NAME" VARCHAR(45) NOT NULL WITH DEFAULT '' , 
		  "DEFECT_TYPE_DESCRIPTION_SHORT" VARCHAR(10) , 
		  "DEFECT_TYPE_DESCRIPTION_LONG" VARCHAR(30) , 
 		  "PRODUCT_KIND" CHAR(18) , 
		  "DEFECT_CATEGORY_NAME" VARCHAR(32) , 
		  "PRIMARY_POSITION" SMALLINT ,		  
		  "HIERARCHY" SMALLINT , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP ,		  
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_DEFECT_TBX IS 'NAQ Defect';

CREATE UNIQUE INDEX GALADM.QI_DEFECT_I1
  ON GALADM.QI_DEFECT_TBX (DEFECT_TYPE_NAME);
  
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_PK" PRIMARY KEY
		("DEFECT_TYPE_NAME");
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C1" CHECK 
		(DEFECT_TYPE_NAME = UPPER(DEFECT_TYPE_NAME));
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C2" CHECK 
		(DEFECT_TYPE_DESCRIPTION_SHORT = UPPER(DEFECT_TYPE_DESCRIPTION_SHORT));
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C3" CHECK 
		(DEFECT_TYPE_DESCRIPTION_LONG = UPPER(DEFECT_TYPE_DESCRIPTION_LONG));
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C4" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));					
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C5" CHECK 
		(DEFECT_CATEGORY_NAME = UPPER(DEFECT_CATEGORY_NAME));	
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C6" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));
		
ALTER TABLE "GALADM  "."QI_DEFECT_TBX" 
	ADD CONSTRAINT "QI_DEFECT_TBX_C7" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));					

ALTER TABLE GALADM.QI_DEFECT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_DEFECT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_DEFECT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEFECT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_INSPECTION_LOCATION_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_INSPECTION_LOCATION_TR1";
DROP TRIGGER "GALADM  "."QI_INSPECTION_LOCATION_TR2";
DROP TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX";

CREATE TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX"  (
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOC_DESC_SHORT" VARCHAR(10) , 
		  "INSPECTION_PART_LOC_DESC_LONG" VARCHAR(30) , 
		  "PRODUCT_KIND" CHAR(18) , 
		  "PRIMARY_POSITION" SMALLINT ,
		  "HIERARCHY" SMALLINT , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_INSPECTION_LOCATION_TBX IS 'NAQ Inspection Location';

CREATE UNIQUE INDEX GALADM.QI_INSPECTION_LOCATION_I1
  ON GALADM.QI_INSPECTION_LOCATION_TBX (INSPECTION_PART_LOCATION_NAME);

ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_PK" PRIMARY KEY
		("INSPECTION_PART_LOCATION_NAME");
		
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C1" CHECK 
		(INSPECTION_PART_LOCATION_NAME = UPPER(INSPECTION_PART_LOCATION_NAME));		
	
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C2" CHECK 
		(INSPECTION_PART_LOC_DESC_SHORT = UPPER(INSPECTION_PART_LOC_DESC_SHORT));		
		
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C3" CHECK 
		(INSPECTION_PART_LOC_DESC_LONG = UPPER(INSPECTION_PART_LOC_DESC_LONG));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C4" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C5" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_LOCATION_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_LOCATION_TBX_C6" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));				

ALTER TABLE GALADM.QI_INSPECTION_LOCATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_INSPECTION_LOCATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_INSPECTION_LOCATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_INSPECTION_LOCATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_INSPECTION_LOCATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_INSPECTION_PART_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_INSPECTION_PART_TR1";
DROP TRIGGER "GALADM  "."QI_INSPECTION_PART_TR2";
DROP TABLE "GALADM  "."QI_INSPECTION_PART_TBX";

CREATE TABLE "GALADM  "."QI_INSPECTION_PART_TBX"  (
		  "INSPECTION_PART_NAME" VARCHAR(32) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_DESC_SHORT" VARCHAR(10) , 
		  "INSPECTION_PART_DESC_LONG" VARCHAR(30) , 
		  "PRODUCT_KIND" CHAR(18) , 
		  "PART_CLASS" VARCHAR(32) ,
		  "PRIMARY_POSITION" SMALLINT ,
		  "HIERARCHY" SMALLINT , 
 		  "ALLOW_MULTIPLE" SMALLINT , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) ) 
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE GALADM.QI_INSPECTION_PART_TBX IS 'NAQ Inspection Part';

CREATE UNIQUE INDEX GALADM.QI_INSPECTION_PART_I1
  ON GALADM.QI_INSPECTION_PART_TBX (INSPECTION_PART_NAME); 

ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_PK" PRIMARY KEY
		("INSPECTION_PART_NAME");
		
ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C1" CHECK 
		(INSPECTION_PART_NAME = UPPER(INSPECTION_PART_NAME));			

ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C2" CHECK 
		(INSPECTION_PART_DESC_SHORT = UPPER(INSPECTION_PART_DESC_SHORT));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C3" CHECK 
		(INSPECTION_PART_DESC_LONG = UPPER(INSPECTION_PART_DESC_LONG));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C4" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));
			
ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C5" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));	
		
ALTER TABLE "GALADM  "."QI_INSPECTION_PART_TBX" 
	ADD CONSTRAINT "QI_INSPECTION_PART_TBX_C6" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));				

ALTER TABLE GALADM.QI_INSPECTION_PART_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_INSPECTION_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_INSPECTION_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_INSPECTION_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_INSPECTION_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_PART_LOCATION_COMBINATION_TR2";
DROP TRIGGER "GALADM  "."QI_PART_LOCATION_COMBINATION_TR1";
DROP TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX";

CREATE TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX"  (
		  "PART_LOCATION_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,
		  "INSPECTION_PART_NAME" VARCHAR(32) NOT NULL WITH DEFAULT '' , 
		  "INSPECTION_PART_LOCATION_NAME" VARCHAR(20) , 
		  "INSPECTION_PART_LOCATION2_NAME" VARCHAR(20) , 
		  "INSPECTION_PART2_NAME" VARCHAR(32) , 
		  "INSPECTION_PART2_LOCATION_NAME" VARCHAR(20) , 
		  "INSPECTION_PART2_LOCATION2_NAME" VARCHAR(20) , 
		  "INSPECTION_PART3_NAME" VARCHAR(32) ,
 		  "PRODUCT_KIND" CHAR(18) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) )
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE GALADM.QI_PART_LOCATION_COMBINATION_TBX IS 'NAQ Part Location Combination';

CREATE UNIQUE INDEX GALADM.QI_PART_LOCATION_COMBINATION_I1
  ON GALADM.QI_PART_LOCATION_COMBINATION_TBX (PART_LOCATION_ID);

ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_PK" PRIMARY KEY
		("PART_LOCATION_ID");

ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C1" CHECK 
		(INSPECTION_PART_NAME = UPPER(INSPECTION_PART_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C2" CHECK 
		(INSPECTION_PART_LOCATION_NAME = UPPER(INSPECTION_PART_LOCATION_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C3" CHECK 
		(INSPECTION_PART_LOCATION2_NAME = UPPER(INSPECTION_PART_LOCATION2_NAME));		
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C4" CHECK 
		(INSPECTION_PART2_NAME = UPPER(INSPECTION_PART2_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C5" CHECK 
		(INSPECTION_PART2_LOCATION_NAME = UPPER(INSPECTION_PART2_LOCATION_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C6" CHECK 
		(INSPECTION_PART2_LOCATION2_NAME = UPPER(INSPECTION_PART2_LOCATION2_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C7" CHECK 
		(INSPECTION_PART3_NAME = UPPER(INSPECTION_PART3_NAME));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C8" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C9" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));	
		
ALTER TABLE "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_PART_LOCATION_COMBINATION_TBX_C10" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));	

ALTER TABLE GALADM.QI_PART_LOCATION_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_PART_LOCATION_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_PART_LOCATION_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_PART_LOCATION_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_PART_LOCATION_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_PRODUCT_KIND_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_PRODUCT_KIND_TR1";
DROP TRIGGER "GALADM  "."QI_PRODUCT_KIND_TR2";
DROP TABLE "GALADM  "."QI_PRODUCT_KIND_TBX";

CREATE TABLE "GALADM  "."QI_PRODUCT_KIND_TBX"  (
		  "PRODUCT_KIND" CHAR(18) NOT NULL , 
		  "PRODUCT_KIND_DESCRIPTION" VARCHAR(64) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_PRODUCT_KIND_TBX IS 'NAQ PRODUCT KIND';

CREATE UNIQUE INDEX GALADM.QI_PRODUCT_KIND_I1
  ON GALADM.QI_PRODUCT_KIND_TBX (PRODUCT_KIND);

ALTER TABLE "GALADM  "."QI_PRODUCT_KIND_TBX" 
	ADD CONSTRAINT "QI_PRODUCT_KIND_PK" PRIMARY KEY
		("PRODUCT_KIND");
		
ALTER TABLE "GALADM  "."QI_PRODUCT_KIND_TBX" 
	ADD CONSTRAINT "QI_PRODUCT_KIND_C1" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));
		
ALTER TABLE "GALADM  "."QI_PRODUCT_KIND_TBX" 
	ADD CONSTRAINT "QI_PRODUCT_KIND_C2" CHECK 
		(PRODUCT_KIND_DESCRIPTION = UPPER(PRODUCT_KIND_DESCRIPTION));		
		
ALTER TABLE "GALADM  "."QI_PRODUCT_KIND_TBX" 
	ADD CONSTRAINT "QI_PRODUCT_KIND_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_PRODUCT_KIND_TBX" 
	ADD CONSTRAINT "QI_PRODUCT_KIND_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_PRODUCT_KIND_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_PRODUCT_KIND_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_PRODUCT_KIND_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_PRODUCT_KIND_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_PRODUCT_KIND_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  