DROP TRIGGER VIOS.PAMPS1_TR1;
DROP TRIGGER VIOS.PAMPS1_TR2;
DROP INDEX VIOS.PAMPS1_I2;
DROP TABLE VIOS.PAMPS1;

CREATE TABLE VIOS.PAMPS1 (
		MAPPER_SOURCE_ID 		INTEGER NOT NULL,
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		SOURCE_NAME 			VARCHAR(255) NOT NULL DEFAULT '',
		PLANT_LOC_CODE 			CHAR(1) NOT NULL DEFAULT ' ',
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
  		CONSTRAINT PAMPS1_PK 	PRIMARY KEY
   		(MAPPER_SOURCE_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAMPS1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAMPS1 IS 'RMT VIOS PID Mapping Source Table';	
	
CREATE UNIQUE INDEX VIOS.PAMPS1_I2
	ON VIOS.PAMPS1
	(SOURCE_NAME		ASC, PLANT_LOC_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAMPS1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPS1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAMPS1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPS1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAMPT1_TR1;
DROP TRIGGER VIOS.PAMPT1_TR2;
DROP INDEX VIOS.PAMPT1_I1;
DROP TABLE VIOS.PAMPT1;

CREATE TABLE VIOS.PAMPT1 (
		MAPPER_TYPE_ID 			INTEGER NOT NULL,
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		PLANT_LOC_CODE CHAR(1) 	NOT NULL DEFAULT ' ',
		TYPE_NAME VARCHAR(255) 	NOT NULL DEFAULT '',
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
  		CONSTRAINT PAMPT1_PK 	PRIMARY KEY
   		(MAPPER_TYPE_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PAMPT1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAMPT1 IS 'RMT VIOS PID Mapping Type Table';	
	
CREATE UNIQUE INDEX VIOS.PAMPT1_I1
	ON VIOS.PAMPT1
	(TYPE_NAME		ASC, PLANT_LOC_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAMPT1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAMPT1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAMPV1_TR1;
DROP TRIGGER VIOS.PAMPV1_TR2;
DROP INDEX VIOS.PAMPV1_I2;
DROP TABLE VIOS.PAMPV1;

CREATE TABLE VIOS.PAMPV1 (
		MAPPER_VALUE_ID 		INTEGER NOT NULL,
		MAPPER_SOURCE_ID 		INTEGER NOT NULL DEFAULT 0,
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		PLANT_LOC_CODE 			CHAR(1) NOT NULL DEFAULT ' ',
		"VALUE"					VARCHAR(255) NOT NULL DEFAULT '',
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
  		CONSTRAINT PAMPV1_PK 	PRIMARY KEY
   		(MAPPER_VALUE_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PAMPV1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAMPV1 IS 'RMT VIOS PID Mapping Value Table';	

CREATE UNIQUE INDEX VIOS.PAMPV1_I2
	ON VIOS.PAMPV1
	(MAPPER_SOURCE_ID		ASC, "VALUE"		ASC,  PLANT_LOC_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAMPV1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPV1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAMPV1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPV1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER VIOS.PAMPL1_TR1;
DROP TRIGGER VIOS.PAMPL1_TR2;
DROP INDEX VIOS.PAMPL1_I2;
DROP TABLE VIOS.PAMPL1;

CREATE TABLE VIOS.PAMPL1 (
		MAPPER_MATRIX_ID 		INTEGER NOT NULL,
		MAPPER_TYPE_ID 			INTEGER NOT NULL DEFAULT 0,
		SOURCE_VALUE_ID 		INTEGER NOT NULL DEFAULT 0,
		TARGET_VALUE_ID 		INTEGER NOT NULL DEFAULT 0,
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		PLANT_LOC_CODE 			CHAR(1) NOT NULL DEFAULT ' ',
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
  		CONSTRAINT PAMPL1_PK 	PRIMARY KEY
   		(MAPPER_MATRIX_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAMPL1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAMPL1 IS 'RMT VIOS PID Mapping Matrix Table';	
	

CREATE UNIQUE INDEX VIOS.PAMPL1_I2
	ON VIOS.PAMPL1
	( MAPPER_TYPE_ID		ASC,
	  SOURCE_VALUE_ID		ASC,
	  TARGET_VALUE_ID		ASC,
	  PLANT_LOC_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAMPL1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAMPL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAMPL1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAMPL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAPID1_TR1;
DROP TRIGGER VIOS.PAPID1_TR2;
DROP INDEX VIOS.PAPID1_I2;
DROP TABLE VIOS.PAPID1;

CREATE TABLE VIOS.PAPID1 (
		PART_IDENTIFICATION_ID 		INTEGER NOT NULL,
		PART_NO CHAR(18) 			NOT NULL DEFAULT '',
		STRUCTURE_LENGTH 			SMALLINT,
		PLANT_LOC_CODE 				CHAR(1) NOT NULL DEFAULT '',
		MAINT_LOGON_ID 				CHAR(8),
		MAINT_DATE 					TIMESTAMP,
		PART_CODE 					VARCHAR(255),
		PART_DESC 					VARCHAR(255),
		MODEL_YEAR_DATE 			DECIMAL(5,1) NOT NULL,
		VEHICLE_MODEL_CODE 			CHAR(1) NOT NULL DEFAULT '',
		CREATE_TIMESTAMP 			TIMESTAMP,
  		UPDATE_TIMESTAMP 			TIMESTAMP,
  		CONSTRAINT PAPID1_PK 		PRIMARY KEY
   		(PART_IDENTIFICATION_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAPID1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAPID1 IS 'RMT VIOS Part Identification Table';	

CREATE UNIQUE INDEX VIOS.PAPID1_I2
	ON VIOS.PAPID1
	( PART_NO		ASC,
	  MODEL_YEAR_DATE		ASC,
	  VEHICLE_MODEL_CODE		ASC,
	  PLANT_LOC_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAPID1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPID1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAPID1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPID1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAPIK1_TR1;
DROP TRIGGER VIOS.PAPIK1_TR2;
DROP INDEX VIOS.PAPIK1_I2;
DROP TABLE VIOS.PAPIK1;

CREATE TABLE VIOS.PAPIK1 (
		PID_PART_MASK_ID 		INTEGER NOT NULL,
		PART_IDENTIFICATION_ID 	INTEGER NOT NULL DEFAULT 0,
		MAPPER_TYPE_ID 			INTEGER NOT NULL DEFAULT 0,
		MASK_POSITION 			SMALLINT,
		MASK_LENGTH 			SMALLINT,
		PLANT_LOC_CODE 			CHAR(1),
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
		CONSTRAINT PAPIK1_PK 	PRIMARY KEY
   		(PID_PART_MASK_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAPIK1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAPIK1 IS 'RMT VIOS PID Mask Table';	

CREATE UNIQUE INDEX VIOS.PAPIK1_I2
	ON VIOS.PAPIK1
	(PART_IDENTIFICATION_ID		ASC,
	  MAPPER_TYPE_ID		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAPIK1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPIK1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAPIK1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPIK1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAPIA1_TR1;
DROP TRIGGER VIOS.PAPIA1_TR2;
DROP INDEX VIOS.PAPIA1_I2;
DROP TABLE VIOS.PAPIA1;

CREATE TABLE VIOS.PAPIA1 (
		PID_PART_MASK_APP_ID 		INTEGER NOT NULL,
		PID_PART_MASK_ID 			INTEGER NOT NULL DEFAULT 0,
		PLANT_LOC_CODE 				CHAR(1),
		MAINT_LOGON_ID 				CHAR(8),
		MAINT_DATE 					TIMESTAMP,
		MASK_CODE 					VARCHAR(255) NOT NULL DEFAULT '',
		CREATE_TIMESTAMP 			TIMESTAMP,
  		UPDATE_TIMESTAMP 			TIMESTAMP,
  		CONSTRAINT PAPIA1_PK 		PRIMARY KEY
   		(PID_PART_MASK_APP_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAPIA1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAPIA1 IS 'RMT VIOS PID Part Masking for Application Table';	

CREATE UNIQUE INDEX VIOS.PAPIA1_I2
	ON VIOS.PAPIA1
	(PID_PART_MASK_ID		ASC,
	  MASK_CODE		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAPIA1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPIA1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAPIA1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPIA1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAPIC1_TR1;
DROP TRIGGER VIOS.PAPIC1_TR2;
DROP INDEX VIOS.PAPIC_I1;
DROP TABLE VIOS.PAPIC1;

CREATE TABLE VIOS.PAPIC1 (
		MASK_MAPPER_REL_ID 		INTEGER NOT NULL,
		MAPPER_MATRIX_ID 		INTEGER,
		PID_PART_MASK_ID 		INTEGER,
		PLANT_LOC_CODE 			CHAR(1),
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
  		CONSTRAINT PAPIC1_PK 	PRIMARY KEY
   		(MASK_MAPPER_REL_ID))
	IN VIOSTBSDAT1
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAPIC1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAPIC1 IS 'RMT VIOS PID Color Mapping Table';	

CREATE INDEX VIOS.PAPIC_I1
	ON VIOS.PAPIC1
	(MASK_MAPPER_REL_ID		ASC,
	  MAPPER_MATRIX_ID		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAPIC1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPIC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAPIC1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPIC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PAPLL1_TR1;
DROP TRIGGER VIOS.PAPLL1_TR2;
DROP INDEX VIOS.PAPLL1_I2;
DROP TABLE VIOS.PAPLL1;

CREATE TABLE VIOS.PAPLL1 (
		PID_IMAGE_ID 			INTEGER NOT NULL,
		PART_IDENTIFICATION_ID 	INTEGER NOT NULL DEFAULT 0,
		IMAGE_TYPE 				SMALLINT,
		IMAGE 					BLOB(3145728),
		PLANT_LOC_CODE 			CHAR(1),
		MAINT_LOGON_ID 			CHAR(8),
		MAINT_DATE 				TIMESTAMP,
		IMAGE_NAME 				VARCHAR(255) NOT NULL DEFAULT '',
		CREATE_TIMESTAMP 		TIMESTAMP,
  		UPDATE_TIMESTAMP 		TIMESTAMP,
		CONSTRAINT PAPLL1_PK 	PRIMARY KEY
	   	(PID_IMAGE_ID))
	IN VIOSTBS16K
	INDEX IN VIOSTBSIDX1;
 
ALTER TABLE VIOS.PAPLL1
	DATA CAPTURE CHANGES
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE VIOS.PAPLL1 IS 'RMT VIOS PID Image Table';

CREATE UNIQUE INDEX VIOS.PAPLL1_I2
	ON VIOS.PAPLL1
	(PART_IDENTIFICATION_ID		ASC,
	  IMAGE_NAME		ASC) PCTFREE 10
ALLOW REVERSE SCANS;

CREATE TRIGGER VIOS.PAPLL1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PAPLL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PAPLL1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PAPLL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

