ALTER TABLE GALADM.GAL176TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.GAL176TBX ALTER COLUMN PRODUCT_SPEC_CODE SET DATA TYPE CHAR(30);
ALTER TABLE GALADM.GAL176TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.GAL176TBX;