DROP TRIGGER GALADM.EQUIP_UNIT_FAULT_TR1;
DROP TRIGGER GALADM.EQUIP_UNIT_FAULT_TR2;
DROP TABLE GALADM.EQUIP_UNIT_FAULT_TBX;

CREATE TABLE "GALADM"."EQUIP_UNIT_FAULT_TBX"
(
   UNIT_ID SMALLINT NOT NULL,
   UNIT_NAME VARCHAR(50),
   CURRENT_FAULT_CODE INT DEFAULT 0 NOT NULL,
   IS_MANUAL_IMPORT INT DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX EQUIP_UNIT_FAULT_I1 ON "GALADM"."EQUIP_UNIT_FAULT_TBX"(UNIT_ID);

ALTER TABLE GALADM.EQUIP_UNIT_FAULT_TBX
   ADD CONSTRAINT "EQUIP_UNIT_FAULT_PK" PRIMARY KEY
   (UNIT_ID); 

CREATE TRIGGER GALADM.EQUIP_UNIT_FAULT_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_UNIT_FAULT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.EQUIP_UNIT_FAULT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_UNIT_FAULT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.EQUIP_FAULT_CODE_TR1;
DROP TRIGGER GALADM.EQUIP_FAULT_CODE_TR2;
DROP TABLE GALADM.EQUIP_FAULT_CODE_TBX;

CREATE TABLE "GALADM"."EQUIP_FAULT_CODE_TBX"
(
   UNIT_ID SMALLINT NOT NULL,
   FAULT_CODE INT NOT NULL,
   FAULT_DESCRIPTION VARCHAR(60),
   IS_CONTROLLABLE SMALLINT DEFAULT 1,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

ALTER TABLE "GALADM"."EQUIP_FAULT_CODE_TBX"
ADD CONSTRAINT REF_EQUIP_UNIT_FAULT_FK1
FOREIGN KEY (UNIT_ID)
REFERENCES "GALADM"."EQUIP_UNIT_FAULT_TBX"(UNIT_ID)
NOT ENFORCED;

CREATE UNIQUE INDEX EQUIP_FAULT_CODE_TBX_I1 ON "GALADM"."EQUIP_FAULT_CODE_TBX" (UNIT_ID, FAULT_CODE);

ALTER TABLE GALADM.EQUIP_FAULT_CODE_TBX
   ADD CONSTRAINT "EQUIP_FAULT_CODE_PK" PRIMARY KEY
   (UNIT_ID,FAULT_CODE); 

CREATE TRIGGER GALADM.EQUIP_FAULT_CODE_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_FAULT_CODE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.EQUIP_FAULT_CODE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_FAULT_CODE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.EQUIP_GROUP_TR1;
DROP TRIGGER GALADM.EQUIP_GROUP_TR2;
DROP TABLE GALADM.EQUIP_GROUP_TBX;

CREATE TABLE "GALADM"."EQUIP_GROUP_TBX"
(
   GROUP_ID SMALLINT NOT NULL,
   GROUP_NAME VARCHAR(50) NOT NULL,
   GROUP_DESCRIPTION VARCHAR(100) NOT NULL,
   FAULT_COUNT SMALLINT DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX EQUIP_GROUP_I1 ON "GALADM"."EQUIP_GROUP_TBX"(GROUP_ID);

ALTER TABLE GALADM.EQUIP_GROUP_TBX
   ADD CONSTRAINT "EQUIP_GROUP_PK" PRIMARY KEY
   (GROUP_ID); 

CREATE TRIGGER GALADM.EQUIP_GROUP_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_GROUP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.EQUIP_GROUP_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_GROUP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.EQUIP_GROUP_UNIT_TR1;
DROP TRIGGER GALADM.EQUIP_GROUP_UNIT_TR2;
DROP TABLE GALADM.EQUIP_GROUP_UNIT_TBX;

CREATE TABLE "GALADM"."EQUIP_GROUP_UNIT_TBX"
(
   GROUP_ID SMALLINT NOT NULL,
   UNIT_ID SMALLINT NOT NULL,
   PRIORITY INT DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

ALTER TABLE "GALADM"."EQUIP_GROUP_UNIT_TBX"
ADD CONSTRAINT REF_EQUIP_GROUP_FK1
FOREIGN KEY (GROUP_ID)
REFERENCES "GALADM"."EQUIP_GROUP_TBX"(GROUP_ID)
NOT ENFORCED;

CREATE UNIQUE INDEX EQUIP_GROUP_UNIT_I1 ON "GALADM"."EQUIP_GROUP_UNIT_TBX" (GROUP_ID, UNIT_ID);

ALTER TABLE GALADM.EQUIP_GROUP_UNIT_TBX
   ADD CONSTRAINT "EQUIP_GROUP_UNIT_PK" PRIMARY KEY
   (GROUP_ID,UNIT_ID); 

CREATE TRIGGER GALADM.EQUIP_GROUP_UNIT_TR1 NO CASCADE BEFORE INSERT ON GALADM.EQUIP_GROUP_UNIT_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.EQUIP_GROUP_UNIT_TR2 NO CASCADE BEFORE UPDATE ON GALADM.EQUIP_GROUP_UNIT_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


