ALTER TABLE GALADM.MC_OP_REV_TBX
  ADD CONSTRAINT MC_OP_REV_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MC_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_REV_TBX
  ADD CONSTRAINT MC_OP_REV_FK2 FOREIGN KEY
    (REV_ID)
  REFERENCES GALADM.MC_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_REV_TBX
  ADD CONSTRAINT MC_OP_REV_FK3 FOREIGN KEY
    (DEPRECATED_REV_ID)
  REFERENCES GALADM.MC_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_TBX
  ADD CONSTRAINT MC_OP_FK1 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MC_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX
  ADD CONSTRAINT MC_OP_FK1 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MC_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX
  ADD CONSTRAINT MC_OP_REV_FK2 FOREIGN KEY
    (PDDA_PLATFORM_ID)
  REFERENCES GALADM.MC_PDDA_PLATFORM_TBX
    (PDDA_PLATFORM_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX
  ADD CONSTRAINT MC_OP_REV_FK3 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_PART_REV_TBX
  ADD CONSTRAINT MC_OP_PART_REV_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MC_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_PART_REV_TBX
  ADD CONSTRAINT MC_OP_PART_REV_FK2 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_PART_REV_TBX
  ADD CONSTRAINT MC_OP_PART_REV_FK3 FOREIGN KEY
    (REV_ID)
  REFERENCES GALADM.MC_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_PART_REV_TBX
  ADD CONSTRAINT MC_OP_PART_REV_FK4 FOREIGN KEY
    (DEPRECATED_REV_ID)
  REFERENCES GALADM.MC_REV_TBX
    (REV_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
   
ALTER TABLE GALADM.MC_OP_PART_TBX
  ADD CONSTRAINT MC_OP_PART_FK1 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MC_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_MEAS_TBX
  ADD CONSTRAINT MC_OP_MEAS_FK1 FOREIGN KEY
    (OPERATION_NAME)
  REFERENCES GALADM.MC_OP_TBX
    (OPERATION_NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_MEAS_TBX
  ADD CONSTRAINT MC_OP_MEAS_FK2 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MC_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_MEAS_TBX
  ADD CONSTRAINT MC_OP_MEAS_FK3 FOREIGN KEY
    (DEVICE_ID)
  REFERENCES GALADM.GAL253TBX
    (CLIENT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_MATRIX_TBX
  ADD CONSTRAINT MC_OP_MATRIX_FK1 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MC_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_OP_MATRIX_TBX
  ADD CONSTRAINT MC_OP_MATRIX_FK2 FOREIGN KEY
    (PDDA_PLATFORM_ID)
  REFERENCES GALADM.MC_PDDA_PLATFORM_TBX
    (PDDA_PLATFORM_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_OP_PART_MATRIX_TBX
  ADD CONSTRAINT MC_OP_PART_MATRIX_FK1 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MC_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_STRUCTURE_TBX
  ADD CONSTRAINT MC_STRUCTURE_FK1 FOREIGN KEY
    (PROCESS_POINT_ID)
  REFERENCES GALADM.GAL214TBX
    (PROCESS_POINT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_STRUCTURE_TBX
  ADD CONSTRAINT MC_STRUCTURE_FK2 FOREIGN KEY
    (OPERATION_NAME, OP_REV)
  REFERENCES GALADM.MC_OP_REV_TBX
    (OPERATION_NAME, OP_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;

ALTER TABLE GALADM.MC_STRUCTURE_TBX
  ADD CONSTRAINT MC_STRUCTURE_FK3 FOREIGN KEY
    (PDDA_PLATFORM_ID)
  REFERENCES GALADM.MC_PDDA_PLATFORM_TBX
    (PDDA_PLATFORM_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
ALTER TABLE GALADM.MC_STRUCTURE_TBX
  ADD CONSTRAINT MC_STRUCTURE_FK4 FOREIGN KEY
    (OPERATION_NAME, PART_ID, PART_REV)
  REFERENCES GALADM.MC_OP_PART_REV_TBX
    (OPERATION_NAME, PART_ID, PART_REV)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;    
    
ALTER TABLE GALADM.MC_PDDA_PLATFORM_TBX
  ADD CONSTRAINT MC_PDDA_PLATFORM_FK1 FOREIGN KEY
    (PROCESS_POINT_ID)
  REFERENCES GALADM.GAL214TBX
    (PROCESS_POINT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT ENFORCED
    ENABLE QUERY OPTIMIZATION;
    
