CREATE TABLE GALADM.INVOICE_TBX
        (INVOICE_NO DECIMAL(10,0) NOT NULL,
        INVOICE_TIMESTAMP TIMESTAMP NOT NULL,
        BATCH_TIMESTAMP TIMESTAMP NOT NULL,
        BATCH_SEQUENCE INTEGER NOT NULL,
        PROC_DATE DATE,
        NUM_SUMMARY_REC INTEGER NOT NULL,
        NUM_DTL_REC INTEGER NOT NULL,
        TRANCE_CODE CHARACTER(3),
        CREATE_TIMESTAMP TIMESTAMP,
        UPDATE_TIMESTAMP TIMESTAMP,
        PRIMARY KEY (INVOICE_NO)
        )
        IN GALTBSDAT7
        INDEX IN GALTBSIDX3;
        
COMMENT ON TABLE GALADM.INVOICE_TBX IS 'OIF Invoice';

CREATE OR REPLACE TRIGGER GALADM.INVOICE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE OR REPLACE TRIGGER GALADM.INVOICE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.INVOICE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.INVOICE_DETAIL_TBX
        (PRODUCT_ID CHARACTER(64) DEFAULT ' ' NOT NULL,
        INSPECTION_TIMESTAMP TIMESTAMP NOT NULL,
        SHIPPING_TIMESTAMP TIMESTAMP NOT NULL,
        PRICE DECIMAL(11,2) NOT NULL,
        QUOTATION_NO CHARACTER(20) DEFAULT ' ',
        PRICE_TYPE CHARACTER(1) DEFAULT ' ',
        INVOICE_NO DECIMAL(10,0) NOT NULL,
        AHM_INVOICE_NO CHARACTER(10) DEFAULT ' ',
        CORRECTION_FLAG CHARACTER(1) DEFAULT 'I',
        RECEIPT_TIMESTAMP CHARACTER(19) DEFAULT '0',
        VALIDATION_DATE CHARACTER(10) DEFAULT '0',
        FINAL_DATE CHARACTER(10) DEFAULT '0',
        FINAL_RECEIPT_FLG CHARACTER(1) DEFAULT 'F',
        FACTORY_SHIPMENT_NO CHARACTER(3) DEFAULT ' ',
        ERROR_CODE CHARACTER(4) DEFAULT ' ',
        DTL_ROW_NO INTEGER,
        CREATE_TIMESTAMP TIMESTAMP,
        UPDATE_TIMESTAMP TIMESTAMP,
        PRIMARY KEY (PRODUCT_ID, INVOICE_NO)
        )
        IN GALTBSDAT7
        INDEX IN GALTBSIDX3;
        
COMMENT ON TABLE GALADM.INVOICE_DETAIL_TBX IS 'OIF Invoice(Detail Record)';

CREATE OR REPLACE TRIGGER GALADM.INVOICE_DETAIL_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE OR REPLACE TRIGGER GALADM.INVOICE_DETAIL_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.INVOICE_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.INVOICE_SUMMARY_TBX
        (INVOICE_NO DECIMAL(10,0) NOT NULL,
        SUM_PRICE DECIMAL(14,2) NOT NULL,
        SUM_TOTAL_QUANTITY INTEGER NOT NULL,
        QUOTATION_NO CHARACTER(20) DEFAULT ' ' NOT NULL,
        SUM_SHIPMENT_NO CHARACTER(3) DEFAULT ' ',
        SUM_INVOICE_DATE DATE, SHIP_DATE DATE,
        CREATE_TIMESTAMP TIMESTAMP,
        UPDATE_TIMESTAMP TIMESTAMP,
        PRIMARY KEY (INVOICE_NO, QUOTATION_NO)
        )
        IN GALTBSDAT7
        INDEX IN GALTBSIDX3;
        
COMMENT ON TABLE GALADM.INVOICE_SUMMARY_TBX IS 'OIF Invoice(Summary Record)';

CREATE OR REPLACE TRIGGER GALADM.INVOICE_SUMMARY_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.INVOICE_SUMMARY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE OR REPLACE TRIGGER GALADM.INVOICE_SUMMARY_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.INVOICE_SUMMARY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
