alter table GALADM.QI_DEFECT_RESULT_TBX add column DEFECT_TRANSACTION_GROUP_ID BIGINT DEFAULT 0 NOT NULL; 
alter table GALADM.QI_DEFECT_RESULT_HIST_TBX add column DEFECT_TRANSACTION_GROUP_ID BIGINT DEFAULT 0 NOT NULL; 
alter table GALADM.QI_REPAIR_RESULT_TBX add column DEFECT_TRANSACTION_GROUP_ID BIGINT DEFAULT 0 NOT NULL; 
alter table GALADM.QI_REPAIR_RESULT_HIST_TBX add column DEFECT_TRANSACTION_GROUP_ID BIGINT DEFAULT 0 NOT NULL;
