------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_APPLICATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_APPLICATION_TR1;
DROP TRIGGER GALADM.QI_MAPPING_APPLICATION_TR2;
DROP TABLE GALADM.QI_MAPPING_APPLICATION_TBX;

CREATE TABLE GALADM.QI_MAPPING_APPLICATION_TBX
(
	APPLICATION_ID        CHAR(16) NOT NULL ,
	OLD_APPLICATION_ID    CHAR(16) NOT NULL ,
	TERMINAL_NAME         VARCHAR(32),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_APPLICATION_TBX IS 'NAQ Application ID Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_APPLICATION_I1
  ON GALADM.QI_MAPPING_APPLICATION_TBX (APPLICATION_ID, OLD_APPLICATION_ID);

ALTER TABLE GALADM.QI_MAPPING_APPLICATION_TBX 
	ADD CONSTRAINT QI_MAPPING_APPLICATION_PK PRIMARY KEY (APPLICATION_ID, OLD_APPLICATION_ID);
		
ALTER TABLE GALADM.QI_MAPPING_APPLICATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_APPLICATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_APPLICATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_APPLICATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_APPLICATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_ENTRY_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR1;
DROP TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR2;
DROP TABLE GALADM.QI_MAPPING_ENTRY_DEPT_TBX;

CREATE TABLE GALADM.QI_MAPPING_ENTRY_DEPT_TBX
(
	ENTRY_SITE_NAME       CHAR(16) NOT NULL ,
	ENTRY_PLANT_NAME      CHAR(16) NOT NULL ,
	ENTRY_PROD_LINE_NO    SMALLINT NOT NULL ,
	ENTRY_DEPT            CHAR(16) NOT NULL ,
	OLD_ENTRY_SITE		  CHAR(16) NOT NULL,
	OLD_ENTRY_PLANT       CHAR(16) NOT NULL ,
	OLD_ENTRY_PROD_LINE_NO  SMALLINT NOT NULL ,
	OLD_ENTRY_DEPT        CHAR(16) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_ENTRY_DEPT_TBX IS 'NAQ Entry Department Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_ENTRY_DEPT_I1
  ON GALADM.QI_MAPPING_ENTRY_DEPT_TBX (ENTRY_SITE_NAME,ENTRY_PLANT_NAME,ENTRY_PROD_LINE_NO,ENTRY_DEPT,OLD_ENTRY_SITE,OLD_ENTRY_PLANT,OLD_ENTRY_PROD_LINE_NO,OLD_ENTRY_DEPT);

ALTER TABLE GALADM.QI_MAPPING_ENTRY_DEPT_TBX 
	ADD CONSTRAINT QI_MAPPING_ENTRY_DEPT_PK PRIMARY KEY (ENTRY_SITE_NAME,ENTRY_PLANT_NAME,ENTRY_PROD_LINE_NO,ENTRY_DEPT,OLD_ENTRY_SITE,OLD_ENTRY_PLANT,OLD_ENTRY_PROD_LINE_NO,OLD_ENTRY_DEPT);
		
ALTER TABLE GALADM.QI_MAPPING_ENTRY_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_ENTRY_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_IMAGE_NAME_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR1;
DROP TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR2;
DROP TABLE GALADM.QI_MAPPING_IMAGE_NAME_TBX;

CREATE TABLE GALADM.QI_MAPPING_IMAGE_NAME_TBX
(
	IMAGE_NAME         VARCHAR(20) NOT NULL ,
	OLD_IMAGE_NAME     VARCHAR(20) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_IMAGE_NAME_TBX IS 'NAQ IMAGE_NAME Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_IMAGE_NAME_I1
  ON GALADM.QI_MAPPING_IMAGE_NAME_TBX (IMAGE_NAME,OLD_IMAGE_NAME);

ALTER TABLE GALADM.QI_MAPPING_IMAGE_NAME_TBX 
	ADD CONSTRAINT QI_MAPPING_IMAGE_NAME_PK PRIMARY KEY (IMAGE_NAME,OLD_IMAGE_NAME);
		
ALTER TABLE GALADM.QI_MAPPING_IMAGE_NAME_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_IMAGE_NAME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_IMAGE_NAME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_IMAGE_NAME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_IQS_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_IQS_TR1;
DROP TRIGGER GALADM.QI_MAPPING_IQS_TR2;
DROP TABLE GALADM.QI_MAPPING_IQS_TBX;

CREATE TABLE GALADM.QI_MAPPING_IQS_TBX
(
	IQS_ID                INTEGER NOT NULL ,	
	OLD_IQS_CATEGORY_NAME    VARCHAR(32) NOT NULL ,
	OLD_IQS_ITEM_NAME     VARCHAR(64) NOT NULL ,
	IQS_VERSION           CHAR(16) NOT NULL ,
	IQS_CATEGORY          VARCHAR(32) NOT NULL ,
	IQS_QUESTION_NO       INTEGER,
	IQS_QUESTION          VARCHAR(256),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_IQS_TBX IS 'NAQ IQS Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_IQS_I1
  ON GALADM.QI_MAPPING_IQS_TBX (IQS_ID, OLD_IQS_CATEGORY_NAME, OLD_IQS_ITEM_NAME);

ALTER TABLE GALADM.QI_MAPPING_IQS_TBX 
	ADD CONSTRAINT QI_MAPPING_IQS_PK PRIMARY KEY (IQS_ID, OLD_IQS_CATEGORY_NAME, OLD_IQS_ITEM_NAME);
		
ALTER TABLE GALADM.QI_MAPPING_IQS_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_IQS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_IQS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_REPAIR_AREA_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_REPAIR_AREA_TR1;
DROP TRIGGER GALADM.QI_MAPPING_REPAIR_AREA_TR2;
DROP TABLE GALADM.QI_MAPPING_REPAIR_AREA_TBX;

CREATE TABLE GALADM.QI_MAPPING_REPAIR_AREA_TBX
(
	REPAIR_AREA         VARCHAR(64) NOT NULL ,
	OLD_REPAIR_AREA     VARCHAR(64) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_REPAIR_AREA_TBX IS 'NAQ REPAIR_AREA Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_REPAIR_AREA_I1
  ON GALADM.QI_MAPPING_REPAIR_AREA_TBX (REPAIR_AREA,OLD_REPAIR_AREA);

ALTER TABLE GALADM.QI_MAPPING_REPAIR_AREA_TBX 
	ADD CONSTRAINT QI_MAPPING_REPAIR_AREA_PK PRIMARY KEY (REPAIR_AREA,OLD_REPAIR_AREA);
		
ALTER TABLE GALADM.QI_MAPPING_REPAIR_AREA_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_REPAIR_AREA_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_REPAIR_AREA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_REPAIR_AREA_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_REPAIR_AREA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_REPAIR_METHOD_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_REPAIR_METHOD_TR1;
DROP TRIGGER GALADM.QI_MAPPING_REPAIR_METHOD_TR2;
DROP TABLE GALADM.QI_MAPPING_REPAIR_METHOD_TBX;

CREATE TABLE GALADM.QI_MAPPING_REPAIR_METHOD_TBX
(
	REPAIR_METHOD         VARCHAR(64) NOT NULL ,
	OLD_REPAIR_METHOD     VARCHAR(64) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_REPAIR_METHOD_TBX IS 'NAQ Repair Method Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_REPAIR_METHOD_I1
  ON GALADM.QI_MAPPING_REPAIR_METHOD_TBX (REPAIR_METHOD,OLD_REPAIR_METHOD);

ALTER TABLE GALADM.QI_MAPPING_REPAIR_METHOD_TBX 
	ADD CONSTRAINT QI_MAPPING_REPAIR_METHOD_PK PRIMARY KEY (REPAIR_METHOD,OLD_REPAIR_METHOD);
		
ALTER TABLE GALADM.QI_MAPPING_REPAIR_METHOD_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_REPAIR_METHOD_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_REPAIR_METHOD_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_REPAIR_METHOD_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_REPAIR_METHOD_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_RESPONSIBILITY_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR1;
DROP TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR2;
DROP TABLE GALADM.QI_MAPPING_RESPONSIBILITY_TBX;

CREATE TABLE GALADM.QI_MAPPING_RESPONSIBILITY_TBX
(
	RESPONSIBLE_SITE      CHAR(16) NOT NULL ,
	RESPONSIBLE_PLANT     CHAR(16) NOT NULL ,
	RESPONSIBLE_DEPT      CHAR(16) NOT NULL ,
	RESPONSIBLE_LEVEL3    VARCHAR(32) NOT NULL ,
	RESPONSIBLE_LEVEL2    VARCHAR(32) NOT NULL ,
	RESPONSIBLE_LEVEL1    VARCHAR(32) NOT NULL ,
	OLD_RESPONSIBLE_SITE   CHAR(16) NOT NULL ,
	OLD_RESPONSIBLE_PLANT  CHAR(16) NOT NULL ,
	OLD_RESPONSIBLE_DEPT  CHAR(16) NOT NULL ,
	OLD_RESPONSIBLE_LEVEL3  VARCHAR(32) NOT NULL ,
	OLD_RESPONSIBLE_LEVEL2  VARCHAR(32) NOT NULL ,
	OLD_RESPONSIBLE_LEVEL1  VARCHAR(32) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_RESPONSIBILITY_TBX IS 'NAQ Responsible Level Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_RESPONSIBILITY_I1
  ON GALADM.QI_MAPPING_RESPONSIBILITY_TBX (RESPONSIBLE_SITE,RESPONSIBLE_PLANT,RESPONSIBLE_DEPT,RESPONSIBLE_LEVEL3,RESPONSIBLE_LEVEL2,RESPONSIBLE_LEVEL1,OLD_RESPONSIBLE_SITE,OLD_RESPONSIBLE_PLANT,OLD_RESPONSIBLE_DEPT,OLD_RESPONSIBLE_LEVEL3,OLD_RESPONSIBLE_LEVEL2,OLD_RESPONSIBLE_LEVEL1);

ALTER TABLE GALADM.QI_MAPPING_RESPONSIBILITY_TBX 
	ADD CONSTRAINT QI_MAPPING_RESPONSIBILITY_PK PRIMARY KEY (RESPONSIBLE_SITE,RESPONSIBLE_PLANT,RESPONSIBLE_DEPT,RESPONSIBLE_LEVEL3,RESPONSIBLE_LEVEL2,RESPONSIBLE_LEVEL1,OLD_RESPONSIBLE_SITE,OLD_RESPONSIBLE_PLANT,OLD_RESPONSIBLE_DEPT,OLD_RESPONSIBLE_LEVEL3,OLD_RESPONSIBLE_LEVEL2,OLD_RESPONSIBLE_LEVEL1);
		
ALTER TABLE GALADM.QI_MAPPING_RESPONSIBILITY_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_RESPONSIBILITY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_THEME_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_THEME_TR1;
DROP TRIGGER GALADM.QI_MAPPING_THEME_TR2;
DROP TABLE GALADM.QI_MAPPING_THEME_TBX;

CREATE TABLE GALADM.QI_MAPPING_THEME_TBX
(
	THEME         VARCHAR(64) NOT NULL ,
	OLD_THEME     VARCHAR(64) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_THEME_TBX IS 'NAQ Theme Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_THEME_I1
  ON GALADM.QI_MAPPING_THEME_TBX (THEME,OLD_THEME);

ALTER TABLE GALADM.QI_MAPPING_THEME_TBX 
	ADD CONSTRAINT QI_MAPPING_THEME_PK PRIMARY KEY (THEME,OLD_THEME);
		
ALTER TABLE GALADM.QI_MAPPING_THEME_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_THEME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_THEME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_WRITE_UP_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR1;
DROP TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR2;
DROP TABLE GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX;

CREATE TABLE GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX
(
	RESPONSIBLE_SITE      CHAR(16) NOT NULL ,
	RESPONSIBLE_PLANT     CHAR(16) NOT NULL ,
	WRITE_UP_DEPARTMENT   VARCHAR(32) NOT NULL ,
	OLD_WRITE_UP_DEPARTMENT  VARCHAR(32) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX IS 'NAQ Write Up Department Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_WRITE_UP_DEPT_I1
  ON GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX (RESPONSIBLE_SITE,RESPONSIBLE_PLANT,WRITE_UP_DEPARTMENT,OLD_WRITE_UP_DEPARTMENT);

ALTER TABLE GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX 
	ADD CONSTRAINT QI_MAPPING_WRITE_UP_DEPT_PK PRIMARY KEY (RESPONSIBLE_SITE,RESPONSIBLE_PLANT,WRITE_UP_DEPARTMENT,OLD_WRITE_UP_DEPARTMENT);
		
ALTER TABLE GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_WRITE_UP_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_WRITE_UP_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  