
ALTER TABLE GALADM.STRAGGLER_TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.STRAGGLER_TBX ADD COLUMN STRAGGLER_TYPE  CHARACTER(10) NOT NULL DEFAULT ‘LOT’;
ALTER TABLE GALADM.STRAGGLER_TBX ADD CONSTRAINT STRAGGLER_PK PRIMARY KEY(PRODUCT_ID, PP_DELAYED_AT,STRAGGLER_TYPE);
