ALTER TABLE GALADM.GAL261TBX ADD COLUMN SUB_PRODUCT_TYPE CHAR (10);

ALTER TABLE GALADM.GAL185TBX ADD COLUMN PRODUCT_TYPE CHAR (10);

ALTER TABLE GALADM.GAL185_HIST_TBX ADD COLUMN PRODUCT_TYPE CHAR (10);
