--############################################################
ALTER TABLE GALADM.GAL703TBX_01
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_01
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_01
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_01;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_01;  
  
  
--############################################################
ALTER TABLE GALADM.GAL703TBX_02
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_02
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_02
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_02;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_02;   
  
--############################################################
ALTER TABLE GALADM.GAL703TBX_03
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_03
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_03
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_03;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_03; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_04
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_04
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_04
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_04;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_04; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_05
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_05
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_05
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_05;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_05; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_06
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_06
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_06
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL703TBX_06;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_06; 

--############################################################
ALTER TABLE GALADM.GAL712TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL712TBX
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL712TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL712TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL712TBX;   

--############################################################