ALTER TABLE GALADM.MC_VIOS_MASTER_OP_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 
reorg table GALADM.MC_VIOS_MASTER_OP_TBX;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 
reorg table GALADM.MC_VIOS_MASTER_OP_CHECKER_TBX;	
			
ALTER TABLE GALADM.MC_VIOS_MASTER_PLATFORM_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 
reorg table GALADM.MC_VIOS_MASTER_PLATFORM_TBX;

ALTER TABLE GALADM.MC_VIOS_MASTER_ASM_PROC_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 
reorg table GALADM.MC_VIOS_MASTER_ASM_PROC_TBX;