ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN CORRECTION_REQUEST_BY VARCHAR(32);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN REASON_FOR_CHANGE VARCHAR(256);
 
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN CORRECTION_REQUEST_BY VARCHAR(32);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN REASON_FOR_CHANGE VARCHAR(256);
 
ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX ADD COLUMN CORRECTION_REQUEST_BY VARCHAR(32);
ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX ADD COLUMN REASON_FOR_CHANGE VARCHAR(256);
 
ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX ADD COLUMN CORRECTION_REQUEST_BY VARCHAR(32);
ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX ADD COLUMN REASON_FOR_CHANGE VARCHAR(256);

ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN PROCESS_NAME SET DATA TYPE VARCHAR(35);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN TEAM SET DATA TYPE VARCHAR(25);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_TBX;

ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN PROCESS_NAME SET DATA TYPE VARCHAR(35);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN TEAM SET DATA TYPE VARCHAR(25);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_TBX;

ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX ALTER COLUMN PROCESS_NAME SET DATA TYPE VARCHAR(35);
ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX ALTER COLUMN TEAM SET DATA TYPE VARCHAR(25);
ALTER TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_HIST_TBX;

ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX ALTER COLUMN PROCESS_NAME SET DATA TYPE VARCHAR(35);
ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX ALTER COLUMN TEAM SET DATA TYPE VARCHAR(25);
ALTER TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_HIST_TBX;


