-- RGALCDEV-1461 - Die Hold - new parameters: Model Code and Sand Core
-- HOLD_PARM_TBX
set schema galadm;
DROP TRIGGER GALADM.HOLD_PARM_TR2;
DROP TRIGGER GALADM.HOLD_PARM_TR1;
ALTER TABLE GALADM.HOLD_PARM_TBX DATA CAPTURE NONE; 

ALTER TABLE GALADM.HOLD_PARM_TBX ADD COLUMN MODEL_CODE VARCHAR(3); 
ALTER TABLE GALADM.HOLD_PARM_TBX ADD COLUMN CORE_NUMBER VARCHAR(80);
ALTER TABLE GALADM.HOLD_PARM_TBX ALTER COLUMN DIE_NUMBER DROP NOT NULL; 

CREATE TRIGGER GALADM.HOLD_PARM_TR1 NO CASCADE BEFORE INSERT ON GALADM.HOLD_PARM_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
CREATE TRIGGER GALADM.HOLD_PARM_TR2 NO CASCADE BEFORE UPDATE ON GALADM.HOLD_PARM_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
ALTER TABLE GALADM.HOLD_PARM_TBX DATA CAPTURE CHANGES;  
REORG TABLE GALADM.HOLD_PARM_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.HOLD_PARM_TBX;


-- QSR_TBX
set schema galadm;
DROP TRIGGER GALADM.QSR_TR2;
DROP TRIGGER GALADM.QSR_TR1;
ALTER TABLE GALADM.QSR_TBX DATA CAPTURE NONE; 

ALTER TABLE GALADM.QSR_TBX ALTER COLUMN DESCRIPTION SET DATA TYPE VARCHAR(250); 

CREATE TRIGGER GALADM.QSR_TR1 NO CASCADE BEFORE INSERT ON GALADM.QSR_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
CREATE TRIGGER GALADM.QSR_TR2 NO CASCADE BEFORE UPDATE ON GALADM.QSR_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
ALTER TABLE GALADM.QSR_TBX DATA CAPTURE CHANGES;  
REORG TABLE GALADM.QSR_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.QSR_TBX;