DROP TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR2;
DROP TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR1;
DROP TABLE GALADM.PRODUCT_ATTRIBUTES_TBX;

CREATE TABLE GALADM.PRODUCT_ATTRIBUTES_TBX (
  PRODUCT_ID	VARCHAR(255)	NOT NULL,
  ATTRIBUTE	CHARACTER(32)	NOT NULL,
  ACTUAL_TIMESTAMP	TIMESTAMP,
  ATTRIBUTE_VALUE	VARCHAR(512),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT PRODUCT_ATTRIBUTES_PK PRIMARY KEY
     (PRODUCT_ID,ATTRIBUTE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PRODUCT_ATTRIBUTES_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PRODUCT_ATTRIBUTES_TBX IS 'RMT ProductAttributes';

CREATE TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_ATTRIBUTES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_ATTRIBUTES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;