update GALADM.GAL206TBX set PART_SERIAL_NUMBER_MASK = REPLACE(PART_SERIAL_NUMBER_MASK,'{','<');
update GALADM.GAL206TBX set PART_SERIAL_NUMBER_MASK = REPLACE(PART_SERIAL_NUMBER_MASK,'}','>');

update GALADM.PART_SPEC_TBX set PART_SERIAL_NUMBER_MASK = REPLACE(PART_SERIAL_NUMBER_MASK,'{','<');
update GALADM.PART_SPEC_TBX set PART_SERIAL_NUMBER_MASK = REPLACE(PART_SERIAL_NUMBER_MASK,'}','>');

