------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPAIR_AREA_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_REPAIR_AREA_TR1;
DROP TRIGGER GALADM.QI_REPAIR_AREA_TR2;
DROP TABLE GALADM.QI_REPAIR_AREA_TBX;

CREATE TABLE GALADM.QI_REPAIR_AREA_TBX
(

	REPAIR_AREA_NAME      VARCHAR(20) NOT NULL ,
	SITE_NAME			  CHAR(16),
	PLANT_NAME			  CHAR(16),
	REPAIR_AREA_DESCRIPTION  VARCHAR(30),
	LOCATION      		  CHAR(1),
	PRIORITY  			  SMALLINT,
	ROW_FILL_SEQ          CHAR(1),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_REPAIR_AREA_TBX IS 'NAQ Repair Area';

CREATE UNIQUE INDEX GALADM.QI_REPAIR_AREA_I1
  ON GALADM.QI_REPAIR_AREA_TBX (REPAIR_AREA_NAME);

ALTER TABLE GALADM.QI_REPAIR_AREA_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_PK PRIMARY KEY (REPAIR_AREA_NAME);
	
CREATE INDEX GALADM.QI_REPAIR_AREA_I2
  ON GALADM.QI_REPAIR_AREA_TBX (SITE_NAME, PLANT_NAME, REPAIR_AREA_NAME);
	
ALTER TABLE GALADM.QI_REPAIR_AREA_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_TBX  
	ADD CONSTRAINT QI_REPAIR_AREA_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPAIR_AREA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPAIR_AREA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPAIR_AREA_ROW_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_REPAIR_AREA_ROW_TR1;
DROP TRIGGER GALADM.QI_REPAIR_AREA_ROW_TR2;
DROP TABLE GALADM.QI_REPAIR_AREA_ROW_TBX;

CREATE TABLE GALADM.QI_REPAIR_AREA_ROW_TBX
(

	REPAIR_AREA_NAME      VARCHAR(20) NOT NULL ,
	REPAIR_AREA_ROW		  INTEGER NOT NULL,
	SPACE_FILL_SEQ        CHAR(1),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_REPAIR_AREA_ROW_TBX IS 'NAQ Repair Area Row';

CREATE UNIQUE INDEX GALADM.QI_REPAIR_AREA_ROW_I1
  ON GALADM.QI_REPAIR_AREA_ROW_TBX (REPAIR_AREA_NAME, REPAIR_AREA_ROW);

ALTER TABLE GALADM.QI_REPAIR_AREA_ROW_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_ROW_PK PRIMARY KEY (REPAIR_AREA_NAME, REPAIR_AREA_ROW);
	
ALTER TABLE GALADM.QI_REPAIR_AREA_ROW_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_ROW_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_ROW_TBX  
	ADD CONSTRAINT QI_REPAIR_AREA_ROW_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_ROW_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_ROW_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPAIR_AREA_ROW_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_ROW_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPAIR_AREA_ROW_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPAIR_AREA_SPACE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_REPAIR_AREA_SPACE_TR1;
DROP TRIGGER GALADM.QI_REPAIR_AREA_SPACE_TR2;
DROP TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX;

CREATE TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX
(

	REPAIR_AREA_NAME      VARCHAR(20) NOT NULL ,
	REPAIR_AREA_ROW		  INTEGER NOT NULL,
	REPAIR_AREA_SPACE	  INTEGER NOT NULL,
	TARGET_RESP_DEPT	  CHAR(16),
	TARGET_REPAIR_AREA	  VARCHAR(20),
	PRODUCT_ID			  CHAR(17),
	DEFECTRESULTID		  INTEGER,
	ACTIVE				  SMALLINT,
	APP_CREATE_TIMESTAMP      TIMESTAMP,
	APP_UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX IS 'NAQ Repair Area Space';

CREATE UNIQUE INDEX GALADM.QI_REPAIR_AREA_SPACE_I1
  ON GALADM.QI_REPAIR_AREA_SPACE_TBX (REPAIR_AREA_NAME, REPAIR_AREA_ROW, REPAIR_AREA_SPACE);

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_PK PRIMARY KEY (REPAIR_AREA_NAME, REPAIR_AREA_ROW, REPAIR_AREA_SPACE);
	
ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX  
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_SPACE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPAIR_AREA_SPACE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_SPACE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPAIR_AREA_SPACE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
      