------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_EXTERNAL_SYSTEM_DATA_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR1;
DROP TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR2;
DROP TABLE GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX;

CREATE TABLE GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX
(
	EXTERNAL_SYSTEM_NAME  CHAR(18) NOT NULL ,
	EXTERNAL_PART_CODE    VARCHAR(64) NOT NULL ,
	EXTERNAL_DEFECT_CODE  VARCHAR(64) NOT NULL ,
	PRODUCT_ID            CHAR(17) NOT NULL ,
	PROCESS_POINT_ID      CHAR(16) NOT NULL ,
	ENTRY_TIMESTAMP       TIMESTAMP NOT NULL ,
	ENTRY_SITE            CHAR(16),
	ENTRY_DEPT            CHAR(16),
	PRODUCT_TYPE          CHAR(10),
	ORIGINAL_DEFECT_STATUS  SMALLINT,
	CURRENT_DEFECT_STATUS  SMALLINT,
	WRITE_UP_DEPT         CHAR(16),
	IMAGE_NAME            VARCHAR(20),
	ASSOCIATE_ID          CHAR(11),
	POINT_X               INTEGER,
	POINT_Y               INTEGER,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX IS 'NAQ table for failed data from External System';

CREATE UNIQUE INDEX GALADM.QI_EXTERNAL_SYSTEM_DATA_I1
  ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX (EXTERNAL_SYSTEM_NAME,EXTERNAL_PART_CODE,EXTERNAL_DEFECT_CODE,PRODUCT_ID,PROCESS_POINT_ID,ENTRY_TIMESTAMP);

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX 
	ADD CONSTRAINT QI_EXTERNAL_SYSTEM_DATA_PK PRIMARY KEY (EXTERNAL_SYSTEM_NAME,EXTERNAL_PART_CODE,EXTERNAL_DEFECT_CODE,PRODUCT_ID,PROCESS_POINT_ID,ENTRY_TIMESTAMP);
	
CREATE INDEX GALADM.QI_EXTERNAL_SYSTEM_DATA_I2
	ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX (EXTERNAL_SYSTEM_NAME, EXTERNAL_PART_CODE, EXTERNAL_DEFECT_CODE);
	
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_EXTERNAL_SYSTEM_DATA_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_EXTERNAL_SYSTEM_DATA_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


