DROP TRIGGER GALADM.MC_PDDA_PROCESS_TR2;
DROP TRIGGER GALADM.MC_PDDA_PROCESS_TR1;
DROP TABLE GALADM.MC_PDDA_PROCESS_TBX;

CREATE TABLE GALADM.MC_PDDA_PLATFORM_TBX (
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   PLANT_LOC_CODE		CHARACTER(1)	NOT NULL,
   DEPT_CODE			CHARACTER(2)	NOT NULL,
   MODEL_YEAR_DATE		DECIMAL(5, 1)	NOT NULL,
   PROD_SCH_QTY			DECIMAL(5, 1)	NOT NULL,
   PROD_ASM_LINE_NO		CHARACTER(1)	NOT NULL,
   VEHICLE_MODEL_CODE	CHARACTER(1)	NOT NULL,
   ASM_PROC_NO			VARCHAR(5)		NOT NULL,
   PROCESS_POINT_ID 	CHARACTER(16)	NOT NULL,
   PROCESS_SEQ_NUM  	INTEGER,
   APPROVER_NO			CHARACTER(11),
   APPROVED				TIMESTAMP,
   DEPRECATER_NO		CHARACTER(11),
   DEPRECATED			TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_PLATFORM_PK PRIMARY KEY 
     (PDDA_PLATFORM_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_PLATFORM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_PLATFORM_TBX IS 'RMT MC_PDDA_PLATFORM is used by Manufacturing Control to link PDDA Plant Loc Code, Dept Code, Model Year Date, Prod Sch Qty, Prod ASM Line No, Vehicle Model Code, ASM Proc No to GALC Process Point ID';
    
CREATE TRIGGER GALADM.MC_PDDA_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_PDDA_PLATFORM_I1
  ON GALADM.MC_PDDA_PLATFORM_TBX
    ( PLANT_LOC_CODE, DEPT_CODE, MODEL_YEAR_DATE, PROD_SCH_QTY, PROD_ASM_LINE_NO, VEHICLE_MODEL_CODE, ASM_PROC_NO )
  ALLOW REVERSE SCANS
  COMPRESS NO;

DROP TRIGGER GALADM.MC_PDDA_UNIT_TR2;
DROP TRIGGER GALADM.MC_PDDA_UNIT_TR1;
DROP TABLE GALADM.MC_PDDA_UNIT_TBX;

CREATE TABLE GALADM.MC_PDDA_UNIT_TBX (
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   UNIT_NO		     	VARCHAR(6)	 	NOT NULL,
   APPROVER_NO	     	CHARACTER(11),
   APPROVED				TIMESTAMP,
   DEPRECATER_NO		CHARACTER(11),
   DEPRECATED			TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_UNIT_PK PRIMARY KEY 
     (OPERATION_NAME, UNIT_NO )
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_UNIT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_UNIT_TBX IS 'RMT MC_PDDA_UNIT is used by Manufacturing Control to define the active PDDA Platforms and Unit No associated to an Operation Name';
    
CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_UNIT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_UNIT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_OP_REV_PLATFORM_TR2;
DROP TRIGGER GALADM.MC_OP_REV_PLATFORM_TR1;
DROP TABLE GALADM.MC_OP_REV_PLATFORM_TBX;

CREATE TABLE GALADM.MC_OP_REV_PLATFORM_TBX (
   OPERATION_NAME		CHARACTER(32) 	NOT NULL,
   OP_REV           	INTEGER 		NOT NULL,
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   OP_SEQ_NUM       	INTEGER,
   OP_TIME          	INTEGER,
   DEVICE_ID        	CHARACTER(32),
   DEVICE_MSG       	CHARACTER(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_REV_PLATFORM_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PLATFORM_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_REV_PLATFORM_TBX IS 'RMT MC_OP_REV_PLATFORM is used by Manufacturing Control to define the platforms that should perform this revision of operation';
    
CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_REV_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_REV_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_OP_MATRIX_TR2;
DROP TRIGGER GALADM.MC_OP_MATRIX_TR1;
DROP TABLE GALADM.MC_OP_MATRIX_TBX;

CREATE TABLE GALADM.MC_OP_MATRIX_TBX (
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   OP_REV             	INTEGER 		NOT NULL,
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   SPEC_CODE_TYPE     	VARCHAR(32) 	NOT NULL,
   SPEC_CODE_MASK     	VARCHAR(30) 	NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_MATRIX_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PLATFORM_ID, SPEC_CODE_TYPE, SPEC_CODE_MASK)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_MATRIX_TBX IS 'RMT MC_OP_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MC_STRUCTUREs';
    
CREATE TRIGGER GALADM.MC_OP_MATRIX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_MATRIX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.MC_STRUCTURE_TR2;
DROP TRIGGER GALADM.MC_STRUCTURE_TR1;
DROP TABLE GALADM.MC_STRUCTURE_TBX;

CREATE TABLE GALADM.MC_STRUCTURE_TBX (
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV      	BIGINT 			NOT NULL,
   PROCESS_POINT_ID   	CHARACTER(16) 	NOT NULL,
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   OP_REV             	INTEGER 		NOT NULL,
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   PART_ID            	CHARACTER(5) 	NOT NULL DEFAULT '',
   PART_REV           	INTEGER 		NOT NULL DEFAULT 0,
   CREATE_TIMESTAMP	  	TIMESTAMP,
   UPDATE_TIMESTAMP	  	TIMESTAMP,
   CONSTRAINT MC_STRUCTURE_PK PRIMARY KEY 
     (PRODUCT_SPEC_CODE, STRUCTURE_REV, PROCESS_POINT_ID, OPERATION_NAME, OP_REV, PDDA_PLATFORM_ID, PART_ID, PART_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_STRUCTURE_TBX IS 'RMT MC_STRUCTURE is used by Manufacturing Control to define the revisions of operations and parts that are used to manufacture a Product Spec Code';
    
CREATE TRIGGER GALADM.MC_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_PDDA_UNIT_REV_TR2;
DROP TRIGGER GALADM.MC_PDDA_UNIT_REV_TR1;
DROP TABLE GALADM.MC_PDDA_UNIT_REV_TBX;

CREATE TABLE GALADM.MC_PDDA_UNIT_REV_TBX (
   OPERATION_NAME		CHARACTER(32) 	NOT NULL,
   OP_REV           	INTEGER 		NOT NULL,
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   UNIT_NO		     	VARCHAR(6)	 	NOT NULL,
   PDDA_REPORT			VARCHAR(6)		NOT NULL,
   APVD_PROC_MAINT_ID	INTEGER			NOT NULL,
   APVD_UNIT_MAINT_ID	INTEGER			NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_UNIT_REV_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PLATFORM_ID, UNIT_NO, PDDA_REPORT)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_UNIT_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_UNIT_REV_TBX IS 'RMT MC_PDDA_UNIT_REV is used by Manufacturing Control to define the approved PDDA revision of units on the given PDDA report';
    
CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_UNIT_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_UNIT_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
     