ALTER TABLE GALADM.GAL106TBX
  ADD COLUMN CONROD_WEIGHT_INDEX VARCHAR(5)
  ADD COLUMN CONROD_RANK_INDEX VARCHAR(5)
  ADD COLUMN CRANK_CON_INDEX VARCHAR(7)
  ADD COLUMN CRANK_MAIN_INDEX VARCHAR(7);
  
  
