ALTER TABLE GALADM.GAL729TBX  ADD COLUMN END_TIMESTAMP     TIMESTAMP    NOT NULL  DEFAULT CURRENT TIMESTAMP;
ALTER TABLE GALADM.GAL729TBX  ADD COLUMN LET_TERMINAL_ID   CHARACTER(3)	NOT NULL  DEFAULT ' ';
ALTER TABLE GALADM.GAL729TBX  ADD COLUMN DIAG_TEST_ID      INTEGER	    NOT NULL  DEFAULT 0;

ALTER TABLE GALADM.GAL729TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.GAL729TBX ADD PRIMARY KEY (END_TIMESTAMP, LET_TERMINAL_ID, DIAG_TEST_ID, DIAG_PARAM_ID);