ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX RENAME COLUMN TEMPORARY_TRACKING TO LOCAL_THEME;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX RENAME COLUMN TEMPORARY_TRACKING TO LOCAL_THEME;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX RENAME COLUMN TEMPORARY_TRACKING TO LOCAL_THEME;

ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN UNIT_DESC SET DATA TYPE VARCHAR(254);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_TBX;

ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN UNIT_DESC SET DATA TYPE VARCHAR(254);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_TBX;

DROP TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR1;
DROP TRIGGER GALADM.QI_TEMPORARY_TRACKING_TR2;
DROP TABLE GALADM.QI_TEMPORARY_TRACKING_TBX;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_LOCAL_THEME_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_LOCAL_THEME_TR1;
DROP TRIGGER GALADM.QI_LOCAL_THEME_TR2;
DROP TABLE GALADM.QI_LOCAL_THEME_TBX;

CREATE TABLE GALADM.QI_LOCAL_THEME_TBX
(
	LOCAL_THEME    		  CHAR(18) NOT NULL ,
	LOCAL_THEME_DESCRIPTION    VARCHAR(64),
	ACTIVE                SMALLINT,	
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_LOCAL_THEME_TBX IS 'NAQ Local Theme';

CREATE UNIQUE INDEX GALADM.QI_LOCAL_THEME_I1
  ON GALADM.QI_LOCAL_THEME_TBX (LOCAL_THEME);

ALTER TABLE GALADM.QI_LOCAL_THEME_TBX 
	ADD CONSTRAINT QI_LOCAL_THEME_PK PRIMARY KEY (LOCAL_THEME);
		
ALTER TABLE GALADM.QI_LOCAL_THEME_TBX 
	ADD CONSTRAINT QI_LOCAL_THEME_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_LOCAL_THEME_TBX  
	ADD CONSTRAINT QI_LOCAL_THEME_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

CREATE TRIGGER GALADM.QI_LOCAL_THEME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_LOCAL_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_LOCAL_THEME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_LOCAL_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;      