DROP TRIGGER GALADM.DC_ZONE_TBX_TR2;
DROP TRIGGER GALADM.DC_ZONE_TBX_TR1;
DROP TABLE GALADM.DC_ZONE_TBX;

CREATE TABLE GALADM.DC_ZONE_TBX (
	ZONE_ID char(16) NOT NULL,
	PROCESS_POINT_ID char(16) NOT NULL,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_TIMESTAMP TIMESTAMP,
	CONSTRAINT DC_ZONE_TBX_PK PRIMARY KEY (ZONE_ID,PROCESS_POINT_ID)
)
	IN GALTBSDAT1
	INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.DC_ZONE_TBX
	DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE GALADM.DC_ZONE_TBX IS
   'RMT Process points by zones representing areas of responsibility';
   
CREATE TRIGGER GALADM.DC_ZONE_TBX_TR1
	NO CASCADE BEFORE INSERT
	ON GALADM.DC_ZONE_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.DC_ZONE_TBX_TR2
	NO CASCADE BEFORE UPDATE
	ON GALADM.DC_ZONE_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX
	GALADM.DC_ZONE_TBX_I1
	ON GALADM.DC_ZONE_TBX
	(ZONE_ID ASC, PROCESS_POINT_ID DESC )
	ALLOW REVERSE SCANS
	COMPRESS NO;
