--SmartBear 388
ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL215TBX  
  ALTER COLUMN PRODUCT_SPEC_CODE  
    SET DATA TYPE CHARACTER(30); 
     
ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE CHANGES; 
      

--SmartBear 384
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX 
  ALTER COLUMN HOST_PORT 
    SET DATA TYPE INTEGER;
    
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;

--SmartBear 383
DROP ALIAS HCM_GAL492TBX;
DROP TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR2;
DROP TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR1;
DROP TABLE GALADM.DEFECT_ACTUAL_PROBLEM_TBX;

DROP ALIAS GALADM.HCM_GAL493TBX;
DROP TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR2;
DROP TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR1;
DROP TABLE GALADM.DEFECT_REPAIR_METHOD_TBX; 

--Identified missing default in VER 0.0.0.0 DDL
ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL650TBX
  ALTER COLUMN NEEDS_LISTENER
    SET DEFAULT 0;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE CHANGES;

--SmartBear 371  
DROP ALIAS GALADM.HCM_BLOCK_BUILD_RESULTS_TBX;
DROP ALIAS GALADM.HCM_BLOCK_HISTORY_TBX;
DROP ALIAS GALADM.HCM_BLOCK_LOAD_TBX;
DROP ALIAS GALADM.HCM_BLOCK_TBX;
DROP ALIAS GALADM.HCM_HEAD_BUILD_RESULTS_TBX;
DROP ALIAS GALADM.HCM_HEAD_HISTORY_TBX;
DROP ALIAS GALADM.HCM_HEAD_TBX;
DROP ALIAS GALADM.HCM_HLD_PARM_TBX;
DROP ALIAS GALADM.HCM_PRODUCT_SEQUENCE_TBX;
DROP ALIAS GALADM.HCM_QUORUM_DETAIL_TBX;
DROP ALIAS GALADM.HCM_QUORUM_TBX;
DROP ALIAS GALADM.HCM_REQUIRED_PARTS_TBX;
DROP ALIAS GALADM.HCM_STANDARD_SCHEDULE_TBX;
DROP ALIAS GALADM.HCM_TRAILER_INFO_TBX;
DROP ALIAS GALADM.HCM_TRAILER_STATUS;
  