-- Adding FormId
INSERT INTO galadm.GAL294TBX (FORM_ID,DESTINATION_ID,DEFAULT_FLAG,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) 
VALUES ('DUNNAGE_PRINT','',1,CURRENT_TIMESTAMP,null);
-- Adding Template object
INSERT INTO galadm.TEMPLATES_TBX (TEMPLATE_NAME,TEMPLATE_DESCRIPTION,TEMPLATE_TYPE,TEMPLATE_DATA,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,FORM_ID,REVISION_ID) 
VALUES ('DUNNAGE_PRINT','Printing Dunnage information','JASPER',EMPTY_BLOB(),CURRENT_TIMESTAMP,null,'DUNNAGE_PRINT',null);
-- Adding print Attributes
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('DUNNAGE_PRINT','PRODUCT_TYPE_NAME',0,0,2,'PRODUCT_TYPE_NAME',1,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('DUNNAGE_PRINT','DUNNAGE_NUMBER',0,0,2,'DUNNAGE_NUMBER',1,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('DUNNAGE_PRINT','SHIFT',0,0,1,'05',1,CURRENT_TIMESTAMP,null,1);





