
------------------------------------------------
-- DDL Statements for Table "GALADM  "."CONROD_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CONROD_TBX"  (
		  "CONROD_ID" VARCHAR(19) NOT NULL , 
		  "MC_SERIAL_NUMBER" VARCHAR(19) , 
		  "DC_SERIAL_NUMBER" VARCHAR(16) , 
		  "ENGINE_SERIAL_NUMBER" VARCHAR(40) , 
		  "MODEL" VARCHAR(12) , 
		  "TRACKING_STATUS" VARCHAR(12) , 
		  "DUNNAGE" VARCHAR(12) , 
		  "DEFECT_STATUS" SMALLINT , 
		  "HOLD_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE "GALADM  "."CONROD_TBX" IS 'RMT Conrod';


-- DDL Statements for Primary Key on Table "GALADM  "."CONROD_TBX"

ALTER TABLE "GALADM  "."CONROD_TBX" 
	ADD CONSTRAINT "CONROD_PK" PRIMARY KEY
		("CONROD_ID");



-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

CREATE INDEX "GALADM  "."CONROD_I1" ON "GALADM  "."CONROD_TBX" 
		("ENGINE_SERIAL_NUMBER" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

CREATE INDEX "GALADM  "."CONROD_I2" ON "GALADM  "."CONROD_TBX" 
		("DC_SERIAL_NUMBER" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

CREATE INDEX "GALADM  "."CONROD_I3" ON "GALADM  "."CONROD_TBX" 
		("DUNNAGE" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CONROD_TBX"

CREATE INDEX "GALADM  "."CONROD_I4" ON "GALADM  "."CONROD_TBX" 
		("LAST_PASSING_PROCESS_POINT_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."CONROD_BUILD_RESULTS_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CONROD_BUILD_RESULTS_TBX"  (
		  "CONROD_ID" VARCHAR(19) NOT NULL , 
		  "PART_NAME" VARCHAR(32) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2" ; 

COMMENT ON TABLE "GALADM  "."CONROD_BUILD_RESULTS_TBX" IS 'RMT ConrodBuildResult';


-- DDL Statements for Primary Key on Table "GALADM  "."CONROD_BUILD_RESULTS_TBX"

ALTER TABLE "GALADM  "."CONROD_BUILD_RESULTS_TBX" 
	ADD CONSTRAINT "CONROD_BUILD_RESULTS_PK" PRIMARY KEY
		("CONROD_ID",
		 "PART_NAME");



------------------------------------------------
-- DDL Statements for Table "GALADM  "."CONROD_HISTORY_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CONROD_HISTORY_TBX"  (
		  "CONROD_ID" VARCHAR(19) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_COUNT" INTEGER NOT NULL WITH DEFAULT 1 )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2" ; 

COMMENT ON TABLE "GALADM  "."CONROD_HISTORY_TBX" IS 'RMT ConrodHistory';


-- DDL Statements for Primary Key on Table "GALADM  "."CONROD_HISTORY_TBX"

ALTER TABLE "GALADM  "."CONROD_HISTORY_TBX" 
	ADD CONSTRAINT "CONROD_HISTORY_PK" PRIMARY KEY
		("CONROD_ID",
		 "PROCESS_POINT_ID",
		 "ACTUAL_TIMESTAMP");



-- DDL Statements for Indexes on Table "GALADM  "."CONROD_HISTORY_TBX"

CREATE INDEX "GALADM  "."CONROD_HISTORY_I1" ON "GALADM  "."CONROD_HISTORY_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."CRANKSHAFT_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CRANKSHAFT_TBX"  (
		  "CRANKSHAFT_ID" VARCHAR(26) NOT NULL , 
		  "MC_SERIAL_NUMBER" VARCHAR(26) , 
		  "DC_SERIAL_NUMBER" VARCHAR(18) , 
		  "ENGINE_SERIAL_NUMBER" VARCHAR(17) , 
		  "MODEL" VARCHAR(12) , 
		  "TRACKING_STATUS" VARCHAR(12) , 
		  "DUNNAGE" VARCHAR(12) , 
		  "DEFECT_STATUS" SMALLINT , 
		  "HOLD_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LAST_PASSING_PROCESS_POINT_ID" CHAR(16) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE "GALADM  "."CRANKSHAFT_TBX" IS 'RMT Crankshaft';


-- DDL Statements for Primary Key on Table "GALADM  "."CRANKSHAFT_TBX"

ALTER TABLE "GALADM  "."CRANKSHAFT_TBX" 
	ADD CONSTRAINT "CRANKSHAFT_PK" PRIMARY KEY
		("CRANKSHAFT_ID");



-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_TBX"

CREATE INDEX "GALADM  "."CRANKSHAFT_I1" ON "GALADM  "."CRANKSHAFT_TBX" 
		("ENGINE_SERIAL_NUMBER" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_TBX"

CREATE INDEX "GALADM  "."CRANKSHAFT_I2" ON "GALADM  "."CRANKSHAFT_TBX" 
		("DC_SERIAL_NUMBER" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_TBX"

CREATE INDEX "GALADM  "."CRANKSHAFT_I3" ON "GALADM  "."CRANKSHAFT_TBX" 
		("DUNNAGE" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_TBX"

CREATE INDEX "GALADM  "."CRANKSHAFT_I4" ON "GALADM  "."CRANKSHAFT_TBX" 
		("LAST_PASSING_PROCESS_POINT_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."CRANKSHAFT_BUILD_RESULTS_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CRANKSHAFT_BUILD_RESULTS_TBX"  (
		  "CRANKSHAFT_ID" VARCHAR(26) NOT NULL , 
		  "PART_NAME" VARCHAR(32) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2" ; 

COMMENT ON TABLE "GALADM  "."CRANKSHAFT_BUILD_RESULTS_TBX" IS 'RMT CrankshaftBuildResult';


-- DDL Statements for Primary Key on Table "GALADM  "."CRANKSHAFT_BUILD_RESULTS_TBX"

ALTER TABLE "GALADM  "."CRANKSHAFT_BUILD_RESULTS_TBX" 
	ADD CONSTRAINT "CRANKSHAFT_BUILD_RESULTS_PK" PRIMARY KEY
		("CRANKSHAFT_ID",
		 "PART_NAME");



------------------------------------------------
-- DDL Statements for Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX"  (
		  "CRANKSHAFT_ID" VARCHAR(26) NOT NULL , 
		  "PROCESS_POINT_ID" CHAR(16) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_COUNT" INTEGER NOT NULL WITH DEFAULT 1 )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSDAT3" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX" IS 'RMT CrankshaftHistory';


-- DDL Statements for Primary Key on Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"

ALTER TABLE "GALADM  "."CRANKSHAFT_HISTORY_TBX" 
	ADD CONSTRAINT "CRANKSHAFT_HISTORY_PK" PRIMARY KEY
		("CRANKSHAFT_ID",
		 "PROCESS_POINT_ID",
		 "ACTUAL_TIMESTAMP");



-- DDL Statements for Indexes on Table "GALADM  "."CRANKSHAFT_HISTORY_TBX"

CREATE INDEX "GALADM  "."CRANKSHAFT_HISTORY_I1" ON "GALADM  "."CRANKSHAFT_HISTORY_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "ACTUAL_TIMESTAMP" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;







-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_BUILD_RESULTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CONROD_BUILD_RESULTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_BUILD_RESULTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CONROD_BUILD_RESULTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_HISTORY_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CONROD_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_HISTORY_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CONROD_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CONROD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CONROD_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CONROD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_BUILD_RESULTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CRANKSHAFT_BUILD_RESULTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_BUILD_RESULTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CRANKSHAFT_BUILD_RESULTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_HISTORY_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CRANKSHAFT_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_HISTORY_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CRANKSHAFT_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CRANKSHAFT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.CRANKSHAFT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CRANKSHAFT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


COMMIT WORK;

