DROP TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR2; 
DROP TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR1; 
DROP TABLE GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX;

CREATE TABLE GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX (
    FORM_ID CHARACTER(32) NOT NULL,
    MODEL_CODE CHARACTER(3) NOT NULL,
    MODEL_YEAR_CODE CHARACTER(1) NOT NULL,
    ATTRIBUTE CHARACTER(32) NOT NULL,
    ROW INTEGER,
    COL INTEGER,
    CREATE_TIMESTAMP TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (FORM_ID, MODEL_CODE, MODEL_YEAR_CODE, ATTRIBUTE)
) IN GALTBSREF11 INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX IS 'Build Sheet Grid Maintenance';

CREATE TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_SHEET_PART_ATTR_MAINT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;