alter table GALADM.GAL131TBX data capture none;
ALTER TABLE GALADM.GAL131TBX ALTER COLUMN ACTUAL_MISSION_TYPE SET DATA TYPE CHAR(22);
alter table GALADM.GAL131TBX data capture changes;

reorg table GALADM.GAL131TBX;

alter table GALADM.GAL143TBX data capture none;
ALTER TABLE GALADM.GAL143TBX ALTER COLUMN ACTUAL_MISSION_TYPE SET DATA TYPE CHAR(22);
alter table GALADM.GAL143TBX data capture changes;

reorg table GALADM.GAL143TBX;

DROP TRIGGER GALADM.GAL143_TR1;
DROP TRIGGER GALADM.GAL143_TR2;
DROP TRIGGER GALADM.GAL131_TR1;
DROP TRIGGER GALADM.GAL131_TR2;

CREATE TRIGGER GALADM.GAL143_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL143TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL143_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL143TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL131_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL131_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
