
--MODEL_PART
ALTER TABLE "LCVINBOM"."MODEL_PART" DROP CONSTRAINT "MODEL_PART_PK";
ALTER TABLE "LCVINBOM"."MODEL_PART" DROP COLUMN "STARTING_PRODUCTION_LOT";

ALTER TABLE "LCVINBOM"."MODEL_PART" ADD COLUMN "MODEL_PART_ID" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "LCVINBOM"."MODEL_PART" ALTER COLUMN "MODEL_PART_ID" DROP DEFAULT;
ALTER TABLE "LCVINBOM"."MODEL_PART" ALTER COLUMN "MODEL_PART_ID" SET GENERATED ALWAYS AS IDENTITY;
REORG TABLE "LCVINBOM"."MODEL_PART";
UPDATE "LCVINBOM"."MODEL_PART" SET "MODEL_PART_ID" = DEFAULT;

ALTER TABLE "LCVINBOM"."MODEL_PART" ADD COLUMN "DC_NUMBER" VARCHAR(10);
ALTER TABLE "LCVINBOM"."MODEL_PART" ADD COLUMN "DC_CLASS" CHAR(1);
ALTER TABLE "LCVINBOM"."MODEL_PART" ADD COLUMN "DC_EFF_BEG_DATE" DATE;
ALTER TABLE "LCVINBOM"."MODEL_PART" ADD CONSTRAINT "MODEL_PART_PK" PRIMARY KEY ("MODEL_PART_ID");
ALTER TABLE "LCVINBOM"."MODEL_PART" ADD CONSTRAINT "MODELPART_IX1" UNIQUE ("PRODUCT_SPEC_WILDCARD","LET_SYSTEM_NAME", "DC_PART_NUMBER");

  
--MODEL_LOT
DROP TABLE "LCVINBOM  "."MODEL_LOT";

CREATE TABLE "LCVINBOM  "."MODEL_LOT"  (
		  "MODEL_PART_ID" BIGINT NOT NULL , 
		  "PLAN_CODE" CHAR(11) NOT NULL , 
		  "STARTING_PRODUCTION_LOT" CHAR(20) NOT NULL , 		  
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."MODEL_LOT" IS 'VIN-BOM Link Rule to Lot Assignment';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."MODEL_LOT"

ALTER TABLE "LCVINBOM  "."MODEL_LOT" 
	ADD CONSTRAINT "MODEL_LOT_PK" PRIMARY KEY
		("MODEL_PART_ID","PLAN_CODE");
		
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_LOT_TR1";

CREATE TRIGGER LCVINBOM.MODEL_LOT_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.MODEL_LOT
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_LOT_TR2";

CREATE TRIGGER LCVINBOM.MODEL_LOT_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.MODEL_LOT
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


--MODEL_PART_APPROVAL
DROP TABLE "LCVINBOM  "."MODEL_PART_APPROVAL";

CREATE TABLE "LCVINBOM  "."MODEL_PART_APPROVAL"  (
		  "MODEL_PART_APPROVAL_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ,
		  "MODEL_PART_ID" BIGINT NOT NULL , 
		  "CURRENT_REFLASH" INTEGER NOT NULL , 
		  "NEW_REFLASH" INTEGER NOT NULL ,
		  "CURRENT_INTERCHANGABLE" INTEGER NOT NULL ,
		  "NEW_INTERCHANGABLE" INTEGER NOT NULL ,
		  "CURRENT_SCRAP_PARTS" INTEGER NOT NULL ,
		  "NEW_SCRAP_PARTS" INTEGER NOT NULL ,
		  "CURRENT_STARTING_PRODUCTION_LOT" CHAR(20) NOT NULL , 		  
		  "NEW_STARTING_PRODUCTION_LOT" CHAR(20) NOT NULL ,
		  "REQUEST_ASSOCIATE_NUMBER" CHAR(11 OCTETS) NOT NULL ,
		  "REQUEST_TIMESTAMP" TIMESTAMP NOT NULL ,
		  "APPROVE_ASSOCIATE_NUMBER" CHAR(11 OCTETS) ,
		  "APPROVE_TIMESTAMP" TIMESTAMP ,
		  "APPROVE_STATUS" INTEGER NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."MODEL_PART_APPROVAL" IS 'VIN-BOM Approvals to change rule and lot assignment';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."MODEL_PART_APPROVAL"

ALTER TABLE "LCVINBOM  "."MODEL_PART_APPROVAL" 
	ADD CONSTRAINT "MODEL_PART_APPROVAL_PK" PRIMARY KEY
		("MODEL_PART_APPROVAL_ID");
		
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_PART_APPROVAL_TR1";

CREATE TRIGGER LCVINBOM.MODEL_PART_APPROVAL_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.MODEL_PART_APPROVAL
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_PART_APPROVAL_TR2";

CREATE TRIGGER LCVINBOM.MODEL_PART_APPROVAL_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.MODEL_PART_APPROVAL
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


--DESIGN_CHANGE_RULES
DROP TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES";

CREATE TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES"  (
		  "DC_CLASS" VARCHAR(10 OCTETS) NOT NULL ,		  
		  "REFLASH" INTEGER NOT NULL ,
		  "INTERCHANGABLE" INTEGER NOT NULL ,		  
		  "SCRAP_PARTS" INTEGER NOT NULL ,		  
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES" IS 'VIN-BOM Rules Applied to Design Changes';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."DESIGN_CHANGE_RULES"

ALTER TABLE "LCVINBOM  "."DESIGN_CHANGE_RULES" 
	ADD CONSTRAINT "DESIGN_CHANGE_RULES_PK" PRIMARY KEY
		("DC_CLASS");

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."DESIGN_CHANGE_RULES_TR1";

CREATE TRIGGER LCVINBOM.DESIGN_CHANGE_RULES_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.DESIGN_CHANGE_RULES
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."DESIGN_CHANGE_RULES_TR2";

CREATE TRIGGER LCVINBOM.DESIGN_CHANGE_RULES_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.DESIGN_CHANGE_RULES
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

-------------------------------
-- Add Default Data
-------------------------------

INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('A', 1, 0, 1, '2021-04-22 13:29:59.873203', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('B', 1, 1, 1, '2021-04-22 13:29:59.910272', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('C', 2, 2, 2, '2021-04-22 13:29:59.962081', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('D', 0, 1, 0, '2021-04-22 13:30:00.000264', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('E', 0, 1, 0, '2021-04-22 13:30:00.056491', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('J', 0, 1, 0, '2021-04-22 13:30:00.092246', null);
INSERT INTO DESIGN_CHANGE_RULES (DC_CLASS, REFLASH, INTERCHANGABLE, SCRAP_PARTS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP) VALUES ('L', 2, 2, 2, '2021-04-22 13:29:59.962081', null);

