ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_TBX ADD COLUMN ACTUAL_TIMESTAMP TIMESTAMP;
ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX ADD COLUMN TARGET_RESP_DEPT CHAR(16);
ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX ADD COLUMN TARGET_REPAIR_AREA VARCHAR(20);
