------------------------------------------------
-- DDL Statements for BUILD_RESULT_TABLES
------------------------------------------------
--GALCDB_VER_1.34.0.0_SEQ1.sql

-- BUILD RESULTS TABLE UPDATE, ADD PROCESS_POINT_ID COLUMN
ALTER TABLE GALADM.HEAD_BUILD_RESULTS_TBX 
ADD PROCESS_POINT_ID VARCHAR(16);
ALTER TABLE GALADM.BLOCK_BUILD_RESULTS_TBX 
ADD PROCESS_POINT_ID VARCHAR(16);
ALTER TABLE GALADM.CONROD_BUILD_RESULTS_TBX 
ADD PROCESS_POINT_ID VARCHAR(16);
ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_TBX 
ADD PROCESS_POINT_ID VARCHAR(16);
