
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE_TBX";


  CREATE TABLE GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TBX (
  PRODUCTION_LOT	CHARACTER(20)	NOT NULL,
  SEQUENCE_NUMBER	INTEGER	NOT NULL,
  MBPN	CHARACTER(18)	NOT NULL,
  COMBINATION_CODE	VARCHAR(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  ) 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;
  
COMMENT ON TABLE "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE_TBX" IS 'RMT Production Lot Mbpn Sequence';


-- DDL Statements for Indexes on Table "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';


-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE"

ALTER TABLE GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TBX
  ADD CONSTRAINT PRODUCTION_LOT_MBPN_SEQUENCE_PK PRIMARY KEY
    (PRODUCTION_LOT, SEQUENCE_NUMBER);;


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE_TR1";

CREATE TRIGGER GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."PRODUCTION_LOT_MBPN_SEQUENCE_TR2";

CREATE TRIGGER GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCTION_LOT_MBPN_SEQUENCE_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


