--Changes to add the STAMP_SERIAL_DESC and BOUNDARY_MARK received in the MISSION_SPEC_CODE_TBX. 
ALTER TABLE GALADM.MISSION_SPEC_CODE_TBX DATA CAPTURE NONE;

ALTER TABLE GALADM.MISSION_SPEC_CODE_TBX ADD COLUMN STAMP_SERIAL_DESC VARCHAR(30) ADD COLUMN BOUNDARY_MARK VARCHAR(1);

ALTER TABLE GALADM.MISSION_SPEC_CODE_TBX DATA CAPTURE CHANGES;

DROP TRIGGER GALADM.MISSION_SPEC_CODE_TR1;
DROP TRIGGER GALADM.MISSION_SPEC_CODE_TR2;

CREATE TRIGGER GALADM.MISSION_SPEC_CODE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MISSION_SPEC_CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MISSION_SPEC_CODE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MISSION_SPEC_CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
