SELECT MAX(DEFECTRESULTID) FROM GALADM.QI_DEFECT_RESULT_TBX;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN DEFECTRESULTID DROP IDENTITY;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN DEFECTRESULTID SET DATA TYPE BIGINT;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN DEFECTRESULTID SET GENERATED DEFAULT AS IDENTITY (START WITH #######); 
--##### is max of DEFECTRESULTID + 1
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_TBX;

SELECT MAX(REPAIR_ID) FROM GALADM.QI_REPAIR_RESULT_TBX;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN REPAIR_ID DROP IDENTITY;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN REPAIR_ID SET DATA TYPE BIGINT;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN REPAIR_ID SET GENERATED DEFAULT AS IDENTITY (START WITH #######); 
--##### is max of REPAIR_ID + 1
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN DEFECTRESULTID SET DATA TYPE BIGINT;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_TBX;
