DROP TRIGGER GALADM.GAL130_TR2;
DROP TRIGGER GALADM.GAL130_TR1;
DROP TABLE GALADM.GAL130TBX;

CREATE TABLE GALADM.GAL130TBX (
	PROCESS_LOCATION char(2) DEFAULT '' NOT NULL,
	PROCESS_POINT_ID char(16) DEFAULT '' NOT NULL,
	END_PRODUCTION_LOT char(20),
	CREATE_TIMESTAMP TIMESTAMP,
	UPDATE_TIMESTAMP TIMESTAMP,
	CONSTRAINT GAL130_PK PRIMARY KEY (PROCESS_LOCATION,PROCESS_POINT_ID)
)

	IN GALTBSDAT7
	INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL130TBX
	DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL130TBX IS 'Download Lot Sequence';

CREATE TRIGGER GALADM.GAL130_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL130TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL130_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL130TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX
	GALADM.GAL130TBX_I1
	ON GALADM.GAL130TBX
	(PROCESS_LOCATION ASC, PROCESS_POINT_ID DESC )
	ALLOW REVERSE SCANS
	COMPRESS NO;
