ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN COMMENT VARCHAR(256);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN COMMENT VARCHAR(256);

ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN ENTRY_MODEL VARCHAR(32);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX 
	ADD CONSTRAINT QI_DEFECT_RESULT_C17 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN ENTRY_MODEL VARCHAR(32);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX 
	ADD CONSTRAINT QI_REPAIR_RESULT_C17 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));			
		
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ALTER COLUMN BOM_MAIN_PART_NO SET DATA TYPE CHAR(5);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_TBX;

ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ALTER COLUMN BOM_MAIN_PART_NO SET DATA TYPE CHAR(5);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_TBX;
		
		