CREATE INDEX GALADM.GAL185_I4 
	ON GALADM.GAL185TBX 
		(PROCESS_POINT_ID ASC, CREATE_TIMESTAMP ASC) 
	ALLOW REVERSE SCANS 
	COMPRESS NO;
	
CREATE INDEX GALADM.GAL185_I5 
	ON GALADM.GAL185TBX 
		(PROCESS_POINT_ID ASC, ACTUAL_TIMESTAMP ASC) 
	ALLOW REVERSE SCANS 
	COMPRESS NO;