--Run these commented commands as well to enable MySQL compatibility
--db2set DB2_COMPATIBILITY_VECTOR=MYS
--db2stop
--db2start
UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = 'PRODUCT_SEARCH_FILTER_BACKGROUND_COLOR' WHERE PROPERTY_KEY = 'PRODUCT_ENTRY_FILTER_BACKGROUND_COLOR';
UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = 'PRODUCT_SEARCH_FILTER_ENABLED' WHERE PROPERTY_KEY = 'PRODUCT_ENTRY_FILTER_ENABLED';
UPDATE GALADM.GAL489TBX SET PROPERTY_KEY = CONCAT('PRODUCT_SEARCH_RADIO_BUTTONS',SUBSTR(PROPERTY_KEY,28)) WHERE PROPERTY_KEY LIKE 'PRODUCT_ENTRY_RADIO_BUTTONS%';
