ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX ADD COLUMN ORIENTATION_ANGLE SMALLINT DEFAULT 0;
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX ALTER COLUMN ENTRY_MODEL SET DATA TYPE VARCHAR(32);
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_MODEL_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_MODEL_TR1;
DROP TRIGGER GALADM.QI_ENTRY_MODEL_TR2;
DROP TABLE GALADM.QI_ENTRY_MODEL_TBX;

CREATE TABLE GALADM.QI_ENTRY_MODEL_TBX
(
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,
	ENTRY_MODEL_DESCRIPTION  VARCHAR(32),
	PRODUCT_TYPE          CHAR(10),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_MODEL_TBX IS 'NAQ Entry Model';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_MODEL_I1
  ON GALADM.QI_ENTRY_MODEL_TBX (ENTRY_MODEL, IS_USED);

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_PK PRIMARY KEY (ENTRY_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_C1 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX  
	ADD CONSTRAINT QI_ENTRY_MODEL_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR1;
DROP TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR2;
DROP TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX;

CREATE TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX
(
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	MTC_MODEL             CHAR(4) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX IS 'NAQ Entry Model Grouping';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_MODEL_GROUPING_I1
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX (ENTRY_MODEL, MTC_MODEL, IS_USED);

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_PK PRIMARY KEY (ENTRY_MODEL, MTC_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C1 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX  
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_TBX
(
	ENTRY_SCREEN          VARCHAR(40) NOT NULL ,
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,
	ENTRY_SCREEN_DESCRIPTION  VARCHAR(30),
	IS_IMAGE              SMALLINT,
	PRODUCT_TYPE          CHAR(10),
	IMAGE_NAME            VARCHAR(20),
	SCREEN_IS_USED		  SMALLINT,
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_TBX IS 'NAQ Entry Screen';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_I1
  ON GALADM.QI_ENTRY_SCREEN_TBX (ENTRY_SCREEN, ENTRY_MODEL, IS_USED);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_PK PRIMARY KEY (ENTRY_SCREEN, ENTRY_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_C4 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX
(
	ENTRY_SCREEN          VARCHAR(40) NOT NULL ,
	DIVISION_ID           CHAR(16) NOT NULL ,
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX IS 'NAQ Entry Screen by Department';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_DEPT_I1
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX (ENTRY_SCREEN, DIVISION_ID, ENTRY_MODEL, IS_USED);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_PK PRIMARY KEY (ENTRY_SCREEN, DIVISION_ID, ENTRY_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEPT_C4 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1;
DROP TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2;
DROP TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX;

CREATE TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
(
	ENTRY_SCREEN          VARCHAR(40) NOT NULL ,
	REGIONAL_DEFECT_COMBINATION_ID  INTEGER NOT NULL ,	
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,
	TEXT_ENTRY_MENU       VARCHAR(32),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX IS 'NAQ Entry Screen Defect Combination';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_I1
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX (ENTRY_SCREEN, REGIONAL_DEFECT_COMBINATION_ID, ENTRY_MODEL, IS_USED);

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_PK PRIMARY KEY (ENTRY_SCREEN, REGIONAL_DEFECT_COMBINATION_ID, ENTRY_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C2 CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU));			
		
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX  
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_ENTRY_SCREEN_DEFECT_COMBINATION_C5 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));			

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_TEXT_ENTRY_MENU_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR1;
DROP TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR2;
DROP TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX;

CREATE TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX
(
	ENTRY_SCREEN          VARCHAR(40) NOT NULL ,
	TEXT_ENTRY_MENU       VARCHAR(32) NOT NULL ,
	ENTRY_MODEL           VARCHAR(32) NOT NULL ,
	IS_USED				  SMALLINT NOT NULL,	
	TEXT_ENTRY_MENU_DESC  VARCHAR(64),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX IS 'NAQ Text Entry Menu by Entry Screen';

CREATE UNIQUE INDEX GALADM.QI_TEXT_ENTRY_MENU_I1
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX (ENTRY_SCREEN, TEXT_ENTRY_MENU, ENTRY_MODEL, IS_USED);

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_PK PRIMARY KEY (ENTRY_SCREEN, TEXT_ENTRY_MENU, ENTRY_MODEL, IS_USED);
	
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C2 CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU));			
		
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX  
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
	ADD CONSTRAINT QI_TEXT_ENTRY_MENU_C5 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));			

ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_TEXT_ENTRY_MENU_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_TEXT_ENTRY_MENU_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

        
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_LOCAL_DEFECT_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_LOCAL_DEFECT_COMBINATION_TR1;
DROP TRIGGER GALADM.QI_LOCAL_DEFECT_COMBINATION_TR2;
DROP TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX;

CREATE TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX
(
	LOCAL_DEFECT_COMBINATION_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,	
	REGIONAL_DEFECT_COMBINATION_ID  INTEGER NOT NULL,
	ENTRY_SITE_NAME       CHARACTER(16),
	ENTRY_PLANT_NAME      CHARACTER(16),
	RESPONSIBLE_LEVEL_ID	INTEGER,
	PDDA_RESPONSIBILITY_ID  INTEGER,
	ENTRY_MODEL           VARCHAR(32),
	ENTRY_SCREEN          VARCHAR(40),
	IS_USED				  SMALLINT,
	TEXT_ENTRY_MENU       VARCHAR(32),
	REPAIR_METHOD         VARCHAR(64),
	REPAIR_METHOD_TIME    SMALLINT,
	ESTIMATED_TIME_TO_FIX  INTEGER,
	LOCAL_THEME           CHAR(18),
	ENGINE_FIRING_FLAG    SMALLINT NOT NULL  DEFAULT 0,
	REPAIR_AREA_NAME      CHAR(20),
	DEFECT_CATEGORY_NAME  VARCHAR(32),
	REPORTABLE			  SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX IS 'NAQ Local Defect Combination';

CREATE UNIQUE INDEX GALADM.QI_LOCAL_DEFECT_COMBINATION_I1
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX (LOCAL_DEFECT_COMBINATION_ID);
  
CREATE INDEX GALADM.QI_LOCAL_DEFECT_COMBINATION_I2
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX (REGIONAL_DEFECT_COMBINATION_ID);  
  
CREATE INDEX GALADM.QI_LOCAL_DEFECT_COMBINATION_I3
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX (ENTRY_SCREEN);  
  
CREATE INDEX GALADM.QI_LOCAL_DEFECT_COMBINATION_I4
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX (RESPONSIBLE_LEVEL_ID); 

ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_LOCAL_DEFECT_COMBINATION_PK PRIMARY KEY (LOCAL_DEFECT_COMBINATION_ID);
	
ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_LOCAL_DEFECT_COMBINATION_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_LOCAL_DEFECT_COMBINATION_C2 CHECK 
		(TEXT_ENTRY_MENU = UPPER(TEXT_ENTRY_MENU));	
				
ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX 
	ADD CONSTRAINT QI_LOCAL_DEFECT_COMBINATION_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX  
	ADD CONSTRAINT QI_LOCAL_DEFECT_COMBINATION_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_LOCAL_DEFECT_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_LOCAL_DEFECT_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
