ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX ALTER COLUMN ENTRY_MODEL SET DATA TYPE CHAR(4);
REORG TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_MODEL_TBX DATA CAPTURE CHANGES;