DROP TABLE GALADM.DUNNAGE_TBX;
DROP TRIGGER GALADM.DUNNAGE_TR1;
DROP TRIGGER GALADM.DUNNAGE_TR2;

CREATE TABLE GALADM.DUNNAGE_TBX
(
DUNNAGE_ID VARCHAR(20) NOT NULL,
EXPECTED_QTY SMALLINT,
PRODUCT_SPEC_CODE VARCHAR(30) ,
DUNNAGE_STATUS SMALLINT,
CREATE_TIMESTAMP TIMESTAMP , 
UPDATE_TIMESTAMP TIMESTAMP
) IN GALTBSDAT10 INDEX IN GALTBSIDX3;

CREATE UNIQUE INDEX GALADM.DUNNAGE_PK ON GALADM.DUNNAGE_TBX(DUNNAGE_ID ASC) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.DUNNAGE_TBX ADD CONSTRAINT DUNNAGE_PK PRIMARY KEY (DUNNAGE_ID);

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.DUNNAGE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.DUNNAGE_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.DUNNAGE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.DUNNAGE_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TABLE GALADM.DUNNAGE_CONTENT_TBX;
DROP TRIGGER GALADM.DUNNAGE_CONTENT_TR1;
DROP TRIGGER GALADM.DUNNAGE_CONTENT_TR2;

CREATE TABLE GALADM.DUNNAGE_CONTENT_TBX
(
   DUNNAGE_ID VARCHAR(20) NOT NULL,
   PRODUCT_ID VARCHAR(17) NOT NULL,
   DUNNAGE_ROW VARCHAR(8) ,
   DUNNAGE_COLUMN VARCHAR(8) ,
   DUNNAGE_LAYER VARCHAR(8) ,
   CREATE_TIMESTAMP TIMESTAMP ,
   UPDATE_TIMESTAMP TIMESTAMP
) IN GALTBSDAT10 INDEX IN GALTBSIDX3;

CREATE UNIQUE INDEX GALADM.DUNNAGE_CONTENT_PK ON GALADM.DUNNAGE_CONTENT_TBX(DUNNAGE_ID ASC,PRODUCT_ID ASC) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.DUNNAGE_CONTENT_TBX ADD CONSTRAINT DUNNAGE_CONTENT_PK PRIMARY KEY (DUNNAGE_ID ,PRODUCT_ID);

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.DUNNAGE_CONTENT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.DUNNAGE_CONTENT_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.DUNNAGE_CONTENT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.DUNNAGE_CONTENT_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


ALTER TABLE GALADM.HEAD_TBX ALTER COLUMN DUNNAGE SET DATA TYPE VARCHAR(20);
ALTER TABLE GALADM.BLOCK_TBX ALTER COLUMN DUNNAGE SET DATA TYPE VARCHAR(20);
ALTER TABLE GALADM.CRANKSHAFT_TBX ALTER COLUMN DUNNAGE SET DATA TYPE VARCHAR(20);
ALTER TABLE GALADM.CONROD_TBX ALTER COLUMN DUNNAGE SET DATA TYPE VARCHAR(20);

