
------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."SYSTEM_RELATIONSHIP"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."SYSTEM_RELATIONSHIP";

CREATE TABLE "LCVINBOM  "."SYSTEM_RELATIONSHIP"  (
	      "BEAM_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL ,
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 	
		  "CREATE_TIMESTAMP" TIMESTAMP , 
          "UPDATE_USER" CHAR(11 OCTETS) NOT NULL ,
		  "UPDATE_TIMESTAMP" TIMESTAMP ,
		  CONSTRAINT "SYSTEM_RELATIONSHIP_PK" PRIMARY KEY("BEAM_SYSTEM_NAME","LET_SYSTEM_NAME") )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."SYSTEM_RELATIONSHIP" IS 'VIN-BOM system Multipart Relatioship';

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."SYSTEM_RELATIONSHIP_TR1";

CREATE TRIGGER LCVINBOM.SYSTEM_RELATIONSHIP_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.SYSTEM_RELATIONSHIP
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."SYSTEM_RELATIONSHIP_TR2";

CREATE TRIGGER LCVINBOM.SYSTEM_RELATIONSHIP_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.SYSTEM_RELATIONSHIP
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
