DROP TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR2;
DROP TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR1;
DROP TABLE GALADM.ENGINE_MANIFEST_TBX;

CREATE TABLE GALADM.ENGINE_MANIFEST_TBX
(
     ENGINE_NO             CHAR       (  12)      NOT NULL,
     MODEL_YEAR_CODE       CHAR       (   1)      NOT NULL,
     ENGINE_MODEL          CHAR       (   3)      NOT NULL,
     ENGINE_TYPE           CHAR       (   3)      NOT NULL,
     ENGINE_OPTION         CHAR       (   2)      NOT NULL,
     ENGINE_BASIC_PART     CHAR       (  17)      NOT NULL WITH DEFAULT,
     ENGINE_PC_NO          CHAR       (   9)      NOT NULL WITH DEFAULT,
     ENGINE_CASE_NO        CHAR       (   7)      NOT NULL WITH DEFAULT,
     ENGINE_EC_NO          CHAR       (  10)      NOT NULL WITH DEFAULT,
     MISSION_NO            CHAR       (  11)      NOT NULL,
     COMPANY               CHAR       (   3)      NOT NULL,
     PLANT                 CHAR       (   3)      NOT NULL,
     VIN                   CHAR       (  17)      NOT NULL WITH DEFAULT,
     ENGINE_KD_LOT         CHAR       (  11)      NOT NULL,
     ENGINE_FIRED_IND      CHAR       (   1)      NOT NULL,
     ENGINE_SOURCE         CHAR       (   5)      NOT NULL WITH DEFAULT,
     UNSHIP_STATUS         INT,
     CREATE_TIMESTAMP      TIMESTAMP,
     UPDATE_TIMESTAMP      TIMESTAMP)
 IN GALTBSDAT4 INDEX IN GALTBSIDX3;
COMMENT ON TABLE GALADM.ENGINE_MANIFEST_TBX IS 'ENGINE MANIFEST';

CREATE UNIQUE INDEX GALADM.ENGINE_MANIFEST_I1 on GALADM.ENGINE_MANIFEST_TBX
        (ENGINE_NO, PLANT) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.ENGINE_MANIFEST_TBX ADD CONSTRAINT ENGINE_MANIFEST_PK Primary Key
        (ENGINE_NO, PLANT);


CREATE TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ENGINE_MANIFEST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.ENGINE_MANIFEST_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ENGINE_MANIFEST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR2;
DROP TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR1;
DROP TABLE GALADM.ENGINE_MANIFEST_HIST_TBX;

CREATE TABLE GALADM.ENGINE_MANIFEST_HIST_TBX (
     ENGINE_NO             CHAR       (  12)      NOT NULL,
     COMPANY               CHAR       (   3)      NOT NULL,
     PLANT                 CHAR       (   3)      NOT NULL,
     DEPARTMENT            CHAR       (   2)      NOT NULL,
     LINE                  CHAR       (   1)      NOT NULL,
     PROCESS               CHAR       (   3)      NOT NULL,
     ACTUAL_TIMESTAMP      TIMESTAMP              NOT NULL,
     PRODUCTION_DATE       DATE                   NOT NULL,
     VIN                   CHAR       (  17)      NOT NULL,
     ENGINE_FIRED_IND      CHAR       (   1)      NOT NULL,
     ENGINE_SOURCE         CHAR       (   5)      NOT NULL WITH DEFAULT,
     CREATE_TIMESTAMP      TIMESTAMP,
     UPDATE_TIMESTAMP      TIMESTAMP)
   IN GALTBSDAT4 INDEX IN GALTBSIDX3;

COMMENT ON TABLE GALADM.ENGINE_MANIFEST_HIST_TBX IS 'ENGINE MANIFEST HISTORY RECORD';

CREATE UNIQUE INDEX GALADM.ENGINE_MANIFEST_HIST_I1 on GALADM.ENGINE_MANIFEST_HIST_TBX
        (ENGINE_NO, COMPANY, PLANT, DEPARTMENT, LINE, PROCESS, ACTUAL_TIMESTAMP) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.ENGINE_MANIFEST_HIST_TBX ADD CONSTRAINT ENGINE_MANIFEST_HIST_PK Primary Key
        (ENGINE_NO, COMPANY, PLANT, DEPARTMENT, LINE, PROCESS, ACTUAL_TIMESTAMP);


CREATE TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ENGINE_MANIFEST_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.ENGINE_MANIFEST_HIST_TBX_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ENGINE_MANIFEST_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

