------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_THEME_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_THEME_TR1;
DROP TRIGGER GALADM.QI_THEME_TR2;
DROP TABLE GALADM.QI_THEME_TBX;

CREATE TABLE GALADM.QI_THEME_TBX
(
	THEME_NAME            VARCHAR(32) NOT NULL ,
	THEME_DESCRIPTION     VARCHAR(128),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_THEME_TBX IS 'NAQ Theme';

CREATE UNIQUE INDEX GALADM.QI_THEME_I1
  ON GALADM.QI_THEME_TBX (THEME_NAME);

ALTER TABLE GALADM.QI_THEME_TBX 
	ADD CONSTRAINT QI_THEME_PK PRIMARY KEY (THEME_NAME);
		
ALTER TABLE GALADM.QI_THEME_TBX 
	ADD CONSTRAINT QI_THEME_C1 CHECK 
		(THEME_NAME = UPPER(THEME_NAME));
		
ALTER TABLE GALADM.QI_THEME_TBX 
	ADD CONSTRAINT QI_THEME_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_THEME_TBX  
	ADD CONSTRAINT QI_THEME_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_THEME_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_THEME_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_THEME_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_THEME_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
    
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_THEME_GROUP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_THEME_GROUP_TR1;
DROP TRIGGER GALADM.QI_THEME_GROUP_TR2;
DROP TABLE GALADM.QI_THEME_GROUP_TBX;

CREATE TABLE GALADM.QI_THEME_GROUP_TBX
(
	THEME_GROUP_NAME      VARCHAR(32) NOT NULL ,
	THEME_GROUP_DESCRIPTION  VARCHAR(128),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_THEME_GROUP_TBX IS 'NAQ Theme Group';

CREATE UNIQUE INDEX GALADM.QI_THEME_GROUP_I1
  ON GALADM.QI_THEME_GROUP_TBX (THEME_GROUP_NAME);

ALTER TABLE GALADM.QI_THEME_GROUP_TBX 
	ADD CONSTRAINT QI_THEME_GROUP_PK PRIMARY KEY (THEME_GROUP_NAME);
		
ALTER TABLE GALADM.QI_THEME_GROUP_TBX 
	ADD CONSTRAINT QI_THEME_GROUP_C1 CHECK 
		(THEME_GROUP_NAME = UPPER(THEME_GROUP_NAME));
		
ALTER TABLE GALADM.QI_THEME_GROUP_TBX 
	ADD CONSTRAINT QI_THEME_GROUP_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_THEME_GROUP_TBX  
	ADD CONSTRAINT QI_THEME_GROUP_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_THEME_GROUP_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_THEME_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_THEME_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_THEME_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_THEME_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
    
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_THEME_GROUPING_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_THEME_GROUPING_TR1;
DROP TRIGGER GALADM.QI_THEME_GROUPING_TR2;
DROP TABLE GALADM.QI_THEME_GROUPING_TBX;

CREATE TABLE GALADM.QI_THEME_GROUPING_TBX
(
	THEME_GROUP_NAME      VARCHAR(32) NOT NULL ,
	THEME_NAME            VARCHAR(32) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_THEME_GROUPING_TBX IS 'NAQ Theme Grouping';

CREATE UNIQUE INDEX GALADM.QI_THEME_GROUPING_I1
  ON GALADM.QI_THEME_GROUPING_TBX (THEME_GROUP_NAME, THEME_NAME);

ALTER TABLE GALADM.QI_THEME_GROUPING_TBX 
	ADD CONSTRAINT QI_THEME_GROUPING_PK PRIMARY KEY (THEME_GROUP_NAME, THEME_NAME);
		
ALTER TABLE GALADM.QI_THEME_GROUPING_TBX 
	ADD CONSTRAINT QI_THEME_GROUPING_C1 CHECK 
		(THEME_GROUP_NAME = UPPER(THEME_GROUP_NAME));
		
ALTER TABLE GALADM.QI_THEME_GROUPING_TBX 
	ADD CONSTRAINT QI_THEME_GROUPING_C2 CHECK 
		(THEME_NAME = UPPER(THEME_NAME));		
		
ALTER TABLE GALADM.QI_THEME_GROUPING_TBX 
	ADD CONSTRAINT QI_THEME_GROUPING_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_THEME_GROUPING_TBX  
	ADD CONSTRAINT QI_THEME_GROUPING_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_THEME_GROUPING_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_THEME_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_THEME_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_THEME_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_THEME_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IQS_VERSION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_IQS_VERSION_TR1;
DROP TRIGGER GALADM.QI_IQS_VERSION_TR2;
DROP TABLE GALADM.QI_IQS_VERSION_TBX;

CREATE TABLE GALADM.QI_IQS_VERSION_TBX
(
	IQS_VERSION           CHAR(16) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_IQS_VERSION_TBX IS 'NAQ IQS Version';

CREATE UNIQUE INDEX GALADM.QI_IQS_VERSION_I1
  ON GALADM.QI_IQS_VERSION_TBX (IQS_VERSION);

ALTER TABLE GALADM.QI_IQS_VERSION_TBX 
	ADD CONSTRAINT QI_IQS_VERSION_PK PRIMARY KEY (IQS_VERSION);
		
ALTER TABLE GALADM.QI_IQS_VERSION_TBX 
	ADD CONSTRAINT QI_IQS_VERSION_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_IQS_VERSION_TBX  
	ADD CONSTRAINT QI_IQS_VERSION_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IQS_VERSION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IQS_VERSION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IQS_VERSION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IQS_VERSION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IQS_VERSION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IQS_CATEGORY_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_IQS_CATEGORY_TR1;
DROP TRIGGER GALADM.QI_IQS_CATEGORY_TR2;
DROP TABLE GALADM.QI_IQS_CATEGORY_TBX;

CREATE TABLE GALADM.QI_IQS_CATEGORY_TBX
(
	IQS_CATEGORY          VARCHAR(32) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_IQS_CATEGORY_TBX IS 'NAQ IQS Category';

CREATE UNIQUE INDEX GALADM.QI_IQS_CATEGORY_I1
  ON GALADM.QI_IQS_CATEGORY_TBX (IQS_CATEGORY);

ALTER TABLE GALADM.QI_IQS_CATEGORY_TBX 
	ADD CONSTRAINT QI_IQS_CATEGORY_PK PRIMARY KEY (IQS_CATEGORY);
		
ALTER TABLE GALADM.QI_IQS_CATEGORY_TBX 
	ADD CONSTRAINT QI_IQS_CATEGORY_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_IQS_CATEGORY_TBX  
	ADD CONSTRAINT QI_IQS_CATEGORY_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IQS_CATEGORY_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IQS_CATEGORY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IQS_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IQS_CATEGORY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IQS_CATEGORY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IQS_QUESTION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_IQS_QUESTION_TR1;
DROP TRIGGER GALADM.QI_IQS_QUESTION_TR2;
DROP TABLE GALADM.QI_IQS_QUESTION_TBX;

CREATE TABLE GALADM.QI_IQS_QUESTION_TBX
(
	IQS_QUESTION_NO       INTEGER NOT NULL ,
	IQS_QUESTION          VARCHAR(256) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_IQS_QUESTION_TBX IS 'NAQ IQS Question';

CREATE UNIQUE INDEX GALADM.QI_IQS_QUESTION_I1
  ON GALADM.QI_IQS_QUESTION_TBX (IQS_QUESTION_NO);

ALTER TABLE GALADM.QI_IQS_QUESTION_TBX 
	ADD CONSTRAINT QI_IQS_QUESTION_PK PRIMARY KEY (IQS_QUESTION_NO);
		
ALTER TABLE GALADM.QI_IQS_QUESTION_TBX 
	ADD CONSTRAINT QI_IQS_QUESTION_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_IQS_QUESTION_TBX  
	ADD CONSTRAINT QI_IQS_QUESTION_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IQS_QUESTION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IQS_QUESTION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IQS_QUESTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IQS_QUESTION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IQS_QUESTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;  
    
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IQS_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_IQS_TR1;
DROP TRIGGER GALADM.QI_IQS_TR2;
DROP TABLE GALADM.QI_IQS_TBX;

CREATE TABLE GALADM.QI_IQS_TBX
(
	IQS_ID                INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,
	IQS_VERSION           CHAR(16) NOT NULL,
	IQS_CATEGORY          VARCHAR(32) NOT NULL,
	IQS_QUESTION_NO       INTEGER NOT NULL,
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_IQS_TBX IS 'NAQ IQS';

CREATE UNIQUE INDEX GALADM.QI_IQS_I1
  ON GALADM.QI_IQS_TBX (IQS_ID);

ALTER TABLE GALADM.QI_IQS_TBX 
	ADD CONSTRAINT QI_IQS_PK PRIMARY KEY (IQS_ID);
		
ALTER TABLE GALADM.QI_IQS_TBX 
	ADD CONSTRAINT QI_IQS_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_IQS_TBX  
	ADD CONSTRAINT QI_IQS_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IQS_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IQS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IQS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IQS_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;  
    