ALTER TABLE GALADM.GAL211TBX ADD COLUMN PROD_LINE_NO SMALLINT DEFAULT 1;

-- Update PROD_LINE_NO as needed.  Default is set to 1. For HMA Frame 2, PROD_LINE_NO = 2
-- UPDATE GALADM.GAL211TBX SET PROD_LINE_NO = 1;

ALTER TABLE GALADM.QI_PLANT_TBX ADD COLUMN ENTRY_SITE CHAR(16);
ALTER TABLE GALADM.QI_PLANT_TBX ADD COLUMN ENTRY_PLANT CHAR(16);
ALTER TABLE GALADM.QI_PLANT_TBX ADD COLUMN PROD_LINE_NO SMALLINT;





