
ALTER TABLE GALADM.MC_ORDER_STRUCTURE_TBX ADD COLUMN DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '';

ALTER TABLE GALADM.MC_ORDER_STRUCTURE_TBX DROP CONSTRAINT MC_ORDER_STRUCTURE_PK;

ALTER TABLE "GALADM"."MC_ORDER_STRUCTURE_TBX"
  ADD CONSTRAINT "MC_ORDER_STRUCTURE_PK" PRIMARY KEY
    ("ORDER_NO", "DIVISION_ID");
    
 
ALTER TABLE GALADM.MC_PRODUCT_STRUCTURE_TBX ADD COLUMN DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '';

ALTER TABLE GALADM.MC_PRODUCT_STRUCTURE_TBX DROP CONSTRAINT MC_PRODUCT_STRUCTURE_PK;

ALTER TABLE "GALADM"."MC_PRODUCT_STRUCTURE_TBX"
  ADD CONSTRAINT "MC_PRODUCT_STRUCTURE_PK" PRIMARY KEY
    ("PRODUCT_ID", "DIVISION_ID", "PRODUCT_SPEC_CODE");


ALTER TABLE GALADM.MC_STRUCTURE_TBX ADD COLUMN DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '';

ALTER TABLE GALADM.MC_STRUCTURE_TBX DROP CONSTRAINT MC_STRUCTURE_PK;

ALTER TABLE "GALADM"."MC_STRUCTURE_TBX"
  ADD CONSTRAINT "MC_STRUCTURE_PK" PRIMARY KEY
    ("PRODUCT_SPEC_CODE", "STRUCTURE_REV", "DIVISION_ID", "PROCESS_POINT_ID", "OPERATION_NAME", "OP_REV", "PDDA_PLATFORM_ID", "PART_ID", "PART_REV");
