SELECT MAX(EXTERNAL_SYSTEM_ID) FROM GALADM.QI_EXTERNAL_SYSTEM_INFO_TBX;

-- Add 1 to the result from above and replace the ### below

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_INFO_TBX 
  ALTER COLUMN EXTERNAL_SYSTEM_ID
  RESTART WITH ###;