FRAME_ENGINE_MODEL_MAP_TBX  Table

DROP TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR2;
DROP TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR1;
DROP TABLE GALADM.FRAME_ENGINE_MODEL_MAP_TBX;

CREATE TABLE GALADM.FRAME_ENGINE_MODEL_MAP_TBX (
	FRM_MODEL_YEAR_CODE char(1) NOT NULL,
	FRM_MODEL_CODE char(3) NOT NULL,
	FRM_MODEL_TYPE_CODE char(3) NOT NULL,
	FRM_MODEL_OPTION_CODE char(3) NOT NULL,
	ENG_MODEL_YEAR_CODE char(1) NOT NULL,
	ENG_MODEL_CODE char(3) NOT NULL,
	ENG_MODEL_TYPE_CODE char(3) NOT NULL,
	ENG_MODEL_OPTION_CODE char(3) NOT NULL,
	UPDT_USERID char(11), 
	CREATE_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATE_TIMESTAMP TIMESTAMP,
	
	CONSTRAINT FRAME_ENGINE_MODEL_MAP_TBX_PK PRIMARY KEY (
		FRM_MODEL_YEAR_CODE,
		FRM_MODEL_CODE,
		FRM_MODEL_TYPE_CODE,
		FRM_MODEL_OPTION_CODE,
		ENG_MODEL_YEAR_CODE,
		ENG_MODEL_CODE,
		ENG_MODEL_TYPE_CODE,
		ENG_MODEL_OPTION_CODE
	)
)

IN GALTBSDAT5
INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.FRAME_ENGINE_MODEL_MAP_TBX
	DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
	PCTFREE 0
	LOCKSIZE ROW
	APPEND OFF
	NOT VOLATILE;

COMMENT ON TABLE GALADM.FRAME_ENGINE_MODEL_MAP_TBX IS
	'Engine to frame models mapping.';

CREATE TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR1
	NO CASCADE BEFORE INSERT
	ON GALADM.FRAME_ENGINE_MODEL_MAP_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FRAME_ENGINE_MODEL_MAP_TBX_TR2
	NO CASCADE BEFORE UPDATE
	ON GALADM.FRAME_ENGINE_MODEL_MAP_TBX
	REFERENCING NEW AS A
	FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX
	GALADM.FRAME_ENGINE_MODEL_MAP_TBX_I1
 	ON GALADM.FRAME_ENGINE_MODEL_MAP_TBX (
		FRM_MODEL_YEAR_CODE ASC,
		FRM_MODEL_CODE ASC,
		FRM_MODEL_TYPE_CODE ASC,
		FRM_MODEL_OPTION_CODE ASC,
		ENG_MODEL_YEAR_CODE ASC,
		ENG_MODEL_CODE ASC,
		ENG_MODEL_TYPE_CODE ASC,
		ENG_MODEL_OPTION_CODE ASC
	)

ALLOW REVERSE SCANS
COMPRESS NO;
