DROP TRIGGER GALADM.SUB_PROD_DETAIL_T1;
DROP TRIGGER GALADM.SUB_PROD_DETAIL_T2;
DROP TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX;

CREATE TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX (
		KD_LOT_NUMBER CHAR(18) NOT NULL,
		SUB_ID CHAR(2) NOT NULL,
		PRODUCT_SEQ_NO SMALLINT NOT NULL DEFAULT 1,
		PRODUCT_ID CHAR(17),
		PRODUCTION_LOT CHAR(20),
		STATUS INTEGER DEFAULT 0,
		CONTAINER_ID CHAR(10),
		CREATE_TIMESTAMP TIMESTAMP,
		UPDATE_TIMESTAMP TIMESTAMP,
		CONSTRAINT SUB_PRODUCT_SHIPPING_DETAIL_PK PRIMARY KEY(
		KD_LOT_NUMBER,SUB_ID, PRODUCT_SEQ_NO)
	)
	DATA CAPTURE CHANGES;


CREATE TRIGGER GALADM.SUB_PROD_DETAIL_T1 
	BEFORE INSERT ON GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX
	REFERENCING  NEW AS A
	FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.SUB_PROD_DETAIL_T2 
	BEFORE UPDATE ON GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX
	REFERENCING  NEW AS A
	FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;