CREATE BUFFERPOOL "LETBPIDX1"  SIZE 9000 PAGESIZE 4096;

CREATE LARGE TABLESPACE "LETTBSIDX1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 20 M 
	 MAXSIZE 2 G 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL LETBPIDX1
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;
	
CREATE LARGE TABLESPACE "LETTBSDAT1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 20 M 
	 MAXSIZE 2 G 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL LETBP1
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

CREATE TABLE GALADM.GAL266TBX (
  TABLE_NAME	CHARACTER(16)	NOT NULL	DEFAULT '',
  COLUMN_NAME	CHARACTER(30)	NOT NULL	DEFAULT '',
  PREFIX	CHARACTER(8),
  START_ID	INTEGER,
  END_ID	INTEGER,
  CURRENT_ID	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL266_PK PRIMARY KEY
    (TABLE_NAME, COLUMN_NAME)
) 
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL266TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL266TBX IS 'RMT IdCreate for managing unique ids used in database columns';

CREATE TRIGGER GALADM.GAL266_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL266TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL266_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL266TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL700TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  SERIES_FRAME_NO	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  CONSTRAINT GAL700_PK PRIMARY KEY
    (PRODUCT_ID)
)
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL700TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL700TBX IS
   'RMT Product for LET';

CREATE TRIGGER GALADM.GAL700_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL700TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL700_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL700TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL700_I1
  ON GALADM.GAL700TBX
    ( SERIES_FRAME_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE TABLE GALADM.GAL701TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER		NOT NULL	DEFAULT 0,
  BUILD_CODE	CHARACTER(20),
  TEST_ID	CHARACTER(20),
  INSPECTION_MTO	CHARACTER(20),
  SEQ_STEP_FILE	VARCHAR(50),
  CONT_STEP_FILE	VARCHAR(50),
  SEQ_RANGE	CHARACTER(20),
  TOTAL_RESULT_STATUS	CHARACTER(1),
  START_TIMESTAMP	TIMESTAMP,
  END_TIMESTAMP	TIMESTAMP,
  LET_MFG_AREA_CODE	CHARACTER(1),
  LET_MFG_NO	CHARACTER(1),
  LET_LINE_NO	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  BASE_RELEASE	CHARACTER(19),
  PRODUCTION	CHARACTER(1),
  ADDITIONAL_DATA	CHARACTER(11),
  CONSTRAINT GAL701_PK PRIMARY KEY
    (PRODUCT_ID, TEST_SEQ)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL701TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL701TBX IS 'RMT LetResult for LET';

CREATE TRIGGER GALADM.GAL701_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL701TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL701_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL701TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL701_I1
  ON GALADM.GAL701TBX
    ( END_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL701_I2
  ON GALADM.GAL701TBX
    ( LET_LINE_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE TABLE GALADM.GAL702TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  ECU_NAME	VARCHAR(64)	NOT NULL	DEFAULT '',
  ECU_LOG	VARCHAR(10000) FOR BIT DATA,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL702_PK PRIMARY KEY
    (PRODUCT_ID, TEST_SEQ, ECU_NAME)
) 
  IN LETTBSDAT2
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL702TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL702TBX IS 'RMT LetLog for LET';

CREATE TRIGGER GALADM.GAL702_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL702TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL702_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL702TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL703TBX_01 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_01
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_01 IS 'RMT LetProgramResultOne for LET';

CREATE TRIGGER GALADM.GAL703_TR2_01
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_01
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_01
  ON GALADM.GAL703TBX_01
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_01
  ON GALADM.GAL703TBX_01
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_01
ADD CONSTRAINT GAL703_PK_01 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL703TBX_02 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_02
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_02 IS 'RMT LetProgramResultTwo for LET';

CREATE TRIGGER GALADM.GAL703_TR2_02
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_02
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_02
  ON GALADM.GAL703TBX_02
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_02
  ON GALADM.GAL703TBX_02
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_02
ADD CONSTRAINT GAL703_PK_02 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL703TBX_03 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_03
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_03 IS 'RMT LetProgramResultThree for LET';

CREATE TRIGGER GALADM.GAL703_TR2_03
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_03
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_03
  ON GALADM.GAL703TBX_03
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_03
  ON GALADM.GAL703TBX_03
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_03
ADD CONSTRAINT GAL703_PK_03 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL703TBX_04 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_04
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_04 IS 'RMT LetProgramResultFour for LET';

CREATE TRIGGER GALADM.GAL703_TR2_04
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_04
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_04
  ON GALADM.GAL703TBX_04
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_04
  ON GALADM.GAL703TBX_04
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_04
ADD CONSTRAINT GAL703_PK_04 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL703TBX_05 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_05
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_05 IS 'RMT LetProgramResultFive for LET';

CREATE TRIGGER GALADM.GAL703_TR2_05
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_05
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_05
  ON GALADM.GAL703TBX_05
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_05
  ON GALADM.GAL703TBX_05
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_05
ADD CONSTRAINT GAL703_PK_05 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL703TBX_06 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL703TBX_06
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL703TBX_06 IS 'RMT LetProgramResultSix for LET';

CREATE TRIGGER GALADM.GAL703_TR2_06
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_06
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL703_PK_06
  ON GALADM.GAL703TBX_06
    ( END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL703_I2_06
  ON GALADM.GAL703TBX_06
    ( PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
ALTER TABLE GALADM.GAL703TBX_06
ADD CONSTRAINT GAL703_PK_06 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID);
  
CREATE TABLE GALADM.GAL704TBX_01 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_01
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_01 IS 'RMT LetProgramValueOne for LET';

CREATE TRIGGER GALADM.GAL704_TR2_01
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_01
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_01
  ON GALADM.GAL704TBX_01
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_01
ADD CONSTRAINT GAL704_PK_01 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL704TBX_02 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_02
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_02 IS 'RMT LetProgramValueTwo for LET';

CREATE TRIGGER GALADM.GAL704_TR2_02
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_02
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_02
  ON GALADM.GAL704TBX_02
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_02
ADD CONSTRAINT GAL704_PK_02 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL704TBX_03 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_03
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_03 IS 'RMT LetProgramValueThree for LET';

CREATE TRIGGER GALADM.GAL704_TR2_03
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_03
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_03
  ON GALADM.GAL704TBX_03
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_03
ADD CONSTRAINT GAL704_PK_03 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL704TBX_04 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_04
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_04 IS 'RMT LetProgramValueFour for LET';

CREATE TRIGGER GALADM.GAL704_TR2_04
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_04
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_04
  ON GALADM.GAL704TBX_04
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_04
ADD CONSTRAINT GAL704_PK_04 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL704TBX_05 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_05
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_05 IS 'RMT LetProgramValueFive for LET';

CREATE TRIGGER GALADM.GAL704_TR2_05
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_05
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_05
  ON GALADM.GAL704TBX_05
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_05
ADD CONSTRAINT GAL704_PK_05 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL704TBX_06 (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT '',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
  
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL704TBX_06
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL704TBX_06 IS 'RMT LetProgramValueSix for LET';

CREATE TRIGGER GALADM.GAL704_TR2_06
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL704TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_06
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL704_PK_06
  ON GALADM.GAL704TBX_06
    (END_TIMESTAMP ASC, PRODUCT_ID ASC, TEST_SEQ ASC, INSPECTION_PGM_ID ASC, INSPECTION_PARAM_ID ASC, INSPECTION_PARAM_TYPE ASC)
  CLUSTER
  ALLOW REVERSE SCANS
  COMPRESS NO;

  
ALTER TABLE GALADM.GAL704TBX_06
ADD CONSTRAINT GAL704_PK_06 PRIMARY KEY
  (END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE);
  
CREATE TABLE GALADM.GAL709TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  HISTORY_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  USER_ID	CHARACTER(11),
  MODIFY_TIMESTAMP	TIMESTAMP,
  MODIFY_TYPE	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL709_PK PRIMARY KEY
    (PRODUCT_ID, HISTORY_SEQ)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL709TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL709TBX IS 'RMT LetModifyHistory for LET';

CREATE TRIGGER GALADM.GAL709_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL709TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL709_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL709TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL710TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  HISTORY_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  BUILD_CODE	CHARACTER(20),
  TEST_ID	CHARACTER(20),
  INSPECTION_MTO	CHARACTER(20),
  SEQ_STEP_FILE	VARCHAR(50),
  CONT_STEP_FILE	VARCHAR(50),
  SEQ_RANGE	CHARACTER(20),
  TOTAL_RESULT_STATUS	CHARACTER(1),
  START_TIMESTAMP	TIMESTAMP,
  END_TIMESTAMP	TIMESTAMP,
  LET_MFG_AREA_CODE	CHARACTER(1),
  LET_MFG_NO	CHARACTER(1),
  LET_LINE_NO	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  BASE_RELEASE	CHARACTER(19),
  PRODUCTION	CHARACTER(1),
  ADDITIONAL_DATA	CHARACTER(11),
  CONSTRAINT GAL710_PK PRIMARY KEY
    (PRODUCT_ID, HISTORY_SEQ, TEST_SEQ)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL710TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL710TBX IS 'RMT LetResultHistory for LET';

CREATE TRIGGER GALADM.GAL710_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL710TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL710_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL710TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL711TBX (
PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  HISTORY_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  ECU_NAME	VARCHAR(64)	NOT NULL	DEFAULT '',
  ECU_LOG	VARCHAR(10000) FOR BIT DATA,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL711_PK PRIMARY KEY
    (PRODUCT_ID, HISTORY_SEQ, TEST_SEQ, ECU_NAME)
) 
  IN LETTBSDAT2
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL711TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL711TBX IS 'RMT LetLogHistory for LET';

CREATE TRIGGER GALADM.GAL711_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL711TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL711_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL711TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL712TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  HISTORY_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_STATUS	CHARACTER(1),
  PROCESS_STEP	CHARACTER(9),
  PROCESS_STATUS	CHARACTER(1),
  PROCESS_START_TIMESTAMP	TIMESTAMP,
  PROCESS_END_TIMESTAMP	TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3),
  LET_RESULT_CAL	CHARACTER(16),
  LET_RESULT_DCREV	CHARACTER(16),
  SOFTWARE_VERSION	VARCHAR(32),
  LET_OPERATOR_ID	CHARACTER(16),
  IN_CYCLE_RETEST_NUM	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL712_PK PRIMARY KEY
    (PRODUCT_ID, HISTORY_SEQ, TEST_SEQ, INSPECTION_PGM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL712TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL712TBX IS 'RMT LetProgramResultHistory for LET';

CREATE TRIGGER GALADM.GAL712_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL712TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL712_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL712TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL713TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  HISTORY_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  TEST_SEQ	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  INSPECTION_PARAM_VALUE	VARCHAR(32),
  INSPECTION_PARAM_UNIT	CHARACTER(10),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL713_PK PRIMARY KEY
    (PRODUCT_ID, HISTORY_SEQ, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID, INSPECTION_PARAM_TYPE)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL713TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL713TBX IS 'RMT LetProgramResultValueHistory for LET';

CREATE TRIGGER GALADM.GAL713_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL713TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL713_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL713TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL714TBX (
  INSPECTION_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PGM_NAME	VARCHAR(75),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL714_PK PRIMARY KEY
    (INSPECTION_PGM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL714TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL714TBX IS 'RMT LetInspectionProgram for LET';

CREATE TRIGGER GALADM.GAL714_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL714TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL714_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL714TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL714_I1
  ON GALADM.GAL714TBX
    ( INSPECTION_PGM_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE TABLE GALADM.GAL715TBX (
  INSPECTION_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  INSPECTION_PARAM_NAME	VARCHAR(300),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL715_PK PRIMARY KEY
    (INSPECTION_PARAM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL715TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL715TBX IS 'RMT LetInspectionParam for LET';

CREATE TRIGGER GALADM.GAL715_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL715TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL715_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL715TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL715_I1
  ON GALADM.GAL715TBX
    ( INSPECTION_PARAM_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE TABLE GALADM.GAL716TBX (
  MODEL_YEAR_CODE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  MODEL_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  MODEL_TYPE_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  MODEL_OPTION_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  EFFECTIVE_TIME	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  EXPIRATION_TIME	TIMESTAMP,
  CONDITION_WEIGHT	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL716_PK PRIMARY KEY
    (MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EFFECTIVE_TIME)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL716TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL716TBX IS 'RMT LetPassCriteriaMTO for LET';

CREATE TRIGGER GALADM.GAL716_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL716TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL716_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL716TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL717TBX (
  MODEL_YEAR_CODE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  MODEL_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  MODEL_TYPE_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  MODEL_OPTION_CODE	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  EFFECTIVE_TIME	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  CRITERIA_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  INSPECTION_DEVICE_TYPE	CHARACTER(1),
  CRITERIA_PGM_ATTRIBUTE	CHARACTER(1),
  CONSTRAINT GAL717_PK PRIMARY KEY
    (MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EFFECTIVE_TIME, CRITERIA_PGM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL717TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL717TBX IS 'RMT LetPassCriteria for LET';

CREATE TRIGGER GALADM.GAL717_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL717TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL717_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL717TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL718TBX (
  CRITERIA_PGM_ID	INTEGER	NOT NULL	DEFAULT 0,
  CRITERIA_PGM_NAME	VARCHAR(75),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  INSPECTION_DEVICE_TYPE	CHARACTER(1),
  CRITERIA_PGM_ATTRIBUTE	CHARACTER(1),
  CONSTRAINT GAL718_PK PRIMARY KEY
    (CRITERIA_PGM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL718TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL718TBX IS 'RMT LetPassCriteriaProgram for LET';

CREATE TRIGGER GALADM.GAL718_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL718TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL718_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL718TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL723TBX (
  TABLE_NAME	CHARACTER(16)	NOT NULL	DEFAULT '',
  PHYSICAL_TABLE_OFFSET	INTEGER	NOT NULL	DEFAULT 0,
  PHYSICAL_TABLE_NAME	CHARACTER(16),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL723_PK PRIMARY KEY
    (TABLE_NAME, PHYSICAL_TABLE_OFFSET)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL723TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL723TBX IS 'RMT PhysicalTablePartitionSetting for LET';

CREATE TRIGGER GALADM.GAL723_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL723TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL723_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL723TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL724TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  TABLE_NAME	CHARACTER(16)	NOT NULL	DEFAULT '',
  PHYSICAL_TABLE_NAME	CHARACTER(16),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL724_PK PRIMARY KEY
    (PRODUCT_ID, TABLE_NAME)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL724TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL724TBX IS 'RMT PhysicalTableMap for LET';

CREATE TRIGGER GALADM.GAL724_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL724TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL724_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL724TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL725TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT ' ',
  ACTUAL_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  PASS_STATUS	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL725_PK PRIMARY KEY
    (PRODUCT_ID, ACTUAL_TIMESTAMP)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL725TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL725TBX IS 'RMT LetResult for LET';

CREATE TRIGGER GALADM.GAL725_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL725TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL725_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL725TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL726TBX (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  TOTAL_RESULT_STATUS	CHARACTER(1),
  BASE_RELEASE	CHARACTER(19),
  SOFTWARE_VERSION	VARCHAR(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL726_PK PRIMARY KEY
    (END_TIMESTAMP, LET_TERMINAL_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL726TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL726TBX IS 'RMT LetDiagResult for LET';

CREATE TRIGGER GALADM.GAL726_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL726TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL726_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL726TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL727TBX (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  DIAG_TEST_ID	INTEGER	NOT NULL	DEFAULT 0,
  DIAG_TEST_STATUS	CHARACTER(1),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL727_PK PRIMARY KEY
    (END_TIMESTAMP, LET_TERMINAL_ID, DIAG_TEST_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL727TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL727TBX IS 'RMT LetDiagDetail for LET';

CREATE TRIGGER GALADM.GAL727_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL727TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL727_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL727TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL728TBX (
  END_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT TIMESTAMP,
  LET_TERMINAL_ID	CHARACTER(3)	NOT NULL	DEFAULT ' ',
  DIAG_TEST_ID	INTEGER	NOT NULL	DEFAULT 0,
  FAULT_CODE_ID	INTEGER	NOT NULL	DEFAULT 0,
  SHORT_DESC_ID	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL728_PK PRIMARY KEY
    (END_TIMESTAMP, LET_TERMINAL_ID, DIAG_TEST_ID, FAULT_CODE_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL728TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL728TBX IS 'RMT DiagFaultDetail for LET';

CREATE TRIGGER GALADM.GAL728_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL728TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL728_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL728TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL729TBX (
  DIAG_PARAM_ID	INTEGER	NOT NULL	DEFAULT 0,
  DIAG_PARAM_TYPE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  DIAG_PARAM_VALUE	VARCHAR(75),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL729_PK PRIMARY KEY
    (DIAG_PARAM_ID)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL729TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL729TBX IS 'RMT LetDiagName for LET';

CREATE TRIGGER GALADM.GAL729_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL729TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL729_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL729TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.GAL730TBX (
  INSPECTION_DEVICE_TYPE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  CRITERIA_PGM_ATTRIBUTE	CHARACTER(1)	NOT NULL	DEFAULT ' ',
  PGM_CATEGORY_NAME	CHARACTER(15),
  BG_COLOR	CHARACTER(7),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL730_PK PRIMARY KEY
    (INSPECTION_DEVICE_TYPE, CRITERIA_PGM_ATTRIBUTE)
) 
  IN LETTBSDAT1
  INDEX IN LETTBSIDX1;

ALTER TABLE GALADM.GAL730TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL730TBX IS 'RMT LetProgramCategory for LET';

CREATE TRIGGER GALADM.GAL730_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL730TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL730_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL730TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE VIEW GALADM.GAL704TBXV      ( END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PARAM_ID,      INSPECTION_PARAM_TYPE, INSPECTION_PARAM_VALUE, INSPECTION_PARAM_UNIT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP )  AS      
  select *         
  from GALADM.GAL704TBX_01         
  UNION ALL         
  select *         
  from GALADM.GAL704TBX_02     
  UNION ALL         
  select *         
  from GALADM.GAL704TBX_03         
  UNION ALL     
  select *         
  from GALADM.GAL704TBX_04         
  UNION ALL         
  select *     
  from GALADM.GAL704TBX_05     
  UNION ALL         
  select *         
  from GALADM.GAL704TBX_06     
  WITH NO ROW MOVEMENT;

COMMENT ON TABLE "GALADM"."GAL704TBXV" IS 'Union All of All Six 704TBX tables';

CREATE VIEW GALADM.GAL703TBXV      ( END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PGM_STATUS,      PROCESS_STEP, PROCESS_STATUS, PROCESS_START_TIMESTAMP, PROCESS_END_TIMESTAMP, LET_TERMINAL_ID,      LET_RESULT_CAL, LET_RESULT_DCREV, SOFTWARE_VERSION, LET_OPERATOR_ID, IN_CYCLE_RETEST_NUM, CREATE_TIMESTAMP, UPDATE_TIMESTAMP )  AS      
  select *         
  from GALADM.GAL703TBX_01     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_02         
  UNION ALL     
  select *         
  from GALADM.GAL703TBX_03         
  UNION ALL         
  select *     
  from GALADM.GAL703TBX_04     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_05     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_06      
  WITH NO ROW MOVEMENT;

COMMENT ON TABLE "GALADM"."GAL703TBXV" IS 'Union ALL of All Six 703TBX Tables';