ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX DROP COLUMN PRODUCT_KIND;
ALTER TABLE GALADM.QI_REPAIR_METHOD_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_METHOD_TBX;
