DROP TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR2;
DROP TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR1;
DROP TABLE GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX;

CREATE TABLE GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX (
   PRODUCT_ID 			CHARACTER(17) 	NOT NULL DEFAULT '',
   PLANT_LOC_CODE		CHARACTER(1),
   DEPT_CODE			CHARACTER(2),
   MODEL_YEAR_DATE		DECIMAL(5, 1),
   PROD_SCH_QTY			DECIMAL(5, 1),
   PROD_ASM_LINE_NO		CHARACTER(1),
   VEHICLE_MODEL_CODE	CHARACTER(1),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PRODUCT_PDDA_PLATFORM_PK PRIMARY KEY 
     (PRODUCT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX IS 'RMT MC_PRODUCT_PDDA_PLATFORM is used by Manufacturing Control to link PDDA Plant Loc Code, Dept Code, Model Year Date, Prod Sch Qty, Prod ASM Line No, Vehicle Model Code to GALC PRODUCT ID';
    
CREATE TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PRODUCT_PDDA_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PRODUCT_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
