create  table GALADM.MC_VIOS_MASTER_OP_PART_PROC_TEMP (
	"VIOS_PLATFORM_ID" CHARACTER(17) NOT NULL ,
	"UNIT_NO" VARCHAR(6) NOT NULL ,
	"PART_NO" CHARACTER(18) NOT NULL ,
	"PART_TYPE" VARCHAR(32) NOT NULL ,
	"PART_MASK" VARCHAR(255) ,
	"PART_CHECK" INTEGER ,
	"PART_DESC" VARCHAR(255), 
	"PART_MARK" VARCHAR(32), 
	"MEASUREMENT_COUNT" INTEGER )
IN "GALTBSREF12" INDEX IN "GALTBSIDX4";

insert into GALADM.MC_VIOS_MASTER_OP_PART_PROC_TEMP(VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_TYPE, PART_MASK, PART_CHECK, PART_DESC, PART_MARK, MEASUREMENT_COUNT) SELECT P.VIOS_PLATFORM_ID, P.UNIT_NO, P.PART_NO, P.PART_TYPE, MAX(P.PART_MASK), MAX(P.PART_CHECK), MAX(P.PART_DESC), MAX(P.PART_MARK), MAX(P.MEASUREMENT_COUNT) FROM GALADM.MC_VIOS_MASTER_OP_PART_TBX P GROUP BY P.VIOS_PLATFORM_ID, P.UNIT_NO, P.PART_NO, P.PART_TYPE;

delete from (select * from GALADM.MC_VIOS_MASTER_OP_PART_TBX fetch first 10000 rows only);

insert into GALADM.MC_VIOS_MASTER_OP_PART_TBX(VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, PART_TYPE, PART_MASK, PART_CHECK, PART_DESC, PART_MARK, MEASUREMENT_COUNT) select VIOS_PLATFORM_ID, UNIT_NO, PART_NO, '', '', PART_TYPE, PART_MASK, PART_CHECK, PART_DESC, PART_MARK, MEASUREMENT_COUNT from GALADM.MC_VIOS_MASTER_OP_PART_PROC_TEMP;

drop table GALADM.MC_VIOS_MASTER_OP_PART_PROC_TEMP;

alter table GALADM.MC_VIOS_MASTER_OP_PART_TBX drop PRIMARY KEY;

drop index GALADM.MC_VIOS_MASTER_OP_PART_I1;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_PART_I1 ON GALADM.MC_VIOS_MASTER_OP_PART_TBX ("VIOS_PLATFORM_ID" ASC, "UNIT_NO" ASC, "PART_NO" ASC,  "PART_TYPE" ASC) INCLUDE ("CREATE_TIMESTAMP" , "UPDATE_TIMESTAMP" );

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX ADD CONSTRAINT MC_VIOS_MASTER_OP_PART_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_TYPE);

alter table GALADM.MC_VIOS_MASTER_OP_PART_TBX drop column PART_SECTION_CODE;

alter table GALADM.MC_VIOS_MASTER_OP_PART_TBX drop column PART_ITEM_NO;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 

reorg table GALADM.MC_VIOS_MASTER_OP_PART_TBX;