
INSERT INTO GALADM.QI_STATION_CONFIG_TBX 
	(SELECT DISTINCT COMPONENT_ID,'GDP Process Point','Yes',1,null,null,'NAQICS-1430',null FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'GLOBAL_DIRECT_PASS' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'
		AND COMPONENT_ID IN (SELECT COMPONENT_ID FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'IS_NAQ_STATION' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'));

INSERT INTO GALADM.QI_STATION_CONFIG_TBX 
	(SELECT DISTINCT COMPONENT_ID,'TRPU Process Point','Yes',1,null,null,'NAQICS-1430',null FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'TRPU_PROCESS_POINT' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'
		AND COMPONENT_ID IN (SELECT COMPONENT_ID FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'IS_NAQ_STATION' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'));



DELETE FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'GLOBAL_DIRECT_PASS' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'
	AND COMPONENT_ID IN (SELECT COMPONENT_ID FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'IS_NAQ_STATION' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE');

DELETE FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'TRPU_PROCESS_POINT' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE'
	AND COMPONENT_ID IN (SELECT COMPONENT_ID FROM GALADM.GAL489TBX WHERE PROPERTY_KEY = 'IS_NAQ_STATION' AND UPPER(TRIM(PROPERTY_VALUE)) = 'TRUE');
