CREATE TABLE GALADM.OIF_SCHED_LMGR
(
   LEASENAME VARCHAR(254) NOT NULL,
   LEASEOWNER VARCHAR(254) NOT NULL,
   LEASE_EXPIRE_TIME BIGINT,
   DISABLED VARCHAR(5)
) 
IN GALTBSREF11 INDEX IN GALTBSIDX1;

CREATE TABLE GALADM.OIF_SCHED_LMPR
(
   LEASENAME VARCHAR(254) NOT NULL,
   NAME VARCHAR(254) NOT NULL,
   VALUE VARCHAR(254) NOT NULL
) 
IN GALTBSREF11 INDEX IN GALTBSIDX1;
		 
CREATE INDEX GALADM.OIF_SCHED_LMPR_IDX1 ON GALADM.OIF_SCHED_LMPR
(
  LEASENAME ASC,
  NAME ASC
)		
ALLOW REVERSE SCANS;

CREATE TABLE GALADM.OIF_SCHED_TASK
(
   TASKID BIGINT PRIMARY KEY NOT NULL,
   VERSION VARCHAR(5) NOT NULL,
   ROW_VERSION INT NOT NULL,
   TASKTYPE INT NOT NULL,
   TASKSUSPENDED SMALLINT NOT NULL,
   CANCELLED SMALLINT NOT NULL,
   NEXTFIRETIME BIGINT NOT NULL,
   STARTBYINTERVAL VARCHAR(254),
   STARTBYTIME BIGINT,
   VALIDFROMTIME BIGINT,
   VALIDTOTIME BIGINT,
   REPEATINTERVAL VARCHAR(254),
   MAXREPEATS INT NOT NULL,
   REPEATSLEFT INT NOT NULL,
   TASKINFO blob(102400),
   NAME VARCHAR(254) NOT NULL,
   AUTOPURGE INT NOT NULL,
   FAILUREACTION INT,
   MAXATTEMPTS INT,
   QOS INT,
   PARTITIONID INT,
   OWNERTOKEN VARCHAR(200) NOT NULL,
   CREATETIME BIGINT NOT NULL
) 
IN GALTBSREF11 INDEX IN GALTBSIDX1;

CREATE UNIQUE INDEX GALADM.OIF_SCHED_TASKI1 ON GALADM.OIF_SCHED_TASK(TASKID ASC)
	ALLOW REVERSE SCANS;

ALTER TABLE GALADM.OIF_SCHED_TASK 
	ADD CONSTRAINT OIF_SCHED_TASK_PK PRIMARY KEY
		(TASKID);

CREATE INDEX GALADM.OIF_SCHED_TASK_IDX2 ON GALADM.OIF_SCHED_TASK
(
  TASKID ASC,
  OWNERTOKEN ASC
) 
ALLOW REVERSE SCANS;

CREATE INDEX GALADM.OIF_SCHED_TASK_IDX3 ON GALADM.OIF_SCHED_TASK
(
  NEXTFIRETIME ASC,
  REPEATSLEFT ASC,
  PARTITIONID ASC
) 
ALLOW REVERSE SCANS;

CREATE TABLE GALADM.OIF_SCHED_TREG
(
   REGKEY VARCHAR(254) NOT NULL,
   REGVALUE VARCHAR(254)
) 
IN GALTBSREF11 INDEX IN GALTBSIDX1;
