------------------------------------------------
-- DDL Statements for Table "GALADM  "."MODEL_GROUP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.MODEL_GROUP_TR1;
DROP TRIGGER GALADM.MODEL_GROUP_TR2;
DROP TABLE GALADM.MODEL_GROUP_TBX;

CREATE TABLE GALADM.MODEL_GROUP_TBX
(
	MODEL_GROUP           VARCHAR(32) NOT NULL ,
	SYSTEM				  CHAR(18) NOT NULL,
	MODEL_GROUP_DESCRIPTION  VARCHAR(32),
	PRODUCT_TYPE          CHAR(10),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.MODEL_GROUP_TBX IS 'MTC Model Group';

CREATE UNIQUE INDEX GALADM.MODEL_GROUP_I1
  ON GALADM.MODEL_GROUP_TBX (MODEL_GROUP, SYSTEM);

ALTER TABLE GALADM.MODEL_GROUP_TBX 
	ADD CONSTRAINT MODEL_GROUP_PK PRIMARY KEY (MODEL_GROUP, SYSTEM);
	
ALTER TABLE GALADM.MODEL_GROUP_TBX 
	ADD CONSTRAINT MODEL_GROUP_C1 CHECK 
		(MODEL_GROUP = UPPER(MODEL_GROUP));	
		
ALTER TABLE GALADM.MODEL_GROUP_TBX 
	ADD CONSTRAINT MODEL_GROUP_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.MODEL_GROUP_TBX  
	ADD CONSTRAINT MODEL_GROUP_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.MODEL_GROUP_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.MODEL_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MODEL_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MODEL_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MODEL_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."MODEL_GROUPING_TBX"
------------------------------------------------

DROP TRIGGER GALADM.MODEL_GROUPING_TR1;
DROP TRIGGER GALADM.MODEL_GROUPING_TR2;
DROP TABLE GALADM.MODEL_GROUPING_TBX;

CREATE TABLE GALADM.MODEL_GROUPING_TBX
(
	MODEL_GROUP           VARCHAR(32) NOT NULL ,
	MTC_MODEL             CHAR(4) NOT NULL ,
	SYSTEM				  CHAR(18) NOT NULL ,	
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.MODEL_GROUPING_TBX IS 'MTC Model Grouping';

CREATE UNIQUE INDEX GALADM.MODEL_GROUPING_I1
  ON GALADM.MODEL_GROUPING_TBX (MODEL_GROUP, MTC_MODEL, SYSTEM);

ALTER TABLE GALADM.MODEL_GROUPING_TBX 
	ADD CONSTRAINT MODEL_GROUPING_PK PRIMARY KEY (MODEL_GROUP, MTC_MODEL, SYSTEM);
	
ALTER TABLE GALADM.MODEL_GROUPING_TBX 
	ADD CONSTRAINT MODEL_GROUPING_C1 CHECK 
		(MODEL_GROUP = UPPER(MODEL_GROUP));	
		
ALTER TABLE GALADM.MODEL_GROUPING_TBX 
	ADD CONSTRAINT MODEL_GROUPING_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.MODEL_GROUPING_TBX  
	ADD CONSTRAINT MODEL_GROUPING_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.MODEL_GROUPING_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.MODEL_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MODEL_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;  