DROP TRIGGER GALADM.CODE_TR2;
DROP TRIGGER GALADM.CODE_TR1;
DROP TABLE GALADM.CODE_TBX;

CREATE TABLE GALADM.CODE_TBX (
   CODE_TYPE VARCHAR (32) NOT NULL,
   CODE VARCHAR (64) NOT NULL,
   CODE_DESCRIPTION VARCHAR (80),
   DIVISION_ID VARCHAR (16),
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT GAL215_PK PRIMARY KEY
    (CODE_TYPE, CODE)
)
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

COMMENT ON TABLE GALADM.CODE_TBX IS 'RMT Code';


CREATE TRIGGER GALADM.CODE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.CODE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
