------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_RESPONSIBILITY_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_RESPONSIBILITY_TR1;
DROP TRIGGER GALADM.QI_STATION_RESPONSIBILITY_TR2;
DROP TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX;

CREATE TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX
(
	PROCESS_POINT_ID      CHARACTER(16) NOT NULL ,
	RESPONSIBLE_LEVEL_ID  INTEGER NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX IS 'NAQ Responsibility Configuration by Station';

CREATE UNIQUE INDEX GALADM.QI_STATION_RESPONSIBILITY_I1
  ON GALADM.QI_STATION_RESPONSIBILITY_TBX (PROCESS_POINT_ID, RESPONSIBLE_LEVEL_ID);

ALTER TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX 
	ADD CONSTRAINT QI_STATION_RESPONSIBILITY_PK PRIMARY KEY (PROCESS_POINT_ID, RESPONSIBLE_LEVEL_ID);
	
ALTER TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX 
	ADD CONSTRAINT QI_STATION_RESPONSIBILITY_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX  
	ADD CONSTRAINT QI_STATION_RESPONSIBILITY_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_STATION_RESPONSIBILITY_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_RESPONSIBILITY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_RESPONSIBILITY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_RESPONSIBILITY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;