--http://hmaapp58:8080/go?page=ReviewDisplay&reviewid=647
DROP TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR2;
DROP TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR1;
DROP TABLE GALADM.DEFECT_ACTUAL_PROBLEM_TBX;

CREATE TABLE GALADM.DEFECT_ACTUAL_PROBLEM_TBX (
  MODEL_CODE		CHARACTER(3)	NOT NULL,
  DEFECT_TYPE_NAME	VARCHAR(45)	NOT NULL,
  INSPECTION_PART_NAME	VARCHAR(32)	NOT NULL,
  SECONDARY_PART_NAME	VARCHAR(20)	NOT NULL,
  ACTUAL_PROBLEM_NAME	VARCHAR(64)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT DEFECT_ACTUAL_PROBLEM_PK PRIMARY KEY
     (MODEL_CODE,DEFECT_TYPE_NAME,INSPECTION_PART_NAME,SECONDARY_PART_NAME,ACTUAL_PROBLEM_NAME)
) 
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.DEFECT_ACTUAL_PROBLEM_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.DEFECT_ACTUAL_PROBLEM_TBX IS
   'RMT DefectActualProblem used by QICS';

CREATE TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.DEFECT_ACTUAL_PROBLEM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.DEFECT_ACTUAL_PROBLEM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.DEFECT_ACTUAL_PROBLEM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR2;
DROP TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR1;
DROP TABLE GALADM.DEFECT_REPAIR_METHOD_TBX;

CREATE TABLE GALADM.DEFECT_REPAIR_METHOD_TBX (
  MODEL_CODE		CHARACTER(3)	NOT NULL,
  DEFECT_TYPE_NAME	VARCHAR(45)	NOT NULL,
  INSPECTION_PART_NAME	VARCHAR(32)	NOT NULL,
  SECONDARY_PART_NAME	VARCHAR(20)	NOT NULL,
  REPAIR_METHOD_NAME	VARCHAR(64)	NOT NULL,
  REPAIR_TIME		INTEGER	DEFAULT 0,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT DEFECT_REPAIR_METHOD_PK PRIMARY KEY
     (MODEL_CODE,DEFECT_TYPE_NAME,INSPECTION_PART_NAME,SECONDARY_PART_NAME,REPAIR_METHOD_NAME)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.DEFECT_REPAIR_METHOD_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.DEFECT_REPAIR_METHOD_TBX IS 'RMT DefectRepairMethod used by QICS';

CREATE TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.DEFECT_REPAIR_METHOD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.DEFECT_REPAIR_METHOD_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.DEFECT_REPAIR_METHOD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
