    
------------------------------------------------
-- DDL Statements for Table "GALADM  "."REGIONAL_CODE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.REGIONAL_CODE_TR1;
DROP TRIGGER GALADM.REGIONAL_CODE_TR2;
DROP TABLE GALADM.REGIONAL_CODE_TBX;

CREATE TABLE GALADM.REGIONAL_CODE_TBX
(
	REGIONAL_CODE_NAME	  VARCHAR(256) NOT NULL,
	REGIONAL_VALUE        VARCHAR(256) NOT NULL,
	REGIONAL_VALUE_NAME	  VARCHAR(128),
	REGIONAL_VALUE_ABBR	  VARCHAR(64),
	REGIONAL_VALUE_DESC	  VARCHAR(256),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.REGIONAL_CODE_TBX IS 'REGIONAL CODE';

CREATE UNIQUE INDEX GALADM.REGIONAL_CODE_I1
  ON GALADM.REGIONAL_CODE_TBX (REGIONAL_CODE_NAME, REGIONAL_VALUE);

ALTER TABLE GALADM.REGIONAL_CODE_TBX 
	ADD CONSTRAINT REGIONAL_CODE_PK PRIMARY KEY (REGIONAL_CODE_NAME, REGIONAL_VALUE);
		
ALTER TABLE GALADM.REGIONAL_CODE_TBX 
	ADD CONSTRAINT REGIONAL_CODE_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.REGIONAL_CODE_TBX  
	ADD CONSTRAINT REGIONAL_CODE_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.REGIONAL_CODE_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.REGIONAL_CODE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.REGIONAL_CODE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.REGIONAL_CODE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.REGIONAL_CODE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
      
------------------------------------------------
-- DDL Statements for Table "GALADM  "."REGIONAL_PROCESS_POINT_GROUP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR1;
DROP TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR2;
DROP TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX;

CREATE TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX
(
	IS_REGIONAL			  SMALLINT DEFAULT 1 NOT NULL,
	SITE	             CHAR(16) NOT NULL,
	PROCESS_POINT_GROUP_NAME	VARCHAR(256) NOT NULL,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX IS 'REGIONAL PROCESS POINT GROUP';

CREATE UNIQUE INDEX GALADM.REGIONAL_PROCESS_POINT_GROUP_I1
  ON GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX (IS_REGIONAL, SITE, PROCESS_POINT_GROUP_NAME);

ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT REGIONAL_PROCESS_POINT_GROUP_PK PRIMARY KEY (IS_REGIONAL, SITE, PROCESS_POINT_GROUP_NAME);
		
ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT REGIONAL_PROCESS_POINT_GROUP_C1 CHECK 
		(SITE = UPPER(SITE));
		
ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT REGIONAL_PROCESS_POINT_GROUP_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX  
	ADD CONSTRAINT REGIONAL_PROCESS_POINT_GROUP_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.REGIONAL_PROCESS_POINT_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
      
------------------------------------------------
-- DDL Statements for Table "GALADM  "."PROCESS_POINT_GROUP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.PROCESS_POINT_GROUP_TR1;
DROP TRIGGER GALADM.PROCESS_POINT_GROUP_TR2;
DROP TABLE GALADM.PROCESS_POINT_GROUP_TBX;

CREATE TABLE GALADM.PROCESS_POINT_GROUP_TBX
(
	IS_REGIONAL			  SMALLINT DEFAULT 0 NOT NULL,
	SITE	              CHAR(16) NOT NULL,
	PROCESS_POINT_GROUP_NAME	VARCHAR(256) NOT NULL,
	PROCESS_POINT_ID	  CHAR(16) NOT NULL,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.PROCESS_POINT_GROUP_TBX IS 'PROCESS POINT GROUP';

CREATE UNIQUE INDEX GALADM.PROCESS_POINT_GROUP_I1
  ON GALADM.PROCESS_POINT_GROUP_TBX (IS_REGIONAL, SITE, PROCESS_POINT_GROUP_NAME, PROCESS_POINT_ID);

ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT PROCESS_POINT_GROUP_PK PRIMARY KEY (IS_REGIONAL, SITE, PROCESS_POINT_GROUP_NAME, PROCESS_POINT_ID);
		
ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT PROCESS_POINT_GROUP_C1 CHECK 
		(SITE = UPPER(SITE));
		
ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX 
	ADD CONSTRAINT PROCESS_POINT_GROUP_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX  
	ADD CONSTRAINT PROCESS_POINT_GROUP_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.PROCESS_POINT_GROUP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PROCESS_POINT_GROUP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.PROCESS_POINT_GROUP_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  