ALTER TABLE GALADM.WSCLIENTS_TBX ADD COLUMN PHONE_EXTENSION CHAR(10);

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_ENTRY_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_ENTRY_DEPT_TR1;
DROP TRIGGER GALADM.QI_STATION_ENTRY_DEPT_TR2;
DROP TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX;

CREATE TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX
(
	PROCESS_POINT_ID      CHAR(16) NOT NULL ,
	DIVISION_ID           CHAR(16) NOT NULL ,
	IS_DEFAULT            SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX IS 'NAQ Entry Department by Station';

CREATE UNIQUE INDEX GALADM.QI_STATION_ENTRY_DEPT_I1
  ON GALADM.QI_STATION_ENTRY_DEPT_TBX (PROCESS_POINT_ID, DIVISION_ID);

ALTER TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_DEPT_PK PRIMARY KEY (PROCESS_POINT_ID, DIVISION_ID);
		
ALTER TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_DEPT_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX  
	ADD CONSTRAINT QI_STATION_ENTRY_DEPT_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_STATION_ENTRY_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_ENTRY_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_ENTRY_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_ENTRY_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
        
        
------------------------------------------------
-- DDL Statements for Table "GALADM  "."STATION_USER_TBX"
------------------------------------------------

DROP TRIGGER GALADM.STATION_USER_TR1;
DROP TRIGGER GALADM.STATION_USER_TR2;
DROP TABLE GALADM.STATION_USER_TBX;

CREATE TABLE GALADM.STATION_USER_TBX
(
	HOST_NAME             CHARACTER(32) NOT NULL,
	USER                  CHAR(11) NOT NULL ,
	LOGIN_TIMESTAMP       TIMESTAMP(6),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.STATION_USER_TBX IS 'Users logged on the station';

CREATE UNIQUE INDEX GALADM.STATION_USER_I1
  ON GALADM.STATION_USER_TBX (HOST_NAME, USER);

ALTER TABLE GALADM.STATION_USER_TBX 
	ADD CONSTRAINT STATION_USER_PK PRIMARY KEY (HOST_NAME, USER);
		
ALTER TABLE GALADM.STATION_USER_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.STATION_USER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.STATION_USER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.STATION_USER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.STATION_USER_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

                                    