DROP TRIGGER GALADM.MFG_CTRL_OP_MATRIX_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_MATRIX_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_MATRIX_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_MEAS_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_MEAS_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_MEAS_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_PART_MATRIX_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_PART_MATRIX_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_PART_MATRIX_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_PART_REV_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_PART_REV_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_PART_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_PART_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_PART_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_REV_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_REV_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_REV_TBX;

DROP TRIGGER GALADM.MFG_CTRL_OP_TR2;
DROP TRIGGER GALADM.MFG_CTRL_OP_TR1;
DROP TABLE GALADM.MFG_CTRL_OP_TBX;

DROP TRIGGER GALADM.MFG_CTRL_ORDER_STRUCTURE_TR2;
DROP TRIGGER GALADM.MFG_CTRL_ORDER_STRUCTURE_TR1;
DROP TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX;

DROP TRIGGER GALADM.MFG_CTRL_PDDA_PROCESS_TR2;
DROP TRIGGER GALADM.MFG_CTRL_PDDA_PROCESS_TR1;
DROP TABLE GALADM.MFG_CTRL_PDDA_PROCESS_TBX;

DROP TRIGGER GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TR2;
DROP TRIGGER GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TR1;
DROP TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX;

DROP TRIGGER GALADM.MFG_CTRL_REV_TR2;
DROP TRIGGER GALADM.MFG_CTRL_REV_TR1;
DROP TABLE GALADM.MFG_CTRL_REV_TBX;

DROP TRIGGER GALADM.MFG_CTRL_STRUCTURE_TR2;
DROP TRIGGER GALADM.MFG_CTRL_STRUCTURE_TR1;
DROP TABLE GALADM.MFG_CTRL_STRUCTURE_TBX;





