ALTER TABLE GALADM.GAL245TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.GAL245TBX ADD COLUMN UPDATE_USER CHAR(11);
ALTER TABLE GALADM.GAL245TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.GAL245TBX;
 
ALTER TABLE GALADM.GAL246TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.GAL246TBX ADD COLUMN UPDATE_USER CHAR(11);
ALTER TABLE GALADM.GAL246TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.GAL246TBX;
 
ALTER TABLE GALADM.GAL259TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.GAL259TBX ADD COLUMN UPDATE_USER CHAR(11);
ALTER TABLE GALADM.GAL259TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.GAL259TBX; 
