ALTER TABLE GALADM.GAL191TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL191TBX
ADD COLUMN PROCESS_POINT_ID CHARACTER(16)
;

ALTER TABLE GALADM.GAL191TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL191TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL191TBX;