CREATE INDEX GALADM.GAL245_I2
	ON GALADM.GAL245TBX
		(PART_NAME ASC, PART_ID ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;

CREATE INDEX GALADM.GAL246_I2
	ON GALADM.GAL246TBX
		(PART_NAME ASC, PROCESS_POINT_ID ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;

CREATE INDEX GALADM.GAL185_I6
	ON GALADM.GAL185TBX
		(PART_NAME ASC, ACTUAL_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;

CREATE INDEX GALADM.GAL185_HIST_I1
	ON GALADM.GAL185_HIST_TBX
		(PART_NAME ASC, PART_SERIAL_NUMBER ASC, PRODUCT_ID ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;
  
CREATE INDEX GALADM.GAL185_HIST_I3
	ON GALADM.GAL185_HIST_TBX
		(PART_NAME ASC, PRODUCT_ID ASC, PART_SERIAL_NUMBER ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;
 
CREATE INDEX GALADM.GAL185_HIST_I4
	ON GALADM.GAL185_HIST_TBX
		(PROCESS_POINT_ID ASC, CREATE_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;
 
CREATE INDEX GALADM.GAL185_HIST_I5
	ON GALADM.GAL185_HIST_TBX
		(PROCESS_POINT_ID ASC, ACTUAL_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;
  
CREATE INDEX GALADM.GAL185_HIST_I6
	ON GALADM.GAL185_HIST_TBX
		(PART_NAME ASC, ACTUAL_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;

CREATE INDEX GALADM.GAL198_I1
	ON GALADM.GAL198TBX
		(PART_NAME ASC, ACTUAL_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;

CREATE INDEX GALADM.GAL198_HIST_I2
	ON GALADM.GAL198_HIST_TBX
		(PART_NAME ASC, ACTUAL_TIMESTAMP ASC)
	ALLOW REVERSE SCANS
	COMPRESS NO;