create  table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_PROC_TEMP (
	"VIOS_PLATFORM_ID" CHARACTER(17) NOT NULL ,
	"UNIT_NO" VARCHAR(6) NOT NULL ,
	"PART_NO" CHARACTER(18) NOT NULL ,
	"CHECK_POINT" VARCHAR(32) NOT NULL ,
	"CHECK_SEQ" INTEGER NOT NULL ,
	"CHECK_NAME" VARCHAR(35) NOT NULL,
	"CHECKER" VARCHAR(255) NOT NULL,
	"REACTION_TYPE" VARCHAR(32) )
IN "GALTBSREF12" INDEX IN "GALTBSIDX4";

insert into GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_PROC_TEMP(VIOS_PLATFORM_ID, UNIT_NO, PART_NO, CHECK_POINT, CHECK_SEQ, CHECK_NAME, CHECKER, REACTION_TYPE) SELECT PC.VIOS_PLATFORM_ID, PC.UNIT_NO, PC.PART_NO, PC.CHECK_POINT, PC.CHECK_SEQ, MAX(PC.CHECK_NAME), MAX(PC.CHECKER), MAX(PC.REACTION_TYPE) FROM GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX PC GROUP BY PC.VIOS_PLATFORM_ID, PC.UNIT_NO, PC.PART_NO, PC.CHECK_POINT, PC.CHECK_SEQ;

delete from (select * from GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX fetch first 10000 rows only);

insert into GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX(VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, CHECK_POINT, CHECK_SEQ, CHECK_NAME, CHECKER, REACTION_TYPE) select VIOS_PLATFORM_ID, UNIT_NO, PART_NO, '', '', CHECK_POINT, CHECK_SEQ, CHECK_NAME, CHECKER, REACTION_TYPE from GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_PROC_TEMP;

drop table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_PROC_TEMP;

alter table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX drop PRIMARY KEY;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX ADD CONSTRAINT MC_VIOS_MASTER_OP_PART_CHECKER_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, PART_NO, CHECK_POINT, CHECK_SEQ);

alter table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX drop column PART_SECTION_CODE;

alter table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX drop column PART_ITEM_NO;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT ''; 

reorg table GALADM.MC_VIOS_MASTER_OP_PART_CHECKER_TBX;