ALTER TABLE GALADM.GAL241TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL241TBX  
  ADD COLUMN APP_VIEW VARCHAR(255)
  ADD COLUMN APP_PROCESSOR VARCHAR(255); 
     
ALTER TABLE GALADM.GAL241TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL241_TR2;
DROP TRIGGER GALADM.GAL241_TR1;

CREATE TRIGGER GALADM.GAL241_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL241_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL241TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL241TBX;

ALTER TABLE GALADM.GAL242TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL242TBX  
  ADD COLUMN SEQ_NUM INTEGER; 
     
ALTER TABLE GALADM.GAL242TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL242_TR2;
DROP TRIGGER GALADM.GAL242_TR1;

CREATE TRIGGER GALADM.GAL242_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL242_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL242TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL242TBX;

ALTER TABLE GALADM.GAL185TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL185TBX
  ADD COLUMN PROCESS_POINT_ID CHARACTER(16)
  ADD COLUMN OP_REV INTEGER
  ADD COLUMN PART_ID CHARACTER(5)
  ADD COLUMN PART_REV INTEGER
  ; 
     
ALTER TABLE GALADM.GAL185TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL185_TR2;
DROP TRIGGER GALADM.GAL185_TR1;

CREATE TRIGGER GALADM.GAL185_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL185TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL185_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL185TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL185TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL185TBX;

ALTER TABLE GALADM.GAL185_HIST_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL185_HIST_TBX  
  ADD COLUMN PROCESS_POINT_ID CHARACTER(16)
  ADD COLUMN OP_REV INTEGER
  ADD COLUMN PART_ID CHARACTER(5)
  ADD COLUMN PART_REV INTEGER
  ; 
     
ALTER TABLE GALADM.GAL185_HIST_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL185_HIST_TR2;
DROP TRIGGER GALADM.GAL185_HIST_TR1;

CREATE TRIGGER GALADM.GAL185_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL185_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL185_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL185_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL185_HIST_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL185_HIST_TBX;

ALTER TABLE GALADM.GAL198TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL198TBX  
  ADD COLUMN PART_ID  CHARACTER(5)
  ADD COLUMN PART_REV INTEGER; 
     
ALTER TABLE GALADM.GAL198TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL198_TR2;
DROP TRIGGER GALADM.GAL198_TR1;

CREATE TRIGGER GALADM.GAL198_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL198TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL198TBX;

ALTER TABLE GALADM.GAL198_HIST_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL198_HIST_TBX  
  ADD COLUMN PART_ID  CHARACTER(5)
  ADD COLUMN PART_REV INTEGER; 
     
ALTER TABLE GALADM.GAL198_HIST_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL198_HIST_TR2;
DROP TRIGGER GALADM.GAL198_HIST_TR1;

CREATE TRIGGER GALADM.GAL198_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL198_HIST_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL198_HIST_TBX;