------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_COMPANY_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_COMPANY_TR1;
DROP TRIGGER GALADM.QI_COMPANY_TR2;
DROP TABLE GALADM.QI_COMPANY_TBX;

CREATE TABLE GALADM.QI_COMPANY_TBX
(
	COMPANY		          VARCHAR(32) NOT NULL ,
	COMPANY_DESCRIPTION   VARCHAR(64),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;


COMMENT ON TABLE GALADM.QI_COMPANY_TBX IS 'NAQ Company';

CREATE UNIQUE INDEX GALADM.QI_COMPANY_I1
  ON GALADM.QI_COMPANY_TBX (COMPANY);

ALTER TABLE GALADM.QI_COMPANY_TBX 
	ADD CONSTRAINT QI_COMPANY_PK PRIMARY KEY (COMPANY);
		
ALTER TABLE GALADM.QI_COMPANY_TBX 
	ADD CONSTRAINT QI_COMPANY_C1 CHECK 
		(COMPANY = UPPER(COMPANY));
		
ALTER TABLE GALADM.QI_COMPANY_TBX 
	ADD CONSTRAINT QI_COMPANY_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_COMPANY_TBX  
	ADD CONSTRAINT QI_COMPANY_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_COMPANY_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_COMPANY_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_COMPANY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_COMPANY_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_COMPANY_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
    
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_SITE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_SITE_TR1;
DROP TRIGGER GALADM.QI_SITE_TR2;
DROP TABLE GALADM.QI_SITE_TBX;

CREATE TABLE GALADM.QI_SITE_TBX
(
	SITE             	  CHAR(16) NOT NULL ,
	SITE_DESCRIPTION      VARCHAR(64),
	COMPANY          	  VARCHAR(32),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_SITE_TBX IS 'NAQ Site';

CREATE UNIQUE INDEX GALADM.QI_SITE_I1
  ON GALADM.QI_SITE_TBX (SITE);

ALTER TABLE GALADM.QI_SITE_TBX 
	ADD CONSTRAINT QI_SITE_PK PRIMARY KEY (SITE);
		
ALTER TABLE GALADM.QI_SITE_TBX 
	ADD CONSTRAINT QI_SITE_C1 CHECK 
		(SITE = UPPER(SITE));
		
ALTER TABLE GALADM.QI_SITE_TBX 
	ADD CONSTRAINT QI_SITE_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_SITE_TBX  
	ADD CONSTRAINT QI_SITE_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_SITE_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_SITE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_SITE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_SITE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_SITE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_PLANT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_PLANT_TR1;
DROP TRIGGER GALADM.QI_PLANT_TR2;
DROP TABLE GALADM.QI_PLANT_TBX;

CREATE TABLE GALADM.QI_PLANT_TBX
(
	SITE             	  CHAR(16) NOT NULL ,
	PLANT          		  CHAR(16) NOT NULL ,
	PLANT_DESCRIPTION  	  VARCHAR(32),
	HAM_PLANT_CODE		  CHAR(1),
	PRODUCT_KIND		  CHAR(18),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_PLANT_TBX IS 'NAQ Plant';

CREATE UNIQUE INDEX GALADM.QI_PLANT_I1
  ON GALADM.QI_PLANT_TBX (SITE, PLANT);

ALTER TABLE GALADM.QI_PLANT_TBX 
	ADD CONSTRAINT QI_PLANT_PK PRIMARY KEY (SITE, PLANT);
	
ALTER TABLE GALADM.QI_PLANT_TBX 
	ADD CONSTRAINT QI_PLANT_C1 CHECK 
		(SITE = UPPER(SITE));	
		
ALTER TABLE GALADM.QI_PLANT_TBX 
	ADD CONSTRAINT QI_PLANT_C2 CHECK 
		(PLANT = UPPER(PLANT));
		
ALTER TABLE GALADM.QI_PLANT_TBX 
	ADD CONSTRAINT QI_PLANT_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_PLANT_TBX  
	ADD CONSTRAINT QI_PLANT_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_PLANT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_PLANT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_PLANT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_PLANT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_PLANT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
    
    
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_DEPT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_DEPT_TR1;
DROP TRIGGER GALADM.QI_DEPT_TR2;
DROP TABLE GALADM.QI_DEPT_TBX;

CREATE TABLE GALADM.QI_DEPT_TBX
(
	SITE             	  CHAR(16) NOT NULL ,
	PLANT          		  CHAR(16) NOT NULL ,
	DEPT                  CHAR(16) NOT NULL ,
	DEPT_NAME             VARCHAR(32),
	DEPT_DESCRIPTION      VARCHAR(128),	
	PDDA_DEPT			  CHAR(16),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;


COMMENT ON TABLE GALADM.QI_DEPT_TBX IS 'NAQ Dept';

CREATE UNIQUE INDEX GALADM.QI_DEPT_I1
  ON GALADM.QI_DEPT_TBX (SITE, PLANT, DEPT);

ALTER TABLE GALADM.QI_DEPT_TBX 
	ADD CONSTRAINT QI_DEPT_PK PRIMARY KEY (SITE, PLANT, DEPT);

ALTER TABLE GALADM.QI_DEPT_TBX 
	ADD CONSTRAINT QI_DEPT_C1 CHECK 
		(SITE = UPPER(SITE));	
		
ALTER TABLE GALADM.QI_DEPT_TBX 
	ADD CONSTRAINT QI_DEPT_C2 CHECK 
		(PLANT = UPPER(PLANT));	
		
ALTER TABLE GALADM.QI_DEPT_TBX 
	ADD CONSTRAINT QI_DEPT_C3 CHECK 
		(DEPT = UPPER(DEPT));
		
ALTER TABLE GALADM.QI_DEPT_TBX 
	ADD CONSTRAINT QI_DEPT_C4 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_DEPT_TBX  
	ADD CONSTRAINT QI_DEPT_C5 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_DEPT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_DEPT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_DEPT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_DEPT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_RESPONSIBLE_LEVEL_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_RESPONSIBLE_LEVEL_TR1;
DROP TRIGGER GALADM.QI_RESPONSIBLE_LEVEL_TR2;
DROP TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX;

CREATE TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX
(
	RESPONSIBLE_LEVEL_ID  INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,
	SITE                  CHAR(16) NOT NULL ,
	PLANT                 CHAR(16) NOT NULL ,
	DEPT                  CHAR(16) NOT NULL ,
	RESPONSIBLE_LEVEL_NAME  CHAR(16) NOT NULL,
	RESPONSIBLE_LEVEL_DESCRIPTION  VARCHAR(32),
	LEVEL                 SMALLINT,
	ROW_TYPE              SMALLINT,
	UPPER_RESPONSIBLE_LEVEL_ID  INTEGER,
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
		DATA CAPTURE CHANGES IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX IS 'NAQ Responsible Level';

CREATE UNIQUE INDEX GALADM.QI_RESPONSIBLE_LEVEL_I1
  ON GALADM.QI_RESPONSIBLE_LEVEL_TBX (RESPONSIBLE_LEVEL_ID);

ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX 
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_PK PRIMARY KEY (RESPONSIBLE_LEVEL_ID);
		
ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX 
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX  
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX 
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_C3 CHECK 
		(SITE = UPPER(SITE));		
		
ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX 
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_C4 CHECK 
		(PLANT = UPPER(PLANT));
		
ALTER TABLE GALADM.QI_RESPONSIBLE_LEVEL_TBX 
	ADD CONSTRAINT QI_RESPONSIBLE_LEVEL_C5 CHECK 
		(DEPT = UPPER(DEPT));
		
CREATE TRIGGER GALADM.QI_RESPONSIBLE_LEVEL_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_RESPONSIBLE_LEVEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_RESPONSIBLE_LEVEL_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_RESPONSIBLE_LEVEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  