ALTER TABLE GALADM.GAL144TBX ADD COLUMN COMMON_SALES_MODEL_CODE  CHARACTER(11);
ALTER TABLE GALADM.GAL144TBX ADD COLUMN COMMON_SALES_MODEL_TYPE_CODE   CHARACTER(4);

ALTER TABLE GALADM.GAL158TBX ADD COLUMN COMMON_SALES_MODEL_CODE  CHARACTER(11);
ALTER TABLE GALADM.GAL158TBX ADD COLUMN COMMON_SALES_MODEL_TYPE_CODE   CHARACTER(4);