------------------------------------------------
-- Remove default values for NAQ tables in 1.60
------------------------------------------------

ALTER TABLE GALADM.QI_DEFECT_TBX ALTER COLUMN DEFECT_TYPE_NAME DROP DEFAULT;

ALTER TABLE GALADM.QI_INSPECTION_LOCATION_TBX ALTER COLUMN INSPECTION_PART_LOCATION_NAME DROP DEFAULT;

ALTER TABLE GALADM.QI_INSPECTION_PART_TBX ALTER COLUMN INSPECTION_PART_NAME DROP DEFAULT;

ALTER TABLE GALADM.QI_PART_LOCATION_COMBINATION_TBX ALTER COLUMN INSPECTION_PART_NAME DROP DEFAULT;

