ALTER TABLE GALADM.GAL704TBX_01
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.GAL704TBX_02
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.GAL704TBX_03
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.GAL704TBX_04
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.GAL704TBX_05
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.GAL704TBX_06
 ALTER COLUMN INSPECTION_PARAM_VALUE
 SET DATA TYPE VARCHAR (255);
 
call sysproc.admin_revalidate_db_objects('view','GALADM',null);