ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX DROP COLUMN START_TIME;
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX DROP COLUMN END_TIME;

ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX ADD COLUMN START_TIME TIME;
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX ADD COLUMN END_TIME TIME;
   
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX 
  DATA CAPTURE CHANGES; 
      
