ALTER TABLE GALADM.PRODUCT_SEQUENCE_TBX ADD COLUMN SEQUENCE_NUMBER INTEGER;

DROP INDEX GALADM.PRODUCT_SEQUENCE_I1;

CREATE INDEX GALADM.PRODUCT_SEQUENCE_I1
  ON GALADM.PRODUCT_SEQUENCE_TBX
    ( PROCESS_POINT_ID ASC, SEQUENCE_NUMBER ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
