--RGALCDEV-358
ALTER TABLE GALADM.QSR_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.QSR_TBX  
  ALTER COLUMN PROCESS_LOCATION  
    SET DATA TYPE VARCHAR(16); 
     
ALTER TABLE GALADM.QSR_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.QSR_TR2;
DROP TRIGGER GALADM.QSR_TR1;

CREATE TRIGGER GALADM.QSR_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QSR_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.QSR_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.QSR_TBX;

-- RGALCDEV-381 (HOLD_PARM_TBX)
ALTER TABLE GALADM.HOLD_PARM_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.HOLD_PARM_TBX  
  ALTER COLUMN DEPARTMENT  
    SET DATA TYPE VARCHAR(16); 
     
ALTER TABLE GALADM.HOLD_PARM_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.HOLD_PARM_TR2;
DROP TRIGGER GALADM.HOLD_PARM_TR1;

CREATE TRIGGER GALADM.HOLD_PARM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOLD_PARM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;  

REORG TABLE  GALADM.HOLD_PARM_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.HOLD_PARM_TBX;