DROP TRIGGER VIOS.PVLPR1_TR1;
DROP TRIGGER VIOS.PVLPR1_TR2;
DROP TABLE VIOS.PVLPR1;

CREATE TABLE VIOS.PVLPR1  (
  PROCESS_ID INTEGER NOT NULL ,
  TEAM_ID INTEGER NOT NULL ,
  MPTAG_ID INTEGER NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  ASM_PROC_SEQ_NO SMALLINT NOT NULL ,
  ASM_PROC_NO CHAR(5) NOT NULL ,
  ASM_PROC_NAME CHAR(35) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVLPR1_PK PRIMARY KEY
    (PROCESS_ID, TEAM_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVLPR1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVLPR1 IS 'RMT VIOS MdrsProcess Table';

CREATE TRIGGER VIOS.PVLPR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLPR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVLPR1_I1 ON VIOS.PVLPR1
  (TEAM_ID ASC,
   MPTAG_ID ASC,
   ASM_PROC_NO ASC)
COMPRESS NO ALLOW REVERSE SCANS;


DROP TRIGGER VIOS.PVLTM1_TR1;
DROP TRIGGER VIOS.PVLTM1_TR2;
DROP TABLE VIOS.PVLTM1;

CREATE TABLE VIOS.PVLTM1  (
  TEAM_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  EFF_BEG_DATE DATE NOT NULL ,
  EFF_END_DATE DATE NOT NULL ,
  PROD_RATE_ID INTEGER NOT NULL ,
  TEAM_SEQ_NO SMALLINT NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVLTM1_PK PRIMARY KEY
    (TEAM_ID, PLANT_LOC_CODE, DEPT_CODE, MODEL_YEAR_DATE, PROD_SCH_QTY, VEHICLE_MODEL_CODE, PROD_ASM_LINE_NO))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVLTM1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVLTM1 IS 'RMT VIOS MdrsTeam Table';

CREATE TRIGGER VIOS.PVLTM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLTM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVLTM1_I1 ON VIOS.PVLTM1
(PLANT_LOC_CODE ASC,
 DEPT_CODE ASC,
 MODEL_YEAR_DATE ASC,
 PROD_SCH_QTY ASC,
 VEHICLE_MODEL_CODE ASC,
 TEAM_NO ASC)
COMPRESS NO ALLOW REVERSE SCANS;


DROP TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1;
DROP TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2;
DROP TABLE VIOS.TBLKNOWLEDGESTATUS;

CREATE TABLE VIOS.TBLKNOWLEDGESTATUS  (
  USER_LOGON_ID_NO CHAR(7) NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  MTC_MODEL CHAR(3) NOT NULL ,
  PROCESS_NO CHAR(5) NOT NULL ,
  PROCLINENO CHAR(1) NOT NULL ,
  PROCTEAM CHAR(4) NOT NULL ,
  PROCDESC CHAR(35) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  KNOWLEDGESTATUS_NO INTEGER NOT NULL ,
  ENTEREDBY_UID CHAR(7) NOT NULL ,
  ENTERED_TSTP TIMESTAMP NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  KNOWLEDGE_NOTE_TEXT VARCHAR(250) ,
  PRODRATE INTEGER,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLKNOWLEDGESTATUS_PK PRIMARY KEY
    (USER_LOGON_ID_NO,
     PROCESS_ID,
     MODEL_YEAR_DATE,
     MTC_MODEL,
     EXTRACT_DATE)
)
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLKNOWLEDGESTATUS
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLKNOWLEDGESTATUS IS 'RMT VIOS TBLKNOWLEDGESTATUS';

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I1 ON VIOS.TBLKNOWLEDGESTATUS
(USER_LOGON_ID_NO ASC,
 PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)
COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I2 ON VIOS.TBLKNOWLEDGESTATUS
(PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)
COMPRESS NO ALLOW REVERSE SCANS;


CREATE TABLE GALADM.PROXSCANNER_MAPPING_TBX  (
	CARD_NUMBER			INTEGER NOT NULL,
	USER_ID				CHAR(11),
	CREATE_TIMESTAMP	TIMESTAMP,
	UPDATE_TIMESTAMP	TIMESTAMP,
	CONSTRAINT PROXSCANNER_MAPPING_PK PRIMARY KEY
		(CARD_NUMBER)
)
	IN GALTBSREF11 
	INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PROXSCANNER_MAPPING_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.PROXSCANNER_MAPPING_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PROXSCANNER_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PROXSCANNER_MAPPING_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PROXSCANNER_MAPPING_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.MC_MDRS_TRAINING_TR2;
DROP TRIGGER GALADM.MC_MDRS_TRAINING_TR1;
DROP TABLE GALADM.MC_MDRS_TRAINING_TBX;

CREATE TABLE GALADM.MC_MDRS_TRAINING_TBX (
   USER_LOGON_ID_NO 	CHARACTER(7)	NOT NULL,
   PROCESS_ID 			INTEGER			NOT NULL,
   MODEL_YEAR_DATE 		DECIMAL(5,1)	NOT NULL,
   MTC_MODEL 			CHARACTER(3)	NOT NULL,
   EXTRACT_DATE			TIMESTAMP		NOT NULL,
   PROCESS_POINT_ID   	CHARACTER(16),
   ASSOCIATE_NO			CHARACTER(11),
   PDDA_PLATFORM_ID		INTEGER,
   SPEC_CODE_TYPE     	VARCHAR(32),
   SPEC_CODE_MASK     	VARCHAR(30),
   TRAINED				TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_MDRS_TRAINING_PK PRIMARY KEY 
     (USER_LOGON_ID_NO, PROCESS_ID, MODEL_YEAR_DATE, MTC_MODEL, EXTRACT_DATE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_MDRS_TRAINING_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_MDRS_TRAINING_TBX IS 'RMT MC_MDRS_TRAINING is used by Manufacturing Control to cross reference MC_TRAINING_TBX to MDRS TBLKNOWLEDGESTATUS';
    
CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_MDRS_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_MDRS_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


CREATE TABLE GALADM.MC_TRAINING_TBX (
   PROCESS_POINT_ID   	CHARACTER(16) 	NOT NULL,
   ASSOCIATE_NO			CHARACTER(11)	NOT NULL,
   PDDA_PLATFORM_ID		INTEGER			NOT NULL,
   SPEC_CODE_TYPE     	VARCHAR(32) 	NOT NULL,
   SPEC_CODE_MASK     	VARCHAR(30) 	NOT NULL,
   TRAINED				TIMESTAMP		NOT NULL,
   EXPIRED				TIMESTAMP,
   APPROVER_NO			CHARACTER(11),
   TRAINING_METHOD		VARCHAR(16),
   COMMENTS				VARCHAR(250),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_TRAINING_PK PRIMARY KEY 
     (PROCESS_POINT_ID, ASSOCIATE_NO, PDDA_PLATFORM_ID, SPEC_CODE_TYPE, SPEC_CODE_MASK, TRAINED)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_TRAINING_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_TRAINING_TBX IS 'RMT MC_TRAINING is used by Manufacturing Control to define the Associates that are trained for specific products at a given process';
    
CREATE TRIGGER GALADM.MC_TRAINING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_TRAINING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_PDDA_PLATFORM_TR2;
DROP TRIGGER GALADM.MC_PDDA_PLATFORM_TR1;
DROP TABLE GALADM.MC_PDDA_PLATFORM_TBX;

CREATE TABLE GALADM.MC_PDDA_PLATFORM_TBX (
   PDDA_PLATFORM_ID		INTEGER			NOT NULL 
     GENERATED BY DEFAULT
       AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE,
                    NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
   PLANT_LOC_CODE		CHARACTER(1)	NOT NULL,
   DEPT_CODE			CHARACTER(2)	NOT NULL,
   MODEL_YEAR_DATE		DECIMAL(5, 1)	NOT NULL,
   PROD_SCH_QTY			DECIMAL(5, 1)	NOT NULL,
   PROD_ASM_LINE_NO		CHARACTER(1)	NOT NULL,
   VEHICLE_MODEL_CODE	CHARACTER(1)	NOT NULL,
   ASM_PROC_NO			VARCHAR(5)		NOT NULL,
   PROCESS_POINT_ID 	CHARACTER(16)	NOT NULL,
   PROCESS_SEQ_NUM  	INTEGER,
   APPROVER_NO			CHARACTER(11),
   APPROVED				TIMESTAMP,
   DEPRECATER_NO		CHARACTER(11),
   DEPRECATED			TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_PLATFORM_PK PRIMARY KEY 
     (PDDA_PLATFORM_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_PLATFORM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_PLATFORM_TBX IS 'RMT MC_PDDA_PLATFORM is used by Manufacturing Control to link PDDA Plant Loc Code, Dept Code, Model Year Date, Prod Sch Qty, Prod ASM Line No, Vehicle Model Code, ASM Proc No to GALC Process Point ID';
    
CREATE TRIGGER GALADM.MC_PDDA_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.MC_PDDA_PLATFORM_I1
  ON GALADM.MC_PDDA_PLATFORM_TBX
    ( PLANT_LOC_CODE, DEPT_CODE, MODEL_YEAR_DATE, PROD_SCH_QTY, PROD_ASM_LINE_NO, VEHICLE_MODEL_CODE, ASM_PROC_NO )
  ALLOW REVERSE SCANS
  COMPRESS NO;

