UPDATE GALADM.GAL246TBX set PRODUCT_SPEC_CODE =
TRIM(
CONCAT(
  CONCAT(
    CONCAT(
      CONCAT(
        CONCAT(RPAD(TRIM(MODEL_YEAR_CODE),1,' '), RPAD(TRIM(REPLACE(MODEL_CODE,'*',' ')),3,' ')),
      RPAD(TRIM(REPLACE(MODEL_TYPE_CODE,'*',' ')),3,' ')), 
    RPAD(TRIM(REPLACE(MODEL_OPTION_CODE,'*',' ')),3,' ')),
  RPAD(TRIM(REPLACE(EXT_COLOR_CODE,'*',' ')),10,' ')),
RPAD(TRIM(REPLACE(INT_COLOR_CODE,'*',' ')),2,' '))) where Length(TRIM(PRODUCT_SPEC_CODE))=0;

update GALADM.GAL245TBX set PRODUCT_SPEC_CODE = 
TRIM(
CONCAT(
  CONCAT(
    CONCAT(
      CONCAT(
        CONCAT(RPAD(TRIM(MODEL_YEAR_CODE),1,' '), RPAD(TRIM(REPLACE(MODEL_CODE,'*',' ')),3,' ')),
      RPAD(TRIM(REPLACE(MODEL_TYPE_CODE,'*',' ')),3,' ')), 
    RPAD(TRIM(REPLACE(MODEL_OPTION_CODE,'*',' ')),3,' ')),
  RPAD(TRIM(REPLACE(EXT_COLOR_CODE,'*',' ')),10,' ')),
RPAD(TRIM(REPLACE(INT_COLOR_CODE,'*',' ')),2,' '))) where Length(TRIM(PRODUCT_SPEC_CODE))=0;