ALTER TABLE GALADM.GAL185_HIST_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL185_HIST_TBX  
  ADD COLUMN OP_REV INTEGER
  ADD COLUMN PART_REV INTEGER
  ; 
     
ALTER TABLE GALADM.GAL185_HIST_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL185_HIST_TR2;
DROP TRIGGER GALADM.GAL185_HIST_TR1;

CREATE TRIGGER GALADM.GAL185_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL185_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL185_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL185_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL185_HIST_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL185_HIST_TBX;

ALTER TABLE GALADM.GAL185TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL185TBX
  ADD COLUMN OP_REV INTEGER
  ADD COLUMN PART_REV INTEGER
  ; 
     
ALTER TABLE GALADM.GAL185TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL185_TR2;
DROP TRIGGER GALADM.GAL185_TR1;

CREATE TRIGGER GALADM.GAL185_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL185TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL185_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL185TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL185TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL185TBX;

ALTER TABLE GALADM.GAL198_HIST_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL198_HIST_TBX  
  ADD COLUMN PART_ID  CHARACTER(5)
  ADD COLUMN PART_REV INTEGER; 
     
ALTER TABLE GALADM.GAL198_HIST_TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL198_HIST_TR2;
DROP TRIGGER GALADM.GAL198_HIST_TR1;

CREATE TRIGGER GALADM.GAL198_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL198_HIST_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL198_HIST_TBX;

ALTER TABLE GALADM.GAL198TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL198TBX  
  ADD COLUMN PART_ID  CHARACTER(5)
  ADD COLUMN PART_REV INTEGER; 
     
ALTER TABLE GALADM.GAL198TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL198_TR2;
DROP TRIGGER GALADM.GAL198_TR1;

CREATE TRIGGER GALADM.GAL198_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL198TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL198TBX;

ALTER TABLE GALADM.GAL241TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL241TBX  
  ADD COLUMN APP_VIEW VARCHAR(255)
  ADD COLUMN APP_PROCESSOR VARCHAR(255); 
     
ALTER TABLE GALADM.GAL241TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL241_TR2;
DROP TRIGGER GALADM.GAL241_TR1;

CREATE TRIGGER GALADM.GAL241_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL241_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL241TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL241TBX;

ALTER TABLE GALADM.GAL242TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL242TBX  
  ADD COLUMN SEQ_NUM INTEGER; 
     
ALTER TABLE GALADM.GAL242TBX 
  DATA CAPTURE CHANGES; 
  
DROP TRIGGER GALADM.GAL242_TR2;
DROP TRIGGER GALADM.GAL242_TR1;

CREATE TRIGGER GALADM.GAL242_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL242_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL242TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL242TBX;

CREATE TABLE GALADM.MFG_CTRL_OP_MATRIX_TBX (
   OPERATION_NAME     CHARACTER(32) NOT NULL,
   OP_REV             INTEGER NOT NULL,
   SPEC_CODE_TYPE     VARCHAR(32) NOT NULL,
   SPEC_CODE_MASK     VARCHAR(30) NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_MATRIX_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, SPEC_CODE_TYPE, SPEC_CODE_MASK)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_MATRIX_TBX IS 'RMT MFG_CTRL_OP_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MFG_CTRL_STRUCTUREs';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_MATRIX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_MATRIX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_OP_MEAS_TBX (
   OPERATION_NAME     CHARACTER(32) NOT NULL,
   PART_ID            CHARACTER(5) NOT NULL,
   PART_REV           INTEGER NOT NULL,
   OP_MEAS_SEQ_NUM    INTEGER NOT NULL,
   MEAS_TYPE          VARCHAR(32),
   MEAS_VIEW          VARCHAR(255),
   MEAS_PROCESSOR     VARCHAR(255),
   DEVICE_ID          CHARACTER(32),
   DEVICE_MSG         CHARACTER(32),
   MINIMUM_LIMIT      DOUBLE,
   MAXIMUM_LIMIT      DOUBLE,
   MEAS_MAX_ATTEMPTS	INTEGER,
   MEAS_TIME          INTEGER,
   MEAS_CHECK         INTEGER,
   CREATE_TIMESTAMP	  TIMESTAMP,
   UPDATE_TIMESTAMP	  TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_MEAS_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV, OP_MEAS_SEQ_NUM)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_MEAS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_MEAS_TBX IS 'RMT MFG_CTRL_OP_MEAS is used by Manufacturing Control to define the part measurement specs for a specific revision of an operation part';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_MEAS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_MEAS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_OP_PART_MATRIX_TBX (
   OPERATION_NAME       CHARACTER(32) NOT NULL,
   PART_ID              CHARACTER(5) NOT NULL,
   PART_REV             INTEGER NOT NULL,
   SPEC_CODE_TYPE     VARCHAR(32) NOT NULL,
   SPEC_CODE_MASK     VARCHAR(30) NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_PART_MATRIX_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV, SPEC_CODE_TYPE, SPEC_CODE_MASK)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_PART_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_PART_MATRIX_TBX IS 'RMT MFG_CTRL_OP_PART_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MFG_CTRL_STRUCTUREs';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_MATRIX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_PART_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_MATRIX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_PART_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX (
   OPERATION_NAME       CHARACTER(32) NOT NULL,
   PART_ID              CHARACTER(5) NOT NULL,
   PART_REV             INTEGER NOT NULL,
   REV_ID         	    BIGINT NOT NULL,
   PART_DESC            VARCHAR(255),
   PART_TYPE            VARCHAR(32),
   PART_VIEW            VARCHAR(255),
   PART_PROCESSOR       VARCHAR(255),
   DEVICE_ID            CHARACTER(32),
   DEVICE_MSG           CHARACTER(32),
   PART_NO              CHARACTER(18),
   PART_SECTION_CODE    CHARACTER(3),
   PART_ITEM_NO         CHARACTER(8),
   PART_MASK          	VARCHAR(255),
   PART_MARK            VARCHAR(32),
   PART_MAX_ATTEMPTS  	INTEGER,
   MEASUREMENT_COUNT  	INTEGER,
   PART_TIME            INTEGER,
   PART_CHECK           INTEGER,
   APPROVED             TIMESTAMP,
   DEPRECATED_REV_ID    BIGINT,
   DEPRECATED           TIMESTAMP,   
   CREATE_TIMESTAMP  	  TIMESTAMP,
   UPDATE_TIMESTAMP	    TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_PART_REV_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_PART_REV_TBX IS 'RMT MFG_CTRL_OP_PART_REV is used by Manufacturing Control to define the revision of parts that can be used at an operation';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_PART_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_PART_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_OP_PART_TBX (
   OPERATION_NAME       CHARACTER(32) NOT NULL,
   PART_ID              CHARACTER(5) NOT NULL,
   PART_REV             INTEGER NOT NULL,
   CREATE_TIMESTAMP  	  TIMESTAMP,
   UPDATE_TIMESTAMP	    TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_PART_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_PART_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_PART_TBX IS 'RMT MFG_CTRL_OP_PART is used by Manufacturing Control to define the current part specs that can be used at an operation';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_OP_REV_TBX (
   OPERATION_NAME	  CHARACTER(32) NOT NULL,
   OP_REV           INTEGER NOT NULL,
   REV_ID       	  BIGINT NOT NULL,
   OP_DESC          VARCHAR(255),
   OP_TYPE          VARCHAR(32),
   OP_VIEW          VARCHAR(255),
   OP_PROCESSOR     VARCHAR(255),
   OP_TIME          INTEGER,
   OP_CHECK         INTEGER,
   PROCESS_POINT_ID CHARACTER(16),
   PROCESS_SEQ_NUM  INTEGER,
   OP_SEQ_NUM       INTEGER,
   DEVICE_ID        CHARACTER(32),
   DEVICE_MSG       CHARACTER(32),
   PDDA_UNIT_ID     BIGINT,
   APPROVED         TIMESTAMP,
   DEPRECATED_REV_ID BIGINT,
   DEPRECATED       TIMESTAMP,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_REV_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_REV_TBX IS 'RMT MFG_CTRL_OP_REV is used by Manufacturing Control to define the revision of operations that can be performed at a process point';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.MFG_CTRL_OP_REV_I1
  ON GALADM.MFG_CTRL_OP_REV_TBX
    ( PROCESS_POINT_ID, OP_SEQ_NUM, OPERATION_NAME, OP_REV )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE TABLE GALADM.MFG_CTRL_OP_TBX (
   OPERATION_NAME	  CHARACTER(32) NOT NULL,
   OP_REV           INTEGER NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_OP_PK PRIMARY KEY 
     (OPERATION_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_OP_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_OP_TBX IS 'RMT MFG_CTRL_OP is used by Manufacturing Control to define the current operations that can be performed at a process point';
    
CREATE TRIGGER GALADM.MFG_CTRL_OP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_OP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX (
   ORDER_NO           CHARACTER(20) NOT NULL,
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV      BIGINT NOT NULL,
   CREATE_TIMESTAMP	  TIMESTAMP,
   UPDATE_TIMESTAMP	  TIMESTAMP,
   CONSTRAINT MFG_CTRL_ORDER_STRUCTURE_PK PRIMARY KEY 
     (ORDER_NO)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX IS 'RMT MFG_CTRL_ORDER_STRUCTURE is used by Manufacturing Control to define the structure revision that should be used to manufacture this order / lot';
    
CREATE TRIGGER GALADM.MFG_CTRL_ORDER_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_ORDER_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_ORDER_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_PDDA_PROCESS_TBX (
   PROCESS_POINT_ID CHARACTER(16) NOT NULL,
   PDDA_PROCESS_ID  INTEGER NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_PDDA_PROCESS_PK PRIMARY KEY 
     (PROCESS_POINT_ID, PDDA_PROCESS_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_PDDA_PROCESS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_PDDA_PROCESS_TBX IS 'RMT MFG_CTRL_PDDA_PROCESS is used by Manufacturing Control to track the PDDA Maintenance ID for processes to GALC Process Point ID';
    
CREATE TRIGGER GALADM.MFG_CTRL_PDDA_PROCESS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_PDDA_PROCESS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_PDDA_PROCESS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_PDDA_PROCESS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX (
   PRODUCT_ID         CHARACTER(17) NOT NULL,
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV      BIGINT NOT NULL,
   CREATE_TIMESTAMP	  TIMESTAMP,
   UPDATE_TIMESTAMP	  TIMESTAMP,
   CONSTRAINT MFG_CTRL_PRODUCT_STRUCTURE_PK PRIMARY KEY 
     (PRODUCT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX IS 'RMT MFG_CTRL_PRODUCT_STRUCTURE is used by Manufacturing Control to define the structure revision that should be used to manufacture this PRODUCT';
    
CREATE TRIGGER GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_PRODUCT_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_REV_TBX (
   REV_ID    	      BIGINT NOT NULL,
   REV_DESC         VARCHAR(255),
   ASSOCIATE_NO	    CHARACTER(11),
   REV_TYPE         VARCHAR(32),
   REV_STATUS       VARCHAR(32),
   PDDA_FORM_ID     BIGINT,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MFG_CTRL_REV_PK PRIMARY KEY 
     (REV_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_REV_TBX IS 'RMT MFG_CTRL_REV is used by Manufacturing Control to track the revisions of operations, parts and structures';
    
CREATE TRIGGER GALADM.MFG_CTRL_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MFG_CTRL_STRUCTURE_TBX (
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV      BIGINT NOT NULL,
   PROCESS_POINT_ID   CHARACTER(16) NOT NULL,
   OPERATION_NAME     CHARACTER(32) NOT NULL,
   OP_REV             INTEGER NOT NULL,
   PART_ID            CHARACTER(5) NOT NULL DEFAULT '',
   PART_REV           INTEGER NOT NULL DEFAULT 0,
   CREATE_TIMESTAMP	  TIMESTAMP,
   UPDATE_TIMESTAMP	  TIMESTAMP,
   CONSTRAINT MFG_CTRL_STRUCTURE_PK PRIMARY KEY 
     (PRODUCT_SPEC_CODE, STRUCTURE_REV, PROCESS_POINT_ID, OPERATION_NAME, OP_REV, PART_ID, PART_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MFG_CTRL_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MFG_CTRL_STRUCTURE_TBX IS 'RMT MFG_CTRL_STRUCTURE is used by Manufacturing Control to define the revisions of operations and parts that are used to manufacture a Product Spec Code';
    
CREATE TRIGGER GALADM.MFG_CTRL_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MFG_CTRL_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MFG_CTRL_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MFG_CTRL_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

