------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_BOM_PART_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_BOM_PART_TR1";
DROP TRIGGER "GALADM  "."QI_BOM_PART_TR2";
DROP TABLE "GALADM  "."QI_BOM_PART_TBX";

CREATE TABLE "GALADM  "."QI_BOM_PART_TBX"  (
		  "DC_PART_NO" CHAR(18) NOT NULL ,
		  "MODEL_CODE" CHAR(18) NOT NULL ,
		  "MAIN_PART_NO" CHAR(7) NOT NULL ,
		  "DC_PART_NAME" VARCHAR(64) NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP )
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_BOM_PART_TBX IS 'NAQ BOM Part';

CREATE UNIQUE INDEX GALADM.QI_BOM_PART_I1
  ON GALADM.QI_BOM_PART_TBX (DC_PART_NO, MODEL_CODE);

ALTER TABLE "GALADM  "."QI_BOM_PART_TBX" 
	ADD CONSTRAINT "QI_BOM_PART_PK" PRIMARY KEY
		("DC_PART_NO", "MODEL_CODE");
		
ALTER TABLE GALADM.QI_BOM_PART_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_BOM_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_BOM_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_BOM_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_BOM_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

  
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_BOM_QICS_PART_MAPPING_TR1";
DROP TRIGGER "GALADM  "."QI_BOM_QICS_PART_MAPPING_TR2";
DROP TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX";

CREATE TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX"  (
		  "MAIN_PART_NO" CHAR(7) NOT NULL ,
		  "INSPECTION_PART_NAME" VARCHAR(32) NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) ,
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX IS 'NAQ BOM QICS Part Mapping';

CREATE UNIQUE INDEX GALADM.QI_BOM_QICS_PART_MAPPING_I1
  ON GALADM.QI_BOM_QICS_PART_MAPPING_TBX (MAIN_PART_NO, INSPECTION_PART_NAME);

ALTER TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX" 
	ADD CONSTRAINT "QI_BOM_QICS_PART_MAPPING_PK" PRIMARY KEY
		("MAIN_PART_NO" , "INSPECTION_PART_NAME");
		
ALTER TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX" 
	ADD CONSTRAINT "QI_BOM_QICS_PART_MAPPING_C1" CHECK 
		(INSPECTION_PART_NAME = UPPER(INSPECTION_PART_NAME));
		
ALTER TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX" 
	ADD CONSTRAINT "QI_BOM_QICS_PART_MAPPING_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_BOM_QICS_PART_MAPPING_TBX" 
	ADD CONSTRAINT "QI_BOM_QICS_PART_MAPPING_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_BOM_QICS_PART_MAPPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_BOM_QICS_PART_MAPPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_BOM_QICS_PART_MAPPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_BOM_QICS_PART_MAPPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IMAGE_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_IMAGE_TR1";
DROP TRIGGER "GALADM  "."QI_IMAGE_TR2";
DROP TABLE "GALADM  "."QI_IMAGE_TBX";

CREATE TABLE "GALADM  "."QI_IMAGE_TBX"  (
		  "BITMAP_FILE_NAME" VARCHAR(255) NOT NULL ,
		  "IMAGE_NAME" VARCHAR(20) NOT NULL , 
		  "IMAGE_DESCRIPTION" VARCHAR(30) ,
		  "IMAGE_DATA" BLOB(1048576) INLINE LENGTH 164 LOGGED COMPACT ,
		  "PRODUCT_KIND" CHAR(18) ,
		  "ACTIVE" SMALLINT ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) ,
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_IMAGE_TBX IS 'NAQ Image';

CREATE UNIQUE INDEX GALADM.QI_IMAGE_I1
  ON GALADM.QI_IMAGE_TBX (BITMAP_FILE_NAME);

CREATE UNIQUE INDEX GALADM.QI_IMAGE_I2
  ON GALADM.QI_IMAGE_TBX (IMAGE_NAME);

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_PK" PRIMARY KEY
		("BITMAP_FILE_NAME");
		
ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C1" CHECK 
		(IMAGE_NAME = UPPER(IMAGE_NAME));
		
ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C2" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));	
				
ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C3" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_IMAGE_TBX" 
	ADD CONSTRAINT "QI_IMAGE_C4" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IMAGE_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IMAGE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IMAGE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IMAGE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IMAGE_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IMAGE_SECTION_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_TR1";
DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_TR2";
DROP TABLE "GALADM  "."QI_IMAGE_SECTION_TBX";

CREATE TABLE "GALADM  "."QI_IMAGE_SECTION_TBX"  (
		  "IMAGE_SECTION_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,
		  "IMAGE_NAME" VARCHAR(20) ,
		  "PART_LOCATION_ID" INTEGER ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) ,
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.QI_IMAGE_SECTION_TBX IS 'NAQ Image Section';

CREATE UNIQUE INDEX GALADM.QI_IMAGE_SECTION_I1
  ON GALADM.QI_IMAGE_SECTION_TBX (IMAGE_SECTION_ID);

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_PK" PRIMARY KEY
		("IMAGE_SECTION_ID");
		
ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_C1" CHECK 
		(IMAGE_NAME = UPPER(IMAGE_NAME));
		
ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_C2" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_C3" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IMAGE_SECTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IMAGE_SECTION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_POINT_TR1";
DROP TRIGGER "GALADM  "."QI_IMAGE_SECTION_POINT_TR2";
DROP TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX";

CREATE TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX"  (
		  "IMAGE_SECTION_ID" INTEGER NOT NULL DEFAULT 0 ,
		  "POINT_SEQUENCE_NO" INTEGER NOT NULL DEFAULT 0 ,
		  "POINT_X" INTEGER ,
  		  "POINT_Y" INTEGER ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
 		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) ,
		  "UPDATE_USER" CHAR(11) )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 
		 
COMMENT ON TABLE GALADM.QI_IMAGE_SECTION_POINT_TBX IS 'NAQ Image Section Point';

CREATE INDEX GALADM.QI_IMAGE_SECTION_POINT_I1
  ON GALADM.QI_IMAGE_SECTION_POINT_TBX (IMAGE_SECTION_ID);

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_PK" PRIMARY KEY
		("IMAGE_SECTION_ID", "POINT_SEQUENCE_NO");
		
ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_C1" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE "GALADM  "."QI_IMAGE_SECTION_POINT_TBX" 
	ADD CONSTRAINT "QI_IMAGE_SECTION_POINT_C2" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_IMAGE_SECTION_POINT_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_POINT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_IMAGE_SECTION_POINT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_IMAGE_SECTION_POINT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_IMAGE_SECTION_POINT_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TR2";
DROP TRIGGER "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TR1";
DROP TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX";

CREATE TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX"  (
		  "REGIONAL_DEFECT_COMBINATION_ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY 
		  (START WITH 1, INCREMENT BY 1, NO CACHE, NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER) ,
		  "PART_LOCATION_ID" INTEGER , 
		  "DEFECT_TYPE_NAME" VARCHAR(45) , 
		  "DEFECT_TYPE_NAME2" VARCHAR(45) , 
		  "REPORTABLE" SMALLINT , 
		  "PRODUCT_KIND" CHAR(18) , 
		  "ACTIVE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "CREATE_USER" CHAR(11) , 
		  "UPDATE_USER" CHAR(11) )
		 IN "GALTBSDAT10" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX IS 'NAQ Regional Defect Combination';

CREATE UNIQUE INDEX GALADM.QI_REGIONAL_DEFECT_COMBINATION_I1
  ON GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX (REGIONAL_DEFECT_COMBINATION_ID);
  
CREATE INDEX GALADM.QI_REGIONAL_DEFECT_COMBINATION_I2
  ON GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX (PART_LOCATION_ID);

ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_PK" PRIMARY KEY
		("REGIONAL_DEFECT_COMBINATION_ID");

ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_TBX_C1" CHECK 
		(DEFECT_TYPE_NAME = UPPER(DEFECT_TYPE_NAME));	
		
ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_TBX_C2" CHECK 
		(DEFECT_TYPE_NAME2 = UPPER(DEFECT_TYPE_NAME2));	
		
ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_TBX_C3" CHECK 
		(PRODUCT_KIND = UPPER(PRODUCT_KIND));		
				
ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_TBX_C4" CHECK 
		(CREATE_USER = UPPER(CREATE_USER));	
		
ALTER TABLE "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX" 
	ADD CONSTRAINT "QI_REGIONAL_DEFECT_COMBINATION_TBX_C5" CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));	

ALTER TABLE GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REGIONAL_DEFECT_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REGIONAL_DEFECT_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  