CREATE TABLE GALADM.GAL228TBX (
  SMARTEYE_LABEL_NUMBER CHARACTER(4) NOT NULL DEFAULT '',
  VIN CHARACTER(17),
  USE_COUNT INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL228_PK PRIMARY KEY(SMARTEYE_LABEL_NUMBER) 
)
IN GALTBSDAT4
INDEX IN GALTBSIDX2;

COMMENT ON TABLE GALADM.GAL228TBX IS 'Smart Eye';

CREATE TRIGGER GALADM.GAL228_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL228TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL228_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL228TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;