UPDATE GALADM.QI_IQS_VERSION_TBX SET IQS_VERSION=UPPER(IQS_VERSION);

ALTER TABLE GALADM.QI_IQS_VERSION_TBX  
	ADD CONSTRAINT QI_IQS_VERSION_C3 CHECK 
		(IQS_VERSION = UPPER(IQS_VERSION));	

UPDATE GALADM.QI_IQS_CATEGORY_TBX SET IQS_CATEGORY=UPPER(IQS_CATEGORY);
		
ALTER TABLE GALADM.QI_IQS_CATEGORY_TBX  
	ADD CONSTRAINT QI_IQS_CATEGORY_C3 CHECK 
		(IQS_CATEGORY = UPPER(IQS_CATEGORY));		

UPDATE GALADM.QI_IQS_QUESTION_TBX SET IQS_QUESTION=UPPER(IQS_QUESTION);
		
ALTER TABLE GALADM.QI_IQS_QUESTION_TBX  
	ADD CONSTRAINT QI_IQS_QUESTION_C3 CHECK 
		(IQS_QUESTION = UPPER(IQS_QUESTION));		

UPDATE GALADM.QI_IQS_TBX SET IQS_VERSION=UPPER(IQS_VERSION);
UPDATE GALADM.QI_IQS_TBX SET IQS_CATEGORY=UPPER(IQS_CATEGORY);
UPDATE GALADM.QI_IQS_TBX SET IQS_QUESTION=UPPER(IQS_QUESTION);
		
ALTER TABLE GALADM.QI_IQS_TBX  
	ADD CONSTRAINT QI_IQS_C3 CHECK 
		(IQS_VERSION = UPPER(IQS_VERSION));
		
ALTER TABLE GALADM.QI_IQS_TBX  
	ADD CONSTRAINT QI_IQS_C4 CHECK 
		(IQS_CATEGORY = UPPER(IQS_CATEGORY));
		
ALTER TABLE GALADM.QI_IQS_TBX  
	ADD CONSTRAINT QI_IQS_C5 CHECK 
		(IQS_QUESTION = UPPER(IQS_QUESTION));		
