
------------------------------------------------
-- DDL Statements for Table "GALADM  "."DUNNAGE_HIST_TBX"
------------------------------------------------
 
DROP TABLE "GALADM  "."DUNNAGE_HIST_TBX";


CREATE TABLE "GALADM  "."DUNNAGE_HIST_TBX"  (
		  "PRODUCT_ID" VARCHAR(17 OCTETS) NOT NULL , 
		  "DUNNAGE_ID" VARCHAR(20 OCTETS) NOT NULL , 
		  "ON_TIMESTAMP" TIMESTAMP NOT NULL , 
		  "OFF_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT7" INDEX IN "GALTBSIDX3"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "GALADM  "."DUNNAGE_HIST_TBX" IS 'RMT Product to Dunnage Association';

		
-- DDL Statements for Primary Key on Table "GALADM  "."DUNNAGE_HIST_TBX"

ALTER TABLE "GALADM  "."DUNNAGE_HIST_TBX" 
	ADD CONSTRAINT "DUNNAGE_HIST_PK" PRIMARY KEY
		("PRODUCT_ID",
		 "DUNNAGE_ID",
		 "ON_TIMESTAMP");
		 

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_HIST_TR1";

CREATE TRIGGER GALADM.DUNNAGE_HIST_TR1 NO CASCADE BEFORE INSERT ON GALADM.DUNNAGE_HIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."DUNNAGE_HIST_TR2";

CREATE TRIGGER GALADM.DUNNAGE_HIST_TR2 NO CASCADE BEFORE UPDATE ON GALADM.DUNNAGE_HIST_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


