-- *** GALADM.MC_OP_REV_TBX

ALTER TABLE GALADM.MC_OP_REV_TBX DROP PRIMARY KEY;

DROP INDEX GALADM.MC_OP_REV_I1;

CREATE UNIQUE INDEX GALADM.MC_OP_REV_I1 ON GALADM.MC_OP_REV_TBX
  (OPERATION_NAME ASC, OP_REV ASC)
  INCLUDE (APPROVED, DEPRECATED)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_OP_REV_TBX ADD CONSTRAINT MC_OP_REV_PK PRIMARY KEY (OPERATION_NAME, OP_REV);


-- *** GALADM.MC_OP_PART_REV_TBX

ALTER TABLE GALADM.MC_OP_PART_REV_TBX DROP PRIMARY KEY;

DROP INDEX GALADM.MC_OP_PART_REV_I1;

CREATE UNIQUE INDEX GALADM.MC_OP_PART_REV_I1 ON GALADM.MC_OP_PART_REV_TBX
  (OPERATION_NAME ASC, PART_ID ASC, PART_REV ASC)
  INCLUDE (APPROVED, DEPRECATED)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_OP_PART_REV_TBX ADD CONSTRAINT MC_OP_PART_REV_PK PRIMARY KEY (OPERATION_NAME, PART_ID, PART_REV);


-- *** GALADM.MC_OP_REV_PLATFORM_TBX

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX DROP PRIMARY KEY;

DROP INDEX GALADM.MC_OP_REV_PLATFORM_I1;

CREATE UNIQUE INDEX GALADM.MC_OP_REV_PLATFORM_I1 ON GALADM.MC_OP_REV_PLATFORM_TBX
   (OPERATION_NAME ASC, PDDA_PLATFORM_ID ASC, OP_REV ASC)
   INCLUDE (OP_TIME ASC, OP_SEQ_NUM ASC, DEVICE_MSG ASC, DEVICE_ID ASC, UPDATE_TIMESTAMP ASC, CREATE_TIMESTAMP ASC)
   ALLOW REVERSE SCANS;

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX ADD CONSTRAINT MC_OP_REV_PLATFORM_PK PRIMARY KEY (OPERATION_NAME, PDDA_PLATFORM_ID, OP_REV);

DROP INDEX GALADM.MC_OP_REV_PLATFORM_I2;

CREATE INDEX GALADM.MC_OP_REV_PLATFORM_I2 ON GALADM.MC_OP_REV_PLATFORM_TBX
   (OP_REV ASC, OPERATION_NAME ASC, PDDA_PLATFORM_ID ASC)
   ALLOW REVERSE SCANS;


-- *** GALADM.MC_OP_PART_MATRIX_TBX

DROP INDEX GALADM.MC_OP_PART_MATRIX_I2;

CREATE INDEX GALADM.MC_OP_PART_MATRIX_I2 ON GALADM.MC_OP_PART_MATRIX_TBX
   (SPEC_CODE_TYPE ASC, SPEC_CODE_MASK DESC)
   ALLOW REVERSE SCANS;


-- *** GALADM.MC_PDDA_UNIT_REV_TBX

DROP INDEX GALADM.MC_PDDA_UNIT_REV_I1;

CREATE INDEX GALADM.MC_PDDA_UNIT_REV_I1 ON GALADM.MC_PDDA_UNIT_REV_TBX
   (PDDA_REPORT ASC)
   ALLOW REVERSE SCANS;


-- *** GALADM.MC_PDDA_PLATFORM_TBX

DROP INDEX GALADM.MC_PDDA_PLATFORM_I2;

CREATE INDEX GALADM.MC_PDDA_PLATFORM_I2 ON GALADM.MC_PDDA_PLATFORM_TBX
   (PROCESS_POINT_ID ASC, PDDA_PLATFORM_ID ASC)
   ALLOW REVERSE SCANS;


-- *** GALADM.MC_STRUCTURE_TBX

DROP INDEX GALADM.MC_STRUCTURE_I1;

CREATE INDEX GALADM.MC_STRUCTURE_I1 ON GALADM.MC_STRUCTURE_TBX
   (OPERATION_NAME ASC, OP_REV ASC)
   ALLOW REVERSE SCANS;

DROP INDEX GALADM.MC_STRUCTURE_I2;

CREATE INDEX GALADM.MC_STRUCTURE_I2 ON GALADM.MC_STRUCTURE_TBX
  (STRUCTURE_REV ASC, PRODUCT_SPEC_CODE ASC)
  ALLOW REVERSE SCANS;


-- *** GALADM.GAL214TBX

ALTER TABLE GALADM.GAL214TBX DROP PRIMARY KEY;

DROP INDEX GALADM.GAL214_I1;

CREATE UNIQUE INDEX GALADM.GAL214_I1 ON GALADM.GAL214TBX
  (PROCESS_POINT_ID ASC)
  INCLUDE (PLANT_NAME)
  ALLOW REVERSE SCANS;

ALTER TABLE GALADM.GAL214TBX ADD CONSTRAINT GAL214_PK PRIMARY KEY (PROCESS_POINT_ID);


-- *** GALADM.BOM_TBX

DROP INDEX GALADM.BOM_I3;

CREATE INDEX GALADM.BOM_I3 ON GALADM.BOM_TBX
  (MTC_TYPE ASC, MTC_COLOR ASC, MTC_MODEL ASC, EFF_BEG_DATE ASC, EFF_END_DATE ASC, PDDA_FIF_TYPE ASC,
  INT_COLOR_CODE ASC, PART_BLOCK_CODE ASC, MTC_OPTION ASC)
  ALLOW REVERSE SCANS;
