ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX DROP PRIMARY KEY;
DROP INDEX GALADM.REGIONAL_PROCESS_POINT_GROUP_I1;
DROP INDEX GALADM.PROCESS_POINT_GROUP_I1;

ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX RENAME COLUMN IS_REGIONAL to CATEGORY_CODE;
ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX RENAME COLUMN IS_REGIONAL to CATEGORY_CODE;

ALTER TABLE GALADM.REGIONAL_PROCESS_POINT_GROUP_TBX ADD CONSTRAINT REGIONAL_PROCESS_POINT_GROUP_PK PRIMARY KEY
                (CATEGORY_CODE, SITE, PROCESS_POINT_GROUP_NAME);

ALTER TABLE GALADM.PROCESS_POINT_GROUP_TBX ADD CONSTRAINT PROCESS_POINT_GROUP_PK PRIMARY KEY
                (CATEGORY_CODE, SITE, PROCESS_POINT_GROUP_NAME, PROCESS_POINT_ID);
