ALTER TABLE GALADM.BLOCK_TBX ALTER COLUMN TRACKING_STATUS SET DATA TYPE VARCHAR(16);
ALTER TABLE GALADM.CONROD_TBX ALTER COLUMN TRACKING_STATUS SET DATA TYPE VARCHAR(16);
ALTER TABLE GALADM.CRANKSHAFT_TBX ALTER COLUMN TRACKING_STATUS SET DATA TYPE VARCHAR(16);
ALTER TABLE GALADM.HEAD_TBX ALTER COLUMN TRACKING_STATUS SET DATA TYPE VARCHAR(16);

ALTER TABLE GALADM.CASE_TBX ALTER COLUMN TRACKING_STATUS SET DATA TYPE VARCHAR(16);