ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX DATA CAPTURE NONE;

ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX RENAME COLUMN MODEL_CODE TO MODEL_GROUP;
ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX ADD COLUMN DEPT CHAR(16);
ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX ADD COLUMN SYSTEM CHAR(18);
ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX ADD COLUMN LEVEL CHAR(16);
ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX ALTER COLUMN MODEL_GROUP SET DATA TYPE VARCHAR(32);

ALTER TABLE GALADM.QI_REPORTING_TARGET_TBX DATA CAPTURE CHANGES;

REORG TABLE GALADM.QI_REPORTING_TARGET_TBX;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPORTING_METRIC_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_REPORTING_METRIC_TR1;
DROP TRIGGER GALADM.QI_REPORTING_METRIC_TR2;
DROP TABLE GALADM.QI_REPORTING_METRIC_TBX;

CREATE TABLE GALADM.QI_REPORTING_METRIC_TBX
(
	METRIC_NAME           CHAR(10) NOT NULL,
	LEVEL				  CHAR(16) NOT NULL,
	METRIC_DESCRIPTION    VARCHAR(64),
	METRIC_DATA_FORMAT    CHAR(16),
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_REPORTING_METRIC_TBX IS 'NAQ Reporting METRIC';

CREATE UNIQUE INDEX GALADM.QI_REPORTING_METRIC_I1
  ON GALADM.QI_REPORTING_METRIC_TBX (METRIC_NAME, LEVEL);

ALTER TABLE GALADM.QI_REPORTING_METRIC_TBX 
	ADD CONSTRAINT QI_REPORTING_METRIC_PK PRIMARY KEY (METRIC_NAME, LEVEL);
		
ALTER TABLE GALADM.QI_REPORTING_METRIC_TBX 
	ADD CONSTRAINT QI_REPORTING_METRIC_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_REPORTING_METRIC_TBX  
	ADD CONSTRAINT QI_REPORTING_METRIC_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_REPORTING_METRIC_TBX 
	ADD CONSTRAINT QI_REPORTING_METRIC_C3 CHECK 
		(METRIC_NAME = UPPER(METRIC_NAME));	

ALTER TABLE GALADM.QI_REPORTING_METRIC_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REPORTING_METRIC_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPORTING_METRIC_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REPORTING_METRIC_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPORTING_METRIC_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  