------------------------------------------------
-- DDL Statements for Table "GALADM  "."ADVANCE_PROCESS_CYCLE_TIMER_TBX" AS PART OF RGALCDEV-7728
------------------------------------------------

DROP TABLE GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX;
DROP TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR1;
DROP TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR2;

CREATE TABLE GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX (
  ID INTEGER NOT NULL,
  LINE_ID VARCHAR(16),
  CYCLE_TIMER VARCHAR(100),
  WARNING_VALUE INTEGER NOT NULL DEFAULT 0,
  ERROR_VALUE INTEGER NOT NULL DEFAULT 0,
  CREATED_BY VARCHAR(100),
  UPDATED_BY VARCHAR(100),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP
) IN GALTBSDAT9 INDEX IN GALTBSIDX3;

COMMENT ON TABLE GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX IS 'Advanced Process Cycle Timer - It holds configuration data for Max Cycle Time and Min and Max time/units for Current Cycle, Over Cycles, Accum. Time and On Target';

ALTER TABLE GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX 
	ADD CONSTRAINT ADVANCE_PROCESS_CYCLE_TIMER_PK PRIMARY KEY (ID);
	
CREATE TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX
  REFERENCING
    NEW AS A
 FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.ADVANCE_PROCESS_CYCLE_TIMER_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
