DROP TRIGGER GALADM.MC_APP_CHECKER_TR2;
DROP TRIGGER GALADM.MC_APP_CHECKER_TR1;
DROP TABLE GALADM.MC_APP_CHECKER_TBX;

CREATE TABLE GALADM.MC_APP_CHECKER_TBX (
   APPLICATION_ID		CHARACTER(16)	NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_APP_CHECKER_PK PRIMARY KEY (APPLICATION_ID, CHECK_POINT, CHECK_SEQ)
)
 	 	 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_APP_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_APP_CHECKER_TBX IS 'RMT MC_APP_CHECKER_TBX is used by Manufacturing Control to define Checkers at the Application level';
    
CREATE TRIGGER GALADM.MC_APP_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_APP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_APP_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_APP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_OP_CHECKER_TR2;
DROP TRIGGER GALADM.MC_OP_CHECKER_TR1;
DROP TABLE GALADM.MC_OP_CHECKER_TBX;

CREATE TABLE GALADM.MC_OP_CHECKER_TBX (
   OPERATION_NAME		CHARACTER(32)	NOT NULL,
   OP_REV				INTEGER			NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_CHECKER_PK PRIMARY KEY (OPERATION_NAME, OP_REV, CHECK_POINT, CHECK_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_CHECKER_TBX IS 'RMT MC_OP_CHECKER_TBX is used by Manufacturing Control to define Checkers at the Operation/Unit level';
    
CREATE TRIGGER GALADM.MC_OP_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_OP_PART_CHECKER_TR2;
DROP TRIGGER GALADM.MC_OP_PART_CHECKER_TR1;
DROP TABLE GALADM.MC_OP_PART_CHECKER_TBX;

CREATE TABLE GALADM.MC_OP_PART_CHECKER_TBX (
   OPERATION_NAME		CHARACTER(32)	NOT NULL,
   PART_ID				CHARACTER(5)	NOT NULL,
   OP_REV				INTEGER			NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_PART_CHECKER_PK PRIMARY KEY (OPERATION_NAME, PART_ID, OP_REV, CHECK_POINT, CHECK_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_PART_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_PART_CHECKER_TBX IS 'RMT MC_OP_PART_CHECKER_TBX is used by Manufacturing Control to define Checkers at the Part level';
    
CREATE TRIGGER GALADM.MC_OP_PART_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_PART_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_PART_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_PART_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MC_OP_MEAS_CHECKER_TR2;
DROP TRIGGER GALADM.MC_OP_MEAS_CHECKER_TR1;
DROP TABLE GALADM.MC_OP_MEAS_CHECKER_TBX;

CREATE TABLE GALADM.MC_OP_MEAS_CHECKER_TBX (
   OPERATION_NAME		CHARACTER(32)	NOT NULL,
   PART_ID				CHARACTER(5)	NOT NULL,
   OP_REV				INTEGER			NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER			NOT NULL,
   CHECK_POINT			VARCHAR(32)		NOT NULL,
   CHECK_SEQ			INTEGER			NOT NULL,
   CHECK_NAME			VARCHAR(35)		NOT NULL,
   CHECKER				VARCHAR(255)	NOT NULL,
   REACTION_TYPE		VARCHAR(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_MEAS_CHECKER_PK PRIMARY KEY (OPERATION_NAME, PART_ID, OP_REV, OP_MEAS_SEQ_NUM, CHECK_POINT, CHECK_SEQ, CHECK_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_MEAS_CHECKER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_MEAS_CHECKER_TBX IS 'RMT MC_OP_MEAS_CHECKER_TBX is used by Manufacturing Control to define Checkers at the Measurement level';
    
CREATE TRIGGER GALADM.MC_OP_MEAS_CHECKER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_MEAS_CHECKER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_MEAS_CHECKER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;










