DROP TRIGGER GALADM.STRAGGLER_TR1;
DROP TRIGGER GALADM.STRAGGLER_TR2;
DROP TABLE GALADM.STRAGGLER_TBX;

CREATE TABLE GALADM.STRAGGLER_TBX (
  PRODUCT_ID	VARCHAR(20)	NOT NULL,
  PP_DELAYED_AT	VARCHAR(16)	NOT NULL,
  IDENTIFIED_TIMESTAMP	TIMESTAMP,
  LAST_PASSING_PROCESS_POINT	VARCHAR(16),
  UNITS_BEHIND	INTEGER,
  ACTUAL_PROCESS_TIMESTAMP TIMESTAMP,
  ACTUAL_UNITS_BEHIND	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT STRAGGLER_PK PRIMARY KEY
    (PRODUCT_ID, PP_DELAYED_AT)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.STRAGGLER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.STRAGGLER_TBX IS 'Straggler';

CREATE TRIGGER GALADM.STRAGGLER_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.STRAGGLER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.STRAGGLER_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.STRAGGLER_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
