CREATE TABLE GALADM.COMPONENT_STATUS_TBX (
  COMPONENT_ID VARCHAR(40) NOT NULL,
  STATUS_KEY VARCHAR(64) NOT NULL,
  STATUS_VALUE VARCHAR(1024) NOT NULL,
  DESCRIPTION VARCHAR(64),
  CHANGE_USER_ID VARCHAR(32),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP)
                 IN "GALTBSREF12" INDEX IN "GALTBSIDX4" ;

COMMENT ON TABLE "GALADM  "."COMPONENT_STATUS_TBX" IS 'RMT Compenent Status';

CREATE UNIQUE INDEX "GALADM  "."COMPONENT_STATUS_I1" ON "GALADM  "."COMPONENT_STATUS_TBX"
                ("COMPONENT_ID" ASC,
                 "STATUS_KEY" ASC)
                ALLOW REVERSE SCANS;

-- DDL Statements for primary key on Table "GALADM  "."COMPONENT_STATUS_TBX"
ALTER TABLE "GALADM  "."COMPONENT_STATUS_TBX"
        ADD CONSTRAINT "COMPONENT_STATUS_PK" PRIMARY KEY
                ("COMPONENT_ID",
                 "STATUS_KEY");

ALTER TABLE GALADM.COMPONENT_STATUS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.COMPONENT_STATUS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.COMPONENT_STATUS_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.COMPONENT_STATUS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.COMPONENT_STATUS_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
