DELETE FROM GALADM.QI_IMAGE_SECTION_TBX WHERE PART_LOCATION_ID IS NULL;

ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX ALTER COLUMN PART_LOCATION_ID SET NOT NULL;
ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_IMAGE_SECTION_TBX; 

ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX DROP PRIMARY KEY;
DROP INDEX GALADM.QI_IMAGE_SECTION_I1;
CREATE UNIQUE INDEX GALADM.QI_IMAGE_SECTION_I1 ON GALADM.QI_IMAGE_SECTION_TBX (IMAGE_SECTION_ID, PART_LOCATION_ID);
ALTER TABLE GALADM.QI_IMAGE_SECTION_TBX ADD CONSTRAINT QI_IMAGE_SECTION_PK PRIMARY KEY (IMAGE_SECTION_ID, PART_LOCATION_ID);