------------------------------------------------
-- DDL Statements for Table "GALADM  "."AUDIT_LOG_TBX"
------------------------------------------------

DROP TRIGGER GALADM.AUDIT_LOG_TR1;
DROP TRIGGER GALADM.AUDIT_LOG_TR2;
DROP TABLE GALADM.AUDIT_LOG_TBX;

CREATE TABLE GALADM.AUDIT_LOG_TBX
(
	TABLE_NAME            VARCHAR(64) NOT NULL ,
	COLUMN_NAME           VARCHAR(64) NOT NULL ,
	PRIMARY_KEY_VALUE     VARCHAR(286) NOT NULL ,
	ACTUAL_TIMESTAMP      TIMESTAMP NOT NULL ,
	PREVIOUS_VALUE        VARCHAR(256) ,
	CURRENT_VALUE         VARCHAR(256) ,
	UPDATE_REASON         VARCHAR(256) ,
	MAINTENANCE_SCREEN    VARCHAR(64) ,
	SYSTEM				  CHAR(18) ,
	CHANGE_TYPE			  CHAR(18) ,
	CREATE_TIMESTAMP      TIMESTAMP ,
	UPDATE_TIMESTAMP      TIMESTAMP ,
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;


COMMENT ON TABLE GALADM.AUDIT_LOG_TBX IS 'NAQ Audit Log';

CREATE UNIQUE INDEX GALADM.AUDIT_LOG_I1
  ON GALADM.AUDIT_LOG_TBX (TABLE_NAME,COLUMN_NAME,PRIMARY_KEY_VALUE,ACTUAL_TIMESTAMP);

ALTER TABLE GALADM.AUDIT_LOG_TBX 
	ADD CONSTRAINT AUDIT_LOG_PK PRIMARY KEY (TABLE_NAME,COLUMN_NAME,PRIMARY_KEY_VALUE,ACTUAL_TIMESTAMP);
		
ALTER TABLE GALADM.AUDIT_LOG_TBX 
	ADD CONSTRAINT AUDIT_LOG_C1 CHECK 
		(TABLE_NAME = UPPER(TABLE_NAME));	
		
ALTER TABLE GALADM.AUDIT_LOG_TBX 
	ADD CONSTRAINT AUDIT_LOG_C2 CHECK 
		(COLUMN_NAME = UPPER(COLUMN_NAME));	

ALTER TABLE GALADM.AUDIT_LOG_TBX  
	ADD CONSTRAINT AUDIT_LOG_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.AUDIT_LOG_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.AUDIT_LOG_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.AUDIT_LOG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.AUDIT_LOG_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.AUDIT_LOG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;  
  