DROP TRIGGER GALADM.REPAIR_PROCESS_POINT_TR2; 
DROP TRIGGER GALADM.REPAIR_PROCESS_POINT_TR1; 
DROP TABLE GALADM.REPAIR_PROCESS_POINT_TBX;

CREATE TABLE GALADM.REPAIR_PROCESS_POINT_TBX (
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL	DEFAULT ,
  PART_NAME	CHARACTER(32)	NOT NULL	DEFAULT ,
  PART_ID	CHARACTER(5)	NOT NULL	DEFAULT ,
  DEVICE_ID	CHARACTER(16),
  INSTRUCTION_CODE	CHARACTER(3),
  SEQUENCE_NUMBER	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP)
  IN GALTBSREF11 INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.REPAIR_PROCESS_POINT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE UNIQUE INDEX GALADM.REPAIR_PROCESS_POINT_I1 ON GALADM.REPAIR_PROCESS_POINT_TBX
  (PROCESS_POINT_ID, PART_NAME, PART_ID);  

ALTER TABLE GALADM.REPAIR_PROCESS_POINT_TBX
  ADD CONSTRAINT REPAIR_PROCESS_POINT_PK PRIMARY KEY (PROCESS_POINT_ID, PART_NAME, PART_ID);

CREATE TRIGGER GALADM.REPAIR_PROCESS_POINT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.REPAIR_PROCESS_POINT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.REPAIR_PROCESS_POINT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.REPAIR_PROCESS_POINT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;