ALTER TABLE GAL212TBX ADD PLAN_OFF_DATE DATE;
 
DROP TABLE "GALADM  "."SCHEDULE_REP_TBX";
CREATE TABLE "GALADM  "."SCHEDULE_REP_TBX"  (
 (
        SOURCE_PROC_LOC CHARACTER(2) DEFAULT '' NOT NULL,
        DEST_PROC_LOC CHARACTER(2) DEFAULT '' NOT NULL,
        DEST_SPEC_CODE CHARACTER(30), DEFAULT '' NOT NULL,
        SUB_ASSY_PROD_ID_FORMAT VARCHAR(1024) DEFAULT NULL,
        PROD_DATE_OFFSET INTEGER DEFAULT 0 NOT NULL,
        CREATE_TIMESTAMP TIMESTAMP,
        UPDATE_TIMESTAMP TIMESTAMP,
        CONSTRAINT SCHEDULE_REP_PK PRIMARY KEY (SOURCE_PROC_LOC, DEST_PROC_LOC, DEST_SPEC_CODE)
    );
COMMENT ON TABLE SCHEDULE_REP_TBX IS 'Schedule Replication: source/destination process locations, Spec Code (MBPNs), Lot Control Rules Applied.';

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SCHEDULE_REP_TBX_TR1";

CREATE TRIGGER GALADM.SCHEDULE_REP_TBX_TR1 NO CASCADE BEFORE INSERT ON GALADM.SCHEDULE_REP_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "GALADM  "."SCHEDULE_REP_TBX_TR2";

CREATE TRIGGER GALADM.SCHEDULE_REP_TBX_TR2 NO CASCADE BEFORE UPDATE ON GALADM.SCHEDULE_REP_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;