CREATE INDEX GALADM.BLOCK_HISTORY_I1 ON GALADM.BLOCK_HISTORY_TBX
(
   "ACTUAL_TIMESTAMP" ASC
)
ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS
;
COMMIT WORK
;
RUNSTATS ON TABLE "GALADM "."BLOCK_HISTORY_TBX" FOR SAMPLED DETAILED INDEX "GALADM "."BLOCK_HIST_PK"
;
RUNSTATS ON TABLE "GALADM "."BLOCK_HISTORY_TBX" FOR SAMPLED DETAILED INDEX "GALADM "."BLOCK_HISTORY_I1"
;

CREATE INDEX GALADM.HEAD_HISTORY_I1 ON GALADM.HEAD_HISTORY_TBX
(
   "ACTUAL_TIMESTAMP" ASC
)
ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS
;
COMMIT WORK
;
RUNSTATS ON TABLE "GALADM "."HEAD_HISTORY_TBX" FOR SAMPLED DETAILED INDEX "GALADM "."HEAD_HIST_PK"
;
RUNSTATS ON TABLE "GALADM "."HEAD_HISTORY_TBX" FOR SAMPLED DETAILED INDEX "GALADM "."HEAD_HISTORY_I1"
;
