------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_MAPPING_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_MAPPING_COMBINATION_TR1;
DROP TRIGGER GALADM.QI_MAPPING_COMBINATION_TR2;
DROP TABLE GALADM.QI_MAPPING_COMBINATION_TBX;

CREATE TABLE GALADM.QI_MAPPING_COMBINATION_TBX
(
	REGIONAL_DEFECT_COMBINATION_ID  INTEGER NOT NULL ,
	OLD_COMBINATION       VARCHAR(169) NOT NULL ,
	INSPECTION_PART_NAME  VARCHAR(32) NOT NULL DEFAULT '',
	INSPECTION_PART_LOCATION_NAME  VARCHAR(20),
	INSPECTION_PART_LOCATION2_NAME  VARCHAR(20),
	INSPECTION_PART2_NAME  VARCHAR(32),
	INSPECTION_PART2_LOCATION_NAME  VARCHAR(20),
	INSPECTION_PART2_LOCATION2_NAME  VARCHAR(20),
	INSPECTION_PART3_NAME  VARCHAR(32),
	DEFECT_TYPE_NAME      VARCHAR(45),
	DEFECT_TYPE_NAME2     VARCHAR(45),
	OLD_COMBINATION_CODE INTEGER,	
	OLD_INSPECTION_PART_NAME  VARCHAR(32),
	OLD_INSPECTION_PART_LOCATION_NAME  VARCHAR(20),
	OLD_INSPECTION_PART_LOCATION2_NAME  VARCHAR(20),
	OLD_INSPECTION_PART2_NAME  VARCHAR(32),
	OLD_INSPECTION_PART2_LOCATION_NAME  VARCHAR(20),
	OLD_INSPECTION_PART2_LOCATION2_NAME  VARCHAR(20),
	OLD_INSPECTION_PART3_NAME  VARCHAR(32),
	OLD_DEFECT_TYPE_NAME      VARCHAR(45),
	OLD_DEFECT_TYPE_NAME2     VARCHAR(45),	
	PRODUCT_KIND          CHAR(18),	
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_MAPPING_COMBINATION_TBX IS 'NAQ Part Defect Combination Mapping between old and new QICS';

CREATE UNIQUE INDEX GALADM.QI_MAPPING_COMBINATION_I1
  ON GALADM.QI_MAPPING_COMBINATION_TBX (REGIONAL_DEFECT_COMBINATION_ID, OLD_COMBINATION);

ALTER TABLE GALADM.QI_MAPPING_COMBINATION_TBX 
	ADD CONSTRAINT QI_MAPPING_COMBINATION_PK PRIMARY KEY (REGIONAL_DEFECT_COMBINATION_ID, OLD_COMBINATION);
		
ALTER TABLE GALADM.QI_MAPPING_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_MAPPING_COMBINATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_MAPPING_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_MAPPING_COMBINATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_MAPPING_COMBINATION_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  
  
  ------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_OLD_COMBINATION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_OLD_COMBINATION_TR2;
DROP TRIGGER GALADM.QI_OLD_COMBINATION_TR1;
DROP TABLE GALADM.QI_OLD_COMBINATION_TBX;

CREATE TABLE GALADM.QI_OLD_COMBINATION_TBX (
    COMBINATION VARCHAR(169) NOT NULL,
    COMBINATION_CODE INTEGER,
    INSPECTION_PART_NAME  VARCHAR(32) NOT NULL DEFAULT '',
    INSPECTION_PART_LOCATION_NAME  VARCHAR(20),
	INSPECTION_PART_LOCATION2_NAME  VARCHAR(20),
	INSPECTION_PART2_NAME  VARCHAR(32),
	INSPECTION_PART2_LOCATION_NAME  VARCHAR(20),
	INSPECTION_PART2_LOCATION2_NAME  VARCHAR(20),
	INSPECTION_PART3_NAME  VARCHAR(32),
	DEFECT_TYPE_NAME      VARCHAR(45),
	DEFECT_TYPE_NAME2     VARCHAR(45),  
    CREATE_TIMESTAMP TIMESTAMP,
    UPDATE_TIMESTAMP TIMESTAMP)
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_OLD_COMBINATION_TBX IS 'NAQ Old Combination for Mapping';

CREATE UNIQUE INDEX GALADM.QI_OLD_COMBINATION_I1
  ON GALADM.QI_OLD_COMBINATION_TBX (COMBINATION);

ALTER TABLE GALADM.QI_OLD_COMBINATION_TBX 
	ADD CONSTRAINT QI_OLD_COMBINATION_PK PRIMARY KEY (COMBINATION);

ALTER TABLE GALADM.QI_OLD_COMBINATION_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_OLD_COMBINATION_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QI_OLD_COMBINATION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_OLD_COMBINATION_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QI_OLD_COMBINATION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;