ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX DROP PRIMARY KEY;
DROP INDEX GALADM.QI_BOM_QICS_PART_MAPPING_I1;

--check if there is duplicate MAIN_PART_NO 
--select MAIN_PART_NO from GALADM.QI_BOM_QICS_PART_MAPPING_TBX group by MAIN_PART_NO having count(*) > 1;
--if yes, delete the duplicate and re-map again
DELETE FROM GALADM.QI_BOM_QICS_PART_MAPPING_TBX WHERE MAIN_PART_NO IN (SELECT MAIN_PART_NO FROM GALADM.QI_BOM_QICS_PART_MAPPING_TBX GROUP BY MAIN_PART_NO HAVING COUNT(*) > 1);

CREATE UNIQUE INDEX GALADM.QI_BOM_QICS_PART_MAPPING_I1 ON GALADM.QI_BOM_QICS_PART_MAPPING_TBX (MAIN_PART_NO);
ALTER TABLE GALADM.QI_BOM_QICS_PART_MAPPING_TBX ADD CONSTRAINT QI_BOM_QICS_PART_MAPPING_PK PRIMARY KEY(MAIN_PART_NO);

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_CONFIG_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_CONFIG_TR1;
DROP TRIGGER GALADM.QI_STATION_CONFIG_TR2;
DROP TABLE GALADM.QI_STATION_CONFIG_TBX;

CREATE TABLE GALADM.QI_STATION_CONFIG_TBX
(
	PROCESS_POINT_ID      CHAR(16) NOT NULL ,
	PROPERTY_KEY          VARCHAR(64) NOT NULL ,
	PROPERTY_VALUE        VARCHAR(64),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;
	
COMMENT ON TABLE GALADM.QI_STATION_CONFIG_TBX IS 'NAQ Station Configuration';

CREATE UNIQUE INDEX GALADM.QI_STATION_CONFIG_I1
  ON GALADM.QI_STATION_CONFIG_TBX (PROCESS_POINT_ID, PROPERTY_KEY);

ALTER TABLE GALADM.QI_STATION_CONFIG_TBX 
	ADD CONSTRAINT QI_STATION_CONFIG_PK PRIMARY KEY (PROCESS_POINT_ID, PROPERTY_KEY);
		
ALTER TABLE GALADM.QI_STATION_CONFIG_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_CONFIG_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_CONFIG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_CONFIG_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_CONFIG_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
      
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR1;
DROP TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR2;
DROP TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX;

CREATE TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX
(
	PROCESS_POINT_ID      CHAR(16) NOT NULL,
	ENTRY_MODEL			  CHAR(4) NOT NULL,
	DIVISION_ID		      CHAR(16) NOT NULL,
	SEQ					  SMALLINT NOT NULL,
	ENTRY_SCREEN          VARCHAR(40) NOT NULL,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX IS 'NAQ Entry Screen by Station';

CREATE UNIQUE INDEX GALADM.QI_STATION_ENTRY_SCREEN_I1
  ON GALADM.QI_STATION_ENTRY_SCREEN_TBX (PROCESS_POINT_ID, ENTRY_MODEL, DIVISION_ID, SEQ);

ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_SCREEN_PK PRIMARY KEY (PROCESS_POINT_ID, ENTRY_MODEL, DIVISION_ID, SEQ);
	
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_SCREEN_C1 CHECK 
		(ENTRY_SCREEN = UPPER(ENTRY_SCREEN));	
		
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_SCREEN_C2 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX 
	ADD CONSTRAINT QI_STATION_ENTRY_SCREEN_C3 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX  
	ADD CONSTRAINT QI_STATION_ENTRY_SCREEN_C4 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));
		
ALTER TABLE GALADM.QI_STATION_ENTRY_SCREEN_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_ENTRY_SCREEN_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_ENTRY_SCREEN_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
        
        
------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_STATION_UPC_PART_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_STATION_UPC_PART_TR1;
DROP TRIGGER GALADM.QI_STATION_UPC_PART_TR2;
DROP TABLE GALADM.QI_STATION_UPC_PART_TBX;

CREATE TABLE GALADM.QI_STATION_UPC_PART_TBX
(
	PROCESS_POINT_ID      CHAR(16) NOT NULL ,
	MAIN_PART_NO		  CHAR(7) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_STATION_UPC_PART_TBX IS 'NAQ UPC Parts by Station';

CREATE UNIQUE INDEX GALADM.QI_STATION_UPC_PART_I1
  ON GALADM.QI_STATION_UPC_PART_TBX (PROCESS_POINT_ID, MAIN_PART_NO);

ALTER TABLE GALADM.QI_STATION_UPC_PART_TBX 
	ADD CONSTRAINT QI_STATION_UPC_PART_PK PRIMARY KEY (PROCESS_POINT_ID, MAIN_PART_NO);
	
ALTER TABLE GALADM.QI_STATION_UPC_PART_TBX 
	ADD CONSTRAINT QI_STATION_UPC_PART_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_STATION_UPC_PART_TBX  
	ADD CONSTRAINT QI_STATION_UPC_PART_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_STATION_UPC_PART_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_STATION_UPC_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_STATION_UPC_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_STATION_UPC_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_STATION_UPC_PART_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
        
              
             