DROP INDEX GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_I2;

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ADD COLUMN ENTRY_MODEL VARCHAR(32) NOT NULL WITH DEFAULT 'ENTRY MODEL' ;

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_SYSTEM_NAME SET DEFAULT 'EXTERNAL SYSTEM' ;
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_SYSTEM_NAME SET NOT NULL;

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_PART_CODE SET DEFAULT 'EXTERNAL PART';
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_PART_CODE SET NOT NULL;

ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_DEFECT_CODE SET DEFAULT 0;
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ALTER COLUMN EXTERNAL_DEFECT_CODE SET NOT NULL;

CREATE UNIQUE INDEX QI_EXTERNAL_SYSTEM_DEFECT_MAP_I2 ON GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX(
EXTERNAL_SYSTEM_NAME ASC ,
EXTERNAL_PART_CODE ASC ,
EXTERNAL_DEFECT_CODE ASC , 
ENTRY_MODEL ASC )

COMPRESS NO 
INCLUDE NULL KEYS ALLOW REVERSE SCANS;