CREATE TABLE GALADM.GAL125_HIST_TBX (
  INSPECTION_PART_NAME VARCHAR(32) NOT NULL DEFAULT '',
  INSPECTION_PART_LOCATION_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DEFECT_TYPE_NAME VARCHAR(45) NOT NULL DEFAULT '',
  SECONDARY_PART_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DEFECTRESULTID INTEGER NOT NULL DEFAULT 0,
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT '',
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  TWO_PART_PAIR_PART VARCHAR(32) NOT NULL DEFAULT '',
  TWO_PART_PAIR_LOCATION VARCHAR(20) NOT NULL DEFAULT '',
  ASSOCIATE_NO CHARACTER(11),
  SHIFT CHARACTER(2),
  DATE DATE,
  ACTUAL_TIMESTAMP TIMESTAMP,
  DEFECT_STATUS SMALLINT,
  IMAGE_NAME VARCHAR(20),
  RESPONSIBLE_DEPT VARCHAR(32),
  RESPONSIBLE_ZONE VARCHAR(32),
  REPAIR_METHOD_NAME_PLAN CHARACTER(64),
  REPAIR_TIME_PLAN INTEGER,
  REPAIR_ASSOCIATE_NO_PLAN CHARACTER(11),
  REPAIR_ASSOCIATE_NO CHARACTER(11),
  WRITE_UP_DEPARTMENT VARCHAR(32),
  TWO_PART_DEFECT_FLAG SMALLINT,
  IQS_CATEGORY_NAME CHARACTER(32),
  IQS_ITEM_NAME CHARACTER(64),
  REGRESSION_CODE CHARACTER(32),
  POINT_X INTEGER,
  POINT_Y INTEGER,
  ENTRY_DEPT VARCHAR(32),
  OUTSTANDING_FLAG SMALLINT,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  REPAIR_TIMESTAMP TIMESTAMP,
  RESPONSIBLE_LINE VARCHAR(32),
  GDP_DEFECT SMALLINT,
  PART_GROUP_NAME CHARACTER(20),
  CHANGE_ASSOCIATE CHARACTER(11),
  CHANGE_NUMBER VARCHAR(255),
  CHANGE_DESCRIPTION VARCHAR(2048),
  CHANGE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT GAL125_HIST_PK PRIMARY KEY
  (INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECTRESULTID, APPLICATION_ID, PRODUCT_ID, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, CHANGE_TIMESTAMP)
)
  IN GALTBSDAT5
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL125_HIST_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL125_HIST_TBX IS
   'RMT DefectResult History for QICS recording defects to product';

CREATE TRIGGER GALADM.GAL125_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL125_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL125_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL125_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL125_HIST_I1
  ON GALADM.GAL125_HIST_TBX
    ( PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL125_HIST_I2
  ON GALADM.GAL125_HIST_TBX
    ( PRODUCT_ID ASC, ENTRY_DEPT ASC, DEFECT_STATUS ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL125_HIST_I3
  ON GALADM.GAL125_HIST_TBX
    ( DATE ASC, ENTRY_DEPT ASC, DEFECT_STATUS ASC, SHIFT ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL125_HIST_I4
  ON GALADM.GAL125_HIST_TBX
    ( DEFECTRESULTID ASC, PRODUCT_ID ASC, OUTSTANDING_FLAG ASC, ACTUAL_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL125_HIST_I5
  ON GALADM.GAL125_HIST_TBX
    ( APPLICATION_ID ASC, PRODUCT_ID ASC, SHIFT ASC, DATE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL125_HIST_I6
  ON GALADM.GAL125_HIST_TBX
    ( DATE ASC, OUTSTANDING_FLAG ASC, APPLICATION_ID ASC, SHIFT ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;