
CREATE SCHEMA LCVINBOM;

CREATE BUFFERPOOL "LCVINBOM1"  SIZE AUTOMATIC PAGESIZE 4096;

CREATE BUFFERPOOL "LCVINBOMIDX"  SIZE AUTOMATIC PAGESIZE 4096;

CREATE LARGE TABLESPACE "LCVINBOMTBSDAT1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL LCVINBOM1
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;
	 
CREATE LARGE TABLESPACE "LCVINBOMTBSIDX1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL LCVINBOMIDX
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."PART";


CREATE TABLE "LCVINBOM  "."PART"  (
		  "PRODUCT_SPEC_CODE" CHAR(30 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "BASE_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "EFFECTIVE_BEGIN_DATE" DATE NOT NULL , 
		  "EFFECTIVE_END_DATE" DATE NOT NULL , 
		  "DESCRIPTION"  VARCHAR(128 OCTETS) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."PART" IS 'VIN-BOM Contains the LET Systems and Part Numbers for LET BOM';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."PART"

ALTER TABLE "LCVINBOM  "."PART" 
	ADD CONSTRAINT "PART_PK" PRIMARY KEY
		("PRODUCT_SPEC_CODE","LET_SYSTEM_NAME");


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."PART_TR1";

CREATE TRIGGER LCVINBOM.PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."PART_TR2";

CREATE TRIGGER LCVINBOM.PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."MODEL_PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."MODEL_PART";


CREATE TABLE "LCVINBOM  "."MODEL_PART"  (
		  "PRODUCT_SPEC_WILDCARD" CHAR(30 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "STARTING_PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "REFLASH" INTEGER NOT NULL , 
		  "INTERCHANGEABLE" INTEGER NOT NULL , 
		  "SCRAP_PARTS" INTEGER NOT NULL , 
		  "ACTIVE" INTEGER NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."MODEL_PART" IS 'VIN-BOM Rules for updating part number from a design change';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."MODEL_PART"

ALTER TABLE "LCVINBOM  "."MODEL_PART" 
	ADD CONSTRAINT "MODEL_PART_PK" PRIMARY KEY
		("PRODUCT_SPEC_WILDCARD","LET_SYSTEM_NAME","DC_PART_NUMBER");


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_PART_TR1";

CREATE TRIGGER LCVINBOM.MODEL_PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.MODEL_PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."MODEL_PART_TR2";

CREATE TRIGGER LCVINBOM.MODEL_PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.MODEL_PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."LOT_PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."LOT_PART";


CREATE TABLE "LCVINBOM  "."LOT_PART"  (
		  "PRODUCTION_LOT" CHAR(20 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "ACTIVE" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."LOT_PART" IS 'VIN-BOM Part Number Assignment for LET System and Production Lot';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."LOT_PART"

ALTER TABLE "LCVINBOM  "."LOT_PART" 
	ADD CONSTRAINT "LOT_PART_PK" PRIMARY KEY
		("PRODUCTION_LOT","LET_SYSTEM_NAME","DC_PART_NUMBER");


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LOT_PART_TR1";

CREATE TRIGGER LCVINBOM.LOT_PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.LOT_PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LOT_PART_TR2";

CREATE TRIGGER LCVINBOM.LOT_PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.LOT_PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."VIN_PART"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."VIN_PART";


CREATE TABLE "LCVINBOM  "."VIN_PART"  (
		  "PRODUCT_ID" VARCHAR(255 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "SHIP_STATUS" INTEGER NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."VIN_PART" IS 'VIN-BOM Part Number Assignment for LET System and VIN';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."VIN_PART"

ALTER TABLE "LCVINBOM  "."VIN_PART" 
	ADD CONSTRAINT "VIN_PART_PK" PRIMARY KEY
		("PRODUCT_ID","LET_SYSTEM_NAME","DC_PART_NUMBER");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_TR1";

CREATE TRIGGER LCVINBOM.VIN_PART_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.VIN_PART
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_TR2";

CREATE TRIGGER LCVINBOM.VIN_PART_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.VIN_PART
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."VIN_PART_APPROVAL"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."VIN_PART_APPROVAL";


CREATE TABLE "LCVINBOM  "."VIN_PART_APPROVAL"  (
		  "VIN_PART_APPROVAL_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER )  ,
		  "PRODUCT_ID" VARCHAR(255 OCTETS) NOT NULL , 
		  "LET_SYSTEM_NAME" VARCHAR(255 OCTETS) NOT NULL , 
		  "CURRENT_SHIP_STATUS" INTEGER NOT NULL , 
		  "NEW_SHIP_STATUS" INTEGER NOT NULL ,
		  "CURRENT_DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL , 
		  "NEW_DC_PART_NUMBER" CHAR(18 OCTETS) NOT NULL ,
		  "INTERCHANGEABLE" INTEGER NOT NULL , 
		  "REQUEST_ASSOCIATE_NUMBER" CHAR(11 OCTETS) NOT NULL ,
		  "REQUEST_TIMESTAMP" TIMESTAMP NOT NULL ,
		  "APPROVE_ASSOCIATE_NUMBER" CHAR(11 OCTETS) ,
		  "APPROVE_TIMESTAMP" TIMESTAMP ,
		  "APPROVE_STATUS" INTEGER NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."VIN_PART_APPROVAL" IS 'VIN-BOM Approvals to change part number or shipping status';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."VIN_PART_APPROVAL"

ALTER TABLE "LCVINBOM  "."VIN_PART_APPROVAL" 
	ADD CONSTRAINT "VIN_PART_APPROVAL_PK" PRIMARY KEY
		("VIN_PART_APPROVAL_ID");


-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_APPROVAL_TR1";

CREATE TRIGGER LCVINBOM.VIN_PART_APPROVAL_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.VIN_PART_APPROVAL
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."VIN_PART_APPROVAL_TR2";

CREATE TRIGGER LCVINBOM.VIN_PART_APPROVAL_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.VIN_PART_APPROVAL
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."AUDIT_LOG"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."AUDIT_LOG";


CREATE TABLE "LCVINBOM  "."AUDIT_LOG"  (
		  "AUDIT_LOG_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER )  , 
		  "CHANGE_TYPE" VARCHAR(18 OCTETS) NOT NULL , 
		  "TABLE_NAME" VARCHAR(64 OCTETS) NOT NULL , 
		  "PRIMARY_KEY_VALUE" VARCHAR(286 OCTETS) NOT NULL , 
		  "COLUMN_NAME" VARCHAR(128 OCTETS) NOT NULL ,
		  "CURRENT_VALUE" VARCHAR(256 OCTETS) ,
		  "UPDATED_VALUE" VARCHAR(256 OCTETS) ,
		  "ASSOCIATE_NUMBER" CHAR(11 OCTETS) ,
		  "ACTUAL_TIMESTAMP" TIMESTAMP ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."AUDIT_LOG" IS 'VIN-BOM Audit Log of System or User changes';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."AUDIT_LOG"

ALTER TABLE "LCVINBOM  "."AUDIT_LOG" 
	ADD CONSTRAINT "AUDIT_LOG_PK" PRIMARY KEY
		("AUDIT_LOG_ID");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."AUDIT_LOG_TR1";

CREATE TRIGGER LCVINBOM.AUDIT_LOG_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.AUDIT_LOG
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."AUDIT_LOG_TR2";

CREATE TRIGGER LCVINBOM.AUDIT_LOG_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.AUDIT_LOG
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."LET_CATEGORY_CODE"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."LET_CATEGORY_CODE";


CREATE TABLE "LCVINBOM  "."LET_CATEGORY_CODE"  (
		  "CATEGORY_CODE_ID" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER )  ,  
		  "NAME" VARCHAR(255 OCTETS) NOT NULL , 		   
		  "DESCRIPTION" VARCHAR(255 OCTETS) ,
		  "INCLUSIVE" INTEGER NOT NULL ,
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."LET_CATEGORY_CODE" IS 'VIN-BOM LET Categories for Partial Check';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."LET_CATEGORY_CODE"

ALTER TABLE "LCVINBOM  "."LET_CATEGORY_CODE" 
	ADD CONSTRAINT "LET_CATEGORY_CODE_PK" PRIMARY KEY
		("CATEGORY_CODE_ID");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_CATEGORY_CODE_TR1";

CREATE TRIGGER LCVINBOM.LET_CATEGORY_CODE_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.LET_CATEGORY_CODE
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_CATEGORY_CODE_TR2";

CREATE TRIGGER LCVINBOM.LET_CATEGORY_CODE_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.LET_CATEGORY_CODE
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "LCVINBOM  "."LET_PARTIAL_CHECK"
------------------------------------------------
 
DROP TABLE "LCVINBOM  "."LET_PARTIAL_CHECK";


CREATE TABLE "LCVINBOM  "."LET_PARTIAL_CHECK"  (
		  "CATEGORY_CODE_ID" BIGINT NOT NULL , 
		  "LET_INSPECTION_NAME" VARCHAR(255 OCTETS) NOT NULL , 		   
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "LCVINBOMTBSDAT1" INDEX IN "LCVINBOMTBSIDX1"  
		 ORGANIZE BY ROW; 

COMMENT ON TABLE "LCVINBOM  "."LET_PARTIAL_CHECK" IS 'VIN-BOM LET Systems for Partial Check';


-- DDL Statements for Primary Key on Table "LCVINBOM  "."LET_PARTIAL_CHECK"

ALTER TABLE "LCVINBOM  "."LET_PARTIAL_CHECK" 
	ADD CONSTRAINT "LET_PARTIAL_CHECK_PK" PRIMARY KEY
		("CATEGORY_CODE_ID","LET_INSPECTION_NAME");

-------------------------------
-- DDL Statements for Triggers
-------------------------------


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_PARTIAL_CHECK_TR1";

CREATE TRIGGER LCVINBOM.LET_PARTIAL_CHECK_TR1 NO CASCADE BEFORE INSERT ON LCVINBOM.LET_PARTIAL_CHECK
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
SET CURRENT SCHEMA = "GALINST ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALINST";

DROP TRIGGER "LCVINBOM  "."LET_PARTIAL_CHECK_TR2";

CREATE TRIGGER LCVINBOM.LET_PARTIAL_CHECK_TR2 NO CASCADE BEFORE UPDATE ON LCVINBOM.LET_PARTIAL_CHECK
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
