DROP INDEX GALADM.BUILD_ATTRIBUTE_BY_BOM_I1;
DROP TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR2;
DROP TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR1;
DROP TABLE GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX;

CREATE TABLE GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX (
  MODEL_GROUP             CHARACTER(32) NOT NULL,
  PART_NO                 CHARACTER(18) NOT NULL,
  PART_COLOR_CODE         CHARACTER(11) NOT NULL,
  ATTRIBUTE               CHARACTER(32) NOT NULL,
  ATTRIBUTE_VALUE         VARCHAR(512),
  ATTRIBUTE_DESCRIPTION   CHARACTER(32),
  CREATE_TIMESTAMP        TIMESTAMP,
  UPDATE_TIMESTAMP        TIMESTAMP,
  CONSTRAINT BUILD_ATTRIBUTE_BY_BOM_PK PRIMARY KEY
    (MODEL_GROUP, PART_NO, PART_COLOR_CODE, ATTRIBUTE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

COMMENT ON TABLE GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX IS 'RMT BuildAttributeByBom';

CREATE INDEX GALADM.BUILD_ATTRIBUTE_BY_BOM_I1 ON GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX
    ( ATTRIBUTE ASC ) ALLOW REVERSE SCANS COMPRESS NO;

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.BUILD_ATTRIBUTE_BY_BOM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.BUILD_ATTRIBUTE_BY_BOM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
