UPDATE GALADM.GAL206TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.GAL245TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.GAL246TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.MEASUREMENT_SPEC_TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.PART_SPEC_TBX SET PART_NAME = TRIM(PART_NAME);
--NALC:1533
UPDATE GALADM.GAL261TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.EXT_REQUIRED_PART_SPEC_TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.RULE_EXCLUSION_TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.REQUIRED_PARTS_TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.REPAIR_PROCESS_POINT_TBX SET PART_NAME = TRIM(PART_NAME);
UPDATE GALADM.PART_LINK_TBX SET PART_NAME = TRIM(PARENT_PART_NAME);
UPDATE GALADM.PART_LINK_TBX SET PART_NAME = TRIM(CHILD_PART_NAME);