--RGALCDEV-90
SET SCHEMA GALADM;

ALTER TABLE GALADM.GAL111TBX DATA CAPTURE NONE; 
ALTER TABLE GALADM.GAL111TBX ADD COLUMN AUTO_ENABLED SMALLINT NOT NULL DEFAULT 0 CONSTRAINT AUTO_CHECK CHECK (AUTO_ENABLED IN (0,1)) ;
ALTER TABLE GALADM.GAL111TBX DATA CAPTURE CHANGES; 

DROP TRIGGER GALADM.GAL111_TR2;
DROP TRIGGER GALADM.GAL111_TR1;

CREATE TRIGGER GALADM.GAL111_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL111_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL111TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL111TBX;

UPDATE GALADM.GAL111TBX SET AUTO_ENABLED = 1;
