ALTER TABLE GALADM.BLOCK_HISTORY_TBX ADD COLUMN PRODUCTION_DATE DATE; 
ALTER TABLE GALADM.BLOCK_HISTORY_TBX ADD COLUMN ASSOCIATE_NO CHAR(11);

ALTER TABLE GALADM.CONROD_HISTORY_TBX ADD COLUMN PRODUCTION_DATE DATE;
ALTER TABLE GALADM.CONROD_HISTORY_TBX ADD COLUMN ASSOCIATE_NO CHAR(11);

ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX ADD COLUMN PRODUCTION_DATE DATE; 
ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX ADD COLUMN ASSOCIATE_NO CHAR(11);

ALTER TABLE GALADM.HEAD_HISTORY_TBX ADD COLUMN PRODUCTION_DATE DATE; 
ALTER TABLE GALADM.HEAD_HISTORY_TBX ADD COLUMN ASSOCIATE_NO CHAR(11);
