DROP TRIGGER GALADM.TGA3011_TR1;
DROP TRIGGER GALADM.TGA3011_TR2;
DROP TABLE GALADM.TGA3011_TBX;

CREATE TABLE "GALADM"."TGA3011_TBX"
(
   PLAN_CODE char(11) NOT NULL,
   LINE_NUMBER char(2) NOT NULL,
   PLAN_PROC_LOC char(2) NOT NULL,
   ON_OFF_FLAG char(1) NOT NULL,
   PRODUCTION_DATE date NOT NULL,
   DAY_OF_WEEK char(3) NOT NULL,
   WORK_FLAG char(1) NOT NULL,
   WEEK_NUMBER char(6) NOT NULL,
   SHIFT_CODE char(2) NOT NULL,
   CAPACITY int NOT NULL,
   CREATE_DATE date DEFAULT CURRENT DATE NOT NULL,
   ROW_PROCESSED char(1) DEFAULT 'N' NOT NULL,
   CREATE_TIMESTAMP timestamp DEFAULT CURRENT TIMESTAMP,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT TGA3011_PK PRIMARY KEY (PLAN_CODE,LINE_NUMBER,PLAN_PROC_LOC,PRODUCTION_DATE,SHIFT_CODE,CREATE_DATE)
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX TGA3011_I1 ON "GALADM"."TGA3011_TBX"
(
  PLAN_CODE,
  LINE_NUMBER,
  PLAN_PROC_LOC,
  PRODUCTION_DATE,
  SHIFT_CODE,
  CREATE_DATE
)
;

CREATE TRIGGER GALADM.TGA3011_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3011_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TGA3011_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3011_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.TGA3021_TR1;
DROP TRIGGER GALADM.TGA3021_TR2;
DROP TABLE GALADM.TGA3021_TBX;

CREATE TABLE "GALADM"."TGA3021_TBX"
(
   PLAN_CODE char(11) NOT NULL,
   LINE_NUMBER char(2) NOT NULL,
   PLAN_PROC_LOC char(2) NOT NULL,
   DAY_OF_WEEK char(3) NOT NULL,
   VALID_DATE date NOT NULL,
   PERIOD char(3) NOT NULL,
   SHIFT_CODE char(2) NOT NULL,
   LABEL_NAME char(5) NOT NULL,
   WORK_TYPE char(3) NOT NULL,
   WORK_PLAN_FLAG char(1) NOT NULL,
   WORK_START_TIME time NOT NULL,
   WORK_END_TIME time NOT NULL,
   NEXT_DAY char(1) NOT NULL,
   CREATE_DATE date DEFAULT CURRENT DATE NOT NULL,
   ROW_PROCESSED char(1) DEFAULT 'N' NOT NULL,
   CREATE_TIMESTAMP timestamp DEFAULT CURRENT TIMESTAMP,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT TGA3021_PK PRIMARY KEY (PLAN_CODE,LINE_NUMBER,PLAN_PROC_LOC,DAY_OF_WEEK,VALID_DATE,PERIOD,CREATE_DATE)
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX TGA3021_I1 ON "GALADM"."TGA3021_TBX"
(
  PLAN_CODE,
  LINE_NUMBER,
  PLAN_PROC_LOC,
  DAY_OF_WEEK,
  VALID_DATE,
  PERIOD,
  CREATE_DATE
)
;

CREATE TRIGGER GALADM.TGA3021_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3021_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TGA3021_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3021_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.TGA3031_TR1;
DROP TRIGGER GALADM.TGA3031_TR2;
DROP TABLE GALADM.TGA3031_TBX;

CREATE TABLE "GALADM"."TGA3031_TBX"
(
   PLAN_CODE char(11) NOT NULL,
   LINE_NUMBER char(2) NOT NULL,
   PLAN_PROC_LOC char(2) NOT NULL,
   PRODUCTION_DATE date NOT NULL,
   PERIOD char(3) NOT NULL,
   SHIFT_CODE char(2) NOT NULL,
   LABEL_NAME char(5) NOT NULL,
   WORK_TYPE char(3) NOT NULL,
   WORK_PLAN_FLAG char(1) NOT NULL,
   WORK_START_TIME time NOT NULL,
   WORK_END_TIME time NOT NULL,
   NEXT_DAY char(1) NOT NULL,
   CREATE_DATE date DEFAULT CURRENT DATE NOT NULL,
   ROW_PROCESSED char(1) DEFAULT 'N' NOT NULL,
   CREATE_TIMESTAMP timestamp DEFAULT CURRENT TIMESTAMP,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT TGA3031_PK PRIMARY KEY (PLAN_CODE,LINE_NUMBER,PLAN_PROC_LOC,PRODUCTION_DATE,PERIOD,CREATE_DATE)
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX TGA3031_I1 ON "GALADM"."TGA3031_TBX"
(
  PLAN_CODE,
  LINE_NUMBER,
  PLAN_PROC_LOC,
  PRODUCTION_DATE,
  PERIOD,
  CREATE_DATE
)
;

CREATE TRIGGER GALADM.TGA3031_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3031_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TGA3031_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3031_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.TGA3051_TR1;
DROP TRIGGER GALADM.TGA3051_TR2;
DROP TABLE GALADM.TGA3051_TBX;

CREATE TABLE "GALADM"."TGA3051_TBX"
(
   AFAE_FLAG char(1) NOT NULL,
   PLAN_CODE char(11) NOT NULL,
   LINE_NUMBER char(2) NOT NULL,
   PLAN_PROC_LOC char(2) NOT NULL,
   WE_LINE_NUMBER char(2) NOT NULL,
   WE_PLAN_PROC_LOC char(2) NOT NULL,
   PA_LINE_NUMBER char(2) NOT NULL,
   PA_PLAN_PROC_LOC char(2) NOT NULL,
   AFAE_OFF_DATE date NOT NULL,
   PROD_SEQ_NUMBER char(12) NOT NULL,
   DEMAND_TYPE char(2) NOT NULL,
   KD_LOT_NO char(18) NOT NULL,
   MODEL_YEAR_CODE char(1) NOT NULL,
   MODEL_CODE char(3) NOT NULL,
   MODEL_TYPE_CODE char(3) NOT NULL,
   MODEL_OPTION char(3) NOT NULL,
   EXT_COLOUR_CODE char(10) NOT NULL,
   INT_COLOUR_CODE char(2) NOT NULL,
   NO_OF_UNITS int NOT NULL,
   START_VIN_NUMBER char(17) NOT NULL,
   REMAKE_FLAG char(1) NOT NULL,
   Y_N_FLAG char(1) NOT NULL,
   CARRY_I_O_FLAG char(1) NOT NULL,
   NO_OF_UNITS_CICO int NOT NULL,
   PLAN_CREATED char(1) NOT NULL,
   CREATE_DATE date DEFAULT CURRENT DATE NOT NULL,
   ROW_PROCESSED char(1) DEFAULT 'N' NOT NULL,
   CREATE_TIMESTAMP timestamp DEFAULT CURRENT TIMESTAMP,
   UPDATE_TIMESTAMP timestamp,
   CONSTRAINT TGA3051_PK PRIMARY KEY (AFAE_FLAG,PLAN_CODE,LINE_NUMBER,PLAN_PROC_LOC,WE_LINE_NUMBER,WE_PLAN_PROC_LOC,PA_LINE_NUMBER,PA_PLAN_PROC_LOC,AFAE_OFF_DATE,PROD_SEQ_NUMBER,CREATE_DATE)
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX TGA3051_I1 ON "GALADM"."TGA3051_TBX"
(
  AFAE_FLAG,
  PLAN_CODE,
  LINE_NUMBER,
  PLAN_PROC_LOC,
  WE_LINE_NUMBER,
  WE_PLAN_PROC_LOC,
  PA_LINE_NUMBER,
  PA_PLAN_PROC_LOC,
  AFAE_OFF_DATE,
  PROD_SEQ_NUMBER,
  CREATE_DATE
)
;

CREATE TRIGGER GALADM.TGA3051_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3051_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TGA3051_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3051_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER GALADM.TGA3061_TR1;
DROP TRIGGER GALADM.TGA3061_TR2;
DROP TABLE GALADM.TGA3061_TBX;

CREATE TABLE "GALADM"."TGA3061_TBX"
(
   CALENDAR_DATE char(8) PRIMARY KEY NOT NULL,
   DAY_OF_WEEK char(3) NOT NULL,
   WEEK_NUMBER char(6),
   UPDATE_TSTMP timestamp NOT NULL,
   UPDATE_UID char(8),
   CREATE_TIMESTAMP timestamp DEFAULT CURRENT TIMESTAMP,
   UPDATE_TIMESTAMP timestamp
)
IN GALTBSDAT9 INDEX IN GALTBSIDX3 ;

CREATE UNIQUE INDEX TGA3061_I1 ON "GALADM"."TGA3061_TBX"(CALENDAR_DATE)
;

CREATE TRIGGER GALADM.TGA3061_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TGA3061_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TGA3061_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TGA3061_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

