DROP TRIGGER GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX_TR2;
DROP TRIGGER GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX_TR1;
DROP TABLE GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX;

CREATE TABLE GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX (
   VIOS_PLATFORM_ID 	CHARACTER(17) 	NOT NULL,
   ASM_PROC_NO 	VARCHAR(5) 	NOT NULL,
   MBPN_MASK			VARCHAR(30)		NOT NULL,
   MTC_TYPE			    VARCHAR(3)	NOT NULL,
   MTC_MODEL		    VARCHAR(4)		NOT NULL,
   USER_ID	VARCHAR(11)	NOT NULL	DEFAULT '',
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX IS 'MC_VIOS_MASTER_MBPN_MATRIX_TBX is used  to load MBPN Master data';
    
CREATE TRIGGER GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.MC_VIOS_MASTER_MBPN_MATRIX_TBX
  ADD CONSTRAINT MC_VIOS_MASTER_MBPN_MATRIX_TBX PRIMARY KEY 
     (VIOS_PLATFORM_ID, ASM_PROC_NO, MBPN_MASK, MTC_TYPE, MTC_MODEL);