DROP TRIGGER GALADM.PRODUCT_ID_MASK_TR1;
DROP TRIGGER GALADM.PRODUCT_ID_MASK_TR2;
DROP TABLE GALADM.PRODUCT_ID_MASK_TBX;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."PRODUCT_ID_MASK_TBX"
------------------------------------------------
 
CREATE TABLE "GALADM"."PRODUCT_ID_MASK_TBX"  (
		  "PROCESS_POINT_ID" CHAR(16) NOT NULL, 
		  "PRODUCT_TYPE" CHAR(10) NOT NULL , 
		  "PRODUCT_ID_MASK" CHAR(17) NOT NULL , 
		  "PRODUCT_SPEC_CODE" CHAR(30) NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE GALADM.PRODUCT_ID_MASK_TBX IS 'Table to store the Map between productIdMask and productSpecCode for a Prcess point';

-- DDL Statements for Indexes on Table "GALADM  "."PRODUCT_ID_MASK_TBX"

CREATE UNIQUE INDEX "GALADM  "."PRODUCT_ID_MASKI1" ON "GALADM  "."PRODUCT_ID_MASK_TBX" 
		("PROCESS_POINT_ID" ASC,
		 "PRODUCT_TYPE" ASC,
		 "PRODUCT_ID_MASK" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
		
-- DDL Statements for Primary Key on Table "GALADM  "."PRODUCT_ID_MASK_TBX"

ALTER TABLE "GALADM  "."PRODUCT_ID_MASK_TBX" 
	ADD CONSTRAINT "PRODUCT_ID_MASK_PK" PRIMARY KEY
		("PROCESS_POINT_ID",
		 "PRODUCT_TYPE",
		 "PRODUCT_ID_MASK");
		 
-------------------------------
-- DDL Statements for Triggers
-------------------------------

CREATE TRIGGER GALADM.PRODUCT_ID_MASK_TR1 NO CASCADE BEFORE INSERT ON GALADM.PRODUCT_ID_MASK_TBX
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_ID_MASK_TR2 NO CASCADE BEFORE UPDATE ON GALADM.PRODUCT_ID_MASK_TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;