CREATE INDEX "GALADM  "."QI_ENTRY_MODEL_GROUPING_I2" ON "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"
 ("MTC_MODEL" ASC, "ENTRY_MODEL" ASC) ALLOW REVERSE SCANS;

CREATE INDEX "GALADM  "."QI_ENTRY_SCREEN_I2" ON "GALADM  "."QI_ENTRY_SCREEN_TBX"
 ("IS_USED" ASC, "IS_IMAGE" ASC, "IMAGE_NAME" ASC, "ENTRY_MODEL" ASC, "ENTRY_SCREEN" ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_IMAGE_SECTION_I2" ON "GALADM  "."QI_IMAGE_SECTION_TBX"
 ("IMAGE_NAME" ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_IQS_I2" ON "GALADM  "."QI_IQS_TBX"
 ("IQS_QUESTION" ASC, "IQS_QUESTION_NO" ASC, "IQS_CATEGORY" ASC, "IQS_VERSION" ASC) ALLOW REVERSE SCANS;
  
CREATE INDEX "GALADM  "."QI_LOCAL_DEFECT_COMBINATION_I5" ON "GALADM  "."QI_LOCAL_DEFECT_COMBINATION_TBX"
 ("REGIONAL_DEFECT_COMBINATION_ID" ASC, "ENTRY_MODEL" ASC, "ENTRY_SCREEN" ASC, "IS_USED" ASC, "PDDA_RESPONSIBILITY_ID" ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_PART_LOCATION_COMBINATION_I2" ON "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX"
 ("INSPECTION_PART_NAME" ASC, "INSPECTION_PART2_NAME" ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_PART_LOCATION_COMBINATION_I3" ON "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX"
 ("PRODUCT_KIND" ASC) ALLOW REVERSE SCANS ;

CREATE INDEX "GALADM  "."QI_PART_LOCATION_COMBINATION_I4" ON "GALADM  "."QI_PART_LOCATION_COMBINATION_TBX"
 (INSPECTION_PART_LOCATION_NAME ASC , INSPECTION_PART2_LOCATION_NAME ASC, INSPECTION_PART2_LOCATION2_NAME ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_PDDA_RESPONSIBILITY_I4" ON "GALADM  "."QI_PDDA_RESPONSIBILITY_TBX"
 ("VEHICLE_MODEL_CODE" ASC, "MODEL_YEAR" ASC, "UNIT_DESC" ASC, "UNIT_NUMBER" ASC, "PROCESS_NAME" ASC, "PROCESS_NUMBER" ASC) ALLOW REVERSE SCANS;
   
CREATE INDEX "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_I3" ON "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX"
 ("PART_LOCATION_ID" ASC, "IQS_ID" ASC, "DEFECT_TYPE_NAME2" ASC, "DEFECT_TYPE_NAME" ASC, "THEME_NAME" ASC, "REGIONAL_DEFECT_COMBINATION_ID" ASC) ALLOW REVERSE SCANS;
 
CREATE INDEX "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_I4" ON "GALADM  "."QI_REGIONAL_DEFECT_COMBINATION_TBX"
 ("THEME_NAME" ASC, "DEFECT_TYPE_NAME2" ASC, "DEFECT_TYPE_NAME" ASC, "IQS_ID" ASC, "PART_LOCATION_ID" ASC, "REGIONAL_DEFECT_COMBINATION_ID" ASC) ALLOW REVERSE SCANS;

CREATE INDEX "GALADM  "."QI_STATION_ENTRY_SCREEN_I2" on "GALADM  "."QI_STATION_ENTRY_SCREEN_TBX"
 ("ENTRY_SCREEN" ASC) ALLOW REVERSE SCANS;