------------------------------------------------
-- DDL Statements for table "GALADM  "."GAL251TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."GAL251TBX"  (
		  "MODEL_YEAR_CODE" CHAR(1) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_CODE" CHAR(3) NOT NULL WITH DEFAULT ' ' , 
		  "MODEL_TYPE_CODE" CHAR(3) NOT NULL WITH DEFAULT '*' , 
		  "JOURNAL_POSITION" VARCHAR(3) NOT NULL WITH DEFAULT '*' , 
		  "BEARING_TYPE" CHAR(10) NOT NULL WITH DEFAULT ' ' , 
		  "COLUMN_MEASUREMENT" CHAR(1) NOT NULL WITH DEFAULT ' ' , 
		  "ROW_MEASUREMENT" CHAR(1) NOT NULL WITH DEFAULT ' ' , 
		  "UPPER_BEARING" CHAR(30) , 
		  "LOWER_BEARING" CHAR(30) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 DATA CAPTURE CHANGES  
		 IN "GALTBSREF12" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE "GALADM  "."GAL251TBX" IS 'Bearing Matrix Cell';


-- DDL Statements for indexes on Table "GALADM  "."GAL251TBX"

CREATE UNIQUE INDEX "GALADM  "."GAL251I1" ON "GALADM  "."GAL251TBX" 
		("MODEL_YEAR_CODE" ASC,
		 "MODEL_CODE" ASC,
		 "MODEL_TYPE_CODE" ASC,
		 "JOURNAL_POSITION" ASC,
		 "BEARING_TYPE" ASC,
		 "COLUMN_MEASUREMENT" ASC,
		 "ROW_MEASUREMENT" ASC)
		ALLOW REVERSE SCANS;
-- DDL Statements for primary key on Table "GALADM  "."GAL251TBX"

ALTER TABLE "GALADM  "."GAL251TBX" 
	ADD CONSTRAINT "GAL251PK" PRIMARY KEY
		("MODEL_YEAR_CODE",
		 "MODEL_CODE",
		 "MODEL_TYPE_CODE",
		 "JOURNAL_POSITION",
		 "BEARING_TYPE",
		 "COLUMN_MEASUREMENT",
		 "ROW_MEASUREMENT");










-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
create trigger GALADM.GAL251TR1 NO CASCADE BEFORE UPDATE ON GALADM.GAL251TBX
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


COMMIT WORK;

