ALTER TABLE GALADM.GAL251TBX DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL251TBX ALTER COLUMN COLUMN_MEASUREMENT SET DATA TYPE CHAR(2);
ALTER TABLE GALADM.GAL251TBX ALTER COLUMN ROW_MEASUREMENT SET DATA TYPE CHAR(2);

ALTER TABLE GALADM.GAL251TBX DATA CAPTURE CHANGES;
  
REORG TABLE GALADM.GAL251TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL251TBX;
