--SEQ RGAL-9199

------------------------------------------------
-- DDL Statements for Table "GALADM  "."BLOCK_BUILD_RESULTS_HIST_TBX"
------------------------------------------------
 
DROP TABLE GALADM.BLOCK_BUILD_RESULTS_HIST_TBX;

CREATE TABLE GALADM.BLOCK_BUILD_RESULTS_HIST_TBX  (
		  "BLOCK_ID" VARCHAR(17 ) NOT NULL , 
		  "PART_NAME" VARCHAR(32 ) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30 ) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11 ) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_POINT_ID" VARCHAR(16 )) 
		IN GALTBSDAT5 INDEX IN GALTBSDAT3   ;

COMMENT ON TABLE "GALADM  "."BLOCK_BUILD_RESULTS_HIST_TBX" IS 'RMT BlockBuildResultHistory to keep history of block build results data';


-- DDL Statements for Primary Key on Table "GALADM  "."BLOCK_BUILD_RESULTS_HIST_TBX"

ALTER TABLE GALADM.BLOCK_BUILD_RESULTS_HIST_TBX 
	ADD CONSTRAINT BLOCK_BUILD_RESULTS_HIST_PK PRIMARY KEY
		("BLOCK_ID",
		 "PART_NAME",
		 "ACTUAL_TIMESTAMP");

	
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BLOCK_BUILD_RESULTS_HIST_TR1";

CREATE TRIGGER GALADM.BLOCK_BUILD_RESULTS_HIST_TR1 NO CASCADE BEFORE INSERT ON
GALADM.BLOCK_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."BLOCK_BUILD_RESULTS_HIST_TR2";

CREATE TRIGGER GALADM.BLOCK_BUILD_RESULTS_HIST_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.BLOCK_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;



------------------------------------------------
-- DDL Statements for Table "GALADM  "."CONROD_BUILD_RESULTS_HIST_TBX"
------------------------------------------------
 
DROP TABLE GALADM.CONROD_BUILD_RESULTS_HIST_TBX;

CREATE TABLE GALADM.CONROD_BUILD_RESULTS_HIST_TBX  (
		  "CONROD_ID" VARCHAR(17 ) NOT NULL , 
		  "PART_NAME" VARCHAR(32 ) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30 ) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11 ) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_POINT_ID" VARCHAR(16 ))    
		IN GALTBSDAT5 INDEX IN GALTBSDAT3   ;

COMMENT ON TABLE GALADM.CONROD_BUILD_RESULTS_HIST_TBX IS 'RMT ConrodBuildResultHistory to keep history of conrod build results data';


-- DDL Statements for Primary Key on Table "GALADM  "."CONROD_BUILD_RESULTS_HIST_TBX"

ALTER TABLE GALADM.CONROD_BUILD_RESULTS_HIST_TBX 
	ADD CONSTRAINT "CONROD_BUILD_RESULTS_HIST_PK" PRIMARY KEY
		("CONROD_ID",
		 "PART_NAME",
		 "ACTUAL_TIMESTAMP");


-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER GALADM.CONROD_BUILD_RESULTS_HIST_TR1;

CREATE TRIGGER GALADM.CONROD_BUILD_RESULTS_HIST_TR1 NO CASCADE BEFORE INSERT
ON GALADM.CONROD_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."CONROD_BUILD_RESULTS_HIST_TR2";

CREATE TRIGGER GALADM.CONROD_BUILD_RESULTS_HIST_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.CONROD_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;



------------------------------------------------
-- DDL Statements for Table "GALADM  "."CRANKSHAFT_BUILD_RESULTS_HIST_TBX"
------------------------------------------------
 
DROP TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX;

CREATE TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX  (
		  "CRANKSHAFT_ID" VARCHAR(17 ) NOT NULL , 
		  "PART_NAME" VARCHAR(32 ) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30 ) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11 ) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_POINT_ID" VARCHAR(16 ))    
		IN GALTBSDAT5 INDEX IN GALTBSDAT3   ;

COMMENT ON TABLE "GALADM  "."CRANKSHAFT_BUILD_RESULTS_HIST_TBX" IS 'RMT CrankshaftBuildResultHistory to keep history of crankshaft build results data';


-- DDL Statements for Primary Key on Table "GALADM  "."CRANKSHAFT_BUILD_RESULTS_HIST_TBX"

ALTER TABLE GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX 
	ADD CONSTRAINT "CRANKSHAFT_BUILD_RESULTS_HIST_PK" PRIMARY KEY
		("CRANKSHAFT_ID",
		 "PART_NAME",
		 "ACTUAL_TIMESTAMP");
		 

-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."CRANKSHAFT_BUILD_RESULTS_HIST_TR1";

CREATE TRIGGER GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TR1 NO CASCADE BEFORE INSERT
ON GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."CRANKSHAFT_BUILD_RESULTS_HIST_TR2";

CREATE TRIGGER GALADM.CRANKSHAFT_BUILD_RESULTS_HIS_TR2 NO CASCADE BEFORE UPDATE
ON GALADM.CRANKSHAFT_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;



------------------------------------------------
-- DDL Statements for Table "GALADM  "."HEAD_BUILD_RESULTS_HIST_TBX"
------------------------------------------------
 
DROP TABLE GALADM.HEAD_BUILD_RESULTS_HIST_TBX;

CREATE TABLE GALADM.HEAD_BUILD_RESULTS_HIST_TBX  (
		  "HEAD_ID" VARCHAR(17 ) NOT NULL , 
		  "PART_NAME" VARCHAR(32 ) NOT NULL WITH DEFAULT ' ' , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  "RESULT_VALUE" VARCHAR(30 ) , 
		  "INSTALLED_PART_STATUS" INTEGER , 
		  "ASSOCIATE_NO" VARCHAR(11 ) , 
		  "CREATE_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "UPDATE_TIMESTAMP" TIMESTAMP , 
		  "PROCESS_POINT_ID" VARCHAR(16 ))    
		IN GALTBSDAT5 INDEX IN GALTBSDAT3   ;

COMMENT ON TABLE "GALADM  "."HEAD_BUILD_RESULTS_HIST_TBX" IS 'RMT HeadBuildResultHistory to keep history of head build results data';


-- DDL Statements for Primary Key on Table "GALADM  "."HEAD_BUILD_RESULTS_HIST_TBX"

ALTER TABLE "GALADM  "."HEAD_BUILD_RESULTS_HIST_TBX" 
	ADD CONSTRAINT "HEAD_BUILD_RESULTS_HIST_PK" PRIMARY KEY
		("HEAD_ID",
		 "PART_NAME",
		 "ACTUAL_TIMESTAMP");

		 
-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HEAD_BUILD_RESULTS_HIST_TR1";

CREATE TRIGGER GALADM.HEAD_BUILD_RESULTS_HIST_TR1 NO CASCADE BEFORE INSERT ON
GALADM.HEAD_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;


SET CURRENT SCHEMA = "GALADM ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

DROP TRIGGER "GALADM  "."HEAD_BUILD_RESULTS_HIST_TR2";

CREATE TRIGGER GALADM.HEAD_BUILD_RESULTS_HIST_TR2 NO CASCADE BEFORE UPDATE ON
GALADM.HEAD_BUILD_RESULTS_HIST_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;


