ALTER TABLE GALADM.GAL198TBX ADD COLUMN DEFECT_REF_ID BIGINT;
ALTER TABLE GALADM.GAL198_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT;
ALTER TABLE GALADM.GAL185TBX ADD COLUMN DEFECT_REF_ID BIGINT;
ALTER TABLE GALADM.GAL185_HIST_TBX ADD COLUMN DEFECT_REF_ID BIGINT;
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ADD COLUMN IS_QICS_REPAIR_REQD SMALLINT WITH DEFAULT 0;
alter table GALADM.GAL246TBX add column QI_DEFECT_FLAG INTEGER DEFAULT 0;

