DROP TRIGGER GALADM.MC_MDRS_TRAINING_TR2;
DROP TRIGGER GALADM.MC_MDRS_TRAINING_TR1;
DROP TABLE GALADM.MC_MDRS_TRAINING_TBX;

CREATE TABLE GALADM.MC_MDRS_TRAINING_TBX (
   USER_LOGON_ID_NO 	CHARACTER(7)	NOT NULL,
   PROCESS_ID 			INTEGER			NOT NULL,
   MODEL_YEAR_DATE 		DECIMAL(5,1)	NOT NULL,
   MTC_MODEL 			CHARACTER(3)	NOT NULL,
   PLANT_LOC_CODE 		CHAR(1) 		NOT NULL,
   DEPT_CODE 			CHAR(2) 		NOT NULL,
   ENTERED_TSTP			TIMESTAMP		NOT NULL,
   EXTRACT_DATE			TIMESTAMP		NOT NULL,
   KNOWLEDGESTATUS_NO	INTEGER			NOT NULL,
   PROCESS_POINT_ID   	CHARACTER(16),
   ASSOCIATE_NO			CHARACTER(11),
   PDDA_PLATFORM_ID		INTEGER,
   SPEC_CODE_TYPE     	VARCHAR(32),
   SPEC_CODE_MASK     	VARCHAR(30),
   TRAINED				TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_MDRS_TRAINING_PK PRIMARY KEY 
     (USER_LOGON_ID_NO, PROCESS_ID, MODEL_YEAR_DATE, MTC_MODEL,PLANT_LOC_CODE,DEPT_CODE,ENTERED_TSTP, EXTRACT_DATE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_MDRS_TRAINING_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_MDRS_TRAINING_TBX IS 'RMT MC_MDRS_TRAINING is used by Manufacturing Control to cross reference MC_TRAINING_TBX to MDRS TBLKNOWLEDGESTATUS';
    
CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_MDRS_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_MDRS_TRAINING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_MDRS_TRAINING_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


