CREATE TABLE "GALADM"."PRODUCT_SHIPPING_TBX"
(
   PRODUCT_ID char(17) PRIMARY KEY NOT NULL,
   PRODUCT_TYPE char(10) NOT NULL,
   TRAILER_NUMBER char(10),
   DUNNAGE char(10),
   SHIP_DATE date,
   TRAILER_STATUS smallint,
   CREATE_TIMESTAMP timestamp,
   UPDATE_TIMESTAMP timestamp
)
;

CREATE TRIGGER "GALADM"."PRODUCT_SHIPPING_TR1" NO CASCADE BEFORE
INSERT ON "GALADM"."PRODUCT_SHIPPING_TBX" REFERENCING NEW AS A FOR EACH ROW MODE DB2SQL SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PRODUCT_SHIPPING_TR2" NO CASCADE BEFORE
UPDATE ON "GALADM"."PRODUCT_SHIPPING_TBX" REFERENCING NEW AS A FOR EACH ROW MODE DB2SQL SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

-- RGALCDEV-2952
	ALTER TABLE GALADM.GAL158TBX
	  DATA CAPTURE NONE;
	 
	ALTER TABLE GALADM.GAL158TBX
	  ALTER COLUMN SALES_MODEL_OPTION_CODE SET DATA TYPE char(3);
	 
	ALTER TABLE GALADM.GAL158TBX
	  DATA CAPTURE CHANGES;