CREATE TABLE GALADM.FEATURE_POINTS_TBX (
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  FEATURE_SEQ	INTEGER	NOT NULL,
  X_COORDINATE	DOUBLE,
  Y_COORDINATE	DOUBLE,
  Z_COORDINATE	DOUBLE,
  CHILD_FEATURE_ID	VARCHAR(32),
  SPATIAL_REFERENCE_SYSTEM	VARCHAR(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT FEATURE_POINTS_PK PRIMARY KEY
    (FEATURE_ID, FEATURE_SEQ)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.FEATURE_POINTS_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.FEATURE_POINTS_TBX IS
   'RMT FeaturePoint coordinates for visualizing information';

CREATE TRIGGER GALADM.FEATURE_POINTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.FEATURE_POINTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FEATURE_POINTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.FEATURE_POINTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.FEATURE_TBX (
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  FEATURE_TYPE	VARCHAR(32) NOT NULL,
  REFERENCE_ID	VARCHAR(32),
  REFERENCE_TYPE	VARCHAR(32),
  ENABLE_HISTORY	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT FEATURE_PK PRIMARY KEY
    (FEATURE_ID, FEATURE_TYPE)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.FEATURE_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.FEATURE_TBX IS
   'RMT Feature for visualizing information';

CREATE TRIGGER GALADM.FEATURE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.FEATURE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FEATURE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.FEATURE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.LAYER_FEATURES_TBX (
  LAYER_ID	VARCHAR(32)	NOT NULL,
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  VISIBLE	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT LAYER_FEATURES_PK PRIMARY KEY
    (LAYER_ID, FEATURE_ID)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.LAYER_FEATURES_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.LAYER_FEATURES_TBX IS
   'RMT LayerFeatures used to relate Layers to Features';

CREATE TRIGGER GALADM.LAYER_FEATURES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LAYER_FEATURES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LAYER_FEATURES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LAYER_FEATURES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.LAYER_TBX (
  LAYER_ID	VARCHAR(32)	NOT NULL,
  LAYER_TYPE	VARCHAR(32) NOT NULL,
  LAYER_DAO	VARCHAR(128),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  DEFAULT_ZOOM	INTEGER,
  BOUNDARY_LEFT	DOUBLE,
  BOUNDARY_LOWER	DOUBLE,
  BOUNDARY_RIGHT	DOUBLE,
  BOUNDARY_UPPER	DOUBLE,
  CONSTRAINT LAYER_PK PRIMARY KEY
    (LAYER_ID, LAYER_TYPE)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.LAYER_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.LAYER_TBX IS
   'RMT Layer to describe how to display visual information';

CREATE TRIGGER GALADM.LAYER_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LAYER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LAYER_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LAYER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE GALADM.VIEW_TBX (
  VIEW_ID	VARCHAR(32)	NOT NULL,
  LAYER_ID	VARCHAR(32)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT VIEW_PK PRIMARY KEY
  (VIEW_ID, LAYER_ID)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.VIEW_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.VIEW_TBX IS
   'RMT View describes collection of Layers';

CREATE TRIGGER GALADM.VIEW_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.VIEW_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.VIEW_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.VIEW_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;