DROP TRIGGER "GALADM".PUSH_TIMER_STATUS_TR1;
DROP TRIGGER "GALADM".PUSH_TIMER_STATUS_TR2;
DROP TABLE "GALADM".PUSH_TIMER_STATUS_TBX;

CREATE TABLE "GALADM"."PUSH_TIMER_STATUS_TBX" (
  "PROCESS_POINT_ID"	CHARACTER(16)	NOT NULL,
  "TERMINAL_ID"	VARCHAR(32)	NOT NULL,
  "PRODUCT_ID"	VARCHAR(32),
  "OPS_PLANNED"	INTEGER,
  "OPS_COMPLETED" INTEGER,
  "STATUS_IN_MINS"	INTEGER	NOT NULL,
  "LAST_UPDATED"	TIMESTAMP,
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "GALTBSREF11"  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."PUSH_TIMER_STATUS_TBX"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PUSH_TIMER_STATUS_TBX" IS 'Maintains Push timer status from all VIOS clients';

CREATE TRIGGER "GALADM"."PUSH_TIMER_STATUS_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."PUSH_TIMER_STATUS_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PUSH_TIMER_STATUS_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."PUSH_TIMER_STATUS_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE "GALADM"."PUSH_TIMER_STATUS_TBX"
  ADD CONSTRAINT "PUSH_TIMER_STATUS_PK" PRIMARY KEY
    ("PROCESS_POINT_ID", "TERMINAL_ID");




