-- DDL Statements for Indexes on Table "GALADM "."GAL185TBX" 
 
CREATE INDEX "GALADM"."GAL185_I3" ON "GALADM "."GAL185TBX" ("PART_SERIAL_NUMBER" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS COMPRESS NO; 

RUNSTATS ON TABLE "GALADM "."GAL185TBX" FOR SAMPLED DETAILED INDEX "GALADM"."GAL185_I3" ;
 
-- DDL Statements for Indexes on Table "GALADM "."GAL185_HIST_TBX" 
 
CREATE INDEX "GALADM"."GAL185_HIST_TBX_I2" ON "GALADM "."GAL185_HIST_TBX" ("PART_SERIAL_NUMBER" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS COMPRESS NO; 
 
RUNSTATS ON TABLE "GALADM "."GAL185_HIST_TBX" FOR SAMPLED DETAILED INDEX "GALADM"."GAL185_HIST_TBX_I2" ; 