DROP TRIGGER VIOS.PVPMU1_TR1;
DROP TRIGGER VIOS.PVPMU1_TR2;
DROP TABLE VIOS.PVPMU1;

CREATE TABLE VIOS.PVPMU1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  UNIT_NO CHAR(6) NOT NULL ,
  UNIT_SEQ_NO INTEGER NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVPMU1_PK PRIMARY KEY
    (MAINTENANCE_ID, UNIT_NO, UNIT_SEQ_NO))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVPMU1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVPMU1 IS 'RMT VIOS ProcessUnit Table';

CREATE TRIGGER VIOS.PVPMU1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVPMU1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
   
DROP TRIGGER VIOS.PVPPI1_TR1;
DROP TRIGGER VIOS.PVPPI1_TR2;
DROP TABLE VIOS.PVPPI1;

CREATE TABLE VIOS.PVPPI1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  PPE_ID INTEGER NOT NULL ,
  PPE_REQUIRED VARCHAR(200) NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  POTENTIAL_HAZARD VARCHAR(300) NOT NULL WITH DEFAULT '' ,
  PPE_USAGE VARCHAR(500) NOT NULL WITH DEFAULT '',
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVPPI1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, PPE_ID))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;
   
ALTER TABLE VIOS.PVPPI1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVPPI1 IS 'RMT VIOS ProcessPpeImage';

CREATE TRIGGER VIOS.PVPPI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVPPI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER VIOS.PVUPI1_TR1;
DROP TRIGGER VIOS.PVUPI1_TR2;
DROP TABLE VIOS.PVUPI1;

CREATE TABLE VIOS.PVUPI1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  PPE_ID INTEGER NOT NULL ,
  PPE_REQUIRED VARCHAR(200) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  POTENTIAL_HAZARD VARCHAR(300) NOT NULL ,
  PPE_USAGE VARCHAR(500),
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUPI1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, PPE_ID))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUPI1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUPI1 IS 'RMT VIOS UnitPpeImage Table';

CREATE TRIGGER VIOS.PVUPI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUPI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GALADM.MASS_MESSAGE_TR1;
DROP TRIGGER GALADM.MASS_MESSAGE_TR2;
DROP TABLE GALADM.MASS_MESSAGE_TBX;

CREATE TABLE "GALADM"."MASS_MESSAGE_TBX" (
  "PLANT_NAME"	CHARACTER(16)	NOT NULL,
  "DEPARTMENT_ID"	CHARACTER(16)	NOT NULL,
  "LINE_ID"	CHARACTER(16)	NOT NULL,
  "MASS_MESSAGE_TYPE"	SMALLINT	NOT NULL,
  "MASS_MESSAGE"	VARCHAR(255)	NOT NULL,
  "MASS_MESSAGE_SEVERITY"	VARCHAR(25)	NOT NULL,
  "ASSOCIATE_NO"	CHARACTER(11)	NOT NULL,
  "CREATE_TIMESTAMP"	TIMESTAMP	NOT NULL,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "GALTBSDAT6"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."MASS_MESSAGE_TBX"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

ALTER TABLE "GALADM"."MASS_MESSAGE_TBX"
  ADD CONSTRAINT "MASS_MESSAGE_PK" PRIMARY KEY
    ("PLANT_NAME", "DEPARTMENT_ID", "LINE_ID", "MASS_MESSAGE_TYPE");

SET CURRENT SCHEMA = "GALADM";



CREATE UNIQUE INDEX "GALADM"."MASS_MESSAGE_I1"
  ON "GALADM"."MASS_MESSAGE_TBX"
    ( "PLANT_NAME" ASC, "DEPARTMENT_ID" ASC, "LINE_ID" ASC, "MASS_MESSAGE_TYPE" ASC )
  ALLOW REVERSE SCANS;
  
CREATE TRIGGER GALADM.MASS_MESSAGE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MASS_MESSAGE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MASS_MESSAGE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MASS_MESSAGE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;  

DROP TRIGGER VIOS.PVLPR1_TR1;
DROP TRIGGER VIOS.PVLPR1_TR2;
DROP TABLE VIOS.PVLPR1;

CREATE TABLE "VIOS"."PVLPR1" (
  "PROCESS_ID"	INTEGER	NOT NULL,
  "TEAM_ID"	INTEGER	NOT NULL,
  "MPTAG_ID"	INTEGER	NOT NULL,
  "BODY_LOC_NO"	CHARACTER(4)	NOT NULL,
  "ASM_PROC_SEQ_NO"	SMALLINT	NOT NULL,
  "ASM_PROC_NO"	CHARACTER(5)	NOT NULL,
  "ASM_PROC_NAME"	CHARACTER(35)	NOT NULL,
  "EXTRACT_DATE"	TIMESTAMP	NOT NULL,
  "PLANT_LOC_CODE"	CHARACTER(1),
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "VIOSTBSDAT1"
  INDEX IN "VIOSTBSIDX1";

ALTER TABLE "VIOS"."PVLPR1"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "VIOS"."PVLPR1" IS 'RMT VIOS MdrsProcess Table';

ALTER TABLE "VIOS"."PVLPR1"
  ADD CONSTRAINT "PVLPR1_PK" PRIMARY KEY
    ("PROCESS_ID", "TEAM_ID");

CREATE TRIGGER VIOS.PVLPR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLPR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;



DROP TRIGGER VIOS.PVLUN1_TR1;
DROP TRIGGER VIOS.PVLUN1_TR2;
DROP TABLE VIOS.PVLUN1;

CREATE TABLE "VIOS"."PVLUN1" (
  "UNIT_REC_ID"	INTEGER	NOT NULL,
  "UNIT_ID"	INTEGER	NOT NULL,
  "PROCESS_ID"	INTEGER	NOT NULL,
  "TEAM_ID"	INTEGER	NOT NULL,
  "UNIT_SEQ_NO"	SMALLINT	NOT NULL,
  "UNIT_NO"	CHARACTER(6)	NOT NULL,
  "UNIT_OP_DESC_TEXT"	CHARACTER(254)	NOT NULL,
  "JOINT_TYPE"	CHARACTER(1)	NOT NULL,
  "TORQUE_CHAR_VALUE"	CHARACTER(3)	NOT NULL,
  "MAX_TORQUE_VAL_QTY"	DECIMAL(4, 1)	NOT NULL,
  "MIN_TORQUE_VAL_QTY"	DECIMAL(4, 1)	NOT NULL,
  "STATUS"	CHARACTER(8)	NOT NULL,
  "ADDED_DATE"	TIMESTAMP	NOT NULL,
  "ACCEPTED_LOGON_ID"	CHARACTER(8)	NOT NULL,
  "ACCEPTED_DATE"	TIMESTAMP	NOT NULL,
  "MAINT_DATE"	TIMESTAMP	NOT NULL,
  "EXTRACT_DATE"	TIMESTAMP	NOT NULL,
  "WORK_PT_DESC_TEXT"	VARCHAR(500)	NOT NULL,
  "QLTY_PT_DESC_TEXT"	VARCHAR(500)	NOT NULL,
  "PLANT_LOC_CODE"	CHARACTER(1),
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "VIOSTBSDAT1"
  INDEX IN "VIOSTBSIDX1";

ALTER TABLE "VIOS"."PVLUN1"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "VIOS"."PVLUN1" IS 'RMT VIOS MdrsUnit Table';


ALTER TABLE "VIOS"."PVLUN1"
  ADD CONSTRAINT "PVLUN1_PK" PRIMARY KEY
    ("UNIT_REC_ID");


CREATE TRIGGER VIOS.PVLUN1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLUN1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


DROP TRIGGER VIOS.PVUPM1_TR1;
DROP TRIGGER VIOS.PVUPM1_TR2;
DROP TABLE VIOS.PVUPM1;


CREATE TABLE "VIOS"."PVUPM1" (
  "MAINTENANCE_ID"	INTEGER	NOT NULL,
  "PLANT_LOC_CODE"	CHARACTER(1)	NOT NULL,
  "DEPT_CODE"	CHARACTER(2)	NOT NULL,
  "PART_NO"	CHARACTER(18)	NOT NULL,
  "PART_SECTION_CODE"	CHARACTER(3)	NOT NULL,
  "PART_ITEM_NO"	CHARACTER(8)	NOT NULL,
  "MTC_MODEL"	CHARACTER(3)	NOT NULL,
  "MTC_TYPE"	CHARACTER(3)	NOT NULL,
  "MTC_OPTION"	CHARACTER(3)	NOT NULL,
  "PART_QTY"	SMALLINT	NOT NULL,
  "PART_MARKING_NO"	CHARACTER(4)	NOT NULL,
  "TGT_EFF_BEG_DATE"	TIMESTAMP	NOT NULL,
  "PART_EFF_DATE"	TIMESTAMP	NOT NULL,
  "DELIVERY_LOCATION"	CHARACTER(4)	NOT NULL,
  "PART_NAME"	CHARACTER(50)	NOT NULL,
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "VIOSTBSDAT1"
  INDEX IN "VIOSTBSIDX1";

ALTER TABLE "VIOS"."PVUPM1"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "VIOS"."PVUPM1" IS 'RMT VIOS UnitPart Table';

ALTER TABLE "VIOS"."PVUPM1"
  ADD CONSTRAINT "PVUPM1_PK" PRIMARY KEY
    ("MAINTENANCE_ID", "MTC_MODEL", "MTC_TYPE", "MTC_OPTION", "PART_ITEM_NO", "PART_NO", "PART_SECTION_CODE", "PART_QTY", "PART_MARKING_NO", "TGT_EFF_BEG_DATE", "PART_EFF_DATE", "DELIVERY_LOCATION", "PART_NAME");


CREATE TRIGGER VIOS.PVUPM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUPM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
