ALTER TABLE HOLD_ACCESS_TYPE_TBX ADD COLUMN PRODUCT_TYPE VARCHAR(30)
UPDATE HOLD_ACCESS_TYPE_TBX SET PRODUCT_TYPE = '' WHERE product_type IS NULL
ALTER TABLE HOLD_ACCESS_TYPE_TBX ALTER COLUMN PRODUCT_TYPE SET NOT NULL
ALTER TABLE HOLD_ACCESS_TYPE_TBX ALTER COLUMN PRODUCT_TYPE SET DEFAULT ''
ALTER TABLE HOLD_ACCESS_TYPE_TBX DROP CONSTRAINT HOLD_ACCESS_TYPE_PK
Call Sysproc.admin_cmd ('reorg Table HOLD_ACCESS_TYPE_TBX');
ALTER TABLE HOLD_ACCESS_TYPE_TBX ADD CONSTRAINT HOLD_ACCESS_TYPE_PK PRIMARY KEY (TYPE_ID, SECURITY_GRP, PRODUCT_TYPE)
Call Sysproc.admin_cmd ('reorg Table HOLD_ACCESS_TYPE_TBX');