CREATE TABLE GALADM.GAL148TBX (
  DATE_STRING	CHARACTER(6)	NOT NULL	DEFAULT '',
  TIME	CHARACTER(6)	NOT NULL	DEFAULT '',
  SEND_LOCATION	CHARACTER(1)	NOT NULL	DEFAULT '',
  TRAN_TYPE	CHARACTER(2)	NOT NULL	DEFAULT '',
  VIN	CHARACTER(17)	NOT NULL	DEFAULT '',
  SALES_MODEL_CODE	CHARACTER(10)	NOT NULL	DEFAULT '',
  SALES_MODEL_TYPE_CODE	CHARACTER(2)	NOT NULL	DEFAULT '',
  SALES_MODEL_OPTION_CODE	CHARACTER(2)	NOT NULL	DEFAULT '',
  SALES_MODEL_COLOR_CODE	CHARACTER(11)	NOT NULL	DEFAULT '',
  ENGINE_NO	CHARACTER(7)	NOT NULL	DEFAULT '',
  KEY_NO	CHARACTER(7)	NOT NULL	DEFAULT '',
  CIC_ISSU_DATA	CHARACTER(6)	NOT NULL	DEFAULT '',
  ADC_PROCESS_CODE	CHARACTER(3)	NOT NULL	DEFAULT '',
  PRODUCTION_LINE_NO	CHARACTER(1)	NOT NULL	DEFAULT '',
  PRODUCTION_DATE_STRING	CHARACTER(6)	NOT NULL	DEFAULT '',
  PRODUCTION_SEQUENCE	CHARACTER(3)	NOT NULL	DEFAULT '',
  PRODUCTION_SUFFIX	CHARACTER(2)	NOT NULL	DEFAULT '',
  KD_LINE_NO	CHARACTER(1)	NOT NULL	DEFAULT '',
  KD_DATE	CHARACTER(4)	NOT NULL	DEFAULT '',
  KD_SEQ_NO	CHARACTER(3)	NOT NULL	DEFAULT '',
  KD_SUFFIX	CHARACTER(1)	NOT NULL	DEFAULT '',
  PRICE_STRING	CHARACTER(9)	NOT NULL	DEFAULT '',
  VEHICLE_UNIT_ID	CHARACTER(10),
  VEHICLE_COMM_UNIT	CHARACTER(11),
  SENDED_FLG	CHARACTER(1)	NOT NULL	DEFAULT '',
  PRINTED_FLAG	CHARACTER(1)	DEFAULT 'N',
  AF_OFF_DATE	CHARACTER(6)	NOT NULL,
  CCC_REG_NBR	CHARACTER(12)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL148_PK PRIMARY KEY
    (VIN, SENDED_FLG)
) 
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL148TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL148TBX IS 'RMT OIF 50A Processing';

CREATE TRIGGER GALADM.GAL148_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL148TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL148_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL148TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


CREATE TABLE GALADM.TEAM_ROTATION_TBX (
  LINE_NO CHARACTER(2) NOT NULL DEFAULT '',
  PROCESS_LOCATION CHARACTER(2) NOT NULL DEFAULT '',
  PLANT_CODE CHARACTER(4) NOT NULL DEFAULT '',
  PRODUCTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  SHIFT CHARACTER(2) NOT NULL DEFAULT '',
  TEAM	VARCHAR(10)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT TEAM_ROTATION_PK PRIMARY KEY 
     (LINE_NO, PROCESS_LOCATION, PLANT_CODE, PRODUCTION_DATE, SHIFT, TEAM)
) 
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;
  
ALTER TABLE GALADM.TEAM_ROTATION_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.TEAM_ROTATION_TBX IS 'RMT used to track TEAM shift rotation';
    
CREATE TRIGGER GALADM.TEAM_ROTATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.TEAM_ROTATION_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TEAM_ROTATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.TEAM_ROTATION_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
