create  table GALADM.MC_VIOS_MASTER_OP_MEAS_PROC_TEMP (
	"VIOS_PLATFORM_ID" CHARACTER(17) NOT NULL ,
	"UNIT_NO" VARCHAR(6) NOT NULL ,
	"PART_TYPE" VARCHAR(32) NOT NULL ,
	"OP_MEAS_SEQ_NUM" INTEGER NOT NULL ,
	"DEVICE_ID" CHARACTER(32),
	"DEVICE_MSG" CHARACTER(32),
	"MIN_LIMIT" DOUBLE,
	"MAX_LIMIT" DOUBLE,
	"MEAS_MAX_ATTEMPTS" INTEGER )
IN "GALTBSREF12" INDEX IN "GALTBSIDX4";

insert into GALADM.MC_VIOS_MASTER_OP_MEAS_PROC_TEMP(VIOS_PLATFORM_ID, UNIT_NO, PART_TYPE, OP_MEAS_SEQ_NUM, DEVICE_ID, DEVICE_MSG, MIN_LIMIT, MAX_LIMIT, MEAS_MAX_ATTEMPTS) SELECT M.VIOS_PLATFORM_ID, M.UNIT_NO, M.PART_TYPE, M.OP_MEAS_SEQ_NUM, MAX(M.DEVICE_ID), MAX(M.DEVICE_MSG), MAX(M.MIN_LIMIT), MAX(M.MAX_LIMIT), MAX(M.MEAS_MAX_ATTEMPTS) FROM GALADM.MC_VIOS_MASTER_OP_MEAS_TBX M GROUP BY M.VIOS_PLATFORM_ID, M.UNIT_NO, M.PART_TYPE, M.OP_MEAS_SEQ_NUM;

delete from (select * from GALADM.MC_VIOS_MASTER_OP_MEAS_TBX fetch first 10000 rows only);

insert into GALADM.MC_VIOS_MASTER_OP_MEAS_TBX(VIOS_PLATFORM_ID, UNIT_NO, PART_NO, PART_SECTION_CODE, PART_ITEM_NO, PART_TYPE, OP_MEAS_SEQ_NUM, DEVICE_ID, DEVICE_MSG, MIN_LIMIT, MAX_LIMIT, MEAS_MAX_ATTEMPTS, MEAS_CHECK, MEAS_TIME) select VIOS_PLATFORM_ID, UNIT_NO, '', '', '', PART_TYPE, OP_MEAS_SEQ_NUM, DEVICE_ID, DEVICE_MSG, MIN_LIMIT, MAX_LIMIT, MEAS_MAX_ATTEMPTS, 0, 0 from GALADM.MC_VIOS_MASTER_OP_MEAS_PROC_TEMP;

drop table GALADM.MC_VIOS_MASTER_OP_MEAS_PROC_TEMP;

alter table GALADM.MC_VIOS_MASTER_OP_MEAS_TBX drop PRIMARY KEY;

drop index GALADM.MC_VIOS_MASTER_OP_MEAS_I1;

CREATE UNIQUE INDEX GALADM.MC_VIOS_MASTER_OP_MEAS_I1 ON GALADM.MC_VIOS_MASTER_OP_MEAS_TBX ("VIOS_PLATFORM_ID" ASC, "UNIT_NO" ASC, "PART_TYPE" ASC, "OP_MEAS_SEQ_NUM" ASC) INCLUDE ("CREATE_TIMESTAMP" , "UPDATE_TIMESTAMP" );

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX ADD CONSTRAINT MC_VIOS_MASTER_OP_MEAS_PK PRIMARY KEY (VIOS_PLATFORM_ID, UNIT_NO, PART_TYPE, OP_MEAS_SEQ_NUM);

alter table GALADM.MC_VIOS_MASTER_OP_MEAS_TBX drop column PART_NO;

alter table GALADM.MC_VIOS_MASTER_OP_MEAS_TBX drop column PART_SECTION_CODE;

alter table GALADM.MC_VIOS_MASTER_OP_MEAS_TBX drop column PART_ITEM_NO;

ALTER TABLE GALADM.MC_VIOS_MASTER_OP_MEAS_TBX  ADD USER_ID CHAR(11) NOT NULL WITH DEFAULT '';

reorg table GALADM.MC_VIOS_MASTER_OP_MEAS_TBX;