DROP TRIGGER GALADM.FEATURE_TYPE_TR1;
DROP TRIGGER GALADM.FEATURE_TYPE_TR2;
DROP TABLE GALADM.FEATURE_TYPE_TBX;

CREATE TABLE GALADM.FEATURE_TYPE_TBX (
  FEATURE_TYPE	VARCHAR(32) NOT NULL,
  FEATURE_SHAPE VARCHAR(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT FEATURE_TYPE_PK PRIMARY KEY
    (FEATURE_TYPE)
) 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

CREATE TRIGGER GALADM.FEATURE_TYPE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.FEATURE_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FEATURE_TYPE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.FEATURE_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


ALTER TABLE GALADM.GAL214TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.GAL214TBX ADD FEATURE_TYPE VARCHAR(32);

ALTER TABLE GALADM.WSCLIENTS_TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.WSCLIENTS_TBX ADD FEATURE_TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL185TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.GAL185TBX ADD FEATURE_TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL185_HIST_TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.GAL185_HIST_TBX ADD FEATURE_TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL198TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.GAL198TBX ADD FEATURE_TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL198_HIST_TBX ADD FEATURE_ID VARCHAR(32);
ALTER TABLE GALADM.GAL198_HIST_TBX ADD FEATURE_TYPE VARCHAR(32);