--Changes to add the MBPN and HES Color received in the GPP306. 
ALTER TABLE GALADM.GAL212TBX DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL212TBX ADD COLUMN MBPN VARCHAR(18) ADD COLUMN HES_COLOR VARCHAR(11);

ALTER TABLE GALADM.GAL212TBX DATA CAPTURE CHANGES;

DROP TRIGGER GALADM.GAL212_TR1;
DROP TRIGGER GALADM.GAL212_TR2;

CREATE TRIGGER GALADM.GAL212_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL212TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL212_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL212TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

-- Dunnage support for Pulleys(SubProduct)
set schema galadm;

ALTER TABLE GALADM.SUB_PRODUCT_TBX DATA CAPTURE NONE; 
ALTER TABLE GALADM.SUB_PRODUCT_TBX ADD COLUMN DUNNAGE VARCHAR(12);
ALTER TABLE GALADM.SUB_PRODUCT_TBX DATA CAPTURE CHANGES;  

REORG TABLE  GALADM.SUB_PRODUCT_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.SUB_PRODUCT_TBX;

CREATE INDEX GALADM.SUB_PRODUCT_I1 ON GALADM.SUB_PRODUCT_TBX ( DUNNAGE ) ALLOW REVERSE SCANS COMPRESS NO;

REORG TABLE  GALADM.SUB_PRODUCT_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.SUB_PRODUCT_TBX;
