ALTER TABLE GALADM.MBPN_PRODUCT_TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.MBPN_PRODUCT_TBX
ADD COLUMN DEFECT_STATUS SMALLINT
;

ALTER TABLE GALADM.MBPN_PRODUCT_TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.MBPN_PRODUCT_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.MBPN_PRODUCT_TBX;