CREATE TABLE GALADM.SEQUENCE_TBX (
  SEQUENCE_ID_NAME      VARCHAR(64)     NOT NULL,
  START_SEQ     INTEGER NOT NULL,
  END_SEQ       INTEGER NOT NULL,
  CURRENT_SEQ   INTEGER NOT NULL,
  INCREMENT_VALUE       INTEGER DEFAULT 1,
  DESCRIPTION   VARCHAR(255),
  CREATE_TIMESTAMP      TIMESTAMP,
  UPDATE_TIMESTAMP      TIMESTAMP
  )
  IN GALTBSREF11 INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.SEQUENCE_TBX
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.SEQUENCE_TBX IS 'RMT Sequence';

ALTER TABLE GALADM.SEQUENCE_TBX
  ADD CONSTRAINT SEQUENCE_PK PRIMARY KEY
    (SEQUENCE_ID_NAME);

CREATE TRIGGER GALADM.SEQUENCE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.SEQUENCE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

insert into GALADM.SEQUENCE_TBX
select 'AFON_SEQUENCE' as sequence_id_name, '1' as start_seq, '9999' as end_seq, current_sequence_number, '1' as increment_value,'afon_sequence' as description,current_timestamp, current_timestamp from galadm.gal103tbx