-- Populate table MC_VIOS_MASTER_PLATFORM_TBX
INSERT INTO GALADM.MC_VIOS_MASTER_PLATFORM_TBX (VIOS_PLATFORM_ID, PLANT_LOC_CODE, DEPT_CODE, MODEL_YEAR_DATE, PROD_SCH_QTY, PROD_ASM_LINE_NO, VEHICLE_MODEL_CODE) 
(select distinct
p.PLANT_LOC_CODE||p.DEPT_CODE||SUBSTR(DIGITS(p.PROD_SCH_QTY),1,4)||'.'||SUBSTR(DIGITS(p.PROD_SCH_QTY),5)||p.PROD_ASM_LINE_NO||p.VEHICLE_MODEL_CODE||SUBSTR(DIGITS(p.MODEL_YEAR_DATE),1,4)||'.'||SUBSTR(DIGITS(p.MODEL_YEAR_DATE),5),
p.PLANT_LOC_CODE, p.DEPT_CODE, p.MODEL_YEAR_DATE, p.PROD_SCH_QTY, p.PROD_ASM_LINE_NO, p.VEHICLE_MODEL_CODE 
from galadm.MC_PDDA_PLATFORM_TBX p where p.DEPRECATED is null);


-- Populate table MC_VIOS_MASTER_ASM_PROC_TBX
INSERT INTO GALADM.MC_VIOS_MASTER_ASM_PROC_TBX (VIOS_PLATFORM_ID, ASM_PROC_NO, PROCESS_POINT_ID, PROCESS_SEQ_NUM)
(select  
p.PLANT_LOC_CODE||p.DEPT_CODE||SUBSTR(DIGITS(p.PROD_SCH_QTY),1,4)||'.'||SUBSTR(DIGITS(p.PROD_SCH_QTY),5)||p.PROD_ASM_LINE_NO||p.VEHICLE_MODEL_CODE||SUBSTR(DIGITS(p.MODEL_YEAR_DATE),1,4)||'.'||SUBSTR(DIGITS(p.MODEL_YEAR_DATE),5),
p.ASM_PROC_NO, p.PROCESS_POINT_ID, p.PROCESS_SEQ_NUM
from galadm.MC_PDDA_PLATFORM_TBX p where p.DEPRECATED is null 
and p.APPROVED IN (
select  MAX(pp.APPROVED)
from galadm.MC_PDDA_PLATFORM_TBX pp where pp.DEPRECATED is null 
GROUP BY pp.PLANT_LOC_CODE, pp.DEPT_CODE, pp.MODEL_YEAR_DATE, pp.PROD_SCH_QTY, pp.PROD_ASM_LINE_NO, pp.VEHICLE_MODEL_CODE, pp.ASM_PROC_NO HAVING MAX(pp.APPROVED) IS NOT NULL)
union
select  
up.PLANT_LOC_CODE||up.DEPT_CODE||SUBSTR(DIGITS(up.PROD_SCH_QTY),1,4)||'.'||SUBSTR(DIGITS(up.PROD_SCH_QTY),5)||up.PROD_ASM_LINE_NO||up.VEHICLE_MODEL_CODE||SUBSTR(DIGITS(up.MODEL_YEAR_DATE),1,4)||'.'||SUBSTR(DIGITS(up.MODEL_YEAR_DATE),5),
up.ASM_PROC_NO, up.PROCESS_POINT_ID, up.PROCESS_SEQ_NUM
from galadm.MC_PDDA_PLATFORM_TBX up where up.DEPRECATED is null 
and up.CREATE_TIMESTAMP IN (
select  MAX(upp.CREATE_TIMESTAMP)
from galadm.MC_PDDA_PLATFORM_TBX upp where upp.DEPRECATED is null 
GROUP BY upp.PLANT_LOC_CODE, upp.DEPT_CODE, upp.MODEL_YEAR_DATE, upp.PROD_SCH_QTY, upp.PROD_ASM_LINE_NO, upp.VEHICLE_MODEL_CODE, upp.ASM_PROC_NO HAVING MAX(upp.APPROVED) IS NULL));

-- ***Update PROCESS_SEQ_NUM Column in MC_STRUCTURE_TBX***

-- Execute Procedure
CALL GALADM.MC_STRUCTURE_MIGRATION;