ALTER TABLE VIOS.PVMSC1 
	ADD CONSTRAINT PVUMX1_PVMSC1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUMT1 
	ADD CONSTRAINT PVUMX1_PVUMT1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVCFU1 
	ADD CONSTRAINT PVCFR1_PVCFU1_FK1 FOREIGN KEY
		(CHANGE_FORM_ID)
	REFERENCES VIOS.PVCFR1
		(CHANGE_FORM_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVCFU1 
	ADD CONSTRAINT PVPMX1_PVCFU1_FK1 FOREIGN KEY
		(APVD_PROC_MAINT_ID)
	REFERENCES VIOS.PVPMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVCFU1 
	ADD CONSTRAINT PVUMX1_PVCFU1_FK1 FOREIGN KEY
		(APVD_UNIT_MAINT_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUMM1 
	ADD CONSTRAINT PVUMX1_PVUMM1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUML1 
	ADD CONSTRAINT PVUMX1_PVUML1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUPM1 
	ADD CONSTRAINT PVUMX1_PVUPM1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVPMU1 
	ADD CONSTRAINT PVPMX1_PVPMU1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVPMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVMAL1 
	ADD CONSTRAINT PVUMX1_PVMAL1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVMPR1 
	ADD CONSTRAINT PVUMX1_PVMPR1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUMC1 
	ADD CONSTRAINT PVUMX1_PVUMC1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUMQ1 
	ADD CONSTRAINT PVUMX1_PVUMQ1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUWX1 
	ADD CONSTRAINT PVUMX1_PVUWX1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVMPC1 
	ADD CONSTRAINT PVUMX1_PVMPC1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVMRP1 
	ADD CONSTRAINT PVUMX1_PVMRP1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVUPI1 
	ADD CONSTRAINT PVUMX1_PVUPI1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVUMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE VIOS.PVPPI1 
	ADD CONSTRAINT PVPMX1_PVPPI1_FK1 FOREIGN KEY
		(MAINTENANCE_ID)
	REFERENCES VIOS.PVPMX1
		(MAINTENANCE_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;