ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX DROP COLUMN ALL_MODELS;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX DROP COLUMN ALL_DEPARTMENTS;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_ENTRY_SCREEN_TBX;

ALTER TABLE GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX ADD IQS_ID INTEGER;

ALTER TABLE GALADM.QI_REGIONAL_DEFECT_COMBINATION_TBX ADD THEME_NAME VARCHAR(32);

