ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX ADD COLUMN STATUS INTEGER DEFAULT 0;
ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX ADD COLUMN CONTAINER_ID	CHAR(10);
ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX ADD COLUMN PRODUCT_SPEC_CODE	CHAR(22);

ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX ALTER COLUMN PRODUCTION_LOT SET NOT NULL;
ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX DATA CAPTURE CHANGES;

ALTER TABLE GALADM.SUB_PRODUCT_SHIPPING_DETAIL_TBX 
	ADD PRIMARY KEY (KD_LOT_NUMBER, PRODUCTION_LOT,SUB_ID,PRODUCT_SEQ_NO);