DROP TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1;
DROP TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2;
DROP TABLE VIOS.TBLKNOWLEDGESTATUS;

CREATE TABLE VIOS.TBLKNOWLEDGESTATUS  (
  USER_LOGON_ID_NO CHAR(7) NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  MTC_MODEL CHAR(3) NOT NULL ,
  PROCESS_NO CHAR(5) NOT NULL ,
  PROCLINENO CHAR(1) NOT NULL ,
  PROCTEAM CHAR(4) NOT NULL ,
  PROCDESC CHAR(35) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  KNOWLEDGESTATUS_NO INTEGER NOT NULL ,
  ENTEREDBY_UID CHAR(7) NOT NULL ,
  ENTERED_TSTP TIMESTAMP NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  KNOWLEDGE_NOTE_TEXT VARCHAR(250) ,
  PRODRATE INTEGER,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLKNOWLEDGESTATUS_PK PRIMARY KEY
    (USER_LOGON_ID_NO,
     PROCESS_ID,
     MODEL_YEAR_DATE,
     MTC_MODEL,
     ENTERED_TSTP,
     EXTRACT_DATE,
     PLANT_LOC_CODE,
     DEPT_CODE)
)
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLKNOWLEDGESTATUS
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLKNOWLEDGESTATUS IS 'RMT VIOS TBLKNOWLEDGESTATUS';

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I1 ON VIOS.TBLKNOWLEDGESTATUS
(USER_LOGON_ID_NO ASC,
 PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)
COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I2 ON VIOS.TBLKNOWLEDGESTATUS
(PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)
COMPRESS NO ALLOW REVERSE SCANS;

DROP TRIGGER VIOS.TBLROTATION_TR1;
DROP TRIGGER VIOS.TBLROTATION_TR2;
DROP TABLE VIOS.TBLROTATION;

CREATE TABLE VIOS.TBLROTATION  (
  ROTATEREC_NO INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  PCAREA_ID INTEGER NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  TEAM_GROUP_ID INTEGER NOT NULL ,
  RECORDDATE TIMESTAMP NOT NULL ,
  RECORDSHIFT SMALLINT NOT NULL ,
  RECORDQTR SMALLINT NOT NULL ,
  MPTAG_NO INTEGER NOT NULL ,
  TAG_GROUP_ID INTEGER NOT NULL ,
  USER_LOGON_ID_NO CHAR(7) NOT NULL ,
  PAIRTYPE SMALLINT NOT NULL ,
  ENTEREDBY_UID CHAR(7) NOT NULL ,
  ENTERED_TSTP TIMESTAMP NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  ERGOTYPE CHAR(1) ,
  COMMENT VARCHAR(250) ,
  REASONCODE SMALLINT,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLROTATION_PK PRIMARY KEY
    (ROTATEREC_NO, PLANT_LOC_CODE, DEPT_CODE, ENTERED_TSTP, EXTRACT_DATE))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLROTATION
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLROTATION IS 'RMT VIOS TBLROTATION';

CREATE TRIGGER VIOS.TBLROTATION_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLROTATION_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.TBLROTATION_I1 ON VIOS.TBLROTATION
(PCAREA_ID ASC,
 TEAM_NO ASC,
 RECORDDATE ASC,
 USER_LOGON_ID_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.TBLROTATION_I2 ON VIOS.TBLROTATION
(MPTAG_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;


DROP TRIGGER VIOS.TBLROTATION_PROCESS_TR1;
DROP TRIGGER VIOS.TBLROTATION_PROCESS_TR2;
DROP TABLE VIOS.TBLROTATION_PROCESS;

CREATE TABLE VIOS.TBLROTATION_PROCESS  (
  ROTATION_PROCESS_ID INTEGER NOT NULL ,
  ROTATEREC_NO INTEGER NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  ASM_PROC_NO CHAR(5) NOT NULL ,
  ASM_PROC_NAME CHAR(35) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  VMC_DESCRIPTION CHAR(35) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY INTEGER NOT NULL ,
  EFF_BEG_DATE TIMESTAMP NOT NULL ,
  EFF_END_DATE TIMESTAMP NOT NULL ,
  PROCESS_STATUS SMALLINT NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLROTATION_PROCESS_PK PRIMARY KEY
    (ROTATEREC_NO,
     PROCESS_ID,
     PLANT_LOC_CODE,
     DEPT_CODE,
     EXTRACT_DATE))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLROTATION_PROCESS
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLROTATION_PROCESS IS 'RMT VIOS TBLROTATION_PROCESS';

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

COMPRESS NO ALLOW REVERSE SCANS;