ALTER TABLE GALADM.PRODUCT_TYPE_TBX ADD PRODUCT_KIND CHAR(18);

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_MODEL_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_MODEL_TR1;
DROP TRIGGER GALADM.QI_ENTRY_MODEL_TR2;
DROP TABLE GALADM.QI_ENTRY_MODEL_TBX;

CREATE TABLE GALADM.QI_ENTRY_MODEL_TBX
(
	ENTRY_MODEL           CHAR(4) NOT NULL ,
	ENTRY_MODEL_DESCRIPTION  VARCHAR(32),
	PRODUCT_TYPE          CHAR(10),
	ACTIVE                SMALLINT,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_MODEL_TBX IS 'NAQ Entry Model';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_MODEL_I1
  ON GALADM.QI_ENTRY_MODEL_TBX (ENTRY_MODEL);

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_PK PRIMARY KEY (ENTRY_MODEL);
	
ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_C1 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX  
	ADD CONSTRAINT QI_ENTRY_MODEL_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_MODEL_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  

------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_ENTRY_MODEL_GROUPING_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR1;
DROP TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR2;
DROP TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX;

CREATE TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX
(
	ENTRY_MODEL           CHAR(4) NOT NULL ,
	MTC_MODEL             CHAR(4) NOT NULL ,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX IS 'NAQ Entry Model Grouping';

CREATE UNIQUE INDEX GALADM.QI_ENTRY_MODEL_GROUPING_I1
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX (ENTRY_MODEL, MTC_MODEL);

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_PK PRIMARY KEY (ENTRY_MODEL, MTC_MODEL);
	
ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C1 CHECK 
		(ENTRY_MODEL = UPPER(ENTRY_MODEL));	
		
ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C2 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX  
	ADD CONSTRAINT QI_ENTRY_MODEL_GROUPING_C3 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_ENTRY_MODEL_GROUPING_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_ENTRY_MODEL_GROUPING_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_ENTRY_MODEL_GROUPING_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

