
------------------------------------------------
-- DDL Statements for table VIOS.TRAINING_PROCESS
------------------------------------------------
 
DROP TABLE VIOS.TRAINING_PROCESS;
CREATE TABLE VIOS.TRAINING_PROCESS  (
		  PROCESS_ID BIGINT NOT NULL , 
		  PROCESS_NO CHAR(5) NOT NULL , 
		  LINE_NUM SMALLINT , 
		  TEAM_ID INTEGER , 
		  PROCESS_DESC VARCHAR(35) NOT NULL , 
		  BODY_LOC_NO CHAR(4) NOT NULL , 
		  LAST_UPDATED_BY CHAR(7) NOT NULL , 
		  LAST_UPDATED_DATE TIMESTAMP NOT NULL , 
		  PROCESSID INTEGER , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.TRAINING_PROCESS

ALTER TABLE VIOS.TRAINING_PROCESS 
	ADD CONSTRAINT TRAINING_PROCESS_PK PRIMARY KEY
		(PROCESS_ID,
		 PLANT_LOC_CODE,
		 DEPT_CODE,
		 LAST_UPDATED_DATE,
		 EXTRACT_DATE);



------------------------------------------------
-- DDL Statements for table VIOS.TRAINING_STATUS
------------------------------------------------
 
DROP TABLE VIOS.TRAINING_STATUS;
CREATE TABLE VIOS.TRAINING_STATUS  (
		  TRAINING_STATUS_ID BIGINT NOT NULL , 
		  PROCESS_ID BIGINT NOT NULL , 
		  MODEL_YEAR CHAR(4) NOT NULL , 
		  MTC_MODEL CHAR(3) NOT NULL , 
		  STATUS_ID SMALLINT NOT NULL , 
		  NOTE VARCHAR(250) , 
		  PROD_RATE INTEGER , 
		  DAYS_FLAG CHAR(1) NOT NULL , 
		  LAST_UPDATED_BY CHAR(7) NOT NULL , 
		  LAST_UPDATED_DATE TIMESTAMP NOT NULL , 
		  USER_ID CHAR(7) NOT NULL , 
		  SCANNED_TRAINER_ID VARCHAR(100) , 
		  SCANNED_TRAINEE_ID VARCHAR(100) , 
		  ELECTRONIC_SIGN_TSTP TIMESTAMP , 
		  SCANNED_TRAINER_TSTP TIMESTAMP , 
		  SCANNED_TRAINEE_TSTP TIMESTAMP , 
		  IS_AVAILABLE SMALLINT NOT NULL , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.TRAINING_STATUS

ALTER TABLE VIOS.TRAINING_STATUS 
	ADD CONSTRAINT TRAINING_STATUS_PK PRIMARY KEY
		(TRAINING_STATUS_ID,
		 PLANT_LOC_CODE,
		 DEPT_CODE,
		 LAST_UPDATED_DATE,
		 EXTRACT_DATE);



------------------------------------------------
-- DDL Statements for table VIOS.ROTATION
------------------------------------------------
 
DROP TABLE VIOS.ROTATION;
CREATE TABLE VIOS.ROTATION  (
		  ROTATION_ID INTEGER NOT NULL , 
		  LINE_NUM SMALLINT , 
		  TEAM_ID INTEGER , 
		  PRODUCTION_DATE TIMESTAMP NOT NULL , 
		  LAST_UPDATED_BY CHAR(7) NOT NULL , 
		  LAST_UPDATED_DATE TIMESTAMP NOT NULL , 
		  CREATED_BY CHAR(7) NOT NULL , 
		  CREATED_DATE TIMESTAMP NOT NULL , 
		  TEAM_GROUP_ID INTEGER , 
		  PC_AREA_ID INTEGER , 
		  SHIFT_ID SMALLINT NOT NULL , 
		  IS_FINALIZED CHAR(18) , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.ROTATION

ALTER TABLE VIOS.ROTATION 
	ADD CONSTRAINT ROTATION_PK PRIMARY KEY
		(ROTATION_ID,
		 PLANT_LOC_CODE,
		 DEPT_CODE,
		 LAST_UPDATED_DATE,
		 EXTRACT_DATE);



------------------------------------------------
-- DDL Statements for table VIOS.MANPOWER_ASSIGNMENT
------------------------------------------------
 
DROP TABLE VIOS.MANPOWER_ASSIGNMENT;
CREATE TABLE VIOS.MANPOWER_ASSIGNMENT  (
		  MANPOWER_ASSIGNMENT_ID BIGINT NOT NULL , 
		  QUARTER SMALLINT NOT NULL , 
		  PAIR_TYPE SMALLINT NOT NULL , 
		  ERGO_TYPE CHAR(1) NOT NULL , 
		  REASON_CODE SMALLINT NOT NULL , 
		  DAYS_FLAG CHAR(1) NOT NULL , 
		  LAST_UPDATED_BY CHAR(7) NOT NULL , 
		  LAST_UPDATED_DATE TIMESTAMP NOT NULL , 
		  ROTATION_ID INTEGER NOT NULL , 
		  TEAM_ID INTEGER , 
		  MANPOWER_TAG_ID INTEGER NOT NULL , 
		  PROCESS_GROUP_ID INTEGER , 
		  PC_AREA_ID INTEGER , 
		  ASSOCIATE_ID CHAR(7) , 
		  ADDITIONAL_ASSOCIATE_ID CHAR(7) , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.MANPOWER_ASSIGNMENT

ALTER TABLE VIOS.MANPOWER_ASSIGNMENT 
	ADD CONSTRAINT MANPOWER_ASSIGNMENT_PK PRIMARY KEY
		(MANPOWER_ASSIGNMENT_ID,
		 PLANT_LOC_CODE,
		 DEPT_CODE,
		 LAST_UPDATED_DATE,
		 EXTRACT_DATE);



------------------------------------------------
-- DDL Statements for table VIOS.PROCESS_ASSIGNMENT_DETAIL
------------------------------------------------
 
DROP TABLE VIOS.PROCESS_ASSIGNMENT_DETAIL;
CREATE TABLE VIOS.PROCESS_ASSIGNMENT_DETAIL  (
		  MANPOWER_ASSIGNMENT_ID BIGINT NOT NULL , 
		  BODY_LOC_NO CHAR(4) NOT NULL , 
		  PROCESS_NO CHAR(5) NOT NULL , 
		  PROCESS_NAME VARCHAR(35) NOT NULL , 
		  VMC CHAR(1) NOT NULL , 
		  VMC_DESC VARCHAR(35) NOT NULL , 
		  MODEL_YEAR CHAR(4) NOT NULL , 
		  PRODUCTION_SCHEDULE_QTY INTEGER NOT NULL , 
		  EFF_BEGIN_DATE TIMESTAMP NOT NULL , 
		  EFF_END_DATE TIMESTAMP NOT NULL , 
		  DAYS_FLAG CHAR(1) NOT NULL , 
		  LAST_UPDATED_BY CHAR(7) NOT NULL , 
		  LAST_UPDATED_DATE TIMESTAMP NOT NULL , 
		  PROCESS_ID BIGINT NOT NULL , 
		  PDDA_PROCESS_ID BIGINT , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.PROCESS_ASSIGNMENT_DETAIL

ALTER TABLE VIOS.PROCESS_ASSIGNMENT_DETAIL 
	ADD CONSTRAINT PROCESS_ASSIGNMENT_DETAIL_PK PRIMARY KEY
		(MANPOWER_ASSIGNMENT_ID,
		 PROCESS_ID,
		 PLANT_LOC_CODE,
		 DEPT_CODE,
		 LAST_UPDATED_DATE,
		 EXTRACT_DATE);



------------------------------------------------
-- DDL Statements for table VIOS.PCLPR1
------------------------------------------------
 
DROP TABLE VIOS.PCLPR1;
CREATE TABLE VIOS.PCLPR1  (
		  APVD_PROC_MAINT_ID INTEGER NOT NULL , 
		  TEAM_ID INTEGER NOT NULL , 
		  MPTAG_ID INTEGER NOT NULL , 
		  BODY_LOC_NO CHAR(4) NOT NULL , 
		  ASM_PROC_SEQ_NO SMALLINT NOT NULL , 
		  ASM_PROC_NO CHAR(5) NOT NULL , 
		  ASM_PROC_NAME CHAR(35) NOT NULL , 
		  ROTATION CHAR(1) NOT NULL , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.PCLPR1

ALTER TABLE VIOS.PCLPR1 
	ADD CONSTRAINT PCLPR1_PK PRIMARY KEY
		(APVD_PROC_MAINT_ID,
		 TEAM_ID);



------------------------------------------------
-- DDL Statements for table VIOS.PCLUN1
------------------------------------------------
 
DROP TABLE VIOS.PCLUN1;
CREATE TABLE VIOS.PCLUN1  (
		  UNIT_REC_ID INTEGER NOT NULL , 
		  APVD_UNIT_MAINT_ID INTEGER NOT NULL , 
		  APVD_PROC_MAINT_ID INTEGER NOT NULL , 
		  TEAM_ID INTEGER NOT NULL , 
		  UNIT_SEQ_NO SMALLINT NOT NULL , 
		  UNIT_NO CHAR(6) NOT NULL , 
		  UNIT_OP_DESC_TEXT CHAR(254) NOT NULL , 
		  JOINT_TYPE CHAR(1) , 
		  TORQUE_CHAR_VALUE CHAR(3) NOT NULL , 
		  MAX_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL , 
		  MIN_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL , 
		  STATUS CHAR(8) NOT NULL , 
		  ADDED_DATE TIMESTAMP NOT NULL , 
		  PROD_UNIT_ID_NO VARCHAR(20) , 
		  ACCEPTED_LOGON_ID CHAR(8) , 
		  ACCEPTED_DATE TIMESTAMP , 
		  MAINT_DATE TIMESTAMP NOT NULL , 
		  WORK_PT_DESC_TEXT VARCHAR(500) NOT NULL , 
		  QLTY_PT_DESC_TEXT VARCHAR(500) NOT NULL , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.PCLUN1

ALTER TABLE VIOS.PCLUN1 
	ADD CONSTRAINT PCLUN1_PK PRIMARY KEY
		(UNIT_REC_ID);



------------------------------------------------
-- DDL Statements for table VIOS.PCLTM1
------------------------------------------------
 
DROP TABLE VIOS.PCLTM1;
CREATE TABLE VIOS.PCLTM1  (
		  TEAM_ID INTEGER NOT NULL , 
		  PLANT_LOC_CODE CHAR(1) NOT NULL , 
		  DEPT_CODE CHAR(2) NOT NULL , 
		  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL , 
		  PROD_SCH_QTY DECIMAL(5,1) NOT NULL , 
		  VEHICLE_MODEL_CODE CHAR(1) NOT NULL , 
		  PROD_ASM_LINE_NO CHAR(1) NOT NULL , 
		  EFF_BEG_DATE DATE NOT NULL , 
		  EFF_END_DATE DATE NOT NULL , 
		  PROD_RATE_ID INTEGER NOT NULL , 
		  TEAM_SEQ_NO SMALLINT NOT NULL , 
		  TEAM_NO CHAR(4) NOT NULL , 
		  EXTRACT_DATE TIMESTAMP NOT NULL , 
		  CREATE_TIMESTAMP TIMESTAMP , 
		  UPDATE_TIMESTAMP TIMESTAMP )   
		 IN VIOSTBSDAT2 INDEX IN VIOSTBSIDX2 ; 


-- DDL Statements for primary key on Table VIOS.PCLTM1

ALTER TABLE VIOS.PCLTM1 
	ADD CONSTRAINT PCLTM1_PK PRIMARY KEY
		(TEAM_ID);









-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR1;
CREATE TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR1 NO CASCADE BEFORE INSERT ON
VIOS.MANPOWER_ASSIGNMENT REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP
= CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR2;
CREATE TRIGGER VIOS.MANPOWER_ASSIGNMENT_TR2 NO CASCADE BEFORE UPDATE ON
VIOS.MANPOWER_ASSIGNMENT REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP
= CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLPR1_TR1;
CREATE TRIGGER VIOS.PCLPR1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLPR1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLPR1_TR2;
CREATE TRIGGER VIOS.PCLPR1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLPR1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLTM1_TR1;
CREATE TRIGGER VIOS.PCLTM1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLTM1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLTM1_TR2;
CREATE TRIGGER VIOS.PCLTM1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLTM1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLUN1_TR1;
CREATE TRIGGER VIOS.PCLUN1_TR1 NO CASCADE BEFORE INSERT ON VIOS.PCLUN1 REFERENCING
NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PCLUN1_TR2;
CREATE TRIGGER VIOS.PCLUN1_TR2 NO CASCADE BEFORE UPDATE ON VIOS.PCLUN1 REFERENCING
NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR1;
CREATE TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR1 NO CASCADE BEFORE INSERT
ON VIOS.PROCESS_ASSIGNMENT_DETAIL REFERENCING NEW AS A FOR EACH ROW SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR2;
CREATE TRIGGER VIOS.PROCESS_ASSIGNMENT_DETAIL_TR2 NO CASCADE BEFORE UPDATE
ON VIOS.PROCESS_ASSIGNMENT_DETAIL REFERENCING NEW AS A FOR EACH ROW SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.ROTATION_TR1;
CREATE TRIGGER VIOS.ROTATION_TR1 NO CASCADE BEFORE INSERT ON VIOS.ROTATION
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.ROTATION_TR2;
CREATE TRIGGER VIOS.ROTATION_TR2 NO CASCADE BEFORE UPDATE ON VIOS.ROTATION
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.TRAINING_PROCESS_TR1;
CREATE TRIGGER VIOS.TRAINING_PROCESS_TR1 NO CASCADE BEFORE INSERT ON VIOS.TRAINING_PROCESS
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP =
CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.TRAINING_PROCESS_TR2;
CREATE TRIGGER VIOS.TRAINING_PROCESS_TR2 NO CASCADE BEFORE UPDATE ON VIOS.TRAINING_PROCESS
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP =
CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.TRAINING_STATUS_TR1;
CREATE TRIGGER VIOS.TRAINING_STATUS_TR1 NO CASCADE BEFORE INSERT ON VIOS.TRAINING_STATUS
REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = VIOS;
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
DROP TRIGGER VIOS.TRAINING_STATUS_TR2;
CREATE TRIGGER VIOS.TRAINING_STATUS_TR2 NO CASCADE BEFORE UPDATE ON VIOS.TRAINING_STATUS
REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


