
ALTER TABLE GALADM.GAL259TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL259TBX
ADD COLUMN PRODUCT_TYPE CHARACTER(10)
ADD COLUMN SUB_ID CHARACTER(2) NOT NULL DEFAULT ''
;

ALTER TABLE GALADM.GAL259TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.GAL259TBX ADD PRIMARY KEY (ATTRIBUTE, PRODUCT_SPEC_CODE, SUB_ID);

ALTER TABLE GALADM.GAL259TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE GALADM.GAL259TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL259TBX;
