-- Increase the character size for FRAME_OPTION in table AEP_STAT_OUT_TBX

ALTER TABLE GALADM.AEP_STAT_OUT_TBX DATA CAPTURE NONE;

ALTER TABLE GALADM.AEP_STAT_OUT_TBX  ALTER COLUMN FRAME_OPTION  SET DATA TYPE CHARACTER(3);

ALTER TABLE GALADM.AEP_STAT_OUT_TBX DATA CAPTURE CHANGES;

reorg table GALADM.AEP_STAT_OUT_TBX;