DROP INDEX GALADM.ABNORMAL_REASON_I1;
DROP TRIGGER GALADM.ABNORMAL_REASON_TR2;
DROP TRIGGER GALADM.ABNORMAL_REASON_TR1;
DROP TABLE GALADM.ABNORMAL_REASON_TBX;

CREATE TABLE GALADM.ABNORMAL_REASON_TBX (
   PRODUCT_ID              CHARACTER (17) NOT NULL,
   ABNORMAL_TYPE           CHARACTER (100) NOT NULL,
   ABNORMAL_REASON         VARCHAR (255),
   ASSOCIATE_NO            CHARACTER (11) NOT NULL,
   ACTUAL_TIMESTAMP        TIMESTAMP,
   CREATE_TIMESTAMP        TIMESTAMP,
   UPDATE_TIMESTAMP        TIMESTAMP
) DATA CAPTURE CHANGES
  IN GALTBSDAT9
  INDEX IN GALTBSIDX3;

COMMENT ON TABLE GALADM.ABNORMAL_REASON_TBX IS 'RMT AbnormalReason';

CREATE INDEX GALADM.ABNORMAL_REASON_I1 ON GALADM.ABNORMAL_REASON_TBX
    ( PRODUCT_ID ASC, ABNORMAL_TYPE ASC ) ALLOW REVERSE SCANS COMPRESS NO;


SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.ABNORMAL_REASON_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ABNORMAL_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.ABNORMAL_REASON_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ABNORMAL_REASON_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
