-- REMARK - depending on LET_MESSAGE_TBX size creation of indexes can take some time.

CREATE INDEX "GALADM"."LET_MESSAGE_I3" ON "GALADM"."LET_MESSAGE_TBX" (XML_MESSAGE_BODY)  GENERATE KEY USING XMLPATTERN '/UNIT_IN_TEST/PROCESS/TESTS/TEST/@Test' AS SQL VARCHAR(255) ALLOW REVERSE SCANS COMPRESS NO; 

CREATE INDEX "GALADM"."LET_MESSAGE_I4" ON "GALADM"."LET_MESSAGE_TBX" (XML_MESSAGE_BODY)  GENERATE KEY USING XMLPATTERN '/UNIT_IN_TEST/PROCESS/TESTS/TEST/@TestEndTime' AS SQL TIMESTAMP ALLOW REVERSE SCANS COMPRESS NO; 


