------------------------------------------------
-- DDL Statements for Table "GALADM  "."QI_REPAIR_AREA_SPACE_HIST_TBX"
------------------------------------------------

DROP TRIGGER GALADM.QI_REPAIR_AREA_SPACE_HIST_TR1;
DROP TRIGGER GALADM.QI_REPAIR_AREA_SPACE_HIST_TR2;
DROP TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX;

CREATE TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX
(

	REPAIR_AREA_NAME      VARCHAR(20) NOT NULL ,
	REPAIR_AREA_ROW		  INTEGER NOT NULL,
	REPAIR_AREA_SPACE	  INTEGER NOT NULL,
	PRODUCT_ID			  CHAR(17) NOT NULL,
	ACTUAL_TIMESTAMP      TIMESTAMP NOT NULL,
	DEFECTRESULTID		  INTEGER,
	CREATE_TIMESTAMP      TIMESTAMP,
	UPDATE_TIMESTAMP      TIMESTAMP,
	CREATE_USER           CHAR(11),
	UPDATE_USER           CHAR(11) )
 	IN GALTBSREF11 INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX IS 'NAQ Repair Area Space History';

CREATE UNIQUE INDEX GALADM.QI_REPAIR_AREA_SPACE_HIST_I1
  ON GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX (REPAIR_AREA_NAME, REPAIR_AREA_ROW, REPAIR_AREA_SPACE, PRODUCT_ID, ACTUAL_TIMESTAMP);

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_HIST_PK PRIMARY KEY (REPAIR_AREA_NAME, REPAIR_AREA_ROW, REPAIR_AREA_SPACE, PRODUCT_ID, ACTUAL_TIMESTAMP);
	
ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX 
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_HIST_C1 CHECK 
		(CREATE_USER = UPPER(CREATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX  
	ADD CONSTRAINT QI_REPAIR_AREA_SPACE_HIST_C2 CHECK 
		(UPDATE_USER = UPPER(UPDATE_USER));

ALTER TABLE GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX 
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_SPACE_HIST_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QI_REPAIR_AREA_SPACE_HIST_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.QI_REPAIR_AREA_SPACE_HIST_TBX
  REFERENCING NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
  