ALTER TABLE GALADM.QI_IQS_TBX ADD COLUMN IQS_QUESTION VARCHAR(256) NOT NULL DEFAULT '';

ALTER TABLE GALADM.QI_IQS_QUESTION_TBX DROP PRIMARY KEY;
DROP INDEX GALADM.QI_IQS_QUESTION_I1;
CREATE UNIQUE INDEX GALADM.QI_IQS_QUESTION_I1 ON GALADM.QI_IQS_QUESTION_TBX (IQS_QUESTION_NO, IQS_QUESTION);
ALTER TABLE GALADM.QI_IQS_QUESTION_TBX ADD CONSTRAINT QI_IQS_QUESTION_PK PRIMARY KEY (IQS_QUESTION_NO, IQS_QUESTION);
