CREATE TABLE GALADM.MC_OP_MATRIX_TBX (
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   OP_REV             	INTEGER 		NOT NULL,
   PDDA_PROCESS_ID		INTEGER			NOT NULL,
   SPEC_CODE_TYPE     	VARCHAR(32) 	NOT NULL,
   SPEC_CODE_MASK     	VARCHAR(30) 	NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_MATRIX_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PROCESS_ID, SPEC_CODE_TYPE, SPEC_CODE_MASK)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_MATRIX_TBX IS 'RMT MC_OP_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MC_STRUCTUREs';
    
CREATE TRIGGER GALADM.MC_OP_MATRIX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_MATRIX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_MEAS_TBX (
   OPERATION_NAME		CHARACTER(32)	NOT NULL,
   PART_ID				CHARACTER(5)	NOT NULL,
   PART_REV				INTEGER		NOT NULL,
   OP_MEAS_SEQ_NUM		INTEGER		NOT NULL,
   MEAS_TYPE			VARCHAR(32),
   MEAS_VIEW			VARCHAR(255),
   MEAS_PROCESSOR		VARCHAR(255),
   DEVICE_ID			CHARACTER(32),
   DEVICE_MSG			CHARACTER(32),
   MIN_LIMIT			DOUBLE,
   MAX_LIMIT			DOUBLE,
   MEAS_MAX_ATTEMPTS	INTEGER,
   MEAS_TIME			INTEGER,
   MEAS_CHECK			INTEGER,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_MEAS_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV, OP_MEAS_SEQ_NUM)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_MEAS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_MEAS_TBX IS 'RMT MC_OP_MEAS is used by Manufacturing Control to define the part measurement specs for a specific revision of an operation part';
    
CREATE TRIGGER GALADM.MC_OP_MEAS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_MEAS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_MEAS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_PART_MATRIX_TBX (
   OPERATION_NAME		CHARACTER(32)	NOT NULL,
   PART_ID				CHARACTER(5)	NOT NULL,
   PART_REV				INTEGER			NOT NULL,
   SPEC_CODE_TYPE		VARCHAR(32)		NOT NULL,
   SPEC_CODE_MASK		VARCHAR(30)		NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_PART_MATRIX_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV, SPEC_CODE_TYPE, SPEC_CODE_MASK)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_PART_MATRIX_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_PART_MATRIX_TBX IS 'RMT MC_OP_PART_MATRIX is used by Manufacturing Control to define the allowed Product and or Part Spec Codes to assist in the generation of the MC_STRUCTUREs';
    
CREATE TRIGGER GALADM.MC_OP_PART_MATRIX_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_PART_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_PART_MATRIX_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_PART_MATRIX_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_PART_REV_TBX (
   OPERATION_NAME       CHARACTER(32)	NOT NULL,
   PART_ID              CHARACTER(5)	NOT NULL,
   PART_REV             INTEGER			NOT NULL,
   REV_ID         	    BIGINT			NOT NULL,
   PART_DESC            VARCHAR(255),
   PART_TYPE            VARCHAR(32),
   PART_VIEW            VARCHAR(255),
   PART_PROCESSOR       VARCHAR(255),
   DEVICE_ID            CHARACTER(32),
   DEVICE_MSG           CHARACTER(32),
   PART_NO              CHARACTER(18),
   PART_SECTION_CODE    CHARACTER(3),
   PART_ITEM_NO         CHARACTER(8),
   PART_MASK          	VARCHAR(255),
   PART_MARK            VARCHAR(32),
   PART_MAX_ATTEMPTS  	INTEGER,
   MEASUREMENT_COUNT  	INTEGER,
   PART_TIME            INTEGER,
   PART_CHECK           INTEGER,
   APPROVED             TIMESTAMP,
   DEPRECATED_REV_ID    BIGINT,
   DEPRECATED           TIMESTAMP,   
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_PART_REV_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID, PART_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_PART_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_PART_REV_TBX IS 'RMT MC_OP_PART_REV is used by Manufacturing Control to define the revision of parts that can be used at an operation';
    
CREATE TRIGGER GALADM.MC_OP_PART_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_PART_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_PART_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_PART_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_PART_TBX (
   OPERATION_NAME       CHARACTER(32)	NOT NULL,
   PART_ID              CHARACTER(5)	NOT NULL,
   PART_REV             INTEGER			NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP	    TIMESTAMP,
   CONSTRAINT MC_OP_PART_PK PRIMARY KEY 
     (OPERATION_NAME, PART_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_PART_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_PART_TBX IS 'RMT MC_OP_PART is used by Manufacturing Control to define the current part specs that can be used at an operation';
    
CREATE TRIGGER GALADM.MC_OP_PART_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_PART_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_PART_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_REV_PLATFORM_TBX (
   OPERATION_NAME		CHARACTER(32) 	NOT NULL,
   OP_REV           	INTEGER 		NOT NULL,
   PDDA_PROCESS_ID		INTEGER			NOT NULL,
   PROCESS_POINT_ID 	CHARACTER(16),
   PROCESS_SEQ_NUM  	INTEGER,
   OP_SEQ_NUM       	INTEGER,
   OP_TIME          	INTEGER,
   DEVICE_ID        	CHARACTER(32),
   DEVICE_MSG       	CHARACTER(32),
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_OP_REV_PLATFORM_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PROCESS_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_REV_PLATFORM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_REV_PLATFORM_TBX IS 'RMT MC_OP_REV_PLATFORM is used by Manufacturing Control to define the platforms that should perform this revision of operation';
    
CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_REV_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_REV_PLATFORM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_REV_PLATFORM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.MC_OP_REV_PLATFORM_I1
  ON GALADM.MC_OP_REV_PLATFORM_TBX
    ( PROCESS_POINT_ID, OP_SEQ_NUM, OPERATION_NAME, OP_REV, PDDA_PROCESS_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE TABLE GALADM.MC_OP_REV_TBX (
   OPERATION_NAME	  CHARACTER(32) NOT NULL,
   OP_REV           INTEGER NOT NULL,
   REV_ID       	  BIGINT NOT NULL,
   OP_DESC          VARCHAR(255),
   OP_TYPE          VARCHAR(32),
   OP_VIEW          VARCHAR(255),
   OP_PROCESSOR     VARCHAR(255),
   OP_CHECK         INTEGER,
   APPROVED         TIMESTAMP,
   DEPRECATED_REV_ID BIGINT,
   DEPRECATED       TIMESTAMP,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MC_OP_REV_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_REV_TBX IS 'RMT MC_OP_REV is used by Manufacturing Control to define the revision of operations that can be performed at a process point';
    
CREATE TRIGGER GALADM.MC_OP_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_OP_TBX (
   OPERATION_NAME	  CHARACTER(32) NOT NULL,
   OP_REV           INTEGER NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MC_OP_PK PRIMARY KEY 
     (OPERATION_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_OP_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_OP_TBX IS 'RMT MC_OP is used by Manufacturing Control to define the current operations that can be performed at a process point';
    
CREATE TRIGGER GALADM.MC_OP_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_OP_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_OP_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_PDDA_CHG_TBX (
   REV_ID			BIGINT	NOT NULL,
   CHANGE_FORM_ID	INTEGER	NOT NULL,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MC_PDDA_CHG_PK PRIMARY KEY 
     (REV_ID, CHANGE_FORM_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_CHG_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_CHG_TBX IS 'RMT MC_PDDA_CHG is used by Manufacturing Control to link the PDDA Change Forms to GALC Revision';
    
CREATE TRIGGER GALADM.MC_PDDA_CHG_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_CHG_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_CHG_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_CHG_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_PDDA_PROCESS_TBX (
   PROCESS_POINT_ID CHARACTER(16)	NOT NULL,
   PDDA_PROCESS_ID	INTEGER			NOT NULL,
   APPROVER_NO		CHARACTER(11),
   APPROVED			TIMESTAMP,
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MC_PDDA_PROCESS_PK PRIMARY KEY 
     (PROCESS_POINT_ID, PDDA_PROCESS_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_PROCESS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_PROCESS_TBX IS 'RMT MC_PDDA_PROCESS is used by Manufacturing Control to link PDDA Process ID to GALC Process Point ID';
    
CREATE TRIGGER GALADM.MC_PDDA_PROCESS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_PROCESS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_PROCESS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_PROCESS_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_PDDA_UNIT_REV_TBX (
   OPERATION_NAME		CHARACTER(32) 	NOT NULL,
   OP_REV           	INTEGER 		NOT NULL,
   PDDA_PROCESS_ID		INTEGER			NOT NULL,
   UNIT_NO		     	VARCHAR(6)	 	NOT NULL,
   PDDA_REPORT			VARCHAR(6)		NOT NULL,
   APVD_PROC_MAINT_ID	INTEGER			NOT NULL,
   APVD_UNIT_MAINT_ID	INTEGER			NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_UNIT_REV_PK PRIMARY KEY 
     (OPERATION_NAME, OP_REV, PDDA_PROCESS_ID, UNIT_NO, PDDA_REPORT)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_UNIT_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_UNIT_REV_TBX IS 'RMT MC_PDDA_UNIT_REV is used by Manufacturing Control to define the approved PDDA revision of units on the given PDDA report';
    
CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_UNIT_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_UNIT_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_UNIT_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_PDDA_UNIT_TBX (
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   PDDA_PROCESS_ID		INTEGER			NOT NULL,
   UNIT_NO		     	VARCHAR(6)	 	NOT NULL,
   APPROVER_NO	     	CHARACTER(11),
   APPROVED				TIMESTAMP,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PDDA_UNIT_PK PRIMARY KEY 
     (OPERATION_NAME, PDDA_PROCESS_ID, UNIT_NO )
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PDDA_UNIT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PDDA_UNIT_TBX IS 'RMT MC_PDDA_UNIT is used by Manufacturing Control to define the active PDDA Platforms and Unit No associated to an Operation Name';
    
CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PDDA_UNIT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PDDA_UNIT_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PDDA_UNIT_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_PRODUCT_STRUCTURE_TBX (
   PRODUCT_ID			CHARACTER(17)	NOT NULL,
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV		BIGINT			NOT NULL,
   CREATE_TIMESTAMP		TIMESTAMP,
   UPDATE_TIMESTAMP		TIMESTAMP,
   CONSTRAINT MC_PRODUCT_STRUCTURE_PK PRIMARY KEY 
     (PRODUCT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_PRODUCT_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_PRODUCT_STRUCTURE_TBX IS 'RMT MC_PRODUCT_STRUCTURE is used by Manufacturing Control to define the structure revision that should be used to manufacture this PRODUCT';
    
CREATE TRIGGER GALADM.MC_PRODUCT_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_PRODUCT_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PRODUCT_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_PRODUCT_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_REV_TBX (
   REV_ID			BIGINT NOT NULL,
   REV_DESC			VARCHAR(255),
   ASSOCIATE_NO	    CHARACTER(11),
   REV_TYPE         VARCHAR(32),
   REV_STATUS       VARCHAR(32),
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT MC_REV_PK PRIMARY KEY 
     (REV_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_REV_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_REV_TBX IS 'RMT MC_REV is used by Manufacturing Control to track the revisions of operations and parts';
    
CREATE TRIGGER GALADM.MC_REV_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_REV_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_REV_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TABLE GALADM.MC_STRUCTURE_TBX (
   PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
   STRUCTURE_REV      	BIGINT 			NOT NULL,
   PROCESS_POINT_ID   	CHARACTER(16) 	NOT NULL,
   OPERATION_NAME     	CHARACTER(32) 	NOT NULL,
   OP_REV             	INTEGER 		NOT NULL,
   PDDA_PROCESS_ID		INTEGER			NOT NULL,
   PART_ID            	CHARACTER(5) 	NOT NULL DEFAULT '',
   PART_REV           	INTEGER 		NOT NULL DEFAULT 0,
   CREATE_TIMESTAMP	  	TIMESTAMP,
   UPDATE_TIMESTAMP	  	TIMESTAMP,
   CONSTRAINT MC_STRUCTURE_PK PRIMARY KEY 
     (PRODUCT_SPEC_CODE, STRUCTURE_REV, PROCESS_POINT_ID, OPERATION_NAME, OP_REV, PDDA_PROCESS_ID, PART_ID, PART_REV)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MC_STRUCTURE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MC_STRUCTURE_TBX IS 'RMT MC_STRUCTURE is used by Manufacturing Control to define the revisions of operations and parts that are used to manufacture a Product Spec Code';
    
CREATE TRIGGER GALADM.MC_STRUCTURE_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.MC_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_STRUCTURE_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.MC_STRUCTURE_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL215TBX
	ADD COLUMN ASSOCIATE_NO		CHARACTER(11)
	ADD COLUMN APPROVER_NO		CHARACTER(11);

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE CHANGES;

  