ALTER TABLE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX ADD COLUMN ORIGINAL_DEFECT_STATUS SMALLINT DEFAULT -1;
UPDATE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX SET CURRENT_DEFECT_STATUS = -1 WHERE CURRENT_DEFECT_STATUS = 0;
UPDATE GALADM.QI_STATION_PREVIOUS_DEFECT_TBX SET CURRENT_DEFECT_STATUS = 5 WHERE CURRENT_DEFECT_STATUS = 2;
