ALTER TABLE "GALADM"."PUSH_TIMER_STATUS_TBX"
  ADD COLUMN ASSOCIATE_NO CHARACTER(11);
  
DROP TRIGGER "GALADM".OP_EFFICIENCY_HIST_TR1;
DROP TRIGGER "GALADM".OP_EFFICIENCY_HIST_TR2;
DROP TABLE "GALADM".OP_EFFICIENCY_HIST_TBX;

CREATE TABLE "GALADM"."OP_EFFICIENCY_HIST_TBX" (
  "PROCESS_POINT_ID"	CHARACTER(16)	NOT NULL,
  "OPERATION_NAME"	CHARACTER(32) NOT NULL,
  "UNIT_ID"	CHARACTER(32),
  "ASSOCIATE_NO"	CHARACTER(11)	NOT NULL,
  "PRODUCT_ID"	VARCHAR(32) NOT NULL,
  "PLANNED_TIME" BIGINT NOT NULL,
  "ACTUAL_TIME" BIGINT NOT NULL,
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "GALTBSREF11"  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."OP_EFFICIENCY_HIST_TBX"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."OP_EFFICIENCY_HIST_TBX" IS 'Keeps history of how long a process took at the process point';

CREATE TRIGGER "GALADM"."OP_EFFICIENCY_HIST_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."OP_EFFICIENCY_HIST_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."OP_EFFICIENCY_HIST_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."OP_EFFICIENCY_HIST_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE "GALADM"."OP_EFFICIENCY_HIST_TBX"
  ADD CONSTRAINT "OP_EFFICIENCY_HIST_PK" PRIMARY KEY
    ("PROCESS_POINT_ID", "OPERATION_NAME");



  