DROP TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR1;
DROP TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR2;
DROP TABLE GALADM.LET_CONNECTED_PROGRAM_TBX;

CREATE TABLE GALADM.LET_CONNECTED_PROGRAM_TBX (
  CRITERIA_PGM_ID INTEGER NOT NULL,
  TRIGGERING_PGM_ID INTEGER NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT LET_CONNECTED_PROGRAM_PK PRIMARY KEY(CRITERIA_PGM_ID, TRIGGERING_PGM_ID)
)IN GALTBSDAT9 INDEX IN GALTBSIDX3; 

ALTER TABLE GALADM.LET_CONNECTED_PROGRAM_TBX 
  ADD FOREIGN KEY LET_CONNECTED_PROGRAM_FK1 
    (CRITERIA_PGM_ID)
  REFERENCES GALADM.GAL718TBX
    (CRITERIA_PGM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE GALADM.LET_CONNECTED_PROGRAM_TBX 
  ADD FOREIGN KEY LET_CONNECTED_PROGRAM_FK2 
    (TRIGGERING_PGM_ID)
  REFERENCES GALADM.GAL718TBX
    (CRITERIA_PGM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

CREATE TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.LET_CONNECTED_PROGRAM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LET_CONNECTED_PROGRAM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.LET_CONNECTED_PROGRAM_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
  SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;