ALTER TABLE GALADM.GAL147TBX ADD COLUMN HOLD_PROCESS_POINT CHARACTER(16);
ALTER TABLE GALADM.GAL147TBX ADD COLUMN EQUIPMENT_FLAG INTEGER DEFAULT 0;
ALTER TABLE GALADM.GAL147TBX ADD COLUMN RELEASE_PERMISSION INTEGER DEFAULT 0;
