ALTER TABLE GALADM.GAL198TBX ADD METHOD_ID VARCHAR(32);
ALTER TABLE GALADM.GAL198TBX ADD METHOD_DESCRIPTION VARCHAR(64);

ALTER TABLE GALADM.GAL198_HIST_TBX ADD METHOD_ID VARCHAR(32);
ALTER TABLE GALADM.GAL198_HIST_TBX ADD METHOD_DESCRIPTION VARCHAR(64);
