-- Adding FormId
INSERT INTO galadm.GAL294TBX (FORM_ID,DESTINATION_ID,DEFAULT_FLAG,CREATE_TIMESTAMP,UPDATE_TIMESTAMP) 
VALUES ('REPRINT_TICKET','',1,CURRENT_TIMESTAMP,null);
-- Adding Template object
INSERT INTO galadm.TEMPLATES_TBX (TEMPLATE_NAME,TEMPLATE_DESCRIPTION,TEMPLATE_TYPE,TEMPLATE_DATA,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,FORM_ID,REVISION_ID) 
VALUES ('REPRINT_TICKET','Reprint Ticket Functionality for Repair Area Management Screen','JASPER',EMPTY_BLOB(),CURRENT_TIMESTAMP,null,'REPRINT_TICKET',null);
-- Adding print Attributes
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','DEFECT_DETAILS',0,0,14,'SELECT * FROM (select distinct DRT.RESPONSIBLE_DEPT as ENTRY_DEPT , (REPLACE(REPLACE(REPLACE(DRT.INSPECTION_PART_NAME || '' '' ||COALESCE(DRT.INSPECTION_PART_LOCATION_NAME, '''')  ||  '' '' || COALESCE (DRT.INSPECTION_PART_LOCATION2_NAME, '''') || '' '' || COALESCE (DRT.INSPECTION_PART2_NAME,'''')|| '' '' || COALESCE (DRT.INSPECTION_PART2_LOCATION_NAME, '''')  || '' '' || COALESCE (DRT.INSPECTION_PART2_LOCATION2_NAME, '''') || '' '' || COALESCE(DRT.INSPECTION_PART3_NAME, '''')|| '' '' || COALESCE(DRT.DEFECT_TYPE_NAME, '''')|| '' '' || COALESCE (DRT.DEFECT_TYPE_NAME2, '''')	 ,'' '',''<>''),''><'',''''),''<>'','' '')) AS DEFECT_DESC from galadm.QI_DEFECT_RESULT_TBX DRT where DRT.PRODUCT_ID=''{PRODUCT_ID}''  and DRT.ORIGINAL_DEFECT_STATUS!=1 and DRT.DELETED=0 and DRT.CURRENT_DEFECT_STATUS!=7 and  DRT.CURRENT_DEFECT_STATUS!=8   )  order by case when DEFECT_DESC= (select (REPLACE(REPLACE(REPLACE(DR.INSPECTION_PART_NAME || '' '' || COALESCE(DR.INSPECTION_PART_LOCATION_NAME, '''')  ||  '' '' || COALESCE (DR.INSPECTION_PART_LOCATION2_NAME, '''') || '' '' || COALESCE (DR.INSPECTION_PART2_NAME,'''')|| '' '' || COALESCE (DR.INSPECTION_PART2_LOCATION_NAME, '''')  || '' '' || COALESCE (DR.INSPECTION_PART2_LOCATION2_NAME, '''') || '' '' || COALESCE(DR.INSPECTION_PART3_NAME, '''')|| '' '' || COALESCE(DR.DEFECT_TYPE_NAME, '''')|| '' '' || COALESCE (DR.DEFECT_TYPE_NAME2, '''')	 ,'' '',''<>''),''><'',''''),''<>'','' '')) AS DEFECT_DESCRIPTION from galadm.QI_DEFECT_RESULT_TBX DR where DR.DEFECTRESULTID=''{DEFECT_RESULT_ID}'') THEN 1 Else 2 END, DEFECT_DESC',9,CURRENT_TIMESTAMP,null,0);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','EXT_COLOR_CODE',0,0,3,'select EXT_COLOR_CODE from galadm.GAL144TBX where PRODUCT_SPEC_CODE = ''{PRODUCT_SPEC_CODE}''',7,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','GRADE_CODE',0,0,3,'select GRADE_CODE from galadm.GAL144TBX where PRODUCT_SPEC_CODE = ''{PRODUCT_SPEC_CODE}''',8,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','LOT',0,0,3,'select CASE WHEN LOCATION=''I'' THEN ''Inside Lot'' WHEN LOCATION=''O'' THEN ''Outside Lot'' ELSE '''' END from galadm.QI_REPAIR_AREA_TBX RA where REPAIR_AREA_NAME=''{REPAIR_AREA}''',2,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','MODEL',0,0,3,'select COALESCE (MODEL_YEAR_CODE, '''')  || COALESCE (MODEL_CODE, '''') || ''-''|| COALESCE (MODEL_TYPE_CODE,'''') from galadm.GAL144TBX where PRODUCT_SPEC_CODE = ''{PRODUCT_SPEC_CODE}''',5,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','PRODUCT_ID',0,0,2,'PRODUCT_ID',1,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','ROW_VALUE',0,0,2,'ROW_VALUE',3,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','SHORT_VIN',0,0,3,'select substr(a.PRODUCT_ID,12) from galadm.GAL143TBX a where a.PRODUCT_ID=''{PRODUCT_ID}''',6,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','SPACE_VALUE',0,0,2,'SPACE_VALUE',4,CURRENT_TIMESTAMP,null,1);
INSERT INTO galadm.GAL258TBX (FORMID,ATTRIBUTE,OFFSET,LENGTH,ATTRIBUTE_TYPE,ATTRIBUTE_VALUE,SEQUENCE_NUMBER,CREATE_TIMESTAMP,UPDATE_TIMESTAMP,REQUIRED) 
VALUES ('REPRINT_TICKET','DEFECT_RESULT_ID',0,0,2,'DEFECT_RESULT_ID',9,CURRENT_TIMESTAMP,null,1);







