CREATE SCHEMA VIOS;

CREATE BUFFERPOOL "VIOSBP1"  SIZE AUTOMATIC PAGESIZE 4096;

CREATE BUFFERPOOL "VIOSBP8K"  SIZE AUTOMATIC PAGESIZE 8192;

CREATE BUFFERPOOL "VIOSBP16K"  SIZE AUTOMATIC PAGESIZE 16384;

CREATE BUFFERPOOL "VIOSBPIDX"  SIZE AUTOMATIC PAGESIZE 4096;


CREATE LARGE TABLESPACE "VIOSTBSDAT1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL VIOSBP1
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "VIOSTBSDAT2" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL VIOSBP1
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE "VIOSTBSIDX1" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL VIOSBPIDX
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "VIOSTBS16K" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 16384 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 50 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL VIOSBP16K
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;

CREATE TABLE VIOS.PVLUN1  (
  UNIT_REC_ID INTEGER NOT NULL ,
  UNIT_ID INTEGER NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  TEAM_ID INTEGER NOT NULL ,
  UNIT_SEQ_NO SMALLINT NOT NULL ,
  UNIT_NO CHAR(6) NOT NULL ,
  UNIT_OP_DESC_TEXT CHAR(254) NOT NULL ,
  JOINT_TYPE CHAR(1) NOT NULL ,
  TORQUE_CHAR_VALUE CHAR(3) NOT NULL ,
  MAX_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL ,
  MIN_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL ,
  STATUS CHAR(8) NOT NULL ,
  ADDED_DATE TIMESTAMP NOT NULL ,
  ACCEPTED_LOGON_ID CHAR(8) NOT NULL ,
  ACCEPTED_DATE TIMESTAMP NOT NULL ,
  MAINT_DATE TIMESTAMP NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  WORK_PT_DESC_TEXT VARCHAR(500) NOT NULL ,
  QLTY_PT_DESC_TEXT VARCHAR(500) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVLUN1_PK PRIMARY KEY
    (UNIT_REC_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVLUN1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVLUN1 IS 'RMT VIOS MdrsUnit Table';

CREATE TRIGGER VIOS.PVLUN1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLUN1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLUN1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVLUN1_I1 ON VIOS.PVLUN1
(UNIT_ID ASC,
 PROCESS_ID ASC,
 TEAM_ID ASC)

COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.PVLUN1_I2 ON VIOS.PVLUN1
(TEAM_ID ASC)

COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.PVLUN1_I3 ON VIOS.PVLUN1
(UNIT_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.PVUPI1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  PPE_ID INTEGER NOT NULL ,
  PPE_REQUIRED VARCHAR(200) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  POTENTIAL_HAZARD VARCHAR(300) NOT NULL ,
  PPE_USAGE VARCHAR(500),
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUPI1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, IMAGE_TIMESTAMP))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUPI1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUPI1 IS 'RMT VIOS UnitPpeImage Table';

CREATE TRIGGER VIOS.PVUPI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUPI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVPPI1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  PPE_ID INTEGER NOT NULL ,
  PPE_REQUIRED VARCHAR(200) NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  POTENTIAL_HAZARD VARCHAR(300) NOT NULL WITH DEFAULT '' ,
  PPE_USAGE VARCHAR(500) NOT NULL WITH DEFAULT '',
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVPPI1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, IMAGE_TIMESTAMP))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVPPI1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVPPI1 IS 'RMT VIOS ProcessPpeImage';

CREATE TRIGGER VIOS.PVPPI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVPPI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPPI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUMI1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  UNIT_IMAGE VARCHAR(508) NOT NULL WITH DEFAULT '',
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMI1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, IMAGE_TIMESTAMP))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMI1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMI1 IS 'RMT VIOS UnitImage Table';

CREATE TRIGGER VIOS.PVUMI1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMI1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMI1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUSH1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE VARCHAR(1) NOT NULL ,
  IMAGE_SEQ_NO SMALLINT NOT NULL ,
  IMAGE_TIMESTAMP TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  IMAGE BLOB(3M) LOGGED NOT COMPACT NOT NULL ,
  IMAGE_NAME VARCHAR(508) NOT NULL WITH DEFAULT '',
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUSH1_PK PRIMARY KEY
    (MAINTENANCE_ID, IMAGE_SEQ_NO, IMAGE_TIMESTAMP))
   IN VIOSTBS16K
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUSH1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUSH1 IS 'RMT VIOS UnitSafetyImage Table';

CREATE TRIGGER VIOS.PVUSH1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUSH1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUSH1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUSH1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVCFR1  (
  CHANGE_FORM_ID INTEGER NOT NULL ,
  CHANGE_FORM_TYPE CHAR(1) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  CONTROL_NO INTEGER NOT NULL ,
  REVISION_NO CHAR(5) NOT NULL ,
  REPORT_DATE TIMESTAMP NOT NULL ,
  CHANGE_DATE TIMESTAMP NOT NULL ,
  MAINT_LOGON_ID CHAR(8) NOT NULL ,
  MAINT_DATE TIMESTAMP NOT NULL ,
  DOCUMENT_NO CHAR(20) NOT NULL ,
  APVD_USER CHAR(8) ,
  APVD_DATE TIMESTAMP ,
  PRINTED_LOGON_ID CHAR(8) ,
  ASHIFT_TRAINING_DT TIMESTAMP ,
  ASHIFT_REMARKS CHAR(10) ,
  BSHIFT_TRAINING_DT TIMESTAMP ,
  BSHIFT_REMARKS CHAR(10) ,
  APV_PART_EFF_DATE TIMESTAMP ,
  PPS_DOCUMENT_NO CHAR(20) NOT NULL ,
  USR_DOCUMENT_NO CHAR(20) NOT NULL ,
  PS_DOCUMENT_NO CHAR(20) NOT NULL ,
  CU_DOCUMENT_NO CHAR(20) NOT NULL ,
  SS_DOCUMENT_NO CHAR(20) NOT NULL ,
  PPS_REVISION_NO CHAR(10) NOT NULL ,
  USR_REVISION_NO CHAR(10) NOT NULL ,
  PS_REVISION_NO CHAR(10) NOT NULL ,
  CU_REVISION_NO CHAR(10) NOT NULL ,
  SS_REVISION_NO CHAR(10) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVCFR1_PK PRIMARY KEY
  (CHANGE_FORM_ID))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVCFR1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVCFR1 IS 'RMT VIOS ChangeForm Table';

CREATE TRIGGER VIOS.PVCFR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVCFR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVCFR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVCFR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVCFU1  (
CHANGE_FORM_ID INTEGER NOT NULL ,
PLANT_LOC_CODE CHAR(1) NOT NULL ,
DEPT_CODE CHAR(2) NOT NULL ,
APVD_UNIT_MAINT_ID INTEGER NOT NULL ,
APVD_PROC_MAINT_ID INTEGER NOT NULL ,
ISSUED_DATE TIMESTAMP ,
ISSR_LOGON_ID CHAR(8) ,
ASM_PROC_NO VARCHAR(5) NOT NULL ,
CHANGE_DESC VARCHAR(254) NOT NULL ,
UNIT_NO VARCHAR(6) ,
PCF_IN CHAR(1) NOT NULL ,
USR_IN CHAR(1) NOT NULL ,
PPS_IN CHAR(1) NOT NULL ,
CU_IN CHAR(1) NOT NULL ,
PS_IN CHAR(1) NOT NULL ,
SS_IN CHAR(1) NOT NULL,
CREATE_TIMESTAMP   TIMESTAMP,
UPDATE_TIMESTAMP   TIMESTAMP,
CONSTRAINT PVCFU1_PK PRIMARY KEY
(APVD_PROC_MAINT_ID,
APVD_UNIT_MAINT_ID,
CHANGE_FORM_ID))
IN VIOSTBSDAT1
INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVCFU1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVCFU1 IS 'RMT VIOS ChangeFormUnit Table';

CREATE TRIGGER VIOS.PVCFU1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVCFU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVCFU1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVCFU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVDPT1  (
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  SHOW_JOINT_TYPE CHAR(1) NOT NULL ,
  SHOW_TORQUE CHAR(1) NOT NULL ,
  SHOW_SAFETY_PT CHAR(1) NOT NULL ,
  SHOW_IMPACT_PT CHAR(1) NOT NULL ,
  USES_PQCT CHAR(1) ,
  PRINT_MSDS_NO CHAR(1) ,
  SHOW_QUALITY_ISSUE CHAR(1) ,
  SHOW_QLTY_CTL_ITEM CHAR(1) ,
  SHOW_TOOL CHAR(1) ,
  PQCT_YEAR CHAR(4) ,
  GPACV_WCH CHAR(4) ,
  TORQUE_UOM CHAR(2) ,
  UNIT_SHEET_TOOL VARCHAR(254) ,
  MAINT_LOGON_ID CHAR(8) NOT NULL ,
  MAINT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVDPT1_PK PRIMARY KEY
  (DEPT_CODE,
   PLANT_LOC_CODE))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVDPT1
       DATA CAPTURE CHANGES
       PCTFREE 0
       LOCKSIZE ROW
       APPEND OFF
       NOT VOLATILE;

COMMENT ON TABLE VIOS.PVDPT1 IS 'RMT VIOS DepartmentSettings Table';

CREATE TRIGGER VIOS.PVDPT1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVDPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVDPT1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVDPT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVLPR1  (
  PROCESS_ID INTEGER NOT NULL ,
  TEAM_ID INTEGER NOT NULL ,
  MPTAG_ID INTEGER NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  ASM_PROC_SEQ_NO SMALLINT NOT NULL ,
  ASM_PROC_NO CHAR(5) NOT NULL ,
  ASM_PROC_NAME CHAR(35) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVLPR1_PK PRIMARY KEY
    (PROCESS_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVLPR1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVLPR1 IS 'RMT VIOS MdrsProcess Table';

CREATE TRIGGER VIOS.PVLPR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLPR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVLPR1_I1 ON VIOS.PVLPR1
  (TEAM_ID ASC,
   MPTAG_ID ASC,
   ASM_PROC_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.PVLTM1  (
  TEAM_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  EFF_BEG_DATE DATE NOT NULL ,
  EFF_END_DATE DATE NOT NULL ,
  PROD_RATE_ID INTEGER NOT NULL ,
  TEAM_SEQ_NO SMALLINT NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVLTM1_PK PRIMARY KEY
    (TEAM_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVLTM1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVLTM1 IS 'RMT VIOS MdrsTeam Table';

CREATE TRIGGER VIOS.PVLTM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVLTM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVLTM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVLTM1_I1 ON VIOS.PVLTM1
(PLANT_LOC_CODE ASC,
 DEPT_CODE ASC,
 MODEL_YEAR_DATE ASC,
 PROD_SCH_QTY ASC,
 VEHICLE_MODEL_CODE ASC,
 TEAM_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.PVMAL1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CONTROL_METHOD CHAR(30) NOT NULL ,
  FREQUENCY CHAR(30) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVMAL1_PK PRIMARY KEY
    (MAINTENANCE_ID, CONTROL_METHOD))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVMAL1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVMAL1 IS 'RMT VIOS UnitAdditionalControl Table';

CREATE TRIGGER VIOS.PVMAL1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMAL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVMAL1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMAL1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVMPC1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CONTROL_METHOD CHAR(30) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVMPC1_PK PRIMARY KEY
    (MAINTENANCE_ID, CONTROL_METHOD))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVMPC1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVMPC1 IS 'RMT VIOS UnitProcessControl Table';

CREATE TRIGGER VIOS.PVMPC1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMPC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVMPC1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMPC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVMPR1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CONTROL_STANDARD VARCHAR(250) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVMPR1_PK PRIMARY KEY
    (MAINTENANCE_ID, CONTROL_STANDARD))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVMPR1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVMPR1 IS 'RMT VIOS UnitProductControl Table';

CREATE TRIGGER VIOS.PVMPR1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVMPR1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMPR1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVMRP1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  REACTION VARCHAR(100) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVMRP1_PK PRIMARY KEY
    (MAINTENANCE_ID, REACTION))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVMRP1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVMRP1 IS 'RMT VIOS UnitReactionPlan Table';

CREATE TRIGGER VIOS.PVMRP1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMRP1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVMRP1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMRP1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVMSC1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CONTROL_APPLIED VARCHAR(254) NOT NULL ,
  PRINT CHAR(1) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVMSC1_PK PRIMARY KEY
    (MAINTENANCE_ID, CONTROL_APPLIED))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

   ALTER TABLE VIOS.PVMSC1
     DATA CAPTURE CHANGES
     PCTFREE 0
     LOCKSIZE ROW
     APPEND OFF
     NOT VOLATILE;

COMMENT ON TABLE VIOS.PVMSC1 IS 'RMT VIOS UnitSpecialControl';

CREATE TRIGGER VIOS.PVMSC1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVMSC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVMSC1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVMSC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVPMU1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  UNIT_NO CHAR(6) NOT NULL ,
  UNIT_SEQ_NO INTEGER NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVPMU1_PK PRIMARY KEY
    (MAINTENANCE_ID, UNIT_NO, UNIT_SEQ_NO))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVPMU1
        DATA CAPTURE CHANGES
        PCTFREE 0
        LOCKSIZE ROW
        APPEND OFF
        NOT VOLATILE;

COMMENT ON TABLE VIOS.PVPMU1 IS 'RMT VIOS ProcessUnit Table';

CREATE TRIGGER VIOS.PVPMU1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVPMU1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPMU1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVPMX1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  ASM_PROC_NO CHAR(5) NOT NULL ,
  ASM_PROC_SEQ_NO SMALLINT NOT NULL ,
  ASM_PROC_NAME CHAR(35) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  EFF_END_DATE DATE NOT NULL ,
  EFF_BEG_DATE DATE NOT NULL ,
  ADDITIONAL_COMMENT CHAR(254) NOT NULL ,
  ADD_INFO_NUMBER CHAR(18) NOT NULL ,
  REASON_CODE_TYPE CHAR(18) NOT NULL ,
  REASON_FOR_CHANGE CHAR(254) NOT NULL ,
  TEAM_SEQ_NO INTEGER NOT NULL ,
  TEAM_DESC CHAR(30) NOT NULL ,
  PROCESS_LOCATION CHAR(4) ,
  NUM_ASSOCIATES SMALLINT NOT NULL ,
  ROTATION CHAR(1) NOT NULL ,
  ACTION CHAR(1) NOT NULL ,
  MAINT_LOGON_ID CHAR(8) NOT NULL ,
  MAINT_DATE TIMESTAMP NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVPMX1_PK PRIMARY KEY
  (MAINTENANCE_ID))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

 ALTER TABLE VIOS.PVPMX1
   DATA CAPTURE CHANGES
   PCTFREE 0
   LOCKSIZE ROW
   APPEND OFF
   NOT VOLATILE;

COMMENT ON TABLE VIOS.PVPMX1 IS 'RMT VIOS Process Table';

CREATE TRIGGER VIOS.PVPMX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVPMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVPMX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVPMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVPMX1_I1 ON VIOS.PVPMX1
  (PLANT_LOC_CODE ASC)

  COMPRESS NO ALLOW REVERSE SCANS;

CREATE INDEX VIOS.PVPMX1_I2 ON VIOS.PVPMX1
  (DEPT_CODE ASC,
   PLANT_LOC_CODE ASC)

  COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.PVPMX1_I3 ON VIOS.PVPMX1
  (ASM_PROC_NO ASC)

  COMPRESS NO ALLOW REVERSE SCANS;
  
CREATE TABLE VIOS.PVUMC1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CNTRL_METH_DESC CHAR(25) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMC1_PK PRIMARY KEY
    (MAINTENANCE_ID, CNTRL_METH_DESC))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMC1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMC1 IS 'RMT VIOS UnitControlMethod Table';

CREATE TRIGGER VIOS.PVUMC1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMC1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMC1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUML1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  QUALITY_POINTS VARCHAR(250) NOT NULL ,
  WORKING_POINTS VARCHAR(250) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUML1_PK PRIMARY KEY
  (MAINTENANCE_ID, QUALITY_POINTS, WORKING_POINTS))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUML1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUML1 IS 'RMT VIOS UnitFmea Table';

CREATE TRIGGER VIOS.PVUML1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUML1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUML1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUML1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUMM1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MOST_SEQ_NO SMALLINT NOT NULL ,
  WORKING_POINT_DTL CHAR(254) NOT NULL ,
  SHOW_ON_PRINT CHAR(1) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMM1_PK PRIMARY KEY
  (MAINTENANCE_ID, MOST_SEQ_NO, WORKING_POINT_DTL))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMM1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMM1 IS 'RMT VIOS UnitMost Table';

CREATE TRIGGER VIOS.PVUMM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUMQ1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  QUALITY_ISS_DESC CHAR(20) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMQ1_PK PRIMARY KEY
    (MAINTENANCE_ID, QUALITY_ISS_DESC))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMQ1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMQ1 IS 'RMT VIOS UnitQualityIssue';

CREATE TRIGGER VIOS.PVUMQ1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMQ1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMQ1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUMT1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  MTC_MODEL CHAR(3) NOT NULL ,
  MTC_TYPE CHAR(3) NOT NULL ,
  MTC_OPTION CHAR(3) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMT1_PK PRIMARY KEY
    (MAINTENANCE_ID, MODEL_YEAR_DATE, MTC_MODEL, MTC_TYPE, MTC_OPTION))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMT1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMT1 IS 'RMT VIOS UnitModelType Table';

CREATE TRIGGER VIOS.PVUMT1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMT1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMT1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVUMT1_I1 ON VIOS.PVUMT1
(MTC_MODEL ASC,
 MTC_TYPE ASC,
 MTC_OPTION ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.PVUMX1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  UNIT_NO CHAR(6) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY DECIMAL(5,1) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  PROD_ASM_LINE_NO CHAR(1) NOT NULL ,
  BASE_PART_NO CHAR(5) NOT NULL ,
  UNIT_CREATE_DATE TIMESTAMP NOT NULL ,
  MIN_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL ,
  MAX_TORQUE_VAL_QTY DECIMAL(4,1) NOT NULL ,
  TORQUE_CHAR_VALUE CHAR(3) NOT NULL ,
  JOINT_TYPE CHAR(1) NOT NULL ,
  AUX_MTRL_DESC_TEXT CHAR(50) ,
  TOOL CHAR(50) NOT NULL ,
  UNIT_OP_DESC_TEXT CHAR(254) NOT NULL ,
  UNIT_RANK CHAR(20) ,
  AUX_MSDS_NO CHAR(20) ,
  ACTION CHAR(1) NOT NULL ,
  UNIT_SEQ_NO INTEGER NOT NULL ,
  LINE_SPEED DECIMAL(5,1) NOT NULL ,
  MAINT_LOGON_ID CHAR(8) NOT NULL ,
  MAINT_DATE TIMESTAMP NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  WORK_PT_DESC_TEXT VARCHAR(500) NOT NULL ,
  QLTY_PT_DESC_TEXT VARCHAR(500) NOT NULL ,
  SAFETY_PT_DESC VARCHAR(500) ,
  IMPACT_PT_DESC VARCHAR(540),
  SAFETY_ERGO_PT VARCHAR(500),
  SAFETY_ERGO_INST VARCHAR(500),
  UNIT_TOT_TIME FLOAT NOT NULL WITH DEFAULT 0,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUMX1_PK PRIMARY KEY
    (MAINTENANCE_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUMX1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUMX1 IS 'RMT VIOS Unit Table';

CREATE TRIGGER VIOS.PVUMX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUMX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUMX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.PVUMX1_I1 ON VIOS.PVUMX1
  (PLANT_LOC_CODE ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.PVUPM1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  PART_NO CHAR(18) NOT NULL ,
  PART_SECTION_CODE CHAR(3) NOT NULL ,
  PART_ITEM_NO CHAR(8) NOT NULL ,
  MTC_MODEL CHAR(3) NOT NULL ,
  MTC_TYPE CHAR(3) NOT NULL ,
  MTC_OPTION CHAR(3) NOT NULL ,
  PART_QTY SMALLINT ,
  PART_MARKING_NO CHAR(4) ,
  TGT_EFF_BEG_DATE TIMESTAMP ,
  PART_EFF_DATE TIMESTAMP,
  DELIVERY_LOCATION CHAR(4),
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUPM1_PK PRIMARY KEY
  (MAINTENANCE_ID, MTC_MODEL, MTC_TYPE, MTC_OPTION, PART_ITEM_NO, PART_NO, PART_SECTION_CODE))
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUPM1
 DATA CAPTURE CHANGES
 PCTFREE 0
 LOCKSIZE ROW
 APPEND OFF
 NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUPM1 IS 'RMT VIOS UnitPart Table';

CREATE TRIGGER VIOS.PVUPM1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUPM1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUPM1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.PVUWX1  (
  MAINTENANCE_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  CONCERN_POINT VARCHAR(150) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT PVUWX1_PK PRIMARY KEY
    (MAINTENANCE_ID, CONCERN_POINT))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.PVUWX1
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.PVUWX1 IS 'RMT VIOS UnitConcernPoint Table';

CREATE TRIGGER VIOS.PVUWX1_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.PVUWX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.PVUWX1_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.PVUWX1
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TABLE VIOS.TBLKNOWLEDGESTATUS  (
  USER_LOGON_ID_NO CHAR(7) NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(18,0) NOT NULL ,
  MTC_MODEL CHAR(3) NOT NULL ,
  PROCESS_NO CHAR(5) NOT NULL ,
  PROCLINENO CHAR(1) NOT NULL ,
  PROCTEAM CHAR(4) NOT NULL ,
  PROCDESC CHAR(35) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  KNOWLEDGESTATUS_NO INTEGER NOT NULL ,
  ENTEREDBY_UID CHAR(7) NOT NULL ,
  ENTERED_TSTP TIMESTAMP NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  KNOWLEDGE_NOTE_TEXT VARCHAR(250) ,
  PRODRATE INTEGER,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLKNOWLEDGESTATUS_PK PRIMARY KEY
    (USER_LOGON_ID_NO,
     PROCESS_ID,
     MODEL_YEAR_DATE,
     MTC_MODEL))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLKNOWLEDGESTATUS
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLKNOWLEDGESTATUS IS 'RMT VIOS TBLKNOWLEDGESTATUS';

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLKNOWLEDGESTATUS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLKNOWLEDGESTATUS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I1 ON VIOS.TBLKNOWLEDGESTATUS
(USER_LOGON_ID_NO ASC,
 PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)

COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.TBLKNOWLEDGESTATUS_I2 ON VIOS.TBLKNOWLEDGESTATUS
(PROCESS_ID ASC,
 MODEL_YEAR_DATE ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.TBLROTATION  (
  ROTATEREC_NO INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  PCAREA_ID INTEGER NOT NULL ,
  TEAM_NO CHAR(4) NOT NULL ,
  TEAM_GROUP_ID INTEGER NOT NULL ,
  RECORDDATE TIMESTAMP NOT NULL ,
  RECORDSHIFT SMALLINT NOT NULL ,
  RECORDQTR SMALLINT NOT NULL ,
  MPTAG_NO INTEGER NOT NULL ,
  TAG_GROUP_ID INTEGER NOT NULL ,
  USER_LOGON_ID_NO CHAR(7) NOT NULL ,
  PAIRTYPE SMALLINT NOT NULL ,
  ENTEREDBY_UID CHAR(7) NOT NULL ,
  ENTERED_TSTP TIMESTAMP NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL ,
  ERGOTYPE CHAR(1) ,
  COMMENT VARCHAR(250) ,
  REASONCODE SMALLINT,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLROTATION_PK PRIMARY KEY
    (ROTATEREC_NO))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLROTATION
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLROTATION IS 'RMT VIOS TBLROTATION';

CREATE TRIGGER VIOS.TBLROTATION_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLROTATION_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX VIOS.TBLROTATION_I1 ON VIOS.TBLROTATION
(PCAREA_ID ASC,
 TEAM_NO ASC,
 RECORDDATE ASC,
 USER_LOGON_ID_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;


CREATE INDEX VIOS.TBLROTATION_I2 ON VIOS.TBLROTATION
(MPTAG_NO ASC)

COMPRESS NO ALLOW REVERSE SCANS;

CREATE TABLE VIOS.TBLROTATION_PROCESS  (
  ROTATION_PROCESS_ID INTEGER NOT NULL ,
  ROTATEREC_NO INTEGER NOT NULL ,
  PROCESS_ID INTEGER NOT NULL ,
  PLANT_LOC_CODE CHAR(1) NOT NULL ,
  BODY_LOC_NO CHAR(4) NOT NULL ,
  ASM_PROC_NO CHAR(5) NOT NULL ,
  ASM_PROC_NAME CHAR(35) NOT NULL ,
  VEHICLE_MODEL_CODE CHAR(1) NOT NULL ,
  VMC_DESCRIPTION CHAR(35) NOT NULL ,
  MODEL_YEAR_DATE DECIMAL(5,1) NOT NULL ,
  PROD_SCH_QTY INTEGER NOT NULL ,
  EFF_BEG_DATE TIMESTAMP NOT NULL ,
  EFF_END_DATE TIMESTAMP NOT NULL ,
  PROCESS_STATUS SMALLINT NOT NULL ,
  DAYSFLAG VARCHAR(1) NOT NULL ,
  EXTRACT_DATE TIMESTAMP NOT NULL ,
  DEPT_CODE CHAR(2) NOT NULL,
  CREATE_TIMESTAMP   TIMESTAMP,
  UPDATE_TIMESTAMP   TIMESTAMP,
  CONSTRAINT TBLROTATION_PROCESS_PK PRIMARY KEY
    (ROTATEREC_NO,
     PROCESS_ID))
   IN VIOSTBSDAT1
   INDEX IN VIOSTBSIDX1;

ALTER TABLE VIOS.TBLROTATION_PROCESS
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.TBLROTATION_PROCESS IS 'RMT VIOS TBLROTATION_PROCESS';

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.TBLROTATION_PROCESS_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.TBLROTATION_PROCESS
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;