CREATE INDEX GALADM.MC_OP_EFFICIENCY_HIST_I2 ON GALADM.MC_OP_EFFICIENCY_HIST_TBX
   ("PROCESS_POINT_ID" ASC, "STATUS" ASC, "PRODUCT_ID"
   ASC, "HOST_NAME" ASC, "END_TIMESTAMP" ASC);

CREATE INDEX GALADM.FIF_CODE_CHOICES_I2 ON GALADM.FIF_CODE_CHOICES_TBX 
	(MODEL_YEAR ASC, FIF_TYPE ASC, FIF_CODE ASC);

ALTER TABLE GALADM.GAL212TBX ADD DEMAND_TYPE CHAR(2);

REORG TABLE  GALADM.GAL212TBX;
