ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE NONE;
DROP INDEX GALADM.QI_DEFECT_RESULT_I4;
DROP INDEX GALADM.QI_DEFECT_RESULT_I6;
DROP INDEX GALADM.QI_DEFECT_RESULT_I7;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX RENAME COLUMN DATE TO PRODUCTION_DATE;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN ENTRY_SCREEN VARCHAR(40);
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN ENGINE_FIRING_FLAG SMALLINT;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DROP COLUMN ORIGINAL_DEFECTRESULTID;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX ADD COLUMN INCIDENT_ID INTEGER;
ALTER TABLE GALADM.QI_DEFECT_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_DEFECT_RESULT_TBX;
CREATE INDEX GALADM.QI_DEFECT_RESULT_I4
  ON GALADM.QI_DEFECT_RESULT_TBX (PRODUCTION_DATE ASC, ENTRY_DEPT ASC, CURRENT_DEFECT_STATUS ASC, SHIFT ASC, PRODUCT_ID ASC);
CREATE INDEX GALADM.QI_DEFECT_RESULT_I6
  ON GALADM.QI_DEFECT_RESULT_TBX (APPLICATION_ID ASC, PRODUCT_ID ASC, SHIFT ASC, PRODUCTION_DATE ASC);    
CREATE INDEX GALADM.QI_DEFECT_RESULT_I7
  ON GALADM.QI_DEFECT_RESULT_TBX (PRODUCTION_DATE ASC, ORIGINAL_DEFECT_STATUS ASC, APPLICATION_ID ASC, SHIFT ASC, PRODUCT_ID ASC);      

ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE NONE;
DROP INDEX GALADM.QI_REPAIR_RESULT_I5;
DROP INDEX GALADM.QI_REPAIR_RESULT_I7;
DROP INDEX GALADM.QI_REPAIR_RESULT_I8;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX RENAME COLUMN DATE TO PRODUCTION_DATE;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN ENTRY_SCREEN VARCHAR(40);
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN ENGINE_FIRING_FLAG SMALLINT;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX ADD COLUMN INCIDENT_ID INTEGER;
ALTER TABLE GALADM.QI_REPAIR_RESULT_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_REPAIR_RESULT_TBX;
CREATE INDEX GALADM.QI_REPAIR_RESULT_I5
  ON GALADM.QI_REPAIR_RESULT_TBX (PRODUCTION_DATE ASC, ENTRY_DEPT ASC, CURRENT_DEFECT_STATUS ASC, SHIFT ASC, PRODUCT_ID ASC);      
CREATE INDEX GALADM.QI_REPAIR_RESULT_I7
  ON GALADM.QI_REPAIR_RESULT_TBX (APPLICATION_ID ASC, PRODUCT_ID ASC, SHIFT ASC, PRODUCTION_DATE ASC);    
CREATE INDEX GALADM.QI_REPAIR_RESULT_I8
  ON GALADM.QI_REPAIR_RESULT_TBX (PRODUCTION_DATE ASC, ORIGINAL_DEFECT_STATUS ASC, APPLICATION_ID ASC, SHIFT ASC, PRODUCT_ID ASC);      

