ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_ID_TBX ADD COLUMN IS_EXT_SYS_REPAIR_REQD SMALLINT WITH DEFAULT 0;
ALTER TABLE GALADM.QI_EXTERNAL_SYSTEM_DEFECT_MAP_TBX ADD COLUMN IS_EXT_SYS_REPAIR_REQD SMALLINT WITH DEFAULT 0;
