ALTER TABLE GALADM.GAL215TBX ADD COLUMN DEVICE_ID VARCHAR(32);
ALTER TABLE GALADM.HEAD_HISTORY_TBX ADD COLUMN DEVICE_ID VARCHAR(32);
ALTER TABLE GALADM.BLOCK_HISTORY_TBX ADD COLUMN DEVICE_ID VARCHAR(32);
ALTER TABLE GALADM.CONROD_HISTORY_TBX ADD COLUMN DEVICE_ID VARCHAR(32);
ALTER TABLE GALADM.CRANKSHAFT_HISTORY_TBX ADD COLUMN DEVICE_ID VARCHAR(32);
