 CREATE INDEX GALADM.GAL215_I4
  ON GALADM.GAL215TBX
   ( PROCESS_POINT_ID ASC, PRODUCT_SPEC_CODE ASC, PRODUCT_ID ASC, ACTUAL_TIMESTAMP ASC ) 
   ALLOW REVERSE SCANS COLLECT STATISTICS
   COMPRESS NO;