CREATE INDEX GALADM.HEAD_BUILD_RESULTS_I1 
ON GALADM.HEAD_BUILD_RESULTS_TBX 
( PART_NAME ASC, RESULT_VALUE ASC ) 
ALLOW REVERSE SCANS 
COMPRESS NO; 
CREATE INDEX GALADM.BLOCK_BUILD_RESULTS_I1 
ON GALADM.BLOCK_BUILD_RESULTS_TBX 
( PART_NAME ASC, RESULT_VALUE ASC ) 
ALLOW REVERSE SCANS 
COMPRESS NO; 
