--QSR_TBX
DROP TRIGGER GALADM.QSR_TR2;
DROP TRIGGER GALADM.QSR_TR1;
DROP TABLE GALADM.QSR_TBX;

CREATE TABLE GALADM.QSR_TBX  (
	QSR_ID INTEGER NOT NULL , 
	PROCESS_LOCATION VARCHAR(2) , 
	DESCRIPTION VARCHAR(80) , 
	QSR_STATUS INTEGER , 
	COMMENT VARCHAR(80) , 
	APPROVER_NAME VARCHAR(30) , 
	UPDATE_TIMESTAMP TIMESTAMP,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL 
)   

IN GALTBSREF12
INDEX IN GALTBSIDX4;

CREATE UNIQUE INDEX GALADM.QSR_l1 ON GALADM.QSR_TBX (QSR_ID ASC) ALLOW REVERSE SCANS;
ALTER TABLE GALADM.QSR_TBX ADD PRIMARY KEY (QSR_ID);

CREATE TRIGGER GALADM.QSR_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QSR_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

--GAL147TBX
--DROP INDEX GALADM.GAL147_l2;
CREATE INDEX GALADM.GAL147_l2 ON GALADM.GAL147TBX (QSR_ID) ALLOW REVERSE SCANS;













