------------------------------------------------
-- DDL Statements for Table "VIOS"."QI_DEFECT_RESP_ASSOCIATE_TBX"
------------------------------------------------

DROP TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR1;
DROP TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR2;
DROP TABLE VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX;

CREATE TABLE VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX  (
				  QFS_DEFECT_NO INTEGER NOT NULL,
				  SITE CHAR(16) NOT NULL,
				  ASSOCIATE_ID CHAR(7) NOT NULL,
				  STATUS SMALLINT,
  				  CREATE_TIMESTAMP TIMESTAMP,
				  UPDATE_TIMESTAMP TIMESTAMP)
 IN VIOSTBSDAT1
 INDEX IN VIOSTBSIDX1;

CREATE UNIQUE INDEX VIOS.QI_DEFECT_RESP_ASSOCIATE_I1 ON VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
        (QFS_DEFECT_NO, SITE) ALLOW REVERSE SCANS;

ALTER TABLE VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
        ADD CONSTRAINT QI_DEFECT_RESP_ASSOCIATE_PK PRIMARY KEY
                (QFS_DEFECT_NO, SITE);

ALTER TABLE VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
DATA CAPTURE CHANGES
PCTFREE 0
LOCKSIZE ROW
APPEND OFF
NOT VOLATILE;

COMMENT ON TABLE VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX IS 'NAQ Responsible Associate Data for MDRS';

SET CURRENT SCHEMA = "VIOS";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","VIOS";
CREATE TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR1
   NO CASCADE BEFORE INSERT
   ON VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER VIOS.QI_DEFECT_RESP_ASSOCIATE_TR2
   NO CASCADE BEFORE UPDATE
   ON VIOS.QI_DEFECT_RESP_ASSOCIATE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for View "GALADM"."QI_GALC_TO_MDRS_TBV"
------------------------------------------------

--drop view if exist
DROP VIEW GALADM.QI_GALC_TO_MDRS_TBV;

--create view
SET CURRENT SCHEMA = "GALADM";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";

CREATE VIEW GALADM.QI_GALC_TO_MDRS_TBV AS

SELECT DISTINCT 
QDRT.AF_ON_SEQUENCE_NUMBER AS "ASSY_SEQ_NO", 
QDRT.ACTUAL_TIMESTAMP AS "DATA_ENTRY_TSTP",
QDRT.INSPECTION_PART_NAME || QDRT.INSPECTION_PART_LOCATION_NAME || QDRT.INSPECTION_PART_LOCATION2_NAME || 
QDRT.INSPECTION_PART2_NAME || QDRT.INSPECTION_PART2_LOCATION_NAME || QDRT.INSPECTION_PART2_LOCATION2_NAME || 
QDRT.INSPECTION_PART3_NAME || QDRT.DEFECT_TYPE_NAME || QDRT.DEFECT_TYPE_NAME2 AS "DEFECT_DESC_TEXT",
QDRT.DEFECT_TYPE_NAME AS "DEFECT_NAME",
QPT.SITE AS "ENT_PLANT_LOC_CODE",
QDRT.SHIFT AS "ENTER_WORK_SHIFT",
GAL128.DIVISION_ID AS "ENTRY_DEPT_NO",
QDRT.ENTRY_MODEL AS "ENTRY_MTC_MODEL",
QDRT.ENTRY_MODEL AS "ENTRY_MTC_MODEL_NAME",
'' AS "ENTRY_SUB_DEPT_NO",
QDRT.CURRENT_DEFECT_STATUS AS "FIXED_DEFECT_CODE",
QDRT.CREATE_TIMESTAMP AS "INSERT_TSTP",
'ADD' AS "LAST_PROCESS_ACTION",
GAL133.MODEL_YEAR_DESCRIPTION AS "MODEL_YEAR",
GAL133.MODEL_CODE AS "MTC_MODEL",
GAL133.MODEL_CODE AS "MTC_MODEL_NAME",
GAL211.PROD_LINE_NO AS "PROC_ASM_LINE_NO",
QDRT.PROCESS_NUMBER AS "PROCESS_NO",
QDRT.PRODUCT_ID AS "PROD_UNIT_ID_NO",
QDRT.PRODUCT_TYPE AS "PROD_UNIT_TY_CODE",
QDRT.DEFECTRESULTID AS "QFS_DEFECT_NO",
QDRT.ORIGINAL_DEFECT_STATUS AS "REPAIRED_SW",
QDRT.RESPONSIBLE_DEPT AS "RESP_DEPT_Main_No",
GAL211.SITE_NAME AS "RESP_PLANT_LOC_CDE",
QDRT.RESPONSIBLE_LEVEL1 AS "RESP_TEAM_NO",

(SELECT SUM(QARMT.REPAIR_TIME) FROM GALADM.QI_APPLIED_REPAIR_METHOD_TBX QARMT
INNER JOIN GALADM.QI_REPAIR_RESULT_TBX QRRT ON QARMT.REPAIR_ID = QRRT.REPAIR_ID
AND QDRT.DEFECTRESULTID = QRRT.DEFECTRESULTID
GROUP BY QDRT.DEFECTRESULTID
) AS "TOTAl_REPAIR_MINUTES",

QDRT.UNIT_NUMBER AS "UNIT_NO",
'' AS "UNIT_RANK",
'' AS "VehicleModelCode"

FROM GALADM.QI_DEFECT_RESULT_TBX QDRT
INNER JOIN GALADM.GAL133TBX GAL133 ON QDRT.PRODUCT_SPEC_CODE = GAL133.PRODUCT_SPEC_CODE 
INNER JOIN GALADM.GAL211TBX GAL211 ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(GAL211.SITE_NAME) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(GAL211.PLANT_NAME)
INNER JOIN GALADM.GAL128TBX GAL128 ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(GAL128.SITE_NAME) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(GAL128.PLANT_NAME) AND UPPER(QDRT.ENTRY_DEPT)=UPPER(GAL128.DIVISION_ID)
INNER JOIN GALADM.QI_PLANT_TBX QPT ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(QPT.SITE) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(QPT.PLANT)
WHERE QDRT.CREATE_TIMESTAMP  BETWEEN CURRENT DATE - 1 DAY AND  CURRENT DATE 
AND QDRT.PRODUCT_TYPE = 'ENGINE'

UNION ALL

SELECT DISTINCT 
QDRT.AF_ON_SEQUENCE_NUMBER AS "ASSY_SEQ_NO", 
QDRT.ACTUAL_TIMESTAMP AS "DATA_ENTRY_TSTP",
QDRT.INSPECTION_PART_NAME || QDRT.INSPECTION_PART_LOCATION_NAME || QDRT.INSPECTION_PART_LOCATION2_NAME || 
QDRT.INSPECTION_PART2_NAME || QDRT.INSPECTION_PART2_LOCATION_NAME || QDRT.INSPECTION_PART2_LOCATION2_NAME || 
QDRT.INSPECTION_PART3_NAME || QDRT.DEFECT_TYPE_NAME || QDRT.DEFECT_TYPE_NAME2 AS "DEFECT_DESC_TEXT",
QDRT.DEFECT_TYPE_NAME AS "DEFECT_NAME",
QPT.SITE AS "ENT_PLANT_LOC_CODE",
QDRT.SHIFT AS "ENTER_WORK_SHIFT",
GAL128.DIVISION_ID AS "ENTRY_DEPT_NO",
QDRT.ENTRY_MODEL AS "ENTRY_MTC_MODEL",
QDRT.ENTRY_MODEL AS "ENTRY_MTC_MODEL_NAME",
'' AS "ENTRY_SUB_DEPT_NO",
QDRT.CURRENT_DEFECT_STATUS AS "FIXED_DEFECT_CODE",
QDRT.CREATE_TIMESTAMP AS "INSERT_TSTP",
'ADD' AS "LAST_PROCESS_ACTION",
GAL144.MODEL_YEAR_DESCRIPTION AS "MODEL_YEAR",
GAL144.MODEL_CODE AS "MTC_MODEL",
GAL144.MODEL_CODE AS "MTC_MODEL_NAME",
GAL211.PROD_LINE_NO AS "PROC_ASM_LINE_NO",
QDRT.PROCESS_NUMBER AS "PROCESS_NO",
QDRT.PRODUCT_ID AS "PROD_UNIT_ID_NO",
QDRT.PRODUCT_TYPE AS "PROD_UNIT_TY_CODE",
QDRT.DEFECTRESULTID AS "QFS_DEFECT_NO",
QDRT.ORIGINAL_DEFECT_STATUS AS "REPAIRED_SW",
QDRT.RESPONSIBLE_DEPT AS "RESP_DEPT_Main_No",
GAL211.SITE_NAME AS "RESP_PLANT_LOC_CDE",
QDRT.RESPONSIBLE_LEVEL1 AS "RESP_TEAM_NO",

(SELECT SUM(QARMT.REPAIR_TIME) FROM GALADM.QI_APPLIED_REPAIR_METHOD_TBX QARMT
INNER JOIN GALADM.QI_REPAIR_RESULT_TBX QRRT ON QARMT.REPAIR_ID = QRRT.REPAIR_ID
AND QDRT.DEFECTRESULTID = QRRT.DEFECTRESULTID
GROUP BY QDRT.DEFECTRESULTID
) AS "TOTAl_REPAIR_MINUTES",

QDRT.UNIT_NUMBER AS "UNIT_NO",
'' AS "UNIT_RANK",
'' AS "VehicleModelCode"

FROM GALADM.QI_DEFECT_RESULT_TBX QDRT
INNER JOIN GALADM.GAL144TBX GAL144 ON QDRT.PRODUCT_SPEC_CODE = GAL144.PRODUCT_SPEC_CODE
INNER JOIN GALADM.GAL211TBX GAL211 ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(GAL211.SITE_NAME) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(GAL211.PLANT_NAME)
INNER JOIN GALADM.GAL128TBX GAL128 ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(GAL128.SITE_NAME) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(GAL128.PLANT_NAME) AND UPPER(QDRT.ENTRY_DEPT)=UPPER(GAL128.DIVISION_ID)
INNER JOIN GALADM.QI_PLANT_TBX QPT ON UPPER(QDRT.ENTRY_SITE_NAME) = UPPER(QPT.SITE) AND UPPER(QDRT.ENTRY_PLANT_NAME) = UPPER(QPT.PLANT)
WHERE QDRT.CREATE_TIMESTAMP  BETWEEN CURRENT DATE - 1 DAY AND  CURRENT DATE 
AND QDRT.PRODUCT_TYPE = 'FRAME';
