-- RGALCDEV-4444
SET SCHEMA GALADM;

DROP TRIGGER GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TR1;
DROP TRIGGER GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TR2;
DROP TABLE GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TBX;

DROP TRIGGER GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TR1;
DROP TRIGGER GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TR2;
DROP TABLE GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX;

CREATE TABLE "GALADM"."MC_ORDER_STRU_FOR_PROCESS_POINT_TBX" (
    "ORDER_NO" CHARACTER(20) NOT NULL,
    "PROCESS_POINT_ID" CHARACTER(16) NOT NULL,
    "PRODUCT_SPEC_CODE" CHARACTER(30) NOT NULL,
    "STRUCTURE_REV" BIGINT NOT NULL,
    "DIVISION_ID" CHARACTER(16) NOT NULL DEFAULT,
    "CREATE_TIMESTAMP" TIMESTAMP,
    "UPDATE_TIMESTAMP" TIMESTAMP)
    IN "GALTBSREF12"
    INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."MC_ORDER_STRU_FOR_PROCESS_POINT_TBX"
     DATA CAPTURE CHANGES
     PCTFREE 0
     LOCKSIZE ROW
     APPEND OFF
     NOT VOLATILE;

COMMENT ON TABLE "GALADM"."MC_ORDER_STRU_FOR_PROCESS_POINT_TBX" IS 'RMT MC_ORDER_STRU_FOR_PROCESS_POINT_TBX is used by Manufacturing Control to define the structure revision for process point that should be used to manufacture this order / lot';

CREATE UNIQUE INDEX GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_I1 ON GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TBX
  (ORDER_NO ASC, PROCESS_POINT_ID ASC);

ALTER TABLE "GALADM"."MC_ORDER_STRU_FOR_PROCESS_POINT_TBX"
  ADD CONSTRAINT "MC_ORDER_STRU_FOR_PROCESS_POINT_PK" PRIMARY KEY
    ("ORDER_NO", "PROCESS_POINT_ID");

CREATE TRIGGER GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TR1
    NO CASCADE BEFORE INSERT
    ON GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TBX
    REFERENCING NEW AS A
    FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TR2
    NO CASCADE BEFORE UPDATE
    ON GALADM.MC_ORDER_STRU_FOR_PROCESS_POINT_TBX
    REFERENCING NEW AS A
    FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
    
    
CREATE TABLE "GALADM"."MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX" (
    "PRODUCT_ID" CHARACTER(17) NOT NULL,
    "PROCESS_POINT_ID" CHARACTER(16) NOT NULL,
    "PRODUCT_SPEC_CODE" CHARACTER(30) NOT NULL,
    "STRUCTURE_REV" BIGINT NOT NULL,
    "DIVISION_ID" CHARACTER(16) NOT NULL DEFAULT,
    "CREATE_TIMESTAMP" TIMESTAMP,
    "UPDATE_TIMESTAMP" TIMESTAMP)
    IN "GALTBSREF12"
    INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX"
     DATA CAPTURE CHANGES
     PCTFREE 0
     LOCKSIZE ROW
     APPEND OFF
     NOT VOLATILE;

COMMENT ON TABLE "GALADM"."MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX" IS 'RMT MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX is used by Manufacturing Control to define the structure revision for process point that should be used to manufacture this PRODUCT';

CREATE UNIQUE INDEX GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_I1 ON GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX
   (PRODUCT_ID ASC, PROCESS_POINT_ID ASC, PRODUCT_SPEC_CODE ASC);

ALTER TABLE "GALADM"."MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX"
  ADD CONSTRAINT "MC_PRODUCT_STRU_FOR_PROCESS_POINT_PK" PRIMARY KEY
    ("PRODUCT_ID", "PROCESS_POINT_ID", "PRODUCT_SPEC_CODE");

CREATE TRIGGER GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TR1
    NO CASCADE BEFORE INSERT
    ON GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX
    REFERENCING NEW AS A
    FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TR2
    NO CASCADE BEFORE UPDATE
    ON GALADM.MC_PRODUCT_STRU_FOR_PROCESS_POINT_TBX
    REFERENCING NEW AS A
    FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;    