------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_AREA_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_AREA_TR1;
DROP TRIGGER GALADM.GTS_AREA_TR2;
DROP TABLE GALADM.GTS_AREA_TBX;
 

CREATE TABLE "GALADM  "."GTS_AREA_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "AREA_DESCRIPTION" VARCHAR(40) , 
		  "PRODUCT_TYPE" CHAR(40) , 
		  "TAG_TYPE" SMALLINT , 
		  "IS_ENABLED" SMALLINT , 
		  "TRACKING_MODE" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_AREA_TBX" IS 'GTS Area';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."PRODUCT_TYPE" IS 'Engine or Vehicle or ...';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."TAG_TYPE" IS 'TAG_TYPE - SMART EYE | RF TAG ....     NONE - NO Tag (In this case no carrier product association)     SMART_EYE     RF_TAG';

COMMENT ON COLUMN "GALADM  "."GTS_AREA_TBX"."TRACKING_MODE" IS 'production mode, maintenance mode. when in maintenance mode, the configuration (layout, bitmap etc) can be changed. When in production mode, configuration is not allowed to be changed ';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_AREA_TBX"

ALTER TABLE "GALADM  "."GTS_AREA_TBX" 
	ADD CONSTRAINT "GTS_AREA_PK" PRIMARY KEY
		("TRACKING_AREA");

CREATE TRIGGER GALADM.GTS_AREA_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_AREA_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_AREA_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_AREA_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_CARRIER_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_CARRIER_TR1;
DROP TRIGGER GALADM.GTS_CARRIER_TR2;
DROP TABLE GALADM.GTS_CARRIER_TBX;

CREATE TABLE "GALADM  "."GTS_CARRIER_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "CARRIER_NUMBER" VARCHAR(40) NOT NULL , 
		  "PRODUCT_ID" VARCHAR(40) , 
		  "CARRIER_TYPE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_CARRIER_TBX" IS 'GTS Carrier';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_CARRIER_TBX" 
	ADD CONSTRAINT "GTS_CARRIER_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "CARRIER_NUMBER");

CREATE TRIGGER GALADM.GTS_CARRIER_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_CARRIER_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_CARRIER_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_CARRIER_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_CLIENT_LIST_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_CLIENT_LIST_TR1;
DROP TRIGGER GALADM.GTS_CLIENT_LIST_TR2;
DROP TABLE GALADM.GTS_CLIENT_LIST_TBX;

CREATE TABLE "GALADM  "."GTS_CLIENT_LIST_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "CLIENT_IP" VARCHAR(40) NOT NULL , 
		  "CLIENT_PORT" SMALLINT NOT NULL , 
		  "CLIENT_NAME" VARCHAR(40) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" IS 'GTS Client List';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_CLIENT_LIST_TBX"

ALTER TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" 
	ADD CONSTRAINT "GTS_CLIENT_LIST_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "CLIENT_IP",
		 "CLIENT_PORT");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_CLIENT_LIST_TBX"

ALTER TABLE "GALADM  "."GTS_CLIENT_LIST_TBX" 
	ADD CONSTRAINT "AREA_CLIENT_LIST_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;


CREATE TRIGGER GALADM.GTS_CLIENT_LIST_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_CLIENT_LIST_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_CLIENT_LIST_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_CLIENT_LIST_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_COLOR_MAP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_COLOR_MAP_TR1;
DROP TRIGGER GALADM.GTS_COLOR_MAP_TR2;
DROP TABLE GALADM.GTS_COLOR_MAP_TBX;

CREATE TABLE "GALADM  "."GTS_COLOR_MAP_TBX"  (
		  "TRACKING_AREA" VARCHAR(5) NOT NULL , 
		  "COLOR_ID" SMALLINT NOT NULL , 
		  "COLOR_CODE" VARCHAR(8) NOT NULL , 
		  "COLOR" VARCHAR(8) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_COLOR_MAP_TBX" IS 'GTS Color Map';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_COLOR_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_COLOR_MAP_TBX" 
	ADD CONSTRAINT "GTS_COLOR_MAP_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "COLOR_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_COLOR_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_COLOR_MAP_TBX" 
	ADD CONSTRAINT "AREA_COLOR_MAP_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_COLOR_MAP_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_COLOR_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_COLOR_MAP_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_COLOR_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_DECISION_POINT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_DECISION_POINT_TR1;
DROP TRIGGER GALADM.GTS_DECISION_POINT_TR2;
DROP TABLE GALADM.GTS_DECISION_POINT_TBX;

CREATE TABLE "GALADM  "."GTS_DECISION_POINT_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "DP_ID" SMALLINT NOT NULL , 
		  "DECISION_POINT_NAME" VARCHAR(10) , 
		  "DECISION_POINT_DESCRIPTION" VARCHAR(40) , 
		  "RULE_CLASS" VARCHAR(100) , 
		  "ENABLED" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "TIME_INTERVAL" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ;  

COMMENT ON TABLE "GALADM  "."GTS_DECISION_POINT_TBX" IS 'GTS Decision Point';

COMMENT ON COLUMN "GALADM  "."GTS_DECISION_POINT_TBX"."ENABLED" IS 'Flag to indicate if the control is currently in use';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_DECISION_POINT_TBX"

ALTER TABLE "GALADM  "."GTS_DECISION_POINT_TBX" 
	ADD CONSTRAINT "GTS_DECISION_POINT_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "DP_ID");


-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_DECISION_POINT_TBX"

ALTER TABLE "GALADM  "."GTS_DECISION_POINT_TBX" 
	ADD CONSTRAINT "AREA_DECISION_POINT_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_DECISION_POINT_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_DECISION_POINT_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_DECISION_POINT_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_DECISION_POINT_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_INDICATOR_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_INDICATOR_TR1;
DROP TRIGGER GALADM.GTS_INDICATOR_TR2;
DROP TABLE GALADM.GTS_INDICATOR_TBX;

CREATE TABLE "GALADM  "."GTS_INDICATOR_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "INDICATOR_NAME" VARCHAR(30) NOT NULL , 
		  "INDICATOR_VALUE" VARCHAR(10) , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_INDICATOR_TBX" IS 'GTS Indicator';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_INDICATOR_TBX"

ALTER TABLE "GALADM  "."GTS_INDICATOR_TBX" 
	ADD CONSTRAINT "GTS_INDICATOR_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "INDICATOR_NAME");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_INDICATOR_TBX"

ALTER TABLE "GALADM  "."GTS_INDICATOR_TBX" 
	ADD CONSTRAINT "AREA_TO_INDICATOR_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_INDICATOR_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_INDICATOR_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_INDICATOR_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_INDICATOR_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_DP_CONDITION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_DP_CONDITION_TR1;
DROP TRIGGER GALADM.GTS_DP_CONDITION_TR2;
DROP TABLE GALADM.GTS_DP_CONDITION_TBX;

CREATE TABLE "GALADM  "."GTS_DP_CONDITION_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "DP_ID" SMALLINT NOT NULL , 
		  "INDICATOR_ID" VARCHAR(30) NOT NULL , 
		  "REQUIRED_VALUE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_DP_CONDITION_TBX" IS 'GTS Decision Point Condition';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_DP_CONDITION_TBX"

ALTER TABLE "GALADM  "."GTS_DP_CONDITION_TBX" 
	ADD CONSTRAINT "GTS_DP_CONDITION_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "DP_ID",
		 "INDICATOR_ID");

ALTER TABLE "GALADM  "."GTS_DP_CONDITION_TBX" 
	ADD CONSTRAINT "DP_CONDITION_TO_INDICATOR_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "INDICATOR_ID")
	REFERENCES "GALADM  "."GTS_INDICATOR_TBX"
		("TRACKING_AREA",
		 "INDICATOR_NAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_DP_CONDITION_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_DP_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_DP_CONDITION_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_DP_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_NODE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_NODE_TR1;
DROP TRIGGER GALADM.GTS_NODE_TR2;
DROP TABLE GALADM.GTS_NODE_TBX;

CREATE TABLE "GALADM  "."GTS_NODE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "NODE_ID" SMALLINT NOT NULL , 
		  "NODE_NAME" VARCHAR(40) , 
		  "STATUS" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "NODE_TYPE" SMALLINT , 
		  "IS_VISIBLE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "IS_USER_SETTABLE" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "X" INTEGER , 
		  "Y" INTEGER , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE "GALADM  "."GTS_NODE_TBX" IS 'GTS Node';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_NODE_TBX"

ALTER TABLE "GALADM  "."GTS_NODE_TBX" 
	ADD CONSTRAINT "GTS_NODE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "NODE_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_NODE_TBX"

ALTER TABLE "GALADM  "."GTS_NODE_TBX" 
	ADD CONSTRAINT "AREA_TO_NODE_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_NODE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_NODE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_NODE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_NODE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LABEL_TBX"
------------------------------------------------


DROP TRIGGER GALADM.GTS_LABEL_TR1;
DROP TRIGGER GALADM.GTS_LABEL_TR2;
DROP TABLE GALADM.GTS_LABEL_TBX;

CREATE TABLE "GALADM  "."GTS_LABEL_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "LABEL_ID" INTEGER NOT NULL , 
		  "LABEL_TEXT" VARCHAR(40) , 
		  "LABEL_FONT" VARCHAR(40) , 
		  "BORDER_TYPE" SMALLINT , 
		  "BORDER_COLOR" VARCHAR(8) , 
		  "TEXT_COLOR" VARCHAR(8) , 
		  "BACK_COLOR" VARCHAR(8) , 
		  "X" SMALLINT , 
		  "Y" SMALLINT , 
		  "X_EXTENT" SMALLINT , 
		  "Y_EXTENT" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ;  

COMMENT ON TABLE "GALADM  "."GTS_LABEL_TBX" IS 'GTS Label';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LABEL_TBX"

ALTER TABLE "GALADM  "."GTS_LABEL_TBX" 
	ADD CONSTRAINT "GTS_LABEL_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LABEL_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LABEL_TBX"

ALTER TABLE "GALADM  "."GTS_LABEL_TBX" 
	ADD CONSTRAINT "LABEL_TO_AREA_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_LABEL_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_LABEL_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_LABEL_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_LABEL_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_CARRIER_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_LANE_CARRIER_TR1;
DROP TRIGGER GALADM.GTS_LANE_CARRIER_TR2;
DROP TABLE GALADM.GTS_LANE_CARRIER_TBX;

CREATE TABLE "GALADM  "."GTS_LANE_CARRIER_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "LANE_ID" VARCHAR(20) NOT NULL , 
		  "LANE_POSITION" TIMESTAMP NOT NULL , 
		  "LANE_CARRIER" VARCHAR(40) , 
		  "DISCREPANCY_STATUS" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" IS 'GTS Lane Carrier';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" 
	ADD CONSTRAINT "GTS_LANE_CARRIER_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID",
		 "LANE_POSITION");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_CARRIER_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_CARRIER_TBX" 
	ADD CONSTRAINT "LANE_TO_CARRIER_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_CARRIER")
	REFERENCES "GALADM  "."GTS_CARRIER_TBX"
		("TRACKING_AREA",
		 "CARRIER_NUMBER")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_LANE_CARRIER_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_LANE_CARRIER_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_LANE_CARRIER_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_LANE_CARRIER_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_LANE_TR1;
DROP TRIGGER GALADM.GTS_LANE_TR2;
DROP TABLE GALADM.GTS_LANE_TBX;

CREATE TABLE "GALADM  "."GTS_LANE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "LANE_ID" VARCHAR(20) NOT NULL , 
		  "LANE_DESCRIPTION" VARCHAR(40) , 
		  "LANE_CAPACITY" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "LANE_TYPE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "ENTRY_GATE_ID" SMALLINT , 
		  "EXIT_GATE_ID" SMALLINT , 
		  "CARRIER_PRESENT" SMALLINT , 
		  "IS_PHYSICALLY_FULL" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE "GALADM  "."GTS_LANE_TBX" IS 'GTS Lane';

COMMENT ON COLUMN "GALADM  "."GTS_LANE_TBX"."LANE_TYPE" IS 'Normal,Entry,Exit';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_TBX" 
	ADD CONSTRAINT "GTS_LANE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_TBX" 
	ADD CONSTRAINT "AREA_TO_LANE_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	DISABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_LANE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_LANE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_LANE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_LANE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_SEGMENT_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_LANE_SEGMENT_TR1;
DROP TRIGGER GALADM.GTS_LANE_SEGMENT_TR2;
DROP TABLE GALADM.GTS_LANE_SEGMENT_TBX;

CREATE TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "LANE_SEGMENT_ID" INTEGER NOT NULL , 
		  "LANE_SEGMENT_NAME" VARCHAR(40) , 
		  "INPUT_NODE_ID" INTEGER NOT NULL , 
		  "OUTPUT_NODE_ID" INTEGER NOT NULL , 
		  "LANE_SEGMENT_CAPACITY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "POWERED" SMALLINT NOT NULL WITH DEFAULT 1 , 
		  "INPUT_CPX" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "INPUT_CPY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "OUTPUT_CPX" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "OUTPUT_CPY" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "CARRIER_VISIBLE" INTEGER NOT NULL WITH DEFAULT 1 , 
		  "IS_SOURCE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "IS_DESTINATION" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF12
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" IS 'GTS Lane Segment';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_SEGMENT_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "GTS_LANE_SEGMENT_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_SEGMENT_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "AREA_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	DISABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "NODE_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "OUTPUT_NODE_ID")
	REFERENCES "GALADM  "."GTS_NODE_TBX"
		("TRACKING_AREA",
		 "NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	DISABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_TBX" 
	ADD CONSTRAINT "NODE_LANE_SEGMENT_FK2" FOREIGN KEY
		("TRACKING_AREA",
		 "INPUT_NODE_ID")
	REFERENCES "GALADM  "."GTS_NODE_TBX"
		("TRACKING_AREA",
		 "NODE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	DISABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_LANE_SEGMENT_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_LANE_SEGMENT_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR1;
DROP TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR2;
DROP TABLE GALADM.GTS_LANE_SEGMENT_MAP_TBX;

CREATE TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "LANE_ID" VARCHAR(20) NOT NULL , 
		  "LANE_SEQ" SMALLINT NOT NULL , 
		  "LANE_SEGMENT_ID" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN GALTBSREF11
		 INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" IS 'GTS Lane Segment Map';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "GTS_LANE_SEGMENT_MAP_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "LANE_ID",
		 "LANE_SEQ");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "LANE_TO_LANE_SEGMENT_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_ID")
	REFERENCES "GALADM  "."GTS_LANE_TBX"
		("TRACKING_AREA",
		 "LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_LANE_SEGMENT_MAP_TBX" 
	ADD CONSTRAINT "LANE_SEGMENT_LANE_SEGMENT_MAP_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID")
	REFERENCES "GALADM  "."GTS_LANE_SEGMENT_TBX"
		("TRACKING_AREA",
		 "LANE_SEGMENT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	DISABLE QUERY OPTIMIZATION;
	
CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_LANE_SEGMENT_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_LANE_SEGMENT_MAP_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_LANE_SEGMENT_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_MOVE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_MOVE_TR1;
DROP TRIGGER GALADM.GTS_MOVE_TR2;
DROP TABLE GALADM.GTS_MOVE_TBX;

CREATE TABLE "GALADM  "."GTS_MOVE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "SOURCE_LANE_ID" VARCHAR(20) NOT NULL , 
		  "DESTINATION_LANE_ID" VARCHAR(20) NOT NULL , 
		  "STATUS" SMALLINT NOT NULL WITH DEFAULT 2 , 
		  "DP_ID" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "ACTUAL_TIMESTAMP" TIMESTAMP , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_MOVE_TBX" IS 'GTS Move';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_MOVE_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_TBX" 
	ADD CONSTRAINT "GTS_MOVE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_MOVE_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_TBX" 
	ADD CONSTRAINT "LANE_DP_MOVE_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "DESTINATION_LANE_ID")
	REFERENCES "GALADM  "."GTS_LANE_TBX"
		("TRACKING_AREA",
		 "LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_MOVE_TBX" 
	ADD CONSTRAINT "LANE_DP_MOVE_FK2" FOREIGN KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID")
	REFERENCES "GALADM  "."GTS_LANE_TBX"
		("TRACKING_AREA",
		 "LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_MOVE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_MOVE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_MOVE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_MOVE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_MOVE_CONDITION_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_MOVE_CONDITION_TR1;
DROP TRIGGER GALADM.GTS_MOVE_CONDITION_TR2;
DROP TABLE GALADM.GTS_MOVE_CONDITION_TBX;

CREATE TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "SOURCE_LANE_ID" VARCHAR(20) NOT NULL , 
		  "DESTINATION_LANE_ID" VARCHAR(20) NOT NULL , 
		  "INDICATOR_ID" VARCHAR(30) NOT NULL , 
		  "REQUIRED_VALUE" SMALLINT NOT NULL WITH DEFAULT 0 , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" IS 'GTS Move Condition';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_MOVE_CONDITION_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "GTS_MOVE_CONDITION_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID",
		 "INDICATOR_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_MOVE_CONDITION_TBX"

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "MV_CONDITION_INDICATOR_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "INDICATOR_ID")
	REFERENCES "GALADM  "."GTS_INDICATOR_TBX"
		("TRACKING_AREA",
		 "INDICATOR_NAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "GALADM  "."GTS_MOVE_CONDITION_TBX" 
	ADD CONSTRAINT "MV_CONDITION_TO_MOVE_FK1" FOREIGN KEY
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID")
	REFERENCES "GALADM  "."GTS_MOVE_TBX"
		("TRACKING_AREA",
		 "SOURCE_LANE_ID",
		 "DESTINATION_LANE_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_MOVE_CONDITION_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_MOVE_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_MOVE_CONDITION_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_MOVE_CONDITION_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_OUTLINE_IMAGE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR1;
DROP TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR2;
DROP TABLE GALADM.GTS_OUTLINE_IMAGE_TBX;

CREATE TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX"  (
		  "IMAGE_ID" SMALLINT NOT NULL , 
		  "OUTLINE_IMAGE_DESCRIPTION" VARCHAR(40) , 
		  "IMAGE" BLOB(12768) LOGGED NOT COMPACT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX" IS 'GTS Outline Image';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_OUTLINE_IMAGE_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_IMAGE_TBX" 
	ADD CONSTRAINT "GTS_OUTLINE_IMAGE_PK" PRIMARY KEY
		("IMAGE_ID");


CREATE TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_OUTLINE_IMAGE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_OUTLINE_IMAGE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_OUTLINE_IMAGE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_OUTLINE_MAP_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_OUTLINE_MAP_TR1;
DROP TRIGGER GALADM.GTS_OUTLINE_MAP_TR2;
DROP TABLE GALADM.GTS_OUTLINE_MAP_TBX;

CREATE TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "OUTLINE_MAP_ID" SMALLINT NOT NULL , 
		  "MODEL_CODE" VARCHAR(5) NOT NULL , 
		  "IMAGE" BLOB(12768) LOGGED NOT COMPACT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ; 

COMMENT ON TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" IS 'GTS Outline Map';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_OUTLINE_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" 
	ADD CONSTRAINT "GTS_OUTLINE_MAP_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "OUTLINE_MAP_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_OUTLINE_MAP_TBX"

ALTER TABLE "GALADM  "."GTS_OUTLINE_MAP_TBX" 
	ADD CONSTRAINT "AREA_OUTLINE_MAP_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_OUTLINE_MAP_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_OUTLINE_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_OUTLINE_MAP_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_OUTLINE_MAP_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_SHAPE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_SHAPE_TR1;
DROP TRIGGER GALADM.GTS_SHAPE_TR2;
DROP TABLE GALADM.GTS_SHAPE_TBX;

CREATE TABLE "GALADM  "."GTS_SHAPE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "SHAPE_ID" SMALLINT NOT NULL , 
		  "SHAPE_TYPE" SMALLINT , 
		  "SHAPE_STYLE" SMALLINT , 
		  "LINE_WIDTH" DOUBLE , 
		  "LINE_STYLE" SMALLINT , 
		  "LINE_COLOR" VARCHAR(8) NOT NULL , 
		  "FILL_COLOR" VARCHAR(8) NOT NULL , 
		  "X" SMALLINT , 
		  "Y" SMALLINT , 
		  "X_EXTENT" SMALLINT , 
		  "Y_EXTENT" SMALLINT , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE "GALADM  "."GTS_SHAPE_TBX" IS 'GTS Shape';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_SHAPE_TBX"

ALTER TABLE "GALADM  "."GTS_SHAPE_TBX" 
	ADD CONSTRAINT "GTS_SHAPE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "SHAPE_ID");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_SHAPE_TBX"

ALTER TABLE "GALADM  "."GTS_SHAPE_TBX" 
	ADD CONSTRAINT "SHAPE_TO_AREA_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_SHAPE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_SHAPE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_SHAPE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_SHAPE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

------------------------------------------------
-- DDL Statements for Table "GALADM  "."GTS_ZONE_TBX"
------------------------------------------------

DROP TRIGGER GALADM.GTS_ZONE_TR1;
DROP TRIGGER GALADM.GTS_ZONE_TR2;
DROP TABLE GALADM.GTS_ZONE_TBX;

CREATE TABLE "GALADM  "."GTS_ZONE_TBX"  (
		  "TRACKING_AREA" VARCHAR(10) NOT NULL , 
		  "ZONE" VARCHAR(20) NOT NULL , 
		  "ZONE_DESCRIPTION" VARCHAR(100) , 
		  "LANES" VARCHAR(100) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		  IN GALTBSREF12
		  INDEX IN GALTBSIDX4 ;

COMMENT ON TABLE "GALADM  "."GTS_ZONE_TBX" IS 'GTS Zone';


-- DDL Statements for Primary Key on Table "GALADM  "."GTS_ZONE_TBX"

ALTER TABLE "GALADM  "."GTS_ZONE_TBX" 
	ADD CONSTRAINT "GTS_ZONE_PK" PRIMARY KEY
		("TRACKING_AREA",
		 "ZONE");

-- DDL Statements for Foreign Keys on Table "GALADM  "."GTS_ZONE_TBX"

ALTER TABLE "GALADM  "."GTS_ZONE_TBX" 
	ADD CONSTRAINT "AREA_TO_ZONE_FK1" FOREIGN KEY
		("TRACKING_AREA")
	REFERENCES "GALADM  "."GTS_AREA_TBX"
		("TRACKING_AREA")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT ENFORCED
	ENABLE QUERY OPTIMIZATION;

CREATE TRIGGER GALADM.GTS_ZONE_TR1 NO CASCADE BEFORE
INSERT ON GALADM.GTS_ZONE_TBX REFERENCING NEW AS A FOR EACH ROW SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_ZONE_TR2 NO CASCADE BEFORE
UPDATE ON GALADM.GTS_ZONE_TBX REFERENCING NEW AS A FOR EACH ROW SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER "GALADM".PUSH_TIMER_STATUS_TR1;
DROP TRIGGER "GALADM".PUSH_TIMER_STATUS_TR2;
DROP TABLE "GALADM".PUSH_TIMER_STATUS_TBX;

CREATE TABLE "GALADM"."PUSH_TIMER_STATUS_TBX" (
  "PROCESS_POINT_ID"	CHARACTER(16)	NOT NULL,
  "TERMINAL_ID"	VARCHAR(32)	NOT NULL,
  "PRODUCT_ID"	VARCHAR(32),
  "OPS_PLANNED"	INTEGER,
  "OPS_COMPLETED" INTEGER,
  "STATUS_IN_SECS"	BIGINT NOT NULL,
  "LAST_UPDATED"	TIMESTAMP,
  "CREATE_TIMESTAMP"	TIMESTAMP,
  "UPDATE_TIMESTAMP"	TIMESTAMP
) 
  IN "GALTBSREF11"  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."PUSH_TIMER_STATUS_TBX"
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PUSH_TIMER_STATUS_TBX" IS 'Maintains Push timer status from all VIOS clients';

CREATE TRIGGER "GALADM"."PUSH_TIMER_STATUS_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."PUSH_TIMER_STATUS_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PUSH_TIMER_STATUS_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."PUSH_TIMER_STATUS_TBX"
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET
UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE "GALADM"."PUSH_TIMER_STATUS_TBX"
  ADD CONSTRAINT "PUSH_TIMER_STATUS_PK" PRIMARY KEY
    ("PROCESS_POINT_ID", "TERMINAL_ID");



-