-- This CLP file was created using DB2LOOK Version "9.7" 
-- Timestamp: Thu Feb 19 21:11:51 2015
-- Database Manager Version: DB2/AIX64 Version 9.7.7       
-- Database Codepage: 1208
-- Database Collating Sequence is: SYSTEM_819



------------------------------------------------
-- DDL Statements for Table "GALADM  "."FIF_CODE_GROUPS_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."FIF_CODE_GROUPS_TBX"  (
		  "PLANT_CD" VARCHAR(4) NOT NULL , 
		  "MODEL_YEAR" VARCHAR(1) NOT NULL , 
		  "MODEL_CD" VARCHAR(3) NOT NULL , 
		  "DEV_SEQ_CD" VARCHAR(1) NOT NULL , 
		  "BASE_TYPE" VARCHAR(3) NOT NULL , 
		  "FIF_TYPE" VARCHAR(3) NOT NULL , 
		  "GROUP_CD" VARCHAR(3) NOT NULL , 
		  "GROUP_DESC" VARCHAR(30) NOT NULL , 
		  "EFCT_BEG_DT" DATE NOT NULL , 
		  "EFCT_END_DT" DATE NOT NULL , 
		  "REQUIRED" VARCHAR(1) NOT NULL , 
		  "FIF_LENGTH" SMALLINT NOT NULL , 
		  "FIF_OFFSET" SMALLINT NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE "GALADM  "."FIF_CODE_GROUPS_TBX" IS 'RGALC table corresponding to  GPCS GMM90D00';


-- DDL Statements for Primary Key on Table "GALADM  "."FIF_CODE_GROUPS_TBX"

ALTER TABLE "GALADM  "."FIF_CODE_GROUPS_TBX" 
	ADD CONSTRAINT "FIF_CODE_GROUPS_FK" PRIMARY KEY
		("PLANT_CD",
		 "MODEL_YEAR",
		 "MODEL_CD",
		 "DEV_SEQ_CD",
		 "BASE_TYPE",
		 "FIF_TYPE",
		 "GROUP_CD",
		 "EFCT_BEG_DT");



------------------------------------------------
-- DDL Statements for Table "GALADM  "."FIF_CODE_CHOICES_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."FIF_CODE_CHOICES_TBX"  (
		  "PLANT_CD" VARCHAR(4) NOT NULL , 
		  "MODEL_YEAR" VARCHAR(1) NOT NULL , 
		  "MODEL_CD" VARCHAR(3) NOT NULL , 
		  "DEV_SEQ_CD" VARCHAR(1) NOT NULL , 
		  "FIF_TYPE" VARCHAR(3) NOT NULL , 
		  "GROUP_CD" VARCHAR(3) NOT NULL , 
		  "FIF_CODE" VARCHAR(3) NOT NULL , 
		  "FIF_DESC" VARCHAR(30) NOT NULL , 
		  "EFCT_BEG_DT" DATE NOT NULL , 
		  "EFCT_END_DT" DATE NOT NULL , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSREF11" INDEX IN "GALTBSIDX4" ; 

COMMENT ON TABLE "GALADM  "."FIF_CODE_CHOICES_TBX" IS 'RGALC table corresponding to  GPCS GMM91D00';


-- DDL Statements for Primary Key on Table "GALADM  "."FIF_CODE_CHOICES_TBX"

ALTER TABLE "GALADM  "."FIF_CODE_CHOICES_TBX" 
	ADD CONSTRAINT "FIF_CODE_CHOICES_PK" PRIMARY KEY
		("PLANT_CD",
		 "MODEL_YEAR",
		 "MODEL_CD",
		 "FIF_TYPE",
		 "GROUP_CD",
		 "FIF_CODE",
		 "DEV_SEQ_CD",
		 "EFCT_BEG_DT");



------------------------------------------------
-- DDL Statements for Table "GALADM  "."SALES_ORDER_FIF_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."SALES_ORDER_FIF_TBX"  (
		  "LOC_PROD_MONTH" VARCHAR(6) NOT NULL , 
		  "ORDER_TYPE" VARCHAR(2) NOT NULL , 
		  "ORDER_SEQ_NO" SMALLINT NOT NULL , 
		  "UNIQUE_ID" VARCHAR(3) NOT NULL , 
		  "SALES_DIV" VARCHAR(1) , 
		  "PROD_DIV" VARCHAR(1) , 
		  "PROD_QTY" INTEGER NOT NULL , 
		  "MODEL_YEAR" VARCHAR(4) NOT NULL , 
		  "SALES_MODEL_CD" VARCHAR(11) NOT NULL , 
		  "SALES_VEH_DEST_CD" VARCHAR(4) NOT NULL , 
		  "SALES_OPTION_CD" VARCHAR(3) NOT NULL , 
		  "SALES_EXT_CLR_CD" VARCHAR(10) NOT NULL , 
		  "SALES_INT_CLR_CD" VARCHAR(2) NOT NULL , 
		  "FRM_PLANT_CD" VARCHAR(4) NOT NULL , 
		  "FRM_MODEL_YEAR_CD" VARCHAR(1) NOT NULL , 
		  "FRM_MODEL_CD" VARCHAR(3) NOT NULL , 
		  "FRM_DEV_SEQ_CD" VARCHAR(1) NOT NULL , 
		  "FRM_TYPE_CD" VARCHAR(3) NOT NULL , 
		  "FRM_OPTION_CD" VARCHAR(3) NOT NULL , 
		  "FRM_EXT_CLR_CD" VARCHAR(10) NOT NULL , 
		  "FRM_INT_CLR_CD" VARCHAR(2) NOT NULL , 
		  "BUILD_BY_DT" VARCHAR(8) NOT NULL , 
		  "SHIPPER_ID" VARCHAR(3) NOT NULL , 
		  "SALES_KD_LOT_NO" VARCHAR(9) , 
		  "EFCT_END_DT" DATE , 
		  "FIF_CODES" VARCHAR(128) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT4" INDEX IN "GALTBSIDX3" ; 

COMMENT ON TABLE "GALADM  "."SALES_ORDER_FIF_TBX" IS 'RGALC table corresponding to  GPCS GMM98D00';


-- DDL Statements for Primary Key on Table "GALADM  "."SALES_ORDER_FIF_TBX"

ALTER TABLE "GALADM  "."SALES_ORDER_FIF_TBX" 
	ADD CONSTRAINT "SALES_ORDER_FIF_PK" PRIMARY KEY
		("UNIQUE_ID",
		 "SALES_MODEL_CD",
		 "SALES_VEH_DEST_CD",
		 "SALES_OPTION_CD",
		 "SALES_EXT_CLR_CD",
		 "SALES_INT_CLR_CD",
		 "ORDER_TYPE",
		 "ORDER_SEQ_NO",
		 "FRM_PLANT_CD",
		 "FRM_MODEL_YEAR_CD",
		 "FRM_MODEL_CD",
		 "FRM_DEV_SEQ_CD",
		 "FRM_TYPE_CD",
		 "FRM_OPTION_CD",
		 "FRM_EXT_CLR_CD",
		 "FRM_INT_CLR_CD");



------------------------------------------------
-- DDL Statements for Table "GALADM  "."BOM_TBX"
------------------------------------------------
 

CREATE TABLE "GALADM  "."BOM_TBX"  (
		  "PART_NO" CHAR(18) NOT NULL , 
		  "PLANT_LOC_CODE" CHAR(1) NOT NULL , 
		  "PART_COLOR_CODE" CHAR(11) , 
		  "SUPPLIER_NO" CHAR(6) NOT NULL , 
		  "TARGET_MFG_DEST_NO" CHAR(6) , 
		  "PART_BLOCK_CODE" CHAR(1) , 
		  "PART_SECTION_CODE" CHAR(3) NOT NULL , 
		  "PART_ITEM_NO" CHAR(7) NOT NULL , 
		  "TGT_SHIP_TO_CODE" CHAR(6) NOT NULL , 
		  "MTC_MODEL" CHAR(4) NOT NULL , 
		  "MTC_COLOR" CHAR(11) NOT NULL , 
		  "MTC_OPTION" CHAR(3) NOT NULL , 
		  "MTC_TYPE" CHAR(3) NOT NULL , 
		  "INT_COLOR_CODE" CHAR(1) NOT NULL , 
		  "EFF_BEG_DATE" DATE NOT NULL , 
		  "EFF_END_DATE" DATE NOT NULL , 
		  "PART_PROD_CODE" CHAR(1) NOT NULL , 
		  "PROCLOC_GP_NO" CHAR(2) NOT NULL , 
		  "PROCLOC_GP_SEQ_NO" CHAR(2) NOT NULL , 
		  "TGT_PLANT_LOC_CODE" CHAR(1) NOT NULL , 
		  "TGT_MODEL_DEV_CODE" CHAR(4) NOT NULL , 
		  "PART_COLOR_ID_CODE" CHAR(1) , 
		  "SUPPLIER_CAT_CODE" CHAR(1) NOT NULL , 
		  "PART_QTY" DECIMAL(6,0) NOT NULL , 
		  "DATA_UPD_DESC_TEXT" CHAR(20) NOT NULL , 
		  "TIMESTAMP_DATE" TIMESTAMP NOT NULL , 
		  "DC_FAM_CLASS_CODE" CHAR(5) NOT NULL , 
		  "DC_PART_NO" CHAR(18) NOT NULL , 
		  "PDDA_FIF_TYPE" VARCHAR(3) , 
		  "CREATE_TIMESTAMP" TIMESTAMP , 
		  "UPDATE_TIMESTAMP" TIMESTAMP )   
		 IN "GALTBSDAT2" INDEX IN "GALTBSIDX2" ; 

COMMENT ON TABLE "GALADM  "."BOM_TBX" IS 'RGALC table corresponding to  TIX.TISAF2';






-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

CREATE INDEX "GALADM  "."BOM_I1" ON "GALADM  "."BOM_TBX" 
		("PART_NO" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

CREATE INDEX "GALADM  "."BOM_I2" ON "GALADM  "."BOM_TBX" 
		("PART_NO" ASC,
		 "MTC_MODEL" ASC,
		 "MTC_TYPE" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "GALADM  "."BOM_TBX"

CREATE UNIQUE INDEX "GALADM  "."BOM_PK" ON "GALADM  "."BOM_TBX" 
		("PART_NO" ASC,
		 "PLANT_LOC_CODE" ASC,
		 "PART_COLOR_CODE" ASC,
		 "SUPPLIER_NO" ASC,
		 "PART_BLOCK_CODE" ASC,
		 "PART_SECTION_CODE" ASC,
		 "PART_ITEM_NO" ASC,
		 "TGT_SHIP_TO_CODE" ASC,
		 "MTC_MODEL" ASC,
		 "MTC_COLOR" ASC,
		 "MTC_OPTION" ASC,
		 "MTC_TYPE" ASC,
		 "INT_COLOR_CODE" ASC,
		 "EFF_BEG_DATE" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;







-------------------------------
-- DDL Statements for Triggers
-------------------------------

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.BOM_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.BOM_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.BOM_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.BOM_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.FIF_CODE_CHOICES_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.FIF_CODE_CHOICES_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.FIF_CODE_CHOICES_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.FIF_CODE_CHOICES_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.FIF_CODE_GROUPS_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.FIF_CODE_GROUPS_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.FIF_CODE_GROUPS_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.FIF_CODE_GROUPS_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.SALES_ORDER_FIF_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.SALES_ORDER_FIF_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

SET CURRENT SCHEMA = "GALADM  ";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","GALADM";
CREATE TRIGGER GALADM.SALES_ORDER_FIF_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.SALES_ORDER_FIF_TBX
  REFERENCING
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;


COMMIT WORK;
