
--PART UPDATE PRIMARY KEY
ALTER TABLE "LCVINBOM"."PART" DROP CONSTRAINT "PART_PK";
ALTER TABLE "LCVINBOM"."PART" ADD CONSTRAINT "PART_PK" PRIMARY KEY ("PRODUCT_SPEC_CODE", "LET_SYSTEM_NAME", "DC_PART_NUMBER");
REORG TABLE "LCVINBOM"."PART";

--UPDATE THE DESIGN CHANGE RULES
UPDATE "LCVINBOM"."DESIGN_CHANGE_RULES" SET SCRAP_PARTS = 2 WHERE DC_CLASS = 'A';
UPDATE "LCVINBOM"."DESIGN_CHANGE_RULES" SET SCRAP_PARTS = 2, INTERCHANGABLE = 0 WHERE DC_CLASS = 'B';