ALTER TABLE GALADM.GAL212TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL212TBX
ALTER COLUMN PRODUCT_SPEC_CODE SET DATA TYPE CHARACTER(30)
ADD COLUMN PLAN_CODE CHARACTER(11)
ADD COLUMN KD_LOT_NUMBER CHARACTER(18)
ADD COLUMN SEQUENCE DOUBLE
ADD COLUMN REMAKE_FLAG CHARACTER(1)
ADD COLUMN STAMPING_FLAG CHARACTER(1)
ADD COLUMN CARRY_IN_OUT_FLAG CHARACTER(1)
ADD COLUMN CARRY_IN_OUT_UNITS INTEGER
;

ALTER TABLE GALADM.GAL212TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.GAL212TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL212TBX;