ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX ALTER COLUMN TEXT_ENTRY_MENU SET DATA TYPE VARCHAR(32);
ALTER TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_TEXT_ENTRY_MENU_TBX;

ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX ALTER COLUMN TEXT_ENTRY_MENU SET DATA TYPE VARCHAR(32);
ALTER TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_LOCAL_DEFECT_COMBINATION_TBX;

ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX DATA CAPTURE NONE;
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX ALTER COLUMN TEXT_ENTRY_MENU SET DATA TYPE VARCHAR(32);
ALTER TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX DATA CAPTURE CHANGES;
REORG TABLE GALADM.QI_ENTRY_SCREEN_DEFECT_COMBINATION_TBX;
