ALTER TABLE GALADM.REQUIRED_PARTS_TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.REQUIRED_PARTS_TBX
ADD COLUMN PRODUCT_TYPE CHARACTER(10)
ADD COLUMN PRODUCT_SPEC_CODE CHARACTER(30) NOT NULL DEFAULT ''
;

ALTER TABLE GALADM.REQUIRED_PARTS_TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.REQUIRED_PARTS_TBX ADD PRIMARY KEY (PROCESS_POINT_ID,MODEL_YEAR_CODE,MODEL_CODE,MODEL_TYPE_CODE,MODEL_OPTION_CODE,INT_COLOR_CODE,EXT_COLOR_CODE,PART_NAME,PRODUCT_SPEC_CODE);

ALTER TABLE GALADM.REQUIRED_PARTS_TBX
  DATA CAPTURE CHANGES;
  
REORG TABLE  GALADM.REQUIRED_PARTS_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.REQUIRED_PARTS_TBX;