--GAL245TBX
--Adding PRODUCT_SPEC_CODE column in GAL245TBX 
ALTER TABLE GALADM.GAL245TBX DROP PRIMARY KEY;
ALTER TABLE GALADM.GAL245TBX ADD PRODUCT_SPEC_CODE CHAR(30) NOT NULL WITH DEFAULT '';

DROP INDEX GALADM.GAL245_I1;
CREATE UNIQUE INDEX GALADM.GAL245_I1 ON GALADM.GAL245TBX (
     PART_ID ASC,
     PART_NAME ASC,
     MODEL_YEAR_CODE ASC,
     MODEL_CODE ASC,
     MODEL_TYPE_CODE ASC,
     MODEL_OPTION_CODE ASC,
     EXT_COLOR_CODE ASC,
     INT_COLOR_CODE ASC,
     PRODUCT_SPEC_CODE ASC
    ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.GAL245TBX ADD CONSTRAINT GAL245_PK PRIMARY KEY (
     PART_ID,
     PART_NAME,
     MODEL_YEAR_CODE,
     MODEL_CODE,
     MODEL_TYPE_CODE,
     MODEL_OPTION_CODE,
     EXT_COLOR_CODE,
     INT_COLOR_CODE,
     PRODUCT_SPEC_CODE
    );

--GAL246TBX
--Adding PRODUCT_SPEC_CODE column in GAL246TBX 
ALTER TABLE GALADM.GAL246TBX DROP PRIMARY KEY; 
ALTER TABLE GALADM.GAL246TBX ADD PRODUCT_SPEC_CODE CHAR(30) NOT NULL WITH DEFAULT ''; 

DROP INDEX GALADM.GAL246_I1;
CREATE UNIQUE INDEX GALADM.GAL246_I1 ON GALADM.GAL246TBX (
     PROCESS_POINT_ID ASC,
     MODEL_YEAR_CODE ASC,
     MODEL_CODE ASC,
     MODEL_TYPE_CODE ASC,
     MODEL_OPTION_CODE ASC,
     INT_COLOR_CODE ASC,
     EXT_COLOR_CODE ASC,
     PART_NAME ASC,
     PRODUCT_SPEC_CODE ASC
    ) ALLOW REVERSE SCANS;

ALTER TABLE GALADM.GAL246TBX ADD CONSTRAINT GAL246_PK PRIMARY KEY ( 
     PROCESS_POINT_ID,
     MODEL_YEAR_CODE,
     MODEL_CODE,
     MODEL_TYPE_CODE,
     MODEL_OPTION_CODE,
     INT_COLOR_CODE,
     EXT_COLOR_CODE,
     PART_NAME,
     PRODUCT_SPEC_CODE
    );