CREATE TABLE STAMPSTOR.ATTRIBUTES_TBX (
  ATTRIBUTE_ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       MINVALUE 0, MAXVALUE 0, NO CYCLE, NO ORDER),
  ATTRIBUTE_TYPE	BIGINT	NOT NULL,
  ATTRIBUTE_NAME	VARCHAR(255),
  ATTRIBUTE_VALUE	INTEGER,
  VERSION	INTEGER
);

ALTER TABLE "STAMPSTOR"."ATTRIBUTES_TBX"
  ADD PRIMARY KEY
    ("ATTRIBUTE_ID");

CREATE TABLE STAMPSTOR.ATTRIBUTE_TYPES_TBX (
  ATTRIBUTE_TYPE_ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       MINVALUE 0, MAXVALUE 0, NO CYCLE, NO ORDER),
  NAME	VARCHAR(50)	NOT NULL,
  VERSION	INTEGER
);

ALTER TABLE "STAMPSTOR"."ATTRIBUTE_TYPES_TBX"
  ADD PRIMARY KEY
    ("ATTRIBUTE_TYPE_ID");

ALTER TABLE "STAMPSTOR"."ATTRIBUTES_TBX"
  ADD CONSTRAINT "FKC5F8EA3D4BBA7177" FOREIGN KEY
    ("ATTRIBUTE_TYPE")
  REFERENCES "STAMPSTOR"."ATTRIBUTE_TYPES_TBX"
    ("ATTRIBUTE_TYPE_ID")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED
    ENABLE QUERY OPTIMIZATION;