// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect OrderFulfillmentPk_Roo_Json {
    
    public String OrderFulfillmentPk.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static OrderFulfillmentPk OrderFulfillmentPk.fromJsonToOrderFulfillmentPk(String json) {
        return new JSONDeserializer<OrderFulfillmentPk>().use(null, OrderFulfillmentPk.class).deserialize(json);
    }
    
    public static String OrderFulfillmentPk.toJsonArray(Collection<OrderFulfillmentPk> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<OrderFulfillmentPk> OrderFulfillmentPk.fromJsonArrayToOrderFulfillmentPks(String json) {
        return new JSONDeserializer<List<OrderFulfillmentPk>>().use(null, ArrayList.class).use("values", OrderFulfillmentPk.class).deserialize(json);
    }
    
}
