// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import javax.persistence.Embeddable;

privileged aspect OrderFulfillmentPk_Roo_Identifier {
    
    declare @type: OrderFulfillmentPk: @Embeddable;
    
    public OrderFulfillmentPk.new(WeldOrder weldOrder, Integer carrierNumber, Integer releaseCycle) {
        super();
        this.weldOrder = weldOrder;
        this.carrierNumber = carrierNumber;
        this.releaseCycle = releaseCycle;
    }

    private OrderFulfillmentPk.new() {
        super();
    }

    public WeldOrder OrderFulfillmentPk.getWeldOrder() {
        return this.weldOrder;
    }
    
    public Integer OrderFulfillmentPk.getCarrierNumber() {
        return this.carrierNumber;
    }

     public Integer OrderFulfillmentPk.getReleaseCycle() {
        return this.releaseCycle;
    }
    
    public boolean OrderFulfillmentPk.equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (!(obj instanceof OrderFulfillmentPk)) return false;
        OrderFulfillmentPk other = (OrderFulfillmentPk) obj;
        if (weldOrder == null) {
            if (other.weldOrder != null) return false;
        } else if (!weldOrder.equals(other.weldOrder)) return false;
        if (carrierNumber == null) {
            if (other.carrierNumber != null) return false;
        } else if (!carrierNumber.equals(other.carrierNumber)) return false;
        if (releaseCycle == null) {
            if (other.releaseCycle != null) return false;
        } else if (!releaseCycle.equals(other.releaseCycle)) return false;
        return true;
    }
    
    public int OrderFulfillmentPk.hashCode() {
        final int prime = 31;
        int result = 17;
        result = prime * result + (weldOrder == null ? 0 : weldOrder.hashCode());
        result = prime * result + (carrierNumber == null ? 0 : carrierNumber.hashCode());
         result = prime * result + (releaseCycle == null ? 0 : releaseCycle.hashCode());
        return result;
    }
    
}
