// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import java.lang.String;

privileged aspect OrderFulfillment_Roo_ToString {
    
    public String OrderFulfillment.toString() {
        StringBuilder sb = new StringBuilder();
       // sb.append("DieNumber: ").append(getDie()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Quantity: ").append(getQuantity()).append(", ");
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
