# Default values for helm-honda-ca-add.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "" # Recommend managing in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml
fullnameOverride: ""

nodeSelector: {}

global:
  productTeam: linectrl
  useCase:
    name: salesinterface
    instance: # Recommend managing in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml
    env: # Recommend managing in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml
  clusterInstance: # Recommend managing in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml

lc-sales-interface-service:
  nameOverride: lc-sales-interface-service
  artifactory: artifactory.amerhonda.com
  artifactoryRepo: # Managed in OpenShift Pipeline argocd-devops-sync task
  imageName: lc-sales-interface-service
  imageVersion: # Managed in pipeline.sh
  replicas: 1
  deployment:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 512Mi
  container:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 512Mi
  ports:
    - name: 8080-tcp
      containerPort: 8080
      protocol: TCP
  service:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    type: ClusterIP
  route:
    url: # Override in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml
    targetPort: 8080-tcp
  env: # Override in values-[[ usecaseEnv ]]-[[ clusterInstance ]].yaml
  envFrom:
    - secretRef: 
        name: ahm-sales-interface-service
