export const processPointsElp: any[] = [
    {
        "TEAM": "WT02",
        "PDDA BODY LOCATION": "011R",
        "PROCESS POINT DESCRIPTION": "ENGINE HARNESS",
        "PROCESS POINT ID": "TAF3WT2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT02",
        "PDDA BODY LOCATION": "014L",
        "PROCESS POINT DESCRIPTION": "UNDERBODY GROUNDS",
        "PROCESS POINT ID": "TAF3WT3P00201",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP-ST32-10-106"
    }, {
        "TEAM": "WT02",
        "PDDA BODY LOCATION": "014R",
        "PROCESS POINT DESCRIPTION": "FRONT IMPACT SENSORS",
        "PROCESS POINT ID": "TAF3WT3P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12PB-14"
    }, {
        "TEAM": "WT02",
        "PDDA BODY LOCATION": "017R",
        "PROCESS POINT DESCRIPTION": "FUEL TANK",
        "PROCESS POINT ID": "TAF3WT3P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1070-A"
    }, {
        "TEAM": "WT03",
        "PDDA BODY LOCATION": "019L",
        "PROCESS POINT DESCRIPTION": "MASTER POWER",
        "PROCESS POINT ID": "TAF3WT3P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT04",
        "PDDA BODY LOCATION": "023R",
        "PROCESS POINT DESCRIPTION": "IPU TIGHTEN",
        "PROCESS POINT ID": "TAF3WT3P00501",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "B23LA13-12"
    }, {
        "TEAM": "WT04",
        "PDDA BODY LOCATION": "026R",
        "PROCESS POINT DESCRIPTION": "DC TERMINAL TIGHTEN",
        "PROCESS POINT ID": "TAF3WT4P00201",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "B23LA13-12"
    }, {
        "TEAM": "WT04",
        "PDDA BODY LOCATION": "028L",
        "PROCESS POINT DESCRIPTION": "ECU LID COVER",
        "PROCESS POINT ID": "TAF3WT4P00101",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT05",
        "PDDA BODY LOCATION": "030L",
        "PROCESS POINT DESCRIPTION": "L/S SEAT STRIKER",
        "PROCESS POINT ID": "TAF3WT5P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "WT05",
        "PDDA BODY LOCATION": "033R",
        "PROCESS POINT DESCRIPTION": "DOOR LABEL PRINT",
        "PROCESS POINT ID": "TAF3WT5PDRLBL",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT05",
        "PDDA BODY LOCATION": "035R",
        "PROCESS POINT DESCRIPTION": "ANTENNA SCAN",
        "PROCESS POINT ID": "TAF3WT5P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "INGERSOLL RAND",
        "TOOL": "QXX2PT08Q4"
    }, {
        "TEAM": "WT06",
        "PDDA BODY LOCATION": "046R",
        "PROCESS POINT DESCRIPTION": "HARNESS SCAN",
        "PROCESS POINT ID": "TAF3WT6P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT06",
        "PDDA BODY LOCATION": "048L",
        "PROCESS POINT DESCRIPTION": "LS SIDE SENSOR",
        "PROCESS POINT ID": "TAF3WT6P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT06",
        "PDDA BODY LOCATION": "048R",
        "PROCESS POINT DESCRIPTION": "RS SIDE SENSOR",
        "PROCESS POINT ID": "TAF3WT6P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT06",
        "PDDA BODY LOCATION": "050R",
        "PROCESS POINT DESCRIPTION": "RS FRONT SCAB TIGHTEN",
        "PROCESS POINT ID": "TAF3WT6P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT07",
        "PDDA BODY LOCATION": "051L",
        "PROCESS POINT DESCRIPTION": "SRS CONTROL UNIT",
        "PROCESS POINT ID": "TAF3WT7P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP-ST32-10-106"
    }, {
        "TEAM": "WT07",
        "PDDA BODY LOCATION": "052L",
        "PROCESS POINT DESCRIPTION": "LS FRONT SCAB TIGHTEN",
        "PROCESS POINT ID": "TAF3WT7P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT07",
        "PDDA BODY LOCATION": "053R",
        "PROCESS POINT DESCRIPTION": "RS GROUND",
        "PROCESS POINT ID": "TAF3WT7P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP-ST32-10-106"
    }, {
        "TEAM": "WT07",
        "PDDA BODY LOCATION": "054R",
        "PROCESS POINT DESCRIPTION": "RS SCAB",
        "PROCESS POINT ID": "TAF3WT7P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT08",
        "PDDA BODY LOCATION": "055L",
        "PROCESS POINT DESCRIPTION": "LS SCAB",
        "PROCESS POINT ID": "TAF3WT8P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "WT08",
        "PDDA BODY LOCATION": "056R",
        "PROCESS POINT DESCRIPTION": "RS SEAT STRIKER",
        "PROCESS POINT ID": "TAF3WT8P00501",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "WT08",
        "PDDA BODY LOCATION": "057L",
        "PROCESS POINT DESCRIPTION": "SEATBELT 1",
        "PROCESS POINT ID": "TAF3WT8P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "WT08",
        "PDDA BODY LOCATION": "058L",
        "PROCESS POINT DESCRIPTION": "SEATBELT 2",
        "PROCESS POINT ID": "TAF3WT8P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "WT08",
        "PDDA BODY LOCATION": "059L",
        "PROCESS POINT DESCRIPTION": "SEATBELT 3",
        "PROCESS POINT ID": "TAF3WT8P00401",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "WT09",
        "PDDA BODY LOCATION": "063L",
        "PROCESS POINT DESCRIPTION": "LS GROUND",
        "PROCESS POINT ID": "TAF3WT9P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP-ST32-10-106"
    }, {
        "TEAM": "WT09",
        "PDDA BODY LOCATION": "063R",
        "PROCESS POINT DESCRIPTION": "SEATBELT 4",
        "PROCESS POINT ID": "TAF3WT9P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STR61-50-10"
    }, {
        "TEAM": "WT09",
        "PDDA BODY LOCATION": "065L",
        "PROCESS POINT DESCRIPTION": "BRAKE PEDAL 1",
        "PROCESS POINT ID": "TAF3WT9P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "WT09",
        "PDDA BODY LOCATION": "065R",
        "PROCESS POINT DESCRIPTION": "BONNET LOCK",
        "PROCESS POINT ID": "TAF3WT9P00301",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST31-10-10 & ETV STR61-50-10"
    }, {
        "TEAM": "IN01",
        "PDDA BODY LOCATION": "076L",
        "PROCESS POINT DESCRIPTION": "SEATBELT 5",
        "PROCESS POINT ID": "TAF3IN1P00201",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STR-61-50-10"
    }, {
        "TEAM": "IN01",
        "PDDA BODY LOCATION": "078R",
        "PROCESS POINT DESCRIPTION": "R/S RR SEAT STRIKER",
        "PROCESS POINT ID": "TAF3IN1P00101",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "IN01",
        "PDDA BODY LOCATION": "081L",
        "PROCESS POINT DESCRIPTION": "SEATBELT 6",
        "PROCESS POINT ID": "TAF3IN1P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "IN01",
        "PDDA BODY LOCATION": "082L",
        "PROCESS POINT DESCRIPTION": "ACCELERATOR PEDAL",
        "PROCESS POINT ID": "TAF3IN1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST31-10-10"
    }, {
        "TEAM": "IN02",
        "PDDA BODY LOCATION": "082R",
        "PROCESS POINT DESCRIPTION": "SEATBELT 7",
        "PROCESS POINT ID": "TAF3IN2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "IN02",
        "PDDA BODY LOCATION": "083R",
        "PROCESS POINT DESCRIPTION": "HVAC SUB",
        "PROCESS POINT ID": "TAF3IN2P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IN03",
        "PDDA BODY LOCATION": "089L",
        "PROCESS POINT DESCRIPTION": "BRAKE PEDAL 2",
        "PROCESS POINT ID": "TAF3IN3P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "IN03",
        "PDDA BODY LOCATION": "095L",
        "PROCESS POINT DESCRIPTION": "LEFT IP INSTALL",
        "PROCESS POINT ID": "TAF3IN3P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STB63-30-10B"
    }, {
        "TEAM": "IN04",
        "PDDA BODY LOCATION": "115R",
        "PROCESS POINT DESCRIPTION": "RS INSTRUMENT PANEL",
        "PROCESS POINT ID": "TAF3IN4P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STB63-30-10B"
    }, {
        "TEAM": "IN04",
        "PDDA BODY LOCATION": "118L",
        "PROCESS POINT DESCRIPTION": "SEATBELT BUCKLE",
        "PROCESS POINT ID": "TAF3IN4P00201",
        "CRV": "X",
        "RDX": "",
        "MDX": "",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "IN05",
        "PDDA BODY LOCATION": "121L",
        "PROCESS POINT DESCRIPTION": "LS FRONT SENSOR",
        "PROCESS POINT ID": "TAF3IN5P00101",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP-ST32-10-106"
    }, {
        "TEAM": "IN04",
        "PDDA BODY LOCATION": "122R",
        "PROCESS POINT DESCRIPTION": "RS FRONT SENSOR",
        "PROCESS POINT ID": "TAF3IN4P00301",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "UB01",
        "PDDA BODY LOCATION": "130R",
        "PROCESS POINT DESCRIPTION": "PCU INSTALL",
        "PROCESS POINT ID": "TAF3UB1P00101",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1030-P"
    }, {
        "TEAM": "UB01",
        "PDDA BODY LOCATION": "141L",
        "PROCESS POINT DESCRIPTION": "SMURF",
        "PROCESS POINT ID": "TAF3UB1P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "FEC",
        "TOOL": ""
    }, {
        "TEAM": "UB02",
        "PDDA BODY LOCATION": "162R",
        "PROCESS POINT DESCRIPTION": "GROUND TIGHTEN",
        "PROCESS POINT ID": "TAF3UB2P00301",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12PB-14"
    }, {
        "TEAM": "UB02",
        "PDDA BODY LOCATION": "165L",
        "PROCESS POINT DESCRIPTION": "UNDERBODY SUS",
        "PROCESS POINT ID": "TAF3UB2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB55LB2-170"
    }, {
        "TEAM": "UB02",
        "PDDA BODY LOCATION": "169R",
        "PROCESS POINT DESCRIPTION": "MOT-PCU",
        "PROCESS POINT ID": "TAF3UB2P00201",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "B23LA13-12"
    }, {
        "TEAM": "UB03",
        "PDDA BODY LOCATION": "173R",
        "PROCESS POINT DESCRIPTION": "PROP SHAFT TIGHTEN",
        "PROCESS POINT ID": "TAF3UB3P00101",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-5-10"
    }, {
        "TEAM": "EX01",
        "PDDA BODY LOCATION": "191L",
        "PROCESS POINT DESCRIPTION": "LEFT FRONT DAMPER",
        "PROCESS POINT ID": "TAF3EX1P00101",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "EX01",
        "PDDA BODY LOCATION": "191R",
        "PROCESS POINT DESCRIPTION": "RIGHT FRONT DAMPER",
        "PROCESS POINT ID": "TAF3EX1P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "EX01",
        "PDDA BODY LOCATION": "199L",
        "PROCESS POINT DESCRIPTION": "VIN PLATE",
        "PROCESS POINT ID": "TAF3EX1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "EX01",
        "PDDA BODY LOCATION": "199R",
        "PROCESS POINT DESCRIPTION": "LABEL GUARANTEE SYSTEM",
        "PROCESS POINT ID": "TAF3EX1P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "IMAGE",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "UB04",
        "PDDA BODY LOCATION": "204R",
        "PROCESS POINT DESCRIPTION": "RIGHT UNDERBODY BRACE",
        "PROCESS POINT ID": "TAF3UB4P00201",
        "CRV": "X",
        "RDX": "",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP TBP81-55-10"
    }, {
        "TEAM": "UB04",
        "PDDA BODY LOCATION": "205L",
        "PROCESS POINT DESCRIPTION": "LEFT UNDERBODY BRACE",
        "PROCESS POINT ID": "TAF3UB4P00301",
        "CRV": "X",
        "RDX": "",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP TBP81-55-10"
    }, {
        "TEAM": "EX02",
        "PDDA BODY LOCATION": "207L",
        "PROCESS POINT DESCRIPTION": "YOKE TIGHTEN",
        "PROCESS POINT ID": "TAF3EX2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10"
    }, {
        "TEAM": "EX02",
        "PDDA BODY LOCATION": "212L",
        "PROCESS POINT DESCRIPTION": "FRONT PDU TIGHTEN",
        "PROCESS POINT ID": "TAF3EX2P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "INGERSOLL RAND",
        "TOOL": "QXX2PT12PQ4"
    }, {
        "TEAM": "EX02",
        "PDDA BODY LOCATION": "213L",
        "PROCESS POINT DESCRIPTION": "ECU SCAN",
        "PROCESS POINT ID": "TAF3EX2P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX03",
        "PDDA BODY LOCATION": "216R",
        "PROCESS POINT DESCRIPTION": "BATTERY GROUND",
        "PROCESS POINT ID": "TAF3EX3P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STB33-12-I06B"
    }, {
        "TEAM": "EX03",
        "PDDA BODY LOCATION": "222L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR SEAT BAR",
        "PROCESS POINT ID": "TAF3EX3P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "INGERSOLL RAND",
        "TOOL": "QXX2PT12PQ4"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "223L",
        "PROCESS POINT DESCRIPTION": "3RD ROW BACK TIGHTEN",
        "PROCESS POINT ID": "TAF3EX4P00301",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "224L",
        "PROCESS POINT DESCRIPTION": "LS 3RD ROW SEAT TIGHTEN",
        "PROCESS POINT ID": "TAF3EX4P00201",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "224R",
        "PROCESS POINT DESCRIPTION": "RS 3RD ROW SEAT TIGHTEN",
        "PROCESS POINT ID": "TAF3EX4P00101",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STB63-50-10B"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "226L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR SEAT 1",
        "PROCESS POINT ID": "TAF3EX4P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "226R",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR SEAT 1",
        "PROCESS POINT ID": "TAF3EX4P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "227L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR SEAT 2",
        "PROCESS POINT ID": "TAF3EX4P00601",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "228R",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR SEAT 2",
        "PROCESS POINT ID": "TAF3EX4P00701",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "231L",
        "PROCESS POINT DESCRIPTION": "FEM",
        "PROCESS POINT ID": "TAF3EX4P01101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1070-A"
    }, {
        "TEAM": "EX04",
        "PDDA BODY LOCATION": "231R",
        "PROCESS POINT DESCRIPTION": "FEM 2",
        "PROCESS POINT ID": "TAF3EX4P00901",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ESTIC",
        "TOOL": "EH2-H1070-A"
    }, {
        "TEAM": "EX05",
        "PDDA BODY LOCATION": "236R",
        "PROCESS POINT DESCRIPTION": "ENGINE MOUNT STOPPER",
        "PROCESS POINT ID": "TAF3EX5P00201",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-70-13"
    }, {
        "TEAM": "EX05",
        "PDDA BODY LOCATION": "244L",
        "PROCESS POINT DESCRIPTION": "RELAY BOX",
        "PROCESS POINT ID": "TAF3EX5P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "UB05",
        "PDDA BODY LOCATION": "267L",
        "PROCESS POINT DESCRIPTION": "SILENCER TIGHTEN",
        "PROCESS POINT ID": "TAF3UB5P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-70-13"
    }, {
        "TEAM": "UB05",
        "PDDA BODY LOCATION": "268L",
        "PROCESS POINT DESCRIPTION": "FRONT GLASS LOAD",
        "PROCESS POINT ID": "TAF3UB5P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "PART",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "UB05",
        "PDDA BODY LOCATION": "268L",
        "PROCESS POINT DESCRIPTION": "FRONT GLASS LOAD HEADLESS",
        "PROCESS POINT ID": "TAF3UB5P00102",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "UB05",
        "PDDA BODY LOCATION": "268R",
        "PROCESS POINT DESCRIPTION": "REAR GLASS LOAD",
        "PROCESS POINT ID": "TAF3UB5P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "PART",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "UB05",
        "PDDA BODY LOCATION": "268R",
        "PROCESS POINT DESCRIPTION": "REAR GLASS LOAD HEADLESS",
        "PROCESS POINT ID": "TAF3UB5P00202",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX06",
        "PDDA BODY LOCATION": "278L",
        "PROCESS POINT DESCRIPTION": "E-AWD SERVICE PLUG CHECK",
        "PROCESS POINT ID": "TAF3EX2P00301",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX06",
        "PDDA BODY LOCATION": "281L",
        "PROCESS POINT DESCRIPTION": "LEFT FRONT SEAT",
        "PROCESS POINT ID": "TAF3EX6P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STR61-50-10"
    }, {
        "TEAM": "EX06",
        "PDDA BODY LOCATION": "281R",
        "PROCESS POINT DESCRIPTION": "RIGHT FRONT SEAT",
        "PROCESS POINT ID": "TAF3EX6P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV STR61-50-10"
    }, {
        "TEAM": "EX06",
        "PDDA BODY LOCATION": "284L",
        "PROCESS POINT DESCRIPTION": "BRAKE FILL",
        "PROCESS POINT ID": "TAF3EX6P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "VACUUM / VOLUME",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX07",
        "PDDA BODY LOCATION": "295L",
        "PROCESS POINT DESCRIPTION": "STEERING WHEEL",
        "PROCESS POINT ID": "TAF3EX7P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX08",
        "PDDA BODY LOCATION": "298L",
        "PROCESS POINT DESCRIPTION": "SRS DRIVER MODULE",
        "PROCESS POINT ID": "TAF3EX8P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-50-10"
    }, {
        "TEAM": "EX08",
        "PDDA BODY LOCATION": "299L",
        "PROCESS POINT DESCRIPTION": "ONE TOUCH",
        "PROCESS POINT ID": "TAF3EX8P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "SALTUS MWR-50 TA"
    }, {
        "TEAM": "EX08",
        "PDDA BODY LOCATION": "302L",
        "PROCESS POINT DESCRIPTION": "LS TIRE INSTALL",
        "PROCESS POINT ID": "TAF3EX8P00202",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": ""
    }, {
        "TEAM": "EX08",
        "PDDA BODY LOCATION": "302R",
        "PROCESS POINT DESCRIPTION": "RS TIRE INSTALL",
        "PROCESS POINT ID": "TAF3EX8P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": ""
    }, {
        "TEAM": "EX07",
        "PDDA BODY LOCATION": "319L",
        "PROCESS POINT DESCRIPTION": "IMMOBI DATA COLLECTION",
        "PROCESS POINT ID": "TAF3EX7P00802",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "LET",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX07",
        "PDDA BODY LOCATION": "319R",
        "PROCESS POINT DESCRIPTION": "RADIATOR FILL HEADLESS",
        "PROCESS POINT ID": "TAF3EX7P00702",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "VACUUM / VOLUME / PRESSURE",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX07",
        "PDDA BODY LOCATION": "319R",
        "PROCESS POINT DESCRIPTION": "RADIATOR FILL",
        "PROCESS POINT ID": "TAF3EX7P00701",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "BROADCAST",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EX09",
        "PDDA BODY LOCATION": "322R",
        "PROCESS POINT DESCRIPTION": "AC FILL",
        "PROCESS POINT ID": "TAF3EX9P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "VACUUM / VOLUME",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL02",
        "PDDA BODY LOCATION": "D01L",
        "PROCESS POINT DESCRIPTION": "LEFT FRONT DOOR HARNESS",
        "PROCESS POINT ID": "TAF3DL2P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL01",
        "PDDA BODY LOCATION": "D01R",
        "PROCESS POINT DESCRIPTION": "RIGHT FRONT DOOR HARNESS",
        "PROCESS POINT ID": "TAF3DL1P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL02",
        "PDDA BODY LOCATION": "D02L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR DOOR HARNESS",
        "PROCESS POINT ID": "TAF3DL2P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL01",
        "PDDA BODY LOCATION": "D02R",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR DOOR HARNESS",
        "PROCESS POINT ID": "TAF3DL1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL02",
        "PDDA BODY LOCATION": "D08L",
        "PROCESS POINT DESCRIPTION": "LEFT OUTER HANDLE",
        "PROCESS POINT ID": "TAF3DL2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "INGERSOLL RAND",
        "TOOL": "QXX2PT12PQ4"
    }, {
        "TEAM": "DL01",
        "PDDA BODY LOCATION": "D08R",
        "PROCESS POINT DESCRIPTION": "RIGHT OUTER HANDLE",
        "PROCESS POINT ID": "TAF3DL1P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "INGERSOLL RAND",
        "TOOL": "QXX1PT12PQ4"
    }, {
        "TEAM": "DL04",
        "PDDA BODY LOCATION": "D37L",
        "PROCESS POINT DESCRIPTION": "LEFT FRONT DOOR LINER SCAN",
        "PROCESS POINT ID": "TAF3DL4P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL03",
        "PDDA BODY LOCATION": "D37R",
        "PROCESS POINT DESCRIPTION": "RIGHT FRONT DOOR LINER SCAN",
        "PROCESS POINT ID": "TAF3DL3P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL04",
        "PDDA BODY LOCATION": "D40L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR DOOR LINER SCAN",
        "PROCESS POINT ID": "TAF3DL4P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "DL03",
        "PDDA BODY LOCATION": "D40R",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR DOOR LINER SCAN",
        "PROCESS POINT ID": "TAF3DL3P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E04L",
        "PROCESS POINT DESCRIPTION": "TCU SCAN",
        "PROCESS POINT ID": "TAF3EL1P00101",
        "CRV": "X",
        "RDX": "",
        "MDX": "",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E08L",
        "PROCESS POINT DESCRIPTION": "MISSION MOUNT",
        "PROCESS POINT ID": "TAF3EL1P00201",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-70-13"
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E11R",
        "PROCESS POINT DESCRIPTION": "HALF SHAFT",
        "PROCESS POINT ID": "TAF3EL1P00401",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-70-13"
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E13R",
        "PROCESS POINT DESCRIPTION": "TRANSFER CASE",
        "PROCESS POINT ID": "TAF3EL1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-70-13"
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E14R",
        "PROCESS POINT DESCRIPTION": "ENGINE MOUNT BRACKET",
        "PROCESS POINT ID": "TAF3EL1P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E23R",
        "PROCESS POINT DESCRIPTION": "RIGHT DRIVESHAFT PRESS",
        "PROCESS POINT ID": "TAF3EL1P00601",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / JUDGEMENT",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EL01",
        "PDDA BODY LOCATION": "E23R",
        "PROCESS POINT DESCRIPTION": "RIGHT DRIVESHAFT PRESS HL",
        "PROCESS POINT ID": "TAF3EL1P00602",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "PRESS / TORQUE",
        "SUPPLIER": "FEC",
        "TOOL": ""
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E24L",
        "PROCESS POINT DESCRIPTION": "LEFT DRIVESHAFT PRESS",
        "PROCESS POINT ID": "TAF3EL2P00601",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / JUDGEMENT",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E24L",
        "PROCESS POINT DESCRIPTION": "LEFT DRIVESHAFT PRESS HL",
        "PROCESS POINT ID": "TAF3EL2P00602",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "PRESS / TORQUE",
        "SUPPLIER": "FEC",
        "TOOL": ""
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E33L",
        "PROCESS POINT DESCRIPTION": "LEFT SUSPENSION TORQUE",
        "PROCESS POINT ID": "TAF3EL2P00801",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13-F"
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E34R",
        "PROCESS POINT DESCRIPTION": "RIGHT SUSPENSION TORQUE",
        "PROCESS POINT ID": "TAF3EL2P00701",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13-F"
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E38L",
        "PROCESS POINT DESCRIPTION": "TRANSMISSION FILL",
        "PROCESS POINT ID": "TAF3EL2P00501",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "BROADCAST",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "EL02",
        "PDDA BODY LOCATION": "E38L",
        "PROCESS POINT DESCRIPTION": "TRANSMISSION FILL HEADLESS",
        "PROCESS POINT ID": "TAF3EL2P00502",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "VOLUME",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F04R",
        "PROCESS POINT DESCRIPTION": "LEFT FRONT LOWER ARM",
        "PROCESS POINT ID": "TAF3FS1P00601",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV-ST101-180-13"
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F05R",
        "PROCESS POINT DESCRIPTION": "RIGHT FRONT LOWER ARM",
        "PROCESS POINT ID": "TAF3FS1P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV-ST101-180-13"
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F08R",
        "PROCESS POINT DESCRIPTION": "FRONT Dual STABI SPRING TIGHTEN",
        "PROCESS POINT ID": "TAF3FS1P00701",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F17R",
        "PROCESS POINT DESCRIPTION": "GEARBOX TIGHTEN",
        "PROCESS POINT ID": "TAF3FS1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV-ST101-180-13"
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F21R",
        "PROCESS POINT DESCRIPTION": "FRONT ENGINE MOUNT",
        "PROCESS POINT ID": "TAF3FS1P00401",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-70-13"
    }, {
        "TEAM": "FS01",
        "PDDA BODY LOCATION": "F22R",
        "PROCESS POINT DESCRIPTION": "FRONT STABI SPRING TIGHTEN",
        "PROCESS POINT ID": "TAF3FS1P00101",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I01L",
        "PROCESS POINT DESCRIPTION": "INPANEL HARNESS SCAN",
        "PROCESS POINT ID": "TAF3IL1P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I04L",
        "PROCESS POINT DESCRIPTION": "ANC TIGHTEN",
        "PROCESS POINT ID": "TAF3IL1P00601",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I05L",
        "PROCESS POINT DESCRIPTION": "INPANEL GROUND BOLTS",
        "PROCESS POINT ID": "TAF3IL1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I06L",
        "PROCESS POINT DESCRIPTION": "FUSE BOX SCAN",
        "PROCESS POINT ID": "TAF3IL1P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I07L",
        "PROCESS POINT DESCRIPTION": "KEY FOB",
        "PROCESS POINT ID": "TAF3IL1P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I10L",
        "PROCESS POINT DESCRIPTION": "IP SHELL",
        "PROCESS POINT ID": "TAF3IL1P00101",
        "CRV": "X",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I11L",
        "PROCESS POINT DESCRIPTION": "IP TIGHTEN",
        "PROCESS POINT ID": "TAF3IL1P00701",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I13L",
        "PROCESS POINT DESCRIPTION": "CENTER SPEAKER LID INSTALL",
        "PROCESS POINT ID": "TAF3IL2P00901",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR-61-30-10-COT"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I14L",
        "PROCESS POINT DESCRIPTION": "EPB SWITCHES",
        "PROCESS POINT ID": "TAF3IL2P01001",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "IMAGE",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I17L",
        "PROCESS POINT DESCRIPTION": "SRS ASSIST MOD",
        "PROCESS POINT ID": "TAF3IL2P00201",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I19L",
        "PROCESS POINT DESCRIPTION": "PASSENGER KNEE AIRBAG",
        "PROCESS POINT ID": "TAF3IL2P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-30-10"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I20L",
        "PROCESS POINT DESCRIPTION": "METER DISPLAY SCAN",
        "PROCESS POINT ID": "TAF3IL2P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I24R",
        "PROCESS POINT DESCRIPTION": "RADIO SCAN",
        "PROCESS POINT ID": "TAF3IL2P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I28R",
        "PROCESS POINT DESCRIPTION": "GLOVE BOX INSTALL",
        "PROCESS POINT ID": "TAF3IL2P00601",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I33R",
        "PROCESS POINT DESCRIPTION": "STEERING COLUMN TIGHTEN",
        "PROCESS POINT ID": "TAF3IL2P00501",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST61-30-10"
    }, {
        "TEAM": "IL02",
        "PDDA BODY LOCATION": "I35R",
        "PROCESS POINT DESCRIPTION": "DVD INSTALL",
        "PROCESS POINT ID": "TAF3IL2P00801",
        "CRV": "",
        "RDX": "X",
        "MDX": "X",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETP STR61-30-10-COT"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I40R",
        "PROCESS POINT DESCRIPTION": "KNEE AIRBAG",
        "PROCESS POINT ID": "TAF3IL1P00801",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12LA13-13"
    }, {
        "TEAM": "IL01",
        "PDDA BODY LOCATION": "I42R",
        "PROCESS POINT DESCRIPTION": "BCM SCAN",
        "PROCESS POINT ID": "TAF3IL1P00901",
        "CRV": "X",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "FEM",
        "PDDA BODY LOCATION": "M04L",
        "PROCESS POINT DESCRIPTION": "BONNET LOCK TIGHTEN",
        "PROCESS POINT ID": "TAF3FE1P00101",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12PB-14"
    }, {
        "TEAM": "FEM",
        "PDDA BODY LOCATION": "M09L",
        "PROCESS POINT DESCRIPTION": "HARNESS SCAN",
        "PROCESS POINT ID": "TAF3FE1P00401",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "FEM",
        "PDDA BODY LOCATION": "M16L",
        "PROCESS POINT DESCRIPTION": "RADAR UNIT",
        "PROCESS POINT ID": "TAF3FE1P00201",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "FEM",
        "PDDA BODY LOCATION": "M24L",
        "PROCESS POINT DESCRIPTION": "SRS SENSOR TIGHTEN",
        "PROCESS POINT ID": "TAF3FE1P00301",
        "CRV": "",
        "RDX": "X",
        "MDX": "",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "STANLEY",
        "TOOL": "EB12PB-14"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R08L",
        "PROCESS POINT DESCRIPTION": "MDX REAR SUBFRAME",
        "PROCESS POINT ID": "TAF3RS1P00501",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN",
        "SUPPLIER": "",
        "TOOL": ""
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R09R",
        "PROCESS POINT DESCRIPTION": "DIFF TIGHTEN 2",
        "PROCESS POINT ID": "TAF3RS1P00601",
        "CRV": "X",
        "RDX": "",
        "MDX": "",
        "TASK": "TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-100-13"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R10L",
        "PROCESS POINT DESCRIPTION": "DIFF TIGHTEN 3",
        "PROCESS POINT ID": "TAF3RS1P00701",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R19L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR SUS 1",
        "PROCESS POINT ID": "TAF3RS1P00101",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R20L",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR SUS 1",
        "PROCESS POINT ID": "TAF3RS1P00201",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R21L",
        "PROCESS POINT DESCRIPTION": "LEFT REAR SUS 2",
        "PROCESS POINT ID": "TAF3RS1P00301",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "RS01",
        "PDDA BODY LOCATION": "R22R",
        "PROCESS POINT DESCRIPTION": "RIGHT REAR SUS 2",
        "PROCESS POINT ID": "TAF3RS1P00401",
        "CRV": "X",
        "RDX": "X",
        "MDX": "X",
        "TASK": "SCAN / TORQUE",
        "SUPPLIER": "ATLAS COPCO",
        "TOOL": "ETV ST81-150-13"
    }, {
        "TEAM": "TDU",
        "PDDA BODY LOCATION": "",
        "PROCESS POINT DESCRIPTION": "TDU ON",
        "PROCESS POINT ID": "TTD3ON1P00101",
        "CRV": "",
        "RDX": "",
        "MDX": "X",
        "TASK": "SCAN / LET",
        "SUPPLIER": "",
        "TOOL": ""
    }
]