// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.storage.web;

import com.honda.mfg.stamp.conveyor.domain.OrderFulfillment;
import com.honda.mfg.stamp.conveyor.domain.OrderFulfillmentPk;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.ConversionService;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.io.UnsupportedEncodingException;
import java.util.Collection;

privileged aspect OrderFulfillmentController_Roo_Controller {
    
    private ConversionService OrderFulfillmentController.conversionService;
    
    @Autowired
    public OrderFulfillmentController.new(ConversionService conversionService) {
        this.conversionService = conversionService;
    }

    @RequestMapping(method = RequestMethod.POST)
    public String OrderFulfillmentController.create(@Valid OrderFulfillment orderFulfillment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("orderFulfillment", orderFulfillment);
            return "orderfulfillments/create";
        }
        uiModel.asMap().clear();
        orderFulfillment.persist();
        return "redirect:/orderfulfillments/" + encodeUrlPathSegment(conversionService.convert(orderFulfillment.getId(), String.class), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String OrderFulfillmentController.createForm(Model uiModel) {
        uiModel.addAttribute("orderFulfillment", new OrderFulfillment());
        return "orderfulfillments/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String OrderFulfillmentController.show(@PathVariable("id") OrderFulfillmentPk id, Model uiModel) {
        uiModel.addAttribute("orderfulfillment", OrderFulfillment.findOrderFulfillment(id));
        uiModel.addAttribute("itemId", conversionService.convert(id, String.class));
        return "orderfulfillments/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String OrderFulfillmentController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("orderfulfillments", OrderFulfillment.findOrderFulfillmentEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) OrderFulfillment.countOrderFulfillments() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("orderfulfillments", OrderFulfillment.findAllOrderFulfillments());
        }
        return "orderfulfillments/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String OrderFulfillmentController.update(@Valid OrderFulfillment orderFulfillment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("orderFulfillment", orderFulfillment);
            return "orderfulfillments/update";
        }
        uiModel.asMap().clear();
        orderFulfillment.merge();
        return "redirect:/orderfulfillments/" + encodeUrlPathSegment(conversionService.convert(orderFulfillment.getId(), String.class), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String OrderFulfillmentController.updateForm(@PathVariable("id") OrderFulfillmentPk id, Model uiModel) {
        uiModel.addAttribute("orderFulfillment", OrderFulfillment.findOrderFulfillment(id));
        return "orderfulfillments/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String OrderFulfillmentController.delete(@PathVariable("id") OrderFulfillmentPk id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        OrderFulfillment.findOrderFulfillment(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/orderfulfillments";
    }
    
    @ModelAttribute("orderfulfillments")
    public Collection<OrderFulfillment> OrderFulfillmentController.populateOrderFulfillments() {
        return OrderFulfillment.findAllOrderFulfillments();
    }
    
    String OrderFulfillmentController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
