// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AlarmContactIntegrationTest_Roo_Configurable {
    
    declare @type: AlarmContactIntegrationTest: @Configurable;
    
}
