// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;
import java.util.Random;

privileged aspect CarrierMesDataOnDemand_Roo_DataOnDemand {

    declare @type: CarrierMesDataOnDemand:@Component;

    private Random CarrierMesDataOnDemand.rnd = new java.security.SecureRandom();

    private List<CarrierMes> CarrierMesDataOnDemand.data;

    @Autowired
    private DieDataOnDemand CarrierMesDataOnDemand.dieDataOnDemand;

    @Autowired
    private StopDataOnDemand CarrierMesDataOnDemand.stopDataOnDemand;

    public CarrierMes CarrierMesDataOnDemand.getNewTransientCarrierMes(int index) {
        CarrierMes obj = new CarrierMes();
        setCarrierNumber(obj, index);
        setTagId(obj, index);
        setDieNumber(obj, index);
        setQuantity(obj, index);
        setUpdateDate(obj, index);
        setCurrentLocation(obj, index);
        setDestination(obj, index);
        setStatus(obj, index);
        setOriginationLocation(obj, index);
        setBuffer(obj, index);
        setSource(obj, "user");
        return obj;
    }

    public void CarrierMesDataOnDemand.setCarrierNumber(CarrierMes obj, int index) {
        Integer carrierNumber = new Integer(index);
        obj.setCarrierNumber(carrierNumber);
    }

    public void CarrierMesDataOnDemand.setTagId(CarrierMes obj, int index) {
        obj.setTagId(index);
    }

    public void CarrierMesDataOnDemand.setQuantity(CarrierMes obj, int index) {
        Integer quantity = new Integer(index);
        obj.setQuantity(quantity);
    }

    public void CarrierMesDataOnDemand.setUpdateDate(CarrierMes obj, int index) {
        obj.setUpdateDate(new Date());
    }

    public void CarrierMesDataOnDemand.setDieNumber(CarrierMes obj, int index) {
        obj.setDieNumber(index % 10);
    }

    public void CarrierMesDataOnDemand.setCurrentLocation(CarrierMes obj, int index) {
        obj.setCurrentLocation(513L);
    }

    public void CarrierMesDataOnDemand.setDestination(CarrierMes obj, int index) {
        obj.setCurrentLocation(1200L + index);
    }

    public void CarrierMesDataOnDemand.setStatus(CarrierMes obj, int index) {
        obj.setStatus(0);
    }

    public void CarrierMesDataOnDemand.setOriginationLocation(CarrierMes obj, int index) {
        obj.setOriginationLocation(index);
    }

    public void CarrierMesDataOnDemand.setBuffer(CarrierMes obj, int index) {
        obj.setBuffer(index % 1);
    }

    public void CarrierMesDataOnDemand.setSource(CarrierMes obj, String source) {
        obj.setSource(source);
    }
    public CarrierMes CarrierMesDataOnDemand.getSpecificCarrier(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        CarrierMes obj = data.get(index);
        return CarrierMes.findCarrier(obj.getId());
    }

    public CarrierMes CarrierMesDataOnDemand.getRandomCarrier() {
        init();
        CarrierMes obj = data.get(rnd.nextInt(data.size()));
        return CarrierMes.findCarrier(obj.getId());
    }

    public boolean CarrierMesDataOnDemand.modifyCarrier(CarrierMes obj) {
        return false;
    }

    public void CarrierMesDataOnDemand.init() {
        data = CarrierMes.findCarrierEntries(0, 10);
        if (data == null)
            throw new IllegalStateException("Find entries implementation for 'Carrier' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }

        data = new java.util.ArrayList<CarrierMes>();
        for (int i = 0; i < 10; i++) {
            CarrierMes obj = getNewTransientCarrierMes(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }

}
