// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import com.honda.mfg.stamp.conveyor.domain.enums.DEFECT_TYPE;
import com.honda.mfg.stamp.conveyor.domain.enums.REWORK_METHOD;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Random;

privileged aspect DefectDataOnDemand_Roo_DataOnDemand {

    declare @type: DefectDataOnDemand:@Component;

    private Random DefectDataOnDemand.rnd = new java.security.SecureRandom();

    private List<Defect> DefectDataOnDemand.data;

    public Defect DefectDataOnDemand.getNewTransientDefect(int index) {
        com.honda.mfg.stamp.conveyor.domain.Defect obj = new com.honda.mfg.stamp.conveyor.domain.Defect();
        setCarrierNumber(obj, index);
        setProductionRunNo(obj, index);
        setDefectType(obj, index);
        setReworkMethod(obj, index);
        setXArea(obj, index);
        setYArea(obj, index);
        setDefectTimestamp(obj, index);
        setDefectRepaired(obj, index);
        setSource(obj, index);
        setNote(obj, index);
        return obj;
    }

    public void DefectDataOnDemand.setCarrierNumber(Defect obj, int index) {
        Integer carrierNumber = new Integer(index);
        obj.setCarrierNumber(carrierNumber);
    }

    public void DefectDataOnDemand.setProductionRunNo(Defect obj, int index) {
        Integer productionRunNo = new Integer(index);
        obj.setProductionRunNo(productionRunNo);
    }

    public void DefectDataOnDemand.setDefectType(Defect obj, int index) {
        DEFECT_TYPE defectType = DEFECT_TYPE.class.getEnumConstants()[0];
        obj.setDefectType(defectType);
    }

    public void DefectDataOnDemand.setReworkMethod(Defect obj, int index) {
        REWORK_METHOD reworkMethod = REWORK_METHOD.class.getEnumConstants()[0];
        obj.setReworkMethod(reworkMethod);
    }

    public void DefectDataOnDemand.setXArea(Defect obj, int index) {
        Integer xArea = new Integer(index);
        obj.setXArea(xArea);
    }

    public void DefectDataOnDemand.setYArea(Defect obj, int index) {
        String yArea = "yArea_" + index;
        obj.setYArea(yArea);
    }

    public void DefectDataOnDemand.setNote(Defect obj, int index) {
        String source = "note_" + index;
        obj.setSource(source);
    }

    public void DefectDataOnDemand.setSource(Defect obj, int index) {
        String source = "user_" + index;
        obj.setSource(source);
    }

    public void DefectDataOnDemand.setDefectTimestamp(Defect obj, int index) {
        java.util.Date defectTimestamp = new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDefectTimestamp(defectTimestamp);
    }

    public void DefectDataOnDemand.setDefectRepaired(Defect obj, int index) {
        Boolean defectRepaired = Boolean.TRUE;
        obj.setDefectRepaired(defectRepaired);
    }

    public Defect DefectDataOnDemand.getSpecificDefect(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Defect obj = data.get(index);
        return Defect.findDefect(obj.getId());
    }

    public Defect DefectDataOnDemand.getRandomDefect() {
        init();
        Defect obj = data.get(rnd.nextInt(data.size()));
        return Defect.findDefect(obj.getId());
    }

    public boolean DefectDataOnDemand.modifyDefect(Defect obj) {
        return false;
    }

    public void DefectDataOnDemand.init() {
        data = com.honda.mfg.stamp.conveyor.domain.Defect.findDefectEntries(0, 10);
        if (data == null)
            throw new IllegalStateException("Find entries implementation for 'Defect' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }

        data = new java.util.ArrayList<com.honda.mfg.stamp.conveyor.domain.Defect>();
        for (int i = 0; i < 10; i++) {
            com.honda.mfg.stamp.conveyor.domain.Defect obj = getNewTransientDefect(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }

}
