// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import com.honda.mfg.stamp.conveyor.domain.PressActivity;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PressActivityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PressActivityDataOnDemand: @Component;
    
    private Random PressActivityDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PressActivity> PressActivityDataOnDemand.data;
    
    public PressActivity PressActivityDataOnDemand.getNewTransientPressActivity(int index) {
        com.honda.mfg.stamp.conveyor.domain.PressActivity obj = new com.honda.mfg.stamp.conveyor.domain.PressActivity();
        setPressName(obj, index);
        setProdRunNumber(obj, index);
        setDieNumber(obj, index);
        setQuantityProduced(obj, index);
        return obj;
    }
    
    public void PressActivityDataOnDemand.setPressName(PressActivity obj, int index) {
        java.lang.String pressName = "pressName_" + index;
        obj.setPressName(pressName);
    }
    
    public void PressActivityDataOnDemand.setProdRunNumber(PressActivity obj, int index) {
        java.lang.Integer prodRunNumber = new Integer(index);
        obj.setProdRunNumber(prodRunNumber);
    }
    
    public void PressActivityDataOnDemand.setDieNumber(PressActivity obj, int index) {
        java.lang.Integer dieNumber = new Integer(index);
        obj.setDieNumber(dieNumber);
    }
    
    public void PressActivityDataOnDemand.setQuantityProduced(PressActivity obj, int index) {
        java.lang.Integer quantityProduced = new Integer(index);
        obj.setQuantityProduced(quantityProduced);
    }
    
    public PressActivity PressActivityDataOnDemand.getSpecificPressActivity(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PressActivity obj = data.get(index);
        return PressActivity.findPressActivity(obj.getId());
    }
    
    public PressActivity PressActivityDataOnDemand.getRandomPressActivity() {
        init();
        PressActivity obj = data.get(rnd.nextInt(data.size()));
        return PressActivity.findPressActivity(obj.getId());
    }
    
    public boolean PressActivityDataOnDemand.modifyPressActivity(PressActivity obj) {
        return false;
    }
    
    public void PressActivityDataOnDemand.init() {
        data = com.honda.mfg.stamp.conveyor.domain.PressActivity.findPressActivityEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PressActivity' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.honda.mfg.stamp.conveyor.domain.PressActivity>();
        for (int i = 0; i < 10; i++) {
            com.honda.mfg.stamp.conveyor.domain.PressActivity obj = getNewTransientPressActivity(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
