// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.honda.mfg.stamp.conveyor.domain;

import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Random;

privileged aspect WeldScheduleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WeldScheduleDataOnDemand: @Component;
    
    private Random WeldScheduleDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<WeldSchedule> WeldScheduleDataOnDemand.data;
    
    public WeldSchedule WeldScheduleDataOnDemand.getNewTransientWeldSchedule(int index) {
        com.honda.mfg.stamp.conveyor.domain.WeldSchedule obj = new com.honda.mfg.stamp.conveyor.domain.WeldSchedule();
        setWeldLine(obj, index);
        setLeftHandProdPlan(obj, index);
        setLeftHandProdRemaining(obj, index);
        setRightHandProdPlan(obj, index);
        setRightHandProdRemaining(obj, index);
        setCurrentModel(obj, index);
        setNextModel(obj, index);
        setNextQuantity(obj, index);
        return obj;
    }

    public void WeldScheduleDataOnDemand.setWeldLine(WeldSchedule obj, int index) {
        java.lang.Integer weldLine = new Integer(index);
        obj.setWeldLine(weldLine);
    }
    public void WeldScheduleDataOnDemand.setLeftHandProdPlan(WeldSchedule obj, int index) {
        java.lang.Integer leftHandProdPlan = new Integer(index);
        obj.setLeftHandProdPlan(leftHandProdPlan);
    }
    
    public void WeldScheduleDataOnDemand.setLeftHandProdRemaining(WeldSchedule obj, int index) {
        java.lang.Integer leftHandProdRemaining = new Integer(index);
        obj.setLeftHandProdRemaining(leftHandProdRemaining);
    }
    
    public void WeldScheduleDataOnDemand.setRightHandProdPlan(WeldSchedule obj, int index) {
        java.lang.Integer rightHandProdPlan = new Integer(index);
        obj.setRightHandProdPlan(rightHandProdPlan);
    }

    public void WeldScheduleDataOnDemand.setRightHandProdRemaining(WeldSchedule obj, int index) {
        java.lang.Integer rightHandProdRemaining = new Integer(index);
        obj.setRightHandProdRemaining(rightHandProdRemaining);
    }

     public void WeldScheduleDataOnDemand.setCurrentModel(WeldSchedule obj, int index) {
        java.lang.Integer currentModel = new Integer(index);
        obj.setCurrentModel(currentModel);
    }

     public void WeldScheduleDataOnDemand.setNextModel(WeldSchedule obj, int index) {
        java.lang.Integer nextModel = new Integer(index);
        obj.setNextModel(nextModel);
    }

     public void WeldScheduleDataOnDemand.setNextQuantity(WeldSchedule obj, int index) {
        java.lang.Integer nextQuantity = new Integer(index);
        obj.setNextQuantity(nextQuantity);
    }
    
    public WeldSchedule WeldScheduleDataOnDemand.getSpecificWeldSchedule(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        WeldSchedule obj = data.get(index);
        return WeldSchedule.findWeldSchedule(obj.getId());
    }
    
    public WeldSchedule WeldScheduleDataOnDemand.getRandomWeldSchedule() {
        init();
        WeldSchedule obj = data.get(rnd.nextInt(data.size()));
        return WeldSchedule.findWeldSchedule(obj.getId());
    }
    
    public boolean WeldScheduleDataOnDemand.modifyWeldSchedule(WeldSchedule obj) {
        return false;
    }
    
    public void WeldScheduleDataOnDemand.init() {
        data = com.honda.mfg.stamp.conveyor.domain.WeldSchedule.findWeldScheduleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'WeldSchedule' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.honda.mfg.stamp.conveyor.domain.WeldSchedule>();
        for (int i = 0; i < 10; i++) {
            com.honda.mfg.stamp.conveyor.domain.WeldSchedule obj = getNewTransientWeldSchedule(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
