package com.honda.galc.property;

import java.util.Map;

import com.honda.galc.property.IProperty;
import com.honda.galc.property.PropertyBean;
import com.honda.galc.property.PropertyBeanAttribute;

/**
 * <h3>Class description</h3> <h4>Description</h4>
 * <p>
 * <code>DunnagePropertyBean</code> is ... .
 * </p>
 * <h4>Usage and Example</h4> <h4>Special Notes</h4>
 * 
 * <h4>Change History</h4>
 * <Table border="1" Cellpadding="3" Cellspacing="0" width="100%">
 * <TR bgcolor="#EEEEFF" Class="TableSubHeadingColor">
 * <TH>Update by</TH>
 * <TH>Update date</TH>
 * <TH>Version</TH>
 * <TH>Mark of Update</TH>
 * <TH>Reason</TH>
 * </TR>
 * <TR>
 * <TD>&nbsp;</TD>
 * <TD>&nbsp;</TD>
 * <TD>0.1</TD>
 * <TD>(none)</TD>
 * <TD>Initial Realse</TD>
 * </TR>
 * </TABLE>
 * 
 * @see
 * @ver 0.1
 * @author Karol Wozniak
 * @created Apr 26, 2013
 */

@PropertyBean(componentId = "DEFAULT_DUNNAGE")
public interface DunnagePropertyBean extends IProperty {

	@PropertyBeanAttribute(defaultValue = "24")
	public int getBlockDunnageCartQuantity();

	@PropertyBeanAttribute(defaultValue = "72")
	public int getHeadDunnageCartQuantity();
	
	@PropertyBeanAttribute(defaultValue = "15")
	public int getDunnageCartQuantity();

	@PropertyBeanAttribute(defaultValue = "false")
	public boolean isDunnageNumberAutoGenerated();

	@PropertyBeanAttribute(defaultValue = "12")
	public int getDunnageNumberLength();

	@PropertyBeanAttribute(defaultValue = "")
	public String[] getOffProcessPointIds();

	@PropertyBeanAttribute(defaultValue = "")
	public String getOffLabel();

	@PropertyBeanAttribute(propertyKey = "SHIPPING_PROCESS_POINT_ID", defaultValue = "")
	public String getShippingProcessPointId();
	
	@PropertyBeanAttribute(propertyKey = "DUNNAGE_PRINTER", defaultValue = "")
	public String getDunnagePrinter();
	
	@PropertyBeanAttribute(propertyKey = "DUNNAGE_FORM", defaultValue = "")
	public String getDunnageForm();
	
	/**
	 * Property for Dunnage to check weather to use new DunnageContent_tbx or not
	 * 
	 * @return
	 */
	@PropertyBeanAttribute(defaultValue = "false")
	public boolean isInsertDunnageContent();
	
	/**
	 * Property for Dunnage to check if differnt models are allowed or not
	 * 
	 * @return
	 */
	@PropertyBeanAttribute(defaultValue = "false")
	public boolean isSameModelCode();
	
	/**
	 * Property for Dunnage to check if model and model type comparison must be performed
	 * 
	 * @return
	 */
	@PropertyBeanAttribute(propertyKey = "DUNNAGE_GROUPED_BY_MODEL_TYPE",defaultValue = "false")
	public boolean isDunnageGroupedByModelType();
	
	/**
	 * Indicates if partial (not full capacity) dunnage can be shipped. 
	 * @return
	 */
	@PropertyBeanAttribute(defaultValue = "true")
	public boolean isPartialDunnageShippable();
	
	
	/**
	 * Comma separated authorized security groups, mapped by ACTION_ID
	 * <br />
	 * <PRE>
	 * property : AUTHORIZATION_GROUP{ACTION_ID}:GROUP_ID
	 * sample   : AUTHORIZATION_GROUP{ADD_TO_DUNNAGE}:SA
	 *            AUTHORIZATION_GROUP{REMOVE_FROM_DUNNAGE}:RU
	 * </PRE>
	 * @return
	 */
	@PropertyBeanAttribute
	public Map<String, String> getAuthorizationGroup();
	
	/**
	 * Property for Dunnage to check weather to validate Dunnage pattern
	 * 
	 * @return
	 */
	@PropertyBeanAttribute(defaultValue = "true")
	public boolean isCheckDunnageId();
	
	@PropertyBeanAttribute(defaultValue = "AAA")
	public String getMachineId();
	
	
	/**
	 * Indicates if dunnageAssociation history need to be created. 
	 * @return
	 */
	@PropertyBeanAttribute(defaultValue = "false")
	public boolean isCreateDunnageHistory();
}
