ALTER TABLE ORDER_FULFILLMENT_TBX DROP CONSTRAINT ORDER_FULFILLMENT_PK;
ALTER TABLE ORDER_FULFILLMENT_TBX ALTER COLUMN RELEASE_CYCLE SET NOT NULL;

CALL sysproc.admin_cmd ('REORG TABLE ORDER_FULFILLMENT_TBX');

ALTER TABLE ORDER_FULFILLMENT_TBX ADD CONSTRAINT ORDER_FULFILLMENT_PK  PRIMARY KEY( WELD_ORDER, CARRIER_NUMBER, RELEASE_CYCLE);