CREATE TABLE "GALADM"."MBPN_TBX" (
  PRODUCT_SPEC_CODE	CHARACTER(30)	NOT NULL,
  MBPN	CHARACTER(18)	NOT NULL,
  HES_COLOR	CHARACTER(11)	NOT NULL,
  MAIN_NO	CHARACTER(5)	NOT NULL,
  CLASS_NO	CHARACTER(3)	NOT NULL,
  PROTOTYPE_CODE	CHARACTER(1)	NOT NULL,
  TYPE_NO	CHARACTER(4)	NOT NULL,
  SUPPLEMENTARY_NO	CHARACTER(2)	NOT NULL,
  TARGET_NO	CHARACTER(2)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."MBPN_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."MBPN_TBX" IS 'MBPN';

ALTER TABLE "GALADM"."MBPN_TBX" ADD CONSTRAINT "MBPN_PK" PRIMARY KEY
 ("PRODUCT_SPEC_CODE");

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."MBPN_TBX" TO GROUP "GALQQA_A";

GRANT SELECT ON TABLE "GALADM"."MBPN_TBX" TO GROUP "GALQQA_S";

COMMIT;
