ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL215TBX  
  ALTER COLUMN PRODUCT_SPEC_CODE  
    SET DATA TYPE CHARACTER(30); 
     
ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE CHANGES; 

REORG TABLE GALADM.GAL215TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL215TBX;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  ALTER COLUMN HOST_IP
    SET DATA TYPE VARCHAR (255)
  ALTER COLUMN HOST_PORT
    SET DATA TYPE INTEGER
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_PROVIDER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_PROVIDER_TBX;

COMMENT ON TABLE GALADM.NOTIFICATION_PROVIDER_TBX IS
   'RMT NotificationProvider for managing hosts setup for asynchronous communication';
