ALTER TABLE CARRIER_RELEASE_TBX ADD COLUMN CURRENT_LOCATION BIGINT REFERENCES STOP_TBX(STOP_ID);

CALL sysproc.admin_cmd('REORD TABLE CARRIER_RELEASE_TBX');

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "STAMPSTOR"."ATTRIBUTES_TBX" TO GROUP "OHCVA_PA";	
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "STAMPSTOR"."ATTRIBUTE_TYPES_TBX" TO GROUP "OHCVA_PA";	

GRANT SELECT ON TABLE "STAMPSTOR"."ATTRIBUTES_TBX" TO GROUP "OHCVA_PS";
GRANT SELECT ON TABLE "STAMPSTOR"."ATTRIBUTE_TYPES_TBX" TO GROUP "OHCVA_PS";