--HMIN security variable (:SEC) examples by database
--GALCDBSB = GALCSB
--GALCDBDV = GALCDV
--GALCDBQA = GALCQA
--GALQDBQA = GALQQA
--GALARCQA = GALAQA
--GALCDBPR = GALCPR
--GALQDBPR = GALQPR
--GALARCPR = GALAPR

--Grant security for tables and views
select
--GRA.GRANTEE
--,tab.TABSCHEMA,tab.TABNAME
--,auth.GRANTEE
CASE WHEN RIGHT(GRA.GRANTEE,1)='A'
THEN 'GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE '||TRIM(tab.TABSCHEMA)||'.'||tab.TABNAME||' TO GROUP '||GRA.GRANTEE||';'
ELSE 'GRANT SELECT ON TABLE '||TRIM(tab.TABSCHEMA)||'.'||tab.TABNAME||' TO GROUP '||GRA.GRANTEE||';'
END
from 
(SELECT GRANTEE
FROM SYSCAT.TABAUTH
WHERE GRANTEE IN (:SEC||'_A',:SEC||'_S')
GROUP BY GRANTEE) AS GRA LEFT JOIN SYSCAT.TABLES tab ON tab.TABSCHEMA='GALADM'
left join SYSCAT.TABAUTH auth on tab.TABNAME=auth.TABNAME and auth.GRANTEE = GRA.GRANTEE
where TAB.TABSCHEMA='GALADM' AND tab.TYPE IN ('T','V') AND auth.GRANTEE IS NULL
order by tab.TABSCHEMA,tab.TABNAME,GRA.GRANTEE
;

--Grant security for functions
SELECT 
'GRANT EXECUTE ON SPECIFIC FUNCTION  '||TRIM(FUN.FUNCSCHEMA)||'.'||FUN.SPECIFICNAME||' TO GROUP '||GRA.GRANTEE||';'
--,FUN.FUNCSCHEMA,FUN.SPECIFICNAME,GRA.GRANTEE,AUTH.GRANTEE,FUN.*
FROM 
(SELECT GRANTEE
FROM SYSCAT.TABAUTH
WHERE GRANTEE IN (:SEC||'_A',:SEC||'_S')
GROUP BY GRANTEE) AS GRA LEFT JOIN SYSCAT.FUNCTIONS FUN ON FUN.FUNCSCHEMA='GALADM'
LEFT JOIN SYSCAT.ROUTINEAUTH AUTH ON FUN.SPECIFICNAME = AUTH.SPECIFICNAME AND AUTH.GRANTEE=GRA.GRANTEE
WHERE FUN.FUNCSCHEMA='GALADM'
 AND auth.GRANTEE IS NULL
order by FUN.FUNCSCHEMA,FUN.SPECIFICNAME,GRA.GRANTEE;

--Grant security for procedures
SELECT 
'GRANT EXECUTE ON SPECIFIC FUNCTION  '||TRIM(PRO.PROCSCHEMA)||'.'||PRO.SPECIFICNAME||' TO GROUP '||GRA.GRANTEE||';'
--,PRO.PROCSCHEMA,PRO.SPECIFICNAME,GRA.GRANTEE,AUTH.GRANTEE,PRO.*
FROM 
(SELECT GRANTEE
FROM SYSCAT.TABAUTH
WHERE GRANTEE IN (:SEC||'_A',:SEC||'_S')
GROUP BY GRANTEE) AS GRA LEFT JOIN SYSCAT.PROCEDURES PRO ON PRO.PROCSCHEMA='GALADM'
LEFT JOIN SYSCAT.ROUTINEAUTH AUTH ON PRO.SPECIFICNAME = AUTH.SPECIFICNAME AND AUTH.GRANTEE=GRA.GRANTEE
WHERE PRO.PROCSCHEMA='GALADM'
 AND auth.GRANTEE IS NULL
order by PRO.PROCSCHEMA,PRO.SPECIFICNAME,GRA.GRANTEE;



--Test selecting
select
--'SELECT * FROM '||TRIM(tab.TABSCHEMA)||'.'||tab.TABNAME||' FETCH FIRST 1 ROW ONLY;'
TAB.*
from 
SYSCAT.TABLES tab
where TAB.TABSCHEMA='GALADM' AND tab.TYPE IN ('A','T') AND tab.REMARKS LIKE 'RMT%'
order by tab.TABSCHEMA,coalesce(tab.BASE_TABNAME,tab.TABNAME)
;

COMMENT ON ALIAS GALADM.HCM_BLOCK_BUILD_RESULTS_TBX IS 'RMT';