<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/data">
	<xsl:text>VIN1, IPU S/N, BAT S/N(Recycle No.), IPU QA Date(Local Time), IPU QA Date(UTC), IPU QA Status, Cell voltage status, Cell Voltage(VBC1), Cell Voltage(VBC2), Cell Voltage(VBC3), Cell Voltage(VBC4), Cell Voltage(VBC5), Cell Voltage(VBC6), Cell Voltage(VBC7), Cell Voltage(VBC8), Cell Voltage(VBC9), Cell Voltage(VBC10), Cell Voltage(VBC11), Cell Voltage(VBC12), Cell Voltage(VBC13), Cell Voltage(VBC14), Cell Voltage(VBC15), Cell Voltage(VBC16), Cell Voltage(VBC17), Cell Voltage(VBC18), Cell Voltage(VBC19), Cell Voltage(VBC20), Cell Voltage(VBC21), Cell Voltage(VBC22), Cell Voltage(VBC23), Cell Voltage(VBC24), Cell Voltage(VBC25), Cell Voltage(VBC26), Cell Voltage(VBC27), Cell Voltage(VBC28), Cell Voltage(VBC29), Cell Voltage(VBC30), Cell Voltage(VBC31), Cell Voltage(VBC32), Cell Voltage(VBC33), Cell Voltage(VBC34), Cell Voltage(VBC35), Cell Voltage(VBC36), Cell Voltage(VBC37), Cell Voltage(VBC38), Cell Voltage(VBC39), Cell Voltage(VBC40), Cell Voltage(VBC41), Cell Voltage(VBC42), Cell Voltage(VBC43), Cell Voltage(VBC44), Cell Voltage(VBC45), Cell Voltage(VBC46), Cell Voltage(VBC47), Cell Voltage(VBC48), Cell Voltage(VBC49), Cell Voltage(VBC50), Cell Voltage(VBC51), Cell Voltage(VBC52), Cell Voltage(VBC53), Cell Voltage(VBC54), Cell Voltage(VBC55), Cell Voltage(VBC56), Cell Voltage(VBC57), Cell Voltage(VBC58), Cell Voltage(VBC59), Cell Voltage(VBC60), Cell Voltage(VBC61), Cell Voltage(VBC62), Cell Voltage(VBC63), Cell Voltage(VBC64), Cell Voltage(VBC65), Cell Voltage(VBC66), Cell Voltage(VBC67), Cell Voltage(VBC68), Cell Voltage(VBC69), Cell Voltage(VBC70), Cell Voltage(VBC71), Cell Voltage(VBC72)&#x0A;</xsl:text>
      <xsl:for-each select="IPU">
        <xsl:value-of select="concat(VIN, ', ', IPU_SN,', ', BAT_SN,', ', QA_DATE_LOCAL,', ', QA_DATE_UTC,', ',IPU_QA_STATUS, ', ', CELL_STATUS,', ',VBC1,', ',VBC2,', ',VBC3,', ',VBC4,', ',VBC5,', ',VBC6, ', ',VBC7,', ',VBC8,', ',VBC9,', ',VBC10,', ',VBC11,', ',VBC12,', ',VBC13,', ',VBC14,', ',VBC15,', ',VBC16, ', ',VBC17,', ',VBC18,', ',VBC19,', ',VBC20,', ',VBC21,', ',VBC22,', ',VBC23,', ',VBC24,', ',VBC25,', ',VBC26, ', ',VBC27,', ',VBC28,', ',VBC29,', ',VBC30,', ',VBC31,', ',VBC32,', ',VBC33,', ',VBC34,', ',VBC35,', ',VBC36, ', ',VBC37,', ',VBC38,', ',VBC39,', ',VBC40,', ',VBC41,', ',VBC42,', ',VBC43)"/> 
		<xsl:text>&#x0A;</xsl:text>
      </xsl:for-each>
</xsl:template>
</xsl:stylesheet>
