CREATE TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" (
  TRACKING_STATUS	CHARACTER(16)	NOT NULL,
  TRACKING_SEQUENCE_NO	DOUBLE	NOT NULL,
  ORDER_NO	CHARACTER(20),
  PRODUCT_ID	CHARACTER(17),
  PLAN_TIMESTAMP	TIMESTAMP,
  FORECAST_TIMESTAMP	TIMESTAMP,
  ACTUAL_TIMESTAMP	TIMESTAMP,
  PLAN_STATUS_ID	INTEGER,
  CONTAINER_ID    CHARACTER(17),
  CONTAINER_POS   INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
)
  IN "GALTBSDAT6"
  INDEX IN "GALTBSIDX2";

ALTER TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" IS 'Product Priority Plan';
COMMENT ON COLUMN "GALADM"."PRODUCT_PRIORITY_PLAN_TBX"."PLAN_STATUS_ID" IS 'Link to PLAN_STATUS_TBX';

ALTER TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" ADD CONSTRAINT "PRODUCT_PRIORITY_PLAN_PK" PRIMARY KEY
 ("TRACKING_STATUS","TRACKING_SEQUENCE_NO");

CREATE TRIGGER "GALADM"."PRODUCT_PRIORITY_PLAN_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."PRODUCT_PRIORITY_PLAN_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PRODUCT_PRIORITY_PLAN_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."PRODUCT_PRIORITY_PLAN_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" TO GROUP "GALCPR_S";

COMMIT;
