--Confirm no invalid objects
SELECT * FROM SYSCAT.INVALIDOBJECTS
ORDER BY OBJECTSCHEMA, OBJECTNAME;

--Confirm no invalid triggers
SELECT TR.TRIGSCHEMA,TR.TRIGNAME
FROM SYSCAT.TRIGGERS TR
WHERE TR.VALID='X'
ORDER BY TR.TRIGSCHEMA, TR.TRIGNAME;

--Confirm no invalid views
SELECT *
FROM SYSCAT.TABLES
WHERE STATUS='X';


--Setup replication for the following tables
--BLOCK_BUILD_RESULTS_TBX
--BLOCK_HISTORY_TBX
--BLOCK_LOAD_TBX
--BLOCK_TBX
--GAL198_HIST_TBX
--GTS_PRODUCT_TBX
--HEAD_BUILD_RESULTS_TBX
--HEAD_HISTORY_TBX
--HEAD_TBX
--HOLD_PARM_TBX
--HOST_PRIORITY_PLAN_TBX
--PART_LOT_TBX
--PLC_MEMORY_MAP_TBX
--PRODUCT_SEQUENCE_TBX
--PRODUCT_SPEC_CODE_TBX
--QUORUM_DETAIL_TBX
--QUORUM_TBX
--REQUIRED_PARTS_TBX
--SKIPPED_PRODUCT_TBX
--STANDARD_SCHEDULE_TBX
--TRAILER_INFO_TBX
--TRAILER_STATUS_TBX
--VANNING_SCHEDULE_TBX

--Refresh the replication for the following tables due to column updates
--GAL125TBX
--GAL125TBX_AUD
--GAL131TBX
--GAL136TBX
--GAL147TBX
--GAL177TBX
--GAL198TBX
--GAL206TBX
--GAL215TBX
--GAL222TBX
--GAL246TBX
--GAL260TBX
--GAL263TBX
--GAL322TBX
--GAL489TBX
--GAL650TBX
--NOTIFICATION_PROVIDER_TBX
--NOTIFICATION_SUBSCRIBER_TBX
--PART_SPEC_TBX


--Test with the following scripts

--BLOCK_BUILD_RESULTS_TBX
--BLOCK_HISTORY_TBX
--BLOCK_LOAD_TBX
--BLOCK_TBX
--
--GAL125TBX
--GAL125TBX_AUD
--GAL131TBX
--GAL136TBX
--GAL147TBX
--GAL177TBX
--
--GAL198_HIST_TBX

--GAL206TBX
--GAL215TBX
--GAL222TBX
--GAL246TBX
--GAL260TBX
--GAL263TBX
--GAL322TBX
--GAL489TBX
--GAL650TBX
--
--GTS_PRODUCT_TBX
--HEAD_BUILD_RESULTS_TBX
--HEAD_HISTORY_TBX
--HEAD_TBX
--HOLD_PARM_TBX
--HOST_PRIORITY_PLAN_TBX
--
--NOTIFICATION_PROVIDER_TBX
--NOTIFICATION_SUBSCRIBER_TBX
--
--PART_LOT_TBX
--
--PART_SPEC_TBX
--PRODUCT_SEQUENCE_TBX
--PRODUCT_SPEC_CODE_TBX
--QUORUM_DETAIL_TBX
--QUORUM_TBX
--REQUIRED_PARTS_TBX
--SKIPPED_PRODUCT_TBX
--STANDARD_SCHEDULE_TBX
--TRAILER_INFO_TBX
--TRAILER_STATUS_TBX
--VANNING_SCHEDULE_TBX

-----------------Insert records in Production Database

INSERT INTO GALADM.BLOCK_BUILD_RESULTS_TBX
(BLOCK_ID, PART_NAME, ACTUAL_TIMESTAMP, RESULT_VALUE, INSTALLED_PART_STATUS, ASSOCIATE_NO) 
VALUES ('BLOCK_ID_VALUE', 'PART_NAME_VALUE', '20130101010111', 'RESULT_VALUE_VALUE', 1, 'ASSOCIATE');
INSERT INTO GALADM.BLOCK_HISTORY_TBX
(BLOCK_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP, PROCESS_COUNT) 
VALUES ('BLOCK_ID_VALUE', 'PROCESS_POINT', '20130101010111', 1);
INSERT INTO GALADM.BLOCK_LOAD_TBX
(MC_NUMBER, PRODUCTION_LOT, LOT_SIZE, PRODUCT_SPEC_CODE, REFERENCE_NUMBER, STATUS) 
VALUES ('MC_NUMBER_VALUE', 'PRODUCTION_LOT_VALUE', 1, 'PRODUCT_SPEC', 1, 'S');
INSERT INTO GALADM.BLOCK_TBX
(BLOCK_ID, MC_SERIAL_NUMBER, DC_SERIAL_NUMBER, ENGINE_SERIAL_NUMBER, MODEL, TRACKING_STATUS, DUNNAGE, DEFECT_STATUS, HOLD_STATUS, LAST_PASSING_PROCESS_POINT_ID) 
VALUES ('BLOCK_ID_VALUE', 'MC_SERIAL', 'DC_SERIAL', 'ENGINE_SERIAL', 'MODEL_VALUE', 'TRACK', 'DUN', 0, 0, 'LAST_PASSING');
INSERT INTO GALADM.GAL125TBX
(INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECTRESULTID, APPLICATION_ID, PRODUCT_ID, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, ASSOCIATE_NO, SHIFT, DATE, ACTUAL_TIMESTAMP, DEFECT_STATUS, IMAGE_NAME, RESPONSIBLE_DEPT, RESPONSIBLE_ZONE, REPAIR_METHOD_NAME_PLAN, REPAIR_TIME_PLAN, REPAIR_ASSOCIATE_NO_PLAN, REPAIR_ASSOCIATE_NO, WRITE_UP_DEPARTMENT, TWO_PART_DEFECT_FLAG, IQS_CATEGORY_NAME, IQS_ITEM_NAME, REGRESSION_CODE, POINT_X, POINT_Y, ENTRY_DEPT, OUTSTANDING_FLAG, REPAIR_TIMESTAMP, RESPONSIBLE_LINE, GDP_DEFECT, PART_GROUP_NAME) 
VALUES ('INSPECTION_PART', 'INSPECTION_PART_LOC', 'DEFECT_TYPE', 'SECONDARY_PART', 1, 'APPLICATION', 'PRODUCT_ID_VALUE', 'TWO_PART_PAIR_PART_VALUE', 'TWO_PART', 'ASSOCIATE', '02', '01/01/2013', '20130101010111', 0, 'IMAGE', 'RESPONSIBLE_DEPT', 'RESPONSIBLE_ZONE', 'REPAIR_METHOD', 10, 'REP_ASSOC', 'REP_ASSOC', 'WRITE_UP', 0, 'IQS', 'IQS_ITEM', 'REGRESSION', 1, 1, 'ENTRY_DEPT', 1, '20130101010111', 'RESPONSIBLE_LINE', 0, 'PART_GROUP');
INSERT INTO GALADM.GAL125TBX_AUD
(ID, AUDIT_TIMESTAMP, ACTION_TYPE, INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECTRESULTID, APPLICATION_ID, PRODUCT_ID, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, OLD_ASSOCIATE_NO, OLD_SHIFT, OLD_DATE, OLD_ACTUAL_TIMESTAMP, OLD_DEFECT_STATUS, OLD_IMAGE_NAME, OLD_RESPONSIBLE_DEPT, OLD_RESPONSIBLE_ZONE, OLD_REPAIR_METHOD_NAME_PLAN, OLD_REPAIR_TIME_PLAN, OLD_REPAIR_ASSOCIATE_NO_PLAN, OLD_REPAIR_ASSOCIATE_NO, OLD_WRITE_UP_DEPARTMENT, OLD_TWO_PART_DEFECT_FLAG, OLD_IQS_CATEGORY_NAME, OLD_IQS_ITEM_NAME, OLD_REGRESSION_CODE, OLD_POINT_X, OLD_POINT_Y, OLD_ENTRY_DEPT, OLD_OUTSTANDING_FLAG, OLD_REPAIR_TIMESTAMP, OLD_RESPONSIBLE_LINE, NEW_ASSOCIATE_NO, NEW_SHIFT, NEW_DATE, NEW_ACTUAL_TIMESTAMP, NEW_DEFECT_STATUS, NEW_IMAGE_NAME, NEW_RESPONSIBLE_DEPT, NEW_RESPONSIBLE_ZONE, NEW_REPAIR_METHOD_NAME_PLAN, NEW_REPAIR_TIME_PLAN, NEW_REPAIR_ASSOCIATE_NO_PLAN, NEW_REPAIR_ASSOCIATE_NO, NEW_WRITE_UP_DEPARTMENT, NEW_TWO_PART_DEFECT_FLAG, NEW_IQS_CATEGORY_NAME, NEW_IQS_ITEM_NAME, NEW_REGRESSION_CODE, NEW_POINT_X, NEW_POINT_Y, NEW_ENTRY_DEPT, NEW_OUTSTANDING_FLAG, NEW_REPAIR_TIMESTAMP, NEW_RESPONSIBLE_LINE, USER_NAME, CHANGE_NUMBER, CHANGE_DESCRIPTION, OLD_GDP_DEFECT, NEW_GDP_DEFECT) 
VALUES (0, '20130101010111', 'ACTION', 'INSPECTION_PART', 'INSPECTION_PART_LOC', 'DEFECT_TYPE', 'SECONDARY_PART', 0, 'APPLICATION', 'PRODUCT_ID', 'TWO_PART', 'TWO_PART_LOC', 'OLD_ASSOC', '02', '01/01/2013', '20130101010111', 0, 'OLD_IMAGE', 'OLD_RES_DEPT', 'OLD_RESP_ZONE', 'OLD_REPAIR_METHOD', 10, 'OLD_REP_ASS', 'OLD_REP_ASS', 'OLD_WRITE_UP', 0, 'OLD_IQS', 'OLD_IQS_ITEM', 'OLD_REG', 1, 1, 'OLD_ENTRY', 0, '20130101010111', 'OLD_RESP_LINE', 'NEW_ASSOC', '02', '01/01/2013', '20130101010111', 1, 'NEW_IMAGE', 'NEW_RESP_DEPT', 'NEW_RESP_ZONE', 'NEW_REP_METHOD', 11, 'NEW_REP_ASS', 'NEW_REP_ASS', 'NEW_WRITE_UP', 1, 'NEW_IQS', 'NEW_IQS_ITEM', 'NEW_REG', 2, 2, 'NEW_ENTRY', 2, '20130101010111', 'NEW_RESP_LINE', 'USER_NAME', 'CHANGE', 'CHANGE_DESC', 0, 1);
INSERT INTO GALADM.GAL131TBX
(PRODUCT_ID, VIN, MISSION_SERIAL_NO, ENGINE_FIRING_FLAG, PRODUCTION_LOT, KD_LOT_NUMBER, PRODUCT_SPEC_CODE, PLAN_OFF_DATE, TRACKING_STATUS, PRODUCTION_DATE, PRODUCT_START_DATE, ACTUAL_OFF_DATE, AUTO_HOLD_STATUS, LAST_PASSING_PROCESS_POINT_ID, MISSION_STATUS, FIRING_TYPE, REPAIR_FLAG, ACTUAL_MISSION_TYPE, PLANT_CODE, DEFECT_STATUS) 
VALUES ('PRODUCT_ID_VALUE', 'VIN_VALUE', 'MISSION_SERIAL', 0, 'PRODUCTION_LOT', 'KD_LOT', 'PRODUCT_SPEC', '01/01/2013', 'TRACKING_STATUS', '01/01/2013', '01/01/2013', '01/01/2013', 0, 'LAST_PASS', 0, 0, 0, 'MISSION', 'PLA', 0);
INSERT INTO GALADM.GAL136TBX
(PRODUCT_ID, ACTUAL_TIMESTAMP, ASSOCIATE_NO, EXCEPTIONAL_OUT_COMMENT, EXCEPTIONAL_OUT_REASON_STRING, PRODUCTION_DATE, PROCESS_POINT_ID, LOCATION) 
VALUES ('PRODUCT_ID_VALUE', '20130101010111', 'ASSOC', 'EXCEPTIONAL_OUT_COMMENT_VALUE', 'EXCEPTIONAL_OUT_REASON_STRING_VALUE', '01/01/2013', 'PROCESS_POINT', 'LOCATION_VALUE');
INSERT INTO GALADM.GAL147TBX
(PRODUCT_ID, ACTUAL_TIMESTAMP, HOLD_TYPE, RELEASE_TIMESTAMP, RELEASE_FLAG, HOLD_ASSOCIATE_NO, HOLD_ASSOCIATE_NAME, HOLD_ASSOCIATE_PHONE, HOLD_ASSOCIATE_PAGER, HOLD_REASON, RELEASE_ASSOCIATE_NO, RELEASE_ASSOCIATE_NAME, RELEASE_ASSOCIATE_PHONE, RELEASE_ASSOCIATE_PAGER, RELEASE_REASON, LOT_HOLD_STATUS, PRODUCTION_LOT, PRODUCT_SPEC_CODE, PRODUCTION_DATE, QSR_ID) 
VALUES ('PRODUCT_ID_VALUE', '20130101010111', 0, '20130101010111', 0, 'HOLD_ASSOC', 'ASSOC_NAME', 'PHONE', 'PAGER', 'HOLD_REASON_VALUE', 'REL_ASSOC', 'REL_ASSOC', 'RELEASE_PHONE', 'RELEASE_PAGERE', 'RELEASE_REASON_VALUE', 0, 'PRODUCTION_LOT', 'PRODUCT_SPEC_CODE', '01/01/2013', 0);
INSERT INTO GALADM.GAL177TBX
(REPAIR_AREA_NAME, PRODUCT_ID, PARKING_LOCATION, ACTUAL_TIMESTAMP, REJECTION, RESPONSIBLE_DEPT) 
VALUES ('REPAIR_AREA', 'PRODUCT_ID_VALUE', 'LOC', '20130101010111', 'REJECTION_VALUE', 'RESPONSIBLE_DEPT_VALUE');
INSERT INTO GALADM.GAL198TBX(PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_VALUE, MEASUREMENT_STATUS, ACTUAL_TIMESTAMP, MEASUREMENT_ANGLE, PART_SERIAL_NUMBER) VALUES
('TEST', 'SIM_0SCAN_1TORQ_PT1             ', 1, 10.1, 1, '20130101010111', 10, 'SERIAL NUM');
DELETE FROM GALADM.GAL198TBX WHERE PRODUCT_ID='TEST' AND PART_NAME='SIM_0SCAN_1TORQ_PT1             ' AND MEASUREMENT_SEQUENCE_NUMBER=1;
INSERT INTO GALADM.GAL198TBX(PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_VALUE, MEASUREMENT_STATUS, ACTUAL_TIMESTAMP, MEASUREMENT_ANGLE, PART_SERIAL_NUMBER) VALUES
('TEST', 'SIM_0SCAN_1TORQ_PT1             ', 1, 10.2, 1, '20130101010222', 10, 'SERIAL NUM');
DELETE FROM GALADM.GAL198TBX WHERE PRODUCT_ID='TEST' AND PART_NAME='SIM_0SCAN_1TORQ_PT1             ' AND MEASUREMENT_SEQUENCE_NUMBER=1;
INSERT INTO GALADM.GAL198TBX(PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_VALUE, MEASUREMENT_STATUS, ACTUAL_TIMESTAMP, MEASUREMENT_ANGLE, PART_SERIAL_NUMBER) VALUES
('TEST', 'SIM_0SCAN_1TORQ_PT1             ', 1, 10.3, 1, '20130101010333', 10, 'SERIAL NUM');
UPDATE GALADM.GAL198TBX
SET MEASUREMENT_VALUE=10.4,ACTUAL_TIMESTAMP='20130314150444'
WHERE PRODUCT_ID='TEST' AND PART_NAME='SIM_0SCAN_1TORQ_PT1             ' AND MEASUREMENT_SEQUENCE_NUMBER=1;
INSERT INTO GALADM.GAL198_HIST_TBX
(PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_ATTEMPT, MEASUREMENT_VALUE, MEASUREMENT_STATUS, ACTUAL_TIMESTAMP, MEASUREMENT_ANGLE, PART_SERIAL_NUMBER) 
VALUES ('PRODUCT_ID_VALUE', 'PART_NAME_VALUE', 1, 1, 1, 1, '20130101010111', 1, 'PART_SERIAL_NUMBER_VALUE');
INSERT INTO GALADM.GAL206TBX
(PART_ID, PART_NAME, PART_DESCRIPTION, PART_SERIAL_NUMBER_MASK, ENTRY_TIMESTAMP, MAXIMUM_VALUE1, MINIMUM_VALUE1, MAXIMUM_VALUE2, MINIMUM_VALUE2, MAXIMUM_VALUE3, MINIMUM_VALUE3, MAXIMUM_VALUE4, MINIMUM_VALUE4, MAXIMUM_VALUE5, MINIMUM_VALUE5, MAXIMUM_VALUE6, MINIMUM_VALUE6, MAXIMUM_VALUE7, MINIMUM_VALUE7, MAXIMUM_VALUE8, MINIMUM_VALUE8, MAXIMUM_VALUE9, MINIMUM_VALUE9, MAXIMUM_VALUE10, MINIMUM_VALUE10, MEASUREMENT_COUNT, ALLOW_DUPLICATES, COMMENT) 
VALUES ('TEST', 'PART_NAME', 'PART_DESC', 'PART_SERIAL', '20130101010111', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 'COMMENT_VALUE');
INSERT INTO GALADM.GAL215TBX
(PRODUCT_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP, PRODUCT_SPEC_CODE, PRODUCTION_DATE, PRODUCTION_LOT, PROCESS_COUNT) 
VALUES ('PRODUCT_ID_VALUE', 'PROCESS_POINT', '20130101010111', 'PRODUCT_SPEC', '01/01/2013', 'PRODUCTION_LOT', 1);
INSERT INTO GALADM.GAL222TBX
(REPAIR_ID, PRODUCT_ID, DEFECTRESULTID, REPAIR_ASSOCIATE_NO, ACTUAL_TIMESTAMP, ACTUAL_PROBLEM_NAME, REPAIR_METHOD_NAME, REPAIR_TIME, REPAIR_DEPT, REPAIR_PROCESS_POINT_ID, COMMENT) 
VALUES (0, 'PRODUCT_ID_VALUE', 0, 'REPAIR', '20130101010111', 'ACTUAL_PROBLEM_NAME_VALUE', 'REPAIR_METHOD_NAME_VALUE', 0, 'REPAIR_DEPT_VALUE', 'REPAIR_PROC', 'COMMENT_VALUE');
INSERT INTO GALADM.GAL246TBX
(PROCESS_POINT_ID, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, INT_COLOR_CODE, EXT_COLOR_CODE, PART_NAME, SEQUENCE_NUMBER, EXPECTED_INSTALL_TIME, VERIFICATION_FLAG, SERIAL_NUMBER_SCAN_FLAG, INSTRUCTION_CODE, STRATEGY, SUB_ID, DEVICE_ID, SERIAL_NUMBER_UNIQUE_FLAG) 
VALUES ('PROCESS_POINT', 'Y', 'COD', 'TYP', 'OP', 'IN', 'EXT', 'PART_NAME_VALUE', 0, 0, 0, 0, '00', 'STRATEGY_VALUE', 'S', 'DEVICE_ID', 0);
INSERT INTO GALADM.GAL260TBX
(APPLICATION_ID, SHIFT, PRODUCTION_DATE, FIRST_PRODUCT_ID, LAST_PRODUCT_ID, PRODUCT_ID_INSPECT, PRODUCT_ID_DIRECT_PASSED, PRODUCT_ID_WITH_DEFECTS, REPAIRED_PRODUCT_ID, OUTSTANDING_PRODUCT_ID, SCRAP, AVERAGE_DEFECT_PER_PRODUCT_ID, STRAIGHT_SHIP_PERCENTAGE, ROYAL_STRAIGHT_SHIP_PERCENTAGE, TOP_COAT_PASS_RATE, REPAIR_PASS_RATE, OUTSTANDING_RPU, ACTUAL_TIMESTAMP, PRODUCT_ID_RSSR, PREHEAT) 
VALUES ('APPLICATION_ID', '00', '01/01/2013', 'FIRST_PRODUCT', 'LAST_PRODUCT', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '20130101010111', 0, 0);
INSERT INTO GALADM.GAL263TBX
(VIN, STATUS, ACTUAL_TIMESTAMP, INVOICED, ON_TIME_SHIPPING, APPC70A_EMISSION_FLAG, APPC70A_TIMESTAMP) 
VALUES ('VIN_VALUE', 0, '20130101010111', '0', 0, '0', '20130101010111');
INSERT INTO GALADM.GAL322TBX
(INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, PART_GROUP_NAME, IQS_CATEGORY_NAME, IQS_ITEM_NAME, REGRESSION_CODE, LOCK_MODE, RESPONSIBLE_DEPT, RESPONSIBLE_ZONE, TWO_PART_DEFECT_FLAG, INVENTORY_REPAIR_TIME, ONLINE_REPAIR_TIME, RESPONSIBLE_LINE, ENGINE_FIRING_FLAG, REPAIR_AREA, REPAIR_DEPARTMENT) 
VALUES ('INSPECTION_PART', 'LOCATION', 'DEFECT_TYPE', 'SECONDARY', 'TWO_PART_PAIR', 'PAIR_LOCATION', 'PART_GROUP', 'IQS', 'IQS_ITEM', 'REGRESSION', 0, 'RESP_DEPT', 'RESP_ZONE', 0, 0, 0, 'RESP_LINE', 0, 'REPAIR_AREA', 'REPAIR_DEP');
INSERT INTO GALADM.GAL489TBX
(COMPONENT_ID, PROPERTY_KEY, PROPERTY_VALUE, DESCRIPTION, CHANGE_USER_ID) 
VALUES ('COMPONENT_ID_VALUE', 'PROPERTY_KEY_VALUE', 'PROPERTY_VALUE_VALUE', 'DESCRIPTION_VALUE', 'USER_ID');
INSERT INTO GALADM.GAL650TBX
(DATA_READY_TAG, OPC_INSTANCE_NAME, ENABLED, NEEDS_LISTENER, DEVICE_ID, REPLY_DATA_READY_TAG, SERVER_URL, SERVER_CLIENT_TYPE, SERVER_CLIENT_MODE, LISTENER_CLASS, READ_SOURCE, PROCESS_COMPLETE_TAG) 
VALUES ('DATA_READY', 'OPC', 0, 0, 'DEVICE', 'REPLY', 'SERVER_URL_VALUE', 0, 0, 'LISTENER_CLASS_VALUE', 0, '0');
INSERT INTO GALADM.GTS_PRODUCT_TBX
(TRACKING_AREA, PRODUCT_ID, SHORT_PROD_ID, LOT_NUMBER, KD_LOT_NUMBER, MODEL_YEAR, MODEL_CODE, MODEL_TYPE, MODEL_OPTION, INT_COLOR_CODE, EXT_COLOR_CODE, HOLD_STATUS, DEFECT_STATUS, INSPECTION_STATUS, PRODUCT_SEQ) 
VALUES ('TRACKING', 'PRODUCT_ID_VALUE', 'SHORT_PROD', 'LOT_NUMBER_VALUE', 'KD_LOT', 'Y', 'COD', 'TYP', 'OP', 'IN', 'EXT', 0, 0, 0, 0);
INSERT INTO GALADM.HEAD_BUILD_RESULTS_TBX
(HEAD_ID, PART_NAME, ACTUAL_TIMESTAMP, RESULT_VALUE, INSTALLED_PART_STATUS, ASSOCIATE_NO) 
VALUES ('HEAD_ID_VALUE', 'PART_NAME_VALUE', '20130101010111', 'RESULT_VALUE_VALUE', 0, 'ASSOC');
INSERT INTO GALADM.HEAD_HISTORY_TBX
(HEAD_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP, PROCESS_COUNT) 
VALUES ('HEAD_ID_VALUE', 'PROCESS_POINT', '20130101010111', 0);
INSERT INTO GALADM.HEAD_TBX
(HEAD_ID, MC_SERIAL_NUMBER, DC_SERIAL_NUMBER, ENGINE_SERIAL_NUMBER, MODEL, TRACKING_STATUS, DUNNAGE, DEFECT_STATUS, HOLD_STATUS, ENGINE_FIRING_FLAG, LAST_PASSING_PROCESS_POINT_ID) 
VALUES ('HEAD_ID_VALUE', 'MC_SERIAL', 'DC_SERIAL', 'ENGINE_SERIAL', 'MODEL', 'TRACKING', 'DUNNAGE', 0, 0, 0, 'LAST_PASSING');
INSERT INTO GALADM.HOLD_PARM_TBX
(HOLD_ID, DEPARTMENT, MACHINE_NUMBER, DIE_NUMBER, START_DATE, STOP_DATE, HOLD_REASON, HOLD_ASSOCIATE_ID, HOLD_ASSOCIATE_NAME, ACTUAL_TIMESTAMP, RELEASE_FLAG, RELEASE_ASSOCIATE_ID, RELEASE_ASSOCIATE_NAME, RELEASE_TIMESTAMP, QSR_ID) 
VALUES (0, '00', 'MACH', 'DIE', '01/01/2013', '01/01/2013', 'HOLD_REASON_VALUE', 'HOLD_ASSOC', 'ASSOC_NAME', '20130101010111', 0, 'REL_ASSOC', 'RELEASE_ASSOCIATE_NAME', '20130101010111', 0);
INSERT INTO GALADM.HOST_PRIORITY_PLAN_TBX
(AFAE_FLAG, PLAN_CODE, LINE_NUMBER, PLAN_PROC_LOC, WE_LINE_NUMBER, WE_PLAN_PROC_LOC, PA_LINE_NUMBER, PA_PLAN_PROC_LOC, AFAE_OFF_DATE, PROD_SEQ_NUMBER, DEMAND_TYPE, KD_LOT_NO, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION, EXT_COLOUR_CODE, INT_COLOUR_CODE, NO_OF_UNITS, START_VIN_NUMBER, REMAKE_FLAG, Y_N_FLAG, CARRY_I_O_FLAG, NO_OF_UNITS_CICO, PLAN_CREATED, CREATE_DATE, ROW_PROCESSED) 
VALUES ('0', 'PLAN_CODE', '00', '00', '00', '0', '01', '1', '01/01/2013', '0', 'PP', 'KD_LOT_NO_VALUE', 'Y', 'COD', 'TYP', 'OP', 'EXT', 'IN', 0, 'START_VIN', '0', 'N', '0', 0, 'N', '01/01/2013', '0');
INSERT INTO GALADM.NOTIFICATION_PROVIDER_TBX
(NOTIFICATION_CLASS, HOST_IP, HOST_PORT, HOST_NAME, DESCRIPTION) 
VALUES ('IPropertyNotification', 'HOST_IP_VALUE', 0, 'HOST_NAME_VALUE', 'DESCRIPTION_VALUE');
INSERT INTO GALADM.NOTIFICATION_SUBSCRIBER_TBX
(NOTIFICATION_CLASS, CLIENT_NAME, CLIENT_IP, CLIENT_PORT) 
VALUES ('IPropertyNotification', 'CLIENT_NAME_VALUE', 'CLIENT_IP_VALUE', 0);
INSERT INTO GALADM.PART_LOT_TBX
(PART_SERIAL_NUMBER, PART_NUMBER, PART_NAME, STATUS, STARTING_QUANTITY, CURRENT_QUANTITY, COMMENT) 
VALUES ('PART_SERIAL', 'PART_NUMBER', 'PART_NAME', 0, 0, 0, 'COMMENT_VALUE');
INSERT INTO GALADM.PART_SPEC_TBX
(PART_NAME, PART_ID, PART_DESCRIPTION, PART_SERIAL_NUMBER_MASK, PART_MAX_ATTEMPTS, MEASUREMENT_COUNT, ENTRY_TIMESTAMP, COMMENT) 
VALUES ('PART_NAME', 'ID', 'PART_DESCRIPTION_VALUE', 'MASK_VALUE', 0, 0, '20130101010111', 'COMMENT_VALUE');
INSERT INTO GALADM.PRODUCT_SEQUENCE_TBX
(PRODUCT_ID, PROCESS_POINT_ID, REFERENCE_TIMESTAMP, ASSOCIATE_NO) 
VALUES ('PRODUCT_ID_VALUE', 'PROCESS_POINT', '20130101010111', 'ASSOC');
INSERT INTO GALADM.PRODUCT_SPEC_CODE_TBX
(PRODUCT_SPEC_CODE, PRODUCT_TYPE, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EXT_COLOR_CODE, INT_COLOR_CODE, MODEL_YEAR_DESCRIPTION) 
VALUES ('PRODUCT_SPEC', 'TYPE', 'Y', 'COD', 'TYP', 'OP', 'EXT', 'IN', 'DESC');
INSERT INTO GALADM.QUORUM_DETAIL_TBX
(QUORUM_DATE, QUORUM_ID, QUORUM_SEQ, KD_LOT, YMTO, ENGINE_NUMBER, STATUS) 
VALUES ('01/01/2013', 0, 0, 'KD_LOT_VALUE', 'YMTO', 'ENGINE_NUM', 0);
INSERT INTO GALADM.QUORUM_TBX
(QUORUM_DATE, QUORUM_ID, TRAILER_ID, TRAILER_ROW, PALLET_TYPE, QUORUM_SIZE, STATUS) 
VALUES ('01/01/2013', 0, 0, 0, 'PAL', 0, 0);
INSERT INTO GALADM.REQUIRED_PARTS_TBX
(PROCESS_POINT_ID, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, INT_COLOR_CODE, EXT_COLOR_CODE, PART_NAME, SUB_ID) 
VALUES ('PROCESS_POINT', 'Y', 'COD', 'TYP', 'OP', 'IN', 'EXT', 'PART_NAME', 'ID');
INSERT INTO GALADM.SKIPPED_PRODUCT_TBX
(PRODUCT_ID, PROCESS_POINT_ID, SUB_ID, PRODUCT_TYPE, KD_LOT_NUMBER, PRODUCTION_LOT, PRODUCT_SPEC_CODE, STATUS, SKIP_TIMESTAMP, DISABLE_TIMESTAMP) 
VALUES ('PRODUCT_ID_VALUE', 'PROCESS_POINT', 'ID', 'TYPE', 'KD_LOT', 'PRODUCTION_LOT', 'PRODUCT_SPEC', 0, '20130101010111', '20130101010111');
INSERT INTO GALADM.STANDARD_SCHEDULE_TBX
(PLANT_CODE, LINE_NO, PROCESS_LOCATION, DAY_OF_WEEK, SHIFT, PERIOD, PERIOD_LABEL, TYPE, "PLAN", START_TIME, END_TIME, NEXT_DAY, CAPACITY, CAPACITY_ON) 
VALUES ('0', '00', '00', '0', '00', 0, 'PER', 'TYP', '0', '01/01/2013', '01/01/2013', 0, 0, 0);
INSERT INTO GALADM.TRAILER_INFO_TBX
(TRAILER_ID, TRAILER_NUMBER, SCH_QTY, ACT_QTY, STATUS) 
VALUES (0, 'TRAILER', 0, 0, 0);
INSERT INTO GALADM.TRAILER_STATUS_TBX
(TRAILER_ID, STATUS) 
VALUES (0, 0);
INSERT INTO GALADM.VANNING_SCHEDULE_TBX
(PRODUCTION_DATE, VANNING_SEQ, TRAILER_ID, KD_LOT, PRODUCTION_LOT, YMTO, SCH_QTY, ACT_QTY) 
VALUES ('01/01/2013', 0, 0, 'KD_LOT_VALUE', 'PRODUCTION_LOT', 'YMTO', 0, 0);



-------------------------Select to confirm data inserted and replicated in each database


SELECT BLOCK_ID, PART_NAME, ACTUAL_TIMESTAMP, RESULT_VALUE, INSTALLED_PART_STATUS, ASSOCIATE_NO, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.BLOCK_BUILD_RESULTS_TBX
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
SELECT BLOCK_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, PROCESS_COUNT 
FROM GALADM.BLOCK_HISTORY_TBX
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
SELECT MC_NUMBER, PRODUCTION_LOT, LOT_SIZE, PRODUCT_SPEC_CODE, REFERENCE_NUMBER, STATUS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.BLOCK_LOAD_TBX
WHERE MC_NUMBER = 'MC_NUMBER_VALUE';
SELECT BLOCK_ID, MC_SERIAL_NUMBER, DC_SERIAL_NUMBER, ENGINE_SERIAL_NUMBER, MODEL, TRACKING_STATUS, DUNNAGE, DEFECT_STATUS, HOLD_STATUS, LAST_PASSING_PROCESS_POINT_ID, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.BLOCK_TBX
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
SELECT INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECTRESULTID, APPLICATION_ID, PRODUCT_ID, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, ASSOCIATE_NO, SHIFT, DATE, ACTUAL_TIMESTAMP, DEFECT_STATUS, IMAGE_NAME, RESPONSIBLE_DEPT, RESPONSIBLE_ZONE, REPAIR_METHOD_NAME_PLAN, REPAIR_TIME_PLAN, REPAIR_ASSOCIATE_NO_PLAN, REPAIR_ASSOCIATE_NO, WRITE_UP_DEPARTMENT, TWO_PART_DEFECT_FLAG, IQS_CATEGORY_NAME, IQS_ITEM_NAME, REGRESSION_CODE, POINT_X, POINT_Y, ENTRY_DEPT, OUTSTANDING_FLAG, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, REPAIR_TIMESTAMP, RESPONSIBLE_LINE, GDP_DEFECT, PART_GROUP_NAME 
FROM GALADM.GAL125TBX
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
SELECT ID, AUDIT_TIMESTAMP, ACTION_TYPE, INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECTRESULTID, APPLICATION_ID, PRODUCT_ID, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, OLD_ASSOCIATE_NO, OLD_SHIFT, OLD_DATE, OLD_ACTUAL_TIMESTAMP, OLD_DEFECT_STATUS, OLD_IMAGE_NAME, OLD_RESPONSIBLE_DEPT, OLD_RESPONSIBLE_ZONE, OLD_REPAIR_METHOD_NAME_PLAN, OLD_REPAIR_TIME_PLAN, OLD_REPAIR_ASSOCIATE_NO_PLAN, OLD_REPAIR_ASSOCIATE_NO, OLD_WRITE_UP_DEPARTMENT, OLD_TWO_PART_DEFECT_FLAG, OLD_IQS_CATEGORY_NAME, OLD_IQS_ITEM_NAME, OLD_REGRESSION_CODE, OLD_POINT_X, OLD_POINT_Y, OLD_ENTRY_DEPT, OLD_OUTSTANDING_FLAG, OLD_REPAIR_TIMESTAMP, OLD_RESPONSIBLE_LINE, NEW_ASSOCIATE_NO, NEW_SHIFT, NEW_DATE, NEW_ACTUAL_TIMESTAMP, NEW_DEFECT_STATUS, NEW_IMAGE_NAME, NEW_RESPONSIBLE_DEPT, NEW_RESPONSIBLE_ZONE, NEW_REPAIR_METHOD_NAME_PLAN, NEW_REPAIR_TIME_PLAN, NEW_REPAIR_ASSOCIATE_NO_PLAN, NEW_REPAIR_ASSOCIATE_NO, NEW_WRITE_UP_DEPARTMENT, NEW_TWO_PART_DEFECT_FLAG, NEW_IQS_CATEGORY_NAME, NEW_IQS_ITEM_NAME, NEW_REGRESSION_CODE, NEW_POINT_X, NEW_POINT_Y, NEW_ENTRY_DEPT, NEW_OUTSTANDING_FLAG, NEW_REPAIR_TIMESTAMP, NEW_RESPONSIBLE_LINE, USER_NAME, CHANGE_NUMBER, CHANGE_DESCRIPTION, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, OLD_GDP_DEFECT, NEW_GDP_DEFECT 
FROM GALADM.GAL125TBX_AUD
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
SELECT PRODUCT_ID, VIN, MISSION_SERIAL_NO, ENGINE_FIRING_FLAG, PRODUCTION_LOT, KD_LOT_NUMBER, PRODUCT_SPEC_CODE, PLAN_OFF_DATE, TRACKING_STATUS, PRODUCTION_DATE, PRODUCT_START_DATE, ACTUAL_OFF_DATE, AUTO_HOLD_STATUS, LAST_PASSING_PROCESS_POINT_ID, MISSION_STATUS, FIRING_TYPE, REPAIR_FLAG, ACTUAL_MISSION_TYPE, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, PLANT_CODE, DEFECT_STATUS 
FROM GALADM.GAL131TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PRODUCT_ID, ACTUAL_TIMESTAMP, ASSOCIATE_NO, EXCEPTIONAL_OUT_COMMENT, EXCEPTIONAL_OUT_REASON_STRING, PRODUCTION_DATE, PROCESS_POINT_ID, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, LOCATION 
FROM GALADM.GAL136TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PRODUCT_ID, ACTUAL_TIMESTAMP, HOLD_TYPE, RELEASE_TIMESTAMP, RELEASE_FLAG, HOLD_ASSOCIATE_NO, HOLD_ASSOCIATE_NAME, HOLD_ASSOCIATE_PHONE, HOLD_ASSOCIATE_PAGER, HOLD_REASON, RELEASE_ASSOCIATE_NO, RELEASE_ASSOCIATE_NAME, RELEASE_ASSOCIATE_PHONE, RELEASE_ASSOCIATE_PAGER, RELEASE_REASON, LOT_HOLD_STATUS, PRODUCTION_LOT, PRODUCT_SPEC_CODE, PRODUCTION_DATE, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, QSR_ID 
FROM GALADM.GAL147TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT REPAIR_AREA_NAME, PRODUCT_ID, PARKING_LOCATION, ACTUAL_TIMESTAMP, REJECTION, RESPONSIBLE_DEPT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.GAL177TBX
WHERE REPAIR_AREA_NAME='REPAIR_AREA';
select * from GALADM.GAL198TBX where PRODUCT_ID='TEST';
select * from GALADM.HMIN_MEASUREMENT_ATTEMPTTBX where PRODUCT_ID='TEST';
SELECT PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_ATTEMPT, MEASUREMENT_VALUE, MEASUREMENT_STATUS, ACTUAL_TIMESTAMP, MEASUREMENT_ANGLE, PART_SERIAL_NUMBER, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.GAL198_HIST_TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PART_ID, PART_NAME, PART_DESCRIPTION, PART_SERIAL_NUMBER_MASK, ENTRY_TIMESTAMP, MAXIMUM_VALUE1, MINIMUM_VALUE1, MAXIMUM_VALUE2, MINIMUM_VALUE2, MAXIMUM_VALUE3, MINIMUM_VALUE3, MAXIMUM_VALUE4, MINIMUM_VALUE4, MAXIMUM_VALUE5, MINIMUM_VALUE5, MAXIMUM_VALUE6, MINIMUM_VALUE6, MAXIMUM_VALUE7, MINIMUM_VALUE7, MAXIMUM_VALUE8, MINIMUM_VALUE8, MAXIMUM_VALUE9, MINIMUM_VALUE9, MAXIMUM_VALUE10, MINIMUM_VALUE10, MEASUREMENT_COUNT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, ALLOW_DUPLICATES, COMMENT 
FROM GALADM.GAL206TBX
WHERE PART_ID='TEST';
SELECT *
FROM GALADM.GAL215TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT REPAIR_ID, PRODUCT_ID, DEFECTRESULTID, REPAIR_ASSOCIATE_NO, ACTUAL_TIMESTAMP, ACTUAL_PROBLEM_NAME, REPAIR_METHOD_NAME, REPAIR_TIME, REPAIR_DEPT, REPAIR_PROCESS_POINT_ID, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, COMMENT 
FROM GALADM.GAL222TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PROCESS_POINT_ID, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, INT_COLOR_CODE, EXT_COLOR_CODE, PART_NAME, SEQUENCE_NUMBER, EXPECTED_INSTALL_TIME, VERIFICATION_FLAG, SERIAL_NUMBER_SCAN_FLAG, INSTRUCTION_CODE, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, STRATEGY, SUB_ID, DEVICE_ID, SERIAL_NUMBER_UNIQUE_FLAG 
FROM GALADM.GAL246TBX
WHERE PROCESS_POINT_ID='PROCESS_POINT';
SELECT APPLICATION_ID, SHIFT, PRODUCTION_DATE, FIRST_PRODUCT_ID, LAST_PRODUCT_ID, PRODUCT_ID_INSPECT, PRODUCT_ID_DIRECT_PASSED, PRODUCT_ID_WITH_DEFECTS, REPAIRED_PRODUCT_ID, OUTSTANDING_PRODUCT_ID, SCRAP, AVERAGE_DEFECT_PER_PRODUCT_ID, STRAIGHT_SHIP_PERCENTAGE, ROYAL_STRAIGHT_SHIP_PERCENTAGE, TOP_COAT_PASS_RATE, REPAIR_PASS_RATE, OUTSTANDING_RPU, ACTUAL_TIMESTAMP, PRODUCT_ID_RSSR, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, PREHEAT 
FROM GALADM.GAL260TBX
WHERE APPLICATION_ID='APPLICATION_ID';
SELECT VIN, STATUS, ACTUAL_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, INVOICED, ON_TIME_SHIPPING, APPC70A_EMISSION_FLAG, APPC70A_TIMESTAMP 
FROM GALADM.GAL263TBX
WHERE VIN='VIN_VALUE';
SELECT INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME, SECONDARY_PART_NAME, TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, PART_GROUP_NAME, IQS_CATEGORY_NAME, IQS_ITEM_NAME, REGRESSION_CODE, LOCK_MODE, RESPONSIBLE_DEPT, RESPONSIBLE_ZONE, TWO_PART_DEFECT_FLAG, INVENTORY_REPAIR_TIME, ONLINE_REPAIR_TIME, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, RESPONSIBLE_LINE, ENGINE_FIRING_FLAG, REPAIR_AREA, REPAIR_DEPARTMENT 
FROM GALADM.GAL322TBX
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
SELECT COMPONENT_ID, PROPERTY_KEY, PROPERTY_VALUE, DESCRIPTION, CHANGE_USER_ID, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.GAL489TBX
WHERE COMPONENT_ID='COMPONENT_ID_VALUE' AND PROPERTY_KEY = 'PROPERTY_KEY_VALUE';
SELECT ID, DATA_READY_TAG, OPC_INSTANCE_NAME, ENABLED, NEEDS_LISTENER, DEVICE_ID, REPLY_DATA_READY_TAG, SERVER_URL, SERVER_CLIENT_TYPE, SERVER_CLIENT_MODE, LISTENER_CLASS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, READ_SOURCE, PROCESS_COMPLETE_TAG 
FROM GALADM.GAL650TBX
WHERE DATA_READY_TAG='DATA_READY';
SELECT TRACKING_AREA, PRODUCT_ID, SHORT_PROD_ID, LOT_NUMBER, KD_LOT_NUMBER, MODEL_YEAR, MODEL_CODE, MODEL_TYPE, MODEL_OPTION, INT_COLOR_CODE, EXT_COLOR_CODE, HOLD_STATUS, DEFECT_STATUS, INSPECTION_STATUS, PRODUCT_SEQ, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.GTS_PRODUCT_TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT HEAD_ID, PART_NAME, ACTUAL_TIMESTAMP, RESULT_VALUE, INSTALLED_PART_STATUS, ASSOCIATE_NO, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.HEAD_BUILD_RESULTS_TBX
WHERE HEAD_ID='HEAD_ID_VALUE';
SELECT HEAD_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, PROCESS_COUNT 
FROM GALADM.HEAD_HISTORY_TBX
WHERE HEAD_ID='HEAD_ID_VALUE';
SELECT HEAD_ID, MC_SERIAL_NUMBER, DC_SERIAL_NUMBER, ENGINE_SERIAL_NUMBER, MODEL, TRACKING_STATUS, DUNNAGE, DEFECT_STATUS, HOLD_STATUS, ENGINE_FIRING_FLAG, LAST_PASSING_PROCESS_POINT_ID, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.HEAD_TBX
WHERE HEAD_ID='HEAD_ID_VALUE';
SELECT HOLD_ID, DEPARTMENT, MACHINE_NUMBER, DIE_NUMBER, START_DATE, STOP_DATE, HOLD_REASON, HOLD_ASSOCIATE_ID, HOLD_ASSOCIATE_NAME, ACTUAL_TIMESTAMP, RELEASE_FLAG, RELEASE_ASSOCIATE_ID, RELEASE_ASSOCIATE_NAME, RELEASE_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, QSR_ID 
FROM GALADM.HOLD_PARM_TBX
WHERE HOLD_ID=0;
SELECT AFAE_FLAG, PLAN_CODE, LINE_NUMBER, PLAN_PROC_LOC, WE_LINE_NUMBER, WE_PLAN_PROC_LOC, PA_LINE_NUMBER, PA_PLAN_PROC_LOC, AFAE_OFF_DATE, PROD_SEQ_NUMBER, DEMAND_TYPE, KD_LOT_NO, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION, EXT_COLOUR_CODE, INT_COLOUR_CODE, NO_OF_UNITS, START_VIN_NUMBER, REMAKE_FLAG, Y_N_FLAG, CARRY_I_O_FLAG, NO_OF_UNITS_CICO, PLAN_CREATED, CREATE_DATE, ROW_PROCESSED, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.HOST_PRIORITY_PLAN_TBX
WHERE PLAN_CODE='PLAN_CODE';
SELECT NOTIFICATION_CLASS, HOST_IP, HOST_PORT, HOST_NAME, DESCRIPTION, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.NOTIFICATION_PROVIDER_TBX
WHERE HOST_IP='HOST_IP_VALUE';
SELECT NOTIFICATION_CLASS, CLIENT_NAME, CLIENT_IP, CLIENT_PORT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.NOTIFICATION_SUBSCRIBER_TBX
WHERE CLIENT_NAME='CLIENT_NAME_VALUE';
SELECT PART_SERIAL_NUMBER, PART_NUMBER, PART_NAME, STATUS, STARTING_QUANTITY, CURRENT_QUANTITY, COMMENT, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.PART_LOT_TBX
WHERE PART_SERIAL_NUMBER='PART_SERIAL';
SELECT PART_NAME, PART_ID, PART_DESCRIPTION, PART_SERIAL_NUMBER_MASK, PART_MAX_ATTEMPTS, MEASUREMENT_COUNT, ENTRY_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, COMMENT 
FROM GALADM.PART_SPEC_TBX
WHERE PART_NAME='PART_NAME';
SELECT PRODUCT_ID, PROCESS_POINT_ID, REFERENCE_TIMESTAMP, ASSOCIATE_NO, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.PRODUCT_SEQUENCE_TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PRODUCT_SPEC_CODE, PRODUCT_TYPE, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EXT_COLOR_CODE, INT_COLOR_CODE, MODEL_YEAR_DESCRIPTION, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.PRODUCT_SPEC_CODE_TBX
WHERE PRODUCT_SPEC_CODE='PRODUCT_SPEC';
SELECT QUORUM_DATE, QUORUM_ID, QUORUM_SEQ, KD_LOT, YMTO, ENGINE_NUMBER, STATUS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.QUORUM_DETAIL_TBX
WHERE QUORUM_ID=0;
SELECT QUORUM_DATE, QUORUM_ID, TRAILER_ID, TRAILER_ROW, PALLET_TYPE, QUORUM_SIZE, STATUS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.QUORUM_TBX
WHERE QUORUM_ID=0;
SELECT PROCESS_POINT_ID, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, INT_COLOR_CODE, EXT_COLOR_CODE, PART_NAME, CREATE_TIMESTAMP, UPDATE_TIMESTAMP, SUB_ID 
FROM GALADM.REQUIRED_PARTS_TBX
WHERE PROCESS_POINT_ID='PROCESS_POINT';
SELECT PRODUCT_ID, PROCESS_POINT_ID, SUB_ID, PRODUCT_TYPE, KD_LOT_NUMBER, PRODUCTION_LOT, PRODUCT_SPEC_CODE, STATUS, SKIP_TIMESTAMP, DISABLE_TIMESTAMP, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.SKIPPED_PRODUCT_TBX
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
SELECT PLANT_CODE, LINE_NO, PROCESS_LOCATION, DAY_OF_WEEK, SHIFT, PERIOD, PERIOD_LABEL, TYPE, "PLAN", START_TIME, END_TIME, NEXT_DAY, CAPACITY, CAPACITY_ON, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.STANDARD_SCHEDULE_TBX
WHERE PLANT_CODE='0';
SELECT TRAILER_ID, TRAILER_NUMBER, SCH_QTY, ACT_QTY, STATUS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.TRAILER_INFO_TBX
WHERE TRAILER_ID=0;
SELECT TRAILER_ID, STATUS, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.TRAILER_STATUS_TBX
WHERE TRAILER_ID=0;
SELECT PRODUCTION_DATE, VANNING_SEQ, TRAILER_ID, KD_LOT, PRODUCTION_LOT, YMTO, SCH_QTY, ACT_QTY, CREATE_TIMESTAMP, UPDATE_TIMESTAMP 
FROM GALADM.VANNING_SCHEDULE_TBX
WHERE TRAILER_ID=0;


-----------------------------Delete test records out of Production Database

DELETE FROM GALADM.BLOCK_BUILD_RESULTS_TBX 
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
DELETE FROM GALADM.BLOCK_HISTORY_TBX 
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
DELETE FROM GALADM.BLOCK_LOAD_TBX 
WHERE MC_NUMBER = 'MC_NUMBER_VALUE';
DELETE FROM GALADM.BLOCK_TBX 
WHERE BLOCK_ID = 'BLOCK_ID_VALUE';
DELETE FROM GALADM.GAL125TBX 
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
DELETE FROM GALADM.GAL125TBX_AUD 
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
DELETE FROM GALADM.GAL131TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL136TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL147TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL177TBX 
WHERE REPAIR_AREA_NAME='REPAIR_AREA';
DELETE FROM GALADM.GAL198TBX WHERE PRODUCT_ID = 'TEST';
DELETE FROM GALADM.HMIN_MEASUREMENT_ATTEMPTTBX WHERE PRODUCT_ID = 'TEST';
DELETE FROM GALADM.GAL198_HIST_TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL206TBX 
WHERE PART_ID='TEST';
DELETE FROM GALADM.GAL215TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL222TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.GAL246TBX 
WHERE PROCESS_POINT_ID='PROCESS_POINT';
DELETE FROM GALADM.GAL260TBX 
WHERE APPLICATION_ID='APPLICATION_ID';
DELETE FROM GALADM.GAL263TBX 
WHERE VIN='VIN_VALUE';
DELETE FROM GALADM.GAL322TBX 
WHERE INSPECTION_PART_NAME='INSPECTION_PART';
DELETE FROM GALADM.GAL489TBX 
WHERE COMPONENT_ID='COMPONENT_ID_VALUE' AND PROPERTY_KEY = 'PROPERTY_KEY_VALUE';
DELETE FROM GALADM.GAL650TBX 
WHERE DATA_READY_TAG='DATA_READY';
DELETE FROM GALADM.GTS_PRODUCT_TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.HEAD_BUILD_RESULTS_TBX 
WHERE HEAD_ID='HEAD_ID_VALUE';
DELETE FROM GALADM.HEAD_HISTORY_TBX 
WHERE HEAD_ID='HEAD_ID_VALUE';
DELETE FROM GALADM.HEAD_TBX 
WHERE HEAD_ID='HEAD_ID_VALUE';
DELETE FROM GALADM.HOLD_PARM_TBX 
WHERE HOLD_ID=0;
DELETE FROM GALADM.HOST_PRIORITY_PLAN_TBX 
WHERE PLAN_CODE='PLAN_CODE';
DELETE FROM GALADM.NOTIFICATION_PROVIDER_TBX 
WHERE HOST_IP='HOST_IP_VALUE';
DELETE FROM GALADM.NOTIFICATION_SUBSCRIBER_TBX 
WHERE CLIENT_NAME='CLIENT_NAME_VALUE';
DELETE FROM GALADM.PART_LOT_TBX 
WHERE PART_SERIAL_NUMBER='PART_SERIAL';
DELETE FROM GALADM.PART_SPEC_TBX 
WHERE PART_NAME='PART_NAME';
DELETE FROM GALADM.PRODUCT_SEQUENCE_TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.PRODUCT_SPEC_CODE_TBX 
WHERE PRODUCT_SPEC_CODE='PRODUCT_SPEC';
DELETE FROM GALADM.QUORUM_DETAIL_TBX 
WHERE QUORUM_ID=0;
DELETE FROM GALADM.QUORUM_TBX 
WHERE QUORUM_ID=0;
DELETE FROM GALADM.REQUIRED_PARTS_TBX 
WHERE PROCESS_POINT_ID='PROCESS_POINT';
DELETE FROM GALADM.SKIPPED_PRODUCT_TBX 
WHERE PRODUCT_ID='PRODUCT_ID_VALUE';
DELETE FROM GALADM.STANDARD_SCHEDULE_TBX 
WHERE PLANT_CODE='0';
DELETE FROM GALADM.TRAILER_INFO_TBX 
WHERE TRAILER_ID=0;
DELETE FROM GALADM.TRAILER_STATUS_TBX 
WHERE TRAILER_ID=0;
DELETE FROM GALADM.VANNING_SCHEDULE_TBX 
WHERE TRAILER_ID=0;
