--This script is to convert HMIN GALC DB over to the initial version of the REGIONAL CODE BASE


ALTER TABLE GALADM.GAL125TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL125TBX
  ADD COLUMN PART_GROUP_NAME CHARACTER(20);

ALTER TABLE GALADM.GAL125TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL125TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL125TBX;

DROP TRIGGER GALADM.GAL125TR2;
DROP TRIGGER GALADM.GAL125TR1;

CREATE TRIGGER GALADM.GAL125_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL125TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL125_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL125TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL125TBX_AUD
  ADD COLUMN OLD_PART_GROUP_NAME CHARACTER(20)
  ADD COLUMN NEW_PART_GROUP_NAME CHARACTER(20);

ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL125TBX_AUD;
REORG INDEXES ALL FOR TABLE GALADM.GAL125TBX_AUD;

DROP TRIGGER GALADM.GAL125AUDTR2;
DROP TRIGGER GALADM.GAL125AUDTR1;

CREATE TRIGGER GALADM.GAL125AUDTR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL125TBX_AUD
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL125AUDTR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL125TBX_AUD
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL131TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL131TBX
  ADD COLUMN DEFECT_STATUS SMALLINT;

ALTER TABLE GALADM.GAL131TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL131TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL131TBX;

DROP TRIGGER GALADM.GAL131TR2;
DROP TRIGGER GALADM.GAL131TR1;

CREATE TRIGGER GALADM.GAL131_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL131_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL136TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL136TBX
  ADD COLUMN LOCATION VARCHAR(20);

ALTER TABLE GALADM.GAL136TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL136TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL136TBX;

DROP TRIGGER GALADM.GAL136TR2;
DROP TRIGGER GALADM.GAL136TR1;

CREATE TRIGGER GALADM.GAL136_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL136TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL136_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL136TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL144TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL144TBX
  ALTER COLUMN BOUNDARY_MARK_REQUIRED
    SET DEFAULT '';

ALTER TABLE GALADM.GAL144TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL144TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL144TBX;

DROP TRIGGER GALADM.GAL144TR2;
DROP TRIGGER GALADM.GAL144TR1;

CREATE TRIGGER GALADM.GAL144_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL144TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL144_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL144TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL147TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL147TBX
  ADD COLUMN QSR_ID INTEGER;

ALTER TABLE GALADM.GAL147TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL147TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL147TBX;

DROP TRIGGER GALADM.GAL147TR2;
DROP TRIGGER GALADM.GAL147TR1;

CREATE TRIGGER GALADM.GAL147_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL147TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL147_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL147TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL177TBX
   DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL177TBX
   ALTER COLUMN RESPONSIBLE_DEPT
     SET DATA TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL177TBX
   DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL177TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL177TBX;

DROP TRIGGER GALADM.GAL177TR2;
DROP TRIGGER GALADM.GAL177TR1;

CREATE TRIGGER GALADM.GAL177_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL177TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL177_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL177TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL198TBX
    DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL198TBX
    ALTER COLUMN PART_SERIAL_NUMBER
      SET DATA TYPE VARCHAR(255);

ALTER TABLE GALADM.GAL198TBX
    DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL198TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL198TBX;

DROP TRIGGER GALADM.GAL198TR2;
DROP TRIGGER GALADM.GAL198TR1;

CREATE TRIGGER GALADM.GAL198_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL206TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL206TBX
  ADD COLUMN ALLOW_DUPLICATES INTEGER NOT NULL DEFAULT 0
  ADD COLUMN COMMENT VARCHAR(256);

ALTER TABLE GALADM.GAL206TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL206TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL206TBX;

DROP TRIGGER GALADM.GAL206TR2;
DROP TRIGGER GALADM.GAL206TR1;

CREATE TRIGGER GALADM.GAL206_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL206TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL206_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL206TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL215TBX
  ALTER COLUMN PRODUCT_SPEC_CODE  
    SET DATA TYPE CHARACTER(30)
  ADD COLUMN PROCESS_COUNT INTEGER;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL215TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL215TBX;

DROP TRIGGER GALADM.GAL215TR2;
DROP TRIGGER GALADM.GAL215TR1;

CREATE TRIGGER GALADM.GAL215_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL215_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL222TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL222TBX
 ALTER COLUMN COMMENT
   SET DATA TYPE VARCHAR(256)
 ALTER COLUMN REPAIR_DEPT
   SET DATA TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL222TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL222TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL222TBX;

DROP TRIGGER GALADM.GAL222TR2;
DROP TRIGGER GALADM.GAL222TR1;

CREATE TRIGGER GALADM.GAL222_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL222TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL222_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL222TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL246TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL246TBX
 ALTER COLUMN INSTRUCTION_CODE
   SET DATA TYPE CHARACTER(2);

ALTER TABLE GALADM.GAL246TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL246TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL246TBX;

DROP TRIGGER GALADM.GAL246TR4;
DROP TRIGGER GALADM.GAL246TR3;
DROP TRIGGER GALADM.GAL246TR2;
DROP TRIGGER GALADM.GAL246TR1;

CREATE TRIGGER GALADM.GAL246_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL246TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL246_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL246TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL246_TR3
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL246TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET SERIAL_NUMBER_UNIQUE_FLAG=VERIFICATION_FLAG;

CREATE TRIGGER GALADM.GAL246_TR4
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL246TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET SERIAL_NUMBER_UNIQUE_FLAG=VERIFICATION_FLAG;

ALTER TABLE GALADM.GAL260TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL260TBX
  ADD COLUMN PREHEAT INTEGER;

ALTER TABLE GALADM.GAL260TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL260TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL260TBX;

DROP TRIGGER GALADM.GAL260TR2;
DROP TRIGGER GALADM.GAL260TR1;

CREATE TRIGGER GALADM.GAL260_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL260TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL260_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL260TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;


ALTER TABLE GALADM.GAL263TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL263TBX
  ADD COLUMN APPC70A_EMISSION_FLAG CHARACTER(1)
  ADD COLUMN APPC70A_TIMESTAMP TIMESTAMP;

ALTER TABLE GALADM.GAL263TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL263TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL263TBX;

DROP TRIGGER GALADM.GAL263TR2;
DROP TRIGGER GALADM.GAL263TR1;

CREATE TRIGGER GALADM.GAL263_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL263TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL263_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL263TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL322TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL322TBX
  ADD COLUMN REPAIR_AREA CHARACTER(20)
  ADD COLUMN REPAIR_DEPARTMENT CHARACTER(32);

ALTER TABLE GALADM.GAL322TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL322TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL322TBX;

DROP TRIGGER GALADM.GAL322TR2;
DROP TRIGGER GALADM.GAL322TR1;

CREATE TRIGGER GALADM.GAL322_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL322TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL322_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL322TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL489TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL489TBX
 ALTER COLUMN PROPERTY_KEY
   SET DATA TYPE VARCHAR(64)
 ALTER COLUMN PROPERTY_VALUE
   SET DATA TYPE VARCHAR(1024);

ALTER TABLE GALADM.GAL489TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL489TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL489TBX;

DROP TRIGGER GALADM.GAL489TR2;
DROP TRIGGER GALADM.GAL489TR1;

CREATE TRIGGER GALADM.GAL489_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL489_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL650TBX
  ALTER COLUMN DATA_READY_TAG
    SET NOT NULL
  ALTER COLUMN NEEDS_LISTENER
    SET NOT NULL
  ADD COLUMN PROCESS_COMPLETE_TAG VARCHAR(128);

ALTER TABLE GALADM.GAL650TBX
  ALTER COLUMN NEEDS_LISTENER
    SET DEFAULT 0;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL650TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL650TBX;

DROP TRIGGER GALADM.GAL650TR2;
DROP TRIGGER GALADM.GAL650TR1;

CREATE TRIGGER GALADM.GAL650_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL650TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL650_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL650TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  ALTER COLUMN HOST_IP
    SET DATA TYPE VARCHAR (255)
  ALTER COLUMN HOST_PORT
    SET DATA TYPE INTEGER
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_PROVIDER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_PROVIDER_TBX;

DROP TRIGGER GALADM.NOTIF_PRO_TR2;
DROP TRIGGER GALADM.NOTIF_PRO_TR1;

CREATE TRIGGER GALADM.NOTIF_PRO_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIF_PRO_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  ALTER COLUMN CLIENT_IP
    SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX;

DROP TRIGGER GALADM.NOTIF_SUB_TR2;
DROP TRIGGER GALADM.NOTIF_SUB_TR1;

CREATE TRIGGER GALADM.NOTIF_SUB_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_SUBSCRIBER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIF_SUB_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_SUBSCRIBER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.NOTIFICATION_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_TBX
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_TBX;

DROP TRIGGER GALADM.NOTIFICATION_TR2;
DROP TRIGGER GALADM.NOTIFICATION_TR1;

CREATE TRIGGER GALADM.NOTIFICATION_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIFICATION_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.WSBUILDS_TBX FOR GALADM.HNA_WSBUILDS_TBX;

CREATE ALIAS GALADM.WSCLIENTS_TBX FOR GALADM.HNA_WSCLIENTS_TBX;

CREATE ALIAS GALADM.WSDEFBUILDS_TBX FOR GALADM.HNA_WSDEFBUILDS_TBX;

