CREATE TABLE "GALADM"."PLAN_STATUS_TBX" (
  PLAN_STATUS_ID	INTEGER	NOT NULL,
  PLAN_STATUS_NAME	CHARACTER(20),
  PLAN_STATUS_DESC	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."PLAN_STATUS_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PLAN_STATUS_TBX" IS 'Plan Status';

ALTER TABLE "GALADM"."PLAN_STATUS_TBX" ADD CONSTRAINT "PLAN_STATUS_PK" PRIMARY KEY
 ("PLAN_STATUS_ID");

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."PLAN_STATUS_TBX" TO GROUP "GALQPR_A";

GRANT SELECT ON TABLE "GALADM"."PLAN_STATUS_TBX" TO GROUP "GALQPR_S";

COMMIT;
