--This script is to convert HMIN GALC DB over to the initial version of the REGIONAL CODE BASE


ALTER TABLE GALADM.GAL125TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL125TBX
  ADD COLUMN PART_GROUP_NAME CHARACTER(20);

ALTER TABLE GALADM.GAL125TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL125TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL125TBX;

ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL125TBX_AUD
  ADD COLUMN OLD_PART_GROUP_NAME CHARACTER(20)
  ADD COLUMN NEW_PART_GROUP_NAME CHARACTER(20);

ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL125TBX_AUD;
REORG INDEXES ALL FOR TABLE GALADM.GAL125TBX_AUD;

ALTER TABLE GALADM.GAL131TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL131TBX
  ADD COLUMN DEFECT_STATUS SMALLINT;

ALTER TABLE GALADM.GAL131TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL131TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL131TBX;

ALTER TABLE GALADM.GAL136TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL136TBX
  ADD COLUMN LOCATION VARCHAR(20);

ALTER TABLE GALADM.GAL136TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL136TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL136TBX;

ALTER TABLE GALADM.GAL144TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL144TBX
  ALTER COLUMN BOUNDARY_MARK_REQUIRED
    SET DEFAULT '';

ALTER TABLE GALADM.GAL144TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL144TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL144TBX;

ALTER TABLE GALADM.GAL147TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL147TBX
  ADD COLUMN QSR_ID INTEGER;

ALTER TABLE GALADM.GAL147TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL147TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL147TBX;

ALTER TABLE GALADM.GAL177TBX
   DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL177TBX
   ALTER COLUMN RESPONSIBLE_DEPT
     SET DATA TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL177TBX
   DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL177TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL177TBX;

ALTER TABLE GALADM.GAL198TBX
    DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL198TBX
    ALTER COLUMN PART_SERIAL_NUMBER
      SET DATA TYPE VARCHAR(255);

ALTER TABLE GALADM.GAL198TBX
    DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL198TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL198TBX;

ALTER TABLE GALADM.GAL206TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL206TBX
  ADD COLUMN ALLOW_DUPLICATES INTEGER NOT NULL DEFAULT 0
  ADD COLUMN COMMENT VARCHAR(256);

ALTER TABLE GALADM.GAL206TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL206TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL206TBX;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL215TBX
  ALTER COLUMN PRODUCT_SPEC_CODE  
    SET DATA TYPE CHARACTER(30)
  ADD COLUMN PROCESS_COUNT INTEGER;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL215TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL215TBX;

ALTER TABLE GALADM.GAL222TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL222TBX
 ALTER COLUMN COMMENT
   SET DATA TYPE VARCHAR(256)
 ALTER COLUMN REPAIR_DEPT
   SET DATA TYPE VARCHAR(32);

ALTER TABLE GALADM.GAL222TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL222TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL222TBX;

ALTER TABLE GALADM.GAL246TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL246TBX
 ALTER COLUMN INSTRUCTION_CODE
   SET DATA TYPE CHARACTER(2);

ALTER TABLE GALADM.GAL246TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL246TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL246TBX;

ALTER TABLE GALADM.GAL260TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL260TBX
  ADD COLUMN PREHEAT INTEGER;

ALTER TABLE GALADM.GAL260TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL260TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL260TBX;

ALTER TABLE GALADM.GAL263TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL263TBX
  ADD COLUMN APPC70A_EMISSION_FLAG CHARACTER(1)
  ADD COLUMN APPC70A_TIMESTAMP TIMESTAMP;

ALTER TABLE GALADM.GAL263TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL263TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL263TBX;

ALTER TABLE GALADM.GAL322TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL322TBX
  ADD COLUMN REPAIR_AREA CHARACTER(20)
  ADD COLUMN REPAIR_DEPARTMENT CHARACTER(32);

ALTER TABLE GALADM.GAL322TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL322TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL322TBX;

ALTER TABLE GALADM.GAL489TBX
 DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL489TBX
 ALTER COLUMN PROPERTY_KEY
   SET DATA TYPE VARCHAR(64)
 ALTER COLUMN PROPERTY_VALUE
   SET DATA TYPE VARCHAR(1024);

ALTER TABLE GALADM.GAL489TBX
 DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL489TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL489TBX;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL650TBX
  ALTER COLUMN DATA_READY_TAG
    SET NOT NULL
  ALTER COLUMN NEEDS_LISTENER
    SET NOT NULL
  ADD COLUMN PROCESS_COMPLETE_TAG VARCHAR(128);

ALTER TABLE GALADM.GAL650TBX
  ALTER COLUMN NEEDS_LISTENER
    SET DEFAULT 0;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL650TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL650TBX;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  ALTER COLUMN HOST_IP
    SET DATA TYPE VARCHAR (255)
  ALTER COLUMN HOST_PORT
    SET DATA TYPE INTEGER
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_PROVIDER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_PROVIDER_TBX;

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  ALTER COLUMN CLIENT_IP
    SET DATA TYPE VARCHAR (255);

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX;

ALTER TABLE GALADM.NOTIFICATION_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_TBX
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_TBX;

CREATE ALIAS GALADM.WSBUILDS_TBX FOR GALADM.HNA_WSBUILDS_TBX;

CREATE ALIAS GALADM.WSCLIENTS_TBX FOR GALADM.HNA_WSCLIENTS_TBX;

CREATE ALIAS GALADM.WSDEFBUILDS_TBX FOR GALADM.HNA_WSDEFBUILDS_TBX;

