function mobileqics(){var O='',vb='" for "gwt:onLoadErrorFn"',tb='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',wc='.cache.html',$='/',gc='05B877EE3A84C8B67DCF18836BBC93E6',hc='0929AF86EE007ABC1016A4FC14DCD765',nc='1CFA4D108973CB3CEDB528C0D5D679FB',oc='225E52A3B24D864C730CCC0A9A3C14E5',Cb='4',Qb='5',pc='56C696C54B72D6592087CED559FD1E8D',qc='5A89D465969C7A1FB7F67C86476D4346',Ob='6',rc='8F3E443F77708991B4604DD274E8E816',sc='8F9FEBC992BA70A98F4F8019B876460A',vc=':',ic=':1',jc=':2',kc=':3',lc=':4',mc=':5',nb='::',yc='<script defer="defer">mobileqics.onInjectionDone(\'mobileqics\')<\/script>',gb='<script id="',qb='=',Z='?',$b='ActiveXObject',sb='Bad handler "',tc='C71ECD6E781D176773C91A8088F3B517',uc='CDBE39B4FB702CF37D38E8FC5EB932A1',_b='ChromeTab.ChromeFrame',xc='DOMContentLoaded',Gb='NA',ib='SCRIPT',fb='__gwt_marker_mobileqics',Bb='android',Ab='android.minVersion',jb='base',bb='baseUrl',S='begin',Vb='blackberry',R='bootstrap',Zb='chromeframe',ab='clear.cache.gif',pb='content',X='end',Wb='file://',ac='gecko',bc='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',ub='gwt:onLoadErrorFn',rb='gwt:onPropertyErrorFn',ob='gwt:property',ec='hosted.html?mobileqics',Hb='iOS.agentIsUIWebView',Nb='iOS.minVersion',wb='iframe',_='img',Ib='ipad',Jb='iphone',Ub='ipod',xb="javascript:''",dc='loadExternalRefs',kb='meta',P='mobileqics',db='mobileqics.nocache.js',mb='mobileqics::',zb='moduleRequested',W='moduleStartup',lb='name',Mb='no',Tb='phonegap.env',yb='position:absolute;width:0;height:0;border:none',Kb='safari',cb='script',fc='selectingPermutation',Q='startup',eb='undefined',cc='unknown',Xb='user.agent',Eb='v1',Db='v4_0',Fb='v4_1',Rb='v5',Pb='v6',Sb='v7',Yb='webkit',Lb='yes';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=O,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(P);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return G(a)}}mobileqics=null;c.gwtOnLoad(y,P,s,x);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function C(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=E(bb);if(a!=null){return a}return O}
function h(){var a=m.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;m.write(gb+b+hb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=m.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
var k=g();if(k==O){k=h()}if(k==O){k=i()}if(k==O){k=j()}if(k==O){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(kb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(lb),g;if(f){f=f.replace(mb,O);if(f.indexOf(nb)>=0){continue}if(f==ob){g=e.getAttribute(pb);if(g){var h,i=g.indexOf(qb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}t[f]=h}}else if(f==rb){g=e.getAttribute(pb);if(g){try{z=eval(g)}catch(a){alert(sb+g+tb)}}}else if(f==ub){g=e.getAttribute(pb);if(g){try{y=eval(g)}catch(a){alert(sb+g+vb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function G(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=m.createElement(wb);a.src=xb;a.id=P;a.style.cssText=yb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:zb});a.contentWindow.location.replace(s+K)}}
v[Ab]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1){var b=/android\s*(1|2|3|4\.0)/;var c=b.exec(a);if(c!=null){var d=c[1];if(d[0]==Cb)return Db;else return Eb}return Fb}return Gb};u[Ab]={NA:0,v1:1,v4_0:2,v4_1:3};v[Hb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Ib)!=-1||a.indexOf(Jb)!=-1){if(a.indexOf(Kb)==-1)return Lb}return Mb};u[Hb]={no:0,yes:1};v[Nb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Ib)!=-1||a.indexOf(Jb)!=-1){var b=/cpu\s+(?:iphone\s+)?os\s*(1_|2_|3_|4_|5_|6_)/;var c=b.exec(a);if(c!=null){var d=c[1];if(d[0]==Ob)return Pb;if(d[0]==Qb)return Rb;else return Eb}return Sb}return Gb};u[Nb]={NA:0,v1:1,v5:2,v6:3,v7:4};v[Tb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Bb)!=-1||(a.indexOf(Ib)!=-1||(a.indexOf(Ub)!=-1||(a.indexOf(Jb)!=-1||a.indexOf(Vb)!=-1)))){var b=document.location.href;if(b.indexOf(Wb)===0){return Lb}}return Mb}};u[Tb]={no:0,yes:1};v[Xb]=function(){var d=navigator.userAgent.toLowerCase();if(typeof e==eb){var e=window}if(function f(){return d.indexOf(Bb)!=-1}())return Bb;if(function g(){return d.indexOf(Ib)!=-1}())return Ib;if(function h(){return d.indexOf(Jb)!=-1}())return Jb;if(function i(){return d.indexOf(Yb)!=-1||(d.indexOf(Zb)!=-1||$b in e&&function c(){try{var b=new e.ActiveXObject(_b);if(b){b.registerBhoIfNeeded();return true}}catch(a){}return false}())}())return Kb;if(function j(){return d.indexOf(ac)!=-1}())return bc;return cc};u[Xb]={android:0,gecko1_8:1,ie6:2,ie8:3,ie9:4,ipad:5,iphone:6,opera:7,safari:8};mobileqics.onScriptLoad=function(){if(H){q=true;B()}};mobileqics.onInjectionDone=function(){p=true;n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:dc,millis:(new Date).getTime(),type:X});B()};D();C();var J;var K;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(P))){l.location.reload();return}K=ec;J=O}n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:fc});if(!A()){try{F([Gb,Mb,Gb,Mb,Kb],gc);F([Gb,Mb,Gb,Mb,Jb],hc);F([Gb,Mb,Eb,Mb,Jb],hc+ic);F([Gb,Mb,Rb,Mb,Jb],hc+jc);F([Gb,Lb,Gb,Mb,Jb],hc+kc);F([Gb,Lb,Eb,Mb,Jb],hc+lc);F([Gb,Lb,Rb,Mb,Jb],hc+mc);F([Gb,Mb,Sb,Mb,Ib],nc);F([Gb,Lb,Sb,Mb,Ib],nc+ic);F([Gb,Mb,Gb,Lb,Kb],oc);F([Gb,Mb,Gb,Mb,bc],pc);F([Gb,Mb,Sb,Mb,Jb],qc);F([Gb,Lb,Sb,Mb,Jb],qc+ic);F([Gb,Mb,Gb,Mb,Ib],rc);F([Gb,Mb,Eb,Mb,Ib],rc+ic);F([Gb,Mb,Rb,Mb,Ib],rc+jc);F([Gb,Lb,Gb,Mb,Ib],rc+kc);F([Gb,Lb,Eb,Mb,Ib],rc+lc);F([Gb,Lb,Rb,Mb,Ib],rc+mc);F([Gb,Mb,Gb,Mb,Bb],sc);F([Eb,Mb,Gb,Mb,Bb],sc+ic);F([Db,Mb,Gb,Mb,Bb],sc+jc);F([Fb,Mb,Gb,Mb,Bb],sc+kc);F([Gb,Mb,Pb,Mb,Ib],tc);F([Gb,Lb,Pb,Mb,Ib],tc+ic);F([Gb,Mb,Pb,Mb,Jb],uc);F([Gb,Lb,Pb,Mb,Jb],uc+ic);J=w[G(Ab)][G(Hb)][G(Nb)][G(Tb)][G(Xb)];var L=J.indexOf(vc);if(L!=-1){x=Number(J.substring(L+1));J=J.substring(0,L)}K=J+wc}catch(a){return}}var M;function N(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(xc,N,false)}if(M){clearInterval(M)}}}
if(m.addEventListener){m.addEventListener(xc,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(m.readyState)){I();N()}},50);n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});n&&n({moduleName:P,sessionId:o,subSystem:Q,evtGroup:dc,millis:(new Date).getTime(),type:S});m.write(yc)}
mobileqics();