
ALTER TABLE "STAMPSTOR"."DIE_TBX"
  ADD COLUMN TEXT_COLOR	VARCHAR(8)
  ADD COLUMN BACKGROUND_COLOR	VARCHAR(8)
  ADD COLUMN ACTIVE smallint;   
  
REORG TABLE "STAMPSTOR"."DIE_TBX";

DROP TABLE STAMPSTOR.ATTRIBUTE_TYPES_TBX;
DROP TABLE STAMPSTOR.ATTRIBUTES_TBX;

CREATE TABLE STAMPSTOR.ATTRIBUTE_TYPES_TBX (
  ATTRIBUTE_TYPE_ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       MINVALUE 0, NO MAXVALUE, NO CYCLE, NO ORDER),
  NAME	VARCHAR(50)	NOT NULL,
  VERSION	INTEGER
);

CREATE TABLE STAMPSTOR.ATTRIBUTES_TBX (
  ATTRIBUTE_ID	BIGINT	NOT NULL	GENERATED ALWAYS
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       MINVALUE 0, NO MAXVALUE, NO CYCLE, NO ORDER),
  ATTRIBUTE_TYPE	BIGINT	NOT NULL,
  ATTRIBUTE_NAME	VARCHAR(255),
  ATTRIBUTE_VALUE	INTEGER,
  VERSION	INTEGER
);