DROP ALIAS HCM_BLOCK_TBX;
DROP TRIGGER GALADM.BLOCK_TR2;
DROP TRIGGER GALADM.BLOCK_TR1;
DROP TABLE GALADM.BLOCK_TBX;

CREATE TABLE GALADM.BLOCK_TBX (
   BLOCK_ID	VARCHAR(17) NOT NULL,
   MC_SERIAL_NUMBER	VARCHAR(17),
   DC_SERIAL_NUMBER	VARCHAR(17),
   ENGINE_SERIAL_NUMBER	VARCHAR(17),
   MODEL	VARCHAR(12),
   TRACKING_STATUS	VARCHAR(12),
   DUNNAGE	VARCHAR(12),
   DEFECT_STATUS	SMALLINT,
   HOLD_STATUS	SMALLINT DEFAULT 0 NOT NULL,
   LAST_PASSING_PROCESS_POINT_ID	CHARACTER(16),
   CREATE_TIMESTAMP	TIMESTAMP,
   UPDATE_TIMESTAMP	TIMESTAMP,
   CONSTRAINT BLOCK_PK PRIMARY KEY 
     (BLOCK_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.BLOCK_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.BLOCK_TBX IS 'RMT Block';
    
CREATE TRIGGER GALADM.BLOCK_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.BLOCK_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.BLOCK_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.BLOCK_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.BLOCK_I1
  ON GALADM.BLOCK_TBX
    ( ENGINE_SERIAL_NUMBER )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.BLOCK_I2
  ON GALADM.BLOCK_TBX
    ( DC_SERIAL_NUMBER )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.BLOCK_I3
  ON GALADM.BLOCK_TBX
    ( DUNNAGE )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.BLOCK_I4
  ON GALADM.BLOCK_TBX
    ( LAST_PASSING_PROCESS_POINT_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.BLOCK_I5
  ON GALADM.BLOCK_TBX
    ( MC_SERIAL_NUMBER )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE ALIAS HCM_BLOCK_TBX FOR GALADM.BLOCK_TBX;
COMMENT ON ALIAS GALADM.HCM_BLOCK_TBX IS 'RMT alias to BLOCK_TBX';