DROP TRIGGER GALADM.GAL126_TR2;
DROP TRIGGER GALADM.GAL126_TR1;
DROP TABLE GALADM.GAL126TBX;

CREATE TABLE GALADM.GAL126TBX (
  DEFECT_TYPE_NAME VARCHAR(45) NOT NULL DEFAULT '',
  DEFECT_TYPE_DESCRIPTION_SHORT VARCHAR(10),
  DEFECT_TYPE_DESCRIPTION_LONG VARCHAR(30),
  TWO_PART_DEFECT_FLAG SMALLINT,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL126_PK PRIMARY KEY
    (DEFECT_TYPE_NAME)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL126TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL126TBX IS 'RMT DefectType for QICS to define defect type name';

CREATE TRIGGER GALADM.GAL126_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL126TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL126_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL126TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL126_I1
  ON GALADM.GAL126TBX
    ( DEFECT_TYPE_NAME ASC, TWO_PART_DEFECT_FLAG ASC, DEFECT_TYPE_DESCRIPTION_LONG ASC, DEFECT_TYPE_DESCRIPTION_SHORT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;