DROP TRIGGER GALADM.GAL177_TR2;
DROP TRIGGER GALADM.GAL177_TR1;
DROP TABLE GALADM.GAL177TBX;

CREATE TABLE GALADM.GAL177TBX (
  REPAIR_AREA_NAME CHARACTER(20),
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  PARKING_LOCATION CHARACTER(6),
  ACTUAL_TIMESTAMP TIMESTAMP,
  REJECTION CHARACTER(100),
  RESPONSIBLE_DEPT VARCHAR(32),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL177_PK PRIMARY KEY
    (PRODUCT_ID)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL177TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL177TBX IS 'RMT InRepairArea for QICS';

CREATE TRIGGER GALADM.GAL177_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL177TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL177_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL177TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL177_I1
  ON GALADM.GAL177TBX
    ( PRODUCT_ID ASC, PARKING_LOCATION ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;