DROP TRIGGER GALADM.GAL173_TR2;
DROP TRIGGER GALADM.GAL173_TR1;
DROP TABLE GALADM.GAL173TBX;

CREATE TABLE GALADM.GAL173TBX (
  IMAGE_NAME VARCHAR(20) NOT NULL DEFAULT '',
  IMAGE_DESCRIPTION_SHORT VARCHAR(10),
  IMAGE_DESCRIPTION_LONG VARCHAR(30),
  BITMAP_FILE_NAME VARCHAR(255) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  IMAGE_DATA BLOB(1M)  INLINE LENGTH 164 LOGGED COMPACT,
  CONSTRAINT GAL173_PK PRIMARY KEY
    (BITMAP_FILE_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL173TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL173TBX IS 'RMT Image for QICS';

CREATE TRIGGER GALADM.GAL173_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL173TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL173_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL173TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL173_I1
  ON GALADM.GAL173TBX
    ( IMAGE_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;