DROP TRIGGER GALADM.GAL135_TR2;
DROP TRIGGER GALADM.GAL135_TR1;
DROP TABLE GALADM.GAL135TBX;

CREATE TABLE GALADM.GAL135TBX (
  PROCESS_POINT_ID CHARACTER(16) NOT NULL DEFAULT '',
  PRODUCT_ID CHARACTER(17),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  LAST_PROCESSED_PRODUCT CHARACTER(17),
  CONSTRAINT GAL135_PK PRIMARY KEY
    (PROCESS_POINT_ID)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL135TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL135TBX IS 'RMT ExpectedProduct for LOT CONTROL';

CREATE TRIGGER GALADM.GAL135_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL135TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL135_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL135TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;