DROP TRIGGER GALADM.GAL118_TR2;
DROP TRIGGER GALADM.GAL118_TR1;
DROP TABLE GALADM.GAL118TBX;

CREATE TABLE GALADM.GAL118TBX (
  PASSING_COUNTER	INTEGER,
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL	DEFAULT '',
  PRODUCTION_DATE	DATE	NOT NULL	DEFAULT CURRENT_DATE,
  SHIFT	CHARACTER(2)	NOT NULL	DEFAULT '',
  PERIOD	INTEGER	NOT NULL	DEFAULT 0,
  PERIOD_LABEL	CHARACTER(5),
  MODEL_CODE	CHARACTER(3)	NOT NULL	DEFAULT '',
  MODEL_YEAR_CODE	CHARACTER(1)	NOT NULL	DEFAULT '',
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL118_PK PRIMARY KEY
    (PROCESS_POINT_ID, PRODUCTION_DATE, SHIFT, PERIOD, MODEL_CODE, MODEL_YEAR_CODE)
) 
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL118TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL118TBX IS 'RMT CounterByModelGroup for summarizing number of models built by process point, production date, shift, period';

CREATE TRIGGER GALADM.GAL118_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL118TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL118_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL118TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
