DROP TRIGGER GALADM.GAL133_TR2;
DROP TRIGGER GALADM.GAL133_TR1;
DROP TABLE GALADM.GAL133TBX;

CREATE TABLE GALADM.GAL133TBX (
  PRODUCT_SPEC_CODE CHARACTER(22) NOT NULL DEFAULT '',
  MISSION_PLANT_CODE CHARACTER(4),
  MISSION_MODEL_CODE CHARACTER(3),
  MISSION_PROTOTYPE_CODE CHARACTER(1),
  MISSION_MODEL_TYPE_CODE CHARACTER(3),
  ENGINE_NO_PREFIX CHARACTER(5),
  TRANSMISSION CHARACTER(5),
  TRANSMISSION_DESCRIPTION CHARACTER(20),
  GEAR_SHIFT CHARACTER(1),
  GEAR_SHIFT_DESCRIPTION CHARACTER(20),
  DISPLACEMENT CHARACTER(5),
  DISPLACEMENT_COMMENT CHARACTER(20),
  ENGINE_PROTOTYPE_CODE CHARACTER(1),
  PLANT_CODE CHARACTER(4),
  MODEL_YEAR_CODE CHARACTER(1),
  MODEL_CODE CHARACTER(3),
  MODEL_TYPE_CODE CHARACTER(3),
  MODEL_OPTION_CODE CHARACTER(3),
  MODEL_YEAR_DESCRIPTION CHARACTER(4),
  MISSION_MODEL_YEAR_CODE CHARACTER(1),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL133_PK PRIMARY KEY
    (PRODUCT_SPEC_CODE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL133TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL133TBX IS 'RMT EngineSpec';

CREATE TRIGGER GALADM.GAL133_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL133TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL133_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL133TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL133_I1
  ON GALADM.GAL133TBX
    ( PRODUCT_SPEC_CODE ASC, MISSION_MODEL_CODE ASC, MISSION_MODEL_TYPE_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;