DROP TRIGGER GALADM.GAL192_TR2;
DROP TRIGGER GALADM.GAL192_TR1;
DROP TABLE GALADM.GAL192TBX;

CREATE TABLE GALADM.GAL192TBX (
  IQS_CATEGORY_NAME CHARACTER(32) NOT NULL DEFAULT '',
  IQS_ITEM_NAME CHARACTER(64) NOT NULL DEFAULT '',
  COEFFICIENT CHARACTER(30),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL192_PK PRIMARY KEY
    (IQS_CATEGORY_NAME, IQS_ITEM_NAME)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL192TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL192TBX IS 'RMT IQS';

CREATE TRIGGER GALADM.GAL192_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL192TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL192_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL192TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;