DROP TRIGGER GALADM.GAL174_TR2;
DROP TRIGGER GALADM.GAL174_TR1;
DROP TABLE GALADM.GAL174TBX;

CREATE TABLE GALADM.GAL174TBX (
  IMAGE_SECTION_ID INTEGER NOT NULL DEFAULT 0,
  IMAGE_NAME VARCHAR(20),
  PART_KIND_FLAG SMALLINT,
  DESCRIPTION_ID INTEGER,
  OVERLAY_NO INTEGER NOT NULL DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL174_PK PRIMARY KEY
    (IMAGE_SECTION_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL174TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL174TBX IS 'RMT ImageSection for QICS';

CREATE TRIGGER GALADM.GAL174_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL174TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL174_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL174TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL174_I1
  ON GALADM.GAL174TBX
    ( OVERLAY_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;