DROP TRIGGER GALADM.GAL144_TR2;
DROP TRIGGER GALADM.GAL144_TR1;
DROP TABLE GALADM.GAL144TBX;

CREATE TABLE GALADM.GAL144TBX (
  PRODUCT_SPEC_CODE CHARACTER(22) NOT NULL DEFAULT '',
  EXT_COLOR_CODE CHARACTER(10),
  INT_COLOR_CODE CHARACTER(2),
  EXT_COLOR_DESCRIPTION CHARACTER(10),
  INT_COLOR_DESCRIPTION CHARACTER(40),
  PLANT_CODE_GPCS CHARACTER(4),
  ENGINE_PLANT_CODE CHARACTER(4),
  ENGINE_MTO CHARACTER(10),
  SALES_MODEL_CODE CHARACTER(10),
  SALES_MODEL_TYPE_CODE CHARACTER(2),
  SALES_EXT_COLOR_CODE CHARACTER(10),
  SALES_INT_COLOR_CODE CHARACTER(2),
  PROTOTYPE_CODE CHARACTER(1),
  FRAME_NO_PREFIX CHARACTER(11),
  SERIES_CODE CHARACTER(1),
  SERIES_DESCRIPTION CHARACTER(40),
  GRADE_CODE CHARACTER(10),
  BODY_AND_TRANS_TYPE_CODE CHARACTER(1),
  BODY_AND_TRANS_TYPE_DESC CHARACTER(30),
  MODEL_CODE CHARACTER(3),
  MODEL_YEAR_CODE CHARACTER(1),
  MODEL_TYPE_CODE CHARACTER(3),
  MODEL_OPTION_CODE CHARACTER(3),
  MODEL_YEAR_DESCRIPTION CHARACTER(4),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  BOUNDARY_MARK_REQUIRED CHARACTER(1) NOT NULL DEFAULT '',
  CONSTRAINT GAL144_PK PRIMARY KEY
    (PRODUCT_SPEC_CODE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL144TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL144TBX IS 'RMT FrameSpec';

CREATE TRIGGER GALADM.GAL144_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL144TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL144_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL144TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL144_I1
  ON GALADM.GAL144TBX
    ( PRODUCT_SPEC_CODE ASC, SALES_MODEL_TYPE_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL144_I2
  ON GALADM.GAL144TBX
    ( MODEL_CODE ASC, MODEL_TYPE_CODE ASC, EXT_COLOR_CODE ASC, MODEL_YEAR_CODE ASC, INT_COLOR_CODE ASC, MODEL_OPTION_CODE ASC, PRODUCT_SPEC_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;