DROP TRIGGER GALADM.GAL128_TR2;
DROP TRIGGER GALADM.GAL128_TR1;
DROP TABLE GALADM.GAL128TBX;

CREATE TABLE GALADM.GAL128TBX (
  DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '',
  SITE_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_NAME CHARACTER(16) NOT NULL DEFAULT '',
  DIVISION_NAME CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_DESCRIPTION CHARACTER(128),
  DIVISION_NAME1 CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_NAME2 CHARACTER(32) NOT NULL DEFAULT '',
  SEQUENCE_NUMBER INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL128_PK PRIMARY KEY
    (DIVISION_ID)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL128TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL128TBX IS 'RMT Division';

CREATE TRIGGER GALADM.GAL128_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL128TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL128_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL128TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL128_I1
  ON GALADM.GAL128TBX
    ( DIVISION_ID ASC, DIVISION_NAME ASC, DIVISION_NAME1 ASC, DIVISION_NAME2 ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL128_I2
  ON GALADM.GAL128TBX
    ( DIVISION_ID ASC, SEQUENCE_NUMBER ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;