DROP TRIGGER GALADM.GAL143_TR2;
DROP TRIGGER GALADM.GAL143_TR1;
DROP TABLE GALADM.GAL143TBX;

CREATE TABLE GALADM.GAL143TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  ENGINE_SERIAL_NO CHARACTER(17),
  MISSION_SERIAL_NO CHARACTER(20),
  STRAIGHT_SHIP_PERCENTAGE DOUBLE,
  KEY_NO CHARACTER(7),
  SHORT_VIN CHARACTER(11),
  PRODUCTION_LOT CHARACTER(20),
  KD_LOT_NUMBER CHARACTER(18),
  PRODUCT_SPEC_CODE CHARACTER(22),
  PLAN_OFF_DATE DATE,
  TRACKING_STATUS CHARACTER(16),
  PRODUCT_START_DATE DATE,
  ACTUAL_OFF_DATE DATE,
  AUTO_HOLD_STATUS SMALLINT,
  PRODUCTION_DATE DATE,
  LAST_PASSING_PROCESS_POINT_ID CHARACTER(16),
  ENGINE_STATUS INTEGER,
  AF_ON_SEQUENCE_NUMBER INTEGER,
  ACTUAL_MISSION_TYPE CHARACTER(7),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL143_PK PRIMARY KEY
    (PRODUCT_ID)
)
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;
  
ALTER TABLE GALADM.GAL143TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL143TBX IS 'RMT Frame';

CREATE TRIGGER GALADM.GAL143_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL143TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL143_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL143TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL143_I1
  ON GALADM.GAL143TBX
    ( ENGINE_SERIAL_NO ASC, AF_ON_SEQUENCE_NUMBER ASC, PRODUCT_SPEC_CODE ASC, MISSION_SERIAL_NO ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I2
  ON GALADM.GAL143TBX
    ( PRODUCT_ID ASC, ENGINE_SERIAL_NO ASC, AF_ON_SEQUENCE_NUMBER ASC, PRODUCT_SPEC_CODE ASC, MISSION_SERIAL_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I3
  ON GALADM.GAL143TBX
    ( LAST_PASSING_PROCESS_POINT_ID ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I4
  ON GALADM.GAL143TBX
    ( PRODUCT_SPEC_CODE ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I5
  ON GALADM.GAL143TBX
    ( PRODUCT_ID ASC, ENGINE_SERIAL_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I6
  ON GALADM.GAL143TBX
    ( ENGINE_SERIAL_NO ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I7
  ON GALADM.GAL143TBX
    ( TRACKING_STATUS ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL143_I8
  ON GALADM.GAL143TBX
    ( PRODUCTION_LOT ASC, PRODUCT_SPEC_CODE ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;