DROP TRIGGER GALADM.GAL127_TR2;
DROP TRIGGER GALADM.GAL127_TR1;
DROP TABLE GALADM.GAL127TBX;

CREATE TABLE GALADM.GAL127TBX (
  DEFECT_TYPE_NAME VARCHAR(45) NOT NULL DEFAULT '',
  SECONDARY_PART_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DEFECT_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL127_PK PRIMARY KEY
    (DEFECT_TYPE_NAME, SECONDARY_PART_NAME, DEFECT_GROUP_NAME)
)
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL127TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL127TBX IS 'RMT DefectTypeDescription for QICS';

CREATE TRIGGER GALADM.GAL127_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL127TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL127_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL127TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL127_I1
  ON GALADM.GAL127TBX
    ( DEFECT_GROUP_NAME ASC, DEFECT_TYPE_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL127_I2
  ON GALADM.GAL127TBX
    ( DEFECT_GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL127_I3
  ON GALADM.GAL127TBX
    ( DEFECT_TYPE_NAME ASC, DEFECT_GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL127_I4
  ON GALADM.GAL127TBX
    ( DEFECT_TYPE_NAME ASC, SECONDARY_PART_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL127_I5
  ON GALADM.GAL127TBX
    ( SECONDARY_PART_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;