DROP TRIGGER GALADM.GAL158_TR2;
DROP TRIGGER GALADM.GAL158_TR1;
DROP TABLE GALADM.GAL158TBX;

CREATE TABLE GALADM.GAL158TBX (
  PLANT_CODE_FRAME CHARACTER(4) NOT NULL DEFAULT '' ,
  MODEL_YEAR_CODE CHARACTER(1) NOT NULL DEFAULT '' ,
  MODEL_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  MODEL_TYPE_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  MODEL_OPTION_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  EXT_COLOR_CODE CHARACTER(10) NOT NULL DEFAULT '' ,
  INT_COLOR_CODE CHARACTER(2) NOT NULL DEFAULT '' ,
  MODEL_YEAR_DESCRIPTION CHARACTER(4),
  EXT_COLOR_DESCRIPTION CHARACTER(10),
  INT_COLOR_DESCRIPTION CHARACTER(40),
  FRAME_NO_PREFIX CHARACTER(11) NOT NULL DEFAULT '' ,
  SERIES_CODE CHARACTER(1) NOT NULL DEFAULT '' ,
  SERIES_DESCRIPTION CHARACTER(40),
  GRADE_CODE CHARACTER(10) NOT NULL DEFAULT '' ,
  BODY_AND_TRANS_TYPE_CODE CHARACTER(1) NOT NULL DEFAULT '' ,
  BODY_AND_TRANS_TYPE_DESC CHARACTER(30),
  SALES_MODEL_CODE CHARACTER(10) NOT NULL DEFAULT '' ,
  SALES_MODEL_TYPE_CODE CHARACTER(2) NOT NULL DEFAULT '' ,
  SALES_MODEL_OPTION_CODE CHARACTER(2) NOT NULL DEFAULT '' ,
  SALES_EXT_COLOR_CODE CHARACTER(10) NOT NULL DEFAULT '' ,
  SALES_INT_COLOR_CODE CHARACTER(2) NOT NULL DEFAULT '' ,
  PROTOTYPE_CODE CHARACTER(1) NOT NULL DEFAULT '' ,
  F_E CHARACTER(1) NOT NULL DEFAULT '' ,
  PLANT_CODE_ENGINE CHARACTER(4) NOT NULL DEFAULT '' ,
  ENGINE_MODEL_YEAR_CODE CHARACTER(1) NOT NULL DEFAULT '' ,
  ENGINE_MODEL_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  ENGINE_MODEL_TYPE_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  ENGINE_OPTION_CODE CHARACTER(3) NOT NULL DEFAULT '' ,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL158_PK PRIMARY KEY
    (PLANT_CODE_FRAME, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EXT_COLOR_CODE, INT_COLOR_CODE)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL158TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL158TBX IS
   'RMT HostMtoc for OIF Frame MTO Master Specification';

CREATE TRIGGER GALADM.GAL158_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL158TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL158_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL158TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;