DROP TRIGGER GALADM.GAL147_TR2;
DROP TRIGGER GALADM.GAL147_TR1;
DROP TABLE GALADM.GAL147TBX;

CREATE TABLE GALADM.GAL147TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  ACTUAL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  HOLD_TYPE INTEGER NOT NULL DEFAULT 0,
  RELEASE_TIMESTAMP TIMESTAMP,
  RELEASE_FLAG SMALLINT,
  HOLD_ASSOCIATE_NO CHARACTER(11),
  HOLD_ASSOCIATE_NAME CHARACTER(30),
  HOLD_ASSOCIATE_PHONE CHARACTER(20),
  HOLD_ASSOCIATE_PAGER CHARACTER(15),
  HOLD_REASON CHARACTER(80),
  RELEASE_ASSOCIATE_NO CHARACTER(11),
  RELEASE_ASSOCIATE_NAME CHARACTER(30),
  RELEASE_ASSOCIATE_PHONE CHARACTER(20),
  RELEASE_ASSOCIATE_PAGER CHARACTER(15),
  RELEASE_REASON CHARACTER(80),
  LOT_HOLD_STATUS INTEGER,
  PRODUCTION_LOT CHARACTER(20),
  PRODUCT_SPEC_CODE CHARACTER(22),
  PRODUCTION_DATE DATE,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  QSR_ID INTEGER,
  CONSTRAINT GAL147_PK PRIMARY KEY
    (PRODUCT_ID, ACTUAL_TIMESTAMP, HOLD_TYPE)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL147TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL147TBX IS 'RMT HoldResult';

CREATE TRIGGER GALADM.GAL147_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL147TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL147_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL147TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;