DROP TRIGGER GALADM.GAL178_TR2;
DROP TRIGGER GALADM.GAL178_TR1;
DROP TABLE GALADM.GAL178TBX;

CREATE TABLE GALADM.GAL178TBX (
  MODEL_CODE CHARACTER(3) NOT NULL DEFAULT ' ',
  PART_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DEFECT_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT '',
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT ' ',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL178_PK PRIMARY KEY
    (MODEL_CODE, APPLICATION_ID, PART_GROUP_NAME, DEFECT_GROUP_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL178TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL178TBX IS 'RMT InspectionModel for QICS';

CREATE TRIGGER GALADM.GAL178_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL178TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL178_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL178TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;