DROP TRIGGER GALADM.GAL105_TR2;
DROP TRIGGER GALADM.GAL105_TR1;
DROP TABLE GALADM.GAL105TBX;

CREATE TABLE GALADM.GAL105TBX (
  ROW_INSERT_TSTMP	TIMESTAMP,
  ROW_UPDATE_TSTMP	TIMESTAMP,
  ROW_DISUSE_TSTMP	TIMESTAMP,
  ROW_HISTRC_CNTER	INTEGER,
  ROW_UPDATE_USER	CHARACTER(11),
  USER_ID	CHARACTER(11)	NOT NULL	DEFAULT '',
  PASSWD	CHARACTER(8),
  PASSWD_1	CHARACTER(8),
  PASSWD_2	CHARACTER(8),
  PASSWD_3	CHARACTER(8),
  PASSWD_4	CHARACTER(8),
  PASSWD_5	CHARACTER(8),
  PASSWD_UPD_DT	CHARACTER(8),
  ERROR_FREQ_1	SMALLINT,
  ERROR_FREQ_2	SMALLINT,
  LOGIN_STATUS	CHARACTER(1),
  USER_NAME	CHARACTER(30),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL105_PK PRIMARY KEY
    (USER_ID)
) 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL105TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL105TBX IS 'RMT AccessControlManager for user security';
    
CREATE TRIGGER GALADM.GAL105_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL105TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL105_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL105TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
    
