DROP TRIGGER GALADM.GAL123_TR2;
DROP TRIGGER GALADM.GAL123_TR1;
DROP TABLE GALADM.GAL123TBX;

CREATE TABLE GALADM.GAL123TBX (
  DEFECT_GROUP_NAME	VARCHAR(20)	NOT NULL	DEFAULT '',
  DEFECT_GROUP_DESCRIPTION_SHORT	VARCHAR(10),
  DEFECT_GROUP_DESCRIPTION_LONG	VARCHAR(30),
  IMAGE_NAME	VARCHAR(20),
  MODEL_CODE	CHARACTER(3),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL123_PK PRIMARY KEY
    (DEFECT_GROUP_NAME)
) 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL123TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL123TBX IS 'RMT DefectGroup for QICS';

CREATE TRIGGER GALADM.GAL123_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL123TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL123_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL123TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL123_I1
  ON GALADM.GAL123TBX
    ( DEFECT_GROUP_NAME ASC, IMAGE_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL123_I2
  ON GALADM.GAL123TBX
    ( DEFECT_GROUP_NAME ASC, DEFECT_GROUP_DESCRIPTION_LONG ASC, DEFECT_GROUP_DESCRIPTION_SHORT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL123_I3
  ON GALADM.GAL123TBX
    ( IMAGE_NAME ASC, DEFECT_GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL123_I4
  ON GALADM.GAL123TBX
    ( MODEL_CODE ASC, DEFECT_GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
