DROP TRIGGER GALADM.GAL191_TR2;
DROP TRIGGER GALADM.GAL191_TR1;
DROP TABLE GALADM.GAL191TBX;

CREATE TABLE GALADM.GAL191TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  IPP_TAG_NO CHARACTER(10) NOT NULL DEFAULT '',
  ACTUAL_TIMESTAMP TIMESTAMP,
  DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL191_PK PRIMARY KEY
    (PRODUCT_ID, IPP_TAG_NO, DIVISION_ID)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL191TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL191TBX IS
   'RMT IPPTag for QICS to track Initial Production Part Tag';

CREATE TRIGGER GALADM.GAL191_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL191TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL191_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL191TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;