DROP TRIGGER GALADM.GAL181_TR2;
DROP TRIGGER GALADM.GAL181_TR1;
DROP TABLE GALADM.GAL181TBX;

CREATE TABLE GALADM.GAL181TBX (
  INSPECTION_PART_LOCATION_NAME VARCHAR(20) NOT NULL DEFAULT '',
  INSPECTION_PART_LOC_DESC_SHORT VARCHAR(10),
  INSPECTION_PART_LOC_DESC_LONG VARCHAR(30),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL181_PK PRIMARY KEY
    (INSPECTION_PART_LOCATION_NAME)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL181TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL181TBX IS 'RMT InspectionPartLocation for QICS';

CREATE TRIGGER GALADM.GAL181_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL181TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL181_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL181TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;