DROP TRIGGER GALADM.GAL117_TR2;
DROP TRIGGER GALADM.GAL117_TR1;
DROP TABLE GALADM.GAL117TBX;

CREATE TABLE GALADM.GAL117TBX (
  SITE_NAME	CHARACTER(16)	NOT NULL	DEFAULT '',
  SITE_DESCRIPTION	CHARACTER(128),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL117_PK PRIMARY KEY
    (SITE_NAME)
) 
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL117TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL117TBX IS 'RMT Site';

CREATE TRIGGER GALADM.GAL117_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL117TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;
    
CREATE TRIGGER GALADM.GAL117_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL117TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
    
