DROP TRIGGER GALADM.GAL198_HIST_TR2;
DROP TRIGGER GALADM.GAL198_HIST_TR1;
DROP TABLE GALADM.GAL198_HIST_TBX;

CREATE TABLE GALADM.GAL198_HIST_TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  PART_NAME CHARACTER(32) NOT NULL DEFAULT '',
  MEASUREMENT_SEQUENCE_NUMBER INTEGER NOT NULL DEFAULT 0,
  MEASUREMENT_ATTEMPT INTEGER NOT NULL DEFAULT 0,
  MEASUREMENT_VALUE DOUBLE,
  MEASUREMENT_STATUS INTEGER,
  ACTUAL_TIMESTAMP TIMESTAMP,
  MEASUREMENT_ANGLE DOUBLE,
  PART_SERIAL_NUMBER VARCHAR(255),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL198_HIST_PK PRIMARY KEY
    (PRODUCT_ID, PART_NAME, MEASUREMENT_SEQUENCE_NUMBER, MEASUREMENT_ATTEMPT)
)
  IN GALTBSDAT3
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL198_HIST_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL198_HIST_TBX IS 'RMT Measurement Attempt History for LOT CONTROL';

CREATE TRIGGER GALADM.GAL198_HIST_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL198_HIST_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL198_HIST_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL198_HIST_I1
  ON GALADM.GAL198_HIST_TBX
    ( PRODUCT_ID ASC, PART_NAME ASC, ACTUAL_TIMESTAMP ASC, MEASUREMENT_VALUE ASC, MEASUREMENT_ATTEMPT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
