DROP TRIGGER GALADM.GAL120_TR2;
DROP TRIGGER GALADM.GAL120_TR1;
DROP TABLE GALADM.GAL120TBX;

CREATE TABLE GALADM.GAL120TBX (
  PASSING_COUNTER	INTEGER,
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL	DEFAULT '',
  PRODUCTION_DATE	DATE	NOT NULL	DEFAULT CURRENT_DATE,
  SHIFT	CHARACTER(2)	NOT NULL	DEFAULT '',
  PERIOD	INTEGER	NOT NULL	DEFAULT 0,
  PERIOD_LABEL	CHARACTER(5),
  PRODUCTION_LOT	CHARACTER(20)	NOT NULL	DEFAULT '',
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL120_PK PRIMARY KEY
    (PROCESS_POINT_ID, PRODUCTION_DATE, SHIFT, PERIOD, PRODUCTION_LOT)
) 
  IN GALTBSDAT4
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL120TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL120TBX IS 'RMT CounterByProductionLot for summarizing number of production lots built by process point, production date, shift, period';

CREATE TRIGGER GALADM.GAL120_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL120TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL120_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL120TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
