DROP TRIGGER GALADM.GAL131_TR2;
DROP TRIGGER GALADM.GAL131_TR1;
DROP TABLE GALADM.GAL131TBX;

CREATE TABLE GALADM.GAL131TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  VIN CHARACTER(17),
  MISSION_SERIAL_NO CHARACTER(20),
  ENGINE_FIRING_FLAG SMALLINT DEFAULT 0,
  PRODUCTION_LOT CHARACTER(20),
  KD_LOT_NUMBER CHARACTER(18),
  PRODUCT_SPEC_CODE CHARACTER(22),
  PLAN_OFF_DATE DATE,
  TRACKING_STATUS CHARACTER(16),
  PRODUCTION_DATE DATE,
  PRODUCT_START_DATE DATE,
  ACTUAL_OFF_DATE DATE,
  AUTO_HOLD_STATUS SMALLINT,
  LAST_PASSING_PROCESS_POINT_ID CHARACTER(16),
  MISSION_STATUS INTEGER,
  FIRING_TYPE INTEGER,
  REPAIR_FLAG SMALLINT,
  ACTUAL_MISSION_TYPE CHARACTER(7),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  PLANT_CODE CHARACTER(4),
  DEFECT_STATUS SMALLINT,
  CONSTRAINT GAL131_PK PRIMARY KEY
    (PRODUCT_ID)
)
  IN GALTBSDAT9
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL131TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL131TBX IS 'RMT Engine';

CREATE TRIGGER GALADM.GAL131_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL131_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL131TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL131_I1
  ON GALADM.GAL131TBX
    ( PRODUCT_ID ASC, PRODUCT_SPEC_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL131_I2
  ON GALADM.GAL131TBX
    ( PRODUCT_ID ASC, VIN ASC, MISSION_SERIAL_NO ASC, PRODUCT_SPEC_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL131_I3
  ON GALADM.GAL131TBX
    ( PRODUCTION_DATE ASC, PRODUCTION_LOT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;