DROP TRIGGER GALADM.GAL136_TR2;
DROP TRIGGER GALADM.GAL136_TR1;
DROP TABLE GALADM.GAL136TBX;

CREATE TABLE GALADM.GAL136TBX (
   PRODUCT_ID                      CHARACTER (17) NOT NULL DEFAULT '',
   ACTUAL_TIMESTAMP                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ASSOCIATE_NO                    CHARACTER (11),
   EXCEPTIONAL_OUT_COMMENT         VARCHAR (255),
   EXCEPTIONAL_OUT_REASON_STRING   CHARACTER (64),
   PRODUCTION_DATE                 DATE,
   PROCESS_POINT_ID                CHARACTER (16),
   CREATE_TIMESTAMP                TIMESTAMP,
   UPDATE_TIMESTAMP                TIMESTAMP,
   LOCATION                        VARCHAR (20),
   CONSTRAINT GAL136_PK PRIMARY KEY
     (PRODUCT_ID, ACTUAL_TIMESTAMP)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL136TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL136TBX IS 'RMT ExceptionalOut';

CREATE TRIGGER GALADM.GAL136_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL136TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL136_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL136TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;