DROP TRIGGER GALADM.GAL141_TR2;
DROP TRIGGER GALADM.GAL141_TR1;
DROP TABLE GALADM.GAL141TBX;

CREATE TABLE GALADM.GAL141TBX (
   ENGINE_SERIAL_NO   CHARACTER (17) NOT NULL DEFAULT '',
   RESULT_ID          INTEGER NOT NULL DEFAULT 0,
   FIRING_TEST_TYPE   CHARACTER (20),
   ASSOCIATE_NO       CHARACTER (11),
   FIRING_NOTES       VARCHAR (255),
   FIRING_STATUS      SMALLINT,
   FIRING_BENCH_NO    INTEGER,
   ACTUAL_TIMESTAMP   TIMESTAMP,
   CREATE_TIMESTAMP   TIMESTAMP,
   UPDATE_TIMESTAMP   TIMESTAMP,
   CONSTRAINT GAL141_PK PRIMARY KEY
     (ENGINE_SERIAL_NO, RESULT_ID)
)
  IN GALTBSDAT9
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL141TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL141TBX IS 'RMT EngineFiringResult';

CREATE TRIGGER GALADM.GAL141_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL141TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL141_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL141TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;