DROP TRIGGER GALADM.GAL111_TR2;
DROP TRIGGER GALADM.GAL111_TR1;
DROP TABLE GALADM.GAL111TBX;

CREATE TABLE GALADM.GAL111TBX (
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL	DEFAULT '',
  SEQUENCE_NUMBER	INTEGER	NOT NULL	DEFAULT 0,
  DESTINATION_TYPE	INTEGER,
  DESTINATION_ID	CHARACTER(32),
  REQUEST_ID	CHARACTER(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  ARGUMENT	CHARACTER(128),
  CONSTRAINT GAL111_PK PRIMARY KEY
    (PROCESS_POINT_ID, SEQUENCE_NUMBER)
) 
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL111TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL111TBX IS 'RMT BroadcastDestination for setting up printing on a process point';

CREATE TRIGGER GALADM.GAL111_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL111_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
