DROP TRIGGER GALADM.GAL179_TR2;
DROP TRIGGER GALADM.GAL179_TR1;
DROP TABLE GALADM.GAL179TBX;

CREATE TABLE GALADM.GAL179TBX (
  INSPECTION_PART_NAME VARCHAR(32) NOT NULL DEFAULT '',
  INSPECTION_PART_DESC_SHORT VARCHAR(10),
  INSPECTION_PART_DESC_LONG VARCHAR(30),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL179_PK PRIMARY KEY
    (INSPECTION_PART_NAME)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL179TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL179TBX IS 'RMT InspectionPart for QICS';

CREATE TRIGGER GALADM.GAL179_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL179TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL179_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL179TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;