DROP TRIGGER GALADM.GAL108_TR2;
DROP TRIGGER GALADM.GAL108_TR1;
DROP TABLE GALADM.GAL108TBX;

CREATE TABLE GALADM.GAL108TBX (
  PRODUCT_ID	CHARACTER(17)	NOT NULL	DEFAULT '',
  JOURNAL_BLOCK_MEASUREMENTS	CHARACTER(6),
  JOURNAL_CRANK_MEASUREMENTS	CHARACTER(6),
  CONROD_CRANK_MEASUREMENTS	CHARACTER(6),
  CONROD_CONS_MEASUREMENTS	CHARACTER(6),
  MODEL_YEAR_CODE	CHARACTER(1),
  MODEL_CODE	CHARACTER(3),
  ACTUAL_TIMESTAMP	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
  JOURNAL_UPPER_BEARING01	CHARACTER(30),
  JOURNAL_LOWER_BEARING01	CHARACTER(30),
  JOURNAL_UPPER_BEARING02	CHARACTER(30),
  JOURNAL_LOWER_BEARING02	CHARACTER(30),
  JOURNAL_UPPER_BEARING03	CHARACTER(30),
  JOURNAL_LOWER_BEARING03	CHARACTER(30),
  JOURNAL_UPPER_BEARING04	CHARACTER(30),
  JOURNAL_LOWER_BEARING04	CHARACTER(30),
  JOURNAL_UPPER_BEARING05	CHARACTER(30),
  JOURNAL_LOWER_BEARING05	CHARACTER(30),
  JOURNAL_UPPER_BEARING06	CHARACTER(30),
  JOURNAL_LOWER_BEARING06	CHARACTER(30),
  CONROD_UPPER_BEARING01	CHARACTER(30),
  CONROD_LOWER_BEARING01	CHARACTER(30),
  CONROD_UPPER_BEARING02	CHARACTER(30),
  CONROD_LOWER_BEARING02	CHARACTER(30),
  CONROD_UPPER_BEARING03	CHARACTER(30),
  CONROD_LOWER_BEARING03	CHARACTER(30),
  CONROD_UPPER_BEARING04	CHARACTER(30),
  CONROD_LOWER_BEARING04	CHARACTER(30),
  CONROD_UPPER_BEARING05	CHARACTER(30),
  CONROD_LOWER_BEARING05	CHARACTER(30),
  CONROD_UPPER_BEARING06	CHARACTER(30),
  CONROD_LOWER_BEARING06	CHARACTER(30),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL108_PK PRIMARY KEY
    (PRODUCT_ID, ACTUAL_TIMESTAMP)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL108TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL108TBX IS 'RMT BearingSelectResult for tracking bearing used in a specific engine';
    
CREATE TRIGGER GALADM.GAL108_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL108TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL108_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL108TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL108_I1
  ON GALADM.GAL108TBX
    ( ACTUAL_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
