DROP TRIGGER GALADM.GAL176_TR2;
DROP TRIGGER GALADM.GAL176_TR1;
DROP TABLE GALADM.GAL176TBX;

CREATE TABLE GALADM.GAL176TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  LINE_ID CHARACTER(16),
  NEXT_PRODUCT_ID CHARACTER(17),
  PRODUCT_SPEC_CODE CHARACTER(22),
  PRODUCTION_LOT CHARACTER(20),
  PLAN_OFF_DATE DATE,
  LAST_PASSING_PROCESS_POINT_ID CHARACTER(16),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL176_PK PRIMARY KEY
    (PRODUCT_ID)
)
  IN GALTBSDAT5
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL176TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL176TBX IS 'RMT InProcessProduct for LINE CONTROL';

CREATE TRIGGER GALADM.GAL176_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL176TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL176_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL176TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL176_I1
  ON GALADM.GAL176TBX
    ( NEXT_PRODUCT_ID ASC, LINE_ID ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL176_I2
  ON GALADM.GAL176TBX
    ( NEXT_PRODUCT_ID ASC, PRODUCT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL176_I3
  ON GALADM.GAL176TBX
    ( LINE_ID ASC, CREATE_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;