DROP TRIGGER GALADM.GAL195_TR2;
DROP TRIGGER GALADM.GAL195_TR1;
DROP TABLE GALADM.GAL195TBX;

CREATE TABLE GALADM.GAL195TBX (
  LINE_ID CHARACTER(16) NOT NULL DEFAULT '',
  SITE_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_NAME CHARACTER(16) NOT NULL DEFAULT '',
  DIVISION_ID CHARACTER(16),
  DIVISION_NAME CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_NAME1 CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_NAME2 CHARACTER(32) NOT NULL DEFAULT '',
  LINE_NAME CHARACTER(32) NOT NULL DEFAULT '',
  LINE_TYPE INTEGER,
  LINE_DESCRIPTION CHARACTER(128),
  ENTRY_PROCESS_POINT_ID CHARACTER(16),
  LINE_SEQUENCE_NUMBER INTEGER,
  STD_INVENTORY INTEGER,
  MAXIMUM_INVENTORY INTEGER,
  MINIMUM_INVENTORY INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL195_PK PRIMARY KEY
    (LINE_ID)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL195TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL195TBX IS 'RMT Line';

CREATE TRIGGER GALADM.GAL195_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL195TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL195_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL195TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL195_I1
  ON GALADM.GAL195TBX
    ( LINE_ID ASC )
  INCLUDE ( DIVISION_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL195_I2
  ON GALADM.GAL195TBX
    ( DIVISION_ID ASC, LINE_ID DESC )
  ALLOW REVERSE SCANS
  COMPRESS NO;