DROP TRIGGER GALADM.GAL180_TR2;
DROP TRIGGER GALADM.GAL180_TR1;
DROP TABLE GALADM.GAL180TBX;

CREATE TABLE GALADM.GAL180TBX (
  INSPECTION_PART_NAME VARCHAR(32) NOT NULL DEFAULT '',
  INSPECTION_PART_LOCATION_NAME VARCHAR(20) NOT NULL DEFAULT '',
  PART_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DESCRIPTION_ID INTEGER NOT NULL DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL180_PK PRIMARY KEY
    (PART_GROUP_NAME, INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL180TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL180TBX IS 'RMT InspectionPartDescription for QICS';

CREATE TRIGGER GALADM.GAL180_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL180TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL180_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL180TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL180_I1
  ON GALADM.GAL180TBX
    ( DESCRIPTION_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE UNIQUE INDEX GALADM.GAL180_I2
  ON GALADM.GAL180TBX
    ( INSPECTION_PART_NAME ASC, INSPECTION_PART_LOCATION_NAME ASC, PART_GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;