DROP TRIGGER GALADM.GAL119_TR2;
DROP TRIGGER GALADM.GAL119_TR1;
DROP TABLE GALADM.GAL119TBX;

CREATE TABLE GALADM.GAL119TBX (
  PASSING_COUNTER	INTEGER,
  PROCESS_POINT_ID	CHARACTER(16)	NOT NULL	DEFAULT '',
  PRODUCTION_DATE	DATE	NOT NULL	DEFAULT CURRENT_DATE,
  SHIFT	CHARACTER(2)	NOT NULL	DEFAULT '',
  PERIOD	INTEGER	NOT NULL	DEFAULT 0,
  PERIOD_LABEL	CHARACTER(5),
  PRODUCT_SPEC_CODE	CHARACTER(22)	NOT NULL	DEFAULT '',
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL119_PK PRIMARY KEY
    (PROCESS_POINT_ID, PRODUCTION_DATE, SHIFT, PERIOD, PRODUCT_SPEC_CODE)
) 
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL119TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL119TBX IS 'RMT CounterByProductSpec for summarizing number of product specs built by process point, production date, shift, period';

CREATE TRIGGER GALADM.GAL119_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL119TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL119_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL119TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL119_I1
  ON GALADM.GAL119TBX
    ( PROCESS_POINT_ID ASC, PRODUCTION_DATE ASC, PASSING_COUNTER ASC, PRODUCT_SPEC_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
