DROP TRIGGER GALADM.GAL175_TR2;
DROP TRIGGER GALADM.GAL175_TR1;
DROP TABLE GALADM.GAL175TBX;

CREATE TABLE GALADM.GAL175TBX (
  IMAGE_SECTION_ID INTEGER NOT NULL DEFAULT 0,
  POINT_SEQUENCE_NO INTEGER NOT NULL DEFAULT 0,
  POINT_X INTEGER,
  POINT_Y INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL175_PK PRIMARY KEY
    (IMAGE_SECTION_ID, POINT_SEQUENCE_NO)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL175TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL175TBX IS 'RMT ImageSectionPoint for QICS';

CREATE TRIGGER GALADM.GAL175_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL175TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL175_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL175TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL175_I1
  ON GALADM.GAL175TBX
    ( IMAGE_SECTION_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;