DROP TRIGGER GALADM.GAL222_TR2;
DROP TRIGGER GALADM.GAL222_TR1;
DROP TABLE GALADM.GAL222TBX;

CREATE TABLE GALADM.GAL222TBX (
  REPAIR_ID INTEGER NOT NULL DEFAULT 0,
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  DEFECTRESULTID INTEGER NOT NULL DEFAULT 0,
  REPAIR_ASSOCIATE_NO CHARACTER(11),
  ACTUAL_TIMESTAMP TIMESTAMP,
  ACTUAL_PROBLEM_NAME CHARACTER(64),
  REPAIR_METHOD_NAME CHARACTER(64),
  REPAIR_TIME INTEGER,
  REPAIR_DEPT VARCHAR(32),
  REPAIR_PROCESS_POINT_ID CHARACTER(16),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  COMMENT VARCHAR(256),
  CONSTRAINT GAL222_PK PRIMARY KEY
    (REPAIR_ID, PRODUCT_ID, DEFECTRESULTID)
)
  IN GALTBSDAT5
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL222TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL222TBX IS 'RMT DefectRepairResult for QICS to record repairs for each product defect';

CREATE TRIGGER GALADM.GAL222_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL222TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL222_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL222TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL222_I1
  ON GALADM.GAL222TBX
    ( DEFECTRESULTID ASC, PRODUCT_ID ASC, ACTUAL_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL222_I2
  ON GALADM.GAL222TBX
    ( REPAIR_PROCESS_POINT_ID ASC, DEFECTRESULTID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;