DROP TRIGGER GALADM.GAL208_TR2;
DROP TRIGGER GALADM.GAL208_TR1;
DROP TABLE GALADM.GAL208TBX;

CREATE TABLE GALADM.GAL208TBX (
  PART_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT '',
  PART_GROUP_DESCRIPTION_SHORT VARCHAR(10),
  PART_GROUP_DESCRIPTION_LONG VARCHAR(30),
  MODEL_CODE CHARACTER(3),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL208_PK PRIMARY KEY
    (PART_GROUP_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL208TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL208TBX IS 'RMT PartGroup for QICS';

CREATE TRIGGER GALADM.GAL208_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL208TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL208_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL208TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;