DROP TRIGGER GALADM.GAL226_TR4;
DROP TRIGGER GALADM.GAL226_TR3;
DROP TRIGGER GALADM.GAL226_TR2;
DROP TRIGGER GALADM.GAL226_TR1;
DROP TABLE GALADM.GAL226TBX;

CREATE TABLE GALADM.GAL226TBX (
  LINE_NO CHARACTER(2) NOT NULL DEFAULT '',
  PROCESS_LOCATION CHARACTER(2) NOT NULL DEFAULT '',
  PLANT_CODE CHARACTER(4) NOT NULL DEFAULT '',
  DAY_OF_WEEK CHARACTER(3),
  PRODUCTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  SHIFT CHARACTER(2) NOT NULL DEFAULT '',
  PERIOD INTEGER NOT NULL DEFAULT 0,
  PERIOD_LABEL CHARACTER(5),
  TYPE CHARACTER(3),
  PLAN CHARACTER(1),
  START_TIME TIME,
  END_TIME TIME,
  NEXT_DAY SMALLINT,
  CAPACITY INTEGER DEFAULT 0,
  CAPACITY_ON INTEGER DEFAULT 0,
  PLAN_CODE CHARACTER(11),
  WEEK_NO CHARACTER(6),
  ISWORK CHARACTER(1),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  START_TIMESTAMP TIMESTAMP,
  END_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL226_PK PRIMARY KEY
    (LINE_NO, PROCESS_LOCATION, PLANT_CODE, PRODUCTION_DATE, SHIFT, PERIOD)
)
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL226TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL226TBX IS
   'RMT DailyDepartmentSchedule for LINE CONTROL to define production working periods per GPCS Plan Code';

CREATE TRIGGER GALADM.GAL226_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL226TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL226_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL226TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL226_TR3
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL226TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET START_TIMESTAMP =
       CASE
          WHEN A.next_day = 1 AND A.start_time < A.end_time
          THEN
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date + 1 DAYS)),
                        1,
                        11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.start_time)), 12, 9)
             || '000000'
          ELSE
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date)), 1, 11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.start_time)), 12, 9)
             || '000000'
       END,
    END_TIMESTAMP =
       CASE
          WHEN A.next_day = 0
          THEN
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date)), 1, 11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.end_time)), 12, 9)
             || '999999'
          ELSE
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date + 1 DAYS)),
                        1,
                        11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.end_time)), 12, 9)
             || '999999'
       END;

CREATE TRIGGER GALADM.GAL226_TR4
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL226TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET START_TIMESTAMP =
       CASE
          WHEN A.next_day = 1 AND A.start_time < A.end_time
          THEN
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date + 1 DAYS)),
                        1,
                        11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.start_time)), 12, 9)
             || '000000'
          ELSE
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date)), 1, 11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.start_time)), 12, 9)
             || '000000'
       END,
    END_TIMESTAMP =
       CASE
          WHEN A.next_day = 0
          THEN
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date)), 1, 11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.end_time)), 12, 9)
             || '999999'
          ELSE
                SUBSTR (CHAR (TIMESTAMP_ISO (A.production_date + 1 DAYS)),
                        1,
                        11)
             || SUBSTR (CHAR (TIMESTAMP_ISO (A.end_time)), 12, 9)
             || '999999'
       END;

CREATE INDEX GALADM.GAL226_I1
  ON GALADM.GAL226TBX
    ( PROCESS_LOCATION ASC, PLANT_CODE ASC, LINE_NO ASC, END_TIMESTAMP ASC, START_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL226_I2
  ON GALADM.GAL226TBX
    ( PRODUCTION_DATE ASC, LINE_NO ASC, PROCESS_LOCATION ASC, PLANT_CODE ASC, SHIFT ASC, DAY_OF_WEEK ASC, WEEK_NO ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
