DROP TRIGGER GALADM.GAL240_TR2;
DROP TRIGGER GALADM.GAL240_TR1;
DROP TABLE GALADM.GAL240TBX;

CREATE TABLE GALADM.GAL240TBX (
  PROCESS_POINT_ID CHARACTER(16) NOT NULL DEFAULT '',
  PRODUCTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  SHIFT CHARACTER(2) NOT NULL DEFAULT '',
  PERIOD INTEGER NOT NULL DEFAULT 0,
  PASSING_COUNTER INTEGER,
  PERIOD_LABEL CHARACTER(5),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL240_PK PRIMARY KEY
    (PROCESS_POINT_ID, PRODUCTION_DATE, SHIFT, PERIOD)
)
  IN GALTBSDAT3
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL240TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL240TBX IS 'RMT Counter';

CREATE TRIGGER GALADM.GAL240_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL240TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL240_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL240TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;