DROP TRIGGER GALADM.GAL260_TR2;
DROP TRIGGER GALADM.GAL260_TR1;
DROP TABLE GALADM.GAL260TBX;

CREATE TABLE GALADM.GAL260TBX (
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT '',
  SHIFT CHARACTER(2) NOT NULL DEFAULT '',
  PRODUCTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  FIRST_PRODUCT_ID CHARACTER(17),
  LAST_PRODUCT_ID CHARACTER(17),
  PRODUCT_ID_INSPECT INTEGER,
  PRODUCT_ID_DIRECT_PASSED INTEGER,
  PRODUCT_ID_WITH_DEFECTS INTEGER,
  REPAIRED_PRODUCT_ID INTEGER,
  OUTSTANDING_PRODUCT_ID INTEGER,
  SCRAP INTEGER,
  AVERAGE_DEFECT_PER_PRODUCT_ID DOUBLE,
  STRAIGHT_SHIP_PERCENTAGE DOUBLE,
  ROYAL_STRAIGHT_SHIP_PERCENTAGE DOUBLE,
  TOP_COAT_PASS_RATE DOUBLE,
  REPAIR_PASS_RATE DOUBLE,
  OUTSTANDING_RPU DOUBLE,
  ACTUAL_TIMESTAMP TIMESTAMP,
  PRODUCT_ID_RSSR INTEGER DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  PREHEAT INTEGER,
  CONSTRAINT GAL260_PK PRIMARY KEY
    (APPLICATION_ID, SHIFT, PRODUCTION_DATE)
)
  IN GALTBSDAT5
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL260TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL260TBX IS 'RMT StationResult for QICS Station Result per process point, production date and shift';

CREATE TRIGGER GALADM.GAL260_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL260TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL260_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL260TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;