DROP TRIGGER GALADM.GAL212_TR2;
DROP TRIGGER GALADM.GAL212_TR1;
DROP TABLE GALADM.GAL212TBX;

CREATE TABLE GALADM.GAL212TBX (
  PRODUCTION_LOT CHARACTER(20) NOT NULL DEFAULT '',
  LOT_SIZE INTEGER,
  START_PRODUCT_ID CHARACTER(17),
  SEND_STATUS INTEGER,
  STAMPED_COUNT INTEGER,
  HOLD_STATUS INTEGER,
  SENT_TIMESTAMP TIMESTAMP,
  NEXT_PRODUCTION_LOT CHARACTER(20),
  LOT_NUMBER CHARACTER(12),
  PLANT_CODE CHARACTER(4),
  PROCESS_LOCATION CHARACTER(2),
  LINE_NO CHARACTER(2),
  PRODUCT_SPEC_CODE CHARACTER(22),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  BUILD_SEQ_NOT_FIXED_FLAG CHARACTER(1),
  BUILD_SEQUENCE_NUMBER CHARACTER(12),
  CONSTRAINT GAL212_PK PRIMARY KEY
    (PRODUCTION_LOT)
)
  IN GALTBSDAT2
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL212TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL212TBX IS 'RMT PreProductionLot for LINE CONTROL';

CREATE TRIGGER GALADM.GAL212_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL212TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL212_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL212TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL212_I1
  ON GALADM.GAL212TBX
    ( NEXT_PRODUCTION_LOT ASC, SEND_STATUS ASC, LOT_SIZE ASC, STAMPED_COUNT ASC, PRODUCTION_LOT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;