DROP TRIGGER GALADM.GAL215_TR2;
DROP TRIGGER GALADM.GAL215_TR1;
DROP TABLE GALADM.GAL215TBX;

CREATE TABLE GALADM.GAL215TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  PROCESS_POINT_ID CHARACTER(16) NOT NULL DEFAULT '',
  ACTUAL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRODUCT_SPEC_CODE CHARACTER(22),
  PRODUCTION_DATE DATE,
  PRODUCTION_LOT CHARACTER(20),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  PROCESS_COUNT INTEGER,
  CONSTRAINT GAL215_PK PRIMARY KEY
    (PRODUCT_ID, PROCESS_POINT_ID, ACTUAL_TIMESTAMP)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL215TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL215TBX IS
   'RMT ProductResult for LINE CONTROL to record history of Product through Process Points';

CREATE TRIGGER GALADM.GAL215_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL215_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL215_I1
  ON GALADM.GAL215TBX
    ( PROCESS_POINT_ID ASC, ACTUAL_TIMESTAMP ASC, PRODUCT_ID ASC )
  INCLUDE ( PRODUCTION_LOT )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL215_I2
  ON GALADM.GAL215TBX
    ( PROCESS_POINT_ID ASC, PRODUCT_ID ASC, ACTUAL_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL215_I3
  ON GALADM.GAL215TBX
    ( PRODUCTION_LOT ASC, PROCESS_POINT_ID ASC, ACTUAL_TIMESTAMP ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;