DROP TRIGGER GALADM.GAL259_TR2;
DROP TRIGGER GALADM.GAL259_TR1;
DROP TABLE GALADM.GAL259TBX;

CREATE TABLE GALADM.GAL259TBX (
  ATTRIBUTE CHARACTER(32) NOT NULL DEFAULT '',
  PRODUCT_SPEC_CODE CHARACTER(30) NOT NULL DEFAULT '',
  ATTRIBUTE_VALUE VARCHAR(512),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  ATTRIBUTE_DESCRIPTION CHARACTER(32),
  CONSTRAINT GAL259_PK PRIMARY KEY
    (ATTRIBUTE, PRODUCT_SPEC_CODE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL259TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL259TBX IS
   'RMT BuildAttribute for LOT CONTROL by Product Spec Code';

CREATE TRIGGER GALADM.GAL259_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL259TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL259_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL259TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;