DROP TRIGGER GALADM.GAL261_TR2;
DROP TRIGGER GALADM.GAL261_TR1;
DROP TABLE GALADM.GAL261TBX;

CREATE TABLE GALADM.GAL261TBX (
  PART_NAME	CHARACTER(32)	NOT NULL	DEFAULT '',
  PART_CONFIRM_CHECK	INTEGER,
  WINDOW_LABEL	CHARACTER(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  PRODUCT_TYPE	CHARACTER(10),
  CONSTRAINT GAL261_PK PRIMARY KEY 
    (PART_NAME)
) 
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL261TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL261TBX IS 'RMT PartName for LOT CONTROL to manage Installed Part';

CREATE TRIGGER GALADM.GAL261_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL261TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL261_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL261TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
