DROP TRIGGER GALADM.GAL234_TR2;
DROP TRIGGER GALADM.GAL234_TR1;
DROP TABLE GALADM.GAL234TBX;

CREATE TABLE GALADM.GAL234TBX (
  HOST_NAME CHARACTER(32) NOT NULL DEFAULT '',
  IP_ADDRESS VARCHAR(255),
  PORT INTEGER,
  ROUTER_PORT INTEGER,
  TERMINAL_DESCRIPTION CHARACTER(128),
  LOCATED_PROCESS_POINT_ID CHARACTER(16),
  DIVISION_ID CHARACTER(16),
  AF_TERMINAL_FLAG SMALLINT,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL234_PK PRIMARY KEY
    (HOST_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL234TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL234TBX IS 'RMT Terminal';

CREATE TRIGGER GALADM.GAL234_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL234TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL234_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL234TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;