DROP TRIGGER GALADM.GAL282_TR2;
DROP TRIGGER GALADM.GAL282_TR1;
DROP TABLE GALADM.GAL282TBX;

CREATE TABLE GALADM.GAL282TBX (
  ROW_INSERT_TSTMP	TIMESTAMP,
  ROW_UPDATE_TSTMP	TIMESTAMP,
  ROW_DISUSE_TSTMP	TIMESTAMP,
  ROW_HISTRC_CNTER	INTEGER,
  ROW_UPDATE_USER	CHARACTER(11),
  USER_ID	CHARACTER(11)	NOT NULL	DEFAULT '',
  SECURITY_GRP	VARCHAR(255)	NOT NULL	DEFAULT '',
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL282_PK PRIMARY KEY 
    (USER_ID, SECURITY_GRP)
) 
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL282TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL282TBX IS 'RMT UserSecurityGroup for SECURITY to manage users to groups';

CREATE TRIGGER GALADM.GAL282_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL282TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL282_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL282TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
