DROP TRIGGER GALADM.GAL211_TR2;
DROP TRIGGER GALADM.GAL211_TR1;
DROP TABLE GALADM.GAL211TBX;

CREATE TABLE GALADM.GAL211TBX (
  SITE_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_LONG_DESCRIPTION CHARACTER(128),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL211_PK PRIMARY KEY
    (SITE_NAME, PLANT_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL211TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL211TBX IS 'RMT Plant';

CREATE TRIGGER GALADM.GAL211_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL211TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL211_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL211TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;