DROP TRIGGER GALADM.GAL287_TR2;
DROP TRIGGER GALADM.GAL287_TR1;
DROP TABLE GALADM.GAL287TBX;

CREATE TABLE GALADM.GAL287TBX (
  CLIENT_ID CHARACTER(32) NOT NULL DEFAULT '',
  NODENUMBER INTEGER NOT NULL DEFAULT 0,
  NODENAME CHARACTER(32),
  PARENTNODENUMBER INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL287_PK PRIMARY KEY
    ( CLIENT_ID, NODENUMBER )
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL287TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL287TBX IS
   'RMT ApplicationMenuEntry for managing Menu Items on Terminals';

CREATE TRIGGER GALADM.GAL287_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL287TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL287_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL287TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;