DROP TRIGGER GALADM.GAL294_TR2;
DROP TRIGGER GALADM.GAL294_TR1;
DROP TABLE GALADM.GAL294TBX;

CREATE TABLE GALADM.GAL294TBX (
  FORM_ID CHARACTER(32) NOT NULL,
  DESTINATION_ID CHARACTER(32) NOT NULL,
  DEFAULT_FLAG INTEGER NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL294_PK PRIMARY KEY
    ( FORM_ID, DESTINATION_ID )
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL294TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL294TBX IS
   'RMT PrintForm for LOT CONTROL to manage forms to printers';

CREATE TRIGGER GALADM.GAL294_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL294TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL294_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL294TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;