DROP TRIGGER GALADM.GAL205_TR2;
DROP TRIGGER GALADM.GAL205_TR1;
DROP TABLE GALADM.GAL205TBX;

CREATE TABLE GALADM.GAL205TBX (
  PARKING_NAME VARCHAR(20) NOT NULL DEFAULT '',
  PARKING_ADDRESS_PRIORITY INTEGER,
  VIN CHARACTER(17),
  PARKING_ADDRESS_SPACE INTEGER NOT NULL DEFAULT 0,
  PARKING_ADDRESS_ROW INTEGER NOT NULL DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  PARKING_ADDRESS_ROW_NAME VARCHAR(20),
  CONSTRAINT GAL205_PK PRIMARY KEY
    (PARKING_NAME, PARKING_ADDRESS_SPACE, PARKING_ADDRESS_ROW)
)
  IN GALTBSDAT9
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL205TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL205TBX IS 'RMT ParkingAddress';

CREATE TRIGGER GALADM.GAL205_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL205TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL205_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL205TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;