DROP TRIGGER GALADM.GAL237_TR2;
DROP TRIGGER GALADM.GAL237_TR1;
DROP TABLE GALADM.GAL237TBX;

CREATE TABLE GALADM.GAL237TBX (
  GPCS_PLANT_CODE CHARACTER(4),
  SITE_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_NAME CHARACTER(16) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL237_PK PRIMARY KEY
    (SITE_NAME, PLANT_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL237TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL237TBX IS 'RMT GpcsPlant';

CREATE TRIGGER GALADM.GAL237_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL237TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL237_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL237TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;