DROP TRIGGER GALADM.GAL235_TR2;
DROP TRIGGER GALADM.GAL235_TR1;
DROP TABLE GALADM.GAL235TBX;

CREATE TABLE GALADM.GAL235TBX (
  ZONE_ID CHARACTER(16) NOT NULL DEFAULT '',
  DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '',
  ZONE_NAME CHARACTER(32) NOT NULL DEFAULT '',
  ZONE_DESCRIPTION CHARACTER(128),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL235_PK PRIMARY KEY
    (ZONE_ID)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL235TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL235TBX IS 'RMT Zone';

CREATE TRIGGER GALADM.GAL235_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL235TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL235_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL235TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;