DROP TRIGGER GALADM.GAL253_TR2;
DROP TRIGGER GALADM.GAL253_TR1;
DROP TABLE GALADM.GAL253TBX;

CREATE TABLE GALADM.GAL253TBX (
  CLIENT_ID CHARACTER(32) NOT NULL DEFAULT '',
  ALIAS_NAME CHARACTER(64),
  DEVICE_TYPE INTEGER,
  DEVICE_DESCRIPTION CHARACTER(128),
  EIF_IP_ADDRESS VARCHAR(255),
  EIF_PORT INTEGER,
  IO_PROCESS_POINT_ID CHARACTER(16),
  DIVISION_ID CHARACTER(16),
  REPLY_CLIENT_ID CHARACTER(32),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL253_PK PRIMARY KEY
    (CLIENT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL253TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL253TBX IS 'RMT Device for LOT CONTROL';

CREATE TRIGGER GALADM.GAL253_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL253TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL253_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL253TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;