DROP TRIGGER GALADM.GAL246_TR2;
DROP TRIGGER GALADM.GAL246_TR1;
DROP TABLE GALADM.GAL246TBX;

CREATE TABLE GALADM.GAL246TBX (
  PROCESS_POINT_ID CHARACTER(16) NOT NULL DEFAULT '',
  MODEL_YEAR_CODE CHARACTER(1) NOT NULL DEFAULT '',
  MODEL_CODE CHARACTER(3) NOT NULL DEFAULT '',
  MODEL_TYPE_CODE CHARACTER(3) NOT NULL DEFAULT '',
  MODEL_OPTION_CODE CHARACTER(3) NOT NULL DEFAULT '',
  INT_COLOR_CODE CHARACTER(2) NOT NULL DEFAULT '',
  EXT_COLOR_CODE CHARACTER(10) NOT NULL DEFAULT '',
  PART_NAME CHARACTER(32) NOT NULL DEFAULT '',
  SEQUENCE_NUMBER INTEGER,
  EXPECTED_INSTALL_TIME INTEGER,
  VERIFICATION_FLAG INTEGER,
  SERIAL_NUMBER_SCAN_FLAG INTEGER,
  INSTRUCTION_CODE CHARACTER(2),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  STRATEGY VARCHAR(256),
  SUB_ID CHARACTER(2),
  DEVICE_ID CHARACTER(16),
  SERIAL_NUMBER_UNIQUE_FLAG INTEGER,
  CONSTRAINT GAL246_PK PRIMARY KEY
    (PROCESS_POINT_ID, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, INT_COLOR_CODE, EXT_COLOR_CODE, PART_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL246TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL246TBX IS
   'RMT LotControlRule for LOT CONTROL to define Installed Part rules per Process Point and Product Spec Code';

CREATE TRIGGER GALADM.GAL246_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL246TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL246_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL246TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL246_I1
  ON GALADM.GAL246TBX
    ( MODEL_CODE ASC, MODEL_YEAR_CODE ASC, SEQUENCE_NUMBER ASC, PROCESS_POINT_ID ASC, PART_NAME ASC, MODEL_TYPE_CODE ASC, MODEL_OPTION_CODE ASC, INT_COLOR_CODE ASC, EXT_COLOR_CODE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;