DROP TRIGGER GALADM.GAL224_TR2;
DROP TRIGGER GALADM.GAL224_TR1;
DROP TABLE GALADM.GAL224TBX;

CREATE TABLE GALADM.GAL224TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  PRODUCTION_DATE DATE,
  ACTUAL_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ASSOCIATE_NO CHARACTER(11),
  REUSE_VIN_REASON VARCHAR(80),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL224_PK PRIMARY KEY
    (PRODUCT_ID, ACTUAL_TIMESTAMP)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL224TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL224TBX IS 'RMT ReuseProductResult';

CREATE TRIGGER GALADM.GAL224_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL224TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL224_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL224TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;