DROP TRIGGER GALADM.GAL243_TR2;
DROP TRIGGER GALADM.GAL243_TR1;
DROP TABLE GALADM.GAL243TBX;

CREATE TABLE GALADM.GAL243TBX (
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT '',
  JNDI_NAME CHARACTER(128),
  TASK_NAME CHARACTER(32) NOT NULL DEFAULT '',
  SEQUENCE_NO INTEGER,
  INPUT_EVENT_EXIST_FLAG SMALLINT,
  BEGIN_FLAG SMALLINT,
  COMMIT_FLAG SMALLINT,
  STATEFULL_SESSION_BEAN_FLAG SMALLINT,
  ARGUMENT CHARACTER(128),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL243_PK PRIMARY KEY
    (APPLICATION_ID, TASK_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL243TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL243TBX IS 'RMT ApplicationTask';

CREATE TRIGGER GALADM.GAL243_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL243TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL243_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL243TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;