DROP TRIGGER GALADM.GAL263_TR2;
DROP TRIGGER GALADM.GAL263_TR1;
DROP TABLE GALADM.GAL263TBX;

CREATE TABLE GALADM.GAL263TBX (
  VIN	CHARACTER(17)	NOT NULL	DEFAULT '',
  STATUS	INTEGER,
  ACTUAL_TIMESTAMP	TIMESTAMP,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  INVOICED	CHARACTER(1)	NOT NULL	DEFAULT 'N',
  ON_TIME_SHIPPING	SMALLINT,
  APPC70A_EMISSION_FLAG	CHARACTER(1),
  APPC70A_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL263_PK PRIMARY KEY 
    (VIN)
) 
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL263TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL263TBX IS 'RMT ShippingStatus for LINE CONTROL to manage FRAME (Vin) shipping status';

CREATE TRIGGER GALADM.GAL263_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL263TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL263_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL263TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL263_I1
  ON GALADM.GAL263TBX
    ( STATUS ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
