DROP TRIGGER GALADM.GAL214_TR2;
DROP TRIGGER GALADM.GAL214_TR1;
DROP TABLE GALADM.GAL214TBX;

CREATE TABLE GALADM.GAL214TBX (
  PROCESS_POINT_NAME CHARACTER(32) NOT NULL DEFAULT '',
  PROCESS_POINT_ID CHARACTER(16) NOT NULL DEFAULT '',
  PROCESS_POINT_DESCRIPTION CHARACTER(128),
  PROCESS_POINT_TYPE INTEGER,
  SITE_NAME CHARACTER(16) NOT NULL DEFAULT '',
  PLANT_NAME CHARACTER(16) NOT NULL DEFAULT '',
  DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '',
  DIVISION_NAME CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_NAME1 CHARACTER(32) NOT NULL DEFAULT '',
  DIVISION_NAME2 CHARACTER(32) NOT NULL DEFAULT '',
  LINE_ID CHARACTER(16) NOT NULL DEFAULT '',
  LINE_NAME CHARACTER(32) NOT NULL DEFAULT '',
  BACK_FILL_PROCESS_POINT_ID CHARACTER(16),
  SEQUENCE_NUMBER INTEGER,
  TRACKING_POINT_FLAG SMALLINT,
  RECOVERY_POINT_FLAG SMALLINT,
  PASSING_COUNT_FLAG SMALLINT,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CURRENT_PROD_LOT CHARACTER(20),
  CONSTRAINT GAL214_PK PRIMARY KEY
    (PROCESS_POINT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL214TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL214TBX IS 'RMT ProcessPoint';

CREATE TRIGGER GALADM.GAL214_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL214TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL214_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL214TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL214_I1
  ON GALADM.GAL214TBX
    ( PROCESS_POINT_ID ASC, PROCESS_POINT_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE INDEX GALADM.GAL214_I2
  ON GALADM.GAL214TBX
    ( LINE_ID ASC, PROCESS_POINT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE INDEX GALADM.GAL214_I3
  ON GALADM.GAL214TBX
    ( LINE_ID ASC, PROCESS_POINT_NAME ASC, PROCESS_POINT_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;
  
CREATE UNIQUE INDEX GALADM.GAL214_I4
  ON GALADM.GAL214TBX
    ( PROCESS_POINT_ID ASC )
  INCLUDE ( DIVISION_ID, LINE_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;