DROP TRIGGER GALADM.GAL283_TR2;
DROP TRIGGER GALADM.GAL283_TR1;
DROP TABLE GALADM.GAL283TBX;

CREATE TABLE GALADM.GAL283TBX (
  SCREEN_ID	CHARACTER(16)	NOT NULL	DEFAULT '',
  SECURITY_GRP	VARCHAR(255)	NOT NULL	DEFAULT '',
  OPERATION	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT GAL283_PK PRIMARY KEY 
    (SCREEN_ID, SECURITY_GRP)
) 
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL283TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL283TBX IS 'RMT AccessControlEntry for SECURITY to manage access to Terminal Applications (Screen ID)';

CREATE TRIGGER GALADM.GAL283_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL283TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL283_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL283TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;
