DROP TRIGGER GALADM.GAL217_TR2;
DROP TRIGGER GALADM.GAL217_TR1;
DROP TABLE GALADM.GAL217TBX;

CREATE TABLE GALADM.GAL217TBX (
  PRODUCTION_LOT CHARACTER(20) NOT NULL DEFAULT '',
  PLAN_CODE CHARACTER(11),
  LINE_NO CHARACTER(2),
  PROCESS_LOCATION CHARACTER(2),
  WE_LINE_NO CHARACTER(2),
  WE_PROCESS_LOCATION CHARACTER(2),
  PA_LINE_NO CHARACTER(2),
  PA_PROCESS_LOCATION CHARACTER(2),
  PRODUCT_SPEC_CODE CHARACTER(22),
  KD_LOT_NUMBER CHARACTER(18),
  START_PRODUCT_ID CHARACTER(17),
  LOT_SIZE INTEGER,
  DEMAND_TYPE CHARACTER(2),
  PLAN_OFF_DATE DATE,
  PRODUCTION_DATE DATE,
  LOT_PASS_FLAG SMALLINT,
  LOT_NUMBER CHARACTER(12),
  PLANT_CODE CHARACTER(4),
  LOT_STATUS INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  PROD_LOT_KD CHARACTER(20),
  CONSTRAINT GAL217_PK PRIMARY KEY
    (PRODUCTION_LOT)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL217TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL217TBX IS 'RMT ProductionLot';

CREATE TRIGGER GALADM.GAL217_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL217TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL217_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL217TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL217_I1
  ON GALADM.GAL217TBX
    ( PRODUCTION_LOT ASC )
  INCLUDE ( PLANT_CODE )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL217_I2
  ON GALADM.GAL217TBX
    ( PROD_LOT_KD ASC, LOT_SIZE ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL217_I3
  ON GALADM.GAL217TBX
    ( PROD_LOT_KD ASC, PRODUCTION_LOT ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;