DROP TRIGGER GALADM.GAL219_TR2;
DROP TRIGGER GALADM.GAL219_TR1;
DROP TABLE GALADM.GAL219TBX;

CREATE TABLE GALADM.GAL219TBX (
  REGRESSION_CODE CHARACTER(32) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL219_PK PRIMARY KEY
    (REGRESSION_CODE)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL219TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL219TBX IS 'RMT Regression';

CREATE TRIGGER GALADM.GAL219_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL219TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL219_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL219TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;