DROP TRIGGER GALADM.GAL245_TR2;
DROP TRIGGER GALADM.GAL245_TR1;
DROP TABLE GALADM.GAL245TBX;

CREATE TABLE GALADM.GAL245TBX (
  PART_ID CHARACTER(5) NOT NULL DEFAULT '',
  PART_NAME CHARACTER(32) NOT NULL DEFAULT '',
  MODEL_YEAR_CODE CHARACTER(1) NOT NULL DEFAULT '',
  MODEL_CODE CHARACTER(3) NOT NULL DEFAULT '',
  MODEL_TYPE_CODE CHARACTER(3) NOT NULL DEFAULT '',
  MODEL_OPTION_CODE CHARACTER(3) NOT NULL DEFAULT '',
  EXT_COLOR_CODE CHARACTER(10) NOT NULL DEFAULT '',
  INT_COLOR_CODE CHARACTER(2) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL245_PK PRIMARY KEY
    (PART_ID, PART_NAME, MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, MODEL_OPTION_CODE, EXT_COLOR_CODE, INT_COLOR_CODE)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL245TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL245TBX IS
   'RMT PartByProductSpecCode for LOT CONTROL to define Installed Part IDs per Product Spec Code';

CREATE TRIGGER GALADM.GAL245_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL245TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL245_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL245TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;