DROP TRIGGER GALADM.GAL258_TR2;
DROP TRIGGER GALADM.GAL258_TR1;
DROP TABLE GALADM.GAL258TBX;

CREATE TABLE GALADM.GAL258TBX (
  FORMID CHARACTER(32) NOT NULL DEFAULT ,
  ATTRIBUTE CHARACTER(32) NOT NULL DEFAULT ,
  OFFSET INTEGER,
  LENGTH INTEGER,
  ATTRIBUTE_TYPE INTEGER,
  ATTRIBUTE_VALUE VARCHAR(1024),
  SEQUENCE_NUMBER INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL258_PK PRIMARY KEY
    (FORMID, ATTRIBUTE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL258TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL258TBX IS 'RMT PrintAttributeFormat for LOT CONTROL by Form';

CREATE TRIGGER GALADM.GAL258_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL258TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL258_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL258TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;