DROP TRIGGER GALADM.GAL242_TR2;
DROP TRIGGER GALADM.GAL242_TR1;
DROP TABLE GALADM.GAL242TBX;

CREATE TABLE GALADM.GAL242TBX (
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT '',
  HOST_NAME CHARACTER(32) NOT NULL DEFAULT '',
  DEFAULT_APPLICATION_FLAG SMALLINT,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL242_PK PRIMARY KEY
    (APPLICATION_ID, HOST_NAME)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL242TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL242TBX IS 'RMT ApplicationByTerminal';

CREATE TRIGGER GALADM.GAL242_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL242_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL242TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;