DROP TRIGGER GALADM.GAL216_TR2;
DROP TRIGGER GALADM.GAL216_TR1;
DROP TABLE GALADM.GAL216TBX;

CREATE TABLE GALADM.GAL216TBX (
  PRODUCTION_LOT CHARACTER(20) NOT NULL DEFAULT '',
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  STAMPING_SEQUENCE_NO INTEGER,
  SEND_STATUS INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL216_PK PRIMARY KEY
    (PRODUCTION_LOT, PRODUCT_ID)
)
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL216TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL216TBX IS 'RMT ProductStampingSequence';

CREATE TRIGGER GALADM.GAL216_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL216TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL216_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL216TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;