DROP TRIGGER GALADM.GAL227_TR2;
DROP TRIGGER GALADM.GAL227_TR1;
DROP TABLE GALADM.GAL227TBX;

CREATE TABLE GALADM.GAL227TBX (
  SECONDARY_PART_NAME VARCHAR(20) NOT NULL DEFAULT '',
  SECONDARY_PART_DESC_SHORT VARCHAR(10),
  SECONDARY_PART_DESC_LONG VARCHAR(30),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL227_PK PRIMARY KEY
    (SECONDARY_PART_NAME)
)
  IN GALTBSDAT10
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL227TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL227TBX IS 'RMT SecondaryPart for QICS';

CREATE TRIGGER GALADM.GAL227_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL227TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL227_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL227TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;