DROP TRIGGER GALADM.GAL236_TR2;
DROP TRIGGER GALADM.GAL236_TR1;
DROP TABLE GALADM.GAL236TBX;

CREATE TABLE GALADM.GAL236TBX (
  LINE_ID CHARACTER(16) NOT NULL DEFAULT '',
  PREVIOUS_LINE_ID CHARACTER(16) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL236_PK PRIMARY KEY
    (LINE_ID, PREVIOUS_LINE_ID)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL236TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL236TBX IS 'RMT PreviousLine';

CREATE TRIGGER GALADM.GAL236_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL236TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL236_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL236TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;