DROP TRIGGER GALADM.GAL238_TR2;
DROP TRIGGER GALADM.GAL238_TR1;
DROP TABLE GALADM.GAL238TBX;

CREATE TABLE GALADM.GAL238TBX (
  GPCS_PLANT_CODE CHARACTER(4),
  GPCS_LINE_NO CHARACTER(2),
  GPCS_PROCESS_LOCATION CHARACTER(2),
  DIVISION_ID CHARACTER(16) NOT NULL DEFAULT '',
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL238_PK PRIMARY KEY
    (DIVISION_ID)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL238TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL238TBX IS 'RMT GpcsDivision';

CREATE TRIGGER GALADM.GAL238_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL238TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL238_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL238TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;