DROP TRIGGER GALADM.GAL257_TR2;
DROP TRIGGER GALADM.GAL257_TR1;
DROP TABLE GALADM.GAL257TBX;

CREATE TABLE GALADM.GAL257TBX (
   CLIENT_ID          CHARACTER (32) NOT NULL DEFAULT '',
   TAG                CHARACTER (128) NOT NULL DEFAULT '',
   SEQUENCE_NUMBER    INTEGER,
   OFFSET             INTEGER,
   LENGTH             INTEGER,
   TAG_TYPE           INTEGER,
   TAG_VALUE          VARCHAR (1024),
   CREATE_TIMESTAMP   TIMESTAMP,
   UPDATE_TIMESTAMP   TIMESTAMP,
   TAG_NAME           VARCHAR (512),
   DATA_TYPE          INTEGER,
   CONSTRAINT GAL257_PK PRIMARY KEY
     (CLIENT_ID, TAG)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL257TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL257TBX IS
   'RMT DeviceFormat for LOT CONTROL to configure Device by Client ID';

CREATE TRIGGER GALADM.GAL257_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL257TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL257_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL257TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;