DROP TRIGGER GALADM.GAL241_TR2;
DROP TRIGGER GALADM.GAL241_TR1;
DROP TABLE GALADM.GAL241TBX;

CREATE TABLE GALADM.GAL241TBX (
  APPLICATION_ID CHARACTER(16) NOT NULL DEFAULT '',
  APPLICATION_NAME CHARACTER(35),
  APPLICATION_TYPE INTEGER,
  TERMINAL_APPLICATION_FLAG SMALLINT,
  SCREEN_ID CHARACTER(16),
  WINDOW_TITLE CHARACTER(32),
  SCREEN_CLASS CHARACTER(128),
  APPLICATION_DESCRIPTION CHARACTER(128),
  PRELOAD INTEGER DEFAULT 0,
  SESSION_REQUIRED SMALLINT DEFAULT 0,
  PERSISTENT_SESSION SMALLINT DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL241_PK PRIMARY KEY
    (APPLICATION_ID)
)
  IN GALTBSDAT8
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.GAL241TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL241TBX IS 'RMT Application';

CREATE TRIGGER GALADM.GAL241_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL241_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL241TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;