DROP TRIGGER GALADM.GAL364_TR2;
DROP TRIGGER GALADM.GAL364_TR1;
DROP TABLE GALADM.GAL364TBX;

CREATE TABLE GALADM.GAL364TBX (
  INSPECTION_PART_NAME VARCHAR(32) NOT NULL DEFAULT '',
  INSPECTION_PART_LOCATION_NAME VARCHAR(20) NOT NULL DEFAULT '',
  TWO_PART_PAIR_LOCATION VARCHAR(20) NOT NULL DEFAULT '',
  TWO_PART_PAIR_PART VARCHAR(32) NOT NULL DEFAULT '',
  PART_GROUP_NAME VARCHAR(20) NOT NULL DEFAULT 'TWO PART PAIR',
  DESCRIPTION_ID INTEGER NOT NULL DEFAULT 0,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL364_PK PRIMARY KEY
    ( INSPECTION_PART_NAME , INSPECTION_PART_LOCATION_NAME , TWO_PART_PAIR_LOCATION , PART_GROUP_NAME , TWO_PART_PAIR_PART )

)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL364TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL364TBX IS
   'RMT InspectionTwoPartDescription for QICS';

CREATE TRIGGER GALADM.GAL364_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL364TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL364_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL364TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL364_I1
  ON GALADM.GAL364TBX
    ( DESCRIPTION_ID ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;