DROP TRIGGER GALADM.GAL322_TR2;
DROP TRIGGER GALADM.GAL322_TR1;
DROP TABLE GALADM.GAL322TBX;

CREATE TABLE GALADM.GAL322TBX (
  INSPECTION_PART_NAME VARCHAR(32) NOT NULL DEFAULT '',
  INSPECTION_PART_LOCATION_NAME VARCHAR(20) NOT NULL DEFAULT '',
  DEFECT_TYPE_NAME VARCHAR(45) NOT NULL DEFAULT '',
  SECONDARY_PART_NAME VARCHAR(20) NOT NULL,
  TWO_PART_PAIR_PART VARCHAR(32) NOT NULL,
  TWO_PART_PAIR_LOCATION VARCHAR(20) NOT NULL,
  PART_GROUP_NAME CHARACTER(20) NOT NULL DEFAULT '',
  IQS_CATEGORY_NAME CHARACTER(32),
  IQS_ITEM_NAME CHARACTER(64),
  REGRESSION_CODE CHARACTER(32),
  LOCK_MODE SMALLINT,
  RESPONSIBLE_DEPT VARCHAR(32),
  RESPONSIBLE_ZONE VARCHAR(32),
  TWO_PART_DEFECT_FLAG SMALLINT,
  INVENTORY_REPAIR_TIME INTEGER,
  ONLINE_REPAIR_TIME INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  RESPONSIBLE_LINE VARCHAR(32),
  ENGINE_FIRING_FLAG SMALLINT NOT NULL DEFAULT 0,
  REPAIR_AREA CHARACTER(20),
  REPAIR_DEPARTMENT CHARACTER(32),
  CONSTRAINT GAL322_PK PRIMARY KEY
    (INSPECTION_PART_NAME, INSPECTION_PART_LOCATION_NAME, DEFECT_TYPE_NAME,
     TWO_PART_PAIR_PART, TWO_PART_PAIR_LOCATION, SECONDARY_PART_NAME, PART_GROUP_NAME)
)
  IN GALTBSDAT5
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.GAL322TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL322TBX IS 'RMT DefectDescription for QICS';

CREATE TRIGGER GALADM.GAL322_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL322TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL322_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL322TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL322_I1
  ON GALADM.GAL322TBX
    ( INSPECTION_PART_NAME ASC, TWO_PART_PAIR_PART ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.GAL322_I2
  ON GALADM.GAL322TBX
    ( INSPECTION_PART_NAME ASC, DEFECT_TYPE_NAME ASC, INSPECTION_PART_LOCATION_NAME ASC, SECONDARY_PART_NAME ASC, RESPONSIBLE_ZONE ASC, RESPONSIBLE_DEPT ASC, REGRESSION_CODE ASC, IQS_ITEM_NAME ASC, IQS_CATEGORY_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;