DROP TRIGGER GALADM.GAL324_TR2;
DROP TRIGGER GALADM.GAL324_TR1;
DROP TABLE GALADM.GAL324TBX;

CREATE TABLE GALADM.GAL324TBX (
  SECURITY_GRP VARCHAR(255) NOT NULL,
  GROUP_NAME VARCHAR(64) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL324_PK PRIMARY KEY
    (SECURITY_GRP)
)
  IN GALTBSREF11
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GAL324TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL324TBX IS 'RMT SecurityGroup for SECURITY';

CREATE TRIGGER GALADM.GAL324_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL324TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL324_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL324TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL324_I1
  ON GALADM.GAL324TBX
    ( SECURITY_GRP ASC, GROUP_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;