DROP TRIGGER GALADM.GAL489_TR2;
DROP TRIGGER GALADM.GAL489_TR1;
DROP TABLE GALADM.GAL489TBX;

CREATE TABLE GALADM.GAL489TBX (
  COMPONENT_ID VARCHAR(40) NOT NULL,
  PROPERTY_KEY VARCHAR(64) NOT NULL,
  PROPERTY_VALUE VARCHAR(1024) NOT NULL,
  DESCRIPTION VARCHAR(64),
  CHANGE_USER_ID VARCHAR(32),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL489_PK PRIMARY KEY
    (COMPONENT_ID, PROPERTY_KEY)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL489TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL489TBX IS
   'RMT ComponentProperty for managing application properties';

CREATE TRIGGER GALADM.GAL489_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL489_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL489TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX GALADM.GAL489_I1
  ON GALADM.GAL489TBX
    ( PROPERTY_KEY ASC, COMPONENT_ID DESC )
  ALLOW REVERSE SCANS
  COMPRESS NO;