DROP TRIGGER GALADM.GAL650_TR2;
DROP TRIGGER GALADM.GAL650_TR1;
DROP TABLE GALADM.GAL650TBX;

CREATE TABLE GALADM.GAL650TBX (
  ID BIGINT NOT NULL,
  DATA_READY_TAG VARCHAR(128) NOT NULL,
  OPC_INSTANCE_NAME VARCHAR(32),
  ENABLED INTEGER,
  NEEDS_LISTENER INTEGER NOT NULL,
  DEVICE_ID VARCHAR(32),
  REPLY_DATA_READY_TAG VARCHAR(128),
  SERVER_URL VARCHAR(256),
  SERVER_CLIENT_TYPE INTEGER NOT NULL DEFAULT 1,
  SERVER_CLIENT_MODE INTEGER NOT NULL DEFAULT 1,
  LISTENER_CLASS VARCHAR(256),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  READ_SOURCE SMALLINT NOT NULL DEFAULT 1,
  PROCESS_COMPLETE_TAG VARCHAR(128),
  CONSTRAINT GAL650_PK PRIMARY KEY
    (ID)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL650TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL650TBX IS
   'RMT OpcConfigEntry for LOT CONTROL to manage OPC EI configuration';

CREATE TRIGGER GALADM.GAL650_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL650TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL650_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL650TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.GAL650I1
  ON GALADM.GAL650TBX
    ( DATA_READY_TAG ASC, OPC_INSTANCE_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;