DROP TRIGGER GALADM.GAL601_TR2;
DROP TRIGGER GALADM.GAL601_TR1;
DROP TABLE GALADM.GAL601TBX;

CREATE TABLE GALADM.GAL601TBX (
  GROUP_ID VARCHAR(32) NOT NULL,
  GROUP_DESC VARCHAR(64),
  DISPLAY_NAME VARCHAR(64),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL601_PK PRIMARY KEY
    (GROUP_ID)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL601TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL601TBX IS 'RMT AdminGroup for SECURITY';

CREATE TRIGGER GALADM.GAL601_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL601TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL601_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL601TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;