DROP TRIGGER GALADM.GAL602_TR2;
DROP TRIGGER GALADM.GAL602_TR1;
DROP TABLE GALADM.GAL602TBX;

CREATE TABLE GALADM.GAL602TBX (
  USER_ID VARCHAR(32) NOT NULL,
  GROUP_ID VARCHAR(32) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL602_PK PRIMARY KEY
    (USER_ID, GROUP_ID)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL602TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL602TBX IS 'RMT AdminUserGroup for SECURITY';

CREATE TRIGGER GALADM.GAL602_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL602TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL602_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL602TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;