DROP TRIGGER GALADM.GAL600_TR2;
DROP TRIGGER GALADM.GAL600_TR1;
DROP TABLE GALADM.GAL600TBX;

CREATE TABLE GALADM.GAL600TBX (
  USER_ID VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(32) FOR BIT DATA,
  USER_DESC VARCHAR(64),
  DISPLAY_NAME VARCHAR(64) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL600_PK PRIMARY KEY
    (USER_ID)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.GAL600TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL600TBX IS 'RMT AdminUser for SECURITY';

CREATE TRIGGER GALADM.GAL600_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL600TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL600_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL600TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;