--*****GALCDB_VER_1.5.0.0_SEQ1.sql*****
--Create QSR_TBX and alter HOLD_PARM_TBX.DEPARTMENT from CHARACTER(2) to VARCHAR(16)

CREATE TABLE GALADM.QSR_TBX  (
	QSR_ID INTEGER NOT NULL , 
	PROCESS_LOCATION VARCHAR(16) , 
	DESCRIPTION VARCHAR(80) , 
	QSR_STATUS INTEGER , 
	COMMENT VARCHAR(80) , 
	APPROVER_NAME VARCHAR(30) , 
	UPDATE_TIMESTAMP TIMESTAMP,
	CREATE_TIMESTAMP TIMESTAMP NOT NULL 
)   

IN GALTBSREF12
INDEX IN GALTBSIDX4;

CREATE UNIQUE INDEX GALADM.QSR_l1 ON GALADM.QSR_TBX (QSR_ID ASC) ALLOW REVERSE SCANS;
ALTER TABLE GALADM.QSR_TBX ADD PRIMARY KEY (QSR_ID);

CREATE TRIGGER GALADM.QSR_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QSR_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QSR_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.QSR_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.QSR_TBX TO GROUP "GALCPR_S";

ALTER TABLE GALADM.HOLD_PARM_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.HOLD_PARM_TBX  
  ALTER COLUMN DEPARTMENT  
    SET DATA TYPE VARCHAR(16); 
     
ALTER TABLE GALADM.HOLD_PARM_TBX 
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GALADM.HOLD_PARM_TR2;
DROP TRIGGER GALADM.HOLD_PARM_TR1;

CREATE TRIGGER GALADM.HOLD_PARM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOLD_PARM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.HOLD_PARM_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.HOLD_PARM_TBX;


--*****GALCDB_VER_1.5.0.0_SEQ2.sql*****
--Create DEFECT_ACTUAL_PROBLEM_TBX and DEFECT_REPAIR_METHOD_TBX

CREATE OR REPLACE ALIAS "GALADM"."DEFECT_ACTUAL_PROBLEM_TBX"
  FOR "GALADM"."HMIN_ACTUAL_PROBLEMS_TBX";
COMMENT ON ALIAS "GALADM"."DEFECT_ACTUAL_PROBLEM_TBX" IS 'HMIN alias to RMT table DEFECT_ACTUAL_PROBLEM_TBX';

CREATE OR REPLACE ALIAS "GALADM"."DEFECT_REPAIR_METHOD_TBX"
  FOR "GALADM"."HMIN_REPAIR_METHODS_TBX";
COMMENT ON ALIAS "GALADM"."DEFECT_REPAIR_METHOD_TBX" IS 'HMIN alias to RMT table DEFECT_REPAIR_METHOD_TBX';

--*****GALCDB_VER_1.6.0.0_SEQ1.sql*****
--Create GAL703TBX/GAL704TBX create timestamp triggers

CREATE TRIGGER GALADM.GAL703_TR1_01
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_02
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_03
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_04
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_05
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_06
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_01
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_02
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_03
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_04
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_05
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL704_TR1_06
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL704TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;


--*****GALCDB_VER_1.6.0.0_SEQ2.sql*****
--Add AUTO_ENABLED column to GAL111TBX

ALTER TABLE GALADM.GAL111TBX DATA CAPTURE NONE; 
ALTER TABLE GALADM.GAL111TBX ADD COLUMN AUTO_ENABLED SMALLINT NOT NULL DEFAULT 0 CONSTRAINT AUTO_CHECK CHECK (AUTO_ENABLED IN (0,1)) ;
ALTER TABLE GALADM.GAL111TBX DATA CAPTURE CHANGES;

DROP TRIGGER GAL111TR1;
DROP TRIGGER GAL111TR2;

CREATE TRIGGER GALADM.GAL111_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL111_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL111TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL111TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL111TBX;

--*****GALCDB_VER_1.7.0.0_SEQ1.sql*****
--Change STANDARD_SCHEDULE_TBX.START_TIME and STANDARD_SCHEDULE_TBX.END_TIME from TIMESTAMP to TIME
REORG TABLE  GALADM.STANDARD_SCHEDULE_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.STANDARD_SCHEDULE_TBX;

ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX DROP COLUMN START_TIME;
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX DROP COLUMN END_TIME;

ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX ADD COLUMN START_TIME TIME;
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX ADD COLUMN END_TIME TIME;
   
ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX 
  DATA CAPTURE CHANGES; 

DROP TRIGGER GALADM.STANDARD_SCHEDULE_TR2;
DROP TRIGGER GALADM.STANDARD_SCHEDULE_TR1;

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.STANDARD_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.STANDARD_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.STANDARD_SCHEDULE_TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.STANDARD_SCHEDULE_TBX;
  
--*****GALCDB_VER_1.7.0.0_SEQ4.sql*****
--Recreate GAL251TBX table

DROP TRIGGER GAL251TR1;
DROP TRIGGER GAL251TR2;
DROP TABLE GALADM.GAL251TBX;

CREATE TABLE GALADM.GAL251TBX  (
  MODEL_YEAR_CODE CHAR(1) NOT NULL WITH DEFAULT '', 
  MODEL_CODE CHAR(3) NOT NULL WITH DEFAULT '', 
  MODEL_TYPE_CODE CHAR(3) NOT NULL WITH DEFAULT '*', 
  JOURNAL_POSITION VARCHAR(3) NOT NULL WITH DEFAULT '*', 
  BEARING_TYPE CHAR(10) NOT NULL WITH DEFAULT '', 
  COLUMN_MEASUREMENT CHAR(1) NOT NULL WITH DEFAULT '', 
  ROW_MEASUREMENT CHAR(1) NOT NULL WITH DEFAULT '', 
  UPPER_BEARING CHAR(30), 
  LOWER_BEARING CHAR(30), 
  CREATE_TIMESTAMP TIMESTAMP, 
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT GAL251TBX_PK PRIMARY KEY 
  (MODEL_YEAR_CODE, MODEL_CODE, MODEL_TYPE_CODE, JOURNAL_POSITION, BEARING_TYPE, COLUMN_MEASUREMENT, ROW_MEASUREMENT)
)   
IN GALTBSREF12 
INDEX IN GALTBSIDX4; 

ALTER TABLE GALADM.GAL251TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GAL251TBX IS 'Bearing Matrix Cell';

CREATE TRIGGER GALADM.GAL251_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.GAL251TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL251_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.GAL251TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.GAL251TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.GAL251TBX TO GROUP "GALCPR_S";


--*****GALCDB_VER_1.8.0.0_SEQ1.sql*****
--Create TEAM_ROTATION_TBX table

CREATE TABLE GALADM.TEAM_ROTATION_TBX (
  LINE_NO CHARACTER(2) NOT NULL DEFAULT '',
  PROCESS_LOCATION CHARACTER(2) NOT NULL DEFAULT '',
  PLANT_CODE CHARACTER(4) NOT NULL DEFAULT '',
  PRODUCTION_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  SHIFT CHARACTER(2) NOT NULL DEFAULT '',
  TEAM	VARCHAR(10)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT TEAM_ROTATION_PK PRIMARY KEY 
     (LINE_NO, PROCESS_LOCATION, PLANT_CODE, PRODUCTION_DATE, SHIFT, TEAM)
) 
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;
  
ALTER TABLE GALADM.TEAM_ROTATION_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.TEAM_ROTATION_TBX IS 'RMT used to track TEAM shift rotation';
    
CREATE TRIGGER GALADM.TEAM_ROTATION_TR1
  NO CASCADE BEFORE INSERT
  ON GALADM.TEAM_ROTATION_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET CREATE_TIMESTAMP=CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TEAM_ROTATION_TR2
  NO CASCADE BEFORE UPDATE
  ON GALADM.TEAM_ROTATION_TBX
  REFERENCING 
    NEW AS A
  FOR EACH ROW
SET UPDATE_TIMESTAMP=CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.TEAM_ROTATION_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.TEAM_ROTATION_TBX TO GROUP "GALCPR_S";


--*****GALCDB_VER_1.8.0.0_SEQ2.sql*****
--Create layer/feature tables

CREATE TABLE GALADM.FEATURE_POINTS_TBX (
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  FEATURE_SEQ	INTEGER	NOT NULL,
  X_COORDINATE	DOUBLE,
  Y_COORDINATE	DOUBLE,
  Z_COORDINATE	DOUBLE,
  CHILD_FEATURE_ID	VARCHAR(32),
  SPATIAL_REFERENCE_SYSTEM	VARCHAR(32),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT FEATURE_POINTS_PK PRIMARY KEY
    (FEATURE_ID, FEATURE_SEQ)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.FEATURE_POINTS_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.FEATURE_POINTS_TBX IS
   'RMT FeaturePoint coordinates for visualizing information';

CREATE TRIGGER GALADM.FEATURE_POINTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.FEATURE_POINTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FEATURE_POINTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.FEATURE_POINTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.FEATURE_POINTS_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.FEATURE_POINTS_TBX TO GROUP "GALCPR_S";

CREATE TABLE GALADM.FEATURE_TBX (
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  FEATURE_TYPE	VARCHAR(32) NOT NULL,
  REFERENCE_ID	VARCHAR(32),
  REFERENCE_TYPE	VARCHAR(32),
  ENABLE_HISTORY	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT FEATURE_PK PRIMARY KEY
    (FEATURE_ID, FEATURE_TYPE)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.FEATURE_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.FEATURE_TBX IS
   'RMT Feature for visualizing information';

CREATE TRIGGER GALADM.FEATURE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.FEATURE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.FEATURE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.FEATURE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.FEATURE_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.FEATURE_TBX TO GROUP "GALCPR_S";

CREATE TABLE GALADM.LAYER_FEATURES_TBX (
  LAYER_ID	VARCHAR(32)	NOT NULL,
  FEATURE_ID	VARCHAR(32)	NOT NULL,
  VISIBLE	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT LAYER_FEATURES_PK PRIMARY KEY
    (LAYER_ID, FEATURE_ID)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.LAYER_FEATURES_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.LAYER_FEATURES_TBX IS
   'RMT LayerFeatures used to relate Layers to Features';

CREATE TRIGGER GALADM.LAYER_FEATURES_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LAYER_FEATURES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LAYER_FEATURES_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LAYER_FEATURES_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.LAYER_FEATURES_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.LAYER_FEATURES_TBX TO GROUP "GALCPR_S";

CREATE TABLE GALADM.LAYER_TBX (
  LAYER_ID	VARCHAR(32)	NOT NULL,
  LAYER_TYPE	VARCHAR(32) NOT NULL,
  LAYER_DAO	VARCHAR(128),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  DEFAULT_ZOOM	INTEGER,
  BOUNDARY_LEFT	DOUBLE,
  BOUNDARY_LOWER	DOUBLE,
  BOUNDARY_RIGHT	DOUBLE,
  BOUNDARY_UPPER	DOUBLE,
  CONSTRAINT LAYER_PK PRIMARY KEY
    (LAYER_ID, LAYER_TYPE)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.LAYER_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.LAYER_TBX IS
   'RMT Layer to describe how to display visual information';

CREATE TRIGGER GALADM.LAYER_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.LAYER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.LAYER_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.LAYER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.LAYER_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.LAYER_TBX TO GROUP "GALCPR_S";

CREATE TABLE GALADM.VIEW_TBX (
  VIEW_ID	VARCHAR(32)	NOT NULL,
  LAYER_ID	VARCHAR(32)	NOT NULL,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP,
  CONSTRAINT VIEW_PK PRIMARY KEY
  (VIEW_ID, LAYER_ID)
) 
  IN GALTBSDAT10
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.VIEW_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;
  
COMMENT ON TABLE GALADM.VIEW_TBX IS
   'RMT View describes collection of Layers';

CREATE TRIGGER GALADM.VIEW_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.VIEW_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.VIEW_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.VIEW_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE GALADM.VIEW_TBX TO GROUP "GALCPR_A";

GRANT SELECT ON TABLE GALADM.VIEW_TBX TO GROUP "GALCPR_S";

--############################################################
ALTER TABLE GALADM.GAL703TBX_01
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_01
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_01
  DATA CAPTURE CHANGES;

DROP TRIGGER GAL703TR2_01;
CREATE TRIGGER GALADM.GAL703_TR2_01
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_01
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_01
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

REORG TABLE  GALADM.GAL703TBX_01;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_01;  
  
  
--############################################################
ALTER TABLE GALADM.GAL703TBX_02
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_02
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_02
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GAL703TR2_02;
CREATE TRIGGER GALADM.GAL703_TR2_02
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_02
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_02
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL703TBX_02;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_02;   
  
--############################################################
ALTER TABLE GALADM.GAL703TBX_03
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_03
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_03
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GAL703TR2_03;
CREATE TRIGGER GALADM.GAL703_TR2_03
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_03
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_03
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL703TBX_03;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_03; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_04
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_04
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_04
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GAL703TR2_04;
CREATE TRIGGER GALADM.GAL703_TR2_04
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_04
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_04
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL703TBX_04;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_04; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_05
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_05
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_05
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GAL703TR2_05;
CREATE TRIGGER GALADM.GAL703_TR2_05
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_05
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_05
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL703TBX_05;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_05; 

--############################################################
ALTER TABLE GALADM.GAL703TBX_06
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL703TBX_06
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL703TBX_06
  DATA CAPTURE CHANGES;
  
DROP TRIGGER GAL703TR2_06;
CREATE TRIGGER GALADM.GAL703_TR2_06
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL703TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL703_TR1_06
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL703TBX_06
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL703TBX_06;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL703TBX_06; 

--############################################################
ALTER TABLE GALADM.GAL712TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.GAL712TBX
ALTER COLUMN LET_RESULT_CAL SET DATA TYPE CHARACTER(19);

ALTER TABLE GALADM.GAL712TBX
  DATA CAPTURE CHANGES;
  
CREATE TRIGGER GALADM.GAL712_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL712TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL712_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL712TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
  
REORG TABLE  GALADM.GAL712TBX;
REORG INDEXES  ALL FOR TABLE  GALADM.GAL712TBX;   

CREATE TRIGGER GALADM.GAL710_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL710TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL710_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL710TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP TRIGGER GAL711TR2;
CREATE TRIGGER GALADM.GAL711_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL711TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL711_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL711TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL713_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL713TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL713_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL713TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

DROP VIEW GAL703TBXV;
CREATE VIEW GALADM.GAL703TBXV      ( END_TIMESTAMP, PRODUCT_ID, TEST_SEQ, INSPECTION_PGM_ID, INSPECTION_PGM_STATUS,      PROCESS_STEP, PROCESS_STATUS, PROCESS_START_TIMESTAMP, PROCESS_END_TIMESTAMP, LET_TERMINAL_ID,      LET_RESULT_CAL, LET_RESULT_DCREV, SOFTWARE_VERSION, LET_OPERATOR_ID, IN_CYCLE_RETEST_NUM, CREATE_TIMESTAMP, UPDATE_TIMESTAMP )  AS      
  select *         
  from GALADM.GAL703TBX_01     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_02         
  UNION ALL     
  select *         
  from GALADM.GAL703TBX_03         
  UNION ALL         
  select *     
  from GALADM.GAL703TBX_04     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_05     
  UNION ALL         
  select *         
  from GALADM.GAL703TBX_06      
  WITH NO ROW MOVEMENT;

COMMENT ON TABLE "GALADM"."GAL703TBXV" IS 'Union ALL of All Six 703TBX Tables';

GRANT DELETE, INSERT, SELECT, UPDATE ON GALADM.GAL703TBXV TO GROUP "GALCPR_A";

GRANT SELECT ON GALADM.GAL703TBXV TO GROUP "GALCPR_S";
