DROP ALIAS GALADM.HCM_GTS_PRODUCT_TBX;
DROP TRIGGER GALADM.GTS_PRODUCT_TR2;
DROP TRIGGER GALADM.GTS_PRODUCT_TR1;
DROP TABLE GALADM.GTS_PRODUCT_TBX;

CREATE TABLE GALADM.GTS_PRODUCT_TBX (
   TRACKING_AREA VARCHAR(10) NOT NULL,
   PRODUCT_ID VARCHAR(40) NOT NULL,
   SHORT_PROD_ID VARCHAR(20),
   LOT_NUMBER VARCHAR(20),
   KD_LOT_NUMBER VARCHAR(18),
   MODEL_YEAR CHARACTER(1),
   MODEL_CODE VARCHAR(5),
   MODEL_TYPE VARCHAR(5),
   MODEL_OPTION VARCHAR(5),
   INT_COLOR_CODE VARCHAR(5),
   EXT_COLOR_CODE VARCHAR(10),
   HOLD_STATUS SMALLINT DEFAULT 0,
   DEFECT_STATUS SMALLINT,
   INSPECTION_STATUS SMALLINT DEFAULT 0,
   PRODUCT_SEQ SMALLINT DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT GTS_PRODUCT_PK PRIMARY KEY
     (TRACKING_AREA,PRODUCT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.GTS_PRODUCT_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.GTS_PRODUCT_TBX IS 'RMT GtsProduct';

CREATE TRIGGER GALADM.GTS_PRODUCT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GTS_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GTS_PRODUCT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GTS_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_GTS_PRODUCT_TBX FOR GALADM.GTS_PRODUCT_TBX;
COMMENT ON ALIAS GALADM.HCM_GTS_PRODUCT_TBX IS 'RMT alias to GTS_PRODUCT_TBX';