DROP ALIAS GALADM.HCM_HEAD_TBX;
DROP TRIGGER GALADM.HEAD_TR2;
DROP TRIGGER GALADM.HEAD_TR1;
DROP TABLE GALADM.HEAD_TBX;

CREATE TABLE GALADM.HEAD_TBX (
   HEAD_ID VARCHAR(17) NOT NULL,
   MC_SERIAL_NUMBER VARCHAR(17),
   DC_SERIAL_NUMBER VARCHAR(17),
   ENGINE_SERIAL_NUMBER VARCHAR(17),
   MODEL VARCHAR(12),
   TRACKING_STATUS VARCHAR(12),
   DUNNAGE VARCHAR(12),
   DEFECT_STATUS SMALLINT,
   HOLD_STATUS SMALLINT DEFAULT 0 NOT NULL,
   ENGINE_FIRING_FLAG SMALLINT DEFAULT 0 NOT NULL,
   LAST_PASSING_PROCESS_POINT_ID CHARACTER(16),
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT HEAD_PK PRIMARY KEY
     (HEAD_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HEAD_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HEAD_TBX IS 'RMT Head';

CREATE TRIGGER GALADM.HEAD_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HEAD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HEAD_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HEAD_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.HEAD_I1
  ON GALADM.HEAD_TBX
    ( ENGINE_SERIAL_NUMBER )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.HEAD_I2
  ON GALADM.HEAD_TBX
    ( DC_SERIAL_NUMBER )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.HEAD_I3
  ON GALADM.HEAD_TBX
    ( DUNNAGE )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX GALADM.HEAD_I4
  ON GALADM.HEAD_TBX
    ( LAST_PASSING_PROCESS_POINT_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE ALIAS GALADM.HCM_HEAD_TBX FOR GALADM.HEAD_TBX;
COMMENT ON ALIAS GALADM.HCM_HEAD_TBX IS 'RMT alias to HEAD_TBX';