DROP ALIAS GALADM.HCM_HEAD_HISTORY_TBX;
DROP TRIGGER GALADM.HEAD_HISTORY_TR2;
DROP TRIGGER GALADM.HEAD_HISTORY_TR1;
DROP TABLE GALADM.HEAD_HISTORY_TBX;

CREATE TABLE GALADM.HEAD_HISTORY_TBX (
   HEAD_ID VARCHAR(17) NOT NULL,
   PROCESS_POINT_ID CHARACTER(16) DEFAULT ' ' NOT NULL,
   ACTUAL_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   UPDATE_TIMESTAMP TIMESTAMP,
   PROCESS_COUNT INTEGER DEFAULT 1 NOT NULL,
   CONSTRAINT HEAD_HISTORY_PK PRIMARY KEY
     (HEAD_ID,PROCESS_POINT_ID,ACTUAL_TIMESTAMP)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HEAD_HISTORY_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HEAD_HISTORY_TBX IS 'RMT HeadHistory';

CREATE TRIGGER GALADM.HEAD_HISTORY_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HEAD_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HEAD_HISTORY_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HEAD_HISTORY_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.HEAD_HISTORY_I1
  ON GALADM.HEAD_HISTORY_TBX
    ( PROCESS_POINT_ID, ACTUAL_TIMESTAMP )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE ALIAS GALADM.HCM_HEAD_HISTORY_TBX FOR GALADM.HEAD_HISTORY_TBX;
COMMENT ON ALIAS GALADM.HCM_HEAD_HISTORY_TBX IS 'RMT alias to HEAD_HISTORY_TBX';