DROP ALIAS GALADM.HCM_HLD_PARM_TBX;
DROP TRIGGER GALADM.HOLD_PARM_TR2;
DROP TRIGGER GALADM.HOLD_PARM_TR1;
DROP TABLE GALADM.HOLD_PARM_TBX;

CREATE TABLE GALADM.HOLD_PARM_TBX (
   HOLD_ID BIGINT NOT NULL,
   DEPARTMENT CHARACTER(2) NOT NULL,
   MACHINE_NUMBER VARCHAR(50) NOT NULL,
   DIE_NUMBER VARCHAR(80) NOT NULL,
   START_DATE DATE NOT NULL,
   STOP_DATE DATE NOT NULL,
   HOLD_REASON VARCHAR(80) NOT NULL,
   HOLD_ASSOCIATE_ID VARCHAR(11) NOT NULL,
   HOLD_ASSOCIATE_NAME VARCHAR(30) NOT NULL,
   ACTUAL_TIMESTAMP TIMESTAMP NOT NULL,
   RELEASE_FLAG SMALLINT NOT NULL,
   RELEASE_ASSOCIATE_ID VARCHAR(11),
   RELEASE_ASSOCIATE_NAME VARCHAR(30),
   RELEASE_TIMESTAMP TIMESTAMP,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   QSR_ID INTEGER,
   CONSTRAINT HOLD_PARM_PK PRIMARY KEY
     (HOLD_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HOLD_PARM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HOLD_PARM_TBX IS 'RMT HoldParm';

CREATE TRIGGER GALADM.HOLD_PARM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOLD_PARM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOLD_PARM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_HLD_PARM_TBX FOR GALADM.HOLD_PARM_TBX;
COMMENT ON ALIAS GALADM.HCM_HLD_PARM_TBX IS 'RMT alias to HOLD_PARM_TBX';