DROP ALIAS GALADM.HCM_TGA3051;
DROP TRIGGER GALADM.HOST_PRIORITY_PLAN_TR2;
DROP TRIGGER GALADM.HOST_PRIORITY_PLAN_TR1;
DROP TABLE GALADM.HOST_PRIORITY_PLAN_TBX;

CREATE TABLE GALADM.HOST_PRIORITY_PLAN_TBX (
   AFAE_FLAG CHARACTER(1) NOT NULL,
   PLAN_CODE CHARACTER(11) NOT NULL,
   LINE_NUMBER CHARACTER(2) NOT NULL,
   PLAN_PROC_LOC CHARACTER(2) NOT NULL,
   WE_LINE_NUMBER CHARACTER(2) NOT NULL,
   WE_PLAN_PROC_LOC CHARACTER(2) NOT NULL,
   PA_LINE_NUMBER CHARACTER(2) NOT NULL,
   PA_PLAN_PROC_LOC CHARACTER(2) NOT NULL,
   AFAE_OFF_DATE DATE NOT NULL,
   PROD_SEQ_NUMBER CHARACTER(12) NOT NULL,
   DEMAND_TYPE CHARACTER(2) NOT NULL,
   KD_LOT_NO CHARACTER(18) NOT NULL,
   MODEL_YEAR_CODE CHARACTER(1) NOT NULL,
   MODEL_CODE CHARACTER(3) NOT NULL,
   MODEL_TYPE_CODE CHARACTER(3) NOT NULL,
   MODEL_OPTION CHARACTER(3) NOT NULL,
   EXT_COLOUR_CODE CHARACTER(10) NOT NULL,
   INT_COLOUR_CODE CHARACTER(2) NOT NULL,
   NO_OF_UNITS INTEGER NOT NULL,
   START_VIN_NUMBER CHARACTER(17) NOT NULL,
   REMAKE_FLAG CHARACTER(1) NOT NULL,
   Y_N_FLAG CHARACTER(1) NOT NULL,
   CARRY_I_O_FLAG CHARACTER(1) NOT NULL,
   NO_OF_UNITS_CICO INTEGER NOT NULL,
   PLAN_CREATED CHARACTER(1) NOT NULL,
   CREATE_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
   ROW_PROCESSED CHARACTER(1) DEFAULT 'N' NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT HOST_PRIORITY_PLAN_PK PRIMARY KEY
     (AFAE_FLAG,PLAN_CODE,LINE_NUMBER,PLAN_PROC_LOC,WE_LINE_NUMBER,WE_PLAN_PROC_LOC,PA_LINE_NUMBER,PA_PLAN_PROC_LOC,AFAE_OFF_DATE,PROD_SEQ_NUMBER,CREATE_DATE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.HOST_PRIORITY_PLAN_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.HOST_PRIORITY_PLAN_TBX IS 'RMT HostPriorityPlan';

CREATE TRIGGER GALADM.HOST_PRIORITY_PLAN_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.HOST_PRIORITY_PLAN_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.HOST_PRIORITY_PLAN_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.HOST_PRIORITY_PLAN_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_TGA3051 FOR GALADM.HOST_PRIORITY_PLAN_TBX;
COMMENT ON ALIAS GALADM.HCM_TGA3051 IS 'RMT alias to HOST_PRIORITY_PLAN_TBX';