DROP TRIGGER GALADM.MBPN_TR2;
DROP TRIGGER GALADM.MBPN_TR1;
DROP TABLE GALADM.MBPN_TBX;

CREATE TABLE GALADM.MBPN_TBX (
  PRODUCT_SPEC_CODE CHARACTER(30) NOT NULL,
  MBPN CHARACTER(18) NOT NULL,
  HES_COLOR CHARACTER(11) NOT NULL,
  MAIN_NO CHARACTER(5) NOT NULL,
  CLASS_NO CHARACTER(3) NOT NULL,
  PROTOTYPE_CODE CHARACTER(1) NOT NULL,
  TYPE_NO CHARACTER(4) NOT NULL,
  SUPPLEMENTARY_NO CHARACTER(2) NOT NULL,
  TARGET_NO CHARACTER(2) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT MBPN_PK PRIMARY KEY
    (PRODUCT_SPEC_CODE)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MBPN_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MBPN_TBX IS
   'RMT Mbpn for defining Manufacturing Base Part Number product spec codes';

CREATE TRIGGER GALADM.MBPN_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MBPN_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MBPN_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MBPN_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;