DROP TRIGGER GALADM.MEASURE_SPEC_TR2;
DROP TRIGGER GALADM.MEASURE_SPEC_TR1;
DROP TABLE GALADM.MEASUREMENT_SPEC_TBX;

CREATE TABLE GALADM.MEASUREMENT_SPEC_TBX (
  PART_NAME CHARACTER(32) NOT NULL,
  PART_ID CHARACTER(5) NOT NULL,
  MEASUREMENT_SEQ_NUM INTEGER NOT NULL,
  MINIMUM_LIMIT DOUBLE,
  MAXIMUM_LIMIT DOUBLE,
  MAX_ATTEMPTS INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT MEASURE_SPEC_PK PRIMARY KEY
    (PART_NAME, PART_ID, MEASUREMENT_SEQ_NUM)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.MEASUREMENT_SPEC_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.MEASUREMENT_SPEC_TBX IS
   'RMT MeasurementSpec for LOT CONTROL to define Installed Part Measurement Specs';

CREATE TRIGGER GALADM.MEASURE_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.MEASUREMENT_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.MEASURE_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.MEASUREMENT_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;