DROP TRIGGER GALADM.NOTIF_SUB_TR2;
DROP TRIGGER GALADM.NOTIF_SUB_TR1;
DROP TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX;

CREATE TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX (
   NOTIFICATION_CLASS   VARCHAR (256) NOT NULL,
   CLIENT_NAME          CHARACTER (32),
   CLIENT_IP            VARCHAR (255) NOT NULL,
   CLIENT_PORT          INTEGER NOT NULL,
   CREATE_TIMESTAMP     TIMESTAMP,
   UPDATE_TIMESTAMP     TIMESTAMP,
   CONSTRAINT NOTIF_SUB_PK PRIMARY KEY
      (NOTIFICATION_CLASS, CLIENT_IP, CLIENT_PORT)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.NOTIFICATION_SUBSCRIBER_TBX IS
   'RMT NotificationSubscriber for managing clients setup for asynchronous communication';

CREATE TRIGGER GALADM.NOTIF_SUB_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_SUBSCRIBER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIF_SUB_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_SUBSCRIBER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;