DROP TRIGGER GALADM.NOTIF_PRO_TR2;
DROP TRIGGER GALADM.NOTIF_PRO_TR1;
DROP TABLE GALADM.NOTIFICATION_PROVIDER_TBX;

CREATE TABLE GALADM.NOTIFICATION_PROVIDER_TBX (
   NOTIFICATION_CLASS   VARCHAR (256) NOT NULL,
   HOST_IP              VARCHAR (255) NOT NULL,
   HOST_PORT            SMALLINT NOT NULL,
   HOST_NAME            CHARACTER (32),
   DESCRIPTION          VARCHAR (256),
   CREATE_TIMESTAMP     TIMESTAMP,
   UPDATE_TIMESTAMP     TIMESTAMP,
   CONSTRAINT NOTIF_PRO_PK PRIMARY KEY
      (NOTIFICATION_CLASS, HOST_IP, HOST_PORT)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.NOTIFICATION_PROVIDER_TBX IS
   'RMT NotificationProvider for managing hosts setup for asynchronous communication';

CREATE TRIGGER GALADM.NOTIF_PRO_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIF_PRO_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;