DROP TRIGGER GALADM.ORDER_TR2;
DROP TRIGGER GALADM.ORDER_TR1;
DROP TABLE GALADM.ORDER_TBX;

CREATE TABLE GALADM.ORDER_TBX (
  ORDER_NO CHARACTER(20) NOT NULL,
  PLAN_CODE CHARACTER(11) NOT NULL,
  PRODUCT_SPEC_CODE CHARACTER(30),
  PRIORITY_DATE DATE,
  PRIORITY_SEQ INTEGER,
  PROD_ORDER_QTY INTEGER,
  LOCATION_LEVEL_ID CHARACTER(16),
  ORDER_STATUS_ID INTEGER,
  HOLD_STATUS_ID INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT ORDER_PK PRIMARY KEY
    (ORDER_NO, PLAN_CODE)
)
  IN GALTBSDAT7
  INDEX IN GALTBSIDX3;

ALTER TABLE GALADM.ORDER_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.ORDER_TBX IS
   'RMT Orders for LINE to track status of Product Orders for a Plan Code';

COMMENT ON GALADM.ORDER_TBX (
 LOCATION_LEVEL_ID IS 'Location Level ID is PROCESS POINT ID or LINE ID of the station(s) that manage these orders',
 ORDER_STATUS_ID IS 'Link to ORDER_STATUS_TBX',
 HOLD_STATUS_ID IS 'Link to HOLD_STATUS_TBX' );

CREATE TRIGGER GALADM.ORDER_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.ORDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.ORDER_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.ORDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;