DROP TRIGGER GALADM.PART_LOT_TR2;
DROP TRIGGER GALADM.PART_LOT_TR1;
DROP TABLE GALADM.PART_LOT_TBX;

CREATE TABLE GALADM.PART_LOT_TBX (
  PART_SERIAL_NUMBER CHARACTER(30) NOT NULL,
  PART_NUMBER CHARACTER(30) NOT NULL,
  PART_NAME CHARACTER(32) NOT NULL,
  STATUS SMALLINT DEFAULT 0,
  STARTING_QUANTITY INTEGER DEFAULT 0,
  CURRENT_QUANTITY INTEGER DEFAULT 0,
  COMMENT VARCHAR(256),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT PART_LOT_PK PRIMARY KEY
    (PART_SERIAL_NUMBER, PART_NAME, PART_NUMBER)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PART_LOT_TBX
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PART_LOT_TBX IS
   'RMT PartLot for tracking quantity of parts installed from a lot';

CREATE TRIGGER GALADM.PART_LOT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PART_LOT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PART_LOT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PART_LOT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;