DROP TRIGGER GALADM.PART_SPEC_TR2;
DROP TRIGGER GALADM.PART_SPEC_TR1;
DROP TABLE GALADM.PART_SPEC_TBX;

CREATE TABLE GALADM.PART_SPEC_TBX (
  PART_NAME CHARACTER(32) NOT NULL,
  PART_ID CHARACTER(5) NOT NULL,
  PART_DESCRIPTION VARCHAR(128),
  PART_SERIAL_NUMBER_MASK VARCHAR(255),
  PART_MAX_ATTEMPTS INTEGER,
  MEASUREMENT_COUNT INTEGER,
  ENTRY_TIMESTAMP TIMESTAMP,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  COMMENT VARCHAR(256) DEFAULT '',
  CONSTRAINT PART_SPEC_PK PRIMARY KEY
    (PART_NAME, PART_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PART_SPEC_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PART_SPEC_TBX IS
   'RMT PartSpec for LOT CONTROL to define Installed Part Spec';

CREATE TRIGGER GALADM.PART_SPEC_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PART_SPEC_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PART_SPEC_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;