DROP TRIGGER GALADM.PLC_MEMORY_MAP_TR2;
DROP TRIGGER GALADM.PLC_MEMORY_MAP_TR1;
DROP TABLE GALADM.PLC_MEMORY_MAP_TBX;

CREATE TABLE GALADM.PLC_MEMORY_MAP_TBX (
  METRIC VARCHAR(160) NOT NULL,
  DATA_TYPE CHARACTER(30),
  MEMORY_BANK CHARACTER(30),
  START_ADDRESS CHARACTER(30),
  BIT CHARACTER(30),
  BYTE_ORDER CHARACTER(30),
  LENGTH INTEGER,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT HMIN_MEM_PK PRIMARY KEY
    (METRIC)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PLC_MEMORY_MAP_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PLC_MEMORY_MAP_TBX IS
   'RMT PlcMemoryMapItem for LOT CONTROL to manage PLC Memory Map';

CREATE TRIGGER GALADM.PLC_MEMORY_MAP_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PLC_MEMORY_MAP_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PLC_MEMORY_MAP_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PLC_MEMORY_MAP_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;