DROP TRIGGER GALADM.PRODUCT_TYPE_TR2;
DROP TRIGGER GALADM.PRODUCT_TYPE_TR1;
DROP TABLE GALADM.PRODUCT_TYPE_TBX;

CREATE TABLE GALADM.PRODUCT_TYPE_TBX (
  PRODUCT_TYPE CHARACTER(10) NOT NULL,
  PRODUCT_TYPE_LABEL CHARACTER(30),
  PRODUCT_SPEC_CODE_FORMAT VARCHAR(256),
  PRODUCT_SPEC_CODE_LABEL CHARACTER(30) DEFAULT 'MTO',
  OWNER_PRODUCT_TYPE CHARACTER(10),
  PRODUCT_ID_LABEL CHARACTER(30),
  PRODUCT_ID_FORMAT CHARACTER(30),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY
    (PRODUCT_TYPE)
)
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.PRODUCT_TYPE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PRODUCT_TYPE_TBX IS
   'RMT ProductTypeData for defining the different product types';

CREATE TRIGGER GALADM.PRODUCT_TYPE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_TYPE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_TYPE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;