DROP ALIAS GALADM.HCM_PRODUCT_SEQUENCE_TBX;
DROP TRIGGER GALADM.PRODUCT_SEQUENCE_TR2;
DROP TRIGGER GALADM.PRODUCT_SEQUENCE_TR1;
DROP TABLE GALADM.PRODUCT_SEQUENCE_TBX;

CREATE TABLE GALADM.PRODUCT_SEQUENCE_TBX (
   PRODUCT_ID CHARACTER(17) NOT NULL,
   PROCESS_POINT_ID CHARACTER(16) NOT NULL,
   REFERENCE_TIMESTAMP TIMESTAMP NOT NULL,
   ASSOCIATE_NO CHARACTER(11),
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT PRODUCT_SEQUENCE_PK PRIMARY KEY
     (PRODUCT_ID,PROCESS_POINT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.PRODUCT_SEQUENCE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PRODUCT_SEQUENCE_TBX IS 'RMT ProductSequence';

CREATE TRIGGER GALADM.PRODUCT_SEQUENCE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_SEQUENCE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_SEQUENCE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_PRODUCT_SEQUENCE_TBX FOR GALADM.PRODUCT_SEQUENCE_TBX;
COMMENT ON ALIAS GALADM.HCM_PRODUCT_SEQUENCE_TBX IS 'RMT alias to PRODUCT_SEQUENCE_TBX';