DROP TRIGGER GALADM.PRODUCT_SPEC_CODE_TR2;
DROP TRIGGER GALADM.PRODUCT_SPEC_CODE_TR1;
DROP TABLE GALADM.PRODUCT_SPEC_CODE_TBX;

CREATE TABLE GALADM.PRODUCT_SPEC_CODE_TBX (
  PRODUCT_SPEC_CODE CHARACTER(22) NOT NULL,
  PRODUCT_TYPE CHARACTER(10) NOT NULL,
  MODEL_YEAR_CODE CHARACTER(1),
  MODEL_CODE CHARACTER(3),
  MODEL_TYPE_CODE CHARACTER(3),
  MODEL_OPTION_CODE CHARACTER(3),
  EXT_COLOR_CODE CHARACTER(10),
  INT_COLOR_CODE CHARACTER(3),
  MODEL_YEAR_DESCRIPTION CHARACTER(4),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT PRODUCT_SPEC_CODE_PK PRIMARY KEY
    (PRODUCT_SPEC_CODE,PRODUCT_TYPE)
)
  IN GALTBSDAT6
  INDEX IN GALTBSIDX2;

ALTER TABLE GALADM.PRODUCT_SPEC_CODE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.PRODUCT_SPEC_CODE_TBX IS
   'RMT ProductTypeData for defining the different product types';

CREATE TRIGGER GALADM.PRODUCT_SPEC_CODE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.PRODUCT_SPEC_CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.PRODUCT_SPEC_CODE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.PRODUCT_SPEC_CODE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;