DROP ALIAS GALADM.HCM_QUORUM_DETAIL_TBX;
DROP TRIGGER GALADM.QUORUM_DETAIL_TR2;
DROP TRIGGER GALADM.QUORUM_DETAIL_TR1;
DROP TABLE GALADM.QUORUM_DETAIL_TBX;

CREATE TABLE GALADM.QUORUM_DETAIL_TBX (
   QUORUM_DATE DATE NOT NULL,
   QUORUM_ID INTEGER NOT NULL,
   QUORUM_SEQ INTEGER NOT NULL,
   KD_LOT CHARACTER(18),
   YMTO  CHARACTER(9),
   ENGINE_NUMBER CHARACTER(12),
   STATUS INTEGER DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT QUORUM_DETAIL_PK PRIMARY KEY
     (QUORUM_DATE,QUORUM_ID,QUORUM_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.QUORUM_DETAIL_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.QUORUM_DETAIL_TBX IS 'RMT ShippingQuorumDetail';

CREATE TRIGGER GALADM.QUORUM_DETAIL_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QUORUM_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QUORUM_DETAIL_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QUORUM_DETAIL_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX QUORUM_DETAIL_I1
  ON GALADM.QUORUM_DETAIL_TBX
    ( ENGINE_NUMBER, QUORUM_ID, QUORUM_DATE )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE ALIAS GALADM.HCM_QUORUM_DETAIL_TBX FOR GALADM.QUORUM_DETAIL_TBX;
COMMENT ON ALIAS GALADM.HCM_QUORUM_DETAIL_TBX IS 'RMT alias to QUORUM_DETAIL_TBX';