DROP ALIAS GALADM.HCM_QUORUM_TBX;
DROP TRIGGER GALADM.QUORUM_TR2;
DROP TRIGGER GALADM.QUORUM_TR1;
DROP TABLE GALADM.QUORUM_TBX;

CREATE TABLE GALADM.QUORUM_TBX (
   QUORUM_DATE DATE NOT NULL,
   QUORUM_ID INTEGER NOT NULL,
   TRAILER_ID INTEGER NOT NULL,
   TRAILER_ROW INTEGER NOT NULL,
   PALLET_TYPE VARCHAR(5) NOT NULL,
   QUORUM_SIZE INTEGER NOT NULL,
   STATUS INTEGER NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT QUORUM_PK PRIMARY KEY
     (QUORUM_DATE,QUORUM_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.QUORUM_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.QUORUM_TBX IS 'RMT ShippingQuorum';

CREATE TRIGGER GALADM.QUORUM_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.QUORUM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.QUORUM_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.QUORUM_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX QUORUM_I1
  ON GALADM.QUORUM_TBX
    ( QUORUM_ID, QUORUM_DATE, TRAILER_ID )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE INDEX QUORUM_I2
  ON GALADM.QUORUM_TBX
    ( STATUS )
  ALLOW REVERSE SCANS
  COMPRESS NO;

CREATE ALIAS GALADM.HCM_QUORUM_TBX FOR GALADM.QUORUM_TBX;
COMMENT ON ALIAS GALADM.HCM_QUORUM_TBX IS 'RMT alias to QUORUM_TBX';