DROP ALIAS GALADM.HCM_REQUIRED_PARTS_TBX;
DROP TRIGGER GALADM.REQUIRED_PARTS_TR2;
DROP TRIGGER GALADM.REQUIRED_PARTS_TR1;
DROP TABLE GALADM.REQUIRED_PARTS_TBX;

CREATE TABLE GALADM.REQUIRED_PARTS_TBX (
   PROCESS_POINT_ID CHARACTER(16) DEFAULT ' ' NOT NULL,
   MODEL_YEAR_CODE CHARACTER(1) DEFAULT ' ' NOT NULL,
   MODEL_CODE CHARACTER(3) DEFAULT ' ' NOT NULL,
   MODEL_TYPE_CODE CHARACTER(3) DEFAULT ' ' NOT NULL,
   MODEL_OPTION_CODE CHARACTER(3) DEFAULT ' ' NOT NULL,
   INT_COLOR_CODE CHARACTER(2) DEFAULT ' ' NOT NULL,
   EXT_COLOR_CODE CHARACTER(10) DEFAULT ' ' NOT NULL,
   PART_NAME CHARACTER(32) DEFAULT ' ' NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   SUB_ID CHARACTER(2),
   CONSTRAINT REQUIRED_PARTS_PK PRIMARY KEY
     (PROCESS_POINT_ID,MODEL_YEAR_CODE,MODEL_CODE,MODEL_TYPE_CODE,MODEL_OPTION_CODE,INT_COLOR_CODE,EXT_COLOR_CODE,PART_NAME)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.REQUIRED_PARTS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.REQUIRED_PARTS_TBX IS 'RMT RequiredPart';

CREATE TRIGGER GALADM.REQUIRED_PARTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.REQUIRED_PARTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.REQUIRED_PARTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.REQUIRED_PARTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_REQUIRED_PARTS_TBX FOR GALADM.REQUIRED_PARTS_TBX;
COMMENT ON ALIAS GALADM.HCM_REQUIRED_PARTS_TBX IS 'RMT alias to REQUIRED_PARTS_TBX';