DROP TRIGGER GALADM.SKIP_PRODUCT_TR2;
DROP TRIGGER GALADM.SKIP_PRODUCT_TR1;
DROP TABLE GALADM.SKIPPED_PRODUCT_TBX;

CREATE TABLE GALADM.SKIPPED_PRODUCT_TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL,
  PROCESS_POINT_ID CHARACTER(16) NOT NULL,
  SUB_ID CHARACTER(2),
  PRODUCT_TYPE CHARACTER(10),
  KD_LOT_NUMBER CHARACTER(18),
  PRODUCTION_LOT CHARACTER(20),
  PRODUCT_SPEC_CODE CHARACTER(22),
  STATUS SMALLINT DEFAULT 0,
  SKIP_TIMESTAMP TIMESTAMP,
  DISABLE_TIMESTAMP TIMESTAMP,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT SKIPPED_PRODUCT_PK PRIMARY KEY
    (PRODUCT_ID, PROCESS_POINT_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.SKIPPED_PRODUCT_TBX
  DATA CAPTURE NONE
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.SKIPPED_PRODUCT_TBX IS
   'RMT SkippedProduct for tracking which products were skipped per plan';

CREATE TRIGGER GALADM.SKIP_PRODUCT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.SKIPPED_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.SKIP_PRODUCT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.SKIPPED_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;