DROP ALIAS GALADM.HCM_STANDARD_SCHEDULE_TBX;
DROP TRIGGER GALADM.STANDARD_SCHEDULE_TR2;
DROP TRIGGER GALADM.STANDARD_SCHEDULE_TR1;
DROP TABLE GALADM.STANDARD_SCHEDULE_TBX;

CREATE TABLE GALADM.STANDARD_SCHEDULE_TBX (
   PLANT_CODE CHARACTER(4) DEFAULT '' NOT NULL,
   LINE_NO CHARACTER(2) DEFAULT '' NOT NULL,
   PROCESS_LOCATION CHARACTER(2) DEFAULT '' NOT NULL,
   DAY_OF_WEEK CHARACTER(3) NOT NULL,
   SHIFT CHARACTER(2) DEFAULT '' NOT NULL,
   PERIOD INTEGER DEFAULT 0 NOT NULL,
   PERIOD_LABEL CHARACTER(5),
   TYPE CHARACTER(3),
   PLAN CHARACTER(1),
   START_TIME TIMESTAMP,
   END_TIME TIMESTAMP,
   NEXT_DAY SMALLINT DEFAULT 0,
   CAPACITY INTEGER DEFAULT 0,
   CAPACITY_ON INTEGER DEFAULT 0,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT STANDARD_SCHEDULE_PK PRIMARY KEY
     (PLANT_CODE,LINE_NO,PROCESS_LOCATION,DAY_OF_WEEK,SHIFT,PERIOD)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.STANDARD_SCHEDULE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.STANDARD_SCHEDULE_TBX IS 'RMT StandardSchedule';

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.STANDARD_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.STANDARD_SCHEDULE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.STANDARD_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_STANDARD_SCHEDULE_TBX
   FOR GALADM.STANDARD_SCHEDULE_TBX;
COMMENT ON ALIAS GALADM.HCM_STANDARD_SCHEDULE_TBX IS 'RMT alias to STANDARD_SCHEDULE_TBX';