DROP TRIGGER GALADM.SUB_PRODUCT_TR2;
DROP TRIGGER GALADM.SUB_PRODUCT_TR1;
DROP TABLE GALADM.SUB_PRODUCT_TBX;

CREATE TABLE GALADM.SUB_PRODUCT_TBX (
  PRODUCT_ID CHARACTER(17) NOT NULL DEFAULT '',
  PRODUCTION_LOT CHARACTER(20),
  KD_LOT_NUMBER CHARACTER(18),
  PRODUCT_TYPE CHARACTER(10),
  PRODUCT_SPEC_CODE CHARACTER(22),
  SUB_ID CHARACTER(2),
  PLAN_OFF_DATE DATE,
  TRACKING_STATUS CHARACTER(16),
  PRODUCT_START_DATE DATE,
  ACTUAL_OFF_DATE DATE,
  AUTO_HOLD_STATUS SMALLINT DEFAULT 0,
  STATUS SMALLINT DEFAULT 0,
  PRODUCTION_DATE DATE,
  LAST_PASSING_PROCESS_POINT_ID CHARACTER(16),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT SUB_PRODUCT_PK PRIMARY KEY
   (PRODUCT_ID)
)
  IN GALTBSDAT1
  INDEX IN GALTBSIDX1;

ALTER TABLE GALADM.SUB_PRODUCT_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.SUB_PRODUCT_TBX IS
   'RMT SubProduct for subassembly products';

CREATE TRIGGER GALADM.SUB_PRODUCT_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.SUB_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.SUB_PRODUCT_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.SUB_PRODUCT_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;