DROP ALIAS GALADM.HCM_TRAILER_STATUS;
DROP TRIGGER GALADM.TRAILER_STATUS_TR2;
DROP TRIGGER GALADM.TRAILER_STATUS_TR1;
DROP TABLE GALADM.TRAILER_STATUS_TBX;

CREATE TABLE GALADM.TRAILER_STATUS_TBX (
   TRAILER_ID INTEGER NOT NULL,
   STATUS INTEGER NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT TRAILER_STATUS_PK PRIMARY KEY
     (TRAILER_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.TRAILER_STATUS_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.TRAILER_STATUS_TBX IS 'RMT ShippingTrailerStatus';

CREATE TRIGGER GALADM.TRAILER_STATUS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TRAILER_STATUS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TRAILER_STATUS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TRAILER_STATUS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_TRAILER_STATUS FOR GALADM.TRAILER_STATUS_TBX;
COMMENT ON ALIAS GALADM.HCM_TRAILER_STATUS IS 'RMT alias to TRAILER_STATUS_TBX';