DROP ALIAS GALADM.HCM_TRAILER_INFO_TBX;
DROP TRIGGER GALADM.TRAILER_INFO_TR2;
DROP TRIGGER GALADM.TRAILER_INFO_TR1;
DROP TABLE GALADM.TRAILER_INFO_TBX;

CREATE TABLE GALADM.TRAILER_INFO_TBX (
   TRAILER_ID INTEGER NOT NULL,
   TRAILER_NUMBER VARCHAR(10),
   SCH_QTY INTEGER NOT NULL,
   ACT_QTY INTEGER DEFAULT 0 NOT NULL,
   STATUS INTEGER,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT TRAILER_INFO_PK PRIMARY KEY
     (TRAILER_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.TRAILER_INFO_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.TRAILER_INFO_TBX IS 'RMT ShippingTrailerInfo';

CREATE TRIGGER GALADM.TRAILER_INFO_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.TRAILER_INFO_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.TRAILER_INFO_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.TRAILER_INFO_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_TRAILER_INFO_TBX FOR GALADM.TRAILER_INFO_TBX;
COMMENT ON ALIAS GALADM.HCM_TRAILER_INFO_TBX IS 'RMT alias to TRAILER_INFO_TBX';