DROP ALIAS GALADM.HCM_VANNING_SCHEDULE_TBX;
DROP TRIGGER GALADM.VANNING_SCHEDULE_TR2;
DROP TRIGGER GALADM.VANNING_SCHEDULE_TR1;
DROP TABLE GALADM.VANNING_SCHEDULE_TBX;

CREATE TABLE GALADM.VANNING_SCHEDULE_TBX (
   PRODUCTION_DATE DATE NOT NULL,
   VANNING_SEQ INTEGER NOT NULL,
   TRAILER_ID INTEGER,
   KD_LOT CHARACTER(18) NOT NULL,
   PRODUCTION_LOT CHARACTER(20) NOT NULL,
   YMTO CHARACTER(9) NOT NULL,
   SCH_QTY INTEGER NOT NULL,
   ACT_QTY INTEGER DEFAULT 0 NOT NULL,
   CREATE_TIMESTAMP TIMESTAMP,
   UPDATE_TIMESTAMP TIMESTAMP,
   CONSTRAINT VANNING_SCHEDULE_PK PRIMARY KEY
     (PRODUCTION_DATE,VANNING_SEQ)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.VANNING_SCHEDULE_TBX
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.VANNING_SCHEDULE_TBX IS 'RMT ShippingVanningSchedule';

CREATE TRIGGER GALADM.VANNING_SCHEDULE_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.VANNING_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.VANNING_SCHEDULE_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.VANNING_SCHEDULE_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE ALIAS GALADM.HCM_VANNING_SCHEDULE_TBX FOR GALADM.VANNING_SCHEDULE_TBX;
COMMENT ON ALIAS GALADM.HCM_VANNING_SCHEDULE_TBX IS 'RMT alias to VANNING_SCHEDULE_TBX';