DROP TRIGGER GALADM.WSBUILDS_TR2;
DROP TRIGGER GALADM.WSBUILDS_TR1;
DROP TABLE GALADM.WSBUILDS_TBX;

CREATE TABLE GALADM.WSBUILDS_TBX (
  BUILD_ID VARCHAR(20) NOT NULL,
  URL VARCHAR(120) NOT NULL,
  DEFAULT_BUILD CHARACTER(1) NOT NULL DEFAULT 'N',
  BUILD_DATE DATE,
  DESCRIPTION VARCHAR(128),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT WSBUILDS_PK PRIMARY KEY
    (BUILD_ID)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.WSBUILDS_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.WSBUILDS_TBX IS
   'RMT WebStartBuild for Web Start to define build numbers';

CREATE TRIGGER GALADM.WSBUILDS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.WSBUILDS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.WSBUILDS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.WSBUILDS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;