DROP TRIGGER GALADM.WSCLIENTS_TR2;
DROP TRIGGER GALADM.WSCLIENTS_TR1;
DROP TABLE GALADM.WSCLIENTS_TBX;

CREATE TABLE GALADM.WSCLIENTS_TBX (
  IP_ADDRESS VARCHAR(255) NOT NULL,
  HOST_NAME VARCHAR(32) NOT NULL,
  DESCRIPTION VARCHAR(128),
  BUILD_ID VARCHAR(20) NOT NULL,
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  ASSET_NUMBER VARCHAR(20) DEFAULT '',
  COLUMN_LOCATION VARCHAR(20) DEFAULT '',
  HEARTBEAT_TIMESTAMP TIMESTAMP,
  RESTART_IN_SECS INTEGER NOT NULL DEFAULT -1,
  CONSTRAINT WSCLIENTS_PK PRIMARY KEY
    (IP_ADDRESS)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.WSCLIENTS_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.WSCLIENTS_TBX IS
   'RMT WebStartClient for Web Start to define Clients';

CREATE TRIGGER GALADM.WSCLIENTS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.WSCLIENTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.WSCLIENTS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.WSCLIENTS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE INDEX GALADM.WSCLIENTS_I1
  ON GALADM.WSCLIENTS_TBX
    ( HOST_NAME ASC )
  ALLOW REVERSE SCANS
  COMPRESS NO;