DROP TRIGGER GALADM.WSDEFBUILDS_TR2;
DROP TRIGGER GALADM.WSDEFBUILDS_TR1;
DROP TABLE GALADM.WSDEFBUILDS_TBX;

CREATE TABLE GALADM.WSDEFBUILDS_TBX (
  ENVIRONMENT VARCHAR(64) NOT NULL,
  DEF_BUILD_ID VARCHAR(20) NOT NULL,
  ENV_DESCRIPTION VARCHAR(128),
  CREATE_TIMESTAMP TIMESTAMP,
  UPDATE_TIMESTAMP TIMESTAMP,
  CONSTRAINT WSDEFBUILDS_PK PRIMARY KEY
    (ENVIRONMENT)
)
  IN GALTBSREF12
  INDEX IN GALTBSIDX4;

ALTER TABLE GALADM.WSDEFBUILDS_TBX
  DATA CAPTURE CHANGES INCLUDE LONGVAR COLUMNS
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE GALADM.WSDEFBUILDS_TBX IS
   'RMT WebStartDefaultBuild for Web start to define default builds per environment';

CREATE TRIGGER GALADM.WSDEFBUILDS_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.WSDEFBUILDS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.WSDEFBUILDS_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.WSDEFBUILDS_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;