SELECT * FROM GALADM.GAL135TBX WHERE GAL135TBX.PROCESS_POINT_ID='TEST_ID';

SELECT * FROM "GALADM"."HOLD_STATUS_TBX" WHERE HOLD_STATUS_ID=999991;

SELECT * FROM "GALADM"."ORDER_STATUS_TBX" WHERE ORDER_STATUS_ID=999992;

SELECT * FROM "GALADM"."PLAN_STATUS_TBX" WHERE PLAN_STATUS_ID=999993;

SELECT * FROM "GALADM"."PRODUCT_STATUS_TBX" WHERE PRODUCT_STATUS_ID=999994;

SELECT * FROM "GALADM"."MBPN_PRODUCT_TBX" WHERE PRODUCT_ID='TEST_PRODUCT';

SELECT * FROM "GALADM"."MBPN_TBX" WHERE PRODUCT_SPEC_CODE='TEST_SPEC';

SELECT * FROM "GALADM"."ORDER_TBX" WHERE ORDER_NO='TEST_ORDER';

SELECT * FROM "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" WHERE TRACKING_STATUS='TEST_STATUS' AND TRACKING_SEQUENCE_NO=1;




DELETE FROM GALADM.GAL135TBX WHERE GAL135TBX.PROCESS_POINT_ID='TEST_ID';

DELETE FROM "GALADM"."HOLD_STATUS_TBX" WHERE HOLD_STATUS_ID=999991;
        
DELETE FROM "GALADM"."ORDER_STATUS_TBX" WHERE ORDER_STATUS_ID=999992;

DELETE FROM "GALADM"."PLAN_STATUS_TBX" WHERE PLAN_STATUS_ID=999993;

DELETE FROM "GALADM"."PRODUCT_STATUS_TBX" WHERE PRODUCT_STATUS_ID=999994;

DELETE FROM "GALADM"."MBPN_PRODUCT_TBX" WHERE PRODUCT_ID='TEST_PRODUCT';

DELETE FROM "GALADM"."MBPN_TBX" WHERE PRODUCT_SPEC_CODE='TEST_SPEC';

DELETE FROM "GALADM"."ORDER_TBX" WHERE ORDER_NO='TEST_ORDER';

DELETE FROM "GALADM"."PRODUCT_PRIORITY_PLAN_TBX" WHERE TRACKING_STATUS='TEST_STATUS' AND TRACKING_SEQUENCE_NO=1;





INSERT INTO "GALADM"."GAL135TBX"
        ("PROCESS_POINT_ID","PRODUCT_ID"  ,"LAST_PROCESSED_PRODUCT") 
 VALUES ('TEST_ID'         ,'TEST_PRODUCT','TEST_LAST');

INSERT INTO "GALADM"."HOLD_STATUS_TBX"
        ("HOLD_STATUS_ID","HOLD_STATUS_NAME","HOLD_STATUS_DESCRIPTION") 
 VALUES (999991          ,'TEST_NAME'       ,'TEST_DESC');

INSERT INTO "GALADM"."ORDER_STATUS_TBX"
       ("ORDER_STATUS_ID","ORDER_STATUS_NAME","ORDER_STATUS_DESC") 
VALUES (999992           ,'TEST_NAME'        ,'TEST_DESC');

INSERT INTO GALADM.PLAN_STATUS_TBX
         ("PLAN_STATUS_ID","PLAN_STATUS_NAME","PLAN_STATUS_DESC") 
  VALUES (999993          ,'TEST_NAME'       ,'TEST_DESC');  

INSERT INTO "GALADM"."PRODUCT_STATUS_TBX"
       ("PRODUCT_STATUS_ID","PRODUCT_STATUS_NAME","PRODUCT_STATUS_DESCRIPTION") 
VALUES (999994             ,'TEST_NAME'          ,'TEST_DESC');

INSERT INTO "GALADM"."MBPN_PRODUCT_TBX"
        ("PRODUCT_ID"  ,"CURRENT_PRODUCT_SPEC_CODE","CURRENT_ORDER_NO","TRACKING_STATUS","LAST_PASSING_PROCESS_POINT","TRACKING_SEQ","HOLD_STATUS_ID","PRODUCT_STATUS_ID","CONTAINER_ID","CONTAINER_POS") 
 VALUES ('TEST_PRODUCT','TEST_SPEC'                ,'TEST_ORDER'      ,'TEST_STATUS'    ,'TEST_LAST'                 ,999999.99     ,999991          ,999994             ,'CONTAINER'   ,99);

INSERT INTO "GALADM"."MBPN_TBX"
       ("PRODUCT_SPEC_CODE","MBPN","HES_COLOR","MAIN_NO","CLASS_NO","PROTOTYPE_CODE","TYPE_NO","SUPPLEMENTARY_NO","TARGET_NO") 
VALUES ('TEST_SPEC'        ,'MPBN','COLOR'    ,'MAIN '  ,'CLA'     ,'Z'             ,'TYPE'   ,'SU'              ,'TA');

INSERT INTO "GALADM"."ORDER_TBX"
       ("ORDER_NO"  ,"PLAN_CODE","PRODUCT_SPEC_CODE","PRIORITY_DATE","PRIORITY_SEQ","PROD_ORDER_QTY","LOCATION_LEVEL_ID","ORDER_STATUS_ID","HOLD_STATUS_ID") 
VALUES ('TEST_ORDER','PLAN'     ,'PRODUCT'          ,'2012-11-15'   ,999           ,99              ,'LOCATION'         ,999992           ,999991);

INSERT INTO "GALADM"."PRODUCT_PRIORITY_PLAN_TBX"
       ("TRACKING_STATUS","TRACKING_SEQUENCE_NO","ORDER_NO"  ,"PRODUCT_ID"  ,"PLAN_TIMESTAMP"        ,"FORECAST_TIMESTAMP" ,"ACTUAL_TIMESTAMP"   ,"PLAN_STATUS_ID","CONTAINER_ID","CONTAINER_POS") 
VALUES ('TEST_STATUS'    ,1                     ,'TEST_ORDER','TEST_PRODUCT','2012-11-15-10.26.00.00','2012-11-16-10.00.00','2012-11-17-10.00.00',999993          ,'CONTAINER'   ,99);
