CREATE TABLE "GALADM"."HOLD_STATUS_TBX" (
  HOLD_STATUS_ID	INTEGER	NOT NULL,
  HOLD_STATUS_NAME	CHARACTER(20),
  HOLD_STATUS_DESCRIPTION	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."HOLD_STATUS_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."HOLD_STATUS_TBX" IS 'Hold Status';

ALTER TABLE "GALADM"."HOLD_STATUS_TBX" ADD CONSTRAINT "HOLD_STATUS_PK" PRIMARY KEY
 ("HOLD_STATUS_ID");

CREATE TRIGGER "GALADM"."HOLD_STATUS_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."HOLD_STATUS_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."HOLD_STATUS_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."HOLD_STATUS_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."HOLD_STATUS_TBX" TO GROUP "GALCQA_A";

GRANT SELECT ON TABLE "GALADM"."HOLD_STATUS_TBX" TO GROUP "GALCQA_S";

COMMIT;
