CREATE TABLE "GALADM"."MBPN_PRODUCT_TBX" (
  PRODUCT_ID	CHARACTER(17)	NOT NULL,
  CURRENT_PRODUCT_SPEC_CODE	CHARACTER(30),
  CURRENT_ORDER_NO	CHARACTER(20),
  TRACKING_STATUS	CHARACTER(16),
  LAST_PASSING_PROCESS_POINT	CHARACTER(16),
  TRACKING_SEQ	DOUBLE,
  HOLD_STATUS_ID	INTEGER,
  PRODUCT_STATUS_ID	INTEGER,
  CONTAINER_ID		CHARACTER(17),
  CONTAINER_POS		INTEGER,  
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSDAT6"
  INDEX IN "GALTBSIDX2";

ALTER TABLE "GALADM"."MBPN_PRODUCT_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."MBPN_PRODUCT_TBX" IS 'MBPN_PRODUCT';
COMMENT ON COLUMN "GALADM"."MBPN_PRODUCT_TBX"."HOLD_STATUS_ID" IS 'Link to HOLD_STATUS_TBX';
COMMENT ON COLUMN "GALADM"."MBPN_PRODUCT_TBX"."PRODUCT_STATUS_ID" IS 'Link to PRODUCT_STATUS_TBX';

ALTER TABLE "GALADM"."MBPN_PRODUCT_TBX" ADD CONSTRAINT "MBPN_PRODUCT_PK" PRIMARY KEY
 ("PRODUCT_ID");

CREATE TRIGGER "GALADM"."MBPN_PRODUCT_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."MBPN_PRODUCT_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."MBPN_PRODUCT_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."MBPN_PRODUCT_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."MBPN_PRODUCT_TBX" TO GROUP "GALCQA_A";

GRANT SELECT ON TABLE "GALADM"."MBPN_PRODUCT_TBX" TO GROUP "GALCQA_S";

COMMIT;
