ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE NONE; 
   
ALTER TABLE GALADM.GAL215TBX  
  ALTER COLUMN PRODUCT_SPEC_CODE  
    SET DATA TYPE CHARACTER(30); 
     
ALTER TABLE GALADM.GAL215TBX 
  DATA CAPTURE CHANGES; 

REORG TABLE GALADM.GAL215TBX;
REORG INDEXES ALL FOR TABLE GALADM.GAL215TBX;

DROP TRIGGER GALADM.GAL215TR2;
DROP TRIGGER GALADM.GAL215TR1;

CREATE TRIGGER GALADM.GAL215_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL215_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL215TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  ALTER COLUMN HOST_IP
    SET DATA TYPE VARCHAR (255)
  ALTER COLUMN HOST_PORT
    SET DATA TYPE INTEGER
  ALTER COLUMN DESCRIPTION
    DROP DEFAULT;

ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.NOTIFICATION_PROVIDER_TBX;
REORG INDEXES ALL FOR TABLE GALADM.NOTIFICATION_PROVIDER_TBX;

DROP TRIGGER GALADM.NOTIF_PRO_TR2;
DROP TRIGGER GALADM.NOTIF_PRO_TR1;

CREATE TRIGGER GALADM.NOTIF_PRO_TR1
   NO CASCADE BEFORE INSERT
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.NOTIF_PRO_TR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.NOTIFICATION_PROVIDER_TBX
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

COMMENT ON TABLE GALADM.NOTIFICATION_PROVIDER_TBX IS
   'RMT NotificationProvider for managing hosts setup for asynchronous communication';

DROP TRIGGER GALADM.HCMREQUIREDPARTSTR2;
DROP TRIGGER GALADM.HCMREQUIREDPARTSTR1;
DROP TRIGGER GALADM.HCMSEQUENCETR2;
DROP TRIGGER GALADM.HCMSEQUENCETR1;
