package com.honda.galc.entity.enumtype;

import org.apache.commons.lang.StringUtils;

public enum OifRunStatus  {

	FAILURE,
	SUCCESS,
	COMPLETE_WITH_ERRORS,	
	NO_FILE_RECEIVED,
	NO_RECORDS_IN_RECEIVED_FILE,
	NO_DETAIL_RECORDS_IN_RECEIVED_FILE,
	NO_MESSAGE_RECEIVED,
	MQ_ERROR,
	MQ_ERROR_READING_MESSAGE,
	MQ_ERROR_WHILE_TRYING_TO_POST_MESSAGE,
	MQ_ERROR_SENDING_FILE,
	MQ_ERROR_CLOSING_CONNECTION,
	EXPORT_PATH_NOT_FOUND,
	MISSING_CONFIGURATION,
	FILE_TRANSFER_ERROR, 
	FILE_CREATE_ERROR,
	FILE_CLOSE_ERROR,
	FTP_FILE_NOT_FOUND,
	INVALID_FILE_FORMAT,
	FAILED_TO_CLOSE_INPUT_STREAM,
	ERROR_WHILE_FORMATING_DATA,
	//custom statuses
	//Replicate Schedule job
	TAIL_NOT_FOUND,
	LOT_ALREADY_EXISTS,
	//GPP631
	CREATE_MBPN_FAIL,
	DUPLICATE_ORDER,
	DELETE_MBPN_FAIL,
	DELETE_PRODUCT_STAMPING_FAIL,
	INCORRECT_PLAN_CODE,
	PRE_PRODUCTION_LOT_NOT_FOUND,
	MULTIPLE_NEXT_PRODUCTION_LOT_WITH_NULL,
	//IPU FTP
	IPU_FTP_ERROR_CREATING_FILE,
	IPU_FTP_ERROR_CLOSING_FILE,
	//XM Radio
	NO_GROUP_CONFIGURED_FOR_PART,
	//GPCS Jobs
	NO_RECORDS_FOUND_FOR_PLAN_CODE,
	NO_RECORDS_FOUND_FOR_LINE,
	//AHM Jobs
	ERROR_PROCESSING_AHM_MESSAGE,
	ERROR_SENDING_MESSAGE_TO_BACKUP_QUEUE,
	VIN_DOES_NOT_HAVE_PRICE,
	//Engine Manifest
	MISSING_ENGINE,
	MISSING_AF_OFF_DATE,
	MISSING_KEY_NUMBER,
	MISSING_FIF_CODE,
	ATLEAST_ONE_ENGINE_SERIAL_MISSING,
	NO_EXISTING_FRAME_FOR_GIVEN_KD_LOT,
	ENGINE_DOES_NOT_MATCH_ASSIGNED_NO,
	//Engine master spec
	MISSING_PRIMARY_KEY,
	//Vin In VQ
	UNEXPECTED_EXCEPTION,
	MISSING_ENGINE_CODE,
	MISSING_ENGINE_TYPE,
	MISSING_ENGINE_OPTION,
	//FRAME PRIORITY PLAN
	CREATE_ENGINE_FAIL,
	FAIL_TO_PARSE_ENGINE,
	CREATE_FRAME_FAIL,
	NO_FRAME_SPEC,
	INVALID_DIGIT_CHARACTER,
	//GIV730
	LOT_NO_FOUND,
	//GPP631
	INCORRECT_TAIL_FOR_ATLEAST_ONE_PLAN,
	RECORDS_MISSING_FOR_CONFIGURED_PLAN_CODE,
	DUPLICATE_ORDER_FOUND_IN_FILE,
	//DISTRIBUTION Jobs
	DISTRIBUTION_MESSAGE_FAILED
	;
	

	public static OifRunStatus get(String name) throws IllegalArgumentException {
		if (name == null) {
			throw new IllegalArgumentException("Not a valid Operation Efficiency Status");
		}
		return Enum.valueOf(OifRunStatus.class, StringUtils.trimToEmpty(name));
	}
}