ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE NONE;

ALTER TABLE GALADM.GAL125TBX_AUD
  ADD COLUMN OLD_PART_GROUP_NAME CHARACTER(20)
  ADD COLUMN NEW_PART_GROUP_NAME CHARACTER(20);

ALTER TABLE GALADM.GAL125TBX_AUD
  DATA CAPTURE CHANGES;

REORG TABLE GALADM.GAL125TBX_AUD;
REORG INDEXES ALL FOR TABLE GALADM.GAL125TBX_AUD;

DROP TRIGGER GALADM.GAL125AUDTR2;
DROP TRIGGER GALADM.GAL125AUDTR1;

CREATE TRIGGER GALADM.GAL125AUDTR1
   NO CASCADE BEFORE INSERT
   ON GALADM.GAL125TBX_AUD
   REFERENCING NEW AS A
   FOR EACH ROW
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER GALADM.GAL125AUDTR2
   NO CASCADE BEFORE UPDATE
   ON GALADM.GAL125TBX_AUD
   REFERENCING NEW AS A
   FOR EACH ROW
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;
