--SmartBear 382
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE NONE;
  
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX 
  ALTER COLUMN HOST_PORT 
    SET DATA TYPE INTEGER;
    
ALTER TABLE GALADM.NOTIFICATION_PROVIDER_TBX
  DATA CAPTURE CHANGES;
    