//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 06:29:12 AM CST 
//


package com.honda.galc.service.qwx.namespace;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dexscription of a feature
 * 
 * <p>Java class for FeatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sciemetric.com/namespace}ElementDefinitionType">
 *       &lt;sequence>
 *         &lt;element name="date_stamp" type="{http://www.sciemetric.com/namespace}QW_datetime"/>
 *         &lt;element name="data" type="{http://www.sciemetric.com/namespace}DataType"/>
 *         &lt;element name="analysis_region" type="{http://www.sciemetric.com/namespace}AnalysisType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureType", propOrder = {
    "dateStamp",
    "data",
    "analysisRegion"
})
public class FeatureType
    extends ElementDefinitionType
{

    @XmlElement(name = "date_stamp", required = true)
    protected XMLGregorianCalendar dateStamp;
    @XmlElement(required = true)
    protected DataType data;
    @XmlElement(name = "analysis_region")
    protected AnalysisType analysisRegion;

    /**
     * Gets the value of the dateStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStamp() {
        return dateStamp;
    }

    /**
     * Sets the value of the dateStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStamp(XMLGregorianCalendar value) {
        this.dateStamp = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setData(DataType value) {
        this.data = value;
    }

    /**
     * Gets the value of the analysisRegion property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisType }
     *     
     */
    public AnalysisType getAnalysisRegion() {
        return analysisRegion;
    }

    /**
     * Sets the value of the analysisRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisType }
     *     
     */
    public void setAnalysisRegion(AnalysisType value) {
        this.analysisRegion = value;
    }

}
