//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 06:29:12 AM CST 
//


package com.honda.galc.service.qwx.namespace;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.honda.galc.service.qwx.namespace package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnalysisTypeLimitsFormatLower_QNAME = new QName("http://www.sciemetric.com/namespace", "format_lower");
    private final static QName _AnalysisTypeLimitsLower_QNAME = new QName("http://www.sciemetric.com/namespace", "lower");
    private final static QName _AnalysisTypeLimitsUpper_QNAME = new QName("http://www.sciemetric.com/namespace", "upper");
    private final static QName _AnalysisTypeLimitsFormatUpper_QNAME = new QName("http://www.sciemetric.com/namespace", "format_upper");
    private final static QName _AnalysisTypeRangeFormatStart_QNAME = new QName("http://www.sciemetric.com/namespace", "format_start");
    private final static QName _AnalysisTypeRangeStop_QNAME = new QName("http://www.sciemetric.com/namespace", "stop");
    private final static QName _AnalysisTypeRangeFormatStop_QNAME = new QName("http://www.sciemetric.com/namespace", "format_stop");
    private final static QName _AnalysisTypeRangeStart_QNAME = new QName("http://www.sciemetric.com/namespace", "start");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.honda.galc.service.qwx.namespace
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link OperationType.StatusBits }
     * 
     */
    public OperationType.StatusBits createOperationTypeStatusBits() {
        return new OperationType.StatusBits();
    }

    /**
     * Create an instance of {@link CatalogItemsType }
     * 
     */
    public CatalogItemsType createCatalogItemsType() {
        return new CatalogItemsType();
    }

    /**
     * Create an instance of {@link WaveformType }
     * 
     */
    public WaveformType createWaveformType() {
        return new WaveformType();
    }

    /**
     * Create an instance of {@link AnalysisType }
     * 
     */
    public AnalysisType createAnalysisType() {
        return new AnalysisType();
    }

    /**
     * Create an instance of {@link StationType }
     * 
     */
    public StationType createStationType() {
        return new StationType();
    }

    /**
     * Create an instance of {@link Root.SinglePart }
     * 
     */
    public Root.SinglePart createRootSinglePart() {
        return new Root.SinglePart();
    }

    /**
     * Create an instance of {@link Root.SinglePart.Information }
     * 
     */
    public Root.SinglePart.Information createRootSinglePartInformation() {
        return new Root.SinglePart.Information();
    }

    /**
     * Create an instance of {@link Root.BinaryCatalog }
     * 
     */
    public Root.BinaryCatalog createRootBinaryCatalog() {
        return new Root.BinaryCatalog();
    }

    /**
     * Create an instance of {@link Root.Gateways }
     * 
     */
    public Root.Gateways createRootGateways() {
        return new Root.Gateways();
    }

    /**
     * Create an instance of {@link ImageType }
     * 
     */
    public ImageType createImageType() {
        return new ImageType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link ElementDefinitionType }
     * 
     */
    public ElementDefinitionType createElementDefinitionType() {
        return new ElementDefinitionType();
    }

    /**
     * Create an instance of {@link PartType }
     * 
     */
    public PartType createPartType() {
        return new PartType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link RepairType }
     * 
     */
    public RepairType createRepairType() {
        return new RepairType();
    }

    /**
     * Create an instance of {@link DefectsType }
     * 
     */
    public DefectsType createDefectsType() {
        return new DefectsType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link DataPointType }
     * 
     */
    public DataPointType createDataPointType() {
        return new DataPointType();
    }

    /**
     * Create an instance of {@link EnvelopeType }
     * 
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link ComponentComplexityType }
     * 
     */
    public ComponentComplexityType createComponentComplexityType() {
        return new ComponentComplexityType();
    }

    /**
     * Create an instance of {@link PartParametersType }
     * 
     */
    public PartParametersType createPartParametersType() {
        return new PartParametersType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link WaveformsType }
     * 
     */
    public WaveformsType createWaveformsType() {
        return new WaveformsType();
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link GatewayDataType }
     * 
     */
    public GatewayDataType createGatewayDataType() {
        return new GatewayDataType();
    }

    /**
     * Create an instance of {@link RepairStationType }
     * 
     */
    public RepairStationType createRepairStationType() {
        return new RepairStationType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link SectionsType }
     * 
     */
    public SectionsType createSectionsType() {
        return new SectionsType();
    }

    /**
     * Create an instance of {@link WaveformScaleType }
     * 
     */
    public WaveformScaleType createWaveformScaleType() {
        return new WaveformScaleType();
    }

    /**
     * Create an instance of {@link ComponentComplexitiesType }
     * 
     */
    public ComponentComplexitiesType createComponentComplexitiesType() {
        return new ComponentComplexitiesType();
    }

    /**
     * Create an instance of {@link OperationsType }
     * 
     */
    public OperationsType createOperationsType() {
        return new OperationsType();
    }

    /**
     * Create an instance of {@link BuildComplexityType }
     * 
     */
    public BuildComplexityType createBuildComplexityType() {
        return new BuildComplexityType();
    }

    /**
     * Create an instance of {@link RepairsType }
     * 
     */
    public RepairsType createRepairsType() {
        return new RepairsType();
    }

    /**
     * Create an instance of {@link ImagesType }
     * 
     */
    public ImagesType createImagesType() {
        return new ImagesType();
    }

    /**
     * Create an instance of {@link ResultType }
     * 
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link DataHeaderType }
     * 
     */
    public DataHeaderType createDataHeaderType() {
        return new DataHeaderType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link ShiftType }
     * 
     */
    public ShiftType createShiftType() {
        return new ShiftType();
    }

    /**
     * Create an instance of {@link DefectType }
     * 
     */
    public DefectType createDefectType() {
        return new DefectType();
    }

    /**
     * Create an instance of {@link PartParameterType }
     * 
     */
    public PartParameterType createPartParameterType() {
        return new PartParameterType();
    }

    /**
     * Create an instance of {@link WaveformDataType }
     * 
     */
    public WaveformDataType createWaveformDataType() {
        return new WaveformDataType();
    }

    /**
     * Create an instance of {@link BuildComplexitiesType }
     * 
     */
    public BuildComplexitiesType createBuildComplexitiesType() {
        return new BuildComplexitiesType();
    }

    /**
     * Create an instance of {@link StationsType }
     * 
     */
    public StationsType createStationsType() {
        return new StationsType();
    }

    /**
     * Create an instance of {@link OperatorType }
     * 
     */
    public OperatorType createOperatorType() {
        return new OperatorType();
    }

    /**
     * Create an instance of {@link OperationType.StatusBits.StatusBit }
     * 
     */
    public OperationType.StatusBits.StatusBit createOperationTypeStatusBitsStatusBit() {
        return new OperationType.StatusBits.StatusBit();
    }

    /**
     * Create an instance of {@link CatalogItemsType.Data }
     * 
     */
    public CatalogItemsType.Data createCatalogItemsTypeData() {
        return new CatalogItemsType.Data();
    }

    /**
     * Create an instance of {@link WaveformType.Nominal }
     * 
     */
    public WaveformType.Nominal createWaveformTypeNominal() {
        return new WaveformType.Nominal();
    }

    /**
     * Create an instance of {@link AnalysisType.Range }
     * 
     */
    public AnalysisType.Range createAnalysisTypeRange() {
        return new AnalysisType.Range();
    }

    /**
     * Create an instance of {@link AnalysisType.Limits }
     * 
     */
    public AnalysisType.Limits createAnalysisTypeLimits() {
        return new AnalysisType.Limits();
    }

    /**
     * Create an instance of {@link StationType.Type }
     * 
     */
    public StationType.Type createStationTypeType() {
        return new StationType.Type();
    }

    /**
     * Create an instance of {@link Root.SinglePart.BirthHistory }
     * 
     */
    public Root.SinglePart.BirthHistory createRootSinglePartBirthHistory() {
        return new Root.SinglePart.BirthHistory();
    }

    /**
     * Create an instance of {@link Root.SinglePart.Information.Source }
     * 
     */
    public Root.SinglePart.Information.Source createRootSinglePartInformationSource() {
        return new Root.SinglePart.Information.Source();
    }

    /**
     * Create an instance of {@link Root.SinglePart.Information.Database }
     * 
     */
    public Root.SinglePart.Information.Database createRootSinglePartInformationDatabase() {
        return new Root.SinglePart.Information.Database();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "format_lower", scope = AnalysisType.Limits.class)
    public JAXBElement<String> createAnalysisTypeLimitsFormatLower(String value) {
        return new JAXBElement<String>(_AnalysisTypeLimitsFormatLower_QNAME, String.class, AnalysisType.Limits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "lower", scope = AnalysisType.Limits.class)
    public JAXBElement<Float> createAnalysisTypeLimitsLower(Float value) {
        return new JAXBElement<Float>(_AnalysisTypeLimitsLower_QNAME, Float.class, AnalysisType.Limits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "upper", scope = AnalysisType.Limits.class)
    public JAXBElement<Float> createAnalysisTypeLimitsUpper(Float value) {
        return new JAXBElement<Float>(_AnalysisTypeLimitsUpper_QNAME, Float.class, AnalysisType.Limits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "format_upper", scope = AnalysisType.Limits.class)
    public JAXBElement<String> createAnalysisTypeLimitsFormatUpper(String value) {
        return new JAXBElement<String>(_AnalysisTypeLimitsFormatUpper_QNAME, String.class, AnalysisType.Limits.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "format_start", scope = AnalysisType.Range.class)
    public JAXBElement<String> createAnalysisTypeRangeFormatStart(String value) {
        return new JAXBElement<String>(_AnalysisTypeRangeFormatStart_QNAME, String.class, AnalysisType.Range.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "stop", scope = AnalysisType.Range.class)
    public JAXBElement<Float> createAnalysisTypeRangeStop(Float value) {
        return new JAXBElement<Float>(_AnalysisTypeRangeStop_QNAME, Float.class, AnalysisType.Range.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "format_stop", scope = AnalysisType.Range.class)
    public JAXBElement<String> createAnalysisTypeRangeFormatStop(String value) {
        return new JAXBElement<String>(_AnalysisTypeRangeFormatStop_QNAME, String.class, AnalysisType.Range.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sciemetric.com/namespace", name = "start", scope = AnalysisType.Range.class)
    public JAXBElement<Float> createAnalysisTypeRangeStart(Float value) {
        return new JAXBElement<Float>(_AnalysisTypeRangeStart_QNAME, Float.class, AnalysisType.Range.class, value);
    }

}
