//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 06:29:12 AM CST 
//


package com.honda.galc.service.qwx.namespace;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Description of an operation
 * 
 * <p>Java class for OperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.sciemetric.com/namespace}ElementDefinitionType">
 *       &lt;sequence>
 *         &lt;element name="data_id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
 *         &lt;element name="date_stamp" type="{http://www.sciemetric.com/namespace}QW_datetime"/>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="shift" type="{http://www.sciemetric.com/namespace}ShiftType" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="operator" type="{http://www.sciemetric.com/namespace}OperatorType" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="version_name" type="{http://www.sciemetric.com/namespace}QW_filename"/>
 *           &lt;element name="version_number" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="version_date" type="{http://www.sciemetric.com/namespace}QW_datetime" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="status_value" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *           &lt;element name="status_bits" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="status_bit" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="label" type="{http://www.sciemetric.com/namespace}QW_label"/>
 *                               &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="result_id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="defects" type="{http://www.sciemetric.com/namespace}DefectsType" minOccurs="0"/>
 *         &lt;element name="images" type="{http://www.sciemetric.com/namespace}ImagesType" minOccurs="0"/>
 *         &lt;element name="waveforms" type="{http://www.sciemetric.com/namespace}WaveformsType" minOccurs="0"/>
 *         &lt;element name="features" type="{http://www.sciemetric.com/namespace}FeaturesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationType", propOrder = {
    "dataId",
    "dateStamp",
    "count",
    "shift",
    "comment",
    "operator",
    "versionName",
    "versionNumber",
    "versionDate",
    "statusValue",
    "statusBits",
    "defects",
    "images",
    "waveforms",
    "features"
})
public class OperationType
    extends ElementDefinitionType
{

    @XmlElement(name = "data_id")
    protected BigInteger dataId;
    @XmlElement(name = "date_stamp", required = true)
    protected XMLGregorianCalendar dateStamp;
    @XmlElement(required = true)
    protected BigInteger count;
    protected ShiftType shift;
    protected Object comment;
    protected OperatorType operator;
    @XmlElement(name = "version_name")
    protected String versionName;
    @XmlElement(name = "version_number")
    protected Object versionNumber;
    @XmlElement(name = "version_date")
    protected XMLGregorianCalendar versionDate;
    @XmlElement(name = "status_value")
    @XmlSchemaType(name = "unsignedInt")
    protected Long statusValue;
    @XmlElement(name = "status_bits")
    protected OperationType.StatusBits statusBits;
    protected DefectsType defects;
    protected ImagesType images;
    protected WaveformsType waveforms;
    protected FeaturesType features;

    /**
     * Gets the value of the dataId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataId() {
        return dataId;
    }

    /**
     * Sets the value of the dataId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataId(BigInteger value) {
        this.dataId = value;
    }

    /**
     * Gets the value of the dateStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateStamp() {
        return dateStamp;
    }

    /**
     * Sets the value of the dateStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateStamp(XMLGregorianCalendar value) {
        this.dateStamp = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the shift property.
     * 
     * @return
     *     possible object is
     *     {@link ShiftType }
     *     
     */
    public ShiftType getShift() {
        return shift;
    }

    /**
     * Sets the value of the shift property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShiftType }
     *     
     */
    public void setShift(ShiftType value) {
        this.shift = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setComment(Object value) {
        this.comment = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorType }
     *     
     */
    public OperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorType }
     *     
     */
    public void setOperator(OperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the versionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * Sets the value of the versionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionName(String value) {
        this.versionName = value;
    }

    /**
     * Gets the value of the versionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVersionNumber(Object value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the versionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVersionDate() {
        return versionDate;
    }

    /**
     * Sets the value of the versionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVersionDate(XMLGregorianCalendar value) {
        this.versionDate = value;
    }

    /**
     * Gets the value of the statusValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStatusValue() {
        return statusValue;
    }

    /**
     * Sets the value of the statusValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStatusValue(Long value) {
        this.statusValue = value;
    }

    /**
     * Gets the value of the statusBits property.
     * 
     * @return
     *     possible object is
     *     {@link OperationType.StatusBits }
     *     
     */
    public OperationType.StatusBits getStatusBits() {
        return statusBits;
    }

    /**
     * Sets the value of the statusBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationType.StatusBits }
     *     
     */
    public void setStatusBits(OperationType.StatusBits value) {
        this.statusBits = value;
    }

    /**
     * Gets the value of the defects property.
     * 
     * @return
     *     possible object is
     *     {@link DefectsType }
     *     
     */
    public DefectsType getDefects() {
        return defects;
    }

    /**
     * Sets the value of the defects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefectsType }
     *     
     */
    public void setDefects(DefectsType value) {
        this.defects = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link ImagesType }
     *     
     */
    public ImagesType getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagesType }
     *     
     */
    public void setImages(ImagesType value) {
        this.images = value;
    }

    /**
     * Gets the value of the waveforms property.
     * 
     * @return
     *     possible object is
     *     {@link WaveformsType }
     *     
     */
    public WaveformsType getWaveforms() {
        return waveforms;
    }

    /**
     * Sets the value of the waveforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaveformsType }
     *     
     */
    public void setWaveforms(WaveformsType value) {
        this.waveforms = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesType }
     *     
     */
    public FeaturesType getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesType }
     *     
     */
    public void setFeatures(FeaturesType value) {
        this.features = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="status_bit" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="label" type="{http://www.sciemetric.com/namespace}QW_label"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="result_id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statusBit"
    })
    public static class StatusBits {

        @XmlElement(name = "status_bit", required = true)
        protected List<OperationType.StatusBits.StatusBit> statusBit;

        /**
         * Gets the value of the statusBit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the statusBit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStatusBit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OperationType.StatusBits.StatusBit }
         * 
         * 
         */
        public List<OperationType.StatusBits.StatusBit> getStatusBit() {
            if (statusBit == null) {
                statusBit = new ArrayList<OperationType.StatusBits.StatusBit>();
            }
            return this.statusBit;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="label" type="{http://www.sciemetric.com/namespace}QW_label"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="result_id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "label",
            "value",
            "resultId"
        })
        public static class StatusBit {

            @XmlElement(required = true)
            protected String label;
            protected boolean value;
            @XmlElement(name = "result_id")
            protected BigInteger resultId;

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

            /**
             * Gets the value of the resultId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getResultId() {
                return resultId;
            }

            /**
             * Sets the value of the resultId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setResultId(BigInteger value) {
                this.resultId = value;
            }

        }

    }

}
