//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 06:29:12 AM CST 
//


package com.honda.galc.service.qwx.namespace;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Description of a part
 * 
 * <p>Java class for PartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.sciemetric.com/namespace}QW_part"/>
 *         &lt;element name="description" type="{http://www.sciemetric.com/namespace}QW_description" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
 *         &lt;element name="unit_id" type="{http://www.sciemetric.com/namespace}QW_id" minOccurs="0"/>
 *         &lt;element name="archive" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.sciemetric.com/namespace}QW_filename">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="serial_number" type="{http://www.sciemetric.com/namespace}QW_serialnumber"/>
 *         &lt;element name="model_number" type="{http://www.sciemetric.com/namespace}ModelType" minOccurs="0"/>
 *         &lt;element name="pallet_number" type="{http://www.sciemetric.com/namespace}QW_serialnumber" minOccurs="0"/>
 *         &lt;element name="rbm_repair_state" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="rbm_time_in_bay" type="{http://www.sciemetric.com/namespace}QW_datetime" minOccurs="0"/>
 *         &lt;element name="rbm_loop_count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="part_parameters" type="{http://www.sciemetric.com/namespace}PartParametersType" minOccurs="0"/>
 *         &lt;element name="build_complexities" type="{http://www.sciemetric.com/namespace}BuildComplexitiesType" minOccurs="0"/>
 *         &lt;element name="component_complexities" type="{http://www.sciemetric.com/namespace}ComponentComplexitiesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartType", propOrder = {
    "label",
    "description",
    "id",
    "unitId",
    "archive",
    "serialNumber",
    "modelNumber",
    "palletNumber",
    "rbmRepairState",
    "rbmTimeInBay",
    "rbmLoopCount",
    "partParameters",
    "buildComplexities",
    "componentComplexities"
})
public class PartType {

    @XmlElement(required = true)
    protected String label;
    protected String description;
    protected BigInteger id;
    @XmlElement(name = "unit_id")
    protected BigInteger unitId;
    protected String archive;
    @XmlElement(name = "serial_number", required = true)
    protected String serialNumber;
    @XmlElement(name = "model_number")
    protected ModelType modelNumber;
    @XmlElement(name = "pallet_number")
    protected String palletNumber;
    @XmlElement(name = "rbm_repair_state")
    protected BigInteger rbmRepairState;
    @XmlElement(name = "rbm_time_in_bay")
    protected XMLGregorianCalendar rbmTimeInBay;
    @XmlElement(name = "rbm_loop_count")
    protected BigInteger rbmLoopCount;
    @XmlElement(name = "part_parameters")
    protected PartParametersType partParameters;
    @XmlElement(name = "build_complexities")
    protected BuildComplexitiesType buildComplexities;
    @XmlElement(name = "component_complexities")
    protected ComponentComplexitiesType componentComplexities;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the unitId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnitId() {
        return unitId;
    }

    /**
     * Sets the value of the unitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnitId(BigInteger value) {
        this.unitId = value;
    }

    /**
     * Gets the value of the archive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchive() {
        return archive;
    }

    /**
     * Sets the value of the archive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchive(String value) {
        this.archive = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the modelNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ModelType }
     *     
     */
    public ModelType getModelNumber() {
        return modelNumber;
    }

    /**
     * Sets the value of the modelNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelType }
     *     
     */
    public void setModelNumber(ModelType value) {
        this.modelNumber = value;
    }

    /**
     * Gets the value of the palletNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPalletNumber() {
        return palletNumber;
    }

    /**
     * Sets the value of the palletNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPalletNumber(String value) {
        this.palletNumber = value;
    }

    /**
     * Gets the value of the rbmRepairState property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRbmRepairState() {
        return rbmRepairState;
    }

    /**
     * Sets the value of the rbmRepairState property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRbmRepairState(BigInteger value) {
        this.rbmRepairState = value;
    }

    /**
     * Gets the value of the rbmTimeInBay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRbmTimeInBay() {
        return rbmTimeInBay;
    }

    /**
     * Sets the value of the rbmTimeInBay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRbmTimeInBay(XMLGregorianCalendar value) {
        this.rbmTimeInBay = value;
    }

    /**
     * Gets the value of the rbmLoopCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRbmLoopCount() {
        return rbmLoopCount;
    }

    /**
     * Sets the value of the rbmLoopCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRbmLoopCount(BigInteger value) {
        this.rbmLoopCount = value;
    }

    /**
     * Gets the value of the partParameters property.
     * 
     * @return
     *     possible object is
     *     {@link PartParametersType }
     *     
     */
    public PartParametersType getPartParameters() {
        return partParameters;
    }

    /**
     * Sets the value of the partParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartParametersType }
     *     
     */
    public void setPartParameters(PartParametersType value) {
        this.partParameters = value;
    }

    /**
     * Gets the value of the buildComplexities property.
     * 
     * @return
     *     possible object is
     *     {@link BuildComplexitiesType }
     *     
     */
    public BuildComplexitiesType getBuildComplexities() {
        return buildComplexities;
    }

    /**
     * Sets the value of the buildComplexities property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildComplexitiesType }
     *     
     */
    public void setBuildComplexities(BuildComplexitiesType value) {
        this.buildComplexities = value;
    }

    /**
     * Gets the value of the componentComplexities property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentComplexitiesType }
     *     
     */
    public ComponentComplexitiesType getComponentComplexities() {
        return componentComplexities;
    }

    /**
     * Sets the value of the componentComplexities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentComplexitiesType }
     *     
     */
    public void setComponentComplexities(ComponentComplexitiesType value) {
        this.componentComplexities = value;
    }

}
