CREATE TABLE "GALADM"."ORDER_STATUS_TBX" (
  ORDER_STATUS_ID	INTEGER	NOT NULL,
  ORDER_STATUS_NAME	CHARACTER(20),
  ORDER_STATUS_DESC	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
)
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."ORDER_STATUS_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."ORDER_STATUS_TBX" IS 'Order Status';

ALTER TABLE "GALADM"."ORDER_STATUS_TBX" ADD CONSTRAINT "ORDER_STATUS_PK" PRIMARY KEY
 ("ORDER_STATUS_ID");

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."ORDER_STATUS_TBX" TO GROUP "GALAPR_A";

GRANT SELECT ON TABLE "GALADM"."ORDER_STATUS_TBX" TO GROUP "GALAPR_S";

COMMIT;
