CREATE TABLE "GALADM"."ORDER_TBX" (
  ORDER_NO	CHARACTER(20)	NOT NULL,
  PLAN_CODE	CHARACTER(11)	NOT NULL,
  PRODUCT_SPEC_CODE	CHARACTER(30),
  PRIORITY_DATE	DATE,
  PRIORITY_SEQ	INTEGER,
  PROD_ORDER_QTY	INTEGER,
  LOCATION_LEVEL_ID	CHARACTER(16),
  ORDER_STATUS_ID	INTEGER,
  HOLD_STATUS_ID	INTEGER,
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSDAT7"
  INDEX IN "GALTBSIDX3";

ALTER TABLE "GALADM"."ORDER_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."ORDER_TBX" IS 'Orders';
COMMENT ON COLUMN "GALADM"."ORDER_TBX"."LOCATION_LEVEL_ID" IS 'Location Level ID is PROCESS POINT ID or LINE ID of the station(s) that manage these orders';
COMMENT ON COLUMN "GALADM"."ORDER_TBX"."ORDER_STATUS_ID" IS 'Link to ORDER_STATUS_TBX';
COMMENT ON COLUMN "GALADM"."ORDER_TBX"."HOLD_STATUS_ID" IS 'Link to HOLD_STATUS_TBX';

ALTER TABLE "GALADM"."ORDER_TBX" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY
 ("ORDER_NO", "PLAN_CODE");

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."ORDER_TBX" TO GROUP "GALAPR_A";

GRANT SELECT ON TABLE "GALADM"."ORDER_TBX" TO GROUP "GALAPR_S";

COMMIT;
