CREATE TABLE "GALADM"."PRODUCT_STATUS_TBX" (
  PRODUCT_STATUS_ID	INTEGER	NOT NULL,
  PRODUCT_STATUS_NAME	CHARACTER(20),
  PRODUCT_STATUS_DESCRIPTION	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."PRODUCT_STATUS_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PRODUCT_STATUS_TBX" IS 'PRODUCT Status';

ALTER TABLE "GALADM"."PRODUCT_STATUS_TBX" ADD CONSTRAINT "PRODUCT_STATUS_PK" PRIMARY KEY
 ("PRODUCT_STATUS_ID");

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."PRODUCT_STATUS_TBX" TO GROUP "GALAPR_A";

GRANT SELECT ON TABLE "GALADM"."PRODUCT_STATUS_TBX" TO GROUP "GALAPR_S";

COMMIT;
