-- <ScriptOptions statementTerminator="@" />
DROP TRIGGER GALADM.GAL215TR8@
DROP TRIGGER GALADM.GAL215TR9@

-- Create Insert Trigger on GAL215TBX
CREATE TRIGGER GALADM.GAL215TR8 
 AFTER INSERT ON GALADM.GAL215TBX
 REFERENCING NEW AS NEWROW
 FOR EACH ROW MODE DB2SQL
 WHEN (NEWROW.PROCESS_POINT_ID = 'PP10104')
 BEGIN ATOMIC
 IF NOT EXISTS (SELECT * FROM GALADM.HMIN_FIC_VIEWER_TBX WHERE VIN = NEWROW.PRODUCT_ID) THEN
  INSERT INTO GALADM.HMIN_FIC_VIEWER_TBX (VIN, PRODUCTION_DATE,MODEL,SHORTVIN) VALUES(NEWROW.PRODUCT_ID,coalesce(NEWROW.ACTUAL_PRODUCTION_DATE,NEWROW.ACTUAL_TIMESTAMP),SUBSTR(NEWROW.PRODUCT_SPEC_CODE,1,4),SUBSTR(NEWROW.PRODUCT_ID,12,6));
 ELSE
  UPDATE GALADM.HMIN_FIC_VIEWER_TBX SET PRODUCTION_DATE = coalesce(NEWROW.ACTUAL_PRODUCTION_DATE,NEWROW.ACTUAL_TIMESTAMP), MODEL = SUBSTR(NEWROW.PRODUCT_SPEC_CODE,1,4), SHORTVIN = SUBSTR(NEWROW.PRODUCT_ID,12,6), UPDATE_TIMESTAMP = CURRENT TIMESTAMP WHERE VIN = NEWROW.PRODUCT_ID;
 END IF;
 END@
 
-- Create Delete Trigger on GAL215TBX
CREATE TRIGGER GALADM.GAL215TR9
 AFTER DELETE ON GALADM.GAL215TBX
 REFERENCING OLD AS OLDROW
 FOR EACH ROW MODE DB2SQL
 WHEN (OLDROW.PROCESS_POINT_ID = 'PP10104')
 BEGIN ATOMIC
  DELETE FROM GALADM.HMIN_FIC_VIEWER_TBX WHERE VIN = OLDROW.PRODUCT_ID;
 END@