DROP TRIGGER "GALADM"."PRODUCT_STATUS_TR2";
DROP TRIGGER "GALADM"."PRODUCT_STATUS_TR1";
DROP TABLE "GALADM"."PRODUCT_STATUS_TBX";

CREATE TABLE "GALADM"."PRODUCT_STATUS_TBX" (
  PRODUCT_STATUS_ID	INTEGER	NOT NULL,
  PRODUCT_STATUS_NAME	CHARACTER(20),
  PRODUCT_STATUS_DESCRIPTION	VARCHAR(255),
  CREATE_TIMESTAMP	TIMESTAMP,
  UPDATE_TIMESTAMP	TIMESTAMP
) 
  IN "GALTBSREF12"
  INDEX IN "GALTBSIDX4";

ALTER TABLE "GALADM"."PRODUCT_STATUS_TBX"
  DATA CAPTURE CHANGES
  PCTFREE 0
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE;

COMMENT ON TABLE "GALADM"."PRODUCT_STATUS_TBX" IS 'PRODUCT Status';

ALTER TABLE "GALADM"."PRODUCT_STATUS_TBX" ADD CONSTRAINT "PRODUCT_STATUS_PK" PRIMARY KEY
 ("PRODUCT_STATUS_ID");

CREATE TRIGGER "GALADM"."PRODUCT_STATUS_TR1"
  NO CASCADE BEFORE INSERT
  ON "GALADM"."PRODUCT_STATUS_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET CREATE_TIMESTAMP = CURRENT_TIMESTAMP;

CREATE TRIGGER "GALADM"."PRODUCT_STATUS_TR2"
  NO CASCADE BEFORE UPDATE
  ON "GALADM"."PRODUCT_STATUS_TBX"
  REFERENCING NEW AS A
  FOR EACH ROW
  MODE DB2SQL
SET UPDATE_TIMESTAMP = CURRENT_TIMESTAMP;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "GALADM"."PRODUCT_STATUS_TBX" TO GROUP "GALCDV_A";

GRANT SELECT ON TABLE "GALADM"."PRODUCT_STATUS_TBX" TO GROUP "GALCDV_S";

COMMIT;
