--Create alias to current HMIN tables to minimize risk of conversion.  Once all QICS stations are converted then will create the new tables and remove this alias and the HMIN tables
CREATE ALIAS GALADM.DEFECT_ACTUAL_PROBLEM_TBX FOR GALADM.HMIN_ACTUAL_PROBLEMS_TBX;
COMMENT ON ALIAS GALADM.DEFECT_ACTUAL_PROBLEM_TBX IS 'RMT alias to HMIN_ACTUAL_PROBLEMS_TBX';

CREATE ALIAS GALADM.DEFECT_REPAIR_METHOD_TBX FOR GALADM.HMIN_REPAIR_METHODS_TBX;
COMMENT ON ALIAS GALADM.DEFECT_REPAIR_METHOD_TBX IS 'RMT alias to HMIN_REPAIR_METHODS_TBX';