//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.honda.galc.wsdl.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.honda.galc.util.ToStringUtil;


/**
 * <p>Java class for frameInfoDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="frameInfoDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="currentLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fifCodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="minsOnLine" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productSpecCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "frameInfoDto", namespace = "http://service.web.galc.honda.com/", propOrder = {
    "currentLine",
    "fifCodes",
    "minsOnLine",
    "productId",
    "productSpecCode"
})
public class FrameInfoDto {

    protected String currentLine;
    protected String fifCodes;
    protected long minsOnLine;
    protected String productId;
    protected String productSpecCode;

    /**
     * Gets the value of the currentLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentLine() {
        return currentLine;
    }

    /**
     * Sets the value of the currentLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentLine(String value) {
        this.currentLine = value;
    }

    /**
     * Gets the value of the fifCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFifCodes() {
        return fifCodes;
    }

    /**
     * Sets the value of the fifCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFifCodes(String value) {
        this.fifCodes = value;
    }

    /**
     * Gets the value of the minsOnLine property.
     * 
     */
    public long getMinsOnLine() {
        return minsOnLine;
    }

    /**
     * Sets the value of the minsOnLine property.
     * 
     */
    public void setMinsOnLine(long value) {
        this.minsOnLine = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productSpecCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSpecCode() {
        return productSpecCode;
    }

    /**
     * Sets the value of the productSpecCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSpecCode(String value) {
        this.productSpecCode = value;
    }
    
    public String toString() {
    	return ToStringUtil.generateJsonToString(this);
    }
}
