//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.honda.galc.wsdl.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "PlantProgressService", targetNamespace = "http://service.web.galc.honda.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlantProgressService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.honda.galc.wsdl.client.PushTimerStatusDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProgress", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetProgress")
    @ResponseWrapper(localName = "getProgressResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetProgressResponse")
    public List<PushTimerStatusDto> getProgress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.util.List<com.honda.galc.wsdl.client.PushTimerStatusDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTopLaggingProcessPoints", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetTopLaggingProcessPoints")
    @ResponseWrapper(localName = "getTopLaggingProcessPointsResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetTopLaggingProcessPointsResponse")
    public List<PushTimerStatusDto> getTopLaggingProcessPoints(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentInventory", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetCurrentInventory")
    @ResponseWrapper(localName = "getCurrentInventoryResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetCurrentInventoryResponse")
    public int getCurrentInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgedInventory", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetAgedInventory")
    @ResponseWrapper(localName = "getAgedInventoryResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetAgedInventoryResponse")
    public int getAgedInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.util.List<com.honda.galc.wsdl.client.OpEfficiencyDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptUnitEfficiency", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetDeptUnitEfficiency")
    @ResponseWrapper(localName = "getDeptUnitEfficiencyResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetDeptUnitEfficiencyResponse")
    public List<OpEfficiencyDto> getDeptUnitEfficiency(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.util.List<com.honda.galc.wsdl.client.OpEfficiencyDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPPUnitEfficiency", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetPPUnitEfficiency")
    @ResponseWrapper(localName = "getPPUnitEfficiencyResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetPPUnitEfficiencyResponse")
    public List<OpEfficiencyDto> getPPUnitEfficiency(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns com.honda.galc.wsdl.client.FrameInfoDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFrameInfo", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetFrameInfo")
    @ResponseWrapper(localName = "getFrameInfoResponse", targetNamespace = "http://service.web.galc.honda.com/", className = "com.honda.galc.wsdl.client.GetFrameInfoResponse")
    public FrameInfoDto getFrameInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
